### ISSUE TITLE
Allow overlay in modal

### ISSUE THREAD

**Issue by jbouzekri** [ColorlibHQ/AdminLTE#1066]
It would be great to be able to use the overlay feature in a modal (the one in the widget which simulate a loading animation blocking the UI).

**Comment by almasaeed2010** [comment]
We'll put that into consideration. Thanks!

**Comment by perseacado** [comment]
+1

**Comment by yakuzaaaa** [comment]
was this done?

**Comment by bluemanos** [comment]
Bump up :)

**Comment by Alisovsky** [comment]
+1

**Comment by marcelogarbin** [comment]
any news?

**Comment by almasaeed2010** [comment]
Bumping this up to be added in v3.

- [ ] Add loading overlay in Modal

**Comment by REJack** [comment]
This issue is fixed with #2123, you can test it on https://adminlte-dev.rejack.space/pages/UI/modals.html (click on `Launch Modal with Overlay`).
