### ISSUE TITLE
RTL support for Arabic languages

### ISSUE THREAD

**Issue by sujit223** [ColorlibHQ/AdminLTE#1116]
Hi Team,
Thanks for your wonderful job.
One issue i am facing is **RTL** support with some languages.
Is there a proper way to solve the **RTL** issue through out the whole project. 
Also can we set it for a particular div.
Setting it to a particular div would help us not to change the complete UI of the application but only to some part which are very necessary.

**Comment by BassemN** [comment]
:+1:

**Comment by ramajd** [comment]
:+1:

**Comment by Farshadi73** [comment]
And of Course for Persian Languages :+1:

**Comment by sneetsher** [comment]
Well, I'm an Arabic user but it is too early to fix this here. While a fundamental library (Bootstrap) does not offer such support for RTL languages. Trying to implement it directly here, much effort and code to put just to override Bootstrap LTR defaults/code.

Current plan for  RTL support dropped from Bootstrap 4.1 .

Patient my friends. If you know some high-lvl developers to help, motivated them to contribute to such basic libraries.

**Comment by almasaeed2010** [comment]
We are working to add minimal RTL support in that the layout will be converted to RTL but inner components will need custom code to support. In that case, it will be the developer's responsibility to override defaults as needed.

- [ ] Add minimal RTL support

**Comment by REJack** [comment]
I close this issue due a new RTL Support issue, see #2236.
