### ISSUE TITLE
main-fotter visual bug (refreshing page)

### ISSUE THREAD

**Issue by ntavb** [ColorlibHQ/AdminLTE#1156]
When i refresh my page, i have this visual bug with the footer:

[https://i.gyazo.com/7736c9ffd943ac89df4e6dbcc34ceb62.gif](https://i.gyazo.com/7736c9ffd943ac89df4e6dbcc34ceb62.gif)

For few mili seconds, the footer goes up and after, goes down. I have all the css and the JS files included like in the starter.html.

I don't understand, please help. (I saw the same bug on few AdminLTE site, but not all)

**Comment by hfishere** [comment]
Yes, i have same problem..

**Comment by tkisme** [comment]
still not fixed adminlte#^2.3.6

**Comment by REJack** [comment]
Hi guys did you tried these on Chrome or Firefox?

I'd helped @cdecker15 with his issue and we noticed thats only happend to Chrome, Edge & Internet Explorer 11 but not to Firefox

**Comment by lenamtl** [comment]
I'm not sure but I think I fixed this problem by adding a minimum height the the main container.
I'm using Chrome

**Comment by franciscomasi** [comment]
I have the same problem in my application using rails 5.2 and bower. Default rails application use turbolinks, comment this in application.js worked for me.

```
//= require rails-ujs
// require turbolinks
//= require jquery
//= require jquery_ujs
//= require bootstrap/dist/js/bootstrap
//= require admin-lte/plugins/iCheck/icheck
//= require admin-lte/dist/js/adminlte
//= require chart.js/Chart
//= require_tree .
```

**Comment by almasaeed2010** [comment]
Is this still an issue in v2.4 and v3?

**Comment by REJack** [comment]
I’ll close this issue after long inactivity.
