### ISSUE TITLE
left side search box on andriod losses focus as soon as you click into it

### ISSUE THREAD

**Issue by joneastwood** [ColorlibHQ/AdminLTE#1196]
If i run the site on an andriod tablet and I click into the search bx on the left hand side to start typing, the keyboard appears for a split second and then disappears and the search box then loses focus.

Annoyingly when i run your demo this works fine yet I have simply copied over the code and it wont work...

Any ideas please?

**Comment by almasaeed2010** [comment]
Make sure to update AdminLTE files to the latest version 2.3.8. If that doesn't work, please let us know.

**Comment by jesseterry** [comment]
Hi @almasaeed2010 - I think I'm having a similar issue as was reported here and I did test it in 2.3.8 and can confirm the problem still exists there as well (freshly cloned, no modifications).

When using the fixed layout and clicking the search box in the sidebar in Android (using Chrome, anyway), the keyboard appears but then disappears right away. It doesn't seem to happen when using the non-fixed layout.

**Comment by annex-chris** [comment]
I'm having the same problem. I've upgraded to 2.3.8 ... but also when I use your preview admin on the same device, the keyboard will not stay open in the left form fields. Problem only occurs on fixed layout.

**Comment by joneastwood** [comment]
glad its not just me :-)

**Comment by almasaeed2010** [comment]
I believe it is because of [line 341](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L341) in app.js. We are gonna have to remove this feature for it to work on Android. I am not sure why Android doesn't respond the same way as IOS. I'll look further into it when I have a chance.

Thanks for reporting it!

**Comment by fraktal12** [comment]
I think @volkanceylan posted a fix here (at least work from my phone - HTC M8):
https://github.com/almasaeed2010/AdminLTE/issues/1265

I have 2.3.5.

**Comment by martin40o** [comment]
I'm having the same problem with 2.3.11 version. As I can see, this problem is the same on preview theme. I have try this fix [#1265 ](https://github.com/almasaeed2010/AdminLTE/issues/1265) but without success. Would you like to resolve this problem with fixed layout.
Thank you in advanced

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.10)?

**Comment by fraktal12** [comment]
Sorry, I don't know, I hav't installed the new version

    On Tuesday, May 21, 2019, 9:32:35 PM GMT+3, Raphael Jackstadt <notifications@github.com> wrote:  
 
 
Is this Issue still open with the latest Version (v2.4.10)?
