### ISSUE TITLE
Box header buttons' colors

### ISSUE THREAD

**Issue by Karmalakas** [ColorlibHQ/AdminLTE#1246]
I've posted a question on [StackOverflow](http://stackoverflow.com/questions/40613682/css-reset-overriden-background-color), but I believe the only way to fix this, is override all button styles for hovers and `default` normal state button. I think it's a bug (although I see CSS rules are added consciously) because I couldn't find any situation where default buttons should be transparent in box headers and where all buttons hovers should be colorless almost transparent. This could be related to [this issue](https://github.com/almasaeed2010/AdminLTE/issues/869). Using latest - 2.3.8 version

**Comment by REJack** [comment]
Is this issue still open with the latest version (v2.4.12)?
