### ISSUE TITLE
Suggest: sidebar shoule be auto collapsed at md resolution

### ISSUE THREAD

**Issue by realpg** [ColorlibHQ/AdminLTE#1272]
Hi, I'm a user of AdminLTE from China. It's very very cool. I like it very much. I have used it in more than 500 web projects.

Devices such like iPad, have a width at 768px. It matches the MD width. In our AdminLTE, the sidebar (of course the left one) is not collapsed by default. I've had a look at some other admin templates, and discussed with my workmates and friends on github, we both think it's better to collapse the sidebar at MD width by default. It's too narrow for devices between 768 & 1000 with a full sidebar. Especially ipad mini, which is small.

Current:
![ipad-1](https://cloud.githubusercontent.com/assets/12572518/21072031/8479a142-beef-11e6-9b91-8c633a600d7c.jpg)

Collapsed seems better:
![ipad-2](https://cloud.githubusercontent.com/assets/12572518/21072032/a1752a0a-beef-11e6-8821-e3cfa50702f0.jpg)

Can you take a consideration about my suggestion?

Thank u.

**Comment by sjzurek** [comment]
This drives me crazy. Anybody knows how to change it?

**Comment by encodia** [comment]
@realpg do you know any workaround to collapse sidebar by default on MD resolution devices? 
I'd try to edit JS `screenSizes` object and `$screen-sm` SCSS variable, without success.

Thanks

**Comment by lenamtl** [comment]
Check in JS file I think this is where it is set.

**Comment by FocusedWanderer** [comment]
Here is how I implemented:
`function autoCollapseSideBar() {
  var viewportWidth = $(window).width();
  if (viewportWidth < $.AdminLTE.options.screenSizes.lg+300) {
    $("body").addClass('sidebar-collapse');
  }
  else {
    $("body").removeClass('sidebar-collapse');
  }
}
$(function () {
  // autoCollapse SideBar on first load
  autoCollapseSideBar();
});
$(document).ready(
    function() {
      // autoCollapse SideBar
      $(window).resize(autoCollapseSideBar);
    });
`

**Comment by REJack** [comment]
I've created a option for v3 with #2119, I'll create soon a documentation with detailed information about the option.

I close this issue for now
