### ISSUE TITLE
Using Scrollpanel instead of Slimscroll ?

### ISSUE THREAD

**Issue by vincent-guesnard** [ColorlibHQ/AdminLTE#1282]
Hello,

Since Slimscroll is dual licensed (MIT & GPL-3.0), what about change it for Scrollpanel (https://github.com/lrsjng/jquery-scrollpanel/) which is distributed only under MIT ?

I perfectly understand that most don't care about licensing, but for ones who care, it would be nice.

There is a similar issue on html5shiv which is distributed with a dual licensed too : MIT & GPL-2.0.  However, for this last, i don't have an alternative.

Thanks you for all your work, you have change my life (really).

Best regards,

Vincent

**Comment by REJack** [comment]
Thats a nice idea, maybe @almasaeed2010 use it in his new v3 that he started to create 😄

**Comment by REJack** [comment]
> I have looked over jquey.nicescroll & other alternatives and I found [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars) which works better than jquery.nicescroll and looks really nice with AdminLTE v3, I'll push soon the changes.

According to this post I looked over jquery-scrollpanel too and I'll replace slimScroll with OverlayScrollbars.
