### ISSUE TITLE
[FEATURE (tiny)] Yes or not checkbox

### ISSUE THREAD

**Issue by vincent-guesnard** [ColorlibHQ/AdminLTE#1297]
Hello,

After 2 years of ICheck, i've decided to delete it from my project for this css : https://www.creativejuiz.fr/trytotry/custom-checkbox-full-css3-flat-ui.html

More ergonomic, more user-friendly, without javascript.

I understand that some of us deal with outdated browsers, but we will be tomorrow in 2017 and i think that HTML 5 and CSS 3 shoud be considerated as mostly supported, allowing us to don't care about depreciated browsers.

Something similar to what i proposed with an active community support would be awesome. I didn't find anything on github.

Any idea ?

Best regards,

V

**Comment by REJack** [comment]
👍 great suggestion for v3

**Comment by REJack** [comment]
This issue is fixed with #2123, you can test it on https://adminlte-dev.rejack.space/pages/forms/general.html#customSwitch1.
