### ISSUE TITLE
mini sidebar width

### ISSUE THREAD

**Issue by kuswantoheng** [ColorlibHQ/AdminLTE#1336]
Hi All,

I'm new to this template. Just wondering, how to change the width of mini style of sidebar on the even of mouse hover?

Many thanks.

Kuswanto

**Comment by kuswantoheng** [comment]
![qqq](https://cloud.githubusercontent.com/assets/25238476/22134794/5d3d6b0e-defc-11e6-9b35-6ebe0d6e1f2c.png)

**Comment by lenamtl** [comment]
Look for this class

`.sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > a > span:not(.pull-right), .sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > .treeview-menu `

check for each @media queries 

```
@media (min-width: 768px)
.sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > a > span:not(.pull-right), .sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > .treeview-menu {
    display: block !important;
    position: absolute;
    width: 180px;
    left: 50px;
}
```

**Comment by kuswantoheng** [comment]
Hi,

I did change the width value to 300px (for example) in AdminLTE.css file, but it still did not work.

Here is the code:

`.sidebar-mini.sidebar-collapse .sidebar-menu > li:hover > .treeview-menu {
    display: block !important;
    position: absolute;
    width: 300px;
    left: 50px;
  }`

**Comment by lenamtl** [comment]
make sure you are changing it for all @media.
Try different width maybe 300px is not enough for your needs

**Comment by giansalex** [comment]
Change this value: 
![captura](https://user-images.githubusercontent.com/14926587/30224695-57eb1792-9495-11e7-8772-6ef4b103d02a.PNG)

**Comment by shaukatwaqarangular** [comment]
never tried it but try to generate minified version of it if you are linking .min version of it

**Comment by ChiKaLiO** [comment]
so 2019 ?
