### ISSUE TITLE
Is there any Vertical Tabs?

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#1348]
Hi,

Is there any Vertical Tabs?
If not this may be a good idea to have one for the next version.

Anyone have a custom one?

**Comment by xeoshow** [comment]
Also strongly request this one ...

**Comment by demiusvosp** [comment]
I have overridden default styles by left tabs.

/* табы слева от контента */
.nav-tabs.tabs-left {
    border: none;
    border-right: 1px solid #ddd;
}
.nav-tabs.tabs-left > li {
    float: none;
    margin-bottom: 0;
    margin-right: -1px;
}
.nav-tabs.tabs-left > li > a {
    margin-right: 0;
    margin-bottom: 2px;
    border: 1px solid transparent;
    border-radius: 4px 0 0 4px;
}
.nav-tabs.tabs-left > li.active > a {
    border: 1px solid #ddd;
    border-right-color: transparent;
}

**Comment by REJack** [comment]
I've added this feature into v3, you can check [this](https://adminlte.io/themes/dev/AdminLTE/pages/UI/navbar.html) out
