### ISSUE TITLE
Cannot compile bootstrap + AdminLTE

### ISSUE THREAD

**Issue by SyncroIT** [ColorlibHQ/AdminLTE#1352]
Hi, I've open this issue to share how I fixed a problem encountered when compiling the Admin
LTE less file in conjunction with bootstrap less files. In this scenario i experienced several crashes of less compiler because of OOM.

When you try to compile Bootstrap and AdminLTE in the same file, as I did:
```
@import (once, less) "admin-lte/build/less/AdminLTE.less";
@import (once, less) "bootstrap-3.3.7/less/bootstrap.less";

```
with lessc ,gulp-less or similar tools,  you will obtain an out of memory problem (OOM).
Analyzing the files i discovered that the problem is caused by these files 

-  AdminLTE.less
- bootstrap-social.less
- select2.less 
- fullcalendar.less

To fix this issue simple comment out the following lines 

```

@import (reference) "../bootstrap-less/mixins"; // Just comment this to solve
@import (reference) "../bootstrap-less/variables"; // Just comment this to solve

```
The exact portion of script that cause problem is in the file _grid-framework.less_  in folder _bootstrap-less/mixins_, at the following lines
```
// Basic looping in LESS
.loop-grid-columns(@index, @class, @type) when (@index >= 0) {
  .calc-grid-column(@index, @class, @type);
  // next iteration
  .loop-grid-columns((@index - 1), @class, @type);
}

```

**Comment by tegola** [comment]
I've got this issue, too, and can confirm that commenting those lines has fixed my problem.

In general, there shouldn't be a reference to internal bootstrap files. Bootstrap should be a package dependency.

**Comment by camilopayan** [comment]
As far as I can tell, this bug remains unresolved, even with `reference` importing.

**Comment by brainz80** [comment]
Still unresolved.

I'm trying to setup AdminLTE (_2.4.18_) and Bootstrap (_3.4.1_) to compile via Webpack (_5.39.0_) and adding them both into my main.less e.g. like:

```less
@import "~admin-lte/build/less/AdminLTE.less";
@import "~bootstrap/less/bootstrap.less";
```

results in a out-of-memory crash.

Only when I commented out

```js
// Basic looping in LESS
.loop-grid-columns(@index, @class, @type) when (@index >= 0) {
  .calc-grid-column(@index, @class, @type);
  // next iteration
  .loop-grid-columns((@index - 1), @class, @type);
}
```

in `grid-framework.less` did it compile. But removing the above lines isn't applicable.
