### ISSUE TITLE
Page suggest

### ISSUE THREAD

**Issue by array81** [ColorlibHQ/AdminLTE#1353]
I would suggest some pages:
- e-commerce: https://colorlib.com/polygon/gentelella/e_commerce.html
- projects: https://colorlib.com/polygon/gentelella/projects.html
- project details: https://colorlib.com/polygon/gentelella/project_detail.html
- contact: https://colorlib.com/polygon/gentelella/contacts.html
- price table

**Comment by masteradhoc** [comment]
That Looks very nice! Could you add them as a pull request?

**Comment by REJack** [comment]
I've added new page demos in AdminLTE v3, you can check them out at the offical [demo](https://adminlte.io/themes/dev/AdminLTE/).

I've added the following pages:
- [E-commerce](https://adminlte.io/themes/dev/AdminLTE/pages/examples/e_commerce.html)
- [Projects](https://adminlte.io/themes/dev/AdminLTE/pages/examples/projects.html)
- [Project Detail](https://adminlte.io/themes/dev/AdminLTE/pages/examples/project_detail.html)
- [Project Add](https://adminlte.io/themes/dev/AdminLTE/pages/examples/project_add.html)
- [Project Edit](https://adminlte.io/themes/dev/AdminLTE/pages/examples/project_edit.html)
- [Contacts](https://adminlte.io/themes/dev/AdminLTE/pages/examples/contacts.html)
