### ISSUE TITLE
Multi-level Treeview Menu not Working

### ISSUE THREAD

**Issue by kacey90** [ColorlibHQ/AdminLTE#1378]
I am using the AdminLTE template (Super cool template by the way) in an AngularJS application of mine. I was able to include all files and setup the layout with my very own Custom Navigation Provider to be displayed on the SideBar and everything works fine. 

However, the menu item that is supposed to expand where the menu has a child-menu item, it doesn't expand at all. In fact, it does nothing at all. But when I toggle the sidebar and hover over the multi-level menu item, It pops out the menu items and child menu items. I don't know what to do really. Please I need help. I've searched for a solution hard for weeks and found nothing that helps.

![adminlte01](https://cloud.githubusercontent.com/assets/26015234/23329645/cd55d1c2-fb3c-11e6-9e07-9c6d2ca67181.png)
![adminlte02](https://cloud.githubusercontent.com/assets/26015234/23329651/d9629400-fb3c-11e6-8a24-b71a1df258d8.png)

**Comment by cjmling** [comment]
How does your multilevel tree-view code looks like ?  Could be helpful

**Comment by ins0** [comment]
Can confirm that this issue is also present in the demo template of admin lte (multi level navigation) after switching to the short navigation. Expand etc is not working

**Comment by emiliobristech** [comment]
What I found out about this issue is that when you set smaller font (i.e: body { font-size: 12px!important; }) a white line appears above sub-menus when it's in mini-menu mode. It's possible to see in your second image.

How do I change font-size without this issue?

**Comment by lucidpsimc** [comment]
I had this same issue. I setup my instance in Laravel but you can probably figure this out for your application also. 

There was a line in my base template calling for jQuery 2.1.3 but in the version I installed (using Bower) it came with jQuery version 2.2.3 in the plugins folder. I just needed to update that reference and everything started working again.

**Comment by stonkeep** [comment]
Same problem here

**Comment by almasaeed2010** [comment]
@stonkeep which version are you using? I don't see this happening in v2.4.

**Comment by hendimarcos** [comment]
You are probably adding the menu items via javascript after the browser renders the page.

Test this in the browser console.
$('ul.sidebar-menu').tree();

**Comment by cactusjack66** [comment]
I have exactly the same problem.
I'm adding the list items with *ngFor after they have been fetched async from a server.
When everything is loaded and I call $('ul.sidebar-menu').tree(); in the browser, it works....

But of course I do not want to call this in my browser. How do I get around this?

**Comment by hendimarcos** [comment]
Can not you make the same call from within a component or angular service?

**Comment by cactusjack66** [comment]
I tried that, but I somehow cannot get access to the 'ul.sidebar-menu' items from my html document,
but I must admit that I'm just a beginner in that jQuery stuff, so maybe I am missing something...
So how would you do that in typescript?

**Comment by dlmvikas** [comment]
@cactusjack66 Have you sorted out your problem. I am also facing the same issue. This jquery $('ul.sidebar-menu').tree(); works fine in browser but not in my Angular 7 app. Error comes out as 'tree is not a function'. I am also  new in angular. My adminlte version is 2.4.15

**Comment by REJack** [comment]
@dlmvikas this sounds like you doesn't injected the adminlte(.min).js

**Comment by dlmvikas** [comment]
I have injected it in angular.json alongwith all other dependency files. As shown below :

 

"node_modules/admin-lte/bower_components/jquery/dist/jquery.min.js",

              "node_modules/admin-lte/bower_components/jquery-ui/jquery-ui.min.js",

              "node_modules/admin-lte/bower_components/bootstrap/dist/js/bootstrap.min.js",

              "node_modules/admin-lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js",

              "node_modules/admin-lte/bower_components/fastclick/lib/fastclick.js",

              "node_modules/admin-lte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js",

              "node_modules/admin-lte/bower_components/jvectormap/jquery-jvectormap.js",

              "node_modules/admin-lte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js",

              "node_modules/admin-lte/bower_components/chart.js/Chart.min.js",

              "node_modules/admin-lte/dist/js/adminlte.js",

              "node_modules/admin-lte/dist/js/pages/dashboard2.js"
