### ISSUE TITLE
A Quickfix for ".login-page&.register-page" unwanted scroll

### ISSUE THREAD

**Issue by ssunbob** [ColorlibHQ/AdminLTE#1379]
I found the issue when I'm trying to use the Latest version of AdminLTE 2.
So I made a quick fix about that after a bit trying.
It's
`.login-page,.register-page{
	margin: auto;
    padding-top: 3%;
	padding-bottom: 3%;
}`
This would help someone,
Thanks! 👍

**Comment by ssunbob** [comment]
A screenshot about this:
![screenshot-almsaeedstudio-com-themes-adminlte-pages-examples-login-html-1488172084609](https://cloud.githubusercontent.com/assets/12933369/23349414/fab225be-fced-11e6-8184-8c374b7df67b.png)

**Comment by Spudra** [comment]
Having the same problem. But where am i supposed to put the code?
Because i tried to put it in all css files that are included in the page, but nothing happened.
Thanks in advance for trying to help people (:

**Comment by ssunbob** [comment]
Well , you need to **push this code into a new css file** and **load it after the framework css (adminlte.min.css) to overwrite the wrong exist code** , or you can try to **overwrite this directly in the framework css**.
just find & replace **.login-page,.register-page**{ _code here_ } to the code I provided above.

**Comment by ssunbob** [comment]
I suggest you can create your own css style file and load it after the Framework css,
It's like
  <link rel="stylesheet" href="pathto/css/AdminLTE.min.css"> // framework css
  <link rel="stylesheet" href="pathto/css/skins/skin-blue.min.css"> // skin css
  <link rel="stylesheet" href="pathto/css/**mystyle**.css"> // **your own css , put fixes into this file :)**

**Comment by Spudra** [comment]
Tried that once, it didnt work, but after i just tried it again, it works. (putting it in adminlte.min.css)
I don't know what but i did something somewhere wrong :)

**Comment by ssunbob** [comment]
You can try to use F12 to have a look.

**Comment by fabiofdsantos** [comment]
I used `margin: auto;padding-top: 10%;` instead of padding top/bottom as `3%`.

**Comment by onesinus** [comment]
set padding top to 10% to make center box, then set overflow to hidden

.login-page,
.register-page {
  background: #d2d6de;
  padding-top: 10%; 
  overflow: hidden;
}

I've tried this, hope this help
