### ISSUE TITLE
Multi-language support for left navigation sidebar

### ISSUE THREAD

**Issue by Jason-Simrany-Inttra** [ColorlibHQ/AdminLTE#1380]
I am running into significant issues getting the left navigation sidebar to work properly with varying label lengths, based on variations in language.  Even with English labels, it is very easy to have labels get 'cut-off' due to the 230px width of the sidebar.  When collapsed, the hover over display is even narrower, so labels often get truncated.  I've tried turning on wrapping, but this causes issues with the animated sidebar.  The only solution I could find is to disable the CSS transitions for collapsing/expanding the sidebar, but this does not solve the collapsed sidebar hover state... because the labels get covered up by the sub-menus.  Sorry if this is confusing, but I guess what I am saying is it is hard to adapt the sidebar navigation to accommodate multi-language support.

Has anyone come up with any solutions for this issue?

**Comment by almasaeed2010** [comment]
This issue has been solved in v2.4-dev. I'll push the changes soon. I'll keep this open until then.
