### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by t3mh4** [ColorlibHQ/AdminLTE#1395]
Hii,

i need to add logo inside Sidebar user panel.İ did bu when sidebar closed logo does not get smaller

**Comment by almasaeed2010** [comment]
Please provide your logo code. Thanks!

**Comment by t3mh4** [comment]
here is my code part

`<div class="user-panel text-center">
                   <img src='@Url.Content("aa","bb")' alt="User Image" width="150" height="100">
</div>`

**Comment by dak-on** [comment]
Hi,
I have the same necessity, I would like to have the logo on the bottom of the left sidebar, and have it disappear or smaller when the sidebar is closed.
Now I only have the logo, and when I close the sidebar, the logo tranship on the content page.
How can I do?
Thanks for the support!
