### ISSUE TITLE
i use react has some troubles. how fix it 

### ISSUE THREAD

**Issue by lansefengxinzi** [ColorlibHQ/AdminLTE#1407]
![image](https://cloud.githubusercontent.com/assets/12048313/23846556/eed12d8c-0808-11e7-8f86-cbf0c965c115.png)
![image](https://cloud.githubusercontent.com/assets/12048313/23846588/1bfb4400-0809-11e7-962f-6bfccc8b828b.png)

**Comment by mdjaman** [comment]
What is the problem. Image doesn't speak by itself
