### ISSUE TITLE
fixed layout side-menu collapsed popout just group

### ISSUE THREAD

**Issue by marc-gist** [ColorlibHQ/AdminLTE#1411]
is it possible to get the same behaviour from the collapsed side menu in "fixed" layout as it doesn't in the standard (without .fixed) layout?

i.e. i want just the menu item being hovered over to "pop" out, not the entire side menu.
I found the issue where you can disable the "pop out" of the entire menu in .fixed mode, but that isn't what I want either.

Thanks!

**Comment by REJack** [comment]
You can modify the app.js to get this behavior 😄

**Comment by marc-gist** [comment]
would be nice to just have a simple setting :)
or could you show me where this is handled ?

**Comment by REJack** [comment]
There is a option for this [L55](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L55), but this option is forced to true if both the fixed layout and sidebar mini are used together.

To tweak this away you can remove 
```js
|| ($('body').hasClass('fixed')
&& $('body').hasClass('sidebar-mini'))
```
 in [L355](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L355)
