### ISSUE TITLE
Two scroll bars!

### ISSUE THREAD

**Issue by andymiaomiao** [ColorlibHQ/AdminLTE#1418]
when the height of main-sidebar is larger than the height of content-wrapper ,two scroll bars appear on the right side of window.

**Comment by tiglui96** [comment]
I have the same problem! 
When I navigate through the pages, 2 scrolls bars appear if the height of the page change.
How can I fix it?
Thanks!

**Comment by and318** [comment]
Same problem here. V2.38 and V2.4.0

**Comment by fllykk** [comment]
same for @version 2.3.8

**Comment by Wakirin** [comment]
```
if ($('aside.main-sidebar').height() > $('div.content-wrapper').height()) {
        $('div.content-wrapper').css('min-height', 'auto');
}
```
as temporary solution.

**Comment by Wakirin** [comment]
```
if ($('aside.main-sidebar').height() > $('div.content-wrapper').height()) {
        $('div.content-wrapper').css('min-height', ($(window).height() - 50) + 'px');
}
```
as temporary solution.

**Comment by erikrs92** [comment]
this work for my.

change this in css style.

.wrapper{height:100%;position:relative;overflow-x:hidden;overflow-y:auto}

for this:

.wrapper{height:100%;position:relative;overflow-x:hidden;overflow-y:**hidden**}

**Comment by cleatuskeetz** [comment]
The same problems exists for me also. So, These changes is maded to which CSS file?

**Comment by ismirsehregal** [comment]
AdminLTE.min.css

**Comment by darkvadaure** [comment]
#1947 https://github.com/almasaeed2010/AdminLTE/issues/1947 seems to correct this issue. However someone must confirm, i didn't make much tests

**Comment by msaied93** [comment]
I still have this issue with release 2.4.9.

**Comment by magicsign** [comment]
If using Chrome set on the body "-webkit-paged-x"
