### ISSUE TITLE
Select menu voice

### ISSUE THREAD

**Issue by m-merola** [ColorlibHQ/AdminLTE#1420]
Hi, I've installed AdminLte and menu in left it's ok.

I've 2 pages (list and detail) and 1 link il left menu (only list).
In list page menu is active, but when I go in detail menu in not active.

How to resolve it?

Thanks

**Comment by REJack** [comment]
Please provide your html code to help you better.

**Comment by m-merola** [comment]
Hi,
I use yii2 extension dmstr\widgets\Menu and this is portion of code

<ul class="sidebar-menu"><li><a href="#"> <span>STUDIA</span> <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
        <ul class='treeview-menu' >
            <li><a href="/test/studia/index"><i class="menuselectedleft"></i>  <span>VOICE 1</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 2</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 3</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 4</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 5</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 6</span></a></li>
            <li><a href="/test/studia/listato"><i class="menuselectedleft"></i>  <span>VOICE 7</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 8</span></a></li>
            <li><a href="/test/studia/#"><i class="menuselectedleft"></i>  <span>VOICE 9</span></a></li>
        </ul>
    </li>
    <li><a href="#"><i class="fa fa-newspaper-o"></i>  <span>VOICE 10</span></a></li>
    <li><a href="/test/sfide"><i class="menuselectedleftTop"></i>  <span>VOICE 11</span></a></li>
    <li><a href="#"><i class="fa fa-newspaper-o"></i>  <span>VOICE 12</span></a></li>
</ul>


The problem is on voice 7.
Where url is /test/studia/listato it's all ok, where url is /test/studia/listato-detail menu is not select.

How I can select dinamically.

Thanks

**Comment by REJack** [comment]
For this problem you can write a little javascript to change the active state
