### ISSUE TITLE
AdminLTE.css has an unwelcome Internet API dependency

### ISSUE THREAD

**Issue by luronumen** [ColorlibHQ/AdminLTE#1421]
**[AdminLTE.min.css](https://github.com/almasaeed2010/AdminLTE/blob/v2.3.11/dist/css/AdminLTE.min.css)** has an unwelcome Internet API dependency ([fonts.googleapis.com](https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic)) that makes the AdminLTE template not fully useful for intranet networks without Internet access:

`@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);
`

Beside that, an _import_ declaration inside css file introduce several issues for bundling CSS files (Search on google for: `Unexpected token, found '@import'`).

There are some other reasons for not using _import_ declaration inside css file that we can check here: [don’t use @import](http://www.stevesouders.com/blog/2009/04/09/dont-use-import/)

**Comment by nermamax** [comment]
Can't you just download these fonts and import them in your application before you call adminLTE css, so that fonts are available to adminLTE?

**Comment by luronumen** [comment]
Hi @nermamax, thank you very much for your reply!

Of course that we can remove the Internet API references ([fonts.googleapis.com](https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic))  from the **[AdminLTE.min.css](https://github.com/almasaeed2010/AdminLTE/blob/v2.3.11/dist/css/AdminLTE.min.css)** and add those references in the personal web project directly but it will generate rework for updating their own web project every time that a new version of the AdminLTE template is released and they want to update their own web project for the new version of the AdminLTE template.

If so, the better solution is remove this Internet API references ([fonts.googleapis.com](https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic)) from the **[AdminLTE.min.css](https://github.com/almasaeed2010/AdminLTE/blob/v2.3.11/dist/css/AdminLTE.min.css)**, like we already have for bootstrap for instance, and make it easy to the AdminLTE developers to update their web project by replacing the **[AdminLTE.min.css](https://github.com/almasaeed2010/AdminLTE/blob/v2.3.11/dist/css/AdminLTE.min.css)** only

**Comment by nermamax** [comment]
Hi @luronumen if it is removed, where should the adminLTE get the fonts from?

**Comment by luronumen** [comment]
Hi @nermamax 
I was not asking for removing the fonts. I asked for removing the AdminLTE Internet API dependency.
And How can we do it? Doing your exactly suggestion: moving the current Internet API dependency to the web project but not the costumer project but in the AdminLTE template

**Comment by WimWidgets** [comment]
@nermamax
> [...] where should the adminLTE get the fonts from?

In my opinion the template should not start with custom fonts to begin with. Just like Bootstrap - on which it's based - it should use standard system fonts by default (Helvetica, Arial, etc. or even just sans-serif). Then every user can easily customize it to taste and load how many external fonts they desire.

**Comment by Otiel** [comment]
Is this going to be done one day?

Closed issues that were already asking for this:
#116
#498
#744 
#1233
#1458
