### ISSUE TITLE
convert to aspx project

### ISSUE THREAD

**Issue by copey573a** [ColorlibHQ/AdminLTE#1426]
I downloaded the adminLTE 2 code, and put it into a asp.net C# web project.  As long as I run the html pages things are working fine.  But if I put the html code in my aspx page, some of the graphs, etc data isn't loading.  What am I missing that I need to fix?
thanks

**Comment by REJack** [comment]
check your console for errors

**Comment by ktngoykalolo** [comment]
check your js and Css file references.
