### ISSUE TITLE
Problem in select2 if I'm using collapsed-box class

### ISSUE THREAD

**Issue by mariapaulinar** [ColorlibHQ/AdminLTE#1428]
I am using an expandable block, like this:

<div class = "box-solid box-primary collapsed-box">

Inside it I have a select2. However when using it, select2 is reduced in size. This does not happen to me when I do not use the collapsed-box class, the select2 is displayed with the correct size. In the following images I show what is happening:

(The enclosed with red is the select2)

1. Without using the collapsed-box class, select2 looks like this:

![captura1](https://cloud.githubusercontent.com/assets/1920342/24569856/e0702d00-162d-11e7-8c55-74f65693ac60.PNG)

2. Using the collapsed-box class the block is initially hidden, correctly displayed. However, when you click the plus icon, select2 is reduced to one size:

![captura2](https://cloud.githubusercontent.com/assets/1920342/24569872/ebd3dd72-162d-11e7-9ebb-3c03038cd339.PNG)

![captura3](https://cloud.githubusercontent.com/assets/1920342/24569897/0db75892-162e-11e7-911b-844ccf6c8877.PNG)

Please if anyone knows what may be going on, I would appreciate your help in commenting on the solution.

**Comment by REJack** [comment]
Please provide HTML & JS Code, to help you better.
