### ISSUE TITLE
Just a small question

### ISSUE THREAD

**Issue by niloleon** [ColorlibHQ/AdminLTE#1429]
Hi all,
i was checking the principal page of the project INDEX2.HTML especially code of "main navigation" where there are links to other sections such as WIDGETS.HTML. Why in that second page (widgets.html) is repeated all the code that creates "main navigation" section?? 
Cannot be done as a layout fixed part and only the content part dynamical?
Thx a lot

**Comment by REJack** [comment]
I don't know it right, but i would say its the the main layout (menu) from AdminLTE
