### ISSUE TITLE
Adminlte a problem of working on asp.net webform

### ISSUE THREAD

**Issue by gmsoftict** [ColorlibHQ/AdminLTE#1442]
my webforms works properly if i test separately but if i connect it with another forms in the button click event does not work, the second problem is i cant use ASP.net controls in adminlte

**Comment by addytsl** [comment]
I have a webforms ASP .NET application and I use asp .net controls with this template.

**Comment by almasaeed2010** [comment]
@gmsoftict please provide more information in order for us to help.

**Comment by 3432sdffsdd** [comment]
> I have a webforms ASP .NET application and I use asp .net controls with this template.

i need ur help man, please help me
mr.ammadarif@gmail.com

i need adminlte in  web forms of asp.net
