### ISSUE TITLE
Update for Bootstrap Datepicker

### ISSUE THREAD

**Issue by pavoltanuska** [ColorlibHQ/AdminLTE#1462]
The Bootstrap Datepicker is quite outdated, it desperately needs an update :)

I'm open to providing a PR, I just need a confirmation regarding the version that you'd like to include.

I see 2 options here:
- [v1.6.4](https://github.com/uxsolutions/bootstrap-datepicker/tree/v1.6.4) which is 9 months old, but looks like a latest stable release
- [v1.7.0-RC2](https://github.com/uxsolutions/bootstrap-datepicker/tree/v1.7.0-RC2) which is "bleeding edge", but as the version name goes, just a release candidate right now

I'd probably go for the v1.6.4 now and make an update to v1.7.0 once it's stable, but I'm interested in your opinion here.

**Comment by almasaeed2010** [comment]
We will upgrade the plugins with the next release v2.4. This is so we don't introduce breaking changes to the current line of releases.

Thanks!

**Comment by pavoltanuska** [comment]
Thank you for heads up! Is there some ETA/timeline for v2.4?
I'm not trying to push you or anything, I just didn't find a milestone for this release :)

**Comment by almasaeed2010** [comment]
Hi @pavoltanuska 

Sorry for the (very) late response! I am not going to put a hard date on the release, but it is currently in master and we adding new things every day. We'll add the plugin upgrades soon and release a beta. Feel free to test and report any issues. The upgrade guide is available here if you are interested: https://adminlte.io/docs/2.4/upgrade-guide

Thanks!
