### ISSUE TITLE
Left Sidebar Expandable like less.sidebar

### ISSUE THREAD

**Issue by asadiqbalse** [ColorlibHQ/AdminLTE#1485]
Hi,

I want to make my left side bar expandable to right like less.sidebar on-mouse over. I have many nested  chlids or sub menus. Please help me to, how can i do that.

I need it on urgent bases.

**Comment by REJack** [comment]
What you mean exactly?

**Comment by almasaeed2010** [comment]
Hello @asadiqbalse 

We are not sure what your request is exactly. Please elaborate on the issue if you can. 


Please close this issue if you have already found a solution. Thanks!
