### ISSUE TITLE
Kaspersky Blocking demo url

### ISSUE THREAD

**Issue by prasannakumarpkd** [ColorlibHQ/AdminLTE#1486]
My Kaspersky internet security 2017 is blocking demo url with the following warning(Phlishing)
![image](https://cloud.githubusercontent.com/assets/28564769/25850743/03d388f6-34e1-11e7-9d6b-1601cab5b015.png)

**Comment by Tjoosten** [comment]
Have u checking your kaspersky settings. Because here no problem

**Comment by prasannakumarpkd** [comment]
What settings I have to check with Kaspersky ?

**Comment by almasaeed2010** [comment]
Try this URL: https://adminlte.io/themes/AdminLTE/pages/UI/buttons.html

If the issue persists, please let us know.

Thanks!

**Comment by prasannakumarpkd** [comment]
![untitled](https://cloud.githubusercontent.com/assets/28564769/26274787/9ece2000-3d6f-11e7-937f-0a8ead9d9499.png)

Problem still exists.
