### ISSUE TITLE
sidebar-menu does not work in mobile

### ISSUE THREAD

**Issue by ZivHsu** [ColorlibHQ/AdminLTE#1505]
Hi @almasaeed2010 

I has change the default status in sidebar-menu setting to close

<body class="skin-blue sidebar-mini wysihtml5-supported sidebar-collapse" style="height: auto;">

But when I use mobile view in first time, the li it can't open or close,

And I try to use AdminLTE v2.4. 

But it will broke... like this...

![1495439815467](https://cloud.githubusercontent.com/assets/19678859/26297849/5f407336-3f07-11e7-8c19-23126670b82e.jpg)

**Comment by miguelguadarrama** [comment]
having this issue too!

**Comment by riddlenl** [comment]
Yes, I have this as well. No answer on this issue, is there an update?
