### ISSUE TITLE
FullCalendar locale Not Working

### ISSUE THREAD

**Issue by alexandremix** [ColorlibHQ/AdminLTE#1506]
I included the locale-all.js File downloaded from the fullcalendar plugin.

I made Sure that I include the file after jquery, moments and fullcalendar.js is loaded
When I initialize the calendar 
 $('#calendar').fullCalendar({
      locale: "pt"
})

The Language does not change

**Comment by 18979687252** [comment]
lang:'pt'

**Comment by alexandremix** [comment]
Please Read: https://fullcalendar.io/docs/text/lang/
Thanks.
I Also tried to include the language JS File, Does not work also

**Comment by JSANL** [comment]
```
>    <script src="js/jquery-3.2.1.js"></script>
> 
>     <!-- Bootstrap Core JavaScript -->
>     <script src="js/bootstrap.min.js"></script>
> 	
> 	<!-- FullCalendar -->
> 	<script src='js/moment.min.js'></script>
> 	<script src='js/fullcalendar.min.js'></script>
> 	<script src='locale-all.js'></script>
> 	
> 	<script>
> 
> 	$(document).ready(function() {	
> 		$('#calendar').fullCalendar({
> 			header: {
> 				...
> 			},
> 			defaultView: 'agendaWeek',
> 			locale:	'de',
>                      ....
```
   "..." for unnecessary code, I also tried it by just importing the de.js file, but nothing is working

**Comment by razvaniacob** [comment]
I have the same issue. Any ideas?

**Comment by xIcarus** [comment]
Ditto, locale isn't working for me either. Has anyone discovered anything around this?

**Comment by LGWen** [comment]
it help me to deal my issue.
maybe you shuold include the language JS File ,(pt.js)

[https://usingfullcalendar.wordpress.com/tag/locale/](url)

**Comment by juanmaussa** [comment]
I have the same problem, I searched a lot in the official documentation and different blogs but the language does not change for more than I try. Has anyone found the solution to this problem?

<script src="js/libs/moment.min.js"></script>
<script src='js/fullcalendar/fullcalendar.min.js'></script>
<script src='js/fullcalendar/locale-all.js'></script>

$(document).ready(function() {
        $('#calendar').fullCalendar({
            locale: 'fr',
            dayNamesShort: ['Lun','Mar','Mie','Jue','Vie','Sáb','Dom'],
            .
            .
            .
       })
    });

**Comment by kaldi-de** [comment]
When you load a FullCalendar locale file, it also loads the translations for MomentJS and jQuery UI Datepicker (if the library is already on the page). Just make sure to include the <script> tags for Moment and Datepicker  **before**  you include FullCalendar’s locale file:

**Comment by gie913** [comment]
I have the same problem. 
i tried to load local lang directy. 
<script src='/vendor/fullcalendar/dist**/locale/id.js**'></script>
and it's worked for me

**Comment by acsar** [comment]
work
``calendar.setOption('locale', 'pt-br');``

**Comment by Rob0ut** [comment]
hey, i used calendar.setOption('locale', initialLocaleCode), where initialLocaleCode is variable like var initialLocaleCode = 'it', but doesn't work for option.

**Comment by acsar** [comment]
see this demo https://fullcalendar.io/docs/locale-demo

**Comment by acsar** [comment]
Is there any error in the console? If yes, which one?

**Comment by Rob0ut** [comment]
> Is there any error in the console? If yes, which one?

i found error.
Looking at the example I noticed that this file was missing
strange that in the installation guide it was not mentioned, but ok
<script src='[https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.5/locales-all.global.min.js](view-source:https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.5/locales-all.global.min.js)'></script>

**Comment by acsar** [comment]
Ótimo! que bom que conseguiu. Parabéns e sucesso!
