### ISSUE TITLE
adminlte.js not found

### ISSUE THREAD

**Issue by Sitronik** [ColorlibHQ/AdminLTE#1510]
When I installed admin-lte 2.3.11 via npm. I don't found file adminlte.js on this path:
```
/node_modules/admin-lte/dist/js/adminlte.js
```
This file isn't correct:
```
/node_modules/plugins/jvectormap/jquery-jvectormap-1.2.2.css
```
He has error:
```
background: #d2d6de;//rgba(0,0,0,0.4);
```
But in your repository this fixed https://github.com/almasaeed2010/AdminLTE/commit/074d1ca039027c72d6b996ed72de71a2e659d097

So when I generating Angular project via angular-cli I get this error:
```
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css
Module build failed: Unknown word (22:26)

  20 |     -moz-border-radius: 2px;
  21 |     border-radius: 2px;
> 22 |     background: #d2d6de; //rgba(0,0,0,0.4);
     |                          ^
  23 |     padding: 5px;
  24 |     color: #444;
```

earlier I reported this...

I will wait for update npm package admin-lte thanks..

**Comment by REJack** [comment]
In v2.3.x it's the app(.min).js
In the comming v2.4 the author changed it to adminlte(.min).js

**Comment by Sitronik** [comment]
@REJack I know it. But app.min.js doesn't work as adminlte.js I have some troubles with app.min.js when my application working.
