### ISSUE TITLE
SlimScroll with Fixed Layout when focus on mobile - Part 2

### ISSUE THREAD

**Issue by Muhamann** [ColorlibHQ/AdminLTE#1518]
Hello,

please goto:
https://github.com/almasaeed2010/AdminLTE/issues/427

I have adminLTE Version 2.3.8, and i have exactly the same error. When focussing the text-input in mobile, the keyboard appears and directly disappears, because of the explained slimscroll-behavior in the linked thread.

Here its discussed and closed, too:
https://github.com/almasaeed2010/AdminLTE/pull/1416

The Threads link to the solution of  almasaeed2010:
https://github.com/almasaeed2010/AdminLTE/commit/bca8e8ec669f93c6b22218d3aff6849e00a23ecf
Which should be included into 2.4 alpha.
But i dont understand this solution. He says, that he updated slimscroll. But when i compare his updates to my 2.3.8. slimscroll, its the same. Even the slimscroll-versions in 2.3.11 and the 2.4.alpha are the same.
The error is NOT fixed in there.

Can please help someone, i need to fix that somehow.
Thank you very much.

**Comment by Muhamann** [comment]
Prusk Fix works:
https://github.com/almasaeed2010/AdminLTE/pull/1416/files

**Comment by kressly** [comment]
First of all the admilte fix by @almasaeed2010 2.3.8. and 2.3.11 and the 2.4.alpha are NOT the same. Kindly read through his update patiently. There are many things that have been changed
