### ISSUE TITLE
Bug in mailbox.html  file.  

### ISSUE THREAD

**Issue by EminRahmanov** [ColorlibHQ/AdminLTE#1521]
Folders and Labels minimize or maximize . Open Folders and ikon -, but Labels closed but ikon -

![screen shot 2017-06-01 at 4 05 16 pm](https://cloud.githubusercontent.com/assets/5392145/26679023/66eef906-46e4-11e7-9da0-112fa18de606.png)

**Comment by REJack** [comment]
Thats a BoxWidget bug in v2.4-alpha.

@almasaeed2010 Please revert the app.min.js/adminlte.min.js to v2.3.12 on your preview.
