### ISSUE TITLE
Admin-Lte anda Laravel entristece-gui views problem

### ISSUE THREAD

**Issue by pbaldovi** [ColorlibHQ/AdminLTE#1524]
Hi. 
There are some incoatibility with user packed var when view is maked. The user VAR is uded by entrust-gui too. To solve this without overwrite controllers i change the name of the user packed VAR before sending it yo View.

**Comment by Tjoosten** [comment]
???

**Comment by pbaldovi** [comment]
Hi. Apologies, it was the fault of the corrector in Spanish.

This is the problem. I have entrust-gui installed to handle permissions and roles.
When I try to use the views along with the admin-lte layout there is a conflict because the user variable passed to the view has the same name in the two packages.

Is there any way to publish the Controllers to be able to change the variable without touching the package? Otherwise maybe for some update a custom variable name could be used so that there is no conflict with a very common variable name like "Users"

**Comment by REJack** [comment]
@pbaldovi AdminLTE is only a UI/UX and can used in any Framework, ask the Laravel Community for this problem.
