### ISSUE TITLE
[UPDATE PLS!] Bootstrap 4 is now available! 

### ISSUE THREAD

**Issue by ArmynC** [ColorlibHQ/AdminLTE#1528]
Try to **update** your framework to **v4** 

Link: [v4-alpha.getbootstrap.com](url)

**Comment by Tjoosten** [comment]
Personally i think its better to wait till the v4 full release.

**Comment by REJack** [comment]
Bootstrap v4 is planned for AdminLTE v3.

**Comment by jeffreyroberts** [comment]
where can I read more about AdminLTE v3 ?

**Comment by Soullivaneuh** [comment]
> Bootstrap v4 is planned for AdminLTE v3.

Do we have an another issue about v3 roadmap?

**Comment by TorbenLundsgaard** [comment]
@Soullivaneuh https://github.com/almasaeed2010/AdminLTE/issues/710

**Comment by opensas** [comment]
> 
> 
> where can I read more about AdminLTE v3 ?

Yeap, I would also like to read something about... features, estimate launch date, how we can help, etc
