### ISSUE TITLE
[UPDATE PLS!] From (c) 2016 to Auto-Change !!

### ISSUE THREAD

**Issue by ArmynC** [ColorlibHQ/AdminLTE#1529]
**From** `Copyright &copy; 2014-2016`

**To** `&copy; <?php echo date('Y'); ?>`

**Comment by ccoltman** [comment]
This isn't a PHP application.

**Comment by Tjoosten** [comment]
You alternative can do this with JS. In my opinion it's a better solution.

**Comment by ccoltman** [comment]
It's a date served from the server, just use whatever platform command appropriately. My point was this template is platform agnostic, not just intended for PHP. The OP should be replacing that on their project end, not inside the template.

**Comment by REJack** [comment]
@ccoltman 👍 i think that too, some ppls use it in ASP.net or inside a nodeJS App.
