### ISSUE TITLE
does it supports on focus expand functionality

### ISSUE THREAD

**Issue by tavishiChat** [ColorlibHQ/AdminLTE#1541]
I want to expand the sidebar panel on focus when the sidebar is minimized and user is navigating using keyboards.
I looked into the js but it seems there is only expand on hover functionality .
Can anyone suggest any solution.ASAP

**Comment by almasaeed2010** [comment]
Unfortunately we do not support this functionality at this. I am not sure if we will implement this but we will keep it in mind. We appreciate your suggestion!

Thanks!

**Comment by REJack** [comment]
I've added this feature into v3, you can test it on the regular dev demo: https://adminlte.io/themes/dev/AdminLTE/
