### ISSUE TITLE
Changed version of datatables then AdminLTE stops working with error

### ISSUE THREAD

**Issue by starcraft04** [ColorlibHQ/AdminLTE#1545]
I only changed the version of my datatables so it is like this now:
<script src="{{ asset('/plugins/datatables.1.10.14/datatables.min.js') }}" type="text/javascript"></script>

Meaning I don't use anymore the datatables provided by the AdminLTE package and then the left menu bar is not working anymore and I get the error:
Uncaught TypeError: Cannot read property 'options' of undefined
    at HTMLDocument.<anonymous> (app.js:156)
    at i (jQuery-2.2.0.min.js:2)
    at Object.fireWith [as resolveWith] (jQuery-2.2.0.min.js:2)
    at Function.ready (jQuery-2.2.0.min.js:2)
    at HTMLDocument.J (jQuery-2.2.0.min.js:2)

And it points in the file app.js to:
//Easy access to options
  var o = $.AdminLTE.options;

Can someone help me solve this?

Thanks.

**Comment by Yarandi** [comment]
i have this issue too.

**Comment by kabutotx** [comment]
What version of AdminLTE?
I used the latest 1.10.15 datatables and worked fine.  I just renamed the old directory and created a new one to match the old.

**Comment by almasaeed2010** [comment]
@starcraft04 make sure you load `app.min.js` (or `adminlte.min.js` for AdminLTE v2.4 and above) after jquery and bootstrap js files.
