### ISSUE TITLE
resize event not triggered after expand treemenu

### ISSUE THREAD

**Issue by Th3M3** [ColorlibHQ/AdminLTE#1547]
I try to update v2.1.2 to actual v2.4.
But when I update old `app.min.js` to new `adminlte.min.js`, I get the following issue:

If I use a content page that is smaller then the browser' height and expand one of the treeview-menus on the left sidebar, the footer should move down to always stay on page's bottom.
This was workig in the older versions, but does not in v2.4

I also tried to reproduce it with the demo page: 
With the browser's developert tools, I removed some of the content, did a browser resize and swithed back to fullscreen, and than expanded one of the treemenu.

This is what I get before expand e.g. the Charts-Menu (everything is as axpected):
![adminlte1](https://user-images.githubusercontent.com/28313514/27360988-c5ca98dc-5624-11e7-8931-bd4b9a35814a.jpg)

And after expand Charts:
![adminlte2](https://user-images.githubusercontent.com/28313514/27361013-e8c29646-5624-11e7-9e89-57f4bc7ec4e3.jpg)
The Footer is not aligned to bottom and there are two scrollbars on the right.
It goes to normal if I collapse the menu or do a screen resize - but the resize event sould get triggered automatically.

**Comment by almasaeed2010** [comment]
@Th3M3 thanks for the raising the issue! 

From my tests so far, this seems to be caused by the change in header height during the transition between the stacked header and the normal header. Trying to figure out a solution right now. Let me know if you find something that could be helpful.

Thanks!

**Comment by almasaeed2010** [comment]
@Th3M3 we just submitted a fix on the master. Would you care to test it?

Thanks!

**Comment by Th3M3** [comment]
I have updated files `adminlte.min.js`, `AdminLTE.min.css`, `skin-blue.min.css` on my [pi-hole](https://github.com/pi-hole/AdminLTE) installation.
For first look, the issue seemd to be solved.
But after further tests, the footer still sometimes not aligned to the bottom.

Here a screenshot (using Opera on Windows) with _Developer Tools_ open and `<body>` element selected:
![devel1](https://user-images.githubusercontent.com/28313514/27518774-d6677e28-59e7-11e7-9698-2b90336185b0.jpg)

At another test in Microsoft Edge, the gap between footer and bottom is even more.

After zoom the page to _110%_, the pages work correctly on Microsoft Edge.
But on Opera, I again get two scollbars on the right side and the footer is again not aligned to site's bottom. (I'm not sure if this is a opera browser bug).
What I found out is that the `<div class="content-wrapper">` gets style `min-height: 464px`.
But after I expand and collapse one of the left tree-menus, the `content-wrapper` gets `min-height: 463px` and then there is only one scrollbar on the right.

![devel2](https://user-images.githubusercontent.com/28313514/27519103-54bbad62-59ed-11e7-88e4-51e605d0bac5.jpg)

The next days I will try to change the js to log the heights variables into Developer Tool's console, to find out what is going on there in detail....

**Comment by almasaeed2010** [comment]
So the issue only occurs on Opera?

**Comment by Th3M3** [comment]
Edit: Maybe jQuery needs to be updated too to get the footers `.outerHeight()` correctly.

I will try this out and will report here.

**Comment by almasaeed2010** [comment]
I tested on Opera, Safari, FF and Chrome but I could not reproduce on the demo. If you test your browser using the [Demo](https://adminlte.io/themes/AdminLTE/index2.html) it would be great!

**Comment by Th3M3** [comment]
>So the issue only occurs on Opera?
At 100% zoom, the gap is still there like you see on my [screenshot](https://user-images.githubusercontent.com/28313514/27518774-d6677e28-59e7-11e7-9698-2b90336185b0.jpg), on Opera and Microsoft Edge. Haven't tested other browsers.

**Comment by Th3M3** [comment]
>I tested on Opera, Safari, FF and Chrome but I could not reproduce on the demo. If you test your browser using the Demo it would be great!

Are you sure to have updated the files in the demo?
I have still the same issues there, using Opera and Microsoft Edge

**Comment by almasaeed2010** [comment]
Sorry I meant testing by downloading the master branch.

**Comment by Th3M3** [comment]
Now I had time to test it again.

But it still not work as expected:
If I collapse a menu wich has only a few items, the footer don't moves down, but a scollbar appears on the right an I can scroll the page to this:

![test1](https://user-images.githubusercontent.com/28313514/27597081-a52cac9a-5b61-11e7-97d0-8151cd53d756.JPG)

But if I collapse a menu-tree with at least six items, the footer move down to page's bottom - as it should be.

Same behavior on Opera and Microsoft Edge.

**Comment by Th3M3** [comment]
The following thins I found out:
* jquery 3.2.1 don't work correctly to me. [It gets wrong `height` and `outerHeight` values, if browser's zoom factor is not set to 100%](https://github.com/jquery/jquery/issues/3681).
With jQuery 3.1.1 the values are correctly.

* in `adminlte(.min).js` I found an issue:
  * The sidebar's height should be the full element's height (including margin and padding)
  * While comparing `sidebarHeight` with `windowHeight`, it's needed to also add the header's height to get the overall height, because the menu-sidebar is placed ___under___ the header.
  * I also would add a function to round up the `neg` variable. In my case, in Opera I always had a scrollbar to scroll only 1px, because I need to use a page zoom factor.

Here my suggestion to the code. My changed lines are marked with a red `>` on the left.

```javascript  
    // Get window height and the wrapper height
    var footerHeight  = $(Selector.mainFooter).outerHeight() || 0
    var neg           = $(Selector.mainHeader).outerHeight() + footerHeight
    var windowHeight  = $(window).height()
>   var sidebarHeight = $(Selector.sidebar).outerHeight() || 0
>   var headerHeight = $(Selector.mainHeader).outerHeight() || 0

    // Set the min-height of the content and sidebar based on
    // the height of the document.
    if ($('body').hasClass(ClassName.fixed)) {
      $(Selector.contentWrapper).css('min-height', windowHeight - footerHeight)
    } else {
      var postSetHeight

>     if (windowHeight >= sidebarHeight + headerHeight) {
>        $(Selector.contentWrapper).css('min-height', windowHeight - Math.ceil(neg))
>        postSetHeight = windowHeight - Math.ceil(neg)
      } else {
>        $(Selector.contentWrapper).css('min-height', sidebarHeight - footerHeight)
>        postSetHeight = sidebarHeight - footerHeight
      }
```

Please review/test out my code. For me it works fine.
But remember, that there is still a issue, when using the `control-sidebar`. I ran all test without it. 
The last test I did with the control-sidebar and an empty page, I noticed, that js reads a wrong height value.

**Comment by jaydenseah** [comment]
Hi Th3M3, your solution on editing the codes in adminlte.js works properly. You should try contributing this changes. By the way, I'm still using the default Jquery provided in the bower_components. Thanks!

**Comment by Th3M3** [comment]
@jaydenseah Thank you for your testing and feedback. 
Glad to hear that it works for you as expected.

I have created a pull request for my changes.

Regarding my jquery issue, I did not notice that there is a `bower_components` folder in the branch.
After I downloaded the master branch, I had no such folder. Seems that I did something wrong.
I will try it again when i have more free time.

**Comment by jaydenseah** [comment]
@Th3M3 you're most welcome.

Regarding the `bower_components` part, try downloading the master branch, and you should be able to see it. Cheers!
