### ISSUE TITLE
Select2 elements loses focus on tab. It should focus on next (select2) element.

### ISSUE THREAD

**Issue by ajcastro** [ColorlibHQ/AdminLTE#1552]
Go to https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html.
Try focusing on a select2 element, then press tab. 
You will see that the focus is not on the next input element. 

I am not sure if the problem is with select2 itself or usage of it in admin-lte.
It seems that select2 is not keyboard friendly. I found other select plugin `selectize`, which is more keyboard friendly.

**Comment by ajcastro** [comment]
Related: https://github.com/select2/select2/issues/4971

**Comment by lenamtl** [comment]
This is a Select2 issue there is a fix for this.
`$('select').on("select2:close", function () { $(this).focus(); });`

**Comment by lenamtl** [comment]
The other problem with the Tab is  if you do a search then click tab the input will not have the new value, you have to click on Enter... I have to find a solution for this

**Comment by lenamtl** [comment]
Hi, check this fix
https://github.com/select2/select2/pull/4427/commits/294e7e664d95eafb7f41264c2b87412ad9aa48fc

**Comment by ajcastro** [comment]
@lenamtl, how do I get the fix??

**Comment by lenamtl** [comment]
You can manually edit the file since the pull request is not done yet...
I have not test it yet.
SO make a backup first then do some tests

**Comment by ZJaume** [comment]
I think this problem is still present
