### ISSUE TITLE
left side nav won't open dropdown links anymore

### ISSUE THREAD

**Issue by theresan** [ColorlibHQ/AdminLTE#1554]
Hi they were working and now I have used php and some ajax etc. and it has stopped working. I even removed the other scripts but it still doesn't work.
Not sure why it would work then not, is there a jquery or css that I am to add to my theme to get them to open up.
thanks

**Comment by kabutotx** [comment]
Look in the browsers developer tools console.  Usually it is some JavaScript failing to load or an error.
