### ISSUE TITLE
Feature Request - Shopping Cart Pages

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#1555]
I am a PHP developer and I am currently working on 

https://github.com/CakePHPKitchen/CakeAdminLTE

I have a bunch of feature requests for pages, the more pages I have as templates, the more PHP code I will write...

it would be absolutely awesome to see what a dashboard shopping cart would look like, you are pretty much half way there...

* Product Page
** w/ forum thread style reviews with multi-media attachments
* Shop Home Page
** Featured Products
** Featured Reviews
* Shop Product Search Page
** Product Search List with reviews/quantity/etc
* Add Product Page

I work based off examples, the more examples I have, the more I will implement with CakePHP in a Dashboard & Web Application Framework

**Comment by REJack** [comment]
I close this issue due your new issue #2359 😄
