### ISSUE TITLE
Box element not work with bootstrap affix

### ISSUE THREAD

**Issue by berlotto** [ColorlibHQ/AdminLTE#1556]
I need create a box, that will be in the top of page if page scrolls.
But, affix not works fine in the box element, the box is not fixed at top.

**Comment by githubjeka** [comment]
https://getbootstrap.com/docs/3.3/javascript/#via-data-attributes-5 doesn't work for any items from `.content`

**Comment by moebaca** [comment]
@githubjeka any ideas why and any workarounds?

**Comment by lenamtl** [comment]
Hi,

In fact it is working fine on the page `<section class="content">` , but it may not work inside a specific widget.
I have a menu that scroll with the page, 
I placed it under `<section class="content">` in row/ column, 
I'm using btn-group with affix and it's working fine.

Just follow the affix syntax 
https://getbootstrap.com/docs/3.3/javascript/#affix
