### ISSUE TITLE
how can I implement Tab Pages in AdminLTE?

### ISSUE THREAD

**Issue by java858** [ColorlibHQ/AdminLTE#1565]
hello, greetings from China, first of all, thanks  for the wonderful and powerful AdminLTE.
is it possible to implement tab pages ? not as a little ui component, but a page, a page which is opened by left side menu item, and there could be many tabs on the top bar,  when your cursor is one the tab title, and you right click the mouse, it will pop up a drop box and you can close the current tab,  you can close  all or close others. 
i do get an article, he made it, but he didn't tell how to make it.
please give me some directs, 
sincerely, thanks, best wishes!

![rrpuz7 x7rns4 9wly7m61z](https://user-images.githubusercontent.com/23737076/27896829-00837ac6-624f-11e7-93b8-b6d8a7b74325.jpg)
![56b06u x w2cs9 aphnw9h](https://user-images.githubusercontent.com/23737076/27896834-0940cd12-624f-11e7-88b9-e02ddc3f5d31.jpg)
![aaa](https://user-images.githubusercontent.com/23737076/27896916-98ce94f0-624f-11e7-8761-c671b702ca85.png)

**Comment by phpyii** [comment]
https://weituotian.github.io/AdminLTE-With-Iframe/pages/index_iframe.html

**Comment by java858** [comment]
thank you! you're awesome! 多谢了，老哥

**Comment by VSoft-Limited** [comment]
Hi please where can I get that?

**Comment by cyberzilla** [comment]
you can fork my work
https://github.com/cyberzilla/dycms
demo: https://labs.dzakiyyah.com/dycms
user&pass: admin

**Comment by 17dengfeng** [comment]
six
six
six

**Comment by infocodeart** [comment]
> https://weituotian.github.io/AdminLTE-With-Iframe/pages/index_iframe.html

Sir from where I can download.

**Comment by rickchew** [comment]
> six
> six
> six

哈哈哈..老铁可以
