### ISSUE TITLE
Question about "Right Sidebar Slide option"

### ISSUE THREAD

**Issue by sama55** [ColorlibHQ/AdminLTE#1579]
Thanks excellent theme. I have one question about "Toggle Right Sidebar Slide" option.

Behavior when checking is very good. However, when unchecking, right sidebar is fixed and we can not select skins (In other words, sidebar can not vertical scroll).

Before:
`<aside class="control-sidebar control-sidebar-dark control-sidebar-open">`

After:
`<aside class="control-sidebar control-sidebar-dark control-sidebar-open" style="position: fixed; height: auto;">`

Is this the intended specification?

**Comment by camilocamacho** [comment]
I have the same problem too

**Comment by camilocamacho** [comment]
debes agregar esto antes de app.js
```
var AdminLTEOptions = {
  controlSidebarOptions: {
    slide: false
  }
};
```
Saludos
