### ISSUE TITLE
Keep Sidebar Menu Group Open w/o being .active

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#1580]
How can I keep the sidebar menu "Support Menu" open without it being active?

I have tried .menu-open which does make the "Support Menu" caret icon point down, but the menu items isn't open...

![screen shot 2017-07-14 at 9 58 20 pm](https://user-images.githubusercontent.com/2320614/28235614-942be218-68df-11e7-8f5b-5fd0d9b2d34c.png)

I want it like

![screen shot 2017-07-14 at 9 57 15 pm](https://user-images.githubusercontent.com/2320614/28235609-74aeb5fa-68df-11e7-9046-e39bef15593a.png)

but without "Support Menu" being bright white aka .active

any ideas on how I can do that? hopefully without javascript =]

**Comment by lenamtl** [comment]
Hi check this #1476
