### ISSUE TITLE
Dont expand to full sidebar on hover when using fixed and sidebar-mini

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#1583]
I have taken a look at #336 and #840, however, neither were acceptable solutions at this time...

I am attempting to have a fixed layout with a sidebar-mini and sidebar-collapse

On hover, I want the menu to look like

![screen shot 2017-07-16 at 5 03 31 pm](https://user-images.githubusercontent.com/2320614/28251313-bb100e1c-6a48-11e7-974e-d62271ecd962.png)

Not like the following

![screen shot 2017-07-16 at 5 04 11 pm](https://user-images.githubusercontent.com/2320614/28251321-d2fd54bc-6a48-11e7-8079-c5af49775395.png)

Any ideas on how I can use a fixed layout with sidebar mini and have the menus open like the first screenshot in this post?

**Comment by jeffreyroberts** [comment]
I also found

    Because AdminLTE uses SlimScroll for the fixed layout, it is not possible to mix sidebar-mini and the fixed layout. However, there is a simple solution that AdminLTE automatically applies in case the two configurations were found active, which is expand on hover. The gif bellow shows the behavior of the sidebar when a user hovers over it and the option expand on hover is enabled. Of course, if you like this effect and prefer to use it with the normal layout, you can always enable it from the javascript options.

and I have to say, thats a great solution, however, i really could use the other solution...

**Comment by jeffreyroberts** [comment]
found some more #660 and #420

**Comment by jeffreyroberts** [comment]
ok, so from what I understand, the issue is, slimScroll will not display anything over the content area that it scrolls... i saw someone else say, challenge accepted, with this issue going back so many years, i am going to take a crack at it, there is a way to display over that content area, the fixed layout does that... so here we go

**Comment by jeffreyroberts** [comment]
this works as most want with adminlte.js, app.js, and demo.js removed, so there is a solution here, we just gotta find it =]

**Comment by islandblaze** [comment]
I think i got it!

```
body.lte-fixed {
    header.main-header {
        position: fixed;
        width: 100%;
    }
    div.content-wrapper {
        margin-top: 50px;
    }
}
```

**Comment by Choy-lingling** [comment]
[Quick fix](https://github.com/ColorlibHQ/AdminLTE/issues/1234#issuecomment-320605497)
i guess this solve the problem just add this maybe 
`  PushMenu.prototype.UnExpandOnHover = function () {
    $(Selector.mainSidebar).off();
  };`
and call the function to the app.js or demo.js to disable the hover
