### ISSUE TITLE
Can widget such as box programmatically collapse?

### ISSUE THREAD

**Issue by yuyenkan** [ColorlibHQ/AdminLTE#1588]
There is some widget like 
<button class="btn btn-box-tool" type="button" data-widget="collapse">
<i class="fa fa-minus"></i>
                </button>
to collapse/expand the box.

Now I want to expand the box by code, can it be done?

**Comment by chijinbo** [comment]
Check the doc. https://adminlte.io/docs/2.4/js-box-widget

**Comment by yuyenkan** [comment]
I am using version 2.3 or below, the box.toggleBox() is not working when there is no button with data widget

**Comment by chijinbo** [comment]
how about just listen on button click event, and using .show() , .hide() or .toggle();
