### ISSUE TITLE
Save Dashboard Position

### ISSUE THREAD

**Issue by METZGERRR** [ColorlibHQ/AdminLTE#1594]
After rearranging the dashboard in AdminLTE, switching to another url, the dashboard is back to its default – the rearrangment isn’t saving 🙁.

There is a solution posted [here](http://ultimateclientmanager.com/forums/topic/admin-lte-dashboard-rearrangment-doesnt-save/) however I can't get it to work.

`$widget_columns = array();
$widget_columns[4] = array(1=>array(),2=>array(),3=>array(),4=>array());
$widget_columns[1] = array(1=>array());
$widget_columns[3] = array(1=>array(),2=>array(),3=>array());
$widget_columns[2] = array(1=>array(),2=>array());`

Where does the lines of code need to be added?

TIA!

**Comment by REJack** [comment]
This is lines are only for the theme thats used in Ultimate Client Manager.

**Comment by METZGERRR** [comment]
is there a possibility to get it working with the standard Admin LTE?

**Comment by lenamtl** [comment]
You can save the position of each item to localstorage or DB
Check this for localstorage example with drag 
https://jsfiddle.net/5mwndskb/1/

**Comment by REJack** [comment]
This example use dragable, but we use sortable.

**Comment by mouedarbi** [comment]
Hi , i try to do the same ! I foibd this tutorial who use .sortable with sql and php : http://www.simonbattersby.com/blog/drag-and-drop-with-jquery-ui/
