### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by asadjaved63** [ColorlibHQ/AdminLTE#1599]
Codeigniter autocomplete with another theme working fine.but when i integrate in adminLte theme with proper style then its stop working and not showing suggestions list but in console showing json response as above pic shows, i tried .ui-autocomplete {z-index: 10000000;} and .ui-autocomplete {z-index: 10000000 !important;} still now working .when i comment AdminLTE.min.css and bootstrap.min.css then its works. why and how to work with in theme??

**Comment by meldin** [comment]
[https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html](url) Check Select2 and check [https://select2.org/data-sources/ajax](url) Select2 Documentation
