### ISSUE TITLE
Amend Sidebar

### ISSUE THREAD

**Issue by johnlim0211** [ColorlibHQ/AdminLTE#1600]
Greetings,

I would like to amend the sidebar as shown below so that my logo could be bigger.
Tried several ways like increased sidebar height, increased logo height and etc but not getting near to what I want. 

![untitled](https://user-images.githubusercontent.com/30790996/29013997-48a4cc5e-7b79-11e7-82be-2ecb1832fc7d.png)

Appreciate your time.
Thanks in advance.

**Comment by lenamtl** [comment]
you will need to adapt the css
```
.user-panel>.image>img {
    width: 100%;
    max-width: 45px;
}
```
