### ISSUE TITLE
Keep treeview-menu open when click

### ISSUE THREAD

**Issue by jonatasfl** [ColorlibHQ/AdminLTE#1601]
I'm using the AdminLTE template in a GIS application and this served perfectly, But I ran into a situation that I can not solve.

When I collapse the sidebar and activate (mouse over) any menu with sub items, the submenu window closes immediately after clicking on any area of it. 

![adminlte](https://user-images.githubusercontent.com/3798405/29028381-7dfd7a8c-7b5a-11e7-95a9-2fbb88624f40.gif)

To solve this, I've tried with `event.stopPropagation()` but not works.
It's possible to prevent this behavior? I need the window to close only when the mouse leaves it.

Thank you and sorry for my bad english!

**Comment by wescleymatos** [comment]
Did you try with event.preventDeafult() ?

**Comment by jonatasfl** [comment]
@wescleymatos Yes, but not works. In the Bootstrap navbar without AdminLTE, it's working well.

**Comment by REJack** [comment]
For this you need to modify the app(.min).js

**Comment by jonatasfl** [comment]
@REJack It worked! Thank you so much!

**Comment by jonatasfl** [comment]
@REJack I've Tried your solution but not works when sidebar is collapsed. It's still closing the submenu window when I click in any area of it. 

Thank you!
