### ISSUE TITLE
select2 in ipad with fastclick

### ISSUE THREAD

**Issue by yoyo837** [ColorlibHQ/AdminLTE#1604]
First and sorry, my English is not good.
When I use both select2 and fastclick, select2 does not seem to support ipad, click no response.
When I remove FastClick, select2 is work fine,
I checked the select2 github repo, it seems that no one in the maintenance of the.

**Comment by lenamtl** [comment]
There are 3 solutions, I have not tested but it's worth a try
https://gist.github.com/olimortimer/6775681
