### ISSUE TITLE
Navbar item's hover animation remains after second click

### ISSUE THREAD

**Issue by simonsmiley** [ColorlibHQ/AdminLTE#1606]
How to reproduce:
1. go to [AdminLTE](https://adminlte.io/themes/AdminLTE/index2.html)
2. click on any navbar item on the right (dropdown)
3. click on same item again
4. move pointer somewhere else

Expected Result: Hover animation not displayed

Actual Result: Hover animation still displayed

**Comment by rgychiu** [comment]
This is actually an issue with Bootstrap 3 dropdowns - even the site (https://getbootstrap.com/docs/3.3/components/#btn-dropdowns) exhibits the same behavior when double clicking the dropdown buttons. Some JS may be required to handle the double click based on the state of the dropdown; however, Bootstrap 4 does have this issue fixed, and I can only assume it'll be easier to resolve once a switch is made to BS4.
