### ISSUE TITLE
navbar dropdown-menu in skin-blue-light has white text on white background

### ISSUE THREAD

**Issue by simonsmiley** [ColorlibHQ/AdminLTE#1607]
in the [skin-blue-light.css](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/skins/skin-blue-light.css#L39) the color of links is set to white, but the background is also white making the text effectively invisible.

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?
