### ISSUE TITLE
How to properly render Comments in a Post?

### ISSUE THREAD

**Issue by motro** [ColorlibHQ/AdminLTE#1610]
Hi guys,

Could you please provide an example of how Comments should be rendered in a user's Post?
I'm referring to the Posts in the Activity tab (there's only an example of the counter) as you can see here: [https://adminlte.io/themes/AdminLTE/pages/examples/profile.html](https://adminlte.io/themes/AdminLTE/pages/examples/profile.html)

Thanks!

**Comment by lenamtl** [comment]
Suggestion

https://adminlte.io/themes/AdminLTE/pages/widgets.html
Chat box
Blog box

https://adminlte.io/themes/AdminLTE/index.html
Chat box

I'm usually take inspiration from snippets repository
https://bootsnipp.com/snippets/a35Pl
https://bootsnipp.com/snippets/gNVj0

**Comment by motro** [comment]
Thanks @lenamtl! I ended up using the example from the widget page.
I still think that there's a need for a working example in the Profile page so I'll keep this issue open.
