### ISSUE TITLE
Bug at the Profile button in the User Account when changed from btn-default to any other color e.g. btn-success

### ISSUE THREAD

**Issue by flatproject** [ColorlibHQ/AdminLTE#1611]
I have changed the Profile button from `<a href="#" class="btn btn-default btn-flat">Profile</a>` to `<a href="#" class="btn btn-success btn-flat">Profile</a>` and it works correctly when on full screen but when the window is smaller a transparent color is applied making the button color not visible. Please see below:

Full screen window (correct):
![fullscreen](https://user-images.githubusercontent.com/18282373/29282403-930ab62c-811a-11e7-849f-ab08c20918bb.PNG)

Minimal window height and width (wrong):
![minimalheightandwidth](https://user-images.githubusercontent.com/18282373/29282420-a4841920-811a-11e7-81d4-806905b3f1fb.PNG)

**Comment by lenamtl** [comment]
Confirmed..

because of this
```
@media (max-width: 767px)
_all-skins.min.css:1
.skin-blue .main-header .navbar .dropdown-menu li a {
    color: #fff;
}
```

```
@media (max-width: 991px)
AdminLTE.min.css:7
.main-header .navbar-custom-menu a, .main-header .navbar-right a {
    color: inherit;
    background: transparent;
}
```
