### ISSUE TITLE
sidebar width

### ISSUE THREAD

**Issue by tengtium** [ColorlibHQ/AdminLTE#1614]
i'm trying to find the width of sidebar and would like to change it because the text does not show as a whole..

![image](https://user-images.githubusercontent.com/3200415/29432245-7503c5e6-83cd-11e7-91fe-2ca9b73285c7.png)

**Comment by Reconix** [comment]
![untitled](https://user-images.githubusercontent.com/559757/29433004-7d16377e-8395-11e7-93fe-4790421c29af.png)

Personally I like to set it to auto
