### ISSUE TITLE
How do I get a tab to active via the URL

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#1615]
I want to navigate to http://localhost:9000/profile#subscribe and have the #subscribe tab active/open when the page loads...

How can I do that, the above url does not seem to active it...

**Comment by ernaniaz** [comment]
Hi Jeffrey.

You can add this code to your main JavaScript code:
if ( document.location.hash)
{
  $('.nav-tabs a[href="' + document.location.hash + '"]').tab ( 'show');
}
