### ISSUE TITLE
Please help me, my payment form looks horrible!

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#1617]
![screen shot 2017-08-18 at 9 40 36 pm](https://user-images.githubusercontent.com/2320614/29482368-f57eb092-845d-11e7-88ff-ae7bc29c06c1.png)

Anyone have any example payment form I can use?

**Comment by Reconix** [comment]
Like those ?
https://bootsnipp.com/tags/payment
