### ISSUE TITLE
app.js and SlimScroll for Navigation Menus

### ISSUE THREAD

**Issue by senycorp** [ColorlibHQ/AdminLTE#1621]
Hi,

is there any purpose for the existing app.js in dist/js. It is not referenced in the preview pages.
My second question is: Can i use SlimScroll in navigation menus (messages, notifications, ...). There are some options in app.js but the tree is not working when it is included.

**Comment by REJack** [comment]
I think you talk about v2.4.0-rc (used in preview too).
If yes, app.js is renamed to adminlte.js and about slimscroll i think its still a bug from v2.4.0-rc and we can hope @almasaeed2010 release soon a full release with anything fixed 😄
