### ISSUE TITLE
how can I close the sidebar with jquery

### ISSUE THREAD

**Issue by pihc** [ColorlibHQ/AdminLTE#1624]
btn add data-toggle="control-sidebar"  is ok,but I want close the sidebar with jquery,please give me some advice thanks! 

sorry! I means right sidebar,I have done my best,My solution is ` $(".control-sidebar").removeClass('control-sidebar-open').addClass('hidden');` 
I think it`s not good :sweat_smile:
does anyone have other better soluntions?:sunglasses:

**Comment by REJack** [comment]
To close the sidebar (collapse) `$("body").addClass('sidebar-collapse').trigger('collapsed.pushMenu');` 
and to open it again `$("body").removeClass('sidebar-collapse').trigger('expanded.pushMenu');`
