### ISSUE TITLE
TypeError: $layout is undefined

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#1626]
When clicking on FixedLayout or BoxedLayout of control-side bar's Layout Options , I saw the error log 
`TypeError: $layout is undefined`
on firefox developer console. You can also check this on your[ demo application](https://adminlte.io/themes/AdminLTE/index2.html). How should I fix this ?

**Comment by mrjooz** [comment]
add `$('body').layout()` in demo.js
```js
$('[data-toggle="push-menu"]').pushMenu()
$('[data-toggle="control-sidebar"]').controlSidebar()
$('body').layout()

var $pushMenu = $('[data-toggle="push-menu"]').data('lte.pushmenu')
var $controlSidebar = $('[data-toggle="control-sidebar"]').data('lte.controlsidebar')
var $layout = $('body').data('lte.layout')
```
