### ISSUE TITLE
Treeview menu closing when clicking on sub menus

### ISSUE THREAD

**Issue by JoCodes** [ColorlibHQ/AdminLTE#1629]
Hi,
I'm using trying out  AdminLTE in asp.net mvc project ( using AdminLTE 2.2.3 installed through nuget package ) . Everything works fine except the Treeview with submenus. 
Issue: 
The Treeview gets closed when any of the submenus inside it is clicked. Also, the clicked item is not active state too. 
Layoutpage view source 
-----------

```
<!-- Sidebar Menu -->
--
   <ul class="sidebar-menu">
   <li class="header">HEADER</li>
   <!-- Optionally, you can add icons to the links -->
   <li class="active"><li role="presentation" class="active"><a href="/">Home</a></li></li>
  <li><li role="presentation"><a href="/Home/About">About</a></li></li>
   <li><li role="presentation"><a href="/Home/Contact">Contact</a></li></li>
   
   <li class="treeview">
  <a href="#"><i class="fa fa-link"></i> <span>Masters</span> <i class="fa fa-angle-left pull-right"></i></a>
   <ul class="treeview-menu">
   <li ><a href="/Clients">Clients</a></li>
   <li><a href="/Divisions">Divisions</a></li>
   <li><a href="/Manufacturers">Manufacturers</a></li>
   <li><a href="/incoTerms">incoTerms</a></li>
  
   </ul>
   </li>
   </ul>
  <!-- /.sidebar-menu -->
```

app.js ( treeview script )
-------
$.AdminLTE.tree = function (menu) {
    var _this = this;
    var animationSpeed = $.AdminLTE.options.animationSpeed;
    $(document).on('click', menu + ' li a', function (e) {
      //Get the clicked link and the next element
      var $this = $(this);
      var checkElement = $this.next();

      //Check if the next element is a menu and is visible
      if ((checkElement.is('.treeview-menu')) && (checkElement.is(':visible')) && (!$('body').hasClass('sidebar-collapse'))) {
        //Close the menu
        checkElement.slideUp(animationSpeed, function () {
          checkElement.removeClass('menu-open');
          //Fix the layout in case the sidebar stretches over the height of the window
          //_this.layout.fix();
        });
        checkElement.parent("li").removeClass("active");
     
      }
      //If the menu is not visible
      else if ((checkElement.is('.treeview-menu')) && (!checkElement.is(':visible'))) {
        //Get the parent menu
        var parent = $this.parents('ul').first();
        //Close all open menus within the parent
        var ul = parent.find('ul:visible').slideUp(animationSpeed);
        //Remove the menu-open class from the parent
        ul.removeClass('menu-open');
        //Get the parent li
        var parent_li = $this.parent("li");

        //Open the target menu and add the menu-open class
        checkElement.slideDown(animationSpeed, function () {
          //Add the class active to the parent li
          checkElement.addClass('menu-open');
          parent.find('li.active').removeClass('active');
          parent_li.addClass('active');
          //Fix the layout in case the sidebar stretches over the height of the window
          _this.layout.fix();
        });
        
      }
      //if this isn't a link, prevent the page from being redirected
      if (checkElement.is('.treeview-menu')) {
        e.preventDefault();
      }
    });
  };
Any help appreciated.Thanks in advance,

**Comment by amsharma9** [comment]
I have the same issue using AdminLTE with a MVC framework Phalcon on Wampserver using Apache 2.4.23 & Php 7.0.10. If the side menu is larger than the screen then it refreshes every time I click a submenu although it does get `active`. My custom code in app.js includes below:

```
// Remove active for all items.
$('.page-sidebar-menu li').removeClass('active');

// highlight submenu item
$('li a[href="' + this.location.pathname + '"]').parent().addClass('active');

// Highlight parent menu item.
$('ul a[href="' + this.location.pathname + '"]').parents('li').addClass('active');
```

This is from a StackOverflow solution [Twitter Bootstrap add active class to li](https://stackoverflow.com/a/20780553)
