### ISSUE TITLE
image and buttons on the data list row with edit option

### ISSUE THREAD

**Issue by VJSash** [ColorlibHQ/AdminLTE#1635]
Hello,

Is there any option in data list to show the image and when click that row to open the popup..? 
images for the reference...
![22](https://user-images.githubusercontent.com/31687058/30152203-0b9f49b4-93d0-11e7-914b-c2d5c5d97041.png)

when click the edit button in the list, the below popup will open.
↓
↓
![12](https://user-images.githubusercontent.com/31687058/30152876-402682ae-93d2-11e7-8af1-d7a915046253.png)

please give me an idea...

**Comment by lenamtl** [comment]
Hi, this is out of the scope of the template ...

Suggestion you can use Datatables and some custom adjustment..

You can have a details view or a modal view just check for responsive plugin.
This will work as long as the information to edit is available from the table.
I would set the latest column as a tool column and always displayed as the latest.

Also Datatables have an editor that you can buy, you can try it for free and it' having the popup form too.

They have a documentation and a forum so you ask for more details
Good luck
