### ISSUE TITLE
Sidebar fixed, disappearing while scrolling on iOS11

### ISSUE THREAD

**Issue by fabiensen** [ColorlibHQ/AdminLTE#1642]
we published several apps based on Cordova for iOS. The graphical interface framework we used was AdminLTE, derived from Bootstrap. In all the apps, we have a sidebar, whose position is fixed in CSS. Beside it, we have a scrollable content. Everything was fine until iOS 10, but now we have a strange behaviour. Scrolling the content, the sidebar simply disappears. I have read many suggestions, e.g. here (https://stackoverflow.com/questions/37914983/overflow-scrolling-not-working-on-position-fixed-element-ios). None of the solutions really work. But the strangest thing is that this behaviour only started in betas of iOS11 (while the proposed solutions are from iOS 5 and later).

When I say it does not work, I mean that this fix, recommended by most ones in SO:

```
.main-sidebar * {
    transform: translate3d(0,0,0); }
```

applies correctly only to the first inner element of .main-sidebar, while the other sub-elements still disappear, when scrolling, to re-appear when scrolling has ended.

So, anybody has faced this particular situation?
Thanks

**Comment by ortega18** [comment]
I have the same problem. Have you solved it? :(

**Comment by adamhong** [comment]
also have the same problem

**Comment by sijakret** [comment]
same here.
the problem seems to be:
if you have a scrolling container and an element nested inside of it that has position: fixed you get this rendering artifact.
As long as your fixed element can be moved outside of the scrolling container this will fix it.
However in some designs this is not possible and it shouldn't be necessary. its a bug in the web view.

**Comment by liwenlong** [comment]
the same problem with me .
anyone know how to solve it ?

**Comment by dannlc** [comment]
same problem, and it seems there's no fix for this.
