### ISSUE TITLE
Chart.js JS error - out of the box

### ISSUE THREAD

**Issue by zendozerris** [ColorlibHQ/AdminLTE#1644]
Line 1565 : index2.html
out : <script src="bower_components/Chart.js/Chart.js"></script>
replace by <script src="bower_components/chart.js/Chart.js"></script>

Line 707 : pages/charts/chartjs.html
out : <script src="../../bower_components/Chart.js/Chart.js"></script>
replace by : <script src="../../bower_components/chart.js/Chart.js"></script>infinity

Very great job beyond

FC-KAR

**Comment by almasaeed2010** [comment]
Hello,

Did you download the package from the master branch or install it with npm/bower?

Downloading directly from master does not yield the issue but it could be present with a package manager. 

Thanks!

**Comment by zendozerris** [comment]
Hello

I installed it with bower

BR

Florent

2017-09-19 1:55 GMT+02:00 Abdullah Almsaeed <notifications@github.com>:
