### ISSUE TITLE
Multi-level menu problem

### ISSUE THREAD

**Issue by hkhv** [ColorlibHQ/AdminLTE#1648]
I found that when the three-level menu is open, I directly let the menu shrink, open again, the right of the icon is wrong
![screenshot from 2017-09-18 15-06-47](https://user-images.githubusercontent.com/28698877/30531919-d7903f8a-9c16-11e7-954a-2b021eefded9.png)

**Comment by almasaeed2010** [comment]
Thanks for reporting the issue. Could you please provide the version number of AdminLTE? Or is this the live demo?

Thanks!

**Comment by hkhv** [comment]
Version 2.4.0  https://adminlte.io/themes/AdminLTE/index2.html

**Comment by almasaeed2010** [comment]
I tried to duplicate the issue several times but it isn't happening on my end. Which browser are you using?

**Comment by hkhv** [comment]
Hello
 I directly let the menu shrink, open again, the right of the icon is wrong, the right arrow should be down instead of left. 
![screenshot from 2017-10-10 09-57-35](https://user-images.githubusercontent.com/28698877/31366030-95ffa96e-ad34-11e7-847f-22652d3a2228.png)
