### ISSUE TITLE
IP mask not working on mobile

### ISSUE THREAD

**Issue by mmucino1** [ColorlibHQ/AdminLTE#1657]
The IP input mask works on Desktop/Laptop display but not in mobile display.

**Comment by bellwood** [comment]
Example of the code you are running?

**Comment by bellwood** [comment]
Testing the 2.4 examples page here:

https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html

I am unable to reproduce the issue on IOS Chrome/Safari for the IP mask type.

Screenshot, browser details and a snippet of your markup would be helpful.

**Comment by kabutotx** [comment]
Doesn't work correctly on my Galaxy s8+ with chrome.  It does the same thing on the inputmask github demo site, so it is a problem with inputmask and needs to be reported to the project.  FYI doesn't work with predictive off either.
