### ISSUE TITLE
adminlte sidebar-toggle is not working and sidebar is refreshing

### ISSUE THREAD

**Issue by yeonsora** [ColorlibHQ/AdminLTE#1659]
hi all,

I have some problem in sidebar.

I use adminlte 2.3.8 by spring in localhost

1. when i click 'sidebar-toggle' button, sidebar was changed slim-sidebar like bellow picture.

![image](https://user-images.githubusercontent.com/14935613/30955352-4542674c-a46e-11e7-854e-d52b3021cdff.png)

but, when i mouse over the icon, I can't see sidebar-menu like adminlte example.

![image](https://user-images.githubusercontent.com/14935613/30954226-5d9e58b8-a46a-11e7-982c-b61b0e23aea2.png)

How can i do?

2. My sidebar can't save status.

When i click treeview and treview-menu, a page go to next while refreshing a sidebar!

How can i save sidebar status?

**Comment by sgtHerbert** [comment]
Got it. I had the same issue.
I deployed AdminLTE on a ASPnet MVC5 project and spotted that the app.js of adminlte downloaded is the wrong one and did not comport the button listener for the top-left toggle button. replace your adminLTE.js or app.js( adminlte main javascript file) with the file of the demo( https://adminlte.io/themes/AdminLTE/starter.htm).
May i suggest to almasaeed a modification of the visual studio package for a better organisation and nomination of the js file.

**Comment by Mahmoudz** [comment]
Set data-toggle to push-menu: `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">` Then add data-widget = tree: `<ul class="sidebar-menu" data-widget="tree">`.

**Comment by REJack** [comment]
For sidebar state remember, look at [this](https://github.com/almasaeed2010/AdminLTE/issues/1240#issuecomment-258836748)

**Comment by KaloyNayve** [comment]
> Set data-toggle to push-menu: `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">` Then add data-widget = tree: `<ul class="sidebar-menu" data-widget="tree">`.

Thanks this did the trick!
