### ISSUE TITLE
app.min.js not found

### ISSUE THREAD

**Issue by alexeydg** [ColorlibHQ/AdminLTE#1673]
I'm trying to add this to the basic Yii2 template.

Views are working fine and css is loading, but there is no js.

There is a 404 error for /assets/xxxxx/js/app.min.js

When I check the assets folder the only js file in there is adminlte.min.js and the uncompressed version (And looking again looks like there is demo.js).

Have I made a config error? I have this working fine with the advanced starter template but I can't see any different config values that might stop the js from loading.

**Comment by Tjoosten** [comment]
Have u checked your code in the Yii2 framework. Personnally i think u made there an error.

**Comment by REBELinBLUE** [comment]
I could be wrong but I believe app.min.js was renamed to adminlte.min.js in 2.4.0

**Comment by acacha** [comment]
@REBELinBLUE yes see: https://adminlte.io/docs/2.4/upgrade-guide

**Comment by rishad2m8** [comment]
@REBELinBLUE, It's now `adminlte.min.js`.  Like @acacha said, please check [ https://adminlte.io/docs/2.4/upgrade-guide](https://adminlte.io/docs/2.4/upgrade-guide) for upgrade guide and new changes.

**Comment by REBELinBLUE** [comment]
I know, I was responding to the op who was looking for `app.min.js` ;)
