### ISSUE TITLE
Horizontal scroll reveals right menu

### ISSUE THREAD

**Issue by ilgrosso** [ColorlibHQ/AdminLTE#1674]
When scrolling horizontally, the right-side menu is revealed, even partially:

![image](https://user-images.githubusercontent.com/1064664/31370868-3d5e3ec4-ad8e-11e7-8c8e-0158d3d62236.png)

This issue (with a potential fix) was reported as https://issues.apache.org/jira/browse/SYNCOPE-1092

**Comment by bellwood** [comment]
What layout type are you using (it's not stated in the linked bug report either)

With content-wrapper being responsive I'm not able to force a horizontal scroll situation to reproduce.

General question, are you sure your markup is valid and not missing any closing tags?

**Comment by ilgrosso** [comment]
Thanks for your answer @bellwood 

The screenshot above is taken from https://adminlte.io/themes/AdminLTE/index2.html

**Comment by bellwood** [comment]
What browser/OS are you using?

Even resizing the demo page, playing with zoom, everything is responsive so I do not see h-scroll 😞

**Comment by ilgrosso** [comment]
I am on Linux.

No need to resize: I just scroll horizontally with the two-figers gesture on the onboard mousepad.

**Comment by bellwood** [comment]
> I just scroll horizontally with the two-figers gesture on the onboard mousepad.

On my MacBook Chrome/Safari when I do this I just see whitespace.

What browser are you using?

**Comment by ilgrosso** [comment]
> What browser are you using?

I've tried with Chromium, Chrome and Firefox (latest versions), with same results.

**Comment by bellwood** [comment]
Oddly, in OSX Firefox, I'm unable to preform the two finger swipe, the page remains static.

Sorry, I'm not much help on this one 🙁
