### ISSUE TITLE
AdminLTE on mobiles and tablets

### ISSUE THREAD

**Issue by molorane** [ColorlibHQ/AdminLTE#1676]
Hello sir, i am currently using your template(version 2.3.3) for my admin console. I am running it on apache PHP 7. However, i noticed that when try to view it on the browsers for mobile devices and tablets, it looses the styles. The page appears as though there are no style sheets applied to the them. I am wondering why this happens and would like to get help. I tried to allow javascript on the privacy settings for the browsers of the mobile devices but that didn't solve the problem. will waiting to hear from you.

**Comment by bellwood** [comment]
Can you share a view-source snippet of your markup that includes the loaded styles.

It could be something as simple as your mobile devices don't have access to the path your styles are on, such as a hardcoded path to files on a desktop, self-signed certificate issue, mixed content issue, etc

As an alternative, when loading the page in a mobile device, tail apache's access/error logs to see the path being requested for the styles...
