### ISSUE TITLE
Bower install doesn't works. Jquery resolution problem

### ISSUE THREAD

**Issue by acacha** [ColorlibHQ/AdminLTE#1680]
Unable to find a suitable version for jquery, please choose one by typing one of the numbers below:
    1) jquery#^2.0 which resolved to 2.2.4 and is required by bootstrap-timepicker#0.5.2
    2) jquery#>=1.7 which resolved to 3.2.1 and is required by datatables.net#1.10.16, datatables.net-bs#2.1.1, inputmask#3.3.9
    3) jquery#1.9.1 - 3 which resolved to 3.2.1 and is required by bootstrap#3.3.7, bootstrap-daterangepicker#2.1.25
    4) jquery#>=1.7.1 <4.0.0 which resolved to 3.2.1 and is required by bootstrap-datepicker#1.7.1
    5) jquery#>= 1.2.6 which resolved to 3.2.1 and is required by Flot#0.8.3
    6) jquery#>=1.7.0 which resolved to 3.2.1 and is required by jquery-knob#1.2.13
    7) jquery#>=1.10 which resolved to 3.2.1 and is required by bootstrap-colorpicker#2.5.1
    8) jquery#>= 2.1.0 which resolved to 3.2.1 and is required by morris.js#0.5.1
    9) jquery#2 - 3 which resolved to 3.2.1 and is required by fullcalendar#3.6.1
    10) jquery#>=1.8 which resolved to 3.2.1 and is required by ion.rangeSlider#2.2.0
    11) jquery#>=1.6 which resolved to 3.2.1 and is required by jquery-ui#1.11.4
    12) jquery#^3.2.1 which resolved to 3.2.1 and is required by admin-lte
```

Maybe as seen on https://stackoverflow.com/questions/40385680/unable-to-find-a-suitable-version-for-jquery we can add a resolution option to bower.json but I'm not sure which version to user 3.2.1?

**Comment by AizeLeOuf** [comment]
Same here, with jquery 3.2.1 can't fidn a suitable version because bootstrap-timepicke support only ^2.0

**Comment by ericksonsv** [comment]
Same here too.

**Comment by miguelAliaga** [comment]
try to add the code below in your bower config
`"resolutions": { 
    "jquery": "2.2.4" 
}`

**Comment by aepp** [comment]
> try to add the code below in your bower config
worked for me
