### ISSUE TITLE
AdminLTEOptions not working in v2.4?

### ISSUE THREAD

**Issue by tegola** [ColorlibHQ/AdminLTE#1694]
I'm using version 2.4 for setting up a simple admin panel for a client and I just wanted to customize the default collapse/expand icons, so here's my setup:

```html
<script>
var AdminLTEOptions = {
  boxWidgetOptions: {
    boxWidgetIcons: {
      collapse: 'fa-chevron-up',
      open: 'fa-chevron-down',
      remove: 'fa-times'
    }
  }
};
</script>
<script src="/js/adminlte.min.js"></script>
```

```html
<div class="box box-default collapsed-box">
  <div class="box-header">
    <h3 class="box-title">Notes</h3>
    <div class="box-tools">
      <a class="btn btn-box-tool" href="#">
        <i class="fa fa-plus"></i> Add
      </a>
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-chevron-down"></i>
      </button>
    </div>
  </div>
  ...
</div>
```

The expand button above works, but the icon that's changing is the "plus" one. I'm assuming the `AdminLTEOption` var is not working anymore like in previous versions?

**Comment by bellwood** [comment]
`AdminLTEOptions` doesn't appear within `adminlte.min.js` as it did within `app.min.js` so one would assume it's been removed.

@almasaeed2010 if removed, the upgrade docs should be notated.

**Comment by yizeng** [comment]
Maybe it will be brought back in version 2.4.4.

See almasaeed2010's comment:
> I am currently working on 2.4.4 which will bring back support to v2.3.* and provide some fixes to the current version. Until then, I'll keep this issue open.

 https://github.com/almasaeed2010/AdminLTE/issues/1669#issuecomment-336122176

**Comment by techtoniq** [comment]
Hi any news on this? I'm trying to use AdminLTEOptions to change the speed of an expanding box and the options are being ignored and I really would rather avoid editing the source.

**Comment by REJack** [comment]
You can change the animation speed with a data attribute like `data-animation-speed="1500"` for a 1500ms animation.

**Comment by techtoniq** [comment]
Great! That's working for me, thanks.

**Comment by h4de5** [comment]
as of version 2.4.12 `AdminLTEOptions` is still listed in the documentation, but nowhere in the source. so it seems not to be in use at all.

**Comment by REJack** [comment]
AdminLTEOptions was removed with v2.4, you can now set simply data attributes to change options. I look over the documentation to display all new options and remove the  AdminLTEOptions part.
