### ISSUE TITLE
Bootstrap 4 Beta Support?

### ISSUE THREAD

**Issue by vibs2006** [ColorlibHQ/AdminLTE#1695]
As Bootstrap 4 Beta (Stable) is released now so any update on bootstrap 4 support?

**Comment by You85** [comment]
+1

**Comment by skendrot** [comment]
@REJack Is there an PR associated with this?

**Comment by REJack** [comment]
Yep checkout my PR draft with new changes or the v3-dev

**Comment by skendrot** [comment]
Can you link the PR # here please. So everyone can find it easily

**Comment by REJack** [comment]
#2167 you can checkout [the demo](https://adminlte.io/themes/dev/AdminLTE/) too.
