### ISSUE TITLE
Sidebar open without animation once

### ISSUE THREAD

**Issue by yuyenkan** [ColorlibHQ/AdminLTE#1699]
I want to open & calculate the size of sidebar in one function, is there a function to open it without delay & animation once?

**Comment by almasaeed2010** [comment]
You would have to manually apply the css instead of using the classes.

```js
// close
$('.sidebar').css('transform', 'translateX(-250px)');

// open
$('.sidebar').css('transform', 'translateX(250px)');
```

Thanks!

**Comment by yuyenkan** [comment]
But it will make some problem? I don think manually do this will be good?
