### ISSUE TITLE
Two scroll bar vertical in my Adminlte 

### ISSUE THREAD

**Issue by azzario** [ColorlibHQ/AdminLTE#1700]
Hi,

i have some problem with my dashboard maybe you can fix this.
This is my bug : 

![two-scroll](https://user-images.githubusercontent.com/28214915/31801855-fec2d262-b574-11e7-9215-b5fa8db509d6.PNG)

When i scroll down
![bug](https://user-images.githubusercontent.com/28214915/31801871-1614fb2a-b575-11e7-9e57-86119419e60f.PNG)

Thanks! hope you can help me

**Comment by lenamtl** [comment]
You have a div issue

**Comment by almasaeed2010** [comment]
I don't have windows, so testing is a bit difficult. Does the issue occur on the live demo?
https://adminlte.io/themes/AdminLTE/index2.html

Thanks!

**Comment by ismirsehregal** [comment]
This answer provided by erikrs92 works:
[https://github.com/almasaeed2010/AdminLTE/issues/1418](https://github.com/almasaeed2010/AdminLTE/issues/1418)

**Comment by cleatuskeetz** [comment]
@almasaeed2010 
Hi,
I also facing the same issue. Its not on the live demo. While we make our own pages and making changes in the <section> for Main content it is happening.
How can I resolve this?_

**Comment by Raghavendrssnk** [comment]
If Your Using Asp.net MVC Under Content Folder there is site.css Make it empty and save.. it may Solve the problem
