### ISSUE TITLE
Sidebar Scroll does not work when window is maximized at first load. 

### ISSUE THREAD

**Issue by VikoBastidas** [ColorlibHQ/AdminLTE#1705]
At first load, when you activate "Fixed layout", it does not work when the window is maximized. You need to resize to make it work.

**Comment by VikoBastidas** [comment]
Steps to replicate issue:
a. Open browser window.
b. Maximize browser window.
c. Load AdminLTE URL (localhost)
d. Activate "Fixed layout" option.
e. Now try to scroll sidebar, it does not scroll.

**Comment by DarioN1** [comment]
I'm having the same problem... Do you have any news ?
