### ISSUE TITLE
Rendering of box is not perfect

### ISSUE THREAD

**Issue by yuyenkan** [ColorlibHQ/AdminLTE#1706]
![image](https://user-images.githubusercontent.com/22000244/32033303-6e65c0e8-ba3e-11e7-886c-e8075c99f688.png)

As shown in the image, some of the box with top or bottom white line when collapsed.

**Comment by lenamtl** [comment]
Make sure you have the correct code ...

**Comment by yuyenkan** [comment]
I found the problem, it is a problem when zoom the content above 100%....., it occur on all browser.

**Comment by almasaeed2010** [comment]
<img width="1079" alt="screen shot 2017-10-29 at 12 06 34 pm" src="https://user-images.githubusercontent.com/1512664/32145600-b005d654-bca1-11e7-8a25-85a90aa866e6.png">

This is a zoomed-in collapsed box and it has no white line. Are you sure you are using the correct markup?

Thanks!

**Comment by yuyenkan** [comment]
try it multiple, because it not always happen.  and mine is browser page zoom 115%.

**Comment by bellwood** [comment]
@yuyenkan: What browser, version and OS? Does the same occur if you use another browser on the same OS with the same 115% zoom level?

**Comment by yuyenkan** [comment]
OS: Window 10, 
Browser & Version: 
- Google Chrome  61.0.3163.100
- Microsoft Edge 40.15063.674.0
- IE 11.674.15063.0

Yes, I tried browser list at above, all of them with same rendering.

**Comment by bellwood** [comment]
Confirmed in OSX chrome but not OSX Safari (latest versions)

In Chrome, for the case of a "box-default", if i change:

```
.box.box-solid.box-default {
    border: 1px solid #d2d6de;
}
```
...to...
```
.box.box-solid.box-default {
    border: 2px solid #d2d6de;
}
```

it goes way... Browser/render bug perhaps?
