### ISSUE TITLE
AdminLTE JS compatibility with SPA JavaScript frameworks

### ISSUE THREAD

**Issue by riklaunim** [ColorlibHQ/AdminLTE#1710]
AdminLTE JS file seems to do a lot of stuff on document-ready state. That works on its own, but problems can/do show up when I use SPA frameworks like Ember.js - not only that main layout of AdminLTE may show up on other than starting routes things like sidebar height maybe a problem as well.

Can the adminlte.js functions be named and accessible so that I can call them when actually needed?

**Comment by almasaeed2010** [comment]
All of adminte's JS plugins are configurable using the API. Please review the JS docs:
https://adminlte.io/docs/2.4/js-layout

Thanks!

**Comment by queuetest** [comment]
@almasaeed2010 i had similar problem with my angular where the page height is broken after router navigation.

$('body').layout('fix');

adding this on my template initialization fixed the issue for me.
thanks a lot!

**Comment by martinmanzo** [comment]
Hi @queuetest, I'm facing the same issue. Adding $('body').layout('fix'); fixed the main layout. But it doesn't fix other elements such as the sidebar's nested elements and the panels minimizations. Did you find a fix for that?
