### ISSUE TITLE
datepicker issue

### ISSUE THREAD

**Issue by hsl1** [ColorlibHQ/AdminLTE#1714]
i Have a filed with a datepicker.
i have 2 problems with this element.
See this link http://prntscr.com/h40onf when i click on the year i wan it to open like this http://prntscr.com/h40qcv and not the way it shows 

Second problem is that i want it to open if the user clicks on the textbox or on the calendar icon 

Using this but not working

  $('#dateofbirth').datepicker(
        {
            allowInputToggle: true
        })

Using this code on html

    <div class="form-group">
                                                <label for="dateofbirth" class="col-sm-2 control-label">Date</label>
                                                <div class="col-sm-10">
                                                    <div class="input-group date" >
                                                        <input type="date" class="form-control" ng-model="client.dateofbirth" ng-required="true" /><span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
                                                   
                                                    </div>
                                                </div>
                                            </div>

i'm using  AdminLTE v2.3.8
And i like the today button so i want it to stay

Sorry but i dont see a way to upload images

**Comment by bellwood** [comment]
For your first issue, you might lodge a question/issue over at the repo for datepicker:

https://github.com/uxsolutions/bootstrap-datepicker

...as that would be a customization of the display of that dependancy.

For your second issue, you are binding `.datepicker()` to `#dateofbirth` but i do not see an id of `#dateofbirth` in your provided markup.
