### ISSUE TITLE
Fixed layout forcing expand on hover for sidebar mini

### ISSUE THREAD

**Issue by mojohub** [ColorlibHQ/AdminLTE#1715]
I'm using latest 2.4.2 and have added "fixed" to the body tag but when the menu is in mini mode the menu expands on hover instead of the menu items pulling out to the right.

The documentation only says the fixed layout cannot work with boxed layout but mentions no other limitation. I can also see in the demo.js the function changeLayout forces $pushMenu.expandOnHover() for fixed class.

Why is this and can the fixed layout work without expanding the sidebar menu?

**Comment by lainlee** [comment]
Exactly, the same problem to me
version: "2.4.2"

I search the source code an find this

```
if (this.options.expandOnHover || ($('body').is(Selector.mini + Selector.layoutFixed))){
    this.expandOnHover() 
    $('body').addClass(ClassName.expandFeature)
}
```

Does it for some special purpose? 
I really need it not bind the 'hover' event when I use layout 'fixed' and 'mini'
Hope to your relpy
