### ISSUE TITLE
Overflow when treeview menu click

### ISSUE THREAD

**Issue by azzario** [ColorlibHQ/AdminLTE#1718]
When i click on sidebar treeview menu
![click-treeview](https://user-images.githubusercontent.com/28214915/32264559-df5f93be-bf11-11e7-8fe1-84d0e45be850.PNG)

The other scroll bar show and hide
![treeview-scroll](https://user-images.githubusercontent.com/28214915/32264651-47961692-bf12-11e7-8200-08511523971b.PNG)

How to fix this? thanks

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?
