### ISSUE TITLE
app.min.js is missing

### ISSUE THREAD

**Issue by shqear93** [ColorlibHQ/AdminLTE#1723]
Hi Abdullah, some repos built on old versions of AdminLTE has stopped working bcz you removed the file **app.min.js** since version 2.4.0
I already posted an issue in [dmstr/yii2-adminlte-asset](https://github.com/dmstr/yii2-adminlte-asset/issues/149) to solve this, but i don't know how! i tried to use the file adminlte.js instead but the navigation menu still not working.

**Comment by dyzajash** [comment]
Upgrade guide: https://adminlte.io/docs/2.4/upgrade-guide

Menu fix is second paragraph.
