### ISSUE TITLE
Nested boxes collapsing bug

### ISSUE THREAD

**Issue by Karmalakas** [ColorlibHQ/AdminLTE#1725]
OK, so I've seen issues #321, #523 and #524.

One of them is, if box is collapsible and contains a form, pressing `Enter` for submit, collapses the box.
Other issue is, collapsing the child box, doesn't collapse the box you want, but collapses the most top holder box, even if this holder box doesn't have a button to collapse, so there's no way to expand it anymore. Even if the child box is collapsed, trying to expand it, collapses the holder box.

Now I'm experiencing this whole collapsing of child boxes problem. Any chances of fixing that?
Using v2.4.0

Thanks

**Comment by Karmalakas** [comment]
I couldn't see in changelog nothing about that, but it seems it's working as expected in 2.4.2

**Comment by ilbassa** [comment]
I have the same problem of box in a box, when I try to open the nested box the parent collapse.
I have v2.4.2 installed

**Comment by REJack** [comment]
This issue doesn't appear in v2.4.13 anymore, if this issue still exists create a new issue.
