### ISSUE TITLE
user list inside tabpane

### ISSUE THREAD

**Issue by hsl1** [ColorlibHQ/AdminLTE#1728]
hi,

i have admin lte 2.3.8 and i have this code (user list) inside a tab pane  but the images dont format well

code here ( because github code wont show html code) https://jsfiddle.net/a37u81y8/

it lookes strange http://prntscr.com/h8u4a6
Thanks for your help

**Comment by almasaeed2010** [comment]
Images should be the same size and have square dimensions (equal height and width. e.g, 100X100)

**Comment by hsl1** [comment]
Cool that works
But i have another litle problem wich is when i have the window in full size the space between 2 images next to other is too much but when i resize the windows seems fine
