### ISSUE TITLE
Image in Sidebar

### ISSUE THREAD

**Issue by flcortesT** [ColorlibHQ/AdminLTE#1734]
### Issue type:
[ ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by flcortesT** [comment]
I would like to know how can I include image in Sidebar ?

**Comment by almasaeed2010** [comment]
Hello @flcortesT 

Please provide more information on the issue for us to be able to help. E.g, where would you like the image precisely (above, under or in the treeview menu)?

In general, you can add an image using the responsive image class:
```
<img class="img-responsive" src"/path/to/image"/>
```

Thanks!
