### ISSUE TITLE
Missing pages when printing

### ISSUE THREAD

**Issue by rip747** [ColorlibHQ/AdminLTE#1736]
### Issue type:
[ ] Feature request 
[x ] Bug report      
[ ] Documentation   

### Environment:
* AdminLTE Version:  2.3.11
* Operating System:  windows
* Browser (Version):  Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Description:

When printing a long page, some pages are cutoff in portrait mode, however they are available in landscape mode.

I have found this is a problem with Bootstrap 3.0 itself as described in their bug:
https://github.com/twbs/bootstrap/issues/22425

The work around is to add page-break-after: always; to the .container:

.container {
	page-break-after: always;
}

I also had to cancel out the padding on the .box-body:

@media print {
	.box-body {
		padding: 0;
	}
}

Hope this helps someone

**Comment by shiri1248** [comment]
Hi @almasaeed2010 , can i work on this issue ?
