### ISSUE TITLE
AdminLTE - DropDown Menu on LOGO location

### ISSUE THREAD

**Issue by kilroyFR** [ColorlibHQ/AdminLTE#1743]
hey there, i am trying to add some submenu items using DropDown on top navbar where logo is located
![adminlte](https://user-images.githubusercontent.com/31513956/33218456-424628c0-d13d-11e7-9207-b6dc5aabf42d.png)

=> adding Version Informations and About Application menu items (available when clicking on arrow)

Could not succeed in making this possible for now. Anyone did find a solution ?

**Comment by lenamtl** [comment]
You can provide a jsfiddle / codepen with your code
https://cdnjs.com/libraries/admin-lte

To my opinion adding this is not user friendly
Some suggestion
You can put some software version in the footer and add a menu item to the left menu?
Depending of the quantity of information can can create a bigger footer that have all infos...
