### ISSUE TITLE
Laravel 5.5 install

### ISSUE THREAD

**Issue by phpgraham** [ColorlibHQ/AdminLTE#1746]
Have installed AdminLTE using composer into a clean Laraval 5.5 install:

composer require "almasaeed2010/adminlte=~2.4"
which creates /vendor/almasaeed2010/adminlte folder

Now what ?
Do I manually move folder/files to public folder, if so which files/folders are needed - assume I want to use all components and features?
I understand I probably need to manually create blade files to convert AdminLTE to Laravel5.5 usage

Seems instructions fall short, run composer and thats it? really!?!, doesn't seem complete to me.

**Comment by bellwood** [comment]
It is upon you to create the blades and integration. Installing via composer just allows you to manage the package.

If you are looking for "easy" integration, take a look at:

https://github.com/jeroennoten/Laravel-AdminLTE

It is worth noting that while this works nicely, small things like SlimScroll are missing.

**Comment by acacha** [comment]
You can also be interested in this project: https://github.com/acacha/adminlte-laravel

**Comment by adamnator92** [comment]
the docs installation is not very clear, it seem like you have to manually move the downloaded package to public directory.
