### ISSUE TITLE
Responsive Logo in Header on Ver 2.4.2

### ISSUE THREAD

**Issue by freesoftwarewiz** [ColorlibHQ/AdminLTE#1747]
### Issue type:
[ ] Feature request 
[ ] Bug report      
[ x] Documentation   

You Need a category for "[ x] Informational Help"

### Environment:
* AdminLTE Version:  2.4.2
* Operating System:  OSX
* Browser (Version):  Chrome (Latest)

### Description:

I would like to know where and how to make the header 'logo' actually **a responsive image** instead of text logo like the "adminLTE" (logo images for both mini and large)?

There is no guidance in the documentation on making obvious _changes_ like this to things like the logo, adding/changing menu items in the header and side bar, etc.

**AND** 
there needs to be a distribution guide: 
what files and directories are REQUIRED (minimum) to have/distribute a functional adminlte panel on your website, and what is not absolutely necessary? (For example, I would assume the 'documentation' directory is not required to be there if you are setting up a functional, customized version of the panle on you site.)

Thank you for your help :-)

**Comment by desenvolvedorindie** [comment]
Possible solution

.logo img {
    padding: 4px;
    object-fit: contain;
    margin: 0 auto;
}

.logo .logo-lg img {
    max-width: 200px;
    max-height: 50px;
}

.logo .logo-mini img {
    max-width: 50px;
    max-height: 50px;
}

**Comment by Astriel** [comment]
Hey @desenvolvedorindie did you manage to make it work ? Not working for me even with this code :/

**Comment by REJack** [comment]
@desenvolvedorindie Nice code, I've added it in v2.4.13.

@Astriel may your markup isn't correct, it work with this markup
```html
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><img src="dist/img/logo-xs.png"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><img src="dist/img/logo-xl.png"></span>
    </a>
```
