### ISSUE TITLE
Problem with sidebar when the screen its @lower than 770px

### ISSUE THREAD

**Issue by 72OTA** [ColorlibHQ/AdminLTE#1748]
### Issue type:
[ ] Bug report     
Getting problems with the over and the click on a ul>li items will show a photo:
[
![image](https://user-images.githubusercontent.com/24867922/33339818-19d773c0-d459-11e7-8565-1385675b4c32.png)
](url)

Instead on this:
[
![image](https://user-images.githubusercontent.com/24867922/33339917-5a1290dc-d459-11e7-9df3-1f8f26b9462a.png)
](url)
### Environment:
* AdminLTE Version:  V2.4.0 
* Operating System: WS10
* Browser (Version):  Chrome (Latest)

### Description:
When someone with screen lower than 770px  the sidebar cant get clicked cause the submenu appear inside the menu and couldnt click.

Im working AdminLTE with a framework called Ocrend MVC

**Comment by daniele-athome** [comment]
Might be related to #1778.

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?

**Comment by REJack** [comment]
I can't replicate this issue, if this issue still appear please open a new issue with detailed infos like online demo in jsfiddle.
