### ISSUE TITLE
Dropdown menu issue when body is set to fixed

### ISSUE THREAD

**Issue by stinsonmktg** [ColorlibHQ/AdminLTE#1749]
### Issue type:
[ ] Feature request 
[X ] Bug report      
[ ] Documentation   

### Environment:
* AdminLTE Version:  2.4
* Operating System:  Win
* Browser (Version):  Chrome, latest

### Description:

We switched for body fixed because we wanted to activate the menu bar open on hover as documented here: https://adminlte.io/themes/AdminLTE/documentation/index.html#adminlte-options

But when fixed class is active, dropdown menu is no more clickable. Anyone else has experienced the same?

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?
