### ISSUE TITLE
Trying to call Auth::user() on config/adminlte.php

### ISSUE THREAD

**Issue by Mate38** [ColorlibHQ/AdminLTE#1750]
I'm trying to do this so that this part of the menu only appears if the user has nivel 1:

```
<?php

use Illuminate\Support\Facades\Auth;

function teste($nivel){
    return ($nivel == 1) ? true : false;
}

if(teste(Auth::user()->nivel)){
    $painel = 'PAINEL ADMINISTRATIVO';
    $menu =  [
        'text' => 'Usuários Cadastrados',
        'url'  => 'users',
        'icon' => 'users',
    ];
    $menu2 = [
        'text'       => 'Cadastrar Novo Usuário',
        'url'  => 'users/create',
        'icon' => 'user-plus',
    ];
}else{
    $painel = '';
    $menu = '';
    $menu2 = '';
}
```

However when trying to call `auth::user ()->nivel` within `config/admin.php` I get this error, when I run `php artisan serve`:

```
  [RuntimeException]
  A facade root has not been set.
```

But, if I just put `if(teste(1))` the program run ok

**Comment by REJack** [comment]
AdminLTE is a Free Premium Admin control Panel Theme Based On Bootstrap 3.x (HTML/JS)
For this you need to ask the laravel community.
