### ISSUE TITLE
footer sometimes does not align to page's bottom

### ISSUE THREAD

**Issue by Th3M3** [ColorlibHQ/AdminLTE#1752]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4.2 
* Operating System: Linux on Server side and Win10 & Samsung Mobile as Clients 
* Browser (Version): Opera 49.0, Windows Edge, Samsung Internet Browser 

 
### Description:
If there is less content on the page and the left Menu's height is approximately as heigh as the window (or even a little bit heigher, but not more then the Header's height), the Footer don't align to the page's bottom.

For me it seems to be a fallacy at the calculation formula.

Steps to reproduce:
* small content on the page
* Height of the left menu approximately as heigh as the window
* tested without using the _right_ sidebar.
* [See detailed steps in my comment below.](#issuecomment-351113300)

Have a look to a demonstration gif:
<kbd>![adminlte2_bug2](https://user-images.githubusercontent.com/28313514/33389988-dd77d9ec-d534-11e7-9a5f-ac2140094e0f.gif)</kbd>

The same issue occurs on mobile view too:
<kbd>
<img src="https://user-images.githubusercontent.com/28313514/33489755-19b49f9a-d6b5-11e7-946e-71249e7d4bab.gif" width=250>
</kbd>

**Comment by lenamtl** [comment]
You probably have a div issue.. check if all div are closed

**Comment by Th3M3** [comment]
@almasaeed2010 @lenamtl 

I can't find any unclosed `div`s.
And the issue also occurs when I open the original `index2.html` in the browser and remove the elements (menu items, content, control-sidebar) with the browser's development tools.

In https://github.com/Th3M3/almasaeed2010-AdminLTE/blob/test/index3.html I have added class `hidden` to some menu items and the control-sidebar (on the right side) so you can reproduce this issue :wink:
I would be glad to have this fixed.

**Comment by lenamtl** [comment]
I see some problems in your code...

You should use the demo index page and compare the original code with your code and you will see the diffs and then you can do some investigation.

For example:
You have some strange code just after the sidebar :
  ```
<!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg hidden"></div>
```

The footer part should be after the wrapper content
```
</div><!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    Copyright  All rights...
  </footer>

```
You can also check if there is a fixed or max height set in your css wrapper or other custom CSS causing this.

The only issue I got that is similar of yours, but not the same is that menu cannot be accessible in some case if you have long menu, but compare to your case my template is ok and I don't see any space under the footer like you have...
https://github.com/almasaeed2010/AdminLTE/issues/1491

**Comment by Th3M3** [comment]
@lenamtl 
I'm still not sure where am I should be wrong.
I grabed the original `index2.html` from the `master` branch and had only added classes `hidden` to the elements I do not need.
I have compared my `index3.html` and the original `index2.html` and the differences are only the added `hidden`-classes. Everything else has been left untouched/unchanged.

**Comment by Th3M3** [comment]
Appendum:

Please try the following on **your** template:
**1.** remove, hide or reduce the content inside `<section class="content">` so that it's less then the window's height
**2.** remove or hide the right sidebar `<aside class="control-sidebar ...>`
**3.** remove `<li ...>`-elements inside of `<ul class="sidebar-menu tree" ...>` in the left menu-bar until the remaining items all fit inside the window.
**4.** If at least one of the existing menu items is a tree, then expand and collapse it or try to zoom in or out the whole page.

You can do this all with the browser's development tools for testing, without need to change your files.
**Now you should be able to see the issue I reported**

**Comment by lenamtl** [comment]
Ok, I see I have not use the correct file to compare, sorry my bald.

Maybe you may have the same issue I had as the page on your example is a short page.

Do a backup of your CSS file.

Can you try this 
Change height value of  **body**  and **wrapper**  css
so replace  
`height: 100%;`  
to a minimum height
 `min-height: 100%;`

**Comment by Th3M3** [comment]
I have not applied own css-files.
As I see, AdminLTE itself adds `min-height: 100%` and `height: auto` to `<html>`, `<body>` and `<div class="wrapper">`.
The element `<div class="content-wrapper">` gets a _wrong_ calculated `min-height`-value.

This is what I ment with "For me it seems to be a fallacy at the calculation formula." in the beginning post.

I don't want to workaround the issue because the cause should be fixed in the `.js` file.

**Comment by lenamtl** [comment]
I agree with you and I already ask about more info on the calculation with no luck.
see #1491  They also tried to fix it many times with no luck too...

Both class have height: 100% and this is not working when a page have a long menu and not much content on it... 

By setting min-height 100% this is a temporary fix (and it's not breaking anything). So no template glitch, the only thing is that if the parent menu have a lot of sub-menus (2-3 levels) in some rare case I have to close and reopen parent menu, this occurred only when a page have not much content in it other pages are ok.

Well I'm talking for my project, each project have custom code and different needs...

If you find a JS fix I will be happy to test it ..

**Comment by Barmunksu** [comment]
Has anyone found a solution?

**Comment by lenamtl** [comment]
You can try this
Change height value of **body and wrapper css**
so replace
`height: 100%;`
to a minimum height
`min-height: 100%;`

**Comment by Barmunksu** [comment]
default demo has this property 
http://prntscr.com/hqvbfa

**Comment by lenamtl** [comment]
Hi, not really as the min-height is generate from JS (in some condition) not from the CSS and sometimes the calculation of the page is wrong and it's not applied the min-height.
So by putting the value directly in the CSS this ensure you that this will be always min-height.

**Comment by Th3M3** [comment]
I'm asking @almasaeed2010 for an reply for this issue.

On [another issue](https://github.com/almasaeed2010/AdminLTE/issues/1669#issuecomment-336122176) he wrote on October that he's currently working on v2.4.4. I'm in hope that this issue will also be fixed with this release.

**Comment by lenamtl** [comment]
This is the reason why I stick to old version 2.3

**Comment by WashichawbachaW** [comment]
Have you tried adding `fixed` class? E.g. <footer class="main-footer fixed">.
It solve that problem for me. But now I'm having issue where my footer's height goes with the content's height. Like if the content is small, the footer's height will increase in size. And I'm still having trouble to fix that.

**Comment by REJack** [comment]
This issue is already fixed
