### ISSUE TITLE
The sidebar menu slides open when I click anywhere in the page in small sized views!

### ISSUE THREAD

**Issue by rezasaberi** [ColorlibHQ/AdminLTE#1754]
I am using adminLTE 2.2.1 and have a problem with the sidebar when I open the pages in my tablet. The sidebar opens when I click in the page and it does not matter where I click, it slikes open. and it is really bad. Do I need to use a higher version or it can be solved easily. Many thanks in advance!

**Comment by lenamtl** [comment]
Can you reproduce the problem with the demo?
Which tablet / browser / OS?
