### ISSUE TITLE
Icons not displayed on treeview submenu on IE and Edge

### ISSUE THREAD

**Issue by guizm0b** [ColorlibHQ/AdminLTE#1757]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.0 (the version from the demo website)
* Operating System:  Win10 and macOS High Sierra
* Browser (Version):  IE v.11 and Edge v.38

### Description:
Hi,

So, I've noticed that if you open the sidebar treeview menu from IE or Edge, some of the bullet points are not displayed right away (Font Awesome icons). They appear only when you hover the submenu with your mouse or if you move your mouse out of the sidebar menu. See the screenshot below, This is a screenshot from the actual demo website.

![pasted image at 2017_12_05 12_43 pm](https://user-images.githubusercontent.com/7038290/33608314-15856bca-d9bc-11e7-9c28-0f5f25f347cf.png)

Any chance someone have found a way to fix that?
Thank you!

**Comment by REJack** [comment]
Look at https://github.com/ColorlibHQ/AdminLTE/issues/2140#issuecomment-510201357
