### ISSUE TITLE
dataTables.min.js and POST button

### ISSUE THREAD

**Issue by theshiv303** [ColorlibHQ/AdminLTE#1758]
Issue type: Bug report 

Environment:
AdminLTE 2.4
Windows 10
Chrome, Firefox, IE, Edge
Debian 8.x
Apache 2
MySQL
PHP5

Description:

I have a form in a table that looks like:

```
<tr>
<form id="member_submit" action="insert.php" method="post">
<td><input type="text" class="form-control input-sm" placeholder="Email" name="email" id="email" style="width: 100%"></input></td>
<td><input type="text" class="form-control input-sm" placeholder="First Name" name="fname" id="fname" style="width: 100%"></input></td>
<td><input type="text" class="form-control input-sm" placeholder="Last Name" name="lname" id="lname" style="width: 100%"></input></td>
<td><input type="text" class="form-control input-sm" placeholder="Public Name" name="pname" id="pname" style="width: 100%"></input></td>
<td><input type="text" class="form-control input-sm" placeholder="Public List" name="plist" id="plist" style="width: 100%"></input></td>
<td><input type="text" class="form-control input-sm" placeholder="Phone Number" name="pnumber" id="pnumber" style="width: 100%"></input></td>
<td><button type="submit" class="btn btn-block btn-danger btn-sm"><i class="fa fa-plus"></i>   Add</button></td>
</form>
</tr>
```

The submit button will not post/work whatsoever. However, if I remove:

`<script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>`

The post operation completes successfully.

If I have this setup incorrectly, doing something wrong or there is a work around, please let me know.

**Comment by lenamtl** [comment]
You better use Bootstrap form element instead table ....
https://getbootstrap.com/docs/3.3/css/#forms

Always check for JS error right click inspect for Chromes dev tool 
If you don't need Datatables then remove the script.
If you need Datatables then you need to learn the way it's working
https://datatables.net/examples/index
