### ISSUE TITLE
Big problems in div.user-panel>div.pull-left.info>p (long name + long last name)

### ISSUE THREAD

**Issue by MusArtVlad** [ColorlibHQ/AdminLTE#1762]
`body>div.wrapper>aside.main-sidebar>section.sidebar>div.user-panel>div.pull-left.info>p`
 
Please correct this problem. 
![image](https://user-images.githubusercontent.com/6503014/33890188-87aeb362-df63-11e7-9feb-ca862a4e080b.png)
I can fix this by using the `<br>` tag, but I would like not to do that specifically.
![image](https://user-images.githubusercontent.com/6503014/33890499-80c7e676-df64-11e7-8000-f23497e925e8.png)

**Comment by lenamtl** [comment]
What you can do is to set a new width for the panel, display only x first characters of the name
remove the display block CSS from the P
https://www.w3schools.com/cssref/pr_class_display.asp
