### ISSUE TITLE
Feature request : News and other database entries example

### ISSUE THREAD

**Issue by rafaeldotjs** [ColorlibHQ/AdminLTE#1763]
Hello, first of all, thank you for this great free template. It is very beautiful, I hope to return the favor soon, I am in debt until I do so.

I would love to see an example of pages to edit, add and list simple database entries, like News, events, etc.

**Comment by REJack** [comment]
I've added new page demos in AdminLTE v3, you can check them out at the offical [demo](https://adminlte.io/themes/dev/AdminLTE/).

I've added the following pages:
- [E-commerce](https://adminlte.io/themes/dev/AdminLTE/pages/examples/e_commerce.html)
- [Projects](https://adminlte.io/themes/dev/AdminLTE/pages/examples/projects.html)
- [Project Detail](https://adminlte.io/themes/dev/AdminLTE/pages/examples/project_detail.html)
- [Project Add](https://adminlte.io/themes/dev/AdminLTE/pages/examples/project_add.html)
- [Project Edit](https://adminlte.io/themes/dev/AdminLTE/pages/examples/project_edit.html)
- [Contacts](https://adminlte.io/themes/dev/AdminLTE/pages/examples/contacts.html)
