### ISSUE TITLE
NavTabs InnerNavTabs

### ISSUE THREAD

**Issue by amanakos** [ColorlibHQ/AdminLTE#1764]
Hello everybody

Im new to programming and new to use useful project AdminLTE. Great work. 

My problem.
I create dynamic nav-tabs-custom onLoad php page. Each tab-pane has another inner nav-tabs-custom with only two tab-pane. All work great.

I have one button, named Insert, where load modal and insert to database one record. I want after succesfully inserted data to reload with ajax code  all nav-tabs-custom but while the data is ok the nav-tabs-custom crushed.

If anyone meet this problem i appreciate to help me. If you want to see my code tell me.

Thkns

**Comment by lenamtl** [comment]
Hi,
AdminLTE this is a template, we cannot help with server side code as it seem what you need...
