### ISSUE TITLE
Space between sidebar heading and menu items when zoomed in/out

### ISSUE THREAD

**Issue by GeoffYoung** [ColorlibHQ/AdminLTE#1766]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  **2.4**
* Operating System:  **MacOS 10.13.2**
* Browser (Version):  **Chrome (Latest)**

### Description:
When Chrome is zoomed in or out there is a visible gap between a section heading and it's list of options in the collapsed sidebar.

![screen shot 2017-12-17 at 7 14 45 pm](https://user-images.githubusercontent.com/869227/34085916-13fd99dc-e365-11e7-8733-6109fcbfd301.png)

I'm seeing this at 80%, 90%, and 110%.

**Comment by REJack** [comment]
This issue is already fixed
