### ISSUE TITLE
chrome for linux display

### ISSUE THREAD

**Issue by Arabira1** [ColorlibHQ/AdminLTE#1768]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4
* Operating System:  ubuntu 16.04
* Browser (Version):  Chrome and Chromium

### Description:
When I browse index2.html in ubuntu's chrome browser, I swipe right with the trackpad, and there is a toolmenu that should be hidden on the right. But this isn't a problem when I swipe right from Chrome in Windows.

**Comment by lenamtl** [comment]
is this problem occurred on the AdminLTE demo page?

**Comment by REJack** [comment]
This issue is already fixed
