### ISSUE TITLE
version 2.4 for a new project?

### ISSUE THREAD

**Issue by josegarciagmx** [ColorlibHQ/AdminLTE#1770]
Hi All

My concern is: I see some issues in the list which haven't been addressed for a long time. 
Commits are also rare, I'm not sure that there will be update releases anytime soon..
Would it be safe to use AdminLTE 2.4 version for a new project?

Thank you

**Comment by eman1986** [comment]
I would say you can, I use it on a internal project for work with no issues, but for me, I wanted just the ui, and none of the other things so it works for my situation.
