### ISSUE TITLE
Issue not fixed #1692, still showing bower_components path in less files

### ISSUE THREAD

**Issue by DroidNinja** [ColorlibHQ/AdminLTE#1772]
### Issue type:
- [ ] Feature request 
- [*] Bug report       
- [x] Documentation   

### Environment:
* AdminLTE Version:   2.4
* Operating System:  OSX 
* Browser (Version): Chrome (Latest)

### Description:
I installed this version  "admin-lte": "2.4.2" but the less file are still bower_components related paths which I am not able to compile through css loader as I am using this in my angular project.

**Comment by mediavariance** [comment]
@DroidNinja Any luck on this?Is there a fix?

**Comment by REJack** [comment]
This issue is already fixed
