### ISSUE TITLE
How to fix small gaps ?

### ISSUE THREAD

**Issue by deshario** [ColorlibHQ/AdminLTE#1773]
I have no idea that how to fix it .... when i use bootstrap panel instead of adminlte boxes it also occurs a same problem. it seems to be have small gaps at the `box-header` if we use` box-solid` class ... how to fix it !
![capture](https://user-images.githubusercontent.com/11426727/34360320-1dfa91cc-ea92-11e7-9e9a-e5ea812ec810.PNG)

**Comment by lenamtl** [comment]
Hi, you probably have a wrong column total, the total per ROW should equal to 12 for the same size.

```
<div class="row">
  <div class="col-md-3">1</div>
  <div class="col-md-3">2</div>
  <div class="col-md-3">3</div>
 <div class="col-md-3">4</div>
</div>
```

esle check the syntax of the code, div and check your custom CSS if you add any.
