### ISSUE TITLE
Height problem

### ISSUE THREAD

**Issue by Vrowk** [ColorlibHQ/AdminLTE#1774]
My one page piece is being cut off, and I do not know what's going on.

![image](https://user-images.githubusercontent.com/34896412/34391495-20138540-eb2d-11e7-92d3-7386ee912570.png)

**Comment by lenamtl** [comment]
Not sure what is the problem...
You can set a minimum height to the container (where the boxes appear), as your page is too short.

**Comment by REJack** [comment]
This issue is already fixed.
