### ISSUE TITLE
DATA TABLE Function not work

### ISSUE THREAD

**Issue by sanjayacloud** [ColorlibHQ/AdminLTE#1776]
When I use data table in php file i cannot see pagination and column sort function. Any one can help to fixed this issue?

**Comment by xDowwdeen** [comment]
Have you placed in the required CSS and JS files.

**Comment by sanjayacloud** [comment]
I have put everything in adminLTE Master folder

**Comment by lenamtl** [comment]
I'm using Datatables on all my pages and never encounter any issue related to AdminLte.
Check your console right click inspect and check errors.
Datatables have a forum where you can post your question.

**Comment by REJack** [comment]
If you can't see pagination and/or column sort function, check your generated HTML code. DataTables crashs everytime if thead has more/less columns than tbody, both need to be even.
