### ISSUE TITLE
Issue of collapsed sidebar-menu at @screen-sm state

### ISSUE THREAD

**Issue by guogangj** [ColorlibHQ/AdminLTE#1778]
- [x ] Bug report

This issue can be easily reproduced by this steps:

1, Open  `https://adminlte.io/themes/AdminLTE/index2.html` a desktop browser.
2, Maximize the browser.
3, Click on the sidebar-toggle button to collapse the sidebar-menu.
4, Make the width of the browser smaller the 768px
5, Click on the sidebar-toggle button to activate the sidebar-menu.

Then you will see the menu's behavior is strange.

### Environment:
* AdminLTE Version: 2.4.2
* Operating System: Windows
* Browser (Version):  Chrome 63, Firefox 57

**Comment by daniele-athome** [comment]
I can confirm this issue on Firefox for Linux and Chrome for Android. I have to load the page with an expanded sidebar to make it work correctly.

**Comment by daniele-athome** [comment]
Might be related to #1748.

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?

**Comment by REJack** [comment]
I can't reproduce the "strange behavior" in v2.4.13, if this issue still appear please open a new issue.
