### ISSUE TITLE
Issue of collapse sidebar-menu's sub menu indicator(angle)

### ISSUE THREAD

**Issue by guogangj** [ColorlibHQ/AdminLTE#1779]
- [ x] Bug report 

### Environment:
* AdminLTE Version:  2.4.2
* Operating System:  Windows
* Browser (Version):  Chrome 63

This is a small bug. It can be reproduced by these steps:
1, Open https://adminlte.io/themes/AdminLTE/index2.html
2, Click the sidebar-toggle button to make the sidebar-menu collapsed
3, Hover your mouse over the collapsed sidebar-menu which has sub-menu
4, Then you can see an angle sign there
5, Click on the angle sign then you will know what I mean.

**Comment by MPalarya** [comment]
i'm experiencing the same behavior on latest firefox version 57

**Comment by aahameed** [comment]
i think this because style="display: block;" in treeview menu and the flash happen when add the same style in JS

**Comment by yawanglan** [comment]
我是在vue项目中引入,但左侧菜单栏收缩后悬浮在图标上没有显示子菜单

**Comment by REJack** [comment]
I've fixed this issue in master branch
