### ISSUE TITLE
AdminLTE treeview expand on ajax menu loading

### ISSUE THREAD

**Issue by alexdran** [ColorlibHQ/AdminLTE#1782]
Environment:
* AdminLTE Version:  Example: 2.4 on yii2
* Operating System:  OSX 10.11.6
* Browser Firefox 57.0.1 (64 bit)

I have the adminLTE left menu whose content is generated by an ajax call, to allow search box to filter menu items

after a search however "treeview" menu items does not explode anymore,
what is the js trigger I have to call to refresh the explode events for sub-menu ?

thanks in advance
alex

**Comment by andrewboy** [comment]
For now you have to write a hack. After you refresh the content, the events unbinds from the menu because thease events not live events and binds only page load. After every content refresh, you have to run this:

```
        $('[data-widget="tree"]').each(function () {
            $.fn.tree.call($(this));
        });
```

In the Tree.js the bind is:

```
  $(window).on('load', function () {
    $(Selector.data).each(function () {
      Plugin.call($(this))
    })
  })
```

It would be nice if it have something similar in Pushmenu.js:

```
  $(document).on('click', Selector.button, function (e) {
    e.preventDefault()
    Plugin.call($(this), 'toggle')
  })
  $(window).on('load', function () {
    Plugin.call($(Selector.button))
  })
```

because this solution at least works.

**Comment by alexdran** [comment]
Is working!!
thanks a lot

when I click on an exploded item and the page reload:
do you know how to keep menu exploded after an inner item selected 
(or this is something to be solved via php), 

alex

**Comment by andrewboy** [comment]
It depends on where the menu renders. 
If the menu renders in backend the first time and you manipulate it on frontend, then I think it's easier to handle on the backend.
If the menu renders fully on frontend, then handle it on the frontend side. Put a 'menu-open' class to the treeview li element and a 'display:block;' style to the inner ul element.

**Comment by alexdran** [comment]
I confirm you is rendered in back-end 
so I should simply add necessary class and style in php

would you have an example of an exploded menu,
I cannot find on the internet

thanks again for your additional support in this!

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?

**Comment by alexdran** [comment]
I'm writing you again since I'm back on this project,
and back again with same problem

I have adminLTE app.js version v2.4.18 on Yii2 2.0.34 under PHP 7.2.3

still when browsing a submenu and loading the link of that submenu, menu loads not exploded.
Do I need to call my link with specific convention
es.
pages/submenulink/menulink ??

that menu is not exploded with link below
![image](https://user-images.githubusercontent.com/13314059/77855059-5dea1b00-71ee-11ea-962f-e4e5c9e03c97.png)

http://localhost/heyconference/backend/agendas/?cid=15#

thanks again for any help
Alessandro
