### ISSUE TITLE
关于官方提供的AdminLTE-2.4.2模板样式问题

### ISSUE THREAD

**Issue by wealthtears** [ColorlibHQ/AdminLTE#1793]
类型：发现BUG
Issue type：Bug report

环境：
AdminLTE版本：AdminLTE-2.4.2
操作系统：windows7 64位
浏览器（版本）：Firefox 57.0.4(64位)
Environment:
AdminLTE Version: AdminLTE-2.4.2
Operating System:  windows7 64位
Browser (Version): Firefox 57.0.4(64位)

说明：
在官方提供的AdminLTE-2.4.2模板index.html页面中，发现如果使用了Control Sidebar控制边栏标签aside后，如果左边树形菜单内容较少和右边正文内容较少时页面底部会出现样式错乱问题，但是删除Control Sidebar控制边栏标签aside标签里面的后一切正常。具体情况可以看图。
Description:
In the official AdminLTE-2.4.2 template index.html page, I found that if you use the Control Sidebar control sidebar label aside, if there is less left-side tree menu contents and less right-hand side of the page will appear when the style disorder , But delete the Control Sidebar control sidebar label aside label everything is normal. Specific circumstances can see the map.
![default](https://user-images.githubusercontent.com/35245652/35210935-250217e4-ff8f-11e7-8dde-490d1f40840c.png)

**Comment by benzunyinzi** [comment]
亲测，给你个建议吧。新增一个footer文件，然后按照官网的html直接copy下来，就可以使用了。也不会导致侧边有多余的右侧栏了。

**Comment by REJack** [comment]
This issue is fixed with the latest version (v2.4.12)
