### ISSUE TITLE
Non focused window page size interpreted incorrectly

### ISSUE THREAD

**Issue by RichardTMiles** [ColorlibHQ/AdminLTE#1809]
First off thanks to everyone who's actively working to make this theme better!! 

It took me a while to figure out when and how to reporduce this bug and hopefully this is consistant with everyone. 

https://media.giphy.com/media/xUNda5mnLyRZ8VDBT2/giphy.mp4

If you load the webpage out of the main point of focus the pagesize is misinterpreted to leave about as a footers worth of room. You can see my source here https://carbonphp.com/

Aslo thats a simple MVC framework documentation website I wrote in php that features live communiction via websockets and more + uses Adminlte.. Thanks for everything yall do!

**Comment by REJack** [comment]
Try to update AdminLTE to v2.4.12 it should fix your issue.
