### ISSUE TITLE
Get an unexpected result when change skin

### ISSUE THREAD

**Issue by Hj1an** [ColorlibHQ/AdminLTE#1812]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  macOS High Sierra 10.13.3 
* Browser (Version):  Chrome Version 64.0.3282.140 (Official Build) (64-bit)

### Description:

Demo: https://adminlte.io/

I set my default skin `skin-purple` on[ **index.html**](https://github.com/almasaeed2010/AdminLTE/blob/master/index.html#L41) as :
``` html
<body class="hold-transition skin-purple sidebar-mini">
```
And then I click control sidebar to change it to `skin-blue`, It's work well on current page. But when I reload the page, it become back to `skin-purple` again. 

It wouldn't happen when I change to the other skins.

I review the code and found the keys.

[**demo.js** L108](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/demo.js#L108)

```javascript
function setup() {
    var tmp = get('skin')
    if (tmp && $.inArray(tmp, mySkins))
      changeSkin(tmp)
```

[**demo.js** L26:L39](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/demo.js#L26:L39)
```javascript
var mySkins = [
    'skin-blue',
    'skin-black',
    ...
```

Obviously

```javascript
$.inArray('skin-blue', mySkins) = 0
```

So, nothing will happen when I reload the page.

There may have two ways to fix it:

``` javascript
if (tmp && $.inArray(tmp, mySkins) > -1)
```
or

``` javascript
if (!$('body').hasClass(tmp) && $.inArray(tmp, mySkins) > -1)
```

**Comment by REJack** [comment]
I can't replicate this issue and changes into demo.js aren't necessary, this kind of script is also removed in v3 demo.
