### ISSUE TITLE
AdminLTE JS File Included Bu no Working

### ISSUE THREAD

**Issue by HeshamEl-Bembawy** [ColorlibHQ/AdminLTE#1813]
Hello Every one,
I have a problem with AdminLTE Version 2.2.0.
I make file with name backend.js and included this file in footer and it's run in view page source but function not working 
this is the code i inclouded in footer 
`    
    <script src="<?php echo $js;?>backend.js"></script>` $js it's rout for js folder 
and this is the function 

> $(function () {
    'use strict';
    //Hide Place Holder On Form Focus
    $('[placeholder]').focus(function () {
        $(this).attr('data-text', $(this).attr('placeholder'));
        $(this).attr('placeholder', '');
    }).blur(function () {
        $(this).attr('placeholder', $(this).attr('data-text'));
    });
    // Add * For Required Field
    $('input').each(function(){
        if($(this).attr('required') === 'required'){
            $(this).after('<span class="asterisk">*</span>')
        }
    });
    // Convert Password Field To Show Field On Hover
    var passField = $('.password');
    $('.show-pass').hover(function (){
        passField.attr('type', 'text');
    }, function (){
        passField.attr('type', 'password');
    });
    //Confirmatio Message
    $('.confirm').click(function (){
        return confirm('هل انت متأكد ؟');
    });
});

any Help Please

**Comment by REJack** [comment]
This is not an AdminLTE related Issue, please ask questions like this on stackoverflow.com.
