### ISSUE TITLE
Icon Not Show in Codeignter 

### ISSUE THREAD

**Issue by sanjayacloud** [ColorlibHQ/AdminLTE#1818]
### Issue type:

- [ ] Bug report       

### Environment:
* AdminLTE Version:  2.4 
* Operating System:  Windows 10 Pro
* Browser (Version):  Chrome (Latest)

### Description:
When I add AdminLte to Codeigniter, Some Icon not show. Please look my screenshot in below URL
[https://www.dropbox.com/s/ql08xkzomj0bcwg/Screenshot%202018-02-19%2019.13.12.png?dl=0](url)

**Comment by REJack** [comment]
It looks like you load not your Icon Set CSS Files, I use CodeIgniter everytime with AdminLTE without any problems caused by AdminLTE.

**Comment by sanjayacloud** [comment]
Yes, I found problem. I have another problem now. I try to add CK Editor to my codeigniter project with AdminLTE. but the textarea not work. after that i use below code. its work fine. 
`<script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>
                   <textarea id="editor1" name="address" rows="10" cols="80">
                                            
                    </textarea>
                    <script>
                      CKEDITOR.replace( 'editor1' );
                    </script>`
Can I how to add AdminLTE CK Editor to my project

**Comment by REJack** [comment]
Do you want CKEditor for any textarea's? If yes, replace `CKEDITOR.replace( 'editor1' );` with `CKEDITOR.replaceAll();`.

**Comment by sanjayacloud** [comment]
I do like this, but it not work with internal JS file it's only work with <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>

**Comment by REJack** [comment]
For this you should ask the CKEditor support, this issue isn't related to AdminLTE.

**Comment by sanjayacloud** [comment]
But it works fine in admimlte original source code...

**Comment by lenamtl** [comment]
For security reason I recommend you to use only internal JS script.
Try to update  CKEditor  script with the latest version.

Check Chrome console for error (right click inspect).

You may have some conflict with your Framework too and probably not related to the template itself.
