### ISSUE TITLE
Error $.AdminLTE undefined 

### ISSUE THREAD

**Issue by Shank4200** [ColorlibHQ/AdminLTE#1820]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4  
* Operating System: Windows 10  
* Browser (Version): Chrome latest 

### Description:
IssueDescription :- While adding sub menus dynamically, tree view does not expand using partial view MVC 4.0
 trying adding :-  $.AdminLTE.tree('.sidebar'); but getting error "$.AdminLTE.Tree undefined"
![dmsissue](https://user-images.githubusercontent.com/36692240/36472494-04c4b4f0-1718-11e8-95be-1f955f59ee49.PNG)
![issuedm](https://user-images.githubusercontent.com/36692240/36472495-04f1f19a-1718-11e8-9196-9f4abbc9ec77.PNG)

**Comment by atg-dmayor** [comment]
Bump, I'm having this issue too

**Comment by REJack** [comment]
$.AdminLTE is not definied, try to use `$('.sidebar').tree()` instead of `$.AdminLTE.tree('.sidebar')`
