### ISSUE TITLE
Keep dropdown user user-menu open

### ISSUE THREAD

**Issue by djlaney3** [ColorlibHQ/AdminLTE#1821]
### Issue type:
- [x ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  version 2.4.0
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

### Description:
Is there a way to keep the user menu dropdown open after a click in the user menu?   I want to add a set of tabs, but as soon as you click a tab, the entire menu closes.  How can I only make the menu close when I click the top level user name menu?  Basically close it the same way you open it.

**Comment by iChaosren** [comment]
Found it's more of an issue with how Bootstrap handles it the dropdowns.

This worked for me:
```
$("a.dont-close-dropdown").on("click", function(e){
    e.stopPropagation();
});
```
