### ISSUE TITLE
White Space in Bottom Page

### ISSUE THREAD

**Issue by bintaroweb** [ColorlibHQ/AdminLTE#1823]
![screenshot_9](https://user-images.githubusercontent.com/12415114/36512693-2561cb68-179e-11e8-9529-14ce00c51ae1.jpg)

Hallo AdminLTE lovers, in my dashboard there is white space at the bottom, any body know?

**Comment by Reconix** [comment]
You're probably just missing a closing div (</div>)

The quickest and best way to test stuff like this is to make sure your edits work fine in plain HTML.
