### ISSUE TITLE
Error Composer bower-asset/adminlte, bower-asset/admin-lte v.2.4.3.

### ISSUE THREAD

**Issue by tecnoterabyte** [ColorlibHQ/AdminLTE#1824]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.3.
* Operating System:  Centos7.

### Description:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bower-asset/adminlte v2.4.3 requires bower-asset/bootstrap-timepicker >=0.5.2,<0.6.0 -> satisfiable by bower-asset/bootstrap-timepicker[v0.5.2].
    - Installation request for bower-asset/adminlte 2.4.3 -> satisfiable by bower-asset/adminlte[v2.4.3].
    - Conclusion: don't install bower-asset/jquery 3.3.1
    - bower-asset/bootstrap-timepicker v0.5.2 requires bower-asset/jquery >=2.0.0,<3.0.0 -> satisfiable by bower-asset/jquery[2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.1-RC2, 2.1.1-RC1, 2.1.1-beta1, 2.1.0, 2.1.0-RC1, 2.1.0-beta3, 2.1.0-beta2, 2.1.0-beta1, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 2.0.0-beta3, 2.0.0-beta2, 2.0.0-beta1].
    - Can only install one of: bower-asset/jquery[2.2.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.2.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.4, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.1-RC2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.1-RC1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.1-beta1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.0-RC1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.0-beta3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.0-beta2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.1.0-beta1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.1, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.0, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.0-beta3, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.0-beta2, 3.2.1].
    - Can only install one of: bower-asset/jquery[2.0.0-beta1, 3.2.1].
    - bower-asset/adminlte v2.4.3 requires bower-asset/jquery >=3.2.1,<4.0.0 -> satisfiable by bower-asset/jquery[3.3.1, 3.3.0, 3.2.1].
    - Conclusion: don't install bower-asset/jquery 3.3.0

**Comment by X-Coder** [comment]
I get a similar error with current AdminLTE3 and can't install it:
```
composer require almasaeed2010/adminlte:3.0.0-alpha.2

our requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for almasaeed2010/adminlte 3.0.0-alpha.2 -> satisfiable by almasaeed2010/adminlte[v3.0.0-alpha.2].
    - almasaeed2010/adminlte v3.0.0-alpha.2 requires bower-asset/jquery >=1.9.0 <4.0.0 -> no matching package found.
```

**Comment by X-Coder** [comment]
Put this into your composer.json to resolve the error:
"repositories": [
    {
        "type": "composer",
        "url": "https://asset-packagist.org"
    }
]
