### ISSUE TITLE
Assignment/ Un assignment of check boxes causing issues in case of large number of records

### ISSUE THREAD

**Issue by talalhaider94** [ColorlibHQ/AdminLTE#1832]
Hello,

I am assigning Petrol pump stations to sales areas in my project. This assignment works by checking the checkboxes. Likewise, I am un assigning the stations by unchecking the checkboxes. It is working fine in case of few records but causing trouble in assignment and un assignment in case of large number of records.

Please guide me why is it causing this issue. I can also share my code file if required. 

Thank you

**Comment by REJack** [comment]
I'll close this, it's not a issue of AdminLTE,
