### ISSUE TITLE
Treeview expands and collapses immediately when clicked

### ISSUE THREAD

**Issue by hkarakose** [ColorlibHQ/AdminLTE#1834]
### Issue type:
- [ ] Bug report 

### Environment:
* AdminLTE Version:  2.4
* Operating System:  OSX
* Browser (Version):  Chrome (Latest)

### Description:
I click a tree menu it expands as expected.
I refresh the page then click a tree menu. This time it expands and and then collapses immediately. 

My expected behavior is to only extend and not collapse even though after a page refresh.

**Comment by hkarakose** [comment]
It turned out that Tree is initialized twice.

First initialization
<img width="720" alt="screen shot 2018-03-10 at 17 42 28" src="https://user-images.githubusercontent.com/406291/37243475-c590aed0-248a-11e8-9ed8-b0ec4b40368f.png">

Second initialization
<img width="723" alt="screen shot 2018-03-10 at 17 42 43" src="https://user-images.githubusercontent.com/406291/37243477-d0660d32-248a-11e8-9b58-5120ce12c939.png">

As a workaround, I updated tree as follows:

<img width="677" alt="screen shot 2018-03-10 at 17 46 14" src="https://user-images.githubusercontent.com/406291/37243489-f3ce5b9e-248a-11e8-8ca5-6708ae104d1d.png">

Then, updated initialization as follows:
<img width="728" alt="screen shot 2018-03-10 at 17 48 09" src="https://user-images.githubusercontent.com/406291/37243496-37f43186-248b-11e8-83fd-1fd3568f72e6.png">

This resolved my expand/collapse issue.

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?
