### ISSUE TITLE
Align form field (with and without label)

### ISSUE THREAD

**Issue by array81** [ColorlibHQ/AdminLTE#1836]
Is there away to align two form field, one with label and one without label?
[![align.jpg](https://s17.postimg.org/4twzha873/align.jpg)](https://postimg.org/image/mjyo2blrv/)

**Comment by lenamtl** [comment]
The problem here is there is no label on second column so you may add a margin/padding only to these input or use inline label instead of top label...
https://getbootstrap.com/docs/3.3/css/#forms-inline
