### ISSUE TITLE
Mutliple Select2 with ng-include html file

### ISSUE THREAD

**Issue by avartaka** [ColorlibHQ/AdminLTE#1837]
Select2 is working fine when I use in the main html file. But when I add it in a child html and ng-include with the main html, it is showing up as linear select control as in the screenshot. Am I missing something?

![image](https://user-images.githubusercontent.com/32299217/37364672-2b80c07a-2721-11e8-92c5-f9a63e70b045.png)

**Comment by REJack** [comment]
maybe you missed to initialize select2, try to add `$('select').select2()`.
