### ISSUE TITLE
I have 2 image rtl and ltr my problem in rtl 

### ISSUE THREAD

**Issue by midobona** [ColorlibHQ/AdminLTE#1841]
hello , 
I have 2 image rtl and ltr my problem in rtl 
LTR :
<img src="https://image.ibb.co/jKF5s7/29345713_904535213053888_2016196030_n.png" width="200" height="350" >
RTL:
<img src="https://image.ibb.co/kWQien/29663518_904535196387223_1176517161_n.png" width="200" height="350" >
I want hide menu in mobile devices

**Comment by midobona** [comment]
any help ??

**Comment by midobona** [comment]
please help me @almasaeed2010

**Comment by REJack** [comment]
Did you use the ControlSidebar in RTL for the sidebar, if yes you need to create a custom script for this.
