### ISSUE TITLE
How to reset sidebar expandOnHover option

### ISSUE THREAD

**Issue by rmpestano** [ColorlibHQ/AdminLTE#1843]
### Issue type:
- [x] Question
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

 
### Environment:
* AdminLTE Version:   2.4
* Browser (Version):  Chrome 60
 
### Description:

I just want to know how to reset sidebar `expandOnHover` behavior. After I set it using:
```$pushMenu.expandOnHover();```
I don't know how to reset to default behavior anymore.

I've tried `$('[data-toggle="push-menu"]').pushMenu({expandOnHover=false})` without success.

Any hints? 

thanks in advance.

**Comment by REJack** [comment]
Try `$('.main-sidebar').off("mouseenter mouseleave");` to remove the hover bindings.
