### ISSUE TITLE
Some issues on Microsoft Edge

### ISSUE THREAD

**Issue by ivansammartino** [ColorlibHQ/AdminLTE#1845]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4
* Operating System:  Windows 10 64 bit
* Browser (Version):  Microsoft Edge Latest

### Description:
Hello, I have two major issue with Microsoft Edge (not Microsoft IE):
 1. the user panel shows some dots offset on the left: I guess they come from the `li`s
![dots](https://user-images.githubusercontent.com/835377/37998101-9bfa03be-321d-11e8-9d5d-ee322d88cd18.png)
 2. when I open a collapsed submenu, there is lot of extra space in the subitems (it does not happens on the submenu that are opened on page load), see the [attached video in the zip](https://github.com/almasaeed2010/AdminLTE/files/1853994/submenu.zip)

Going deeper with Edge Developer tools, there's a strange "offset" in the `li`s:
![offset](https://user-images.githubusercontent.com/835377/37998330-825c78a0-321e-11e8-8753-cc4522bcacff.png)

That's all! :-) Thanks

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.12)?

**Comment by REJack** [comment]
I can't replicate this issue with the latest version (v2.4.12), if this issue still appear please open a new issue.
