### ISSUE TITLE
Move main content

### ISSUE THREAD

**Issue by mix2002** [ColorlibHQ/AdminLTE#1848]
I can't change the postion of the items in main content, i changed the section class but margin or padding just don't work at all.. Anyone know how to fix this?

![1](https://user-images.githubusercontent.com/8055275/38164833-620f91b8-3502-11e8-8893-6033305df4a1.png)
![2](https://user-images.githubusercontent.com/8055275/38164834-63b6f858-3502-11e8-89df-6c713c2793da.png)

**Comment by marchershey** [comment]
I don't understand what you're trying to change. 

Please explain with more detail.
