### ISSUE TITLE
Ajax loaded box collapse broken again on 2.4

### ISSUE THREAD

**Issue by soullivaneuh** [ColorlibHQ/AdminLTE#1857]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4
* Operating System: Linux
* Browser (Version):  Chrome (Latest)

### Description:

The issue was already reported in #302 and fixed.

Here again, on 2.4, the box can not be collapsed if they are loaded in ajax.

A automated test should be added to prevent this kind of bug in the future.

Current possible workaround waiting the fix, using the [arrive](https://yarnpkg.com/en/package/arrive) component:

```javascript
jQuery(document).arrive('div.box [data-widget]', (element) => {
  $(element).parents('.box').boxWidget();
});
```

**Comment by adrianrz** [comment]
Is the issue remains unsolved?
Thans

**Comment by ZackPK** [comment]
All,

As a workaround, add "jquery.arrive" JS to your project, https://raw.githubusercontent.com/uzairfarooq/arrive/master/minified/arrive.min.js

then call "jQuery(document).arrive('div.box [data-widget]', (element) => { $(element).parents('.box').boxWidget(); });" after ajax request.

**Comment by REJack** [comment]
If you add a complete box via a ajax call you need to init the boxWidget on the box to collapse it after insert.
