### ISSUE TITLE
Problem Using <li class="treeview"> with Longer Title 

### ISSUE THREAD

**Issue by gtilflm** [ColorlibHQ/AdminLTE#1858]
I have this...

`			<li class="treeview">
			  <a href="#"><i class="material-icons" style="font-size: 18px; vertical-align: sub; margin-left: -3px; padding-right: 5px;">headset_mic</i> <span>Sessions & Whiteboard</span> 
				<span class="pull-right-container">
					<i class="fa fa-angle-left pull-right"></i>
				  </span>
			  </a>
			  <ul class="treeview-menu">
				<li><a href="#">Join LIVE Session</a></li>
				<li><a href="#">Recorded Sessions & H.W.</a></li>
				<li><a href="#">Work Room</a></li>
			  </ul>
			</li>
`

When collapsed, the "Sessions & Whiteboard" title is partially obscured by the `<span class="pull-right-container">` which is oddly big for just showing `<i class="fa fa-angle-left pull-right"></i>`.

What changes can be made to fully display longer titles?

**Comment by REJack** [comment]
There is no real fix for this behavior you can only crop the title and add a tooltip.
