### ISSUE TITLE
how can i hide the side bar in md

### ISSUE THREAD

**Issue by Lennuj420** [ColorlibHQ/AdminLTE#1863]
hi im new in using adminlte and im greatful to the creators
this post is not an actually an issue but more like of a question.

i am trying to make it work in just like in two screens. large screen and mobile screen.

i want to hide the sidebar in medium screens not just collapsing it retaining the icons on the side... i want to do is to hide it totally like in the xs screens? 

thank you for having the time reading this question...

**Comment by tikky** [comment]
I am not sure if this could help you, but I suggest you can read how to hide div on specific screen size:
https://stackoverflow.com/questions/14207109/hiding-elements-in-responsive-layout
https://getbootstrap.com/docs/3.3/css/#responsive-utilities

**Comment by REJack** [comment]
Try to remove `.sidebar-mini` from body, you can create a custom javascript based on viewport width to remove or add the class.
