### ISSUE TITLE
suggestion to add alerts

### ISSUE THREAD

**Issue by webblufter** [ColorlibHQ/AdminLTE#1867]
AdminLte is best one 
i ever use this theme in my most of the projects for admin dashboard 

i want to suggest/request to add toastr alerts in AdminLte this one is good one to shoe something is saved / delete / updated or not 

hope so you will check this and add it 
http://codeseven.github.io/toastr/demo.html
https://github.com/CodeSeven/toastr

thanks

**Comment by REJack** [comment]
I've added Toastr in AdminLTE, you can test it [here](https://adminlte.io/themes/dev/AdminLTE/pages/UI/modals.html)
