### ISSUE TITLE
Uncaught TypeError: $(...).expandOnHover is not a function

### ISSUE THREAD

**Issue by pupattan** [ColorlibHQ/AdminLTE#1872]
I am trying to use feature "Sidebar Expand on Hover".
But its showing this issue.

Uncaught TypeError: $(...).expandOnHover is not a function

**Comment by REJack** [comment]
expand on hover is not a js functions, it's a option definable through a data-attribute on the push-menu button, e.g. `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button" data-expand-on-hover="true">`
