### ISSUE TITLE
reload url but not refresh leftbar

### ISSUE THREAD

**Issue by yuguo6211** [ColorlibHQ/AdminLTE#1873]
i reload url but not refresh leftbar;and then the leftbar can not click;if i refresh the page ,it is ok

**Comment by yuguo6211** [comment]
i use the nuxt, change the page by reload url but not reload the page

**Comment by REJack** [comment]
You need to create a custom script like this https://github.com/ColorlibHQ/AdminLTE/issues/1806#issuecomment-362635514
