### ISSUE TITLE
Data table doesn't change to another page

### ISSUE THREAD

**Issue by caturseptian** [ColorlibHQ/AdminLTE#1874]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  3
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

### Description:
Data table doesn't change to another page
![image](https://user-images.githubusercontent.com/13551379/39953102-5665fb58-55ce-11e8-9369-630402aa027c.png)

**Comment by guillaume-cozic** [comment]
https://github.com/almasaeed2010/AdminLTE/issues/1870

**Comment by caturseptian** [comment]
@guillaume-cozic i dont find the script v3 alpha 2

**Comment by joe-inz** [comment]
where to find the script !!!
