### ISSUE TITLE
Problems with bootstrap-slider version. The only dependency with "*"

### ISSUE THREAD

**Issue by prsolucoes** [ColorlibHQ/AdminLTE#1875]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  Linux
* Browser (Version):  Chrome (Latest)

### Description:

I have a project all-included made with Yii2 and AdminLTE:
https://github.com/prsolucoes/yii2-app-advanced

Im upgrading it to AdminLTE 2.4.3 but have some conflict:

```
bower-asset/admin-lte v2.4.3 requires bower-asset/bootstrap-slider * -> satisfiable by bower-asset/bootstrap-slider[dev-master] but these conflict with your requirements or minimum-stability.
```

I search for it on AdminLTE repository and find it on bower.json:

```
"bootstrap-slider": "*",
```

Can you put in the version 2.4.4 the latest version of bootstrap-slider to solve this conflict? Everyone that dont let update to development version will have this problem.

**Comment by REJack** [comment]
I've changed the bootstrap-slider line from * to @dev, coming with the next release.
