### ISSUE TITLE
Chartjs version 2 Not working

### ISSUE THREAD

**Issue by hooramin** [ColorlibHQ/AdminLTE#1885]
### Issue type:
- [ ] Feature request 
- [ ] Bug report     
- [x] Documentation   
- [x] Question   

### Environment:
* AdminLTE Version:  3 Alpha
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

### Description:
Hi there, I'm new to AdminLTE. i already was working with chartjs v2 but i saw the version implemented on "Adminlte 3 alpha" is an older version ( 1 ).
First i wanna know what's the problem that author didn't upgrade it to latest version and second i wanna know what can i do to use later version on AdminLTE ?
Because when i use chartjs2 script file on header ,i can't get any output of my charts ( that myself wrote their code - not demos ) anymore
is it because of some (weird)  Interference on JavaScript libraries ?

**Comment by almasaeed2010** [comment]
Hi @hooramin 

AdminLTE 3 provides support for both chartJS v1 and v2. Visit index3.html to see ChartJS v2 https://adminlte.io/themes/dev/AdminLTE/index3.html
