### ISSUE TITLE
same text-color as background for nav-item:hover dropdown

### ISSUE THREAD

**Issue by X-Coder** [ColorlibHQ/AdminLTE#1893]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version: v3-dev 
* Operating System: W10 
* Browser (Version):  Firefox/Chrome 

### Description:
If you click on dropdown menu of the tab example and hover the main nav-item labeled "Dropdown", it has same text-color as background, and is therefore not readable any more.
https://adminlte.io/themes/dev/AdminLTE/pages/UI/general.html

**Comment by almasaeed2010** [comment]
Thanks for reporting @X-Coder

**Comment by REJack** [comment]
This issue is fixed with #2110, you can test it in v3-dev branch.
