### ISSUE TITLE
Removing Demo js and setting skin breaks theme

### ISSUE THREAD

**Issue by pyralix** [ColorlibHQ/AdminLTE#1906]
Greetings,

When setting the theme statically I am removing the following from the page:
`<script src="~/adminlte/dist/js/pages/dashboard.js"></script>`
`<script src="~/adminlte/dist/js/pages/dashboard2.js"></script>`
`<script src="~/adminlte/dist/js/demo.js"></script>`

Set the stylesheet
`<link rel="stylesheet" href="~/adminlte/dist/css/skins/skin-yellow.min.css">`

Then I set the body:
`<body class="skin-yellow fixed sidebar-collapse sidebar-mini">`

However, when the page loads I get a broken white/blue theme that isn't any valid theme, and the body class changes to this:
`<body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">`

Is there another step that I'm missing or a js that is setting it on load? I'd like to avoid having the colors set with javascript to avoid the flickering.

Thanks

**Comment by almasaeed2010** [comment]
Did you make sure you have adminlte.css and bootstrap.css loaded?

**Comment by REJack** [comment]
The demo.js has an script that saves the selected skin in LocalStorage, you need to remove the demo.js or clean your LocalStorage for the domain.

**Comment by smjars** [comment]
> Additionally, editing skin-blue does nothing.

you only need delete this:
