### ISSUE TITLE
AdminLTE 3 collapse button

### ISSUE THREAD

**Issue by eduardsui** [ColorlibHQ/AdminLTE#1910]
I've noticed that when switching to AdminLTE 3 (alpha 2), the collapse buttons don't switch between - and + icon. It is easy to reproduce: access https://adminlte.io/themes/dev/AdminLTE/index.html and collapse the visitors window. The window will collapse just fine, but the collapse button icon will remain the same, instead of switching to + icon(tried with Firefox and Chrome). Is this the new behavior or a bug?

Thank you for such a wonderful template!

**Comment by almasaeed2010** [comment]
Thanks for reporting @eduardsui

**Comment by eduardsui** [comment]
Tested #1938. It's working correctly.

**Comment by REJack** [comment]
This issue is already fixed you can test it on http://adminlte-dev.rejack.space/.
