### ISSUE TITLE
Navbar active item [v3-alpha2]

### ISSUE THREAD

**Issue by tradingstratagem** [ColorlibHQ/AdminLTE#1915]
### Environment:
* AdminLTE Version:  3.0.0-alpha-2
* Operating System:  OSX
* Browser (Version):  Chrome 69

### Description:
When using the navbar (https://getbootstrap.com/docs/4.1/components/navbar/),
the active item doesn't have a differente color like shown in the example page.

**Comment by almasaeed2010** [comment]
We need to implement both hover effects and active styling.

Thanks for reporting @tradingstratagem !

**Comment by shiri1248** [comment]
I can work on this issue. But the problem is  how can i run the AdminLTE Version: 3.0.0-alpha-2 in my machine. Please can you help me

**Comment by rgomez90** [comment]
Is this still an issue? 
I downloaded yesterday the alpha-2 version and I could see the different styling when `active` applied...

@shiri1248 to run it, just go to [Releases](https://github.com/almasaeed2010/AdminLTE/releases) and download [AdminLTE 3 Alpha-2](https://github.com/almasaeed2010/AdminLTE/releases/tag/v3.0.0-alpha.2)
