### ISSUE TITLE
bootstrap label

### ISSUE THREAD

**Issue by vaishnavkoka** [ColorlibHQ/AdminLTE#1920]
I have Datatable having a column named as "Status" , I am retrieving the data from the database and displaying under this column, if the status is "failed" it should be displayed under "danger-label" of bootstrap and if the status is "running" it should be displayed under "primary-label" of bootstrap as you used for [is active: bootstrap] in your datatable sample, can you just help to achieve this ?
I tried many ways but i was only able to apply some background color, which i dont like it at all.
Reference Image Link : [link](http://prntscr.com/k2iuza)

**Comment by omkartapale** [comment]
Hi @vaishnavkoka you have to do this in your PHP code. You can check your status data and accordingly set css class for element.
For example

```
<?php $status = "running";?>
<span class="label <?php echo ($status=='running')?'label-success':'label-danger';?>">Approved</span>
```
