### ISSUE TITLE
error on nav right header

### ISSUE THREAD

**Issue by frandisag** [ColorlibHQ/AdminLTE#1930]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  windows
* Browser (Version):  chrome

### Description:
how to fix it in laravel ?
![error](https://user-images.githubusercontent.com/31004538/42455094-79b405d0-83bb-11e8-9b5f-05bcbf87caf7.png)

**Comment by almasaeed2010** [comment]
Hello,

Does this happen in the demo? How can we replicate this issue?

Thanks!
