### ISSUE TITLE
left menu expand error

### ISSUE THREAD

**Issue by lruijun** [ColorlibHQ/AdminLTE#1934]
Issue type:

- [ ]   Feature request
- [x]   Bug report
- [ ]   Documentation
- [ ]   License Compliancy

Environment:
AdminLTE Version: 2.4.2、2.4.3、2.4.7 and 2.4.8
Operating System: windows
Browser (Version): Chrome

Description:
if i activate the fixed layout and click the left menu "Multilevel" and it's sub menu severl times, then the error occurred. The menu expanded above the others.
<img width="526" alt="42439755-4dd37a06-8396-11e8-98f3-3ffb56b5e49a" src="https://user-images.githubusercontent.com/5811905/42740726-c7cc86a8-88dd-11e8-8bd6-7b38f4966e78.png">

I duplicate this issue on chrome, windows os with adminlte v2.4.8 and I recorded a video below for this issue.
[AdminLTE 2 _ Dashboard - Google Chrome 2018_7_16 9_07_05.zip](https://github.com/almasaeed2010/AdminLTE/files/2196359/AdminLTE.2._.Dashboard.-.Google.Chrome.2018_7_16.9_07_05.zip)

**Comment by omkartapale** [comment]
Yes confirmed the same issue. Third level menu elements are seen overlapped.

**Comment by ahntuna** [comment]
This issue also occurs on my project. Please help to fix it. Thanks!

**Comment by REJack** [comment]
I've found the bug and added a fix into the master branch, coming with the next release (v2.4.13).
