### ISSUE TITLE
Problem in sidebar menu navigation access while using AdminLte JS

### ISSUE THREAD

**Issue by ghost** [ColorlibHQ/AdminLTE#1936]
I have a issue.
Anyone who   knows the solution, please help.
I am using   AdminLte 2 Dashboard.
I am using   my own custom DIY MVC Framework.
My Sidebar   links won't work when I include the AdminLte JS File in   "footer.php". But when I don’t include the AdminLte JS file, my   sidebar links work.
All the   links are OK. I checked it. I need to keep the AdminLte JS file and would   like everything to work properly.
![1](https://user-images.githubusercontent.com/25742312/42746091-2412aa5e-8911-11e8-923a-640af5f2fd3d.jpg)

![2](https://user-images.githubusercontent.com/25742312/42746093-27d41e48-8911-11e8-97d3-d7018cdd6f3c.jpg)

Thanking you for your understanding.

**Comment by REJack** [comment]
Try to place AdminLTE's js file as last js file or merge the multiple ul.sidebar-menu to one big ul.
