### ISSUE TITLE
Supporting html labels

### ISSUE THREAD

**Issue by ednella** [ColorlibHQ/AdminLTE#1940]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
Imagine a usual web form, with text boxes, drop lists, mandatory fields and all the rest of it. Now let's say I want to be able to edit one of the fields on the web form from my admin dashboard AdminLTE. So I just login in my admin portal and change the text, which will magically appear changed in my web form.
Well, I did all of that and it does work nicely. The challenge comes if, when editing in my admin portal, I want to include an html label in order to show a picture, or a link as part of the text to be shown in my web form. That is not working... :(

Any clue?

Thanks

**Comment by REJack** [comment]
I don't understand what you mean with html labels, for me `<label>` is a html label and this is supported out of the box.

I'll close this issue, you can reopen it if you can give me more details/infos.
