### ISSUE TITLE
Navbar Hight is not set as the template.

### ISSUE THREAD

**Issue by NomanJaved** [ColorlibHQ/AdminLTE#1941]
Navbar hight is messed up after adding all files during converting into php codeigniter files. I double checked the files included with the template files. Any guide for me how to fix it.  Also the dropdown menu are not working.
![image](https://user-images.githubusercontent.com/8793822/42843401-6e26b78e-8a29-11e8-89fc-f995a2b18503.png)
Thanks

**Comment by Ross-C** [comment]
I have also had this exact same problem with Laravel 5.6

**Comment by REJack** [comment]
This look like your html markup is not correct, I guess you missed an closing div.

I'll close this issue, please ask questions like this on stackoverflow.com with an AdminLTE tag.
