### ISSUE TITLE
[3.0 alpha 2] No more layouts?

### ISSUE THREAD

**Issue by jmsche** [ColorlibHQ/AdminLTE#1943]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: AdminLTE 3 Alpha-2
* Operating System: N/A
* Browser (Version): N/A

### Description:

Hi, I'm wondering if there are still layouts included with AdminLTE v3?

Eg. I currently haven't found any with only the top navigation as in v2.

Is it still a thing, or is it removed?

**Comment by REJack** [comment]
I've added Layout demos with #2110, you can test it in v3-dev branch.
