### ISSUE TITLE
[3.0 Alpha2] Layout does not consider footer height when setting min-height for content-wrapper

### ISSUE THREAD

**Issue by ericenns** [ColorlibHQ/AdminLTE#1944]
### Issue type:
- [ ] Feature request 
- [ x ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0 Alpha 2
* Operating System:  Linux
* Browser (Version):  (Latest)

### Description:
Layout does not consider height of the footer when setting min-height for content-wrapper.

* View "Blank Page" example @ https://adminlte.io/themes/dev/AdminLTE/pages/examples/blank.html
* Note that you have to scroll down to view the footer

**Comment by REJack** [comment]
This issue is already fixed
