### ISSUE TITLE
Wrong calculation of content-wrapper height

### ISSUE THREAD

**Issue by darkvadaure** [ColorlibHQ/AdminLTE#1947]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.7+
* Operating System:  all
* Browser (Version):  all

### Description:

In the picture you can see that the height of the content-wrapper is too small.
This is a problem of calculation in line 617 of AdminLTE.js (v2.4.7+)

if (windowHeight >= sidebarHeight ) {
        $(Selector.contentWrapper).css('min-height', windowHeight - neg);
        postSetHeight = windowHeight - neg;
      } else {
        $(Selector.contentWrapper).css('min-height', sidebarHeight);
        postSetHeight = sidebarHeight;
      }

You need to add the height of header 
if (windowHeight >= sidebarHeight + headerHeight) {

![image](https://user-images.githubusercontent.com/7440914/42959941-b9fb7994-8b8a-11e8-9c5d-a3666f7a5987.png)

**Comment by reloxx13** [comment]
Tipp:
As workaround a trigger resize on document fixed the height for me.

i hope @almasaeed2010 is alive and can merge the PR.

```
$(document).ready(function () {
   $(document).trigger("resize");
});
```

**Comment by safly** [comment]
Thanks! It works!

**Comment by REJack** [comment]
Is this issue still open in the latest version?
