### ISSUE TITLE
Add jquery.nicescroll for the scroll of the dashboard menu

### ISSUE THREAD

**Issue by dacoto** [ColorlibHQ/AdminLTE#1949]
### Issue type:
- [x] Feature request 
### Environment:
* AdminLTE Version:  v3.dev
### Description:
Use https://github.com/inuyaksa/jquery.nicescroll for the scroll of the dashboard menu

![image](https://user-images.githubusercontent.com/16915053/43027238-89b1b902-8c79-11e8-9d8a-9375296fa9e3.png)

**Comment by rodruiz** [comment]
@almasaeed2010 
I recommend: [perfect-scrollbar](https://github.com/utatti/perfect-scrollbar) 
[Demo](http://utatti.github.io/perfect-scrollbar/)

This [theme](http://themedesigner.in/demo/wrappixel/admin-template/xtreme/html/ltr/index7.html) is using it too.

Thanks.

**Comment by REJack** [comment]
I have looked over jquey.nicescroll & other alternatives and I found [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars) which works better than jquery.nicescroll and looks really nice with AdminLTE v3

**Comment by dacoto** [comment]
Yes, you are right, it is a good alternative and also without dependence on jquery.
This will go well with bootstrap 5, since the dependence on jquery will be eliminated.

**Comment by REJack** [comment]
This issue is done with #2119, you can test it on https://adminlte-dev.rejack.space/
