### ISSUE TITLE
boxWidget in version 3

### ISSUE THREAD

**Issue by knoxfighter** [ColorlibHQ/AdminLTE#1950]
### Issue type:
- [x] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0-alpha.2 
* Operating System: ubuntu 16.04 

### Description:
In the version 3.0.0-alpha.2, there is no boxWidget. Can you please implement this too? If not, does it has an alternative widget, from you or bootstrap to use?

**Comment by REJack** [comment]
In AdminLTE v3 the boxWidget is replaced with Widget, I'll create soon a documentation for AdminLTE v3.
