### ISSUE TITLE
Decouple Bootstrap from AdminLTE

### ISSUE THREAD

**Issue by bellwood** [ColorlibHQ/AdminLTE#1952]
Please please please decouple the Bootstrap CSS and JS from AdminLTE.

Integrating AdminLTE into a project that already has bootstrap adds unnecessary complication.

Thank you very much =D

**Comment by REJack** [comment]
Sorry to say but in order to integrate Bootstrap 4 correctly like it is [documented](https://getbootstrap.com/docs/4.3/getting-started/theming/) we can only get a combined css file with Bootstrap and AdminLTE.
