### ISSUE TITLE
About Sidebar's scrollbar

### ISSUE THREAD

**Issue by jyxjjj** [ColorlibHQ/AdminLTE#1957]
### Issue type:
- [X] Feature request

### Environment:
* AdminLTE Version:  v3.0.0-alpha.2
* Operating System:  Windows 1920*1080
* Browser (Version):  Chrome 68.0.3440.84

### Description:
Sidebar's scrollbar is ugly by chrome default.
### Recommond: 
Transparent.

**Comment by jyxjjj** [comment]
Uh....But I think it should be concealed instead of hidden.
Just like AdmineLTE 2 "index1.html"
> body > div.wrapper > div.content-wrapper > section.content > div:nth-child(2) > section.col-lg-7.connectedSortable.ui-sortable > div.box.box-success > div.slimScrollDiv > div.slimScrollBar

**Comment by REJack** [comment]
This issue is already fixed you can test it on http://adminlte-dev.rejack.space/.

**Comment by jyxjjj** [comment]
> This issue is already fixed you can test it on http://adminlte-dev.rejack.space/.

Sorry, has the old version been deleted?
Which two commit hashes should we compare to find the difference?
It was too long spend, i have already forgot the old version.

**Comment by REJack** [comment]
The old version not loaded slimScroll, now it's loaded in index.html for demo purposes.

But slimScroll will be replaced soon.
