### ISSUE TITLE
mail box not warking

### ISSUE THREAD

**Issue by Apical-shop** [ColorlibHQ/AdminLTE#1958]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
 How to set mail inbox, send, junk, link.

**Comment by n3storm** [comment]
This project is not an application that will do anything. Is just the HTML elements, CSS styles and JS componentes to build your own application.

@almasaeed2010 please close this issue
