### ISSUE TITLE
Use both layout-top-nav  and sidebar in one page?

### ISSUE THREAD

**Issue by Wuaner** [ColorlibHQ/AdminLTE#1959]
Hi guys, 

Is there any example to illustrate how can I use both Top Navigation and Sidebar in one page like this?
The top navigation show sub modules
The sidebar show functions that corresponding to the selected sub-module.
![Top Navigation and Sidebar](https://preview.ibb.co/i69Toz/top_and_side.jpg)

Thanks in advance.

**Comment by Wuaner** [comment]
Supplementary: 
The top navigation show sub modules
The sidebar show functions that corresponding to the selected sub-module.

**Comment by REJack** [comment]
You can easily add top nav items beside .sidebar-toggle, like this:

```
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a>
  <ul class="nav navbar-nav">
    <li><a href="#"><i class="fa fa-dashboard"></i></a></li>
  </ul>
</nav>
```
