### ISSUE TITLE
Vector map not working properly in local server.

### ISSUE THREAD

**Issue by RaruRv** [ColorlibHQ/AdminLTE#1961]
### Issue type:
- [x] Bug report    
Vector map not working properly in local server.

after downloading and running the template in my loacl machine the tooltip in the vector map is not working.

URL: https://adminlte.io/themes/AdminLTE/index2.html
Check Visitors Report

### Environment:
* AdminLTE Version:  2.4.5
* Operating System:  Ubuntu 16.04
* Browser (Version):  Google Chrome 55.0.2883.87

**Comment by cracker182** [comment]
can you check your console (dev-tools) maybe there is a hint, why the map do not work

Cheers
