### ISSUE TITLE
Problems with Timepicker in AdminLTE v3

### ISSUE THREAD

**Issue by vailukhin** [ColorlibHQ/AdminLTE#1962]
Hello

I have problems with datepicker in AdminLTE v3
https://github.com/almasaeed2010/AdminLTE/blob/v3-dev/pages/forms/advanced.html

I cant see arrows. Example in screenshoot
![default](https://user-images.githubusercontent.com/7951414/43825707-1a68df60-9afe-11e8-924b-cc09ec345490.png)

**Comment by REJack** [comment]
This issue is already fixed with #1968
