### ISSUE TITLE
Broken link on installation docs page (https://adminlte.io/adminlte-docs/%7Bv%7D/dependencies)

### ISSUE THREAD

**Issue by opensas** [ColorlibHQ/AdminLTE#1965]
### Issue type:
- [X] Bug report
- [X] Documentation

### Online documentation

* AdminLTE Version:  2.4
* Operating System:  any
* Browser (Version):  any

### Description:

Steps: 
- navigate to https://adminlte.io/docs/2.4/installation
- click [dependencies section](https://adminlte.io/adminlte-docs/%7Bv%7D/dependencies) link
- you'll be redirected to `https://adminlte.io/adminlte-docs/%7Bv%7D/dependencies` instead of `https://adminlte.io/docs/2.4/dependencies`

**Comment by REJack** [comment]
I'm can't change the docs for 2.4 but I'll move the docs to the repo so we can manage them from the repo.
