### ISSUE TITLE
More Skins or Something like Child template for adminlte

### ISSUE THREAD

**Issue by twf-nikhila** [ColorlibHQ/AdminLTE#1966]
### Issue type:
- [x ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:

Firstly thanks for this beautiful open source theme. 

I have been using this theme for a project. We have different skin options but these only changes the colour of header & sidebar. I'm looking for a much better skin which can change the look & feel of the theme.

Does anyone have created any alternative skins? If so it will be nice if you can share it.

Thank you in advance :)

Thanks again for this theme :)

**Comment by REJack** [comment]
I don't know about any alternative skins for AdminLTE.
