### ISSUE TITLE
.sidebar-toggle not show icon when fontawesome 5

### ISSUE THREAD

**Issue by awebc** [ColorlibHQ/AdminLTE#1973]
![Uploading FireShot Capture 18 - Welcome - Admin - https___www.nygq.net_admin_default_welcome.png…]()
![Uploading FireShot Capture 18 - Welcome - Admin - https___www.nygq.net_admin_default_welcome.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by REJack** [comment]
I've added abilty to use FA5 in AdminLTE v2, in the next version you can simply add .fa5 to .sidebar-toggle
