### ISSUE TITLE
Update Font Awesome library to 5.x

### ISSUE THREAD

**Issue by mt77s2** [ColorlibHQ/AdminLTE#1975]
Hi there. I was hoping we could see a new release of Admin LTE that uses Font Awesome 5. Thanks!

**Comment by StephanBis** [comment]
It's very easy to update it yourself! 
Check the FontAwesome website, it has a tutorial for upgrading from 4.* to 5.*. Its basically as easy as replacing and adding one .css file and editing your CSS link in HTML.

**Comment by mxdpeep** [comment]
what's worse is to upgrade to Bootstrap 4 :{

**Comment by weholt** [comment]
Yes, I tried updating to Bootstrap 4.0 and it didn't work at all. Looked all crooked and lots of javascript errors in the developers console. Is this a planned upgrade in the near future?

**Comment by StephanBis** [comment]
You don't have to update it yourself, just download the Alpha 2 and migrate what's new: HTML, CSS, JS files. It really isn't that hard to do, I did it in 2 hours and everything (including Font Awesome 5) works like a charm!

**Comment by REJack** [comment]
AdminLTE v3 comes with FA5, but you can use FA5 in v2 too.
