### ISSUE TITLE
Login screen body does not stretch to full height

### ISSUE THREAD

**Issue by cactusjack66** [ColorlibHQ/AdminLTE#1977]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4 
* Operating System:  Windows 10
* Browser (Version): Chrome (Latest)
* Visual Studio Code, Angular 6

### Description:
Make a new Angular App using Visual Code with Angular CLI ng new TestApp.
Install admin-lte with ng install admin-lte.
Remove the sample code in app.component.html.
Add neccessary styles and scripts to angular.json.

Copy the sample code from the AdminLTE source code to the app.component.html.

What you get is this:
![issue](https://user-images.githubusercontent.com/42271325/44584339-ee59b180-a7a8-11e8-87aa-1c837e6b189c.png)

I am not able to stretch the login screen to full height. Body 100%, html 100% and all fixes from other posts which are similar to this did not work. The html stretches to full height, but the body does not.

**Comment by REJack** [comment]
This issue is fixed, you can test the latest version.
