### ISSUE TITLE
Remove dependency on jvectormap

### ISSUE THREAD

**Issue by dkarchmer** [ColorlibHQ/AdminLTE#1980]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.3 
* Operating System:  
* Browser (Version):  

### Description:

This package uses an AGPL license which is problematic. It is the only dependency in such a license, and therefore is not worth it for this project to use.

**Comment by dkarchmer** [comment]
This is what https://fossa.io reports on jvectormap when analyzing a project that uses admin-lte

> AGPL requires you to disclose the source code of “derivative” works even for hosted/network software. Due to the broad scope of what falls under “derivative”, by default we deny AGPL (though acceptable to “flag” instead). Also contains provisions requiring delivery of installation information for consumer devices (which may be inconsistent with use in closed systems).

**Comment by REJack** [comment]
In AdminLTE v2, I doesn't replace/remove jvectormap but I replaced it in v3.
