### ISSUE TITLE
Scale Viewport - Fixed Menu, footer and header

### ISSUE THREAD

**Issue by SirwanAfifi** [ColorlibHQ/AdminLTE#1984]
Can anyone offer a solution to the following issue

We have a dashboard layout based upon adminLTE

The side menus are fixed and do not sit within a tree structure

There are 16 menu items

When the user opens the dashboard on their screen, we would like the viewport to scale to the size of the screen without losing any of the
main canvas, header, footer and menu items (they must not collapse)  - the ideal scenario is that the viewport zooms to scale and if it is too small, the fonts are simply unreadable (as they will be too small to read)

**Comment by REJack** [comment]
Sadly there is no solution for this issue, I also searched often for something like this.
