### ISSUE TITLE
how to upgrade to version 3.0.0 simple

### ISSUE THREAD

**Issue by Janus-Xu** [ColorlibHQ/AdminLTE#1989]
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0 
* Operating System:  Windows
* Browser (Version):   Chrome (Latest) 

### Description:
i have tried upgrade to v3.0.0，and it seems a big change，almost all html-tags、class-tags has been changed.
is this version backward compatible?
or
are there any docs about how to upgrade from v2.4 to v3.0？

**Comment by Baozi2** [comment]
v3.0 base on bootstrap4，so， before you upgrade，read about bootstrap 4

**Comment by REJack** [comment]
I've added simple upgrade guide in docs
