### ISSUE TITLE
bootstrap vulnerabilities Bug report

### ISSUE THREAD

**Issue by mxdpeep** [ColorlibHQ/AdminLTE#1990]
### Issue type:
- Bug report

### Environment:
* AdminLTE Version:  2.4.5
* Operating System:  N/A
* Browser (Version):  N/A

### Description:
known XSS vulnerabilities
(detected by Google Chrome Lighthouse Auditing)
[https://snyk.io/vuln/npm:bootstrap?lh@3.3.7](https://snyk.io/vuln/npm:bootstrap?lh@3.3.7)

**Comment by Jamesking56** [comment]
See #2038
