### ISSUE TITLE
Unable to expand ajax loaded collapse box adminlte

### ISSUE THREAD

**Issue by ranjangolden** [ColorlibHQ/AdminLTE#1991]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:

Please Help
 Normal Loading is working, but when i am loading collapse box using ajax it is not working. Unable to expand collapse box

```
<div class="box box-primary collapsed-box">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Project Type</h3>

                                    <div class="box-tools pull-right">
                                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                    <!-- /.box-tools -->
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body"  style="height:120px;overflow: scroll">
                                    //CONTENT OF BOX
                                </div>
                                <!-- /.box-body -->
                            </div>
```

**Comment by OldaHorak** [comment]
@ranjangolden Can you provide more details?
How do you load the content of the box?
`$("#theboxid .box-body").load("new_content.txt");`
I used this code just now and all is OK, the loaded box can be expanded or collapsed without problems.

**Comment by pkeogan** [comment]
if you dynamically add a box to the page, the collapse and remove widgets do not work, just confirmed it by using `$().appends(HTML)?`

**Comment by pkeogan** [comment]
@ranjangolden **How To Fix:**

After ajax loading your box in, you need to reinitialize the box, or boxes. You may be confused because the documentation is wrong.  https://adminlte.io/docs/2.4/js-box-widget

```
...

$('.box').boxWidget({
    animationSpeed : 500,
    collapseTrigger: '[data-widget="collapse"]',
    removeTrigger  : '[data-widget="remove"]',
    collapseIcon   : 'fa-minus',
    expandIcon     : 'fa-plus',
    removeIcon     : 'fa-times'
})

...
```
