### ISSUE TITLE
AdminLTE requires jquery v2.4.8.

### ISSUE THREAD

**Issue by franferns** [ColorlibHQ/AdminLTE#1992]
Hi, 
I get this error when i try to reference the admin-lte

![image](https://user-images.githubusercontent.com/779253/45731592-f9600000-bbf5-11e8-82f2-4c08188258ff.png)

Is there something that i am missing probably something really basic ? I am using a typescript react project .  I have installed jquery and am importing jquery before importing admin-lte .Thanks.

Regards,
Francis P.

**Comment by esavichev** [comment]
Any news? I've faced exactly the same issue. Is there any recommended way to integrate admin-lte into ES6 project via import?

**Comment by franferns** [comment]
try referencing the adminlte.js and the jquery in your public/index.html
```
<script type="text/javascript" charset="utf-8" src="jquery.js"></script>
  <script type="text/javascript" charset="utf-8" src="adminlte.js"></script>
```

**Comment by esavichev** [comment]
> try referencing the adminlte.js and the jquery in your public/index.html
> 
> ```
> <script type="text/javascript" charset="utf-8" src="jquery.js"></script>
>   <script type="text/javascript" charset="utf-8" src="adminlte.js"></script>
> ```

Of course, it works. But it is not ES6 or CommonJS way to manage dependencies and bundling the application.
