### ISSUE TITLE
Using chart boxe inside a TAB not display !

### ISSUE THREAD

**Issue by techfree** [ColorlibHQ/AdminLTE#1993]
Hi, 

I am trying to display a chart collapsable box inside a tab div but the chart doesnt display.
If i put the chart box outside the `<div class="tab-pane" id="tab_name">`  work.
Can you tell me please how must be structure the div box to display the chart inside a tab ?

Regards.

**Comment by REJack** [comment]
You need to render/create the Chart after switching to the tab, i have often problems like this with tabs.
