### ISSUE TITLE
Issue in carousel in UI>general.html

### ISSUE THREAD

**Issue by RaruRv** [ColorlibHQ/AdminLTE#1994]
A design issue found in carousel in general.html. 
Link => https://adminlte.io/themes/AdminLTE/pages/UI/general.html

### Environment:
* AdminLTE Version:  2.4.0
* Operating System:  Ubuntu
* Browser (Version):  Google Chrome (Version 55.0.2883.87 (64-bit) )

#Description 
A design issue found in carousel in general.html. 
Link => https://adminlte.io/themes/AdminLTE/pages/UI/general.html
Please scroll down and check the carousel.

**Comment by pramilgawande** [comment]
Could you please elaborate further ?
