### ISSUE TITLE
search bar overlapping responsive issue

### ISSUE THREAD

**Issue by abhishektomer** [ColorlibHQ/AdminLTE#1995]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
![2018-09-20](https://user-images.githubusercontent.com/25544041/45812335-24794b00-bced-11e8-9058-3fc1b6e1a0dc.png)

**Comment by REJack** [comment]
I've added .hidden-xs to the input-group but this is only a workaround, the searchbar isn't a real part of the tables or box-tools it's only a example what you can do with the box-tools.
