### ISSUE TITLE
Problem with scroll and wide content

### ISSUE THREAD

**Issue by alekson** [ColorlibHQ/AdminLTE#1999]
Need scrolls with wide content, as in the standard tweet bootstrap.
How to do it?

Problem:
https://cl.ly/c24a3355d608

**Comment by galihsetyo** [comment]
have you used table-responsive class?. 
https://getbootstrap.com/docs/3.3/css/#tables-responsive

**Comment by heemza** [comment]
> yes, not work - https://cl.ly/83dabc63085c
> 
> but work "min-width", https://cl.ly/92606de0c692

.table-responsive class should be the parent of table not itself.

```
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

**Comment by alekson** [comment]
thx! it works!
