### ISSUE TITLE
Accordion sidebar menu item is shown only when page is load ,but later does not showed the listed item when clicked 

### ISSUE THREAD

**Issue by Iqbal487** [ColorlibHQ/AdminLTE#2007]
Hi , In Accordion sidebar menu item is shown only when i reload the page .but, later no events is happened when i clicked on the listed menu in sidebar . The Dashboard and other menu is clicked but don not show anything .
Here is the view when the page is reload --
![image](https://user-images.githubusercontent.com/15795139/46582589-3be56180-ca6b-11e8-968a-3d0ddb99fe74.png)
But when i clicked on any item of this sidebar 
this view is appeared and no list item as well as sub menu is not shown --
![image](https://user-images.githubusercontent.com/15795139/46582610-66371f00-ca6b-11e8-9e55-b2a51d781e7b.png)

by clicking the sidebar menu item nothing is happened , there is no sub menu item is shown .

**Comment by REJack** [comment]
It look like your html markup is not correct.
