### ISSUE TITLE
进入页面点击侧边栏没反应

### ISSUE THREAD

**Issue by YuFy1314** [ColorlibHQ/AdminLTE#2009]
这个框架在和element-ui结合使用的情况下, 通过点击登录跳转到首页, 然后再点击首页左侧的菜单, 发现菜单点击不了, 没反应, 然后刷新一下页面, 才好使, 这个是怎么回事? 和element-ui有冲突关系么?
![](https://user-images.githubusercontent.com/24446694/46940737-06103080-d09c-11e8-8dfa-f84faa363393.png)
执行这个登录方法, 登录方法里面的内容就是验证之后跳转路由:
![](https://user-images.githubusercontent.com/24446694/46940809-2e982a80-d09c-11e8-94da-607089f6b595.png)
跳转到主页:
![](https://user-images.githubusercontent.com/24446694/46940838-4374be00-d09c-11e8-9865-a8fc5e03f74f.png)
然后点击左侧的菜单, 以下是菜单代码:
![](https://user-images.githubusercontent.com/24446694/46940861-54bdca80-d09c-11e8-8559-04b74ae51d48.png)
进来之后点击菜单不好使, 再刷新一下页面再点击才好使, 这是怎么回事呢, 希望看到的大神帮助下谢谢

**Comment by er1z** [comment]
Really glad that the whole community understand this.

**Comment by ajcastro** [comment]
is that vue with admin lte? I am also looking for an vue port of adminlte

**Comment by Baozi2** [comment]
你是怎么结合使用的，是只用了adminLTE的css还是把js也拿进来了，要是把js也拿进来，是不是有地方冲突了

**Comment by Baozi2** [comment]
怎么和element-ui集成的？你都没有说清楚

**Comment by REJack** [comment]
Is this Issue still open?
