### ISSUE TITLE
Problem with arrow in left side bar menu

### ISSUE THREAD

**Issue by eothein** [ColorlibHQ/AdminLTE#2011]
### Issue type:
- [ x] Bug report       

### Environment:
* AdminLTE Version:  2.4.8
* Operating System:  Mac OS Maverick
* Browser (Version):  FireFox

### Description:
After updating to the latest version, my application crashes by not showing the arrow correctly in the left side bar. I have updated my code as per the documentation.  

<img width="220" alt="schermafbeelding 2018-10-19 om 17 35 56" src="https://user-images.githubusercontent.com/7603307/47228710-2acf1580-d3c6-11e8-843d-0dbaa6be89be.png">

The code I have for the left side bar is the following:

`<section class="sidebar" style="height: auto;">

        
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/images/users/erci8ZdixsSnQyGJTdNG3eo8-KZljaPHchicken.jpg" class="img-circle" alt="User Image">	
            </div>
            <div class="pull-left info">
                <p>TimAdmin</p>

                <a href="#"><svg class="svg-inline--fa fa-circle fa-w-16 text-success" aria-hidden="true" data-prefix="fa" data-icon="circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8z"></path></svg> Online</a>
            </div>
        </div>

        
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><svg class="svg-inline--fa fa-search fa-w-16" aria-hidden="true" data-prefix="fa" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg>
                    </button>
                </span>
            </div>
        </form>
        

        
        <ul class="sidebar-menu tree" data-widget="tree"><li><a href="/site/index"><svg class="svg-inline--fa fa-share fa-w-16" aria-hidden="true" data-prefix="fa" data-icon="share" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M503.691 189.836L327.687 37.851C312.281 24.546 288 35.347 288 56.015v80.053C127.371 137.907 0 170.1 0 322.326c0 61.441 39.581 122.309 83.333 154.132 13.653 9.931 33.111-2.533 28.077-18.631C66.066 312.814 132.917 274.316 288 272.085V360c0 20.7 24.3 31.453 39.687 18.164l176.004-152c11.071-9.562 11.086-26.753 0-36.328z"></path></svg>  <span>Dashboard</span></a></li>
<li><a href="/site/offertedashboard"><svg class="svg-inline--fa fa-share fa-w-16" aria-hidden="true" data-prefix="fa" data-icon="share" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M503.691 189.836L327.687 37.851C312.281 24.546 288 35.347 288 56.015v80.053C127.371 137.907 0 170.1 0 322.326c0 61.441 39.581 122.309 83.333 154.132 13.653 9.931 33.111-2.533 28.077-18.631C66.066 312.814 132.917 274.316 288 272.085V360c0 20.7 24.3 31.453 39.687 18.164l176.004-152c11.071-9.562 11.086-26.753 0-36.328z"></path></svg><!-- <i class="fa fa-fa fa-share"></i>  <span>Offerte Dashboard</span></a></li>
<li class="treeview"><a href="#"><svg class="svg-inline--fa fa-share fa-w-16" aria-hidden="true" data-prefix="fa" data-icon="share" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M503.691 189.836L327.687 37.851C312.281 24.546 288 35.347 288 56.015v80.053C127.371 137.907 0 170.1 0 322.326c0 61.441 39.581 122.309 83.333 154.132 13.653 9.931 33.111-2.533 28.077-18.631C66.066 312.814 132.917 274.316 288 272.085V360c0 20.7 24.3 31.453 39.687 18.164l176.004-152c11.071-9.562 11.086-26.753 0-36.328z"></path></svg><!-- <i class="fa fa-fa fa-share"></i>  <span>Klantenbeheer</span> <span class="pull-right-container"><svg class="svg-inline--fa fa-angle-left fa-w-8 pull-right" aria-hidden="true" data-prefix="fa" data-icon="angle-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" data-fa-i2svg=""><path fill="currentColor" d="M31.7 239l136-136c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9L127.9 256l96.4 96.4c9.4 9.4 9.4 24.6 0 33.9L201.7 409c-9.4 9.4-24.6 9.4-33.9 0l-136-136c-9.5-9.4-9.5-24.6-.1-34z"></path></svg> <i class="fa fa-angle-left pull-right"></i> </span></a>
    </section>`

**Comment by henri9813** [comment]
Hello,

Which version of font awesome are you using ?

**Comment by eothein** [comment]
@henri9813 Thanks for letting me check that: I'm using Yii2 with the dmstr library to import Admin LTE, but I was also using the Kartik Icon library. These both loaded different version of FontAwesome which conflicted with each other, loaded outdated icons (I guess).

Deleting the Kartik library solved the isse. 

Thanks for the heads up!

**Comment by henri9813** [comment]
Hello @eothein, 

I'm satisfacted you fixed your issue. 
Currently they are an issue related to the FontAwesome 5 integration with AdminLTE: #1975 

Regards

**Comment by phoolto** [comment]
Put these settings before loading fontawesome in Javascript. This will nest the svg's in the used <i> and fixes your issue.

`FontAwesomeConfig = {
          autoReplaceSvg: 'nest'
      };`

**Comment by REJack** [comment]
Is this issue still open?

**Comment by henri9813** [comment]
Hello @REJack 

I think not, @eothein  may forgot to close this issue.

Regards

**Comment by REJack** [comment]
Ok nice, I'll close it 😄

**Comment by eothein** [comment]
My apologies, I forgo to close indeed! Thanks for the help!

**Comment by diegotejadav** [comment]
> @henri9813 Thanks for letting me check that: I'm using Yii2 with the dmstr library to import Admin LTE, but I was also using the Kartik Icon library. These both loaded different version of FontAwesome which conflicted with each other, loaded outdated icons (I guess).
> 
> Deleting the Kartik library solved the isse.
> 
> Thanks for the heads up!

@eothein suggestion worked perfectly!! thank you so much!
