### ISSUE TITLE
Support for input type="range"

### ISSUE THREAD

**Issue by henri9813** [ColorlibHQ/AdminLTE#2013]
### Issue type:
- [X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  All
* Operating System:  All
* Browser (Version):  All

### Description:

It could be very cool if AdminLte could support the range type.

Here is a screen of the render of `type=range` without CSS.

![image](https://user-images.githubusercontent.com/4645967/47296690-5a269200-d613-11e8-888f-97aa8cc06080.png)

**Comment by REJack** [comment]
I've added this feature into v3, you can check it [here](https://adminlte.io/themes/dev/AdminLTE/pages/forms/general.html#customRange1)
