### ISSUE TITLE
Adding a Facebook style popup notification

### ISSUE THREAD

**Issue by samisadder** [ColorlibHQ/AdminLTE#2015]
Hello,

I need to have a small box which pops up on the bottom left side the same like in facebook. I tried to develop it myself, but I will prefer if it is done before

Thanks

**Comment by Devin0231577** [comment]
You could implement any javascript plugin for "Toasts". That is the concept you are looking for I believe. My preferred plugins for this are either [izimodal](http://izitoast.marcelodolce.com/) or [SweetAlerts2](https://sweetalert2.github.io/#mixin) both of which are super easy to implement on your own. I don't think it would be a terrible idea to add one of these to the core functionality of admin lte but there are already so many different options available and everyone has their own preference.

**Comment by REJack** [comment]
I've added SweetAlerts2 in AdminLTE, you can test it [here](https://adminlte.io/themes/dev/AdminLTE/pages/UI/modals.html)
