### ISSUE TITLE
treeview-menu issue

### ISSUE THREAD

**Issue by jsCabed** [ColorlibHQ/AdminLTE#2019]
### Issue type:
- [x ] Bug report       

### Environment:
* AdminLTE Version: 2.4.5 

### Description:
When navigating continuously in the left menu, there comes a time when expanding an option is shown as follows.
![image](https://user-images.githubusercontent.com/1258891/47750651-7c449380-dc55-11e8-96cd-b3b4f374b75b.png)

When I see the generated code, I realize that the last menu that I expanded contains the style in an erroneous way. I have tried to collapse all the options using jquery but the error persists.

![image](https://user-images.githubusercontent.com/1258891/47750783-bdd53e80-dc55-11e8-9183-72773d93e19a.png)

By changing the style of the menu to display: none; It starts working without problems.

![image](https://user-images.githubusercontent.com/1258891/47750945-22909900-dc56-11e8-880e-39aa4c0daa4a.png)

**Comment by minhchuongqt** [comment]
"By changing the style of the menu to display: none; It starts working without problems." I need an answer is more clear. My menu has no display when i change the style to none. Thank you!

**Comment by minhchuongqt** [comment]
> By changing the style of the menu to display: none; It starts working without problems.
 I need an answer is more clear. My menu has no display when i change the style to none. Thank you!

**Comment by Lowhearth** [comment]
The slideUp and slideDown methods callbacks where triggering the events before the queue was finished.
The pull request totally does solve the problem, not sure if its elegant enought tho.

**Comment by Lowhearth** [comment]
To better reproduce the bug just increase the animationSpeed and spam click at a treview menu.

**Comment by sebarswee** [comment]
AdminLTE version：2.4.9

The problem reproduce by using fixed layout and spam click at a treview menu.
The same goes for the official website example.

![1569326072(1)](https://user-images.githubusercontent.com/4177237/65509839-0c429a00-df06-11e9-9fc7-181b04180a90.jpg)

**Comment by REJack** [comment]
This bug comes often from an old jquery version, please update AdminLTE or at least jQuery to v3.4.1.
