### ISSUE TITLE
Fixed layout in AdminLTE3

### ISSUE THREAD

**Issue by tikky** [ColorlibHQ/AdminLTE#2020]
### Issue type:
- [x] Feature request
- [ ] Bug report
- [x] Documentation

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
Hello, is there possible to use AdminLTE3 with fixed layout,
like in Admin LTE2: https://adminlte.io/themes/AdminLTE/pages/layout/fixed.html

I would like to user AdminLTE3 to display google maps + sidebar.
The thing is that I would like to use a fixed layout, without scrolling.

**Comment by tikky** [comment]
This is how it looks just now:
<img width="971" alt="fixed_layout" src="https://user-images.githubusercontent.com/546755/48401640-e5360c00-e729-11e8-8f05-6fd703d2f362.PNG">

how to make it full page, without the scroll?

**Comment by REJack** [comment]
This looks like you set not the correct height for your google maps, try `height: calc(100% - 102px);`

**Comment by tikky** [comment]
Hello, as for now I am using something like this with my map (Leaflet.js in my example) without footer:

  
  <div class="content-wrapper" >
	<div id="map" style="width: 100%; height: calc(100vh - 57px); position: relative; outline: none;"></div>
  </div>

**Comment by REJack** [comment]
I've created a js option for this, you can now add `.content-fixed` to body and then content-wrapper get's the same `height` as `min-height` is set, then you can set height 100% for the map. 
You can test it in the v3-dev branch.
