### ISSUE TITLE
 What's the problem?

### ISSUE THREAD

**Issue by Ho-Gyu-Lee** [ColorlibHQ/AdminLTE#2022]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v2.4.8
* Operating System:  Windows
* Browser (Version):  Explorer & Chrom

### Description:

![top](https://user-images.githubusercontent.com/7202847/48758809-a2090980-ece4-11e8-910f-d45ac493cd47.png)

Python Flask + AdminLTE 2.4.8

Problems occur when encoding html files to utf-8. but there is no problem with ANSI.

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.10)?
