### ISSUE TITLE
Add stacked bar chart support

### ISSUE THREAD

**Issue by SinaSn** [ColorlibHQ/AdminLTE#2023]
Hi, Please add stacked bar chart (Chart.js) support.
https://www.chartjs.org/samples/latest/charts/bar/stacked.html

**Comment by REJack** [comment]
I've add some other ChartJs demo's in v3-dev, check out [this](https://adminlte.io/themes/dev/AdminLTE/pages/charts/chartjs.html)

**Comment by nelsondcosta23** [comment]
There is anyway to add total ath the top?
