### ISSUE TITLE
Treeview menu and tabs

### ISSUE THREAD

**Issue by zanscath** [ColorlibHQ/AdminLTE#2025]
### Issue type:
- [ ] Bug report

### Environment:
* AdminLTE Version:  2.5
* Operating System:  w10
* Browser (Version):  Firefox V63.0.3

### Description:
If I try to implement a sidebar menu that opens different tabs rather than links on separate pages the datatree plugin is showing interesting behavior: when clicking on a normal li for the first time, the opened treeview closes (as expected). When clicking on the treeview again, the previously active li remains active, the treeview opens but does not get the class "active". If clicking again on a regular li, the treeview doesn't close anymore as one would expect.

Here's what i think is relevant code:

> <section class="sidebar">
	<ul class="sidebar-menu" data-widget="tree">
		<li class="header">NAVIGARE</li>
		<li class="active treeview menu-open">
			<a href="#"><i class="fa fa-list"></i> <span>Sarcini</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
			<ul class="treeview-menu">
				<li><a id="ttqTasksBtn" data-toggle="tab" href="#sarcini"><i class="fa fa-circle-o"></i> Sarcini V1</a></li>
				<li class="active"><a id="ttqTasksBtnAlt" data-toggle="tab" href="#sarcini"><i class="fa fa-circle-o"></i> Sarcini V2</a></li>
			</ul>
		</li>
		<li><a id="ttqPlansBtn" data-toggle="tab" href="#planificare"><i class="fa fa-calendar"></i> <span>Planificare</span></a></li>
		<li><a id="ttqProjectsBtn" data-toggle="tab" href="#proiecte"><i class="fa fa-cubes"></i> <span>Proiecte</span></a></li>
	</ul>
</section>

**Comment by iyilm4z** [comment]
+1

**Comment by REJack** [comment]
Try to to add or change the `data-accordion` to `true` beside `data-widget="tree"` like 
``` html
<ul class="sidebar-menu" data-widget="tree" data-accordion="true">
...
</ul>
```
