### ISSUE TITLE
Ajax call the main template

### ISSUE THREAD

**Issue by dantedantas** [ColorlibHQ/AdminLTE#2028]
### Issue type:
- [X] Bug report       
- [ ] Feature request 
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.3
* Operating System Server:  WindowsServer2012 R2
* Operating System Client:  Windows10
* Browser (Version):  Google Chrome 70.0.3538.102 (Official Build) (64-bit)

### Description:

Dear All,

Actually I am trying to use an Ajax script without success. All time that I am trying to call the function it load the main layout of the page (or the page itself).

![image](https://user-images.githubusercontent.com/10854571/49082438-0c243000-f24a-11e8-8f16-68f0f0d7dae3.png)

I tried the code outside of the AdminLTE and it works fine.

Please, may someone help me?

My code:

````
<script>
function showHint(str) {
    if (str.length == 0) { 
        document.getElementById("txtHint").innerHTML = "";
        return;
    } else {
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("txtHint").innerHTML = this.responseText;
            }
        };
        xmlhttp.open("POST", "getjornal.php?" + str, true);
        xmlhttp.send();
    }
}
</script>
``` `

And to show the result:

`<p><span onclick="showHint('j=200094&a=V&o=D')">CLICK HERE!!!</span></p>
<p id="txtHint"></p>`

As I said, it works outside of the AdminLTE. I did many tests here without success. :(

Please, may someone help me?

Thank you in advance.

Best regards,
Dante Dantas

**Comment by dantedantas** [comment]
I tried now to open it inside of an iFrame but I got the same result.

![image](https://user-images.githubusercontent.com/10854571/49087031-41cf1600-f256-11e8-8bee-7e5f1259f0e9.png)

Here is the code:

![image](https://user-images.githubusercontent.com/10854571/49087214-ae4a1500-f256-11e8-89ad-6e5df8024867.png)

And the page getjornal.php:
(I dont have any HTML code, just PHP.)

![image](https://user-images.githubusercontent.com/10854571/49087299-e7828500-f256-11e8-831e-26e3fd24904d.png)

Thank you in advance.

BR,
Dante Dantas

**Comment by dantedantas** [comment]
In version 2.4 also doesn't work. :P

**Comment by heemza** [comment]
It seems that getjornal.php generate html with main layout html. 
Please make sure it only generate html which you want (e.g. extended class, auto template etc.)
