### ISSUE TITLE
How long for the hiatus to end?

### ISSUE THREAD

**Issue by Morinohtar** [ColorlibHQ/AdminLTE#2030]
Just wondering if this awesome project (v2 and v3) is still going on or if this long hiatus is a sign that is going to stop for good. Any news?

**Comment by REJack** [comment]
I've released recently v3.0.0-beta.2 and created a milestone for v3.0.0-rc.1 with 1. Sept '19 as due date, you can look at #2190 with new infos about v3.0.0-beta.2 there is also a docs & demo link.
