### ISSUE TITLE
Select2 can't call ajax

### ISSUE THREAD

**Issue by ragshion** [ColorlibHQ/AdminLTE#2031]
admin lte 3, i have issues why i can't call ajax request in select2 ? if class in select tag is'nt 'select2' and i don't get the data after click it... 
i use source code from https://select2.org/data-sources/ajax

**Comment by REJack** [comment]
Please give some more informations like used html code & js code.

**Comment by ragshion** [comment]
this my code, i use example from https://select2.org/data-sources/ajax , i have tried in pure bootstrap 4, and works well. but in admin lte 3, it's just a blank input

html

<div class="form-group">
  <label class="control-label">Nama Sekolah Sebelumya</label>
    <select class="form-control" id="selsekol" style="width: 100%;" tabindex="-1" aria-hidden="true">
    </select>
</div>

javascript

$("#selsekol").select2({
  ajax: {
    url: "https://api.github.com/search/repositories",
    dataType: 'json',
    delay: 250,
    data: function (params) {
      return {
        q: params.term, // search term
        page: params.page
      };
    },
    processResults: function (data, params) {
      params.page = params.page || 1;

      return {
        results: data.items,
        pagination: {
          more: (params.page * 30) < data.total_count
        }
      };
    },
    cache: true
  },
  placeholder: 'Search for a repository',
  escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
  minimumInputLength: 1,
  templateResult: formatRepo,
  templateSelection: formatRepoSelection
});

function formatRepo (repo) {
  if (repo.loading) {
    return repo.text;
  }

  var markup = "<div class='select2-result-repository clearfix'>" +
    "<div class='select2-result-repository__avatar'><img src='" + repo.owner.avatar_url + "' /></div>" +
    "<div class='select2-result-repository__meta'>" +
      "<div class='select2-result-repository__title'>" + repo.full_name + "</div>";

  if (repo.description) {
    markup += "<div class='select2-result-repository__description'>" + repo.description + "</div>";
  }

  markup += "<div class='select2-result-repository__statistics'>" +
    "<div class='select2-result-repository__forks'><i class='fa fa-flash'></i> " + repo.forks_count + " Forks</div>" +
    "<div class='select2-result-repository__stargazers'><i class='fa fa-star'></i> " + repo.stargazers_count + " Stars</div>" +
    "<div class='select2-result-repository__watchers'><i class='fa fa-eye'></i> " + repo.watchers_count + " Watchers</div>" +
  "</div>" +
  "</div></div>";

  return markup;
}

function formatRepoSelection (repo) {
  return repo.full_name || repo.text;
}

**Comment by ragshion** [comment]
I have check my console too.. but i didn't see any errors

**Comment by REJack** [comment]
Is your code inside `$(function () {` or `$(document).ready(function(){`?

Like this:
```
$(function () {
  $("#selsekol").select2({
  ...
  });
});
```

**Comment by ragshion** [comment]
ooooww.... my code is directly inside <script> . now i place my code inside doc ready function.. and it's work's well.. thanks.. i'm sorry :D
