### ISSUE TITLE
Iphone 6 Plus and 6 large screens

### ISSUE THREAD

**Issue by davidbuckleyni** [ColorlibHQ/AdminLTE#2032]
I have a major issue i am using the box dialog on my forms but for some reason its not allowing the user of the iphone to scroll to right when i place a telerik grid in it it spans bigger than the box 

* @Author  Almsaeed Studio
* @Support <https://www.almsaeedstudio.com>
* @Email   <abdullah@almsaeedstudio.com>
* @version 2.4.5
This version i am using 

When I am saying box body i am using the following.

    <div class="row">
        <div class="col-md-10">

            <div class="box box-danger">
                <div class="box-header">
                    <h3 class="box-title">Product Allocation</h3>
                </div>
                <div class="box-body">
                    

But its not allowing a iphone user to scroll to the right ?

**Comment by davidbuckleyni** [comment]
I checked and slim scroll is loaded as seen that might be an issue ?

**Comment by REJack** [comment]
You want a scroll scrollbar inside the box-body?
If yes, add the `table-responsive` class to box-body.
