### ISSUE TITLE
select2 can't be clone

### ISSUE THREAD

**Issue by SushantRT** [ColorlibHQ/AdminLTE#2033]
![issue](https://user-images.githubusercontent.com/6875368/49441917-eff63500-f7ed-11e8-94d5-034f17abb24b.png)
In case of using jquery .clone() function select2 dropdown is being cloned but it's not working as a dropdown.

**Comment by REJack** [comment]
Yep a simple .clone() doesn't work, you need to destroy the select2 before cloning ` $(".className").select2("destroy");` and then render both after cloning `$(".className").select2();`
