### ISSUE TITLE
Autocomplete looks fugly

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#2034]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  latest
* Operating System:  macOs
* Browser (Version):  Chrome - latest

### Description:

Autocomplete with jQuery-ui look fugly

![screen shot 2018-12-05 at 2 56 36 am](https://user-images.githubusercontent.com/2320614/49498664-ccf17280-f839-11e8-9a24-e74e38477ae7.png)

Any ideas on how I can pretty that up with maybe just a blank white background?

**Comment by REJack** [comment]
You need to load a jquery-ui theme in your html.
