### ISSUE TITLE
Redirect to js/adminlte.min.js.map after login

### ISSUE THREAD

**Issue by bazuzu931** [ColorlibHQ/AdminLTE#2043]
hi, I use laravel 5.6 and "admin-lte": "^3.0.0-alpha.2",
when I login its redirect me to http://127.0.0.1:8000/js/adminlte.min.js.map, and admin pic with logo are not show, but rest of app is render good.
there is not problem after registration of the new user. How to fix it?

**Comment by REJack** [comment]
This sounds like a laravel related error, please ask it in the Laravel Forum or on stackoverflow.com.
