### ISSUE TITLE
AdminLTE 3

### ISSUE THREAD

**Issue by fjbardelli** [ColorlibHQ/AdminLTE#2046]
Is AdminLTE 3 stable for production?

**Comment by Reconix** [comment]
I'd probably say more so than some of the paid for solutions out there ;)

**Comment by davidov7** [comment]
wait for an update or have to find another project?

**Comment by GregJPreece** [comment]
I've done a little work with AdminLTE 3 and despite being an alpha it's surprisingly decent. Development has been stale for a while, but we did get a flurry of activity yesterday which suggests AdminLTE 3 will still make final.

**Comment by developedsoftware** [comment]
I am using the v3-dev branch - any reason why the skins are missing from dist?

**Comment by harsh85** [comment]
https://tyrosx.com/

**Comment by harsh85** [comment]
https://tyrosx.com/antarctica/
Antarctica (or the Arctic) is the southernmost continent of the Earth in which the South Pole is built. It is located in the Antarctic region of the southern hemisphere and almost entirely south of the Antarctic Circle. It is surrounded by the Southern Ocean around. With its 140 million sq km (54 million sq mi) area, followed by Asia, Africa, North America, and South America, the fifth largest continent of the Earth, 98% of Antarctica is covered with an average of 1.6 km thick ice.

**Comment by harsh85** [comment]
A simplified representation of the location of the Himalayan mountain
Himalaya “The nature of the Himalayas” = The plains of North India’s Indo-Gangetic Brahmaputra is the ground of rivers from the Himalayas. The Himalayan ranges are rain-covered in our states by creating barriers to the monsoon route. The morning when the sun rises, the sun’s rays adorn the Himalayas.
https://tyrosx.com/the-himalayas/

**Comment by REJack** [comment]
@developedsoftware AdminLTE v3 comes not with skins but you can change the Navbar, Sidebar (Light & Dark) & Brand Logo color

**Comment by bekirshala** [comment]
Hi Guys,

How to run compiler for sass in Admin LTE 3 Beta2 Edition, I need to compile scss into css.
Thanks

**Comment by REJack** [comment]
@bekirshala You need only run `npm run css` it runs the css-compile css-prefix & css-minify script, if you want to compile it in your own project I don't can give you help with that it's depending on your build system but you need to autoprefix the compiled css.

**Comment by REJack** [comment]
AdminLTE is not 100% stable for production I need to test it more, but I look forward to get it stable for production with v3.0.0-rc.2. You can see the actucal bugs in #2190

**Comment by bekirshala** [comment]
Thanks @REJack
