### ISSUE TITLE
Top-nav menu missing in mobile browser. 

### ISSUE THREAD

**Issue by ronlinet** [ColorlibHQ/AdminLTE#2048]
### Issue type:
- [x] Bug report       

### Environment:
* Operating System:  Mac OS
* Browser (Version):  Firefox Quantum

### Description
The top-nav menu is not handled in mobile browser. 
AdminLTE has already a push menu for small screens in the side-bar so switching the top-nav menu to side-bar while detecting a mobile browser may be a solution?
Once sorted out you can close the issue #1586 which is related to this problem.   

![image](https://user-images.githubusercontent.com/2538315/51059884-b6b69f00-15bb-11e9-98d4-697de0bf2921.png)

**Comment by ronlinet** [comment]
It will be about to reusing the Mobile_Detect.php from http://mobiledetect.net/ 
```
if ( $detect->isMobile() ) {
  config(['adminlte.layout' => 'top-nav']); 
}
```

**Comment by ronlinet** [comment]
Laravel package for Mobile_Detect.php https://github.com/riverskies/laravel-mobile-detect . 
Hooking the bellow snippet to page.blade.php should do the trick. 
```
@mobile 
<?config(['adminlte.layout' => null]); ?> 
@elsemobile 
<?config(['adminlte.layout' => 'top-nav']); ?> 
@endmobile
```

**Comment by REJack** [comment]
Is this Issue still open?
