### ISSUE TITLE
Vertical scrollbars flicking

### ISSUE THREAD

**Issue by vsilva472** [ColorlibHQ/AdminLTE#2050]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4.5
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)
* Machine Type: Notebook (Asus Ultrabook)
* Screen Resolution: 1366x768

### Description:
Document scrollbars flicking when the content does not generate scroll.
Only tested on Google Chrome

**Steps to Reproduce.**
* Download Admin LTE at [https://github.com/almasaeed2010/AdminLTE/archive/v2.4.5.zip](https://github.com/almasaeed2010/AdminLTE/archive/v2.4.5.zip)
* Unzip the file and open **/starter.html** with the browser (Google Chrome)

**Expected Behavior**
The page opens `without` a vertical scrollbar

**Actual Behavior**
The page opens `with` vertical scrollbars and then the scrollbars are removed like a flick effect, On slow connection this flick can be saw with more visibility

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.10)?

**Comment by vsilva472** [comment]
Yes, can reproduce this with 2.4.10 version

**Comment by REJack** [comment]
In which Browsers does it happens?

**Comment by vsilva472** [comment]
@REJack I can reproduce this in Google Chrome and Firefox 67.0
IE 11 Everything is ok... even login screen in Firefox and Chrome have a permanent vertical scrollbar and IE there is no scrollbars.

**Comment by REJack** [comment]
For login I've changed height to auto coming with the next release, you have the issue on https://adminlte.io/themes/AdminLTE/starter.html too?

**Comment by vsilva472** [comment]
Yes.. Take a look at the scrollbars in this [GIF](https://i.imgur.com/cvsbEqZ.gifv)

**Comment by REJack** [comment]
I've changed the `calc()` for .content-wrapper, you can test the master branch 😄
