### ISSUE TITLE
What is the difference 2.3.6 an latest version?

### ISSUE THREAD

**Issue by stevehomer** [ColorlibHQ/AdminLTE#2052]
Just a nudge. I can see what I have to change to migrate but I CANNOT see the difference. Without knowing the improvements (?) how can I say if worth the effort?

But overall lovely job!
ATB
Steve

**Comment by kabutotx** [comment]
[Upgrade Guid](https://adminlte.io/docs/2.4/upgrade-guide)

You can also go to the releases section and view updates, like the 2.4.0-rc. etc.
