### ISSUE TITLE
What does LTE stand for?

### ISSUE THREAD

**Issue by timoc** [ColorlibHQ/AdminLTE#2053]
### Issue type: 
- [ ] Feature request 
- [X] Bug report
- [X] Documentation

### Environment:
* AdminLTE Version:  All i could find.
* Operating System:  All.
* Browser (Version):  All.

### Description:
Brought us to a standstill with google searches trying to figure out (and agree) what LTE means. 
Is it AdminLTE or AdminLTe?, or Admin Long Term Evolution? or Laravel Template Edition?

**Comment by almasaeed2010** [comment]
haha I find this a little funny

When I started this, LTE just meant lite to me. But anyone can interpret it however they wish. There is no official meaning 🙂
