### ISSUE TITLE
Extra height added after login redirect

### ISSUE THREAD

**Issue by Algarode** [ColorlibHQ/AdminLTE#2054]
### Issue type:
- [ ] Feature request 
- [x ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.3.11
* Browser (Version):  FireFox (latest), Chrome (latest), Opera (latest), IE (11)

### Description:
I'm setting up a dashboard page using AdminLTE (2.3.11) + Angular 5. The way it's set up right now, is when you start/open the app you get to the Login screen. After that you are redirected to the dashboard. No matter whether there is content or not, the footer seems to be pushed down a bit, causing a scrollbar to show up. If I navigate to any other page, or open the Developer tools the scrollbar will disappear.

I have tried lowering the content height-wise, and tried several solutions provided here on SO such as:

$.AdminLTE.activate();
$.AdminLTE.fix();
$.AdminLTE.fixSidebar();

Any variation of those above had no effect. Setting the min-height value on the content-wrapper had no effect either.

What are other things I could try?

**Comment by REJack** [comment]
Try the latest version, I've added a calc() to .content-wrapper so you should not need the JS lines.
