### ISSUE TITLE
Support for fixed Table Header inside Scrollable box body

### ISSUE THREAD

**Issue by codekeyz** [ColorlibHQ/AdminLTE#2056]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.5
* Operating System:  Windows 10
* Browser (Version): Google Chrome

### Description:
Would you consider adding an example for fixed table headers inside scrollable box ? I tried implementing buh doesn't seem to work fine.

**Comment by REJack** [comment]
I've added this feature into v3, you can check it [here](https://adminlte.io/themes/dev/AdminLTE/pages/tables/simple.html) at the end of the page.
