### ISSUE TITLE
should i need to give attribution or any thing in my commercial project?I am working on a commercial project and using adminlte. In AdminLTE license its written that include the copyright in "all copies or substantial portions of the Software". What does it mean?

### ISSUE THREAD

**Issue by OJMALIK** [ColorlibHQ/AdminLTE#2057]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by OJMALIK** [comment]
I am working on a commercial project and using adminlte. In AdminLTE license its written that include the copyright in "all copies or substantial portions of the Software". What does it mean?

**Comment by REJack** [comment]
The License Conditions are _License and copyright notice_.
A copy of the license and copyright notice must be included with the software.
