### ISSUE TITLE
This is worked for me.. But i have another issue.. If i navigate to inside page, how can i active my sidebar-menu? Example: My treeview is Usermanagement. Treeview menu is User list.  i have one navigation on user list page like Add/Update. If i navigate to Add/update page,sidebar menu is not active. how can i solve it?  

### ISSUE THREAD

**Issue by Amusoft1** [ColorlibHQ/AdminLTE#2058]
1. nice script but it is not valid 
2. where you took the class `ul.level-1` from? 😄 AdminLTE doesn't use something like this. 

i fixed it to get it work on AdminLTE
```js
/** add active class and stay opened when selected */
var url = window.location;

// for sidebar menu entirely but not cover treeview
$('ul.sidebar-menu a').filter(function() {
	 return this.href == url;
}).parent().addClass('active');

// for treeview
$('ul.treeview-menu a').filter(function() {
	 return this.href == url;
}).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
```

i tested all variations till level 3 (all items) 😃

_Originally posted by @REJack in https://github.com/almasaeed2010/AdminLTE/issues/1482#issuecomment-300619799_

**Comment by REJack** [comment]
For this you need to create a customized script, I accomplish this with PHP in my projects not with JS.

**Comment by ilyas5** [comment]
it is not working when URL contains Query String like e.g https://github.com/ColorlibHQ/AdminLTE/issues/?id=2058

--Need help to resolve this
