### ISSUE TITLE
Modify AdminLTE 2 | Invoice Title 

### ISSUE THREAD

**Issue by MuzahidApps** [ColorlibHQ/AdminLTE#2059]
How to modify The "AdminLTE 2 | Invoice " Title on print screen.  I want to Change it to "adminLTE my order print "
Please anyone help.

**Comment by heemza** [comment]
Did you mean change page title? You can change it in title tag.
`<title>AdminLTE 2 | Invoice</title>`
in 
`<head>...</head>`

**Comment by xonexx** [comment]
I already did it. Thanks
