### ISSUE TITLE
AdminLTE is adding default boxes via div's.... why? 

### ISSUE THREAD

**Issue by RJanssen81** [ColorlibHQ/AdminLTE#2060]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.3.11
* Browser (Version):  FireFox (latest), Chrome (latest), IE (11)

### Description:
In our project we are setting up an application dashboard using AdminLTE (2.3.11) together with Angular 5. The problem that we have is when a page is loaded/rendered via browser, then some default boxes are added to the html page.  The first two div's (box box-default and box-body) are added by the template/javascript. The problem is that we don't want those boxed to be added because the interfere with the design and we don't have any influence on them. 

Code below shows what is shown in the browser (with added extra box divs)
`<div class="box box-default" ng-reflect-ng-class="[object Object]">
	<div class="box-body" ng-reflect-ng-class="[object Object]">
               <router-outlet></router-outlet><app-home _nghost-c12="">
			<div _ngcontent-c12="" class="content-wrapper" style="min-height: 853px;">
				<section _ngcontent-c12="" class="content-header">
					<div _ngcontent-c12="" class="row">
						<div _ngcontent-c12="" class="col-md-12 `clear-both">`

Code below is what we have as HTML beginning of that page 
`<div class="content-wrapper"><section class="content-header"><div class="row">
		<div class="col-md-12 clear-both">
				<div class="box box-primary">
						<div class="box-header with-border">` 

In the screenshot you will see 7 boxes (Area chart, Pending object requests.... etc.) which are intended to show up, but there is on big default box added around them.
![src](https://user-images.githubusercontent.com/7458287/52777460-2baa4800-3044-11e9-95fe-4185e3d3543d.jpg)

Any ideas why those boxes are added.... are we missing some div's? How can we solve this?

**Comment by REJack** [comment]
Is this Issue still open? 
If yes this looks like you closed your divs not correctly or you missed a closing div.
