### ISSUE TITLE
AdminLTE3 - how to fix active sidebar

### ISSUE THREAD

**Issue by jvbalcita** [ColorlibHQ/AdminLTE#2068]
### Environment:
* AdminLTE Version:  version 3 alpha 2
* Operating System:  All.
* Browser (Version):  All.

In the previous version of AdminLTE which is the Bootstrap 3 there is a fix to make the sidebar dynamically active when selected.

Here's the code used

```
$(function(){
  /** add active class and stay opened when selected */
  var url = window.location;

  // for sidebar menu entirely but not cover treeview
  $('ul.sidebar-menu a').filter(function() {
     return this.href == url;
  }).parent().addClass('active');

  // for treeview
  $('ul.treeview-menu a').filter(function() {
     return this.href == url;
  }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
  
});
```

but now in AdminLTE 3 this code is not working.
Is anyone already tried this? and produced a resolution?

Thanks in advance

**Comment by arbex10** [comment]
Hello @jvbalcita 

Can you test this, please:

/** add active class and stay opened when selected */
var url = window.location;

// for sidebar menu entirely but not cover treeview
$('ul.nav-sidebar a').filter(function() {
&nbsp;&nbsp;&nbsp;&nbsp;return this.href == url;
}).addClass('active');

// for treeview
$('ul.nav-treeview a').filter(function() {
&nbsp;&nbsp;&nbsp;&nbsp;return this.href == url;
}).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open') .prev('a').addClass('active');

**Comment by jvbalcita** [comment]
it's working @arbex10 . Thank you very much!

**Comment by cristo89** [comment]
> Hello @jvbalcita
> 
> Can you test this, please:
> 
> /** add active class and stay opened when selected */
> var url = window.location;
> 
> // for sidebar menu entirely but not cover treeview
> $('ul.nav-sidebar a').filter(function() {
>     return this.href == url;
> }).addClass('active');
> 
> // for treeview
> $('ul.nav-treeview a').filter(function() {
>     return this.href == url;
> }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open') .prev('a').addClass('active');

hey bro, this code where? iam sorry my english not good.
thanks

**Comment by cristo89** [comment]
> it's working @arbex10 . Thank you very much!

hey bro, this code ppaste where?sorry my english not good

**Comment by renzo-tarazona07** [comment]
el código va dentro de un script en el pie de pagina antes de finalizar así:
this code insert into footer page... 

<script>
    /** add active class and stay opened when selected */
    var url = window.location;

    // for sidebar menu entirely but not cover treeview
    $('ul.nav-sidebar a').filter(function() {
        return this.href == url;
    }).addClass('active');

    // for treeview
    $('ul.nav-treeview a').filter(function() {
        return this.href == url;
    }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');
</script>
</body>
</html>

**Comment by ashif9** [comment]
Thank You it worked @arbexmb

**Comment by AshrafulRasel** [comment]
@**arbexmb**  when  blog/users , this works but blog/users/3/edit this url not working for menuopen

**Comment by GersonFD** [comment]
> Hello @jvbalcita
> 
> Can you test this, please:
> 
> ```
> /** add active class and stay opened when selected */
> var url = window.location;
> 
> // for sidebar menu entirely but not cover treeview
> $('ul.nav-sidebar a').filter(function() {
>     return this.href == url;
> }).addClass('active');
> 
> // for treeview
> $('ul.nav-treeview a').filter(function() {
>     return this.href == url;
> }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');
> ```

It only works for the first element of second level, could you help me to work with the rest of levels?

**Comment by kpsanmao** [comment]
> > it's working @arbex10 . Thank you very much!
> 
> hey bro, this code ppaste where?sorry my english not good

放到基础模板或者每个页面的</body>前面。
`<script>
$(document).ready(function() {
  /** add active class and stay opened when selected */
  var url = window.location;

  // for sidebar menu entirely but not cover treeview
  $('ul.nav-sidebar a').filter(function() {
      return this.href == url;
  }).addClass('active');

  // for treeview
  $('ul.nav-treeview a').filter(function() {
      return this.href == url;
  }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');
})
</script>`

你这典型的中式英语，茫茫多的英语中一眼就能看出来是国人！

**Comment by edward221096** [comment]
I searched too many documentation but @arbexmb code is working perfectly! Thank you!!

**Comment by JuanVqz** [comment]
I'm using rails 6 with `turbolinks` and `webpacker` the code which works for me it's this.

```js
$(document).on("turbolinks:load", function() {
  var url = window.location

  $("ul.nav-sidebar a").filter(toggleNavSidebar);
  $("ul.nav-treeview a").filter(toggleNavTreeview);

  function toggleNavSidebar() {
    if (this.href != url) return

    $(this).addClass("active")
  }

  function toggleNavTreeview() {
    if (this.href != url) return

    $(this).parentsUntil(".nav-sidebar > .nav-treeview")
      .addClass("menu-open").prev("a").addClass("active");
  }
})

```

**Comment by GallitoMZ** [comment]
> @**arbexmb** when blog/users this works but blog/users/3/edit for this url not working for menuopen



encontré una solucion parecida al que han mencionado:

`
    /** add active class and stay opened when selected */
    var url = window.location;



    // for sidebar menu entirely but not cover treeview
    $('ul.nav-sidebar a').filter(function() {
        if (this.href) {
            return this.href == url || url.href.indexOf(this.href) == 0;
        }


    }).addClass('active');

    // for treeview
    $('ul.nav-treeview a').filter(function() {
        if (this.href) {
            return this.href == url || url.href.indexOf(this.href) == 0;
        }

    }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');

`

**Comment by keserwang** [comment]
> Hello @jvbalcita
> 
> Can you test this, please:
> 
> ```js
> /** add active class and stay opened when selected */
> var url = window.location;
> 
> // for sidebar menu entirely but not cover treeview
> $('ul.nav-sidebar a').filter(function() {
>     return this.href == url;
> }).addClass('active');
> 
> // for treeview
> $('ul.nav-treeview a').filter(function() {
>     return this.href == url;
> }).parentsUntil(".nav-sidebar > .nav-treeview").addClass('menu-open').prev('a').addClass('active');
> ```

This code should be placed in adminlte.js.
