### ISSUE TITLE
plugins directory removed from dist

### ISSUE THREAD

**Issue by neoacevedo** [ColorlibHQ/AdminLTE#2069]
Hi. I have updated AdminLTE to 2.4.9. In previous versions I could access the plugins because the plugins directory was downloaded on each update, but now, in the version 2.4.9 I have seen the _plugins_ directory has been dropped. I think is related to https://github.com/almasaeed2010/AdminLTE/blob/e691c465e3f4f8338336d003262283c8094ef63a/.gitattributes#L8. Same situation could be present if anyone tries to use the _pages_ assets: https://github.com/almasaeed2010/AdminLTE/blob/e691c465e3f4f8338336d003262283c8094ef63a/.gitattributes#L7

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.10)?

**Comment by REJack** [comment]
Instead of the `plugins` folder you can use the `bower_components`.
