### ISSUE TITLE
Where is the Documentation for Alpha Version?

### ISSUE THREAD

**Issue by Bawzee** [ColorlibHQ/AdminLTE#2070]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
Where is the documentation for the Alpha Version 3?  Every documentation link I could find was for a prior version.

**Comment by REJack** [comment]
I've added docs with my PR #2169, you can check it out [here](https://adminlte.io/docs/3.0/).
