### ISSUE TITLE
I can't generate PDF cakephp 3

### ISSUE THREAD

**Issue by Villo21** [ColorlibHQ/AdminLTE#2074]
Hello, before using AdminLTE, I generated PDF files with CakePDF, after installing AdminLTE, I can not render the pdf.  
I discovered the problem but I do not know how to solve it. 
In AppController.php 
`public function beforeRender(Event $event){ $this->viewBuilder()->setTheme('AdminLTE'); // Overwrite AppView class $this->viewBuilder()->setClassName('AdminLTE.AdminLTE'); }` 
Removing this line $this->viewBuilder()->setClassName('AdminLTE.AdminLTE'); , the pdf works, but AdminLTE has the default menus again.

**Comment by REJack** [comment]
This is not an AdminLTE related Issue, please ask it in the CakePHP Forum or on stackoverflow.com.

I don't work with CakePHP but I would say you need a seperate theme for Login/Register pages, I create in my CodeIgniter Projects 2 layouts (1 with Sidebar & Navbar and 1 without Sidebar & Navbar)
