### ISSUE TITLE
How much time will it take to publish stable release of Adminlte v3 ? 

### ISSUE THREAD

**Issue by takielias** [ColorlibHQ/AdminLTE#2077]
I'm waiting for the stable release of Adminlte v3. I'm really excited. How much time will it take to publish stable release?

**Comment by johnnyq** [comment]
No one knows for sure, but i'm sure its just right around the corner

**Comment by manigopal** [comment]
waiting for it #AdminLTE3

**Comment by puikinsh** [comment]
Dublicate
