### ISSUE TITLE
About V3

### ISSUE THREAD

**Issue by jyxjjj** [ColorlibHQ/AdminLTE#2078]
### Issue type:
- [x] Feature request 
- [ ] Documentation   
- [ ] Bug report       

### Environment:
* AdminLTE Version:  3.0
* Operating System:  All
* Browser (Version):  Chrome

### Description:
Searched "is:issue is:open V3" will show a lot about "when V3 release".
The same to me.
Now Bootstrap V4 is gradually replacing V3.
And I saw some like Google Material Design in AdminLTE V3.
It will be a so great template.
I even stopped all of our projects to wait V3 release.
I think many people are looking forward to its release too.
Please,Please,Please,Please,Please,Please,Please,Please,Please,Please,Please,Please,Please,Please,Please!!!!!!!!
Even it will not for free.
Very expect.

**Comment by aly14** [comment]
I am with you .

**Comment by johnnyq** [comment]
I'm there too I cant wait to see what v3 it will bring super excited!!

**Comment by MammutAlex** [comment]
I am with you .

**Comment by jfcaldeira** [comment]
Wish we could donate to make v3 release faster

**Comment by jyxjjj** [comment]
> Wish we could donate to make v3 release faster

@almasaeed2010 
Did you see this? Help!!! Maybe I should use 'SOS'?

**Comment by nuthingman** [comment]
I think the best is to start looking for other alternatives.

**Comment by ReneHetzel** [comment]
Iam still waiting for the new release too
All alternative projects are completely oversized or just bad :(

**Comment by puikinsh** [comment]
Please help us test [V3 dev branch](https://github.com/ColorlibHQ/AdminLTE/tree/v3-dev) instead of wasting time here. We feel that it is ready but since the user base is so big we don't want to release without proper testing from you.

**Comment by ReneHetzel** [comment]
OK .. i choose v3 dev

**Comment by lenamtl** [comment]
Is there any demo for v3 so we can test without installing...

**Comment by jyxjjj** [comment]
> 是否有任何v3的演示，所以我们可以测试而无需安装...

@lenamtl, Yes, I've saw it at https://adminlte.io/themes/dev/AdminLTE/index.html

**Comment by REJack** [comment]
https://adminlte.io/themes/dev/AdminLTE/index.html is not updated!

I've created a subdomain on my space with the latest v3-dev, feel free to use this http://adminlte-dev.rejack.space/.

**Comment by REJack** [comment]
AdminLTE is not 100% stable for production I need to test it more, but I look forward to get it stable for production with v3.0.0-rc.2. You can see the actucal bugs and find a demo/docs link in #2190
