### ISSUE TITLE
it's not working after published on iis

### ISSUE THREAD

**Issue by aly14** [ColorlibHQ/AdminLTE#2079]
everything is working in visual studio but , not working after published IIS , the error like below

Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:1455/Content/adminlte/css/?v=FzFgJ0aRhezrmNVwo8c-OXoHu8UcywCkPuM-Twfet2s1".

**Comment by adamkenway007** [comment]
hello sir,could you post image / upload on hosting? i can't see error..

**Comment by aly14** [comment]
[http://artibilisim.com/docs/screen.png](url)

**Comment by jfcaldeira** [comment]
have you tried clearing cache?

**Comment by judero01col** [comment]
The same thing happens to me, can someone solve this error?

**Comment by REJack** [comment]
Is this Issue still open?
