### ISSUE TITLE
AdminLTE-v3 Close first treeview if second treeview clicked

### ISSUE THREAD

**Issue by adamkenway007** [ColorlibHQ/AdminLTE#2080]
### Environment:
* AdminLTE Version:  AdminLTE v3.0.0-beta.
* Operating System: All OS
* Browser (Version):  Any Browser
### Description:
as default adminlte3-dev make treeview always open when clicked and close if clicked again at same place but my problem it's my first treeview won't close if i click at another treeview

i wish i can make it same as default feature adminlte2 which will work on adminlte3
sorry for my bad english

**Comment by jfcaldeira** [comment]
You will probably have to write your own jquery function to do that work

**Comment by REJack** [comment]
You only need to add or change the `data-accordion` to `true` beside `data-widget="treeview"` like 
``` html
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
...
</ul>
```
