### ISSUE TITLE
Form - Not adjustable when load data

### ISSUE THREAD

**Issue by phietzindo** [ColorlibHQ/AdminLTE#2083]
Can anyone help me about adjusting the form :
![WhatsApp Image 2019-03-24 at 23 58 18](https://user-images.githubusercontent.com/10143630/54882877-2afda080-4e91-11e9-8739-8dfa7a010616.jpeg)
If there is no data called from the controller or pure input data (rm number, name, address, date of birth, postcode), then the display on the form will be fine. 
![2019-03-25_0-12-54](https://user-images.githubusercontent.com/10143630/54882993-d9eeac00-4e92-11e9-9116-906474f693e2.png)

But when calling data from the controller (the city contains a list of cities, the province contains a list of provinces) then it looks imperfect.
![2019-03-25_0-13-17](https://user-images.githubusercontent.com/10143630/54882995-dd823300-4e92-11e9-8637-370ef94a7259.png)

Is there anything I have to do to make it look better? thanks.

**Comment by REJack** [comment]
Your code structure is not correct, if you don't want them side by side remove the classes from label like this
```
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
```
