### ISSUE TITLE
the exports button on datatable not showing

### ISSUE THREAD

**Issue by aly14** [ColorlibHQ/AdminLTE#2085]
the exports button on datatable not showing ?

**Comment by lenamtl** [comment]
Using chrome right click inspect, check for JS errors.
Make sure you have all Datatables plugins link url for the plugins

**Comment by REJack** [comment]
Please provide a code example or a demo

**Comment by REJack** [comment]
AdminLTE v2 doesn't deliver any DataTables plugins, you need to download and setup it.

**Comment by vanlalruata** [comment]
Hi All,

I am using AdminLTE v3.0.4, I am trying to include the export buttons. But with no success. I am getting an error like

DataTables warning: table id=**datalist**- Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

*datalist is the id of my table.

Does anyone have a solution with this?

**Comment by REJack** [comment]
@vanlalruata  Ask please questions like the at the datatables forum.

**Comment by lenamtl** [comment]
Datatables forum https://datatables.net/forums/

**Comment by BinMamun** [comment]
> s anyone have a sol

Add this line 
"Dom": 'Bfrtip',

$("#exampleTable").DataTable({
    "Dom": 'Bfrtip',
    "responsive": true,
    "lengthChange": true,
    "autoWidth": true,
    "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
}).buttons().container().appendTo('#exampleTable_wrapper .col-md-6:eq(0)');

I believe the code above will fix your problem. and don't forget to add necessary scripts link in your html page
