### ISSUE TITLE
Bug: wrong event name in adminlte.js

### ISSUE THREAD

**Issue by HugoBossOD** [ColorlibHQ/AdminLTE#2088]
Bug: 
"expandingEvent is not defined" message in console, when collapsing ".box"

Solution:
Wrong event name in adminlte.js (Line 244) "expandingEvent" - change to collapsingEvent

**Comment by westinyang** [comment]
补充，在adminlte.js中搜索'expandingEvent '，找到后替换为'c'，'c'变量等同于非压缩版中的'collapsingEvent'

**Comment by yuvrajsab** [comment]
In adminlte.min.js, find "expandingEvent" replace it with "c" and it should work fine.

**Comment by kuba1999** [comment]
`  BoxWidget.prototype.collapse = function () {
    var collapsedEvent = $.Event(Event.collapsed);
    var collapsingEvent = $.Event(Event.collapsing);
    var expandingEvent = $.Event(Event.expanding); //add
    var collapseIcon   = this.options.collapseIcon;
    var expandIcon     = this.options.expandIcon;`

**Comment by REJack** [comment]
Is this Issue still open with the latest Version (v2.4.10)?

**Comment by trimmell** [comment]
sesms like this issue is still open in the latest version 2.4.10. i was able to fix the erorr by replacing "expandingEvent" with "c" as described above. please merge this fix into master!

**Comment by REJack** [comment]
Fix is already merged, release comes this weekend.
