### ISSUE TITLE
Can update v3 from npm?

### ISSUE THREAD

**Issue by DanielAccorsi** [ColorlibHQ/AdminLTE#2092]
Hi. I saw that version 3 had updates, but when checking with 'npm outdated', it detects downgrade:

**Current:**
3.0.0-alpha.2
**Wanted:**
3.0.0-alpha.2
**Latest:**
2.4.10

How to upgrade to the latest version?

**Comment by jfcaldeira** [comment]
Probably best to just download from github and use the required files since it's still in alpha

**Comment by Darshan197** [comment]
Try This Command

npm install admin-lte@v3.0.0-alpha.2 --save

**Comment by REJack** [comment]
AdminLTE v3.0.0-beta.1 is released on GitHub, NPM & Packagist too.

You can use now `npm i admin-lte@v3.0.0-beta.1`.

P.S. `npm outdated` ignores alpha's, beta's & rc's.
