### ISSUE TITLE
Sidebar menu with sub menus - cannot expand to access sub-menus

### ISSUE THREAD

**Issue by distributev** [ColorlibHQ/AdminLTE#2094]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.10 with Angular 7
* Operating System:  Windows 10
* Browser (Version):  Recent Chrome (Electron)

### Description:

The same issue was reported many times with the sidebar menu not expanding when clicked to access the sub-menus => can not access the sub-menus. I tried without success all things suggested here - https://github.com/ColorlibHQ/AdminLTE/issues/1666 and here https://github.com/ColorlibHQ/AdminLTE/issues/1570

What was tried

1. Loading Admin LTE globally in the angular.json under the scripts section like this
```
"scripts": [
              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/bootstrap/dist/js/bootstrap.min.js",
              "./node_modules/admin-lte/dist/js/adminlte.min.js"
]
```
In the html I have ```<ul class="sidebar-menu" data-widget="tree">```

When I try to execute 
```
 $(document).ready(() => {
      const trees: any = $('[data-widget="tree"]');
      if (trees) {
        trees.tree();
      }
    });
```
I get the error .tree() function was not found. The user @thiagoreis got the same error here https://github.com/ColorlibHQ/AdminLTE/issues/1570. Later @thiagoreis suggested a solution which without success (I tried but I get the same error).

2. I removed adminlte.min.js from angular.json scripts and tried to load using ```import 'admin-lte'``` (did not work) and then I tried also ```require ('admin-lte')``` - did not work either I always get the same error  .tree() function was not found

![image](https://user-images.githubusercontent.com/19224635/55939607-78725f80-5c3e-11e9-9545-ee276cc2d7f3.png)

**Comment by REJack** [comment]
This looks like a Angular related error and it is similar to #1570 maybe it can helps you.

**Comment by dlmvikas** [comment]
Exactly the same issue I am also facing with AdminLte 2.4.15 and Angular 7. No related github posts helped either.

**Comment by JorgelGtzGtz** [comment]
hello @dlmvikas  you found the solution ?

**Comment by dlmvikas** [comment]
@JorgelGtzGtz No I didn't found any solution. What i did to solve it is rather than displaying the admin page after login success(which was not working), first I removed login page from home component and shifted the whole admin part to home component and inside that admin component I called login component. On application initialization admin part works but if we try to load it through javascript then it doesn't works. I'm new to angular, so this was the only solution for me which worked.

**Comment by magicdict** [comment]
> In case anyone is struggling with this, this thread was really helpful: (https://stackoverflow.com/questions/45512475/angular4-cant-find-jquery-ui-functions) -- look for the answer of Chris and after applying it, follow the code:
> 
> ```
> $(document).ready(() => {
>       const trees: any = $('[data-widget="tree"]');
>       if (trees) {
>         trees.tree();
>       }
>     });
> ```
> 
> on the ngOnInit of your component

Great!!!!!!  It really works!!!!!
