### ISSUE TITLE
Ajax version?

### ISSUE THREAD

**Issue by rfossella** [ColorlibHQ/AdminLTE#2099]
Hi.  Was trying to find an AJAX version of 2.4x.  Is there a link or GitHib someone can point me to?

Much appreciated!

**Comment by rfossella** [comment]
Is this still an active board?

**Comment by REJack** [comment]
You can use the [box refresh function](https://adminlte.io/docs/2.4/js-box-refresh)

**Comment by rfossella** [comment]
Quick question - the box refresh function appears to be for single "boxed" elements within the site.  I was trying to track down an AJAX version for the entire site - i.e. instead of an entire reload on each menu click.  Any guidance for that?   Thanks!

**Comment by dacoto** [comment]
If you want it with Jquery I recommend: https://github.com/defunkt/jquery-pjax, although it is a little old, it works, if you are looking for something more modern I recommend you use vue and vue-router.

**Comment by danny007in** [comment]
I think so the issue is outdated in the world of ReactJS, VueJS, AngularJs etc.
@rfossella  this is all Ajaxified framework u can use it.
