### ISSUE TITLE
treeview-menu clicked, then it is collapsed, while mainsidebar hover is also triggered

### ISSUE THREAD

**Issue by phoenix-yassin** [ColorlibHQ/AdminLTE#2100]
status: sidebar was fixed and collapsed;

operation:  click the treeview-menu,  then it is collapsed, while mainsidebar hover is also triggered, so the mainsidebar is collapsed too.  one chick, triggers treeview-menu and mainsiderbar.

**Comment by REJack** [comment]
Which version of AdminLTE you use?

**Comment by CoderSquirrel** [comment]
it may be related to #1854 ?

**Comment by REJack** [comment]
I close this issue due no response from issue author.
