### ISSUE TITLE
Update Bootstrap to 4.3.1

### ISSUE THREAD

**Issue by johnnyq** [ColorlibHQ/AdminLTE#2101]
### Issue type:
Update Asset

### Environment:
* AdminLTE Version:  3.0 Alpha 2

### Description:

Update Bootstrap Asset to the latest 4.3.1

**Comment by REJack** [comment]
Bootstrap 4 is updated to 4.3.1 with 91533abab12b76ffbfd7051e90ae6eccb6a0fea8
