### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by IneniousDeveloper** [ColorlibHQ/AdminLTE#2102]
tooltips color not showing, When append span by JavaScript
![tooltips](https://user-images.githubusercontent.com/50582693/57622880-2cec0200-75ac-11e9-9b66-2cfd953af8a7.png)
And its working properly add tooltip by html
![tooltips1](https://user-images.githubusercontent.com/50582693/57622945-50af4800-75ac-11e9-902c-cbb5ba655fb4.png)
Here is my code
![tooltips2](https://user-images.githubusercontent.com/50582693/57622961-59a01980-75ac-11e9-9fa1-1dd9f90a785c.PNG)

**Comment by IneniousDeveloper** [comment]
Please help me!

**Comment by REJack** [comment]
You need to init the tooltip after adding it with javascript with`$('[data-toggle="tooltip"]').tooltip();`

**Comment by CoderSquirrel** [comment]
@REJack du you thing it would be a 'fix' for this kind of problems and the box colappsing problem, when late render, to add jquery arrive for the components intialization?

**Comment by REJack** [comment]
@CoderSquirrel If you add content like @IneniousDeveloper posted yes, it always depends on the content if you add a complete box you may need to init the boxWidget after inserting.

**Comment by CoderSquirrel** [comment]
ops i maybe not be clear sorry.

i mean about [this](https://github.com/ColorlibHQ/AdminLTE/issues/1822#issuecomment-404761829)  and #1857 the use of jquery arruve ti add boxWidget

**Comment by REJack** [comment]
Arrive is not needed to init boxWidget after inserting via ajax, this line should be enough after your insert `$('.content-wrapper .box').boxWidget();`.
