### ISSUE TITLE
Modal V3

### ISSUE THREAD

**Issue by Dasc3er** [ColorlibHQ/AdminLTE#2103]
### Issue type:
- [x] Bug report    

### Environment:
* AdminLTE Version:  v3.0.0-alpha2
* Operating System:  Windows
* Browser (Version):  Firefox

### Description:
Opening a modal inside v3 (alpha 2) causes the sidebar to be visible on top of the modal, particularly with small screens.

Steps:
 - Create a page with the main sidebar
 - Open a bootstrap modal
 - Resize the window to check the behavior

![example](https://user-images.githubusercontent.com/15911489/57939880-1bdb1380-7880-11e9-8cec-53410b7315b7.png)

The issue is caused by the following z-index, which is higher than bootstrap's modal (1050):
https://github.com/ColorlibHQ/AdminLTE/blob/7e4417d7599c57f1a65fbdaa859c07ef0210ea79/build/scss/_variables.scss#L141

**Comment by REJack** [comment]
This Issue is fixed with #2106, you can close it 😄

**Comment by Dasc3er** [comment]
Thanks!
