### ISSUE TITLE
Disable loading bar at the top of the screen on adminLTE v2

### ISSUE THREAD

**Issue by windy569** [ColorlibHQ/AdminLTE#2104]
### Issue type:
- [ ] Feature request 
- [#] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4.2  
* Operating System: Windows 10 
* Browser (Version): Chrome (Latest)  

### Description:
Hi bro, I still can't figure out how to disable the loading bar that shows up at the top of the page on every page change for this version?
Thanks before
![Screenshot1](https://user-images.githubusercontent.com/28553376/57964315-83b35c00-795d-11e9-9a80-ca1eee6fbf5d.jpg)

**Comment by REJack** [comment]
Remove the pace css and js from your html

**Comment by windy569** [comment]
> Remove the pace css and js from your html

Hi @REJack , thanks a lot man you saving a lot of coffee for me.
