### ISSUE TITLE
ChartJS scaling issues with maximize button of browser

### ISSUE THREAD

**Issue by hipy** [ColorlibHQ/AdminLTE#2107]
### Issue type:
-  Bug report       

### Environment:
* AdminLTE Version:  2
* Operating System:  Linux/Windows
* Browser (Version):  Chrome (Latest)/Firefox (Latest)
* URL: [https://adminlte.io/themes/AdminLTE/pages/charts/chartjs.html](url)

### Description:
Hello,

There seems to be a bug with resizing a window with ChartJS. Dynamically resizing a window results in no issues with resizing the charts.

When you however press the resize button of the browser, the chart does not scale at all. The text becomes blurry and only resizing the site by hand or refreshing solves it. When you zoom back out again the charts have the wrong height until you refresh the page.

Anyone know a solution for this or a possible workaround? The options 'maintainAspectRatio' and 'responsive' were both tested with true and false but this had no effect on the bug.

Step 1: maximized browser: press maximize button to resize to last known size(in this case as small as possible)
![chartjs1](https://user-images.githubusercontent.com/1358013/58115470-6bac3880-7bfa-11e9-9d7b-2995488ecc77.PNG)
This results in blurry text and a weird stretched chart.

Step 2: maximize browser
![chartjs2](https://user-images.githubusercontent.com/1358013/58115490-7666cd80-7bfa-11e9-85c3-92c7e61398f8.PNG)
This results in the charts having the wrong height

**Comment by REJack** [comment]
There are two ways to get it work:
1. Update Chart.js to a newer version (e.g. v2.8)
2. Add a workaround css style (not perfect and need optimations)
Example for areaChart, remove the inline style from the div and add these css lines.  
```
    #areaChart {
      height: 180px;
      max-height: 180px;
    }

    @media (min-width: 768px) {
      #areaChart {
        height: 200px;
        max-height: 200px;
      }      
    }
    @media (min-width: 992px) {
      #areaChart {
        height: 250px;
        max-height: 250px;
      }      
    }
```

**Comment by REJack** [comment]
That's a bug related to the ChartJS version used inside AdminLTE, you can get rid of this bug with updating ChartJS
