### ISSUE TITLE
Sidebar collapse not working on smaller screens

### ISSUE THREAD

**Issue by Lennylendog** [ColorlibHQ/AdminLTE#2109]
Please see below screenshot,

I can't seem to think why this is happening

![image](https://user-images.githubusercontent.com/50716844/58437656-d231ca80-80c2-11e9-90d3-4a28112b7f47.png)

Btw before anyone says anything the copyright for the AdminLTD is on the footer too on the right side. 👍

**Comment by REJack** [comment]
Could you provide your code from the sidebar or the whole page 😄, it looks like you missed a closing div or something like this.

**Comment by Lennylendog** [comment]
`
  <aside class="main-sidebar">
    
    <section class="sidebar">
      
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo GetUserProfileImage($_SESSION["DCRP_AccountID"]); ?>" class="img-circle" alt="User Image">
        </div>
        <?php
        if(GetSupporterLevel() >= 1)
        {
          $rankName = GetSupporterRankName(GetSupporterLevel());
        }
        if(GetAdminLevel() >= 1)
        {
          $rankName = GetAdminRankName(GetAdminLevel());
        }
        ?>
        <div class="pull-left info">
          <p><?php echo GetUserName($_SESSION["DCRP_AccountID"]); ?></p>
          <small><?php echo $rankName; ?></small>
        </div>
      </div>

      
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">NAVIGATION</li>
        <li><a href="?page=home"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
          <li class="treeview">
            <a href="#">
              <i class="fa fa-fw fa-cog"></i> <span>Settings</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="?page=edit-profile-image"><i class="fa fa-portrait"></i> Edit Profile Image</a></li>
            </ul>
          </li>
        <?php
        if(GetAdminLevel() >= 1 || GetSupporterLevel() >= 1)
        {
          echo '<li class="treeview">
            <a href="#">
              <i class="fa fa-fw fa-life-ring"></i> <span class="menu-title">Community Supporter</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="?page=application-management"><i class="fa fa-scroll"></i> Application Management</a></li>
              <li><a href="?page=check-bans"><i class="fa fa-search"></i> Check Bans</a></li>
            </ul>
          </li>';
        }
        if(GetAdminLevel() >= 1)
        {
          echo '<li class="treeview">
            <a href="#">
              <i class="fa fa-fw fa-gavel"></i> <span class="menu-title">Administrator</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-ban"></i> Ban Management</a></li>
              <li><a href="#"><i class="fa fa-scroll"></i> Admin Records</a></li>
              <li><a href="#"><i class="fa fa-scroll"></i> Admin Notes</a></li>
              <li><a href="#"><i class="fa fa-circle-o"></i> Admin Jail</a></li>
              <li><a href="#"><i class="fa fa-clipboard-list"></i> Server Logs</a></li>
            </ul>
          </li>';
        }
        if(GetAdminLevel() >= 4)
        {
            echo '<li class="treeview">
            <a href="#">
              <i class="fa fa-fw fa-university"></i> <span class="menu-title">Lead Administrator</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-newspaper"></i> Site News Management</a></li>
              <li><a href="#"><i class="fa fa-bullhorn"></i> In-Game Announcement</a></li>
            </ul>
          </li>';
        }
        if(GetAdminLevel() >= 5)
        {
            echo '<li class="treeview">
            <a href="#">
              <i class="fa fa-fw fa-crown"></i> <span class="menu-title">Community Manager</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-lock"></i> Password Management</a></li>
              <li><a href="#"><i class="fa fa-user-secret"></i> Secret Word Management</a></li>
              <li><a href="#"><i class="fa fa-clipboard-list"></i> Server Logs</a></li>
            </ul>
          </li>';
        }
        if(GetAdminLevel() >= 5 || isDeveloper() >= 1)
        {
            echo '<li class="treeview">
            <a href="#">
              <i class="fa fa-fw fa-code"></i> <span class="menu-title">Community Developer</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-cog"></i> Site Change Logs</a></li>
              <li><a href="#"><i class="fa fa-clipboard-list"></i> Main Site Management</a></li>
              <li><a href="#"><i class="fa fa-bullhorn"></i> Main Site Announcement</a></li>
            </ul>
          </li>';
        }
        ?>
      </ul>
    </section>
    
  </aside>`

Sidebar code

**Comment by Lennylendog** [comment]
Fixed
