### ISSUE TITLE
Fixed Header Navbar

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2112]
Currently I'm testing version 3 . Is this is suitable for real world project and also I'm trying to achieve fix layout for header. I can't figure out that how to achieve this. If any one achieve this please help me.
And I I found a bug in side navbar. 
When i expand nav after scrolling it little bit, It automatically scroll at top. Please help me to figure out this.

**Comment by REJack** [comment]
I work at the moment on a real layout fixed and layout notfixed for AdminLTE v3 I'll push soon my changes then you can test it again, the scroll at top bug is also fixed.

**Comment by saileshkush95** [comment]
Please push scroll at top bug fixed as soon as possible. I'll manage fixed layout for my project.

**Comment by REJack** [comment]
This issue is done with #2119, you can test it on https://adminlte-dev.rejack.space/pages/layout/fixed-topnav.html you can also look over https://adminlte-dev.rejack.space/index2.html it combines layout-fixed layout-navbar-fixed & layout-footer-fixed
