### ISSUE TITLE
AdminLTE 3 wrong content-wraper min-height calculation

### ISSUE THREAD

**Issue by fvromera** [ColorlibHQ/AdminLTE#2113]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0-alpha.2 
* Operating System: Fedora 30 
* Browser (Version): Firefox 67.0  

### Description:
I detect a little bug in content-wraper min-height calculation, and that's is because of line 232 of adminlte.js are currently:

`$(Selector.CONTENT).css('min-height', max - heights.header);`

And it should be:

`$(Selector.CONTENT).css('min-height', max - heights.header - heights.footer);`

To take in account the footer height, if not, footer is under window height and causes scroll.

**Comment by REJack** [comment]
This issue is fixed with #2119, you can test it on https://adminlte-dev.rejack.space/
