### ISSUE TITLE
Navigation can't scroll sometime

### ISSUE THREAD

**Issue by yangtuhua** [ColorlibHQ/AdminLTE#2116]
![image](https://user-images.githubusercontent.com/14036085/58742881-39040a80-845a-11e9-81f3-c746d55e571e.png)

**Comment by yangtuhua** [comment]
Thank you for opening up your masterpiece.

I just meet some problem when I use them, could you please give me a hand?

issues as below:

I can't scroll down the menu, when I expand one of them, and they are out of the browser, and I can't reach them. Could you please tell me how I can solve it, thanks.

**Comment by REJack** [comment]
Please provide a code example
