### ISSUE TITLE
I can't add zero before the hour in format 24

### ISSUE THREAD

**Issue by YesIdDotNet** [ColorlibHQ/AdminLTE#2117]
In timepicker (AdminLTE v2), I can't add zero before the hour in format 24. 

I tried using `timeFormat: 'HH: mm',` and `format: 'HH: mm',` without success.

`$(function () {
	$('.timepicker').timepicker({
		showMeridian: false,
		showInputs: false,
		defaultTime: false,
		minuteStep: 30,
		format: 'HH:mm' //Not work
	})
})`

How can I do it?

![timepicker](https://user-images.githubusercontent.com/51274352/58753469-3074f980-8485-11e9-9dac-1a9720054b33.jpg)

**Comment by REJack** [comment]
Thats not possible with `bootstrap-timepicker`, there is no option for this.

You can replace timepicker with [datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker).
