### ISSUE TITLE
Box widget bugfix should be released ASAP.

### ISSUE THREAD

**Issue by hirayama-onagigawa-computing** [ColorlibHQ/AdminLTE#2118]
Box widget collapsing bug fixed by 998a1ff4be94959fc2223991bfdfbb007515b52c and 17f46f4eca45ee3738ebf039cad6618ca3e407f2 is **FATAL**.
It should be released ASAP.

**Comment by REJack** [comment]
I'll release a new version (v2.4.11) this weekend, I look over the v2 issues if there are any little bug too to fix.

**Comment by hirayama-onagigawa-computing** [comment]
Thanks!

**Comment by REJack** [comment]
I'll close this Issue 😄
