### ISSUE TITLE
Sidebar can't collapse

### ISSUE THREAD

**Issue by vrabe** [ColorlibHQ/AdminLTE#2121]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0-beta.1
* Operating System: Linux
* Browser (Version): Firefox (Latest) and Chrome (Latest)

### Description:
Sidebar can't collapse or open by clicking the button (`data-widget="pushmenu"`) after commit 9c640e0f6ff7bb4018f6462ca1e33727881120c9.

**Comment by REJack** [comment]
Thanks for reporting, I've found the bug and push the fix soon also with other enhancements 😄

**Comment by REJack** [comment]
This issue is fixed with #2123, you can test it on https://adminlte-dev.rejack.space.
