### ISSUE TITLE
2.4.8 version getting from NPM

### ISSUE THREAD

**Issue by coolsamk7** [ColorlibHQ/AdminLTE#2124]
When we command "npm install admin-lte@latest" it gives us 2.4.8 instead of 2.4.10. Please resolve.

**Comment by REJack** [comment]
I can not reproduce this, my results

```bash
Raphaels-MBP:ColorlibHQ rejack$ npm i admin-lte@latest
npm WARN deprecated jvectormap@1.2.2: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
npm WARN saveError ENOENT: no such file or directory, open '/Users/rejack/Projekte/GitHub/ColorlibHQ/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/rejack/Projekte/GitHub/ColorlibHQ/package.json'
npm WARN ColorlibHQ No description
npm WARN ColorlibHQ No repository field.
npm WARN ColorlibHQ No README data
npm WARN ColorlibHQ No license field.

+ admin-lte@2.4.11
added 173 packages from 154 contributors and audited 1884 packages in 14.38s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Raphaels-MBP:ColorlibHQ rejack$ 
```

**Comment by coolsamk7** [comment]
@REJack Thank you for you response,
Please see the two scree shot below.
Actually I am trying to get the admin-lte version 2.4.10 but actually I'm getting 2.4.8
![Screen Shot 2019-06-12 at 12 28 58 PM](https://user-images.githubusercontent.com/17364368/59330368-e4d91000-8d0e-11e9-9368-cf1ffbd0a2d4.png)
**In above screenshot I'm install rpm version 2.4.10**
![Screen Shot 2019-06-12 at 12 29 23 PM](https://user-images.githubusercontent.com/17364368/59330422-0e923700-8d0f-11e9-8b76-5996f1918126.png)
Actually Im getting this one 2.4.8

**Comment by REJack** [comment]
Oh now I understand, the JS files was not regenerated before publishing 🤦‍♂, sadly it's not possible to overwrite the old releases but I recreated the files in the latest versions (v2.4.11 & v2.4.12).

**Comment by coolsamk7** [comment]
Thank you @REJack , 
My issue is solved now, it was in collapse the box.

**Comment by rcqcxy** [comment]
> Oh now I understand, the JS files was not regenerated before publishing 🤦‍♂, sadly it's not possible to overwrite the old releases but I recreated the files in the latest versions (v2.4.11 & v2.4.12).




Thank you very much. It helped me a lot.
