### ISSUE TITLE
2.4.11 - strange navigation menu behavior + dark space on reloads

### ISSUE THREAD

**Issue by toxpal** [ColorlibHQ/AdminLTE#2126]
Upgraded to 2.4.11 several minutes ago and noticed 2 strange things (never happened with previous releases):

1. Navigation menu is not smooth anymore. Now, if I have one of menus opened (so other menus are closed) and click on closed menu to open it, currently opened menu just collapses instantly, which looks bad. It was collapsing slowly and smoothly in previous builds. Don't know how to  explain it better, but if you play with live demo, you will notice how bad and unnatural collapsing looks now.

2. All the pages that don't take 100% (or more) of screen's height now display dark space at the bottom during reloads. It only happens for a second or so, but it's really annoying. To see what I mean go to any small page (like https://adminlte.io/themes/AdminLTE/pages/examples/pace.html) and use forced reload (usually CTRL + F5). When page reloads, you will notice it displays dark color (the same one used by menu) in almost whole page, which only disappears after page is fully loaded.

**Comment by REJack** [comment]
I've fixed both issues, you can test it on the offical demo page.

**Comment by toxpal** [comment]
Thank you, that was fast!

**Comment by REJack** [comment]
No problem 😄
