### ISSUE TITLE
Treeview not working

### ISSUE THREAD

**Issue by Sharlaan** [ColorlibHQ/AdminLTE#2127]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [x] Documentation   

### Environment:
* AdminLTE Version:  2.4.12
* JQuery: 3.4.1
* Bootstrap: 3.4.1
* Vue: 2.6.10
* Operating System:  Windows10Pro
* Browser (Version):  Chrome (Latest)

### Description:
Context: i need a 2-levels deep collapsible treeview, in a VueJS based project.
i saw admin-lte documentation already provide one, so using the data api version i litteraly copy pasted the demo, expecting it to work out of the box.

Result: i only get a mere ul list without any formatting applied and more importantly lvl1 anchors not responsive to click (ie not collapsing children)
[CodeSandBox](https://codesandbox.io/embed/vue-template-ti7lr?fontsize=14)

no error in console.

What am i missing ? (might as well update the demo to make sure it works ?)

Note: Hopefully, i'm trying to avoid using JQuery, it is only in project because my client imposed AdminLTE which requires it.

**Comment by REJack** [comment]
Look over this [CodeSandBox fork](https://codesandbox.io/s/vue-template-s0xkh?fontsize=14)
