### ISSUE TITLE
Sidebar Expand on Hover Auto On

### ISSUE THREAD

**Issue by DevkanKafkas** [ColorlibHQ/AdminLTE#2129]
### Environment:
* AdminLTE Version:  AdminLTE 2.4.12
* Operating System:  Win7
* Browser (Version):  Chrome (Latest)

`<body class="hold-transition skin-blue sidebar-mini sidebar-collapse **fixed**">`

Adding "Fixed" to Body automatically open Sidebar Expand on Hover Active

Whats Is Fixed

**Comment by REJack** [comment]
In AdminLTE v2 the `fixed` class gives you the ability for a fixed header and sidebar.
