### ISSUE TITLE
Indent child menu items (v3)

### ISSUE THREAD

**Issue by jrandhawa09** [ColorlibHQ/AdminLTE#2130]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3 
* Operating System:  Windows 10
* Browser (Version):  Chrome 75

### Description:

For the side bar, when a main menu item is expanded, how can any child menu items be indented to the right? e.g. when I click on Charts, I would like ChartJS, Flot and Inline child items to be indented to the right slightly. 

![image](https://user-images.githubusercontent.com/20520383/59468509-24e0e580-8e2a-11e9-99eb-0ff841a3fbf7.png)

For users this make it more obvious the items and in a child/sub menu of the main menu item.

**Comment by JNPSoftware** [comment]
You can use this:
`<style type="text/css">
.treeview-menu>li>a>.glyphicon, .treeview-menu>li>a>.fas { margin-left: 15px; }
</style>`
For glyphicon and FontAwesome5 .fas, but you can increment more options.

**Comment by REJack** [comment]
Good idea I'll add this to beta.1 later.

**Comment by REJack** [comment]
I've added it, you can add now `.nav-child-indent` to `ul.nav-sidebar`.
