### ISSUE TITLE
Doesn't auto close expand expanded menu in sidebar

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2131]
Every things working fine. But missing one features which is available in v2 i.e auto close expanded menu when ever click on other menu item in sidebar.

**Comment by REJack** [comment]
Is this issue related to AdminLTE v2 or v3?

**Comment by saileshkush95** [comment]
This issue is related is in v3

**Comment by REJack** [comment]
Check out this https://github.com/ColorlibHQ/AdminLTE/issues/2025#issuecomment-494730304
