### ISSUE TITLE
custom-switch-on-* doesn't work

### ISSUE THREAD

**Issue by iaguas** [ColorlibHQ/AdminLTE#2135]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-beta.1
* Operating System:  OSX
* Browser (Version):  Safari and Chrome (lastest both)

### Description:
I'm using the custom switch added in beta version. I've realized that after the commit d852f4ba34f9865fc8d2616bba7496f48c167cb1, instead of having a widget all green, it is only green in the circle part. Here images of both situations:

**Before** the commit d852f4ba34f9865fc8d2616bba7496f48c167cb1:
![before](https://user-images.githubusercontent.com/4259550/59640662-0bf46f00-915f-11e9-9e47-d7c9c8775b17.png)

**After** the commit d852f4ba34f9865fc8d2616bba7496f48c167cb1:
![after](https://user-images.githubusercontent.com/4259550/59640664-0eef5f80-915f-11e9-84ac-121e0f147a8d.png)

I'm not sure which change in that commit makes the problem for that widget, but I will be so grateful if someone can give an idea.

**Comment by REJack** [comment]
Thanks for reporting this issue, I see what you mean with activating gradients the background changes instead of background-color 🤦‍♂ I'll fix it soon before releasing beta.1

**Comment by REJack** [comment]
I've fixed this issue, check the demo again
