### ISSUE TITLE
Indent child menu items in sub menus (v3) 

### ISSUE THREAD

**Issue by jrandhawa09** [ColorlibHQ/AdminLTE#2136]
### Issue type:
- [x] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3 (beta 1) 
* Operating System: Windows 10 
* Browser (Version): Chrome 75 

### Description:

Hi 

This is related to feature request #2130 which was added to Beta 1. Thanks very much for that.

How can I get items in sub-menus to also be indented? 

![SubItems](https://user-images.githubusercontent.com/20520383/59754062-49e7b500-927d-11e9-80a1-fd0a685027e2.jpg)

Thanks

**Comment by REJack** [comment]
Oh damn i missed the upper levels, I'll add a fix to indent them too.

**Comment by REJack** [comment]
Can you provide me the html as code example?

**Comment by jrandhawa09** [comment]
Hi

 

Below is the test menu I was using (have also attached the test file). Perhaps I’m doing it incorrectly?

 

Under Menu 2 there is a Sub Menu 2. Within Sub Menu 2 there is another Sub Menu 3 (should look like the attached image)

 

      

        <nav class="mt-2">

          <ul class="nav nav-pills nav-sidebar nav-child-indent flex-column" data-widget="treeview" role="menu" data-accordion="false">

            

            <li class="nav-item has-treeview">

              <a href="#" class="nav-link">

                <i class="nav-icon fas fa-copy"></i>

                <p>

                  Menu 1

                  <i class="fas fa-angle-left right"></i>

                  <span class="badge badge-info right">6</span>

                </p>

              </a>

              <ul class="nav nav-treeview">

                <li class="nav-item has-treeview">

                  <a href="#" class="nav-link">

                    <i class="nav-icon fa fa-table"></i>

                    <p>

                      Sub-Menu 1

                      <i class="fas fa-angle-left right"></i>

                      <span class="badge badge-info right">6</span>

                    </p>

                  </a>

                  <ul class="nav nav-treeview">

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 1</p>

                      </a>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 2</p>

                      </a>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 3</p>

                      </a>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 4</p>

                      </a>

                    </li>

                  </ul>

                </li>

                <li class="nav-item">

                  <a href="#" class="nav-link">

                    <i class="far fa-circle nav-icon"></i>

                    <p>Item 1</p>

                  </a>

                </li>

                <li class="nav-item">

                  <a href="#" class="nav-link">

                    <i class="far fa-circle nav-icon"></i>

                    <p>Item 1</p>

                  </a>

                </li>

                <li class="nav-item">

                  <a href="#" class="nav-link">

                    <i class="far fa-circle nav-icon"></i>

                    <p>Item 1</p>

                  </a>

                </li>

              </ul>

            </li>

            <li class="nav-item has-treeview">

              <a href="#" class="nav-link">

                <i class="nav-icon fas fa-copy"></i>

                <p>

                  Menu 2

                  <i class="fas fa-angle-left right"></i>

                  <span class="badge badge-info right">6</span>

                </p>

              </a>

              <ul class="nav nav-treeview">

                <li class="nav-item has-treeview">

                  <a href="#" class="nav-link">

                    <i class="nav-icon fa fa-table"></i>

                    <p>

                      Sub-Menu 2

                      <i class="fas fa-angle-left right"></i>

                      <span class="badge badge-info right">6</span>

                    </p>

                  </a>

                  <ul class="nav nav-treeview">

                    <li class="nav-item has-treeview">

                      <a href="#" class="nav-link">

                        <i class="nav-icon fa fa-table"></i>

                        <p>

                          Sub-Menu 3

                          <i class="fas fa-angle-left right"></i>

                          <span class="badge badge-info right">6</span>

                        </p>

                      </a>

                      <ul class="nav nav-treeview">

                        <li class="nav-item">

                          <a href="#" class="nav-link">

                            <i class="far fa-circle nav-icon"></i>

                            <p>Sub-Item A</p>

                          </a>

                        </li>

                        <li class="nav-item">

                          <a href="#" class="nav-link">

                            <i class="far fa-circle nav-icon"></i>

                            <p>Sub-Item B</p>

                          </a>

                        </li>

                        <li class="nav-item">

                          <a href="#" class="nav-link">

                            <i class="far fa-circle nav-icon"></i>

                            <p>Sub-Item C</p>

                          </a>

                        </li>

                        <li class="nav-item">

                          <a href="#" class="nav-link">

                            <i class="far fa-circle nav-icon"></i>

                            <p>Sub-Item D</p>

                          </a>

                        </li>

                      </ul>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 1</p>

                      </a>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 2</p>

                      </a>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 3</p>

                      </a>

                    </li>

                    <li class="nav-item">

                      <a href="#" class="nav-link">

                        <i class="far fa-circle nav-icon"></i>

                        <p>Sub-Item 5</p>

                      </a>

                    </li>

                  </ul>

                </li>

                <li class="nav-item">

                  <a href="#" class="nav-link">

                    <i class="far fa-circle nav-icon"></i>

                    <p>Item 1</p>

                  </a>

                </li>

                <li class="nav-item">

                  <a href="#" class="nav-link">

                    <i class="far fa-circle nav-icon"></i>

                    <p>Item 1</p>

                  </a>

                </li>

                <li class="nav-item">

                  <a href="#" class="nav-link">

                    <i class="far fa-circle nav-icon"></i>

                    <p>Item 1</p>

                  </a>

                </li>

              </ul>

            </li>

          </ul>

        </nav>

        

 

 

Thanks

 

Jas

**Comment by REJack** [comment]
Nice, I'll look over it this weekend.

**Comment by REJack** [comment]
I've added a fix for this, update your files to latest v3-dev commit ;)

**Comment by FlavioSuarez** [comment]
Hi,

As can be seen on the online demo page (v3.1.0), this bug is still there...
![Multilevel_bug](https://user-images.githubusercontent.com/12549794/124336773-b6d4fb80-db75-11eb-8e9a-6c890302f6b8.png)

**Comment by REJack** [comment]
You need to add a custom class to indent the childs, that's no bug!

**Comment by FlavioSuarez** [comment]
Ah, ok... 
It would be great to have this custom class on these demo pages... Just my 0.02...

Thanks for your reply!
BTW, keep the great work with AdminLTE... I love it!
