### ISSUE TITLE
Unable to click on hamburger button

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2137]
### Environment:
* AdminLTE Version:  V3
* Operating System: Linux
* Browser (Version): Google Chrome

### Description:
Once I collapsed sidebar I can't able to click. This issue is related to dashboard 2
https://adminlte.io/themes/dev/AdminLTE/index2.html
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28560875/59853912-8e647500-9391-11e9-8d71-962384f8eb59.gif)

**Comment by REJack** [comment]
I've fixed this issue, check the demo again 😄

**Comment by saileshkush95** [comment]
Thanks for your works,
