### ISSUE TITLE
How To Install Version 3.0.0-beta.1 by npm ?

### ISSUE THREAD

**Issue by Darshan197** [ColorlibHQ/AdminLTE#2138]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [x] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by REJack** [comment]
AdminLTE v3.0.0-beta.1 is not released yet, I‘ll create the release next week and also publish it on npm & packagist.

**Comment by Darshan197** [comment]
Thanks For Attention...
