### ISSUE TITLE
Feature: Loading Overlay for SmallBox

### ISSUE THREAD

**Issue by Zanoshky** [ColorlibHQ/AdminLTE#2139]
### Issue type:
- [ x ] Feature request

### Environment:
* AdminLTE Version:  3.0

### Description:
Please create an animated overlay for SmallBox like for the Cards.

That would be a great asset!

Thank you for such an amazing project.

**Comment by REJack** [comment]
Done 😄, check it [here](https://adminlte.io/themes/dev/AdminLTE/pages/widgets.html)

**Comment by Zanoshky** [comment]
Thank you so much @REJack !!

You are an amazing developer and real inspiration. Thank you for being so dedicated to the community!
