### ISSUE TITLE
Fixed Layout for Dragable event 

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2146]
### Issue type:
- [ ] Feature request => Fixed Layout for Draggable Events
- [ ] Bug report    => Unable to edit or delete event name once added

### Environment:
* AdminLTE Version:  Version3 beta 1
* Operating System: Kde neon
* Browser (Version):  Latest Chrome, Firefox

### Description:
Is there any simple step to fix layout for drag-able event list like shown in below image.
![Screenshot_20190629_115626](https://user-images.githubusercontent.com/28560875/60380781-c5f6af80-9a6a-11e9-8d09-ce0fdbd8cd45.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28560875/60384061-23095a00-9a99-11e9-8fa0-e4c687352434.gif)

**Comment by REJack** [comment]
1. Fixed Layout for Draggable Events
I need to check up the code, if it is possible to change this easily.

2. Unable to edit or delete event name once added
The Fullcalendar demo inside AdminLTE's demo is not a complete demo, it's only as demonstration for fullcalendar.

**Comment by REJack** [comment]
@saileshkush95 Can you provide me the code from the second gif (sticky mailbox)?

**Comment by saileshkush95** [comment]
Sorry for that , I just apply some style property in browser, like position fixed for left div and use some margin for right div. You used flex property so, I know this is not the actual way to do this. Here I'm just try to visualise for better understanding.

**Comment by REJack** [comment]
Ok 😄 I‘ll look later over it, may I can achieve this with the col offset and position sticky feature from Bootstrap 4.

**Comment by REJack** [comment]
I've found the bug why sticky-top not worked and changed the calendar demo to test the sticky-top feature, I'll merge my PR soon.

**Comment by saileshkush95** [comment]
Once again thanks.
