### ISSUE TITLE
BUG: Small Box values do not scale

### ISSUE THREAD

**Issue by Zanoshky** [ColorlibHQ/AdminLTE#2147]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  Admin LTE 3 
* Operating System:  Any
* Browser (Version):  Chrome Latest / Firefox Latest

### Description:

For the Small Box and info box -  text and values do not scale depending on the col-size.

![image](https://user-images.githubusercontent.com/8194241/60381159-7e632a00-9a50-11e9-951c-199c87b91346.png)

**Comment by REJack** [comment]
Thanks for reporting this bug, I'll add a fix for this in the next days.
