### ISSUE TITLE
wysihtml5 editor is missing

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2148]
### Issue type:
- [ ] Bug report      => wysihtml5 editor folder is missing from plugins folder

### Environment:
* AdminLTE Version:  V3 beta 1
* Operating System:  Kde Neon (Linux)
* Browser (Version):  Latest Chrome

Thanks for your amazing works, 
I'm trying to implement this dashboard with Django , Every things working fine.
but one thing is not working properly ie wysihtml5 editor in compose mailbox page.
After scratching my head, I figure out that, file related to wysihtml5 editor is missing from plugins folder. Once again thanks for your amazing works

**Comment by REJack** [comment]
In AdminLTE v3 bootstrap-wysihtml5 is replaced with summernote (due no support for BS4), I'll replace wysihtml5 code with Summernote.

**Comment by saileshkush95** [comment]
Thanks for your quick reply

**Comment by REJack** [comment]
I've replaced bootstrap-wysihtml5 with summernote, you can checkout the v3-dev branch.
