### ISSUE TITLE
Disable toggle when clicking on the body

### ISSUE THREAD

**Issue by jitan16** [ColorlibHQ/AdminLTE#2150]
How can I disable the toggle when clicking on the body on the mobile screen?  

I just want to use the toggle when the icon clicked. 

http://prntscr.com/o8wz13

**Comment by REJack** [comment]
Toggle for the sidebar? 

There is no toggle when clicking on the body, I don't know what you mean :/

**Comment by jitan16** [comment]
1. First the sidebar is opened 
http://prntscr.com/o8x934
2. Clicked on the body part or content. The sidebar closed. 
http://prntscr.com/o8xaip

**Comment by jitan16** [comment]
It always triggers the close toggle on the top
http://prntscr.com/o8xbv5

**Comment by REJack** [comment]
Which version of AdminLTE you use, v2.3.x or v2.4.x?

**Comment by jitan16** [comment]
AdminLTE 2.3

**Comment by REJack** [comment]
You need to change the `screenSizes.sm` to 320 or 0 through [AdminLTE Options](https://adminlte.io/themes/AdminLTE/documentation/index.html#adminlte-options).

**Comment by jitan16** [comment]
Thanks for the help @REJack. It works!
