### ISSUE TITLE
Feature: Language selection in navbar

### ISSUE THREAD

**Issue by Zanoshky** [ColorlibHQ/AdminLTE#2156]
### Issue type:
- [x] Feature request

### Description:
![image](https://user-images.githubusercontent.com/8194241/60925709-bb2aee80-a2a4-11e9-92e5-7eb0fe9dc94e.png)

Something similar or nicer...?

**Comment by REJack** [comment]
That’s a nice idea, I‘ll add a language dropdown in v3 demo.

**Comment by saileshkush95** [comment]
I thinks this is necessary features

**Comment by saileshkush95** [comment]
Does this is implement??

**Comment by REJack** [comment]
Yep checkout [this demo](https://adminlte.io/themes/dev/AdminLTE/pages/examples/language-menu.html)
