### ISSUE TITLE
Managing roles/permissions to restrict access [Documentation]

### ISSUE THREAD

**Issue by DCAR1** [ColorlibHQ/AdminLTE#2157]
Hi everybody,

An AdminLTE portal has been implemented in my company and a user asked me to create an other "admin" user named "su" for example. I created it but I could not manage role/permission on it to restrict access (see attached printscreen).

I created permissions with the name of the section/under-section but it does not work.

Is it possible to have support for it or to send me a link to do this?
Do I have to adapt code? Or is it only a setting to create/adapt in the database?

I really thank you in advance for your support.

Best regards,
David

![image](https://user-images.githubusercontent.com/52709627/60945322-8726ec00-a2eb-11e9-9d6a-0a3a0ea75472.png)

**Comment by REJack** [comment]
AdminLTE is only a HTML/CSS Theme based on Bootstrap. Is this a real WebApp based on PHP, ASP.net or something similar?

I guess you use something like Laravel-AdminLTE.

**Comment by DCAR1** [comment]
It's a WebApp based on ASP.net.

Thank you!

**Comment by REJack** [comment]
I doesn't use ASP.net, you need a authentication system with role based authorization, but may these two links helps you.

https://jasonwatmore.com/post/2018/06/26/aspnet-core-21-simple-api-for-authentication-registration-and-user-management
https://jasonwatmore.com/post/2019/01/08/aspnet-core-22-role-based-authorization-tutorial-with-example-api

**Comment by saileshkush95** [comment]
I thinks you should close this issue because this issue is not related to this project.
