### ISSUE TITLE
Logo in side menu when minimised

### ISSUE THREAD

**Issue by jrandhawa09** [ColorlibHQ/AdminLTE#2159]
### Issue type:
- [X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3 Beta 2 
* Operating System:  Windows 10 
* Browser (Version):  Chrome 75 

### Description:

If a add a company logo to the side bar/menu as below

![image](https://user-images.githubusercontent.com/20520383/61050712-90918080-a3df-11e9-84c5-76c5136cbaae.png)

how can I display a different (smaller) logo when the side menu is minimised (rather than cropped version of larger logo)

![image](https://user-images.githubusercontent.com/20520383/61050783-adc64f00-a3df-11e9-87e9-b63cee10e16a.png)

Also, if I hover over the side menu, it would be nice if the larger logo would then show and the smaller one when minimised again.

Thanks

**Comment by REJack** [comment]
I've added a way to handle this easily 😄 comes with v3.0.0-beta.2.

You need only this brank-link/logo markup
```html
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link logo-switch">
      <img src="dist/img/logo-xs.png" alt="AdminLTE Logo" class="brand-image-xs logo-xs">
      <img src="dist/img/logo-xl.png" alt="AdminLTE Logo" class="brand-image-xl logo-xl">
    </a>
```
results
![sidebar logo demo](https://user-images.githubusercontent.com/1554582/61124509-5ee3ec80-a4a7-11e9-8dea-37fdb9a68927.png)
