### ISSUE TITLE
Feature: Fixed header on desktop, while not fixed on mobile

### ISSUE THREAD

**Issue by Zanoshky** [ColorlibHQ/AdminLTE#2162]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
Hello,

Could you please make additional settings for fixed header and fixed footer?

I would love to see the following options:
1) While on desktop - header is fixed, but the mobile header is not fixed
2) While on desktop - header is not fixed, but the mobile header is fixed

Same possible settings for the footer.

I think this can be achieved in css with 
**@media (min-width: xxx px) setting.**

Please, I would really need to have fixed footer on desktop (bottom of page) while it is not nice on mobile (small screen).

Kind regards,
Z

**Comment by REJack** [comment]
For AdminLTE v3?

**Comment by Zanoshky** [comment]
yes

**Comment by REJack** [comment]
Ok I‘ll add it before releasing v3.0.0-beta.2

**Comment by REJack** [comment]
Responsive fixed header/footer done 😃 you can test it in my PR.

You can now add classes to the body like this `layout-footer-fixed layout-md-footer-not-fixed layout-lg-footer-fixed`, this enables fixed footer on for xs, sm, lg & xl and disables fixed footer only on md.
