### ISSUE TITLE
webpack + 3.0.0-beta.2

### ISSUE THREAD

**Issue by alexdresko** [ColorlibHQ/AdminLTE#2163]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-beta.2
* Operating System:  Windows 10
* Browser (Version):  Chrome latest

### Description:
When 3.0.0-beta.1 is installed, everything builds fine. When 3.0.0-beta.2 is installed, I get this error:

```
ERROR in ./src/base/base.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "mailbox";
^
      File to import not found or unreadable: mailbox.
      in C:\code\stark\SOLO\src\Stark.Solo.Web\node_modules\admin-lte\build\scss\AdminLTE-raw.scss (line 51, column 1)
 @ ./src/base/base.html
 @ ./src/base/base.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper
```

And it's true... mailbox.scss is not in that directory. Not sure what the difference is between beta 1 and beta 2.

**Comment by REJack** [comment]
Oh, I’ve moved mailbox and other page related scss files to a seperate folder also with plugin scss files, but I doesn’t updated the AdminLTE-raw.scss file.

 I’ll update it tomorrow.

**Comment by alexdresko** [comment]
Wow! Thanks for the quick update! I've been trying to figure this out for a few hours now.. :)

**Comment by REJack** [comment]
I've updated AdminLTE-raw.scss in my PR, I'll merge it tomorrow then it should work again.

**Comment by alexdresko** [comment]
That did the trick, thank you!
