### ISSUE TITLE
humburger menu is not working properly in dashboard 2

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2166]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version: latest v3
* Operating System:  Linux
* Browser (Version):  Latest Chrome

### Description:
Unable to toggle humberger menu in dashbaord 2
![ezgif com-gif-maker](https://user-images.githubusercontent.com/28560875/61183910-03f8f380-a667-11e9-8b3b-ed8f6335c619.gif)

**Comment by REJack** [comment]
I've found the bug too, while working on the docs, you can check out my new PR draft :smile:
