### ISSUE TITLE
Sidebar color after pressed

### ISSUE THREAD

**Issue by HELkashef90** [ColorlibHQ/AdminLTE#2176]
Hello,
I want to change (**red**) color that appears after pressing at any options in the left sidebar.
thanks.

![image](https://user-images.githubusercontent.com/42306744/61355265-493e4080-a874-11e9-975f-fe539e864410.png)

**Comment by REJack** [comment]
I've added this for debbuging purposes and released it 🤦‍♂ , please update to the latest version (v2.4.15).

**Comment by HELkashef90** [comment]
Thanks for your help, much appreciated.
