### ISSUE TITLE
Some forms are missing for selecting multiple items.

### ISSUE THREAD

**Issue by sandeep787898** [ColorlibHQ/AdminLTE#2177]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:   Latest V3
* Operating System:  Linux
* Browser (Version):  Latest Chrome

### Description:
First of all thanks for this awesome project. This templates contains all the basis element for developing Admin Panel. But still some features are missing. For example, forms like below.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53010130/61385382-0743e780-a8d2-11e9-8080-63efdabd3663.gif)

This helps to select multiple item in more interactive way

**Comment by REJack** [comment]
That's a great idea, which dual listbox plugin is in the gif?

**Comment by sandeep787898** [comment]
It's default django admin panel.

**Comment by saileshkush95** [comment]
I thinks this one is good because it support bootstrap4.
[jQuery Dual Select Boxes](https://www.jqueryscript.net/demo/Responsive-jQuery-Dual-Select-Boxes-For-Bootstrap-Bootstrap-Dual-Listbox/)

**Comment by REJack** [comment]
I’ve found this one, https://github.com/istvan-ujjmeszaros/bootstrap-duallistbox also with BS4 support and it’s available via npm.

**Comment by saileshkush95** [comment]
This one is also awesome please include it,  as soon as possible

**Comment by REJack** [comment]
Ok sweet, I’ll add it tomorrow in my PR then you can test it.

**Comment by saileshkush95** [comment]
You are awesome.

**Comment by REJack** [comment]
I've added bootstrap-duallistbox as plugin and created a demo in forms/advanced, you can check it out in my PR #2169.

**Comment by REJack** [comment]
This issue is merged with my PR #2169
