### ISSUE TITLE
jvectormap is not maintened !!!

### ISSUE THREAD

**Issue by ldynia** [ColorlibHQ/AdminLTE#2179]
Looks like **jvectormap** is no longer in maintened! What can be confirmed here https://www.npmjs.com/package/jvectormap and here  https://yarnpkg.com/en/package/jvectormap

Can you please remove not supported dependencies ?

# Yarn
```bash
$ yarn add admin-lte@2.4.15
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
warning admin-lte > jvectormap@1.2.2: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
error Couldn't find the binary git

info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command
```

# Npm
```bash
$ npm install admin-lte@2.4.15
npm WARN deprecated jvectormap@1.2.2: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/morrisjs/morris.js.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2019-07-19T13_25_43_096Z-debug.log
```

**Comment by mymaizi** [comment]
npm install admin-lte@3.0.0-beta.1
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/CivilError/jqvmap.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by REJack** [comment]
@ldynia I doesn't like this error too, but I don't want to remove this because it could break installs by AdminLTE users.

@mymaizi I've fixed this error already in my PR, it will released in v3.0.0-beta.2.

**Comment by mymaizi** [comment]
@REJack Thank you very much for your reply. Does v3.0.0-beta.2 have a specific release time?

**Comment by REJack** [comment]
@mymaizi I look forward to release it this weekend.

**Comment by ldynia** [comment]
Thanks guys for the feedback. I could not install the package because I did not have **git** installed. As strange as it sounds some packages in **npm** (including `jvectormap`) require git to be installed. So if you develop your application using **docker** especially **alpine** images then, prior to running `yarn add` or `npm install` **make sure that git is installed!** 
* Alpine -`apk add git` 
* Debian - `apt install git`
* CentOS - `yum install git`

P.S. At the end of the day the error was there: **Couldn't find the binary git**
