### ISSUE TITLE
Tabbed html form with a common div

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2181]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
It would be nice if we have also a form like sharing common div.
Refrence:-
https://stackoverflow.com/questions/9551625/how-to-create-a-tabbed-html-form-with-a-common-div
Completed Example:-
https://jsfiddle.net/5S7ea/

**Comment by REJack** [comment]
That's a nice idea, I will add a "custom tab content"-class to add additional content above/below the tab-pane's.

Keep in mind you can use any content in tab-pane's.

**Comment by REJack** [comment]
I've added custom tab content class & demo at pages/UI/navbar in my PR #2169
