### ISSUE TITLE
border radius on input-group-text class

### ISSUE THREAD

**Issue by SmileYzn** [ColorlibHQ/AdminLTE#2182]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  v3 beta 2
* Operating System:  Win 8.1
* Browser (Version):  Firefox (Latest) 

### Description:

There is a (very small heheh) mistake with input-group-text class, i think we can remove border radius to fix it. Also try to fix the shadow of focus on these inputs to glow too. 

I'm not a pro in github or these things related to template, so sorry for any mistake on bug report.

Here is a screenshots:

1. Without fix: https://i.imgur.com/j3VeI6p.png
2. Fixed: https://i.imgur.com/ZwgvPdu.png

3. Border focus: https://i.imgur.com/GAJbSGo.png

For a better web! Thanks again

**Comment by REJack** [comment]
Thanks for the bug report, it's perfect 😄.

I've found the bugs both are related to the html markup, I'll fix it soon in my PR.

It's this
```html
<div class="input-group mb-3">
    <input type="email" class="form-control" placeholder="Email">
    <div class="input-group-append input-group-text">
        <span class="fas fa-envelope"></span>
    </div>
</div>
```
instead of 
```html
<div class="input-group mb-3">
    <input type="email" class="form-control" placeholder="Email">
    <div class="input-group-append">
        <div class="input-group-text">
            <span class="fas fa-envelope"></span>
        </div>
    </div>
</div>
```

**Comment by SmileYzn** [comment]
Also it is possible to reduce the shadow in focused controls for adminlte?
Is a bit default from bootstrap, make it like adminlte v2.

Thanks

**Comment by REJack** [comment]
> Also it is possible to reduce the shadow in focused controls for adminlte?
> Is a bit default from bootstrap, make it like adminlte v2.

That's a good idea I'm also doesn't like the box-shadow's in bootstrap and it's more similar to v2, I'll look over it in the next days

**Comment by REJack** [comment]
I've fixed the markup in demo & removed the box-shadow from the inputs, it's added in my PR #2169.

**Comment by SmileYzn** [comment]
Thanks
