### ISSUE TITLE
Please add Gallery Page

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2186]
### Issue type:
- [ ] Bug report       
- [x] Feature request 
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
Almost every admin panel contains gallery page. 
So please add galley page also.
Some plugins that I like.
https://www.jqueryscript.net/gallery/jQuery-Plugin-For-Impressive-Galleries-With-CSS-Effects-Filterizr.html

https://www.jqueryscript.net/gallery/Gallery-Popup-With-jQuery-LC-Lightbox.html

**Comment by REJack** [comment]
Nice idea, I will check out the plugins and create a demo within the next release (v3.0.0-rc.1)

**Comment by REJack** [comment]
I've added a gallery demo with FilterizR in my PR #2220 😄

**Comment by saileshkush95** [comment]
Wow, First of all thanks for your works.  But filterizr plugin is missing image preview features

**Comment by REJack** [comment]
I know, I'm looking for an dependency less lightbox, but I doesn’t found one I‘ll look tomorrow again for a nice lightbox then I’ll update the gallery demo.

**Comment by saileshkush95** [comment]
Thanks

**Comment by REJack** [comment]
I've added ekko-lightbox for now & updated the gallery demo in my PR

**Comment by saileshkush95** [comment]
Wow its awesome
