### ISSUE TITLE
User menu should be right side of the main header

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2191]
### Issue type:
- [ ] Feature
- [ ] Suggestion

### Environment:
* AdminLTE Version:  3.0
* Operating System:  Window 10
* Browser (Version):  Firefox(Latest) 

### Description:

Since version 2 , there has `user-menu` under `main-header` and this is very useful to add dropdown links such as **profile** , **Sign Out** , **settings**. I hope this will be re-added.

**Comment by REJack** [comment]
This menu is already built-in, you can check it [out here](https://adminlte.io/themes/dev/AdminLTE/pages/examples/legacy-user-menu.html).  I’ve added it not to all demo pages.
