### ISSUE TITLE
AdminLTE 3 beta 2 Fontawesome not shown

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2193]
Thank You for developing to next version
I was download ver. 3 beta 2, when I running in my local machine fontawesome not shown.

OS: windows 10

**Comment by SmileYzn** [comment]
Try to check network tab and see what is wrong when try to load fa icons, also repply here with more information from that.

Ps. It is running fine here

**Comment by REJack** [comment]
@AdeSupriyadi On which browser you face this problem?

**Comment by AdeSupriyadi** [comment]
On Chrome was shown,
On Firefox not shown

**Comment by REJack** [comment]
Ok you face the same problem that I faced too, Firefox restricted cross-origin resource sharing from file:// it need http:// or https:// due new policy changes, you need to bypass this with change `security.fileuri.strict_origin_policy` to `false` in about:config.

**Comment by AdeSupriyadi** [comment]
where in firefox to change security.fileuri.strict_origin_policy?

**Comment by REJack** [comment]
On `about:config`-page you need to add this in the address bar, there you can search for `security.fileuri.strict_origin_policy`.

**Comment by REJack** [comment]
If this little workaround helped fixed the problem, please close the issue 😄 .
