### ISSUE TITLE
Starte page not loading over localhost

### ISSUE THREAD

**Issue by f86597** [ColorlibHQ/AdminLTE#2194]
### Issue type:

- [ ] Bug report     starter page is not loading over localhost when i copied it from orignal to a new folder along with all dependencies.  but after viewing page source and clicking on the link of css file it loaded in browser.
and when i open starter page through file explorer its working fine but not on localhost.

### Environment:
* AdminLTE Version:  2.4
* Operating System:  Windows 10 (Latest version)
* Browser (Version):  Firefox latest version

**Comment by REJack** [comment]
Please check your console for errors, I guess you have a problem with your assets placing or a apache/nginx config bug on your localhost like missing mime types.

**Comment by f86597** [comment]
all style-sheets ans js files are blocked by adblocker plus extension.

**Comment by REJack** [comment]
Check your adblocker filter may you have an entry to block localhost files.

**Comment by REJack** [comment]
Closing Issue due inactivity
