### ISSUE TITLE
Can not select child option.

### ISSUE THREAD

**Issue by dodacvan** [ColorlibHQ/AdminLTE#2196]
Here is my code
`const theData = [{
            'id': '',
            'text': ''
        },
            {
                'text': 'Group 1',
                'children': [{
                    'id': 1,
                    'text': 'Option 1.1'
                },
                    {
                        'id': 2,
                        'text': 'Option 1.2'
                    }
                ]
            },
            {
                'text': 'Group 2',
                'children': [{
                    'id': 3,
                    'text': 'Subgroup 2.1',
                    'children': [{
                        'id': 41,
                        'text': 'Option 2.1.1'
                    },
                        {
                            'id': 42,
                            'text': 'Option 2.1.2'
                        }
                    ]
                },
                    {
                        'id': 4,
                        'text': 'Subgroup 2.2',
                        'children': [{
                            'id': 41,
                            'text': 'Subgroup 2.2.1',
                            'children': [{
                                'id': 41,
                                'text': 'Option 2.2.1.1'
                            }]
                        },
                            {
                                'id': 42,
                                'text': 'Subgroup 2.2.2',
                                'children': [{
                                    'id': 41,
                                    'text': 'Option 2.2.2.1'
                                },
                                    {
                                        'id': 42,
                                        'text': 'Option 2.2.2.2'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ];`
        
`$('#mySelect').select2({
            placeholder: 'Select a option...',
            data: theData
        });`

![Screenshot_1](https://user-images.githubusercontent.com/12047875/62687528-275a5880-b9f1-11e9-8f12-85aaaa5b2449.png)

**Comment by REJack** [comment]
That's a error according to select2 and this is not supported.
> Because Select2 generates an <optgroup> when creating nested options, only a single level of nesting is supported. Any additional levels of nesting is not guaranteed to be displayed properly across all browsers and devices.

[Source](https://select2.org/data-sources/formats#grouped-data)
