### ISSUE TITLE
AdminLTE 3 beta 2 - bug dropdown and google chrome

### ISSUE THREAD

**Issue by tiagomv94** [ColorlibHQ/AdminLTE#2202]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  AdminLTE v3.0.0-beta.2 
* Operating System:  Windows 10
* Browser (Version):  Google Chrome 76.0.3809.100

### Description:

I have a problem with google chrome and dropdowns, the options box doesn't have the correct borders.

this happens when I place the dropdown inside a bootstrap class like `<div class="col-md-3">`

**bug example:**
![dropdown_bad](https://user-images.githubusercontent.com/24566218/62840386-660a4000-bc89-11e9-9d77-eba1d78b6790.png)

**correct way (from adminlte 3 demo):**
![dropdown_correct](https://user-images.githubusercontent.com/24566218/62840392-833f0e80-bc89-11e9-83ed-63caf017f11c.png)

**the code (dropdown between line 610 and 622)**
[http://s000.tinyupload.com/?file_id=90241532223052944951](url)

**Comment by REJack** [comment]
I can't replicate this issue with the latest chrome (76.0.3809.132), do you use a beta version?
