### ISSUE TITLE
Tree-menu go wrong when you click the menu quickly in short time

### ISSUE THREAD

**Issue by songyuantai** [ColorlibHQ/AdminLTE#2204]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  2.4.15
* Operating System:  Windows7
* Browser (Version):   Chrome (v76.0.3809.100) 

### Description:
i meet this problem on the version 2.4.10 first time, then i upgrade to version 2.4.15 but the problem still exsits.
![QQ截图20190812153108](https://user-images.githubusercontent.com/12009645/62850911-11150b00-bd17-11e9-8c8e-097f0461c9d8.png)
![QQ截图20190812153223](https://user-images.githubusercontent.com/12009645/62850919-14a89200-bd17-11e9-83aa-6f43fb85f937.png)

**Comment by REJack** [comment]
Which version of jQuery you have loaded in your template? I can't reproduce this with jQuery 3.4.1.

**Comment by songyuantai** [comment]
yes，i don‘t find this issue in your exsample.but i shall used the same version jquery. those day my harddisk broken, i would debug it carefully today. then give you answer

**Comment by songyuantai** [comment]
i create a repo [test repo](https://github.com/songyuantai/Adminlte_Tests) to test the problem. clone the repo, you can click tree-menu randomly donzens of times to reproduce the bug. i found it seems relate to 'fixed' class in 'body' tag. 
![QQ截图20190816164348](https://user-images.githubusercontent.com/12009645/63155435-1fc82e80-c045-11e9-815f-31edbb88ecd3.png)

**Comment by REJack** [comment]
I use currently macOS and can't reproduce this bug, but I'll test this in the next days on Windows.

I've added a fix to avoid producing a queue of slide animations, this could fix the issue here too.
