### ISSUE TITLE
Card-outline inside card wrong styling

### ISSUE THREAD

**Issue by Dasc3er** [ColorlibHQ/AdminLTE#2205]
### Issue type:
- [x] Bug report   

### Environment:
* AdminLTE Version:  v3 beta 2
* Operating System:  Windows
* Browser (Version):  Firefox (Latest) and Chrome (Latest)

### Description:
When creating a card outlined inside another a normal card, if the parent doesn't have the _card-outline_ class the child is redered wrong.

Example: _card-outline_ inside _card_ [wrong]
```html
<div class="card card-info">
	<div class="card-header">
		<h3 class="card-title">Outside</h3>
	</div>

	<div class="card-body">

		Test

		<div class="card card-outline card-success">
			<div class="card-header">
				<h3 class="card-title">Inside outline</h3>
			</div>
			<div class="card-body">
				Test 2
			</div>
		</div>
	</div>
</div>
```
![screen1](https://user-images.githubusercontent.com/15911489/62880919-d6b76800-bd2e-11e9-8060-d33e87a29350.png)

Example: _card_ inside _card-outline_ [right]
```html
<div class="card card-outline card-info">
	<div class="card-header">
		<h3 class="card-title">Outside</h3>
	</div>

	<div class="card-body">

		Test

		<div class="card card-success">
			<div class="card-header">
				<h3 class="card-title">Inside outline</h3>
			</div>
			<div class="card-body">
				Test 2
			</div>
		</div>
	</div>
</div>
```
![screen2](https://user-images.githubusercontent.com/15911489/62881004-07979d00-bd2f-11e9-9329-ce2f4a43de91.png)

**Comment by REJack** [comment]
PR #2220 is merged

**Comment by Dasc3er** [comment]
@REJack The problem was not solved.
I think the follwing styling is the cause: `.card-primary:not(.card-outline) .card-header`, which should be `.card-primary:not(.card-outline).card-header`. The same is applied with allo card types.

**Comment by REJack** [comment]
@Dasc3er That's exactly what I've done, look [here](https://github.com/ColorlibHQ/AdminLTE/pull/2220/files?file-filters%5B%5D=.scss#diff-a4f78eae315c1fdf80f024e2a64e554fR10)

**Comment by Dasc3er** [comment]
From v3.0.1: https://github.com/ColorlibHQ/AdminLTE/blob/5988c4f9dbed5f12c314620f1273359cffd7b887/dist/css/adminlte.css#L15657
Looking right now on the master version, the problem is solved: https://github.com/ColorlibHQ/AdminLTE/blob/478cfc17431cb84e2f85805374d5cc2938bdb342/dist/css/adminlte.css#L15842
So v3.0.2 will actually solve it, I believe.

**Comment by REJack** [comment]
🤦‍♂ oh dang may I missed to recompile it correct before releasing it, correct v3.0.2 should fix it.
