### ISSUE TITLE
Dropdown menu on Top Navigation

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2206]
### Issue type:
- [ ] Feature request

### Environment:
* AdminLTE Version:  3.0
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:
I have already seen the thread [top navigation multilevel menu](https://github.com/ColorlibHQ/AdminLTE/issues/1504). Can you please add an exmple at **Top Navigation** layout page ?

**Comment by julienmru** [comment]
Ideally I'd love a multi-level top navigation dropdown too, optionally opened on hover instead of click.

**Comment by REJack** [comment]
I've added dropdown menu with submenus in the top nav example, also I created a `.dropdown-hover` class to open the menus with hovering 😄 This is added in my PR #2220

**Comment by julienmru** [comment]
@REJack Thanks! I pulled the latest changes from your repo and I do see the the dropdown menu however in Chrome and Safari nothing happens when I hover "Hover for action" submenu.
Also on which element should I add the `dropdown-hover` class?

**Comment by REJack** [comment]
The "Hover for action" submenu is miss-titled right now 🤦‍♂ but I'll add there the `dropdown-hover` class.
You can set the `dropdown-hover` class beside this classes:
- `.dropdown` (to use hover for the whole dropdown menu)
- `.dropdown-menu` (to use hover on a specific menu item & sub menus)
- `.dropdown-submenu` (to use hover on a specific sub menu item & sub sub menus)

It only work not on split buttons right now.

**Comment by REJack** [comment]
PR #2220 is merged
