### ISSUE TITLE
AdminLTE 2.4.16 cannot be installed

### ISSUE THREAD

**Issue by prsolucoes** [ColorlibHQ/AdminLTE#2208]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.16
* Operating System:  macos
* Browser (Version):  Chrome (Latest)

### Description:

Im trying use version 2.4.16 of AdminLTE, but receive this message:

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/admin-lte 2.4.16 exists as bower-asset/admin-lte[v3.0.0-beta.2, v3.0.0-beta.1, v3.0.0-alpha.2, v3.0.0-alpha1, v2.4.15, v2.4.14, v2.4.13, v2.4.12, v2.4.11, v2.4.10, v2.4.9, v2.4.8, v2.4.7, v2.4.6, v2.4.5, v2.4.4, v2.4.3, v2.4.2, v2.4.1, v2.4.0, v2.4.0-RC1, v2.4.0-beta1, v2.4.0-alpha1, v2.3.11, v2.3.10, v2.3.9, v2.3.8, v2.3.7, v2.3.6, v2.3.5, v2.3.4, v2.3.3, v2.3.2, v2.3.1, v2.3.0, v2.2.1, v2.2.0, v2.1.2, 2.1.1, 2.1.0, v2.1.0-beta1, v2.1.0-alpha1, v2.0.5, v2.0.4, v2.0.3, v2.0.2, v2.0.1, v2.0.0, 1.3.1, 1.3.0, 1.2.1-patch1, v1.2.1, 1.2, 1.1, 1.0, 0.1, dev-master, 2.x-dev, dev-v3-dev] but these are rejected by your constraint.

make: *** [php-composer-update] Error 2
```

As latest version "v2.4.15".

Can anyone help me?

Thanks.

**Comment by REJack** [comment]
Asset Packaging fetchs approximately every 3-4 days the packages, but you can run the package fetch on https://asset-packagist.org/package/bower-asset/admin-lte if this error accours again.

Also I've fixed jquery package resolving with asset packaging with the new release 2.4.17, you should use this version instead of 2.4.16.
