### ISSUE TITLE
Reduce Font size a little

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2210]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:   3.0
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:
Font sizes on V3 are much bigger than V2 and I personally prefer V2's. I don't think I am the only one who feels like that. I would like to suggest to reduce font size and paddings a little bit on most widgets (for an instance : [card headers at widget page](https://adminlte.io/themes/dev/AdminLTE/pages/widgets.html)).

**Comment by REJack** [comment]
The bigger font size is bigger according to bootstrap 4's new font size, but I know the card header font size is a bit too big and padding is not nice too, I'll change this may I add also a custom class for compact sidebar nav items.

**Comment by REJack** [comment]
I've reduced the font-size and paddings/margins from card header/tools, also I created a `.nav-compact` class for reduced paddings in main-sidebar nav. 

This changes are pushed to my PR #2220

**Comment by REJack** [comment]
PR #2220 is merged
