### ISSUE TITLE
How install adminlte 3 with composer in laravel?

### ISSUE THREAD

**Issue by paraguayo7** [ColorlibHQ/AdminLTE#2214]
How do I install adminlte version 3 in laravel 5.8 with composer? version 2 I installed it with: 

> composer require acacha/admin-lte-template-laravel

and version 3 I try with:

> composer require acacha/admin-lte-template-laravel:3.*

but version 3 doesn't generate the template files, thanks.

**Comment by REJack** [comment]
For this you need to open an issue on the [package repo](https://github.com/acacha/adminlte-laravel) not here.
