### ISSUE TITLE
Design issue inside the class box-header

### ISSUE THREAD

**Issue by RaruRv** [ColorlibHQ/AdminLTE#2215]
### Issue type:
- [x] Bug report  

### Environment:
* AdminLTE Version:  2.4
* Operating System:  Ubuntu 16.04
* Browser (Version):  Google Chrome 66.0.3359.139 (Official Build) (64-bit)

URL : https://adminlte.io/themes/AdminLTE/pages/widgets.html
![Clipboard - August 19, 2019 5-45 PM](https://user-images.githubusercontent.com/315027/63265353-12ac7900-c2ab-11e9-9ccd-5dfdc92d7cfd.png)

If the data content inside heading of DIV with class 'box-header' is quiet larger, it will affect the desing as shown in the screenshot.

**Comment by REJack** [comment]
This issue is already fixed in my PR #2197. 

It will look like this:
![Screenshot_2019-08-19 AdminLTE 3 Widgets](https://user-images.githubusercontent.com/1554582/63266185-a2dcc500-c28f-11e9-93d6-d177aae4864d.png)

**Comment by REJack** [comment]
Oh dang 🤦‍♂ I've fixed it for v3 but I'll fix it in v2.4.18.

**Comment by REJack** [comment]
I've added a fix for this in master branch

**Comment by REJack** [comment]
This is released with v2.4.18
