### ISSUE TITLE
Background Image Collapsing faster than actual sidebar

### ISSUE THREAD

**Issue by drofnasb** [ColorlibHQ/AdminLTE#2216]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0beta1
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

### Description:
I added an image to the background of the left sidebar and when I collapse the sidebar the transition seems off. I see the image move faster than the actual animation of the collapse. Which makes the image disappear quicker and I end up seeing the background color as the bar is closing. I am not certain if this is a bug or not. I have tried adjusting transition values but I am missing something.

**Comment by REJack** [comment]
Can you provide a example for this, e.g. your css for the background image?

**Comment by drofnasb** [comment]
Forgive my ignorance if what I posted below is a simple error or a newbie mistake. I am new to this and searched all over before I made a topic.  The image has no other issues than the movement issue. Below is the code. 

.sidebar {
    height: calc(100% - 4rem);
    overflow-y: auto;
    padding-bottom: 0;
    padding-left: 0.5rem;
    padding-right: 0.5rem;
    padding-top: 0;
}

.sidebar-image .main-sidebar:before {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: #263238;
    background-position: bottom;
    background-attachment: fixed;
    background-repeat: no-repeat;
    opacity: .3;
}

.sidebar-image .main-sidebar:after {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
    background: rgba(0,0,0,.45);
    background: -webkit-gradient(linear,left bottom,left top,color-stop(0,rgba(0,0,0,.65)),color-stop(1,transparent));
    background: -o-linear-gradient(transparent,rgba(0,0,0,.65));
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='rgba(0, 0, 0, 0)',endColorstr='rgba(0, 0, 0, 0.65)',GradientType=0);
}

.background-clouds .main-sidebar:before {
    background-image: url('../img/Background Clouds.png');
    background-position: 0 100%;
}

**Comment by REJack** [comment]
Set in `.sidebar-image .main-sidebar:before` width to `100% !important;`, this should fix your bug 😄

**Comment by REJack** [comment]
Mmmh strange :/ in my test file it works with `width: 100% !imporant`, if I doesn't change this is the background image always a bit slower than the main sidebar animation itself.

**Comment by REJack** [comment]
Did you test it again with rc.1?

**Comment by drofnasb** [comment]
Yes it was a me issue. I didn't set the image to the right elements and the filter I put on was moving independent of the actual sidebar. Thanks for the help.
