### ISSUE TITLE
How can i embed the iframe to it?

### ISSUE THREAD

**Issue by yuxin5156** [ColorlibHQ/AdminLTE#2218]
How can i embed the iframe to it?

**Comment by REJack** [comment]
What excatly you mean?

**Comment by yuxin5156** [comment]
I means insert iframe  into content-wrapper,but zhe iframe can't be full of content-wrapper,because the content-wrapper use min-height

**Comment by REJack** [comment]
You can set the iframe height with `height: calc(100vh - 101px);` or `height: calc(100vh - 50px);` if you doesn't use the footer.
