### ISSUE TITLE
Collapse/Expand Card manually on click of buttons/some events also maintain +/- functionalities

### ISSUE THREAD

**Issue by sangeetmen** [ColorlibHQ/AdminLTE#2221]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [x] Documentation   

### Environment:
* AdminLTE Version:  3.0.0
* Operating System: Windows
* Browser (Version):  Firefox(Latest)

### Description:
I need to Collapse/Expand Cards at specific events and/or on button clicks manually. Also at the same time need the data-widget functionalities inside the card tools to work in sync.
How can that be done manually. Please add the same in the documentation, if possible with an example. 

I have collapse /expand the card using 

`$("#card-body").Widget('collapse');`
& 
`$("#card-body").Widget('expand')`

But need the tool icon to change at the same time when the card is collapsed/expanded

Thanks

**Comment by REJack** [comment]
I've modified the Widget Plugin with my last PR #2197, important changes since PR
- Widget is renamed to CardWidget
- CardWidget works now directly on the card e.g. `$('#my-card').CardWidget('collapse')`
- renamed data selector `data-widget="*"` to `data-card-widget="*"`
- created maximize & minimize methods

I only forgot to update the icons if it's used directly on card/card-body.

----

> Also at the same time need the data-widget functionalities inside the card tools to work in sync.

What you mean with "work in sync", if I change the collapse state direct on the card via javascript and then I click on the button the card expands but the icons are not update.

**Comment by sangeetmen** [comment]
When I expand/collapse the card via javascript mannually the icons were not updating. I wrote a custom function as below to get that done  

```
(function( $ ){
	   $.fn.cardAction = function(option) {
		  if(option=='collapse'){
			$(this).find('.card-body').Widget('collapse');
			var toolIcon=$(this).find('div').find('.fa-minus');
			$(toolIcon).removeClass('fa-minus');
			$(toolIcon).addClass('fa-plus');
		  }
		  else if(option=='expand'){
			$(this).find('.card-body').Widget('expand');						
			var toolIcon=$(this).find('div').find('.fa-plus');
			$(toolIcon).removeClass('fa-plus');
			$(toolIcon).addClass('fa-minus');			  
		  }
	      return this;
	   }; 
	}( jQuery));
```
Then called the function by the card id as per reqired

`$("#mycardID").cardAction ('collapse'); ` or  `$("#mycardID").cardAction ('expand');`

Anyways I will check out the Updated Plugin

**Comment by REJack** [comment]
You can also run `$('#mycardID [data-widget="collapse"]').Widget('collapse')` this updates the icon, only if you use the Widget on the card it self you need at the moment this workaround.

**Comment by sangeetmen** [comment]
**Great!!! that works perfectly.** I will be using this for the moment and will wait for future v3 updates and close this thread. 
**Thanks**

**Comment by Softcodic** [comment]
asdf
