### ISSUE TITLE
White space in content when using margin bottom

### ISSUE THREAD

**Issue by joester89** [ColorlibHQ/AdminLTE#2222]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  Version: 3.0.0beta2
* Operating System:  Windows
* Browser (Version):  Chrome(latest)

### Description:
When using the layout `layout-fixed` (others not tested) there is a problem when the last element in the content has a margin bottom. I am ending up with white space at the bottom.

![image](https://user-images.githubusercontent.com/9624366/63938224-96612500-ca64-11e9-8eb4-a1e88d3f78b3.png)

The last element now is a `div` having the class `mb-3`.

**Comment by joester89** [comment]
Just had a rubber-duck moment... This problem arises when not using `div.row` and `div.col` in the container.

**Comment by lukachochua** [comment]
Thank you for this :D Been struggling with the issue for the good part of 3 hours. Made tons of changes in bootstrap classes with no avail. Grateful af to stumble upon this.
