### ISSUE TITLE
Sidebar color and active color Not working with fix header

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2223]
- [ ] Bug report       

### Environment:
* AdminLTE Version:  3.0
* Operating System:  Windows
* Browser (Version):  Chrome (Latest) 

### Description:
When we are using fix Top header and fixed sidebar. Sidebar background color and active link background color not working with light background.

**Comment by REJack** [comment]
I can't replicate this issue, it works if I change on [this demo](https://adminlte.io/themes/dev/AdminLTE/index2.html) the sidebar style to any light style via control sidebar.

Please provide a example code.

**Comment by deepak458** [comment]
There is some issue with **Info boxes** width, its not configure properly for desktop.

![image](https://user-images.githubusercontent.com/29248598/64013444-6d609300-cb3d-11e9-9688-d98cd05f466f.png)

**Comment by deepak458** [comment]
When we are using popover with its showing text blur, but when i'm using multiple popover its show only first popover blur second popover a little clear and third one is with clear text.

You can view a little popover in below image. In this image popover text displaying with blur.
![image](https://user-images.githubusercontent.com/29248598/64013785-3b036580-cb3e-11e9-8513-8c815b8d9ab3.png)

**Comment by deepak458** [comment]
I have also a little customized Login page with Small Text and with a little bit long width of box.

![image](https://user-images.githubusercontent.com/29248598/64014063-dbf22080-cb3e-11e9-929a-231b38c95171.png)

**Comment by REJack** [comment]
> There is some issue with Info boxes width, its not configure properly for desktop.

Can you provide the html code from it, on the demo it works.

> When we are using popover with its showing text blur, but when i'm using multiple popover its show only first popover blur second popover a little clear and third one is with clear text.

What you mean with blur text and can you provide the html code from it?

> I have also a little customized Login page with Small Text and with a little bit long width of box.

I'll update Logo font size / padding it's quite big, but smaller text inside the card you can use `.text-sm`, if you want to use col-* for the card sizing add e.g. `col-sm-6 w-100` to the `div.login-box`
