### ISSUE TITLE
White Space above footer

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2225]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version:  3.0
* Operating System:  Windows
* Browser (Version):  Chrome (Latest)

### Description:
There is a little white space above footer. it's look like footer start from white space.

**Comment by REJack** [comment]
Can you please provide some infos like a picture or a code example?

**Comment by deepak458** [comment]
@REJack you can view it in following image
![image](https://user-images.githubusercontent.com/29248598/64019312-71e07800-cb4c-11e9-9598-67b75062beb6.png)

**Comment by REJack** [comment]
I found the bug, the single cards need to nested in `<div class="row">` & `<div class="col-*">`. I'll update the demo files.
