### ISSUE TITLE
Callouts message fonts a little bit larger or need a little more padding.

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2226]
### Issue type:
- [ ] Feature request 

### Description:
**Callouts** messages text and headline fonts are a little big, you can small the font size a little bit or add a little padding into it.

**Comment by REJack** [comment]
I see what you mean, I'll increase the padding a bit.

**Comment by deepak458** [comment]
Can we change **Callouts** with old background color it's easy to display message.
![image](https://user-images.githubusercontent.com/29248598/64023538-2af78000-cb56-11e9-9e1a-107a383c3306.png)

**Comment by REJack** [comment]
You can combine it with bg-* e.g. `callout-danger bg-danger`

**Comment by REJack** [comment]
PR #2220 is merged
