### ISSUE TITLE
Popover text have some blur or contrast issue!!!

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2227]
### Issue type:
- [ ] Bug report       

### Description:
When we are using popover with its showing text blur, but when i'm using multiple popover its show only first popover blur second popover a little clear and third one is with clear text.

You can view a little popover in below image. In this image popover text displaying with blur.
image
![image](https://user-images.githubusercontent.com/29248598/64019375-9c323580-cb4c-11e9-94b6-94095e640068.png)

You can clearly take a look my my question in below image "See the popover text contrast and background font contrast"
![image](https://user-images.githubusercontent.com/29248598/64019777-ac96e000-cb4d-11e9-91d3-9f59642af504.png)

**Comment by REJack** [comment]
Please provide a code example

**Comment by deepak458** [comment]
@REJack  You can see my last image

**Comment by REJack** [comment]
Yes I see but how you changed this style?

**Comment by REJack** [comment]
And which browser you use?

**Comment by deepak458** [comment]
> Yes I see but how you changed this style?

Which Style?

> And which browser you use?
Currently Using Chrome Latest Version in Windows

**Comment by REJack** [comment]
I see what you mean on your pictures, but I can't replicate this bug I get always the correct color without any blur
