### ISSUE TITLE
Loading bar at the starting of the page with fix top nav bar

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2228]
### Issue type:
- [ ] Feature request 

### Description:
I'm looking for one more feature on it for Angular or Ajax request can you add a loading bar at the begin of the page along with loading icon in center of the header. And its also appear with fix top header.

**Comment by REJack** [comment]
There is already pace added in plugins, I'll add a example for pace. You can take a look [here](https://github.hubspot.com/pace/docs/welcome/) for the pace themes.

**Comment by deepak458** [comment]
@REJack is there any way so we can get early acess to the V.3 RC1 that completed till now.

**Comment by REJack** [comment]
You need to download my fork from #2220 and compile the css/js by your self, I'll update the dist files at last change in my PR they are still the pre PR dist files.
