### ISSUE TITLE
Inbuilt Notification or Alret option other then  Toastr or sweet alerts

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2229]
### Issue type:
- [ ] Feature request 

### Description:
Can you add more inbuilt alerts like Toastr or sweet alerts with few customization. i know i can use both by plugin but i'm looking for something inbuilt so i don't need to add one more plugin in my code only for notifications if we have few more option in V.3.0

**Comment by REJack** [comment]
There are [toasts](https://getbootstrap.com/docs/4.3/components/toasts/) from bootstrap 4 itself, but this has no javascript driven markup creation you would need to inject the toast markup by your self.

**Comment by REJack** [comment]
I've created a simple plugin to create easily bootstrap 4 toasts via javascript in my PR #2256 
You can test it, I've created also a demo and docs for it.

**Comment by deepak458** [comment]
@REJack we we received RC 2, and also where I can check demo of this alert.

**Comment by cataclysmuprising** [comment]
@deepak458  You can clone and test from [his forked repo](https://github.com/REJack/AdminLTE/tree/v3-dev).

**Comment by deepak458** [comment]
@REJack getting error with build in *Toasts Examples built in AdminLTE*
`modals.html:1219 Uncaught TypeError: $(...).Toasts is not a function`
