### ISSUE TITLE
Widget: user widget improvement

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2230]
### Issue type:
- [ ] Feature request 

### Description:
I'm taking a look of Widget: user widget and i think there is some issue with card, in the card head text aling left currently something look like this
![image](https://user-images.githubusercontent.com/29248598/64058135-2ff31880-cbc4-11e9-874a-aa307033f086.png)

But i have made few changes with following style, so you can get the exact idea what i'm saying.
![image](https://user-images.githubusercontent.com/29248598/64058160-924c1900-cbc4-11e9-9ecd-1b870c575a13.png)

**Comment by deepak458** [comment]
There is one more widgets header not configure properly check below image.
![image](https://user-images.githubusercontent.com/29248598/64058176-f838a080-cbc4-11e9-8a26-bb5e4a136adc.png)

**Comment by deepak458** [comment]
Sidebar looks very good but sidebar shadow a little bit long. You can see the sidebar shadow upper of the "content-wrapper" box. If you want to continue with that long shadow you can but then you need to increase the left padding in "content-wrapper".

**Comment by deepak458** [comment]
If you click on **back-to-top** button. its good but when it's on focus icon color change with gray color.

**Comment by deepak458** [comment]
Vertical Tabs Examples not configure for mobile, its overly with content in mobile view. also your can use  tab-pane with **text-align: justify**

**Comment by REJack** [comment]
Can you provide the changed css from your user widget?

> Sidebar looks very good but sidebar shadow a little bit long. You can see the sidebar shadow over of the "content-wrapper" card. If you want to continue with that long shadow you can but then you need to increase the left padding in "content-wrapper".
 
I personally like the look, but if you want a smaller shadow on the sidebar you can change `elevation-4`-class to `elevation-3` or less, alternatively you can set `pl-1` or `pl-2` on `.content-wrapper` for padding-left.

> Vertical Tabs Examples not configure for mobile, its overly with content in mobile view. also your can use tab-pane with text-align: justify
I'll update the vertical tabs examples, but you can litteraly set the sizes for mobile by your self also you can add `.text-left` if you want anywhere text align left.

**Comment by deepak458** [comment]
> ### Issue type:
> * [ ]  Feature request
> 
> ### Description:
> I'm taking a look of Widget: user widget and i think there is some issue with card, in the card head text aling left currently something look like this
> ![image](https://user-images.githubusercontent.com/29248598/64058135-2ff31880-cbc4-11e9-874a-aa307033f086.png)
> 
> But i have made few changes with following style, so you can get the exact idea what i'm saying.
> ![image](https://user-images.githubusercontent.com/29248598/64058160-924c1900-cbc4-11e9-9ecd-1b870c575a13.png)


I have made few changes you can check below.
.widget-user .widget-user-header {
    border-top-left-radius: .25rem;
    border-top-right-radius: .25rem;
    height: 135px;/* Added 15px more height */
    padding: 1rem;
	text-align: center;/* Added text-align - center; */
}

.widget-user .widget-user-image {
    left: 50%;
    margin-left: -45px;
    position: absolute;
    top: 90px;/*Added 25px more in top*/
}

.widget-user .card-footer {
    padding-top: 60px; /* Added 20px more Padding */
}

**Comment by deepak458** [comment]
@REJack waiting for today release how much time you will take.

**Comment by REJack** [comment]
@deepak458 I'll work on it today and merge my PR soon with the compiled dist files, but I release it at the latest at 9 PM CEST.

**Comment by REJack** [comment]
PR #2220 is merged
