### ISSUE TITLE
NPM Download getting error

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2231]
### Issue type:
- [ ] Bug report       

### Description:
Hello, I'm facing following issue with downloading Beta 2.0 from NPM.

C:\Users\Deepak>npm install admin-lte@3.0.0-beta.2 --save
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/bbmumford/jqvmap.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Deepak\AppData\Roaming\npm-cache\_logs\2019-08-31T04_39_38_989Z-debug.log

**Comment by REJack** [comment]
This error appears if you doesn't have git installed on your system, in beta.2 it's needed but this will removed with rc.1.
