### ISSUE TITLE
Right Sidebar do not display on mobile layout

### ISSUE THREAD

**Issue by SmileYzn** [ColorlibHQ/AdminLTE#2233]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  v3 Latest release
* Operating System: Proudly Linux Mint 19.2 :sunglasses: 
* Browser (Version):  Chromium 76.0.3809.100

### Description:

The right sidebar do not get displayed when layout is in mobile.

![Captura de tela de 2019-09-02 01-04-00](https://user-images.githubusercontent.com/5851851/64089669-8f187080-cd1d-11e9-8d64-101cec03e0f1.png)

Thanks for hard work.

**Comment by REJack** [comment]
Oh dang 🤦‍♂, I'll change this in my next PR.

**Comment by REJack** [comment]
I've added a fix for this issue in my PR #2256

**Comment by SmileYzn** [comment]
Thanks
