### ISSUE TITLE
freezing a little while clicking on sidebar toggler at some pages

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2234]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version:  3.0.0-rc.1
* Operating System:  Window 10
* Browser (Version):  Firefox(Latest)

### Description:

When I clicking several times on sidebar toggler (_data-widget="pushmenu"_), I have noticed that it was freezed a little on most pages _(eg: dashboard pages)_ but it is smooth on some page like  **Forms > Editors** .

**Comment by REJack** [comment]
How you mean freezed, like a delay or not opening?

**Comment by cataclysmuprising** [comment]
Please test by clicking on `pushmenu` widget several times and compare on different pages. It is a bit slow on most pages  but it is smooth on some page like **Forms > Editors** .

**Comment by REJack** [comment]
I get only really rarely this behavior mostly on high cpu loads :/ I guess this depends on the used plugins, on the dashboards are many plugins that regenerate the content on resize events.
