### ISSUE TITLE
rectangular input boxes

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2235]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  3.0.0-rc.1
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:

I don't like rounded input boxes of v3. Can I get a style class to override rounded boxes to rectangular boxes as v2 ?

**Comment by cataclysmuprising** [comment]
Sorry ... I think I should use the style class `rounded-0`.

**Comment by REJack** [comment]
Yep that's correct 😄 `rounded-0` is the correct way.
