### ISSUE TITLE
Input mask is not working. Mask is showing  but unable to enter anything

### ISSUE THREAD

**Issue by sangeetmen** [ColorlibHQ/AdminLTE#2237]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v3 rc1 beta2
* Operating System:   Windows 10
* Browser (Version):   Firefox/Chrome (Latest)

### Description:

The input mask (Forms > Advance Elements) is not working. I am unable to type any number in any of the input boxes.

![image](https://user-images.githubusercontent.com/32362498/64097743-b05f7800-cd82-11e9-81a9-db76aa157fab.png)

The mask is shown but it does not allow me to type anything 

![image](https://user-images.githubusercontent.com/32362498/64098364-4d6ee080-cd84-11e9-830a-0b0433cc0df1.png)

**Comment by deepak458** [comment]
npm download url ?

**Comment by REJack** [comment]
This error comes from a wrong markup, I've created a fix in my fork and create soon a PR draft with this fix.

@deepak458 what you mean with npm download url?

**Comment by REJack** [comment]
I've added a fix in my PR for this.
