### ISSUE TITLE
How can re-init the sidebar in angular 7?

### ISSUE THREAD

**Issue by JorgelGtzGtz** [ColorlibHQ/AdminLTE#2238]
Hello, I cant init the side bar in angular project, if refresh all page working fine the tree menu in the side bar but when navigate from login to main page the menu failed.

I use the version 2.4.17

I hope can help me

**Comment by REJack** [comment]
You need to init the plugins like this 
```js
$('body').layout();
$('[data-toggle="push-menu"]').pushMenu();
$('[data-widget="tree"]').tree();
$('[data-toggle="control-sidebar"]').controlSidebar();
```
