### ISSUE TITLE
brand-link background issue

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2239]
If we use Fix Navbar + Fix Sidebar along with Primary Header, Primary Light Sidebar and if we add **navbar-primary** into brand-link to it's show white background because of following class:
`.layout-navbar-fixed .wrapper .sidebar-light-primary .brand-link {
    background-color: #fff;
}`

**Comment by REJack** [comment]
Use __bg-primary__ instead of __navbar-primary__, this should work.

**Comment by deepak458** [comment]
@REJack i have already figure it out, currently using **`bg-primary`** but that should need to fix, because if you are using **`bg-primary`** in **`brand-link`** it consider it as link with bg-primary and when we hover it the background color change because of **`bg-primaty`** a class.

**Comment by REJack** [comment]
I see what you mean, I'll fix navbar-* for usage on brand-link

**Comment by deepak458** [comment]
Thnaks !!!

**Comment by REJack** [comment]
I've added a fix in my PR #2256
