### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by julianonunes** [ColorlibHQ/AdminLTE#2240]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

None of the above.

### Environment:
* AdminLTE Version:  3.0.0-rc.1
* Operating System:  Windows
* Browser (Version):  Chrome (Latest)

### Description:

I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/admin-lte?version=3.0.0-rc.1) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by REJack** [comment]
I‘ve seen that the npm package is really big on publishing, I‘ll remove the plugins directory from the npm package and add travisci to create on new tags a complete zip with all plugins for github releases. 

I‘m also not happy with all the plugins inside the github repo itself.

**Comment by julianonunes** [comment]
Not sure, but I think the sample images are also in the npm package and there are some large photos there.

**Comment by REJack** [comment]
That's true but also the summary of the plugins crashed the size limit, the easiest way is to ignore the plugins folder in package.json and may the docs folder too. The plugins folder is not necessary for npm all the plugins are in the package.json.

I only would need to update the README.md/docs for demo usage with npm/yarn install.

**Comment by REJack** [comment]
I've added a `.npmignore` to ignore plugins & docs in my PR #2256, that will reduce the npm package size.
