### ISSUE TITLE
How to resize top-nav layout to full width

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2241]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  2.4.15
* Operating System:  Windows
* Browser (Version):  Chrome

### Description:
I am using AdminLTE top-nav layout as a landing page. Please how do I make it (resize) to occupy the whole width. I don't want any space on the sides. It should occupy both sides. I want to resize it to occupy full width.

**Comment by REJack** [comment]
Inside the Header & Content Wrapper is a `.container` change this to `.container-fluid` and you get your fullwidth 😄

**Comment by noblemfd** [comment]
@REJack  Please Inside which of the css will I find Header & Content Wrapper  .container to change to .container-fluid

**Comment by REJack** [comment]
According to the demo [L37](https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/layout/top-nav.html#L37) & [L222](https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/layout/top-nav.html#L222)

**Comment by noblemfd** [comment]
@REJack  - Great, you solved the problem.  Thanks
