### ISSUE TITLE
Is the feature that toggle right sidebar slide some problem?

### ISSUE THREAD

**Issue by Jionl** [ColorlibHQ/AdminLTE#2243]
When I had selected the feature that toggle right sidebar slide, and then I click the setting button.
The slide bar can't close, just display none...

**Comment by REJack** [comment]
In which version of AdminLTE you get this bug, v2.4 or v3.0?

**Comment by Jionl** [comment]
I find this bug in v2.4, and it is Ok in v2.3.

**Comment by REJack** [comment]
What's your exact version e.g. 2.4.18?
Please provide a code example of the control sidebar toggle.

**Comment by Jionl** [comment]
Yes, I find the bug in exact version e.g.2.4.18 and e.g.2.4.17.
I never write any code. The setting in the demo.js. 
Can I upload the picture?
![pic1](https://user-images.githubusercontent.com/19813649/64232485-a07f9980-cf24-11e9-9849-a1d62ff7afda.png)
![pic2](https://user-images.githubusercontent.com/19813649/64232501-a5444d80-cf24-11e9-9b36-1b539f61c1c9.png)

**Comment by REJack** [comment]
This is only demo releated bug, the demo.js only set the class to body and doesn't changes the option to get the right closing behavior. for the correct result you would need to add `data-controlsidebar-slide="false"` to the control sidebar toggle.

**Comment by Jionl** [comment]
OK,I see, thanks.
