### ISSUE TITLE
How to change the grey background colour to an image

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2244]
### Issue type:
- [ ] Feature request Requesting the implementation of a new feature

### Environment:
* AdminLTE Version:  2.4.15 
* Operating System:  Windows
* Browser (Version):  Example: Chrome (Latest)

![adminlte-topnav](https://user-images.githubusercontent.com/34077129/64252060-d49d8f00-cf11-11e9-89d6-db9985dae678.PNG)

Hello, I want to use AdminLTE top-nav layout as a landing page. 

1. How do I change the grey background colour to and image
2. Is there any other way to get a good landing page in AdminLTE?
3. How do I add carousel to my AdminLTE to make it look like landing page?

**Comment by REJack** [comment]
1. add custom css like this 
```css
.content-wrapper {
   background: blue;
   // here you can add also a image
}
```
2. I don't know
3. You can try to adapt [this](https://codepen.io/ondrejsvestka/pen/wdMZzz) for your behavior

**Comment by noblemfd** [comment]
@REJack - Am sorry please, where do I add the custom CSS?

**Comment by REJack** [comment]
Create a css file and load it after the adminlte css file

**Comment by noblemfd** [comment]
OK. Thanks
