### ISSUE TITLE
AdminLTE v3.0.0-rc.1 released

### ISSUE THREAD

**Issue by REJack** [ColorlibHQ/AdminLTE#2245]
Hey folks, 

I've published recently AdminLTE v3.0.0-rc.1 🎉 . with some nice changes like:
- migrated CardRefresh aka BoxRefresh
- enhanced CardWidget JS
- enhanced ControlSidebar CSS/JS
- added Dropdown JS
- added new demo pages
- updated plugins and added all missing datatables extensions
- _and many more..._

For the complete changelog [look here](https://github.com/ColorlibHQ/AdminLTE/compare/v3.0.0-beta.2...v3.0.0-rc.1).

[AdminLTE v3 Demo](https://adminlte.io/themes/dev/AdminLTE/)
[AdminLTE v3 Docs](https://adminlte.io/docs/3.0/)

It would be awesome if you can test AdminLTE v3.0.0-rc.1 😄

Feel free to open issues with bugs/errors or feature requests for AdminLTE v3.0.0.

**Comment by jhongonz** [comment]
thanks for the support

**Comment by syarifulumam** [comment]
can't input in the date mask form
