### ISSUE TITLE
Multilevel Menu Feature request 

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2246]
### Issue type:
- [ ] Feature request 

### Description:
Looking for **Multilevel Menu**in sidebar

**Comment by REJack** [comment]
This is already added in v2 and v3 but in v3 is no demo in the sidebar.

**Comment by REJack** [comment]
I've added a multi level example across the demo pages for v3 in my PR #2256

**Comment by AlexLove77** [comment]
I've tried multi level example,  but there is no indention in sub menu. How do I add the indention? Thanks.

**Comment by REJack** [comment]
Add `.nav-child-indent` to `.nav-sidebar`.

**Comment by potatollu** [comment]
hello world

**Comment by fredmichel81** [comment]
Hi,

I was comparing MULTI LEVEL EXAMPLE vrom V2 to V3 and I wonder if there is a way to have the Multilevel Menu Show exactly the same way as in V2. The V3 are all aligned left, but in the V2 we see the Indentation for all sub menu levels.

See below image:
![Capture](https://user-images.githubusercontent.com/55694604/67512567-166fc980-f667-11e9-9076-b909ead66cbc.PNG)

Thank you

**Comment by AlexLove77** [comment]
Hi fredmichel81,


Add `.nav-child-indent` to `.nav-sidebar`.


_Originally posted by @REJack in https://github.com/ColorlibHQ/AdminLTE/issues/2246#issuecomment-531848321_





------------------ 原始邮件 ------------------
发件人: "fredmichel81"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 凌晨2:05
收件人: "ColorlibHQ/AdminLTE"<AdminLTE@noreply.github.com>;
抄送: "Alex.Cao"<crlwinner@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ColorlibHQ/AdminLTE] Multilevel Menu Feature request  (#2246)




Hi,
 
I was comparing MULTI LEVEL EXAMPLE vrom V2 to V3 and I wonder if there is a way to have the Multilevel Menu Show exactly the same way as in V2. The V3 are all aligned left, but in the V2 we see the Indentation for all sub menu levels.
 
See below image:
 
 
Thank you

**Comment by fredmichel81** [comment]
> 
> Hi fredmichel81, Add `.nav-child-indent` to `.nav-sidebar`. _Originally posted by @REJack in [#2246 (comment)](https://github.com/ColorlibHQ/AdminLTE/issues/2246#issuecomment-531848321_)
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "fredmichel81"<notifications@github.com>; 发送时间: 2019年10月25日(星期五) 凌晨2:05 收件人: "ColorlibHQ/AdminLTE"<AdminLTE@noreply.github.com>; 抄送: "Alex.Cao"<crlwinner@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [ColorlibHQ/AdminLTE] Multilevel Menu Feature request (#2246) Hi, I was comparing MULTI LEVEL EXAMPLE vrom V2 to V3 and I wonder if there is a way to have the Multilevel Menu Show exactly the same way as in V2. The V3 are all aligned left, but in the V2 we see the Indentation for all sub menu levels. See below image: Thank you — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Amazing :), thanks a lot

**Comment by fredmichel81** [comment]
Hi Alex,
Thanks a lot :)
