### ISSUE TITLE
How to Align top and side (left and right) in Top Nav Layout - Remove spaces

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2248]
### Issue type:
- [ ] Feature request Requesting the implementation of a new feature

### Environment:
* AdminLTE Version:  Example: 2.4 .15
* Operating System:  Example: Windows
* Browser (Version):  Example: Chrome (Latest)

![adminlte_topnav](https://user-images.githubusercontent.com/34077129/64315180-3bba5280-cfa9-11e9-8c2b-b493830f5e4e.PNG)

### Description:
AdminLTE Top Nav Layout is being used as my Landing Page. From the diagram above,  I have already replace `<div class="container">` with `<div class="container-fluid">` to stretch the top bar and the content-wrapper. However, where I marked red, I want to remove spaces between the top left and right. That is, make the content to touch the top bar and the two sides.

Please how do I achieve this?

**Comment by REJack** [comment]
Remove `.content` from `<section class="content">` or place new code in clean div above it.

**Comment by noblemfd** [comment]
@REJack - When I removed `.content` from `<section class="content">`, the spaces on top has been removed, which is okay. But the left and right sides still have spaces. How do I resolve that.  See the latest changes below:

![adminlte_topnav_latest](https://user-images.githubusercontent.com/34077129/64318573-4cbb9180-cfb2-11e9-9a15-f51fe77d6830.PNG)

Thanks

**Comment by REJack** [comment]
If I remove the `.content` in the top-nav I have no paddings there. Do you have `.row` around?

**Comment by noblemfd** [comment]
@REJack  - No, I don.t have `.row` around.  This s what I have there:

`    <div class="content-wrapper">
    <div class="container-fluid">
      

      
      <section>
        <div class="callout callout-info">
          <h4>Tip!</h4>

          <p>Add the layout-top-nav class to the body tag to get this layout. This feature can also be used with a
            sidebar! So use this class if you want to remove the custom dropdown menus from the navbar and use regular
            links instead.</p>
        </div>
        <div class="callout callout-danger">
          <h4>Warning!</h4>

          <p>The construction of this layout differs from the normal one. In other words, the HTML markup of the navbar
            and the content will slightly differ than that of the normal layout.</p>
        </div>
        <div class="box box-default">
          <div class="box-header with-border">
            <h3 class="box-title">Blank Box</h3>
          </div>
          <div class="box-body">
            The great content goes here
          </div>
          
        </div>
        
      </section>
      
    </div>
    
  </div>`
