### ISSUE TITLE
整体字体过大，希望可以添加调整字体大小功能

### ISSUE THREAD

**Issue by longfeide2008** [ColorlibHQ/AdminLTE#2249]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version: 3.0 
* Operating System:  macos 
* Browser (Version):   Google Chrome 76.0.3809.132（正式版本） （64 位）  !-- Example: Chrome (Latest) -->

### Description:

整体字体过于大，希望可以添加调整字体大小的功能。
如下是浏览器缩放比例100%，屏幕可显示内容非常少，缩放比例调整到75%-80%感觉刚刚好。

浏览器 100%显示效果：
![image](https://user-images.githubusercontent.com/26161015/64315276-29113f00-cfe4-11e9-9716-2a9de9bebd16.png)

浏览器 75%显示效果:
![image](https://user-images.githubusercontent.com/26161015/64315235-13037e80-cfe4-11e9-88e9-9d07c5f5c658.png)

希望页面字体可以统一缩放：
![image](https://user-images.githubusercontent.com/26161015/64315488-c0769200-cfe4-11e9-864c-bf87675206a2.png)

**Comment by REJack** [comment]
Please write your issue in english

**Comment by xiaozhi2018** [comment]
@REJack He said the font was too big

**Comment by longfeide2008** [comment]
> @REJack他说字体太大了

yes

**Comment by REJack** [comment]
I close this issue there is a english version #2251
