### ISSUE TITLE
About AdminLTE V3 font issue

### ISSUE THREAD

**Issue by longfeide2008** [ColorlibHQ/AdminLTE#2251]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  3.0.0-beta.2 
* Operating System:  macos 10.14.6 
* Browser (Version):  Google Chrome 76.0.3809.132 

### Description:
AdminLTE V3 overall font is too large, I hope to add the ability to adjust the font size.

The following is a browser scale of 100%, the screen can display very little content, if you adjust the browser zoom ratio to 75% -80% feel better.

Browser zoom ratio 100% display effect:
![image](https://user-images.githubusercontent.com/26161015/64326178-13a80f00-cffc-11e9-8b1d-4d642b9e0d30.png)

Browser zoom ratio 75% display effect:
![image](https://user-images.githubusercontent.com/26161015/64326258-3cc89f80-cffc-11e9-86c6-025e8c086534.png)

I hope the text displayed on the page can support unified zoom.
![image](https://user-images.githubusercontent.com/26161015/64326290-4b16bb80-cffc-11e9-911a-597a298ec35b.png)

**Comment by andcarpi** [comment]
Modify $font-size-base in _bootstrap-variables.scss from 1rem to 0.9 rem...

**Comment by longfeide2008** [comment]
> 将_bootstrap-variables.scss中的$ font-size-base从1rem修改为0.9 rem ...

Need to rebuild?

**Comment by andcarpi** [comment]
Yes... but it's an easy process...
1. Git clone the AdminLTE v3-dev branch
`git clone -b v3-dev https://github.com/ColorlibHQ/AdminLTE.git`
2. Install Dependencies (inside the new AdminLTE folder)
`npm install`
3. Start dev
`npm run dev`
4. Make the modifications and wait the build
5. Copy the modified files from the dist folder

**Comment by andcarpi** [comment]
Please note that this process will affect only the font size, and not the whole layout size like the browser zoom ratio. But it will help you to fit more content.
To make a "compact" AdminLTE, a lot more options would have to be changed like paddings, margins, sizes, etc...

**Comment by REJack** [comment]
The easiest way is to change and rebuild, I've also added a class for a sidebar menu but you can also add text-sm to the parts where you want have smaller font sizes.

**Comment by REJack** [comment]
I've added support for .text-sm with brand-link, main-header, main-sidebar & main-footer in my PR #2256 with that you can get a nice result with smaller font size, you can also use it on `.content` too.

**Comment by longfeide2008** [comment]
> I've added support for .text-sm with brand-link, main-header, main-sidebar & main-footer in my PR #2256 with that you can get a nice result with smaller font size, you can also use it on `.content` too.

I tested. text-sm added to body to change the global font size, but is there any other rule font size optional?
Whether it can be added to Control Sidebar is that users can customize and adjust the font size.

**Comment by REJack** [comment]
> I tested. text-sm added to body to change the global font size, but is there any other rule font size optional? @longfeide2008 
> I wish text-sm class or something to add at body and this makes the whole theme to change smaller (fonts,paddings,margins .. etc) @cataclysmuprising

I've added support for `.text-sm` on body that reduces the header/brand & footer height and fontsize.
I changed only the padding from nav-link in card header.


> Whether it can be added to Control Sidebar is that users can customize and adjust the font size.

I've added some checkboxes to the control sidebar in demo (demo.js), to try the smaller fonts in

**Comment by cataclysmuprising** [comment]
@REJack  I think `text-sm` does not effect on `.content-header h1`. It still takes `1.8rem` and should reduce little amount of paddings too for `text-sm` on body class. Thanks for your great works. :D

**Comment by REJack** [comment]
I added in my local repo a override for content-header, I'll push it later on my PR.
Which paddings should reduced with `text-sm`?
I like the result with `text-sm`, but I doesn't checked if anything looks good with it.

**Comment by cataclysmuprising** [comment]
@REJack  Hello bro.. I personally used some css changes for `text-sm` as

```
.text-sm .content-header {
    padding: 10px .5rem;
}

.text-sm .content-header h1 {
    font-size: 1.5rem;
}

.text-sm .form-control {
    font-size: .875rem;
}
```
and added `input-sm` class as

```
.input-sm {
    height: calc(1.875rem + 2px);
}
```

I will try to reduce some paddings and margins at near future at my custom css file because AdminLTE 3 is bigger a lot and I think it looks bad at my home computer (1280 resolution). I need to reduce most of components for compact view. Please don't be mind my words. I really appreciated your efforts and great works. Our local clients mostly use 1280 resolution screens and they can't see most pages without scrolling. 

`text-sm` class helps me alot.

**Comment by REJack** [comment]
I'll test your css changes 😄 but you can use `.form-control-sm` beside `.form-control` instead of your custom `input-sm` class.

Please create a new issue, if you have some padding change ideas.

**Comment by REJack** [comment]
I've enhanced the content header with `body.text-sm` in my PR 😄

**Comment by cataclysmuprising** [comment]
Thank you bro ! Can I get and test PR ?

**Comment by REJack** [comment]
I'll merge my PR soon then you can download the compiled files from the main repo, but you can download [my fork](https://github.com/REJack/AdminLTE/tree/v3-dev) and compile the dist files.

**Comment by cataclysmuprising** [comment]
`.dropdown-menu` still remain in **1rem** for `text-sm`

**Comment by REJack** [comment]
I've added a fix in my PR for the dropdown-menu, button & dropdown-toggle.
