### ISSUE TITLE
 Problem with sidebar-menu

### ISSUE THREAD

**Issue by dedzec** [ColorlibHQ/AdminLTE#2253]
Hello,

I have problems with the sidebar when any other modal in my project.
Before opening the modal:
![antes](https://user-images.githubusercontent.com/43690181/64352762-f4e15280-cfd2-11e9-9653-2d065591c271.PNG)

After the modal has been opened:
![depois](https://user-images.githubusercontent.com/43690181/64352809-09254f80-cfd3-11e9-82d0-c05b7d77d6b3.PNG)

I was wondering if this problem is in javascript or css because I tried everything and was unsuccessful.

**Comment by andcarpi** [comment]
What adminlte version are you using? 2.... 

And well, that's probably a problem in your modal calling/closing. Do some checks:

1. Modal structure

2. Conflicts in:  
- Modal divs id
- Buttons data-target ids
- Menu items id.

**Comment by dedzec** [comment]
I'm using version 3.2.11

**Comment by REJack** [comment]
This bug can come with an old version of jQuery, try to update it to 3.4.1 like it's in the latest release (v2.4.18)
