### ISSUE TITLE
Questions about AdminLTE upgrade

### ISSUE THREAD

**Issue by longfeide2008** [ColorlibHQ/AdminLTE#2254]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  AdminLTE-3.0.0-beta.2 
* Operating System:  macos 10.14.6 
* Browser (Version):  Google Chrome 76.0.3809.132 

### Description:

Currently my engineering front-end framework is built on AdminLTE-3.0.0-beta.2 and is rendered using Flask templates. What do I need to do if I want to upgrade to AdminLTE-3.0.0-rc.1? Need to re-adjust?

**Comment by REJack** [comment]
The biggest change between beta.2 and rc.1 is that I've renamed the data api for card widgets like `data-widget="remove"` to `data-card-widget="remove"` and some JS option changes like `data-slide="false"` to `data-controlsidebar-slide="false"`.

**Comment by longfeide2008** [comment]
> The biggest change between beta.2 and rc.1 is that I've renamed the data api for card widgets like `data-widget="remove"` to `data-card-widget="remove"` and some JS option changes like `data-slide="false"` to `data-controlsidebar-slide="false"`.

First of all, thank you very much!

Then I just can't upgrade directly, right?
Need to be redeveloped based on the new version?

**Comment by REJack** [comment]
> Then I just can't upgrade directly, right?

If you doesn't use the card tools (e.g. collapse card button) you can update it without problems, if you does use the card tools you will need to update the card widget data api to get the card widget's working.

>  Need to be redeveloped based on the new version?

What you mean with that?

**Comment by longfeide2008** [comment]
> > Then I just can't upgrade directly, right?
> 
> If you doesn't use the card tools (e.g. collapse card button) you can update it without problems, if you does use the card tools you will need to update the card widget data api to get the card widget's working.
> 
> > Need to be redeveloped based on the new version?
> 
> What you mean with that?

I just started to contact Adminlte and feel very good, but I don't know how to update it to the new version based on the old version.

For example, the following code is the Flask template I made.

![image](https://user-images.githubusercontent.com/26161015/64413024-508b0900-d0c3-11e9-86d1-987698e11a54.png)

**Comment by REJack** [comment]
first you should update the js/css files, the main template need no changes but you may need update other templates

**Comment by longfeide2008** [comment]
> 首先你应该更新js / css文件，主模板不需要更改，但你可能需要更新其他模板

Okay, I probably understand

**Comment by REJack** [comment]
Can this issue closed?

**Comment by longfeide2008** [comment]
> 这个问题可以关闭吗？

Yes, thank you very much!
