### ISSUE TITLE
How to use bootstrap-switch in AdminLTE

### ISSUE THREAD

**Issue by longfeide2008** [ColorlibHQ/AdminLTE#2255]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  3.0 
* Operating System:  macos 
* Browser (Version):  google chrome 

### Description:
I want to add a switch button to the form.

example:
![image](https://user-images.githubusercontent.com/26161015/64399185-1d804f80-d09a-11e9-83a5-9aa50ca67fe0.png)

I follow the official documentation to include the dependency library.

<link rel="stylesheet" href="css/bootstrap4/bootstrap-switch.css">
<script src="js/bootstrap-switch.js" type="text/javascript"></script>

Instantiation:
![image](https://user-images.githubusercontent.com/26161015/64399547-5836b780-d09b-11e9-85e8-509d65fe81c9.png)

But I found the result to be wrong,All are OFF.
![image](https://user-images.githubusercontent.com/26161015/64399570-756b8600-d09b-11e9-9ccb-4f1330d17790.png)

Comment out drawCallback,The result is correct,But there is no style.
![image](https://user-images.githubusercontent.com/26161015/64399686-f460be80-d09b-11e9-86f5-2dd342d33106.png)

I need to use bootstrap-switch in AdminLTE DataTables.

**Comment by REJack** [comment]
Related to bootstrap-switch you should use a method from bootstrap-switch like `$('input[name="my-checkbox"]').bootstrapSwitch('state', true);`.

Docs: https://bttstrp.github.io/bootstrap-switch/methods.html

**Comment by longfeide2008** [comment]
> Related to bootstrap-switch you should use a method from bootstrap-switch like `$('input[name="my-checkbox"]').bootstrapSwitch('state', true);`.
> 
> Docs: https://bttstrp.github.io/bootstrap-switch/methods.html

Maybe I didn't describe my problem clearly.

I made a test page

Original state:
// $("[name='my-checkbox']").bootstrapSwitch('state', true);
![image](https://user-images.githubusercontent.com/26161015/64409734-094d4a00-d0bc-11e9-9d53-2bccdb6dbb81.png)

![image](https://user-images.githubusercontent.com/26161015/64409450-7f9d7c80-d0bb-11e9-9901-e0535e435793.png)

Instantiate:
$("[name='my-checkbox']").bootstrapSwitch('state', true);
![image](https://user-images.githubusercontent.com/26161015/64409714-005c7880-d0bc-11e9-8f95-4c4dc96e239b.png)

![image](https://user-images.githubusercontent.com/26161015/64409660-f175c600-d0bb-11e9-96fc-fe3bbb8bb691.png)

The test examples are as follows:

https://github.com/longfeide2008/bootstrap-switch-test/archive/master.zip

**Comment by REJack** [comment]
Try this
```html
            "drawCallback": (function () {
                // 初始化启用禁用按钮
                $('input[name="my-checkbox"]').bootstrapSwitch({
                    'size': 'small',
                    'onColor': 'success',
                    'offColor': 'danger'
                });
                $('input[name="my-checkbox"]:checked').bootstrapSwitch('state', true);
            })
```

This behavior is a bug from bootstrap-switch.

**Comment by longfeide2008** [comment]
> ```
> $('input[name="my-checkbox"]').bootstrapSwitch({
>                     'size': 'small',
>                     'onColor': 'success',
>                     'offColor': 'danger'
>                 });
>                 $('input[name="my-checkbox"]:checked').bootstrapSwitch('state', true);
> ```

Thank you very much.
Will you build some methods into Adminlte? Include bootstrap-switch because these are very basic.

**Comment by REJack** [comment]
I looked over bootstrap-switch it's nice, I'll add this to AdminLTE v3 😄

**Comment by longfeide2008** [comment]
> 我查看了bootstrap-switch，这很好，我将其添加到AdminLTE v3 😄



> 我查看了bootstrap-switch，这很好，我将其添加到AdminLTE v3 😄

Your attitude makes me feel very surprised. I like AdminLte more and more, including your group of lovely developers.
I also hope you can work happily and live seriously!

iCheck:
![image](https://user-images.githubusercontent.com/26161015/64413362-f5a5e180-d0c3-11e9-9bff-6c176c1c6316.png)
There are also these features that I hope you can build into DataTables.

**Comment by REJack** [comment]
You can place literally anything in datatables but it depends on what you want to display. If you want to use icheck-bootstrap you need for any checkbox an unique id.

**Comment by REJack** [comment]
I've added a bootstrap-switch demo in my PR #2256 and created a theme for it.
