### ISSUE TITLE
Problema no user-panel dentro do 'sidebar'

### ISSUE THREAD

**Issue by adrielwramos** [ColorlibHQ/AdminLTE#2257]
```html
<div class="user-panel">
            <div class="pull-left image">
                <img src="../css_js/imagens/avatar5.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p><?php echo $_SESSION['login_nome'] ?></p>
                <a href="#"><i class="fa fa-circle text-primary"></i><b><?php
                        switch ($_SESSION['login_nivel']) {
                            case 1: echo "WebMaster";
                                break;
                            case 2: echo "Admin";
                                break;
                            case 3: echo "Padrão";
                                break;
                        }
                        ?></b>!<br>
                    <span class="fa fa-circle text-success"></span><i style="font-size:10px;">Tempo Restante: <b id="time">30:00</b></i></a>
            </div>
        </div>
```

Abro o Painel e aparece normal, porém passa 2 segundo ele fica de acordo com a imagem 2.
Começou a ocorrer ontem isso, antes estava normal, atualizei a versão do painel e tudo porém não resolvido esse problema.

![img1](https://user-images.githubusercontent.com/26151922/64447372-9c34b700-d0b1-11e9-8c7b-938de0eeb361.png)

Ele joga pra baixo e fica invisivel, da uns 2 segundos após carregar o painel, e acontece isso
![img2](https://user-images.githubusercontent.com/26151922/64447379-a060d480-d0b1-11e9-911d-09551220f18b.png)

Alguem pode me ajudar?

**Comment by REJack** [comment]
Please write your issue in english and please provide a example code of your user-panel.

**Comment by andcarpi** [comment]
Você tem algum javascript rodando nessa página?

**Comment by adrielwramos** [comment]
```html
<div class="user-panel">
            <div class="pull-left image">
                <img src="../css_js/imagens/avatar5.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p><?php echo $_SESSION['login_nome'] ?></p>
                <a href="#"><i class="fa fa-circle text-primary"></i><b><?php
                        switch ($_SESSION['login_nivel']) {
                            case 1: echo "WebMaster";
                                break;
                            case 2: echo "Admin";
                                break;
                            case 3: echo "Padrão";
                                break;
                        }
                        ?></b>!<br>
                    <span class="fa fa-circle text-success"></span><i style="font-size:10px;">Tempo Restante: <b id="time">30:00</b></i></a>
            </div>
        </div>
```

I open the Panel and it appears normal, but 2 seconds later it is in accordance with the image 2.
It started to happen yesterday, before it was normal, I updated the version of the panel and all but not solved this problem.

![img1](https://user-images.githubusercontent.com/26151922/64447372-9c34b700-d0b1-11e9-8c7b-938de0eeb361.png)


He plays down and is invisible, about 2 seconds after loading the panel, and it happens.
![img2](https://user-images.githubusercontent.com/26151922/64447379-a060d480-d0b1-11e9-911d-09551220f18b.png)


Can someone help me?

**Comment by adrielwramos** [comment]
**Você tem algum javascript rodando nessa página?**

Sim
/*! jQuery v3.3.1 | (c) JS Foundation and other contributors | jquery.org/license */
<script src="../css_js/plugins/jquery/jquery.min.js"></script>

Já tentei atualizar para a ultima versão, porém o problema persistiu.

**Comment by adrielwramos** [comment]
**Resolvido**

<div class="pull-left info" **style="position:unset !important"**>
