### ISSUE TITLE
v3 treeview trigger should search for next nav-treeview

### ISSUE THREAD

**Issue by wizhippo** [ColorlibHQ/AdminLTE#2258]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version:  v3
* Operating System:  Linux
* Browser (Version):  Chrome

### Description:
The Treemenu allows setting the 'trigger' but if that element is not the element prior to the child ul it will not work. It naively assumes that the next element is the submenu

This is an issue if you wish to make the menu labels links and the expand arrow be the trigger.

Example:

```
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" data-accordion="true"
    data-trigger=".nav-expand" role="menu">
    <li class="nav-item has-treeview">
        <div>
            <a href="/Training" class="nav-link">
                <i class="nav-sprite"></i>
                Training
            </a>
            <i class="right fas fa-angle-left nav-expand"></i>
        </div>
        <ul class="nav nav-treeview menu_level_1">
            <li></li>
            ...
        </ul>
    </li>
</ul>
```

**Comment by REJack** [comment]
Try to place `<i class="right fas fa-angle-left nav-expand"></i>` inside the `<a>`.

**Comment by wizhippo** [comment]
@REJack that does not work.  Looking at the code you can see why

https://github.com/ColorlibHQ/AdminLTE/blob/v3-dev/build/js/Treeview.js#L91

The `ul` for the submenu has to be the `next` element to the element with the `trigger` class..

**Comment by REJack** [comment]
Try this 
```html
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" data-accordion="true"
    data-trigger=".nav-expand" role="menu">
    <li class="nav-item has-treeview">
        <div>
            <a href="/Training" class="nav-link">
                <i class="nav-sprite"></i>
                Training
            </a>
            <i class="right fas fa-angle-left nav-expand"></i>
            <ul class="nav nav-treeview menu_level_1">
                <li></li>
                ...
            </ul>
        </div>
    </li>
</ul>
```

**Comment by wizhippo** [comment]
That works yes but to get correct styling on the menu item I need the links and the expand element inside the div on their own without the ul.

I can simply fix this in the javascript by test the next element in the parent if the next sibling fails to have `nav-treeview` but was hoping that treeview could support a more flexible menu structure.  Pehaps instead of `next` we can try to `find` the next element with nav-treeview in siblings and if nto found move up the dom until one is found?

**Comment by REJack** [comment]
I've updated the Treeview to use find() instead of next(), you can test it in my PR #2256

**Comment by wizhippo** [comment]
That does allow the target to be outside of the link thank you,
