### ISSUE TITLE
Link styled as button with different text color

### ISSUE THREAD

**Issue by Dasc3er** [ColorlibHQ/AdminLTE#2261]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  v3 RC 1
* Operating System: Windows
* Browser (Version):  Firefox (Latest)

### Description:
When creating a link `<a>` with the class **btn ...**, the color of the text doesn't replicate the defined one for a button `<button>` with the same class attribute.

![immagine](https://user-images.githubusercontent.com/15911489/64476858-76341300-d194-11e9-8d7f-ddf533584b11.png)

HTML code:
```html
    <a class="btn btn-success">
        <i class="fa fa-check"></i> Link
    </a>

    <buttom class="btn btn-success">
        <i class="fa fa-check"></i> Button
    </buttom>
```

**Comment by REJack** [comment]
Thanks for the bug report, I'll check out this bug.

**Comment by REJack** [comment]
I don't know why but you need a `href="*"` in `<a>` then you get the correct result.
