### ISSUE TITLE
active class for Radio Button Group doesn't work

### ISSUE THREAD

**Issue by milkcocoa** [ColorlibHQ/AdminLTE#2264]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:

* AdminLTE Version: 3.0-rc1

### Description:

At the following commit, `box-shadow` for the active button is set `none`, but this property is also used in the active state of radio button group at `label` tag.

https://github.com/ColorlibHQ/AdminLTE/commit/f1f98ba2d89d3786d36a183228a1253a35cc7924#diff-71df22ff86b41e331039a5d6b03135daR367

Now, I cannot see any state changes for these radio buttons.

You can see the description of radio button group is here.

https://getbootstrap.com/docs/4.3/components/buttons/#checkbox-and-radio-buttons

**Comment by REJack** [comment]
I've added a fix for this bug in my PR #2256

**Comment by milkcocoa** [comment]
Thanks for fixing.

**Comment by milkcocoa** [comment]
@REJack Hmm... This issue seems not be fixed at RC 4.

**Comment by milkcocoa** [comment]
The reason why this issue isn't fixed in my environment might be I don't use `bg-*` class with `btn`  class.

**Comment by REJack** [comment]
Please provide a html example of your radio button group. I have no problems in my test setup.

**Comment by milkcocoa** [comment]
Here is a sample, and 'A' has an `active` class, so it should have shadow.

```
<div class="btn-group-toggle">
    <label class="active btn btn-default"><input type="radio" autocomplete="off" class="align-middle" value="A">A</label>
    <label class="btn btn-default"><input type="radio" autocomplete="off" class="align-middle" value="KA">KA</label>
    <label class="btn btn-default"><input type="radio" autocomplete="off" class="align-middle" value="SA">SA</label>
    <label class="btn btn-default"><input type="radio" autocomplete="off" class="align-middle" value="TA">TA</label>
    <label class="btn btn-default"><input type="radio" autocomplete="off" class="align-middle" value="NA">NA</label>
</div>
```
