### ISSUE TITLE
User post broken in the current V3 branch

### ISSUE THREAD

**Issue by DivadNojnarg** [ColorlibHQ/AdminLTE#2265]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0 rc-1 
* Operating System:  OSX
* Browser (Version):  Safari (Latest), Chrome (Latest) 

### Description:

This bug occurs in the [profile](https://adminlte.io/themes/dev/AdminLTE/pages/examples/profile.html) demo page of adminLTE3.

What we should observe:

<img width="1053" alt="Screenshot 2019-09-09 at 16 00 43" src="https://user-images.githubusercontent.com/18291543/64537771-c2f62600-d31b-11e9-95e9-793bcf64c16e.png">

What we actually have:

<img width="1044" alt="Screenshot 2019-09-09 at 15 58 13" src="https://user-images.githubusercontent.com/18291543/64537801-cee1e800-d31b-11e9-9326-e2cb6af00324.png">

```html
<div class="post">
    <div class="user-block">
      <img class="img-circle img-bordered-sm" src="../../dist/img/user1-128x128.jpg" alt=
      "user image" /> <span class="username"><a href="#">Jonathan Burke Jr.</a> <a href=
      "#" class="float-right btn-tool"></a></span> <span class="description">Shared
      publicly - 7:30 PM today</span>
    </div><!-- /.user-block -->

    <p>Lorem ipsum represents a long-held tradition for designers, typographers and the
    like. Some people hate it and argue for its demise, but others ignore the hate as
    they create awesome tools to help create filler text for everyone from bacon lovers
    to Charlie Sheen fans.</p>

    <p><a href="#" class="link-black text-sm mr-2">Share</a> <a href="#" class=
    "link-black text-sm"> Like</a> <span class="float-right"><a href="#" class=
    "link-black text-sm"> Comments (5)</a></span></p><input class=
    "form-control form-control-sm" type="text" placeholder="Type a comment" />
  </div>
```

**Comment by REJack** [comment]
Thanks for the report, I'll check it out in the next days posts with photos bugs also.

**Comment by dlnsk** [comment]
Also on cards at Starter page

**Comment by REJack** [comment]
I've added a fix for this issue and also for the card-text issue in my PR #2256

**Comment by DivadNojnarg** [comment]
thanks!
