### ISSUE TITLE
Are any scss gone?

### ISSUE THREAD

**Issue by dlnsk** [ColorlibHQ/AdminLTE#2270]
### Issue type:
- [x] Bug report

### Environment:
* AdminLTE Version:  3.0.0-rc.1
* Operating System:  Linux
* Browser (Version):  Chromium (Latest)

SCSS files _badge.scss and _navbar.scss are gone. There are styles in compiled css version and links in .css.map but in scss folder no files and no styles.

Styles which has disappear:
.navbar-expand .navbar-nav .nav-link {
    padding-right: 1rem;
    padding-left: 1rem;
}
![image](https://user-images.githubusercontent.com/332778/64753715-72b2da00-d54e-11e9-94a9-045b82960c0a.png) Here padding is 0.5
.badge-info {
    color: #fff;
    background-color: #17a2b8;
}
![image](https://user-images.githubusercontent.com/332778/64753748-9118d580-d54e-11e9-8bf3-de6741362d2b.png)

**Comment by REJack** [comment]
The SCSS files _badge & _navbar comes from the bootstrap node_module, AdminLTE itself has no overrides for this so we use exact the style from bootstrap.

**Comment by dlnsk** [comment]
But why screenshots look different to https://adminlte.io/themes/dev/AdminLTE/index.html (padding and text color)?

**Comment by REJack** [comment]
> I imported bootstrap 4.3.1 from scss...

Do you compile AdminLTE from your self?

**Comment by dlnsk** [comment]
> Where the screenshots from, they are from the online demo?

This is local development.

> Do you compile AdminLTE by your self?

Yes. I use Laravel 6.
AdminLTE and Bootstrap 4.3.1 have imported form sources and compiled using webpack (configuration comes with laravel)

**Comment by REJack** [comment]
>  AdminLTE and Bootstrap 4.3.1 have imported form sources and compiled using webpack (configuration comes with laravel)

Which scss files you use for compiling this, AdminLTE.scss or AdminLTE-raw.scss?

**Comment by dlnsk** [comment]
> Which scss files you use for compiling this, AdminLTE.scss or AdminLTE-raw.scss?

No differences.

> Since Bootstrap 4, it's important to use an autoprefixer after compile (before minifing), if you compile it by yourself.

I'll try to test. This is very strange because $cyan is #6cb2eb instead of #17a2b8a and I don't understand why, yet...
So, this is local compilation bug.

**Comment by dlnsk** [comment]
Found. Sorry!
