### ISSUE TITLE
How to control sidebar according screen size (Desktop and iPad)

### ISSUE THREAD

**Issue by dmiepub** [ColorlibHQ/AdminLTE#2271]
I want to display the normal sidebar on the medium and big screen size device (laptop, desktop >1024) and sidebar collapse on small screen size device (like iPad, tablets etc <=1024)

**Comment by REJack** [comment]
For which AdminLTE version?

**Comment by dmiepub** [comment]
I am using latest version AdminLTE-3.0.0-rc.1

**Comment by dmiepub** [comment]
> For which AdminLTE version?

I am using latest version AdminLTE-3.0.0-rc.1

**Comment by REJack** [comment]
Ok, it's quite easy you need only to add ` data-auto-collapse-size="1024"` on `data-widget="pushmenu"` this collapse the sidebar if the size is equal or less, you can also add `.sidebar-mini-md` beside `.sidebar-mini` to stay with the mini sidebar till 768px, without `.sidebar-mini-md` the mini sidebar stay till 992px.

**Comment by dmiepub** [comment]
> Ok, it's quite easy you need only to add ` data-auto-collapse-size="1024"` on `data-widget="pushmenu"` this collapse the sidebar if the size is equal or less, you can also add `.sidebar-mini-md` beside `.sidebar-mini` to stay with the mini sidebar till 768px, without `.sidebar-mini-md` the mini sidebar stay till 992px.

I have changed `.sidebar-mini`to `.sidebar-mini-md`but still normal sidebar is displaying on ipas.
![Screenshot 2019-09-13 at 4 48 11 PM](https://user-images.githubusercontent.com/6203084/64858960-82ade500-d646-11e9-8600-60f42479e799.png)

**Comment by REJack** [comment]
Change body to `<body class="hold-transition sidebar-mini sidebar-mini-md layout-fixed">` and you need to add `data-auto-collapse-size="1024"` on `data-widget="pushmenu"` this collapse the sidebar.

**Comment by dmiepub** [comment]
> Change body to `<body class="hold-transition sidebar-mini sidebar-mini-md layout-fixed">` and you need to add `data-auto-collapse-size="1024"` on `data-widget="pushmenu"` this collapse the sidebar.
> 
> Like this `<a class="nav-link" data-widget="pushmenu" data-auto-collapse-size="1024" href="#"><i class="fas fa-bars"></i></a>`

Thanks, buddy... It is working now.
![Screenshot 2019-09-13 at 5 08 46 PM](https://user-images.githubusercontent.com/6203084/64859904-2b5d4400-d649-11e9-9e73-b4efde81cd24.png)

**Comment by REJack** [comment]
No problem, I'll close this issue.
