### ISSUE TITLE
BSTooltip problem

### ISSUE THREAD

**Issue by emregulerr** [ColorlibHQ/AdminLTE#2272]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.18
* Operating System:  
* Browser (Version):  Chrome (Latest)

### Description:

I'm trying to use bootstrap tooltips. I've added `data-toggle="tooltip"` to the element. But when I hover to the element, nothing happens. When I initialize the tooltips with `$('[data-toggle="tooltip"]').tooltip();` and hover to the element again, this time no text is showing up. But this time a white space (a new white row) is adding to the end of page. I've tried `data-container="body"` too but nothing was changed.

**Comment by emregulerr** [comment]
I noticed something. when I hover to the element (when using `$('[data-toggle="tooltip"]').tooltip();` );  I saw the title as plain text and misplaced (at the left of page but vertically aligned with the element) also white row is still appearing at the end of the page

**Comment by REJack** [comment]
I can't reproduce this bug, can you provide a code example?

You always need to init the tooltip, if you add it to a element via js or create a new element with tooltip via js.

**Comment by emregulerr** [comment]
I'm using data-* attributes for tooltip.

`<a href="#" class="btn btn-primary pull-right" data-toggle="tooltip" title="This is a reaaaaally reaaaaally long title for tooltip test!">Hover over me for tooltip testing</a>`

and init like that;

`<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>`

and my CSS & JS includes with screenshots are in attached files

![js](https://user-images.githubusercontent.com/22560050/64905219-aec87500-d6dd-11e9-8c1b-c91904cb8307.png)
![css](https://user-images.githubusercontent.com/22560050/64905222-aec87500-d6dd-11e9-92ea-fad505fc7067.png)
![ss](https://user-images.githubusercontent.com/22560050/64905221-aec87500-d6dd-11e9-9007-99e87296e0e6.png)

**Comment by REJack** [comment]
The button markup is correct, if I place this in a AdminLTE v2 project it works correctly may it collides with any plugin. 

I looked over the index demo and may you need a widget bridge like in the demo, the script load looks like this:
```html
<!-- jQuery 3 -->
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="bower_components/raphael/raphael.min.js"></script>
<script src="bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="bower_components/moment/min/moment.min.js"></script>
<script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>
```

**Comment by emregulerr** [comment]
Nope, it's not working. I've already tried
