### ISSUE TITLE
flat-nav issues

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2273]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version:   3.0.0 rc1 PR #2256 
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:
While adding flat menu style via [This comment](https://github.com/ColorlibHQ/AdminLTE/issues/2252#issuecomment-531116119) , scrollbar has appeared as below screenshoot.

![Capture](https://user-images.githubusercontent.com/5186970/64910686-1c58bd80-d73f-11e9-8e71-8c6c4b4fd9e0.PNG)

This is fine if putting `layout-fixed` class on body but without it or others(such as `layout-navbar-fixed`) , the scrollbar will appear. 

Another one , while clicking on `data-widget="pushmenu"` , menu items are not aligned at center. Please check on below image.

![Capture2](https://user-images.githubusercontent.com/5186970/64911210-9a6b9300-d744-11e9-97b5-249b0bc36fa5.PNG)

**Comment by REJack** [comment]
Thanks for report, I found the bug and fix it soon ;) and I'll also fix the margins while collapsed sidebar.

**Comment by REJack** [comment]
I've fixed the scrollbar bug in my PR, but I need to fix the margins later 😄

**Comment by REJack** [comment]
I've fixed the margin bugs in my PR
