### ISSUE TITLE
How to Increase the width of Modal in AdminLTE

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2274]
### Issue type:
- [ ] Feature request  Requesting the implementation of a new feature 

### Environment:
* AdminLTE Version: : 2.4.15
* Operating System:  : Windows
* Browser (Version):  Chrome

### Description:

I am using this modal, but the width size is small and it doe increase as I add content. How do I increase the width size.

`

        <div class="modal fade" id="modal-default">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Default Modal</h4>
              </div>
              <div class="modal-body">
                <p>One fine body&hellip;</p>
              </div>
              
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
            
          </div>
          
        </div>
        
`

**Comment by REJack** [comment]
For this checkout the bootstrap docs, https://getbootstrap.com/docs/3.4/javascript/#modals-sizes
