### ISSUE TITLE
Your project involves the issue of China's sovereignty. I hope you can correct it

### ISSUE THREAD

**Issue by echo9dian** [ColorlibHQ/AdminLTE#2275]
In Dashboard v2, Taiwan and diaoyu island are not marked as China in the map. Please correct it as soon as possible or I will report it

**Comment by REJack** [comment]
In which AdminLTE version? 
Please provide a screenshot.

**Comment by echo9dian** [comment]
![China](https://user-images.githubusercontent.com/39938997/64960075-17257b00-d8c5-11e9-8745-cf12ca564313.png)

**Comment by REJack** [comment]
Sadly this deliverd by jQuery Mapael, I can't change the map itself but I'll change it to a US map it's only a demo for card content.

**Comment by echo9dian** [comment]
Please amend it. China's territory is inviolable.

**Comment by REJack** [comment]
I've updated the map in my PR #2256, the online demo will updated with the next release.

**Comment by echo9dian** [comment]
thanks 

> 我在PR [＃2256中](https://github.com/ColorlibHQ/AdminLTE/pull/2256)更新了地图，在线演示将在下一个版本中更新。
