### ISSUE TITLE
treeview no working submenu

### ISSUE THREAD

**Issue by Markuz1995** [ColorlibHQ/AdminLTE#2276]
The treeview for the side menu does not work, where you can see the submenus, I am working with angular loading the file /dist/js/adminlte.js.

When entering from the login the treeview does not work, but when reloading the page it already works.
Can you guide me how to solve this please

**Comment by REJack** [comment]
Which AdminLTE version you use? 
You need to init the treeview after entering via login.

**Comment by Markuz1995** [comment]
Hi, I'm using the AdminLTE-3.0.0-rc.1 version,

I have a login component and another dashboard component, when you log in, open the dashboard component,

Hi, I'm using the AdminLTE-3.0.0-rc.1 version, and the angular 8 version

I have a login component and another dashboard component, when you log in, open the dashboard component,

so I am loading the scripts in the angular.json file

"src / assets / js / index.js",
"src / assets / plugins / jquery / jquery.min.js",
"src / assets / plugins / jquery-ui / jquery-ui.min.js", "src / assets / plugins / bootstrap / js / bootstrap.bundle.min.js",
"src / assets / plugins / chart.js / Chart.min.js",
"src / assets / plugins / jquery-knob / jquery.knob.min.js",
"src / assets / plugins / moment / moment.min.js", "src / assets / plugins / daterangepicker / daterangepicker.js",
"src / assets / plugins / tempusdominus-bootstrap-4 / js / tempusdominus-bootstrap-4.min.js",
"src / assets / plugins / summernote / summernote-bs4.min.js", "src / assets / plugins / overlayScrollbars / js / jquery.overlayScrollbars.min.js",
"src / assets / dist / js / adminlte.js",
"src / assets / dist / js / pages / dashboard.js",
"src / assets / dist / js / demo.js"

In the dashboard.component.ts component where I have the template should I load something like this into the ngOnInit method?

ngOnInit () {
   
    $ (document) .ready (() => {
      const trees: any = $ ('[data-widget = "treeview"]');
      trees.Treeview();
    });
 }

I appreciate your understanding and help I am just starting with angular and I want to be able to work with this template, thank you very much

**Comment by REJack** [comment]
ngOnInit looks good, do you recieve any console error?

**Comment by zhenxingshan** [comment]
I use the version 3.0.0-beta.2
use `  $('[data-widget="treeview"]').Treeview('init') `

**Comment by Markuz1995** [comment]
@REJack @zhenxingshan 

Hello, I would like to thank you for your help, the following code worked perfectly for me 
$('[data-widget="treeview"]').Treeview('init') in ngOnInit()

**Comment by jpnobrega** [comment]
it's closed but, can be useful for someone. 
Im loading the submenus dynamically, i fix this using:

```
//path of your adminlte.js
import * as adminlte from '@assets/js/adminlte.js';

ngOnInit() {
    adminlte.Treeview('init');
}
```

**Comment by Thalinda** [comment]
> 
> 
> I use the version 3.0.0-beta.2
> use ` $('[data-widget="treeview"]').Treeview('init')`

Thank you very much this is worked using electron js without any other frameworks like vue, angular, react

**Comment by LuisFernandoAyalaValverde** [comment]
When use -> $('[data-widget="treeview"]').Treeview('init'); 
After reload the page with Angular, the 3rd level menu **overlap** adminlte 3.

**Comment by REJack** [comment]
> When use -> $('[data-widget="treeview"]').Treeview('init'); After reload the page with Angular, the 3rd level menu **overlap** adminlte 3.

If your level 3+ menu overlaps with level 2, then check and update your jQuery version that causes it.
