### ISSUE TITLE
control-label is not valid class for forms

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2277]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  3.0.0 rc1
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:

I think `control-label` class is not a valid style class for form labels in Bootstrap 4. It should replace with `col-form-label` class at **Forms > General Elements > Horizontal Form** . This style class will change vertical align to center. Thanks.

**Comment by REJack** [comment]
Thanks for the report, I've fixed it in my PR #2256.
