### ISSUE TITLE
dropdown-toggle style not align center due to margin-left attribute

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2278]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version: 3.0.0 rc1
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest) 

### Description:

Hello bro ! I think you should remove `margin-left` attribute of css style class `.dropdown-toggle::after` because it is not aligned at center. It is more obvious with `btn-sm` class.
Please check below image. Thanks ..

![Capture](https://user-images.githubusercontent.com/5186970/65019718-c4de6b80-d951-11e9-8f80-61c0a68dfe2a.PNG)

### Question

I would like to show dropdown menu as appended button style for split buttons _(starting from let 0)_ . What should I do ?
![Capture](https://user-images.githubusercontent.com/5186970/65019916-2c94b680-d952-11e9-9e1d-47ae1f9aaa51.PNG)

![Capture](https://user-images.githubusercontent.com/5186970/65020093-75e50600-d952-11e9-8981-0d8596b1fd50.PNG)

**Comment by REJack** [comment]
I've created a extra class for icon only dropdown-toggles `.dropdown-icon` to fix this margin bug.

> I would like to show dropdown menu as appended button style for split buttons (starting from let 0) . What should I do ?

What you mean with this, you want to append a split button?

**Comment by REJack** [comment]
fix/add is commited in my PR #2256

**Comment by cataclysmuprising** [comment]
> What you mean with this, you want to append a split button?

Hello bro ! Please check the first image (Appended Button), dropdown menu was appeared at position `left : 0`; . But at second image (split button) , dropdown menu was appeared starting from under dropdown toggler. I would like to use split button component but I wish to appear dropdown menu from position `left : 0`. Below is the image that I would like to achieve.
![Capture](https://user-images.githubusercontent.com/5186970/65028587-4b02ae00-d962-11e9-830a-1e71cafdf6d7.PNG)

**Comment by cataclysmuprising** [comment]
Another , I putted dropdown menu at last `<td>` element of a table and it exceeds the browser window.
Please check on below image.
![Capture](https://user-images.githubusercontent.com/5186970/65028849-bb113400-d962-11e9-9531-ff962b8d47ba.PNG)

**Comment by REJack** [comment]
Oh that a normal behavior from bootstrap 4 and I don't know if it's fix able, for your table problem add `.dropdown-menu-right` beside `.dropdown-menu`.
