### ISSUE TITLE
Nav-Tab Styles

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2280]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  version 3.0.0 rc.1
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:

1. Right Sided (nav-tabs-right) example at **UI Elements > Navbar & Tabs** page shows wrong tab content.

2. While hovering on adjacent nav link of active link , border style is overlapped. Please check on below image. I think this is Bootstrap 4's default style but I'm just requesting you to change something more cool ...

![Capture](https://user-images.githubusercontent.com/5186970/65111306-843e2b00-da01-11e9-8785-9b23a758e3e7.PNG)

I think hovering nav link styles should be with background color instead of border style _(just a suggestion :D )_. 

3. `tab-pane` should have some margin top values as I think.

![Capture](https://user-images.githubusercontent.com/5186970/65111573-9a002000-da02-11e9-955a-a392d08f6bc7.PNG)

4. I'd like to get nav tabs as a particular panel or widget like vesion 2's. 

![Capture](https://user-images.githubusercontent.com/5186970/65111827-77223b80-da03-11e9-82fc-b21e2babd21b.PNG)

Because , when put inside `card-body` and it is not looking good. Please check below image.

![Capture](https://user-images.githubusercontent.com/5186970/65111946-d4b68800-da03-11e9-95cc-f4b8ac97b672.PNG)

**Comment by cataclysmuprising** [comment]
For case (4). I can use `nav-pills` as [Bootstrap's nav component page](https://getbootstrap.com/docs/4.0/components/navs/)

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll check this later out.

**Comment by REJack** [comment]
1. fixed
2. I've reworked the border style, the right border should not be displayed so it looks like it comes out under the nav tabs border also the border radius was not correct.

> I think hovering nav link styles should be with background color instead of border style (just a suggestion :D ).

That's the default nav tabs layout, bootstrap also comes with nav pills with background instead of border 😄 

3. Thats also the default from nav tabs by bootstrap, you can add `.mb-2` to `.tab-pane`

4. I will look to create a support for nav tabs in card header.

**Comment by REJack** [comment]
I've added a support for nav tabs in card header (3 variants) and reworked the navbar demo 😄.

![nav tabs in header demo pic](https://user-images.githubusercontent.com/1554582/65313605-eaa78280-db94-11e9-882e-4164f0fbf67d.png)

**Comment by cataclysmuprising** [comment]
Wow ! That looks awesome.. Great work bro. Thanks !
