### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kinkod** [ColorlibHQ/AdminLTE#2281]
1. Please make a setting/body class to enable/disable dropshadows (mainly on sidebar).
2. Please make a navbar theme that is full gray/silver like the white theme for AdminLTE2. I am sure a lot of people like the clean silver look.

**Comment by REJack** [comment]
> Please make a setting/body class to enable/disable dropshadows (mainly on sidebar).

I guess you mean the shadow from the sidebar over the content, if yes remove `.elevation-4` from `.main-sidebar` if not please provide a screenshot 😄.

> Please make a navbar theme that is full gray/silver like the white theme for AdminLTE2. I am sure a lot of people like the clean silver look.

Try to remove `.navbar-white` and leave only `.navbar-light`.
