### ISSUE TITLE
Plugins not work using npm 

### ISSUE THREAD

**Issue by rarangels** [ColorlibHQ/AdminLTE#2282]
### Issue type:
- [] Feature request 
- [] Bug report       
- [] Documentation   

### Environment:
* AdminLTE Version: 3.0.0-rc.1 
* Operating System: Linux Ubuntu 
* Browser (Version): Google chrome Versión 77.0.3865.75 (Build oficial) (64 bits)
 

### Description:

In Laravel with npm, I am importing AdminLTE as follows:

> require ('admin-lte');

It works "well" adminLTE but when making use of the plugins (inputmask, fullcalendar, among others), does not recognize them. I am doing the following test from js console:

> $ ('[data-mask]').inputmask();

With result:

> Uncaught TypeError: $(...).inputmask is not a function at <anonymous>:1:18

What I can do?
I need to configure something so that the plugins with npm import work?

Upgrade: 

Make a copy of the file "admin-lte/plugins/inputmask/min/jquery.inputmask.bundle.min.js" to the public folder and import it with::

> <script src="{{ url('js/plugins/jquery.inputmask.bundle.min.js') }}"></script>

And work:

 $ ('[data-mask]').inputmask();

But the following message appears in the js console:

> jquery.inputmask.bundle.min.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by REJack** [comment]
If you need a plugin in AdminLTE then you need to load/add them by yourself, AdminLTE doesn't load automaticly plugins . 


> jquery.inputmask.bundle.min.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

This error comes from inputmask itself, see https://github.com/RobinHerbots/Inputmask /issues/2185

**Comment by rarangels** [comment]
> If you need a plugin in AdminLTE then you need to load/add them by yourself, AdminLTE doesn't load automaticly plugins .
> (https://github.com/RobinHerbots/Inputmask/issues/2185)

In the documentation, they should add information indicating this, to avoid confusion.

**Comment by REJack** [comment]
What exaclty you mean to add in docs, the error from inputmask or that the user need to load the plugins by yourself?

**Comment by rarangels** [comment]
Advertise in the documentation that the user needs to add the import of the different plugins. This is why in the live preview, they show the functional plugin.

In my case it was a bit confusing, but it was already solved by importing. However I would not have noticed without the previous comment.

In another case it is the inputmask error that you already show me that was reported in the github.

**Comment by REJack** [comment]
> Advertise in the documentation that the user needs to add the import of the different plugins. This is why in the live preview, they show the functional plugin.

We have already a advertise in the docs at the "Dependencies & Plugins" Section

> Note! You need to load the js/css files of the plugin that you want to use. AdminLTE doesn’t load automatically all plugins, this would cause huge load times on every page load.
