### ISSUE TITLE
Can't overide with `rounded-0` to `input-group-text`

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2284]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version:  3.0.0 rc1
* Operating System:  Window 10
* Browser (Version):  Firefox (Latest)

### Description:

I wish flat style input boxes at Login page but I can't set `input-group-text` with `rounded-0` class due to un-overridable border radius style.

![Capture](https://user-images.githubusercontent.com/5186970/65300578-ecc01000-db99-11e9-9cd2-5e7484e4550e.PNG)

**Comment by REJack** [comment]
This is already fixed in my PR #2256 with cac5828 😄 I like also the flat inputs too.
