### ISSUE TITLE
Tab Custom Content Example

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2285]
### Issue type:
- [ ] Feature request 

### Description:
If someone using Tab custom content example in header there should be one more class for following style:

`.nav-tabs .nav-link:first-child {
    border-left-color: transparent !important;
    border-top-left-radius: 0 !important;
}`

So Its look like this
![image](https://user-images.githubusercontent.com/29248598/65368606-0710f100-dc61-11e9-9819-a82209c13602.png)

**Comment by REJack** [comment]
Is this based on my PR #2256 fork?

**Comment by REJack** [comment]
If yes, I've added a fix for this download & compile it again 😄 

I've added also a abilty to change the accent color (link & pagination) this works also for nav-tabs.

**Comment by deepak458** [comment]
> Is this based on my PR #2256 fork?

Yes

Also Can you please confirm when you are releasing next version. and don't forgot to fix your builtin Toastr, i have cloned your project for testing and want to see some fix. in your ongoing project Toastr not working properly.

**Comment by REJack** [comment]
You mean Toasts (own plugin) or Toastr (external plugin)?
If you mean Toasts what is exactly not working, please create a new issue with your bug reports.

For release infos, I've created a milestone ([v3.0.0-rc.2](https://github.com/ColorlibHQ/AdminLTE/milestone/4)) with an due date for _1. Okt '19_, I've created also a milestone for the stable release.
