### ISSUE TITLE
100vh in body and html instead of 100%

### ISSUE THREAD

**Issue by erickxs** [ColorlibHQ/AdminLTE#2286]
[ ] Feature request

Would not it be better to handle these values ​​with 100vh to accommodate for example the .login-box to the center of the screen?

AdminLTE 3.0.0-rc.1

**Comment by REJack** [comment]
I can't override without a additional html class the html min-height value and if I only change body min-height to 100vh, but this will still not center it correct.

Even with display flex it will cause bugs, the box will not displayed correctly on mobile.

The only way to get a 100% centered box is to create a javascript that corrects the centering.

**Comment by erickxs** [comment]
Thanks for responding, if in fact what I did was add some javascript to center it, although as the script of adminlte.js modifies the height I have to do it with a timeout and it moves somewhat abruptly when applied, finally I can continue working just as you have developed it!

**Comment by REJack** [comment]
I've enhanced the position with flex and a addtional script in Layout.js in my PR #2256.

**Comment by erickxs** [comment]
Nice! let me know when I can download that version please! Thanks in advance.

**Comment by REJack** [comment]
That's a bit complicated you need nodejs/npm on your machine and then fork my PR branch lastly you need to compile the dist files via `npm run production`, I compile only my changes before merging 😄.

**Comment by REJack** [comment]
I will release v3.0.0-rc.2 on 1. Okt '19 with this fix.

**Comment by erickxs** [comment]
@REJack Nice thank you!
