### ISSUE TITLE
select2 color variants

### ISSUE THREAD

**Issue by topjor** [ColorlibHQ/AdminLTE#2287]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4
* Operating System:  N/A
* Browser (Version):  N/A

### Description:
I would like to request the addition of colored versions of the select2 plugin that match the different admin-lte skins. This way it is possible to have one nice matched color scheme / accent color as select2 currently is styled only with a blue variant.
I have not checked all, but I know some other form extensions already have colored versions and this would be a nice addition to making a more coherent experience for end-users.

**Comment by REJack** [comment]
I've checked the v2.4.18, the blue color is the primary color from AdminLTE same as other inputs.

**Comment by topjor** [comment]
Maybe it would be nice to have this option in the future, for both the plugins as well as the normal form styling. (I do not follow the v3 development but it might also be nice there, I did saw there is a lot more customization in terms of colors.)

I might try and style select2 myself sometime but I do not know if I will have the time soon to do that.

**Comment by REJack** [comment]
I've added color variations for select2 elements in my v3 PR #2256, but it changes only the focus/hover colors.

**Comment by topjor** [comment]
Nice.
Question, does this also apply to the selected items color when using multi-value/select?

**Comment by REJack** [comment]
Yep, you can check it out at the [v3 demo](https://adminlte.io/themes/dev/AdminLTE/pages/forms/advanced.html).
