### ISSUE TITLE
[question] change sidebar toggling behaviour

### ISSUE THREAD

**Issue by Wqrld** [ColorlibHQ/AdminLTE#2288]
Hi, when i try to toggle the sidebar with `<button class="btn sidebar-toggle-btn btn-primary" data-toggle="push-menu">Toggle Sidebar</button>`

After clicking it once the `sidebar-mini-expand-feature` class shows up on the body but that doesnt change after you click it again and nothing happens to the sidebar.

I am using `skin-blue fixed sidebar-mini` as base classes for the body.

Is there a way to either fix this so it gets a `sidebar-collapse` instead?

Or even better just default to sidebar-collapse when on mobile instead of fully hiding the sidebar.

**Comment by REJack** [comment]
Which AdminLTE version you use?
On which screen size does this bug appears?

**Comment by Wqrld** [comment]
im running 2.4.0.

the sidebar just slides away right after going below 767(width)x869

**Comment by Wqrld** [comment]
i think its the 767 referenced here: https://github.com/ColorlibHQ/AdminLTE/blob/e38376ec15f956b281065e0c7bf9c1767a077b62/build/js/PushMenu.js#L15

**Comment by Wqrld** [comment]
preferably i would like it to be small and turn to the normal size on hover on mobile.

**Comment by REJack** [comment]
You can change this value with adding `data-collapse-screen-size="x"` (x is your definied value) to you pushmenu-button.

**Comment by Wqrld** [comment]
the button that is needed according to the docs doesn't work and i dont want to change that value, i want to have a working button.
