### ISSUE TITLE
admin lte theme is not working in mvc 5 asp.net c#

### ISSUE THREAD

**Issue by rajeshpaliwal** [ColorlibHQ/AdminLTE#2289]
**Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Module '"C:/Users/Rajesh/source/repos/WebApplication4/Content/AdminLTE-3.0.0-rc.1/plugins/filterizr/ActiveFilter"' has no exported member 'Filter'.	WebApplication4	C:\Users\Rajesh\source\repos\WebApplication4\Content\AdminLTE-3.0.0-rc.1\plugins\filterizr\Filterizr.d.ts	4	

**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Module '"C:/Users/Rajesh/source/repos/WebApplication4/Content/AdminLTE-3.0.0-rc.1/plugins/filterizr/FilterizrOptions/defaultOptions"' has no exported member 'RawOptions'.	WebApplication4	C:\Users\Rajesh\source\repos\WebApplication4\Content\AdminLTE-3.0.0-rc.1\plugins\filterizr\Filterizr.d.ts	5	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Module '"C:/Users/Rajesh/source/repos/WebApplication4/Content/AdminLTE-3.0.0-rc.1/plugins/filterizr/FilterizrOptions/defaultOptions"' has no exported member 'RawOptionsCallbacks'.	WebApplication4	C:\Users\Rajesh\source\repos\WebApplication4\Content\AdminLTE-3.0.0-rc.1\plugins\filterizr\FilterContainer.d.ts	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Cannot find name 'Parameters'.	WebApplication4	C:\Users\Rajesh\source\repos\WebApplication4\Content\AdminLTE-3.0.0-rc.1\plugins\fullcalendar\main.d.ts	136

**Comment by REJack** [comment]
Your error looks like your use AdminLTE in TypeScript and I guess you converted the js files to ts files, if I guess right you need to manually update them. 
AdminLTE doesn't support TypeScript right now.

**Comment by nickdavidbhs** [comment]
Sorry but converting the ts files to js worked for you? i'm having the same problem, literally just downloaded the template, implemented at asp.net core layout and got the same error
