### ISSUE TITLE
【Emergency】sidebar dosen't have  correct adminlte css

### ISSUE THREAD

**Issue by coderMmw** [ColorlibHQ/AdminLTE#2291]
### Description:

sidebar dosen't have  Correct adminlte css

![image](https://user-images.githubusercontent.com/40792126/65737418-0a98f200-e111-11e9-9fa7-032064955c5f.png)

it's dynamically generated elements

The page on display is new_index.html path : newadmin/new_index.html
here is code  
[newadmin.zip](https://github.com/ColorlibHQ/AdminLTE/files/3660605/newadmin.zip)

another static page  is correct; The page on display is new_index3.html path : newadmin/new_index3.html
![image](https://user-images.githubusercontent.com/40792126/65739275-3fa84300-e117-11e9-929f-421775d1ba25.png)

**Comment by REJack** [comment]
You need to load the overlayScrollbars & adminlte js files to get a correct layout fixed behavior

**Comment by coderMmw** [comment]
> You need to load the overlayScrollbars & adminlte js files to get a correct layout fixed behavior

I loaded both ,but it's ineffective；
![image](https://user-images.githubusercontent.com/40792126/65744702-b64f3b80-e12b-11e9-8b1c-f99116458714.png)

**Comment by REJack** [comment]
I see you load it via requirejs, I don't know why but jquery's default dom ready doesn't work with this, you can change the adminlte require with something like this, it can happen that you need to load other plugins too if in use.
```js
require(["adminlte"], function() {
$(document).Layout();
});
```

**Comment by coderMmw** [comment]
> I see you load it via requirejs, I don't know why but jquery's default dom ready doesn't work with this, you can change the adminlte require with something like this, it can happen that you need to load other plugins too if in use.
> 
> ```js
> require(["adminlte"], function() {
> $(document).Layout();
> });
> ```
i want to build  a SPA ，so choose requirejs to manage it;

is it because of the loading order of JS

**Comment by REJack** [comment]
The order of the js looks correct.

**Comment by coderMmw** [comment]
> The order of the js looks correct.
![image](https://user-images.githubusercontent.com/40792126/65749116-164bdf00-e138-11e9-8cc1-9560b74423fc.png)

when i click the sidebar menu of another page（new_index3.html） without requirejs, it load treeview.js and this function is implemented  ,but this page(new_index.html) dosen't load treeview.js 

how or where  can i load treeview.js

**Comment by REJack** [comment]
You can find the Treeview.js in build/js/, you can also load the build/js/AdminLTE.js it imports/requires the Treeview.js.

**Comment by coderMmw** [comment]
> You can find the Treeview.js in build/js/, you can also load the build/js/AdminLTE.js it imports/requires the Treeview.js.

eh，If I load it directly like this 
![image](https://user-images.githubusercontent.com/40792126/65826264-651e8380-e2b4-11e9-8f7d-5e3b9bc12451.png)

It makes an error 
![image](https://user-images.githubusercontent.com/40792126/65826313-132a2d80-e2b5-11e9-9ca4-1ff27c45bccb.png)

**Comment by coderMmw** [comment]
I have solved this problem ，I reinitialized this ‘treeview‘ manually ，it works.

**Comment by gotounix** [comment]
> 
> 
> I have solved this problem ，I reinitialized this ‘treeview‘ manually ，it works.

I have the same problems, how to reinitialized this ‘treeview‘ manually? Thanks.

**Comment by coderMmw** [comment]
> > I have solved this problem ，I reinitialized this ‘treeview‘ manually ，it works.
> 
> I have the same problems, how to reinitialized this ‘treeview‘ manually? Thanks.

Two lines of code；
        //Reset scrollbar
	 $('body').Layout('fixLayoutHeight');
	//Reinitialize the tree in the sidebar
	$('ul').Treeview("init");

**Comment by gotounix** [comment]
@coderMmw Thanks. I use the two lines fixed this problem, but while using ``$('body').Layout('fixLayoutHeight');`` the ``content`` will have scrollbar, do you have this problem?

**Comment by coderMmw** [comment]
if you don't want "scrollbar", just don't use it.&nbsp;



---Original---

**Comment by gotounix** [comment]
@coderMmw Thanks for you reply.
I mean these fixed left scrollbar, but in right content area will display a scrollbar while the content is not enough for scrolling.

**Comment by REJack** [comment]
@gotounix Which AdminLTE version you use (lower than v3.0.0-rc.5)? This bug should fixed with v3.0.0-rc.5.

**Comment by gotounix** [comment]
@REJack Thanks. I used rc3, updated to rc.5 fixed it.

**Comment by kn-id** [comment]
this fixed my problem when using using requirejs and treeview not working:

```js
require(['jquery', 'adminlte'], function($) {
    if(document.readyState == 'complete') {
        $(window).trigger('load');
    }
});
```
sometimes `window.load` event triggered before the anonymous function
