### ISSUE TITLE
菜单路径的问题，怎么改成重新加载路径，

### ISSUE THREAD

**Issue by libao199739** [ColorlibHQ/AdminLTE#2292]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by REJack** [comment]
Please write your issue in english.

**Comment by cataclysmuprising** [comment]
A cat on keyboard :D

**Comment by REJack** [comment]
Can this issue closed?

**Comment by firstrose** [comment]
> Please write your issue in english.

Sorry for the Chinese question from my countryman.

He wrote "Question about menu's path(url?): How to reload(change?) menu's path(url?) (after page load?)"

I am not very sure his meaning, since I am a newbie for your project. In brackets are my guess.

**Comment by firstrose** [comment]
> A cat on keyboard :D

a mad monkey :)

**Comment by REJack** [comment]
@firstrose Thanks for the translations :) could you ask him for more details? I need to know which AdminLTE Version & what he excatly want to accomplish.

If he want to auto active sidebar nav items on page load for AdminLTE v2, here is a script https://github.com/ColorlibHQ/AdminLTE/issues/1806#issuecomment-362635514.

**Comment by firstrose** [comment]
@libao199739 

请问你用的AdminLTE是哪个版本？另外，我不是很明白你的问题。你是不是想问，页面加载完成以后，要动态修改左边的菜单里，某些菜单项对应的url（就是点击菜单后转向的url）？或者你是想问，有没有办法单独把左边的菜单栏重新刷新（刷新后可能是完全不同的另外一套菜单了）？如果不是，麻烦你用尽可能清晰精确的语言重述一下你的问题。谢谢。

另外， #1806 描述了一个和菜单有关的bug，你看看是不是你想问的。
