### ISSUE TITLE
No responsive navbar in top navigation layout

### ISSUE THREAD

**Issue by RobFijneman** [ColorlibHQ/AdminLTE#2293]
* Bug report
* AdminLTE Version:  V3
* Operating System:  Windows
* Browser (Version):  Chrome (Latest)
* URL: https://adminlte.io/themes/dev/AdminLTE/pages/layout/top-nav.html

If you click on the above link and make your browser smaller, you can see that the menu text (Home, Contact and Dropdown) are going into te logo. Maybe add a menu button so it pops down or from the side?

**Comment by REJack** [comment]
I've updated the top-nav layout in my fork and push the changes soon to the repo.

**Comment by REJack** [comment]
This change is released with v3.0.0-rc.4.
