### ISSUE TITLE
There is no jquery validation in Form element section.

### ISSUE THREAD

**Issue by ankitkanojia** [ColorlibHQ/AdminLTE#2294]
There is no jQuery form validation available, can anyone provide that jQuery validation so that everyone can aware with validation with form elements.

**Comment by REJack** [comment]
I've added jquery-validation in v3 but without any demo, coming with the next release (rc.5).

**Comment by ankitkanojia** [comment]
> 
> 
> I've added jquery-validation in v3 but without any demo, coming with the next release (rc.5).

Thank you @REJack
