### ISSUE TITLE
Invoice Print : Shows Blank Preview

### ISSUE THREAD

**Issue by vittalgar** [ColorlibHQ/AdminLTE#2300]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  3.0.0 rc3
* Operating System:  Windows
* Browser (Version):  Chrome 77

### Description:
In AdminLTEv3, On clicking on 'Print' icon blank Print Preview is displayed.

![AdminLTEv3](https://user-images.githubusercontent.com/9591756/66119649-ad141200-e5f6-11e9-9e9b-62e2c6ef5e39.png)

**Comment by REJack** [comment]
I added a fix to load the css before runing the window.print() in my fork.

**Comment by REJack** [comment]
This fix is released with v3.0.0-rc.4.
