### ISSUE TITLE
生成css有误

### ISSUE THREAD

**Issue by qbsencom** [ColorlibHQ/AdminLTE#2301]
AdminLTE Version:  AdminLTE-3.0.0-rc.3
生成css时出错，3.0.0-rc.1能正常生成css。
错误提示如图：
![微信图片_20191003184135](https://user-images.githubusercontent.com/50788466/66120704-15222280-e60e-11e9-9fe0-788fc8a4b2b4.png)

**Comment by REJack** [comment]
I've added a fix in my fork and push it soon to the repo.

**Comment by REJack** [comment]
This fix is released with v3.0.0-rc.4.
