### ISSUE TITLE
Issue in layout in responsive mode

### ISSUE THREAD

**Issue by Q8root** [ColorlibHQ/AdminLTE#2306]
There is menu issue when try to open the template using a mobile
![image](https://user-images.githubusercontent.com/33479962/66253482-a78f0700-e771-11e9-991c-6eedbb325af0.png)

**Comment by REJack** [comment]
Please provide your code example or changes if you test it on top of the demo examples.

**Comment by Q8root** [comment]
> Please provide your code example or changes if you test it on top of the demo examples.

Please explain more, what do you need me to provide ? The whole code .

But the issue also occurred when i directly access the [index.html](https://github.com/ColorlibHQ/AdminLTE/blob/master/index.html) file with no change done from my side.

**Comment by REJack** [comment]
I can't replicate this with the latest version (v2.4.18), it looks like it should.
![Bildschirmfoto vom 2019-10-05 um 12 44 14](https://user-images.githubusercontent.com/1554582/66253801-f175ee00-e76d-11e9-9e9f-04b31f70aa2e.png)

I guess you use a RTL language on your system, but AdminLTE doesn't support RTL out of the box, you would need to add lang="en" or dir="ltr" on your html tag.

**Comment by Q8root** [comment]
> I can't replicate this with the latest version (v2.4.18), it looks like it should.
> ![Bildschirmfoto vom 2019-10-05 um 12 44 14](https://user-images.githubusercontent.com/1554582/66253801-f175ee00-e76d-11e9-9e9f-04b31f70aa2e.png)
> 
> I guess you use a RTL language on your system, but AdminLTE doesn't support RTL out of the box, you would need to add lang="en" or dir="ltr" on your html tag.

Thank you for your help. I added dir="ltr" to html tag but no change.
Please advice.

**Comment by REJack** [comment]
Did you tried `lang="en"`?

**Comment by Q8root** [comment]
> Did you tried `lang="en"`?

I tried both but still having the issue.
here is my working platform 
http://eomosys.com/panel/package/

**Comment by REJack** [comment]
I can't replicate this issue on your platform.
