### ISSUE TITLE
AdminLTE v3 sidebar issue on small screen

### ISSUE THREAD

**Issue by bboehmke** [ColorlibHQ/AdminLTE#2307]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-rc.4
* Operating System:  Linux
* Browser (Version):  Chrome (Latest)

### Description:
On small screen the sidebar is by default not collapsed and hide the content of the page.

To reproduce simply open https://adminlte.io/themes/dev/AdminLTE/index.html and reduce the window size below a width of 760px.

I would expect that the sidebar will be collapsed by default on small screens (as it was in AdminLTE v2).

![image](https://user-images.githubusercontent.com/9787279/66253950-dc9a5a00-e76f-11e9-8e0b-364e29464da9.png)

**Comment by toxpal** [comment]
https://github.com/ColorlibHQ/AdminLTE/issues/2304#issuecomment-538422237

But I suggest this option should be enabled **by default** in future releases of v3.

**Comment by bboehmke** [comment]
Oh I totally missed this comment.

I can find the option in the documentation (maybe caused by the broken state at the moment).
But after some try & error I found how to set the `autoCollapseSize`:
> Add `data-auto-collapse-size="*"` to the `<a class="nav-link" data-widget="pushmenu" ...`

I would agree with @toxpal that this option should be set by default.

**Comment by REJack** [comment]
I'll change this behavior like it was before in v2, coming with the next RC (rc.5).

**Comment by REJack** [comment]
I've changed the default behavior with the latest release (rc.5).
