### ISSUE TITLE
almasaeed2010/adminlte v2.4.18 requires bower-asset/jquery >=1.9.0 <4.0.0 -> no matching package found.

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#2308]
### Issue type:
- [ ] Feature request 
- [X] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.18
* Operating System:  OSX
* Browser (Version):  Chrome (latest)

### Description:
composer require almasaeed2010/adminlte 2.4.18

results with

almasaeed2010/adminlte v2.4.18 requires bower-asset/jquery >=1.9.0 <4.0.0 -> no matching package found.

**Comment by REJack** [comment]
You need to add the asset-packagist stuff to get this working. For more infos look at https://asset-packagist.org/.

**Comment by jeffreyroberts** [comment]
Thank you
