### ISSUE TITLE
In index.html, the Sales Graph's [+], [-] button is not working.

### ISSUE THREAD

**Issue by monadgon** [ColorlibHQ/AdminLTE#2311]
### Environment:
* AdminLTE Version:  AdminLTE-3.0.0-rc.4
* Operating System:  Windows 10 Pro
* Browser (Version):  Chrome (Latest), IE 11

### Description:
1. Test protocol is file://
ex) file:///D:/AdminLTE/AdminLTE-3.0.0-rc.4/index.html

2. In Chrome (Latest)
in the Sales Graph
step 1) Click [-] button: OK(collapse the graph)
step 2) Click [+] button: NG
    The line graph is not displayed.

![image](https://user-images.githubusercontent.com/511164/66278865-0a0a1380-e8e8-11e9-8334-355b5086a7b2.png)

3. In IE 11
The Sales Graph is expanding to vertical infinitely.
![image](https://user-images.githubusercontent.com/511164/66278881-3faefc80-e8e8-11e9-82a2-5a3c562bd19e.png)

**Comment by REJack** [comment]
I've fixed both bugs in v3-dev, comes with next release (rc.5).
