### ISSUE TITLE
npm WARN deprecated ckeditor@4.12.1 renamed & jsvectormap unmaintained

### ISSUE THREAD

**Issue by phillipsharring** [ColorlibHQ/AdminLTE#2314]
### Issue type:

- [ ] Feature request
- [X ] Bug report
- [ ] Documentation

### Environment:

* AdminLTE Version:  2.4.18
* Operating System:  Windows 10 Pro
* Browser (Version):  N/A - happens during npm install
* NPM version:  6.9.0
* Node version:  v12.5.0

### Description:

Following npm instructions found here:
https://adminlte.io/docs/2.4/installation

Running `npm install admin-lte --save` gives a couple of warnings.

```
npm WARN deprecated ckeditor@4.12.1: We have renamed the @ckeditor package. New versions are available under the @ckeditor4 name.
npm WARN deprecated jvectormap@1.2.2: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
```

There's an old, closed issue regarding a ckeditor version bump here:
https://github.com/ColorlibHQ/AdminLTE/issues/922
but it looks like this rename has happened even since then.

I didn't find anything re:  jsvectormap.

Just a heads-up.

**Comment by REJack** [comment]
Thanks for reporting the ckeditor rename error with npm, I will update ckeditor in the next days.

jsvectormap is already known as not maintened, but it will remain in v2 to avoid possible breaks by users.
