### ISSUE TITLE
Sticky Position

### ISSUE THREAD

**Issue by keithtumusiime** [ColorlibHQ/AdminLTE#2315]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
Sticky position when applied to divs in the wrapper not working

**Comment by keithtumusiime** [comment]
Please help me

**Comment by REJack** [comment]
In which AdminLTE Version?

**Comment by keithtumusiime** [comment]
AdminLTE v3.0.0-rc.1

**Comment by REJack** [comment]
Please provide a html example, working position sticky demo is in pages/calendar.html.

**Comment by keithtumusiime** [comment]
It worked using the class sticky-top. thanks so much
