### ISSUE TITLE
Error installing AdminLTE v3-rc4 via npm

### ISSUE THREAD

**Issue by rino7** [ColorlibHQ/AdminLTE#2317]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v3-rc4
* Operating System:  Debian Docker over Windows 10 x64 host
* Browser (Version):  N/A 

### Description:
When you trying to install AdminLTE v3 vía npm as described in documentation
`npm install admin-lte@v3-latest --save`
It's throwing an error like this:

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! admin-lte@3.0.0-rc.4 install: npm run plugins
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the admin-lte@3.0.0-rc.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I've tried cleaning and reinstall with this command:
`npm cache clean --force && rm -rf node_modules && rm ./package-lock.json && npm install`
But was not successfull

Here is a more detailed StackTrace:

36407 verbose stack Error: admin-lte@3.0.0-rc.4 install: npm run plugins
36407 verbose stack Exit status 243
36407 verbose stack at EventEmitter. (/home/laradock/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
36407 verbose stack at EventEmitter.emit (events.js:209:13)
36407 verbose stack at ChildProcess. (/home/laradock/.nvm/versions/node/v12.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
36407 verbose stack at ChildProcess.emit (events.js:209:13)
36407 verbose stack at maybeClose (internal/child_process.js:1021:16)
36407 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by REJack** [comment]
I found a similar issue on github, the issue author closed his issue with this:

> This ended up looking to be a permissions issue.
> https://github.com/vector-im/riot-web/issues/7458

The npm error say also "This is probably not a problem with npm".
Please check if your permission are correct 😄

**Comment by rino7** [comment]
But have no Sense because RC.1 Is not failing

**Comment by REJack** [comment]
The difference between rc.1 and rc.4 is that the plugins come not within the npm package, caused they are in the package.json and will installed with adminlte and for this is the plugins script, may I will remove it from install scripts to avoid this errors.

**Comment by rino7** [comment]
Well, finally I could install rc.4 via npm. Effectively, It was a permission issue.
npm had not access to /root/.npm dir
I've set grant access to that dir and installation was succesfull. I don't know if there's a better solution. In official page suggests [this one](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). But, sincerely I don't know if works.

**Comment by REJack** [comment]
I close this issue 😄

**Comment by bobvandevijver** [comment]
@REJack I just experienced some problems with yarn, as somehow the plugins folder no longer contained the plugin I was expecting (this was due to the fact that it was downgraded to v2 by mistake, so no direct connection with this particular issue).

I think it would indeed be wise to remove the custom install script for the plugins, and make users aware that they should link the assets from the `node_modules` directly if required.

**Comment by ajewole** [comment]
I had similar issue
