### ISSUE TITLE
Slim Version

### ISSUE THREAD

**Issue by rrpadilla** [ColorlibHQ/AdminLTE#2320]
### Issue type:
- [X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v3 and v2 *
* Operating System:  N/A
* Browser (Version):  N/A

### Description:
- Need a very tiny version of the template (sidebar + only required scripts and css).
- How we can reduce files size using "[Tree Shaking](https://webpack.js.org/guides/tree-shaking/)".
- How we can use "[PurgeCSS](https://www.purgecss.com/)" to remove unused CSS.

Thanks!

**Comment by REJack** [comment]
> Need a very tiny version of the template (sidebar + only required scripts and css).

Even without any bootstrap css?

> How we can reduce files size using "Tree Shaking".

In AdminLTE v3 we using rollup, rollup has Tree Shaking enabled by default (see [here](https://rollupjs.org/guide/en/#tree-shaking)). AdminLTE 2 don't will recieve any new feature since v3 development is new to releasing stable, for this you would need to research/modify by yourself.

> How we can use "PurgeCSS" to remove unused CSS.

I don't know how to use PurgeCSS I've never used it, but they have a good looking documentation and I would try the cli for this 😄.

**Comment by rodruiz** [comment]
Hi @REJack,
> Even without any bootstrap css?

I think bootstrap css is required all the time because the grid system.

> In AdminLTE v3 we using rollup, rollup has Tree Shaking enabled by default (see [here](https://rollupjs.org/guide/en/#tree-shaking)). 

Awesome!

> AdminLTE 2 don't will recieve any new feature since v3 development is new to releasing stable, for this you would need to research/modify by yourself.

Makes sense.

> I don't know how to use PurgeCSS I've never used it, but they have a good looking documentation and I would try the cli for this 😄.

The idea is to remove unused css when building for production.

Thanks!

**Comment by REJack** [comment]
> I think bootstrap css is required all the time because the grid system.

I'll look over the code and may I create a adminlte-slim(.min).css 😄 only with sidebar, content/content-header, navbar & footer css styles.

> The idea is to remove unused css when building for production.

That's a nice idea but this would not possible to implement in AdminLTE. AdminLTE is only a OpenSource Dashboard Template.

For this you would need to add a build step in your application.

**Comment by REJack** [comment]
I've released rc.6 with additinoal alternative css files: core, components, extra-components, pages & plugins.
