### ISSUE TITLE
AdminLTE theme doesn’t render correctly with asp.net blazor (server side) application 

### ISSUE THREAD

**Issue by sumit394** [ColorlibHQ/AdminLTE#2326]
Hi,

I am learning asp.net blazor and trying to use adminLTE theme as front end.

Somehow I am not able to make it work at all. It doesn’t render the webpage correctly and menu toggle doesn’t work.

Has anyone tried to use adminLTE theme with asp.net blazor?

I have tried to publish basic on freeware azure servers without changing anything from index.html but it still doesn’t work. It renders correctly on localhost but sidebar menu toggle doesn’t work on localhost or after deployment 

If anyone has asp.net blazor starter kit with adminLTE theme so it would be a huge help for beginners 

Regards

**Comment by REJack** [comment]
Sadly I can't help you with that, may you can find a better help on stackoverflow.com.

**Comment by KoenBoone** [comment]
this should help transforming adminLTE to blazor: https://www.youtube.com/watch?v=tm7QheXi8R4
