### ISSUE TITLE
caret on multilevel menu not open

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2327]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-rc.4
* Operating System:  Windows 10
* Browser (Version):  Google Chrome (77.0.3865.120)

### Description:
Thank You for developing this awesome framework.

![image](https://user-images.githubusercontent.com/14267724/66725079-d71bce80-ee57-11e9-896e-b57ba539c72d.png)

as we see, when we click on level-1, default of level-2 is expanded, but the caret not open.

**Comment by AdeSupriyadi** [comment]
sorry this issue was duplicated to [this](https://github.com/ColorlibHQ/AdminLTE/issues/2310)

**Comment by REJack** [comment]
This is already fixed in v3-dev branch and will published with the next release (rc.5), if I find time then I publish today the release.
