### ISSUE TITLE
sidbar menu scroll option not showing

### ISSUE THREAD

**Issue by machaderwala** [ColorlibHQ/AdminLTE#2328]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by machaderwala** [comment]
sidebar menu option scrolling option is not coming

**Comment by REJack** [comment]
What exactly you mean and for which AdminLTE Version?

**Comment by machaderwala** [comment]
version 3, scrolling side bar menu is not loading

**Comment by REJack** [comment]
Did you added layout-fixed to your body class?

**Comment by machaderwala** [comment]
no

**Comment by REJack** [comment]
You get only a scrollbar on sidebar, with layout-fixed but you need also to load overlayScrollbars too.

**Comment by machaderwala** [comment]
how to load it

**Comment by REJack** [comment]
You need to add script/link tags, like this from the demo.
```html
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- overlayScrollbars -->
  <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
```

May you need to change the plugin path (plugins/overlayScrollbars) to your favor.

**Comment by machaderwala** [comment]
ok in which file i need to put this code in sidebar.php?

**Comment by REJack** [comment]
Oh there I can't help you, this depends where you placed your main html markup (<html>, <head> & <body>). It not work beside the sidebar aside
