### ISSUE TITLE
Collapsed Sidebar Not Working in new release

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2329]
Collapsed Sidebar not working in latest release.

**Comment by deepak458** [comment]
@REJack In latest release javascript removing Collapsed Sidebar class from body. have a look

**Comment by REJack** [comment]
What exactly doesn't work?

**Comment by deepak458** [comment]
@REJack  Collapsed Sidebar auto removing by javascript.

**Comment by REJack** [comment]
I need more details, which browser, type of device (mobile or desktop), screen/window size. Also a demo link/ html code would be nice.

**Comment by deepak458** [comment]
@REJack Im using Chrome 77.0 Latest Version in Windows 10 operating system. For more referance you can check [this link ](https://adminlte.io/themes/dev/AdminLTE/pages/layout/collapsed-sidebar.html).

In Above link by default side bar open Collapsed using `.sidebar-collapse` class but your javascript remove `.sidebar-collapse` on page load.

**Also Let me know the quick solutions for this.**

**Comment by REJack** [comment]
Oh now I understand, I'll check this out tomorrow and push a fix before releasing the next version.

**Comment by deepak458** [comment]
Thanks @REJack 😃👍

**Comment by deepak458** [comment]
Any quick solutions for this so i can continue work on this.

**Comment by REJack** [comment]
@deepak458 I've added a fix but I've not published the it with the latest release 🤦‍♂ you can download the js files from the v3-dev branch for a quick workaround.

**Comment by deepak458** [comment]
@REJack Ok Thanks

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.
