### ISSUE TITLE
nav nav-tabs header left border

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2330]
Hi @REJack  i'm working with nav-tabs in your latest release, and in nav-tabs header left-border not showing you can check below image for reference.

![image](https://user-images.githubusercontent.com/29248598/66810268-83d77800-ef4c-11e9-8e16-2b725fc41547.png)

And i found the solution it is:

You have to change css as below code
`.card-primary.card-outline-tabs>.card-header .nav-item:first-child .nav-link {
    margin-left: -1px;
    border-left: 0;
}`

**Set margin-left:0px** 
 
And also below css

`.card-primary.card-outline .nav-item:first-child .nav-link {
    margin-left: -1px;
    border-left: 0;
}`
**Set margin-left:0px**

**Comment by REJack** [comment]
I've added a fix for this bug in v3-dev branch, comes with the next release (rc.5) :D

**Comment by deepak458** [comment]
Thanks

**Comment by deepak458** [comment]
@REJack You can also fix this bug mention in  in below image

![image](https://user-images.githubusercontent.com/29248598/66944972-db203a00-f06b-11e9-80b2-1c34a7b68747.png)

It's shows 1px border-top;

You can fix it As below image
![image](https://user-images.githubusercontent.com/29248598/66945137-29353d80-f06c-11e9-8a46-fa0ef6b455a3.png)

Sorry I don't have code but maybe you can do.

**Comment by REJack** [comment]
@deepak458 I've published the left border fix in v3.0.0-rc.5, I'll add the border top change in the next days.

**Comment by deepak458** [comment]
@REJack i need some help, i'm new in `npm` and just using your release with npm. All file and package.json file created.

but can you please help me how i can extract and use only required file from /node_modules/ to /plugins folder.

i not require any html or other file from installed plugins.

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.

> but can you please help me how i can extract and use only required file from /node_modules/ to /plugins folder.

For this your should need only to run `npm run plugins`, but it should run on `npm install` too. If you still stuck on this open please a new issue.
