### ISSUE TITLE
starter template scrollable

### ISSUE THREAD

**Issue by knightowl1000** [ColorlibHQ/AdminLTE#2331]
### Issue type:
- [ ] Feature request 
- [x ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  AdminLTE 3.0.0-rc.4
* Operating System:  Windows
* Browser (Version):  Chrome/Firefox

### Description:
The starter.html template content is light. For some reason you must scroll down to see the footer. I have the footer in my starter.html file with the class of `layout-footer-fixed` in the body. It's fixed, but you still have the scroll bar. In Version 2, this was done correctly. Empty page or light on content, the scroll bar does not show up. If content heavy and scroll bar needs to exist, it shows up.

**Comment by REJack** [comment]
I've added a fix for this bug in v3-dev branch.

**Comment by REJack** [comment]
AdminLTE v3.0.0-rc.5 is released with this fix.
