### ISSUE TITLE
Select2 OnFocus Outline hide

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2334]
### Issue type:
- [ ] Feature request 

### Environment:
* AdminLTE Version:  rc.3
* Operating System:  Windows 10
* Browser (Version):  74.0

### Description:
**Select2 Focus Outline hide on focus.**
![image](https://user-images.githubusercontent.com/29248598/66944066-128de700-f06a-11e9-9103-53f407c492ce.png)

**All Other Buttons don't have focus outline but still select2 have focus outline check above image.**

**Comment by REJack** [comment]
If I‘m not wrong I already fixed it in v3-dev branch and will published with the next release.

**Comment by deepak458** [comment]
Ok
