### ISSUE TITLE
AdminLTE v3.0.0-rc.5 is released!

### ISSUE THREAD

**Issue by REJack** [ColorlibHQ/AdminLTE#2338]
Hey Folks 😄,

I've published AdminLTE v3.0.0-rc.5 with the following changes/fixes:

### Release Notes
- fixed docs generation problems
- fixed submenu expand bug 
- fixed resizing bugs with chartjs in index.html 
- enable auto collapse size by 992px as default option  
- added new plugin jquery-validation v1.19.1
- fixed content height calculation 
- fixed some little select2 default theme
- fixed autocallapse on mobile touchscroll & rebuild dists
- fixed select2 multiple height bug
- fixed content height calc with less sidebar content
- fixed navbar tabs border in card-header

For the complete changelog [look here](https://github.com/ColorlibHQ/AdminLTE/compare/v3.0.0-rc.4...v3.0.0-rc.5).

regards REJack

**Comment by Jeckerson** [comment]
Hello!

Any release date for `v3.0.0` ?

**Comment by REJack** [comment]
@Jeckerson My focus is on the 1. Nov '19, If anything works without problems 😄

**Comment by mzy666888** [comment]
Very good, fantastic news

**Comment by U-node** [comment]
Hi, I'm sorry if my question is too stupid.
I try to import adminlte.js to my reacts app and I get following error: ReferenceError: Can't find variable: jQuery.

It is in such strings of Adminlte.js as

```
var Toasts = function ($) {
    ...
}(jQuery);
```

- If I connect jquery.js by `script` tag in HTML, everything is ok
- Or if I remove `(jQuery)` from Adminlte.js lines, everything is ok too, but it is bad idea to change package content


Sory for my stupidness one more time and please help me :)
