### ISSUE TITLE
use original bootstrap alert

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2341]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-rc.5
* Operating System:  windows 10
* Browser (Version):  Chrome

### Description:

I need to use original bootstrap 4 alert, instead admin-lte customized, how to do it?

**Comment by REJack** [comment]
What excatly you mean, the style of the alert (e.g. background color)?

**Comment by REJack** [comment]
I've added `alert-default-*` classes to get the default bs4 alert style instead of AdminLTE's style, it's released with the latest release (rc.6).
