### ISSUE TITLE
Where the User toggle like in version 2

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2342]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-rc.5
* Operating System:  windows 10
* Browser (Version):  Google Chrome

### Description:

When in version 2 we have the user toggle

![image](https://user-images.githubusercontent.com/14267724/67193801-18941700-f420-11e9-8409-8b749595b460.png)

Will You add this to in version 3?

**Comment by REJack** [comment]
Look at https://adminlte.io/themes/dev/AdminLTE/pages/examples/legacy-user-menu.html
