### ISSUE TITLE
sidebar-collapse no longer works in 3.0.0-rc.5

### ISSUE THREAD

**Issue by bobvandevijver** [ColorlibHQ/AdminLTE#2343]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  3.0.0-rc.5
* Operating System:  Windows
* Browser (Version):  Example: Chrome (Latest)

### Description:

Setting the class `sidebar-collapse` does collapse the sidebar initially, but when the page load has been fully finished, it expands itself once again.

It does work as expected in 3.0.0-rc.4 (it stays collapsed).

**Comment by REJack** [comment]
Duplicate of #2329

**Comment by bobvandevijver** [comment]
Oops 🙈
