### ISSUE TITLE
About sidebar display when 'medium' width

### ISSUE THREAD

**Issue by waiei** [ColorlibHQ/AdminLTE#2344]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0-rc.5 
* Operating System: Windows 10 
* Browser (Version): Chrome77 / Edge18 

### Description:

Hello.
Thank you for making a great template.
I have a question about behavior that cannot be determined to be a specification or a bug.

If the sidebar is closed when the window width is Medium (767px<Width<992px), it will be hidden as if it were 767px or less.
However, when the sidebar is displayed, the sidebar does not overlap the main content.
The main content is pushed to the right in the same way as when the width is more than 992px.
Oddly enough, if I try to operate the main content in this state, the sidebar will close.
In AdminLTE2, when the sidebar is closed, the display is minimized, and the main content can be operated even when the sidebar is open.
(The following screenshot shows the behavior when starter.html is displayed.)

![lte3](https://user-images.githubusercontent.com/8708955/67271205-0c2dbe00-f4f5-11e9-84d6-9d4abcd4f5a9.jpg)

![lte2](https://user-images.githubusercontent.com/8708955/67271222-12bc3580-f4f5-11e9-82c7-565c9dd0f46f.jpg)

The behavior I expect is one of the following two:
(1) Same behavior as AdminLTE2
(2) Similar to when 'Small' width (767px<Width), when the sidebar is opened, it is displayed so as to overlap the main content(Like the image below)

![lte_exp](https://user-images.githubusercontent.com/8708955/67271244-1fd92480-f4f5-11e9-88ab-5fb9a6d1d027.jpg)

Is the operation of Rc5 a specification?
I look forward to your response.
Thank you.

**Comment by REJack** [comment]
For the 1st behavior you only need to add `.sidebar-mini-md` beside the `.sidebar-mini`. The default behavior should work like you expect it, I'll fix this later.

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.
