### ISSUE TITLE
Need help for dynamic data loading of DataTable (paging and lengthChange)

### ISSUE THREAD

**Issue by shiran3F** [ColorlibHQ/AdminLTE#2345]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  AdminLTE-3.0.0-rc.4
* Operating System:  any
* Browser (Version):  any

### Description:
Just a question.
Suppose there are dozen of rows in a database, I don't want to load all of them to the html page in one time. 

Currently, I referred to the sample (/pages/tables/data.html, "DataTable with default features"), but I don't know how to do with the paging and lengthChange (I don't need searching feature). One of my thought is to generate all related html elements by jinja (I am using Flask) instead of js function. Is this the best practice? Or what else should I do?

P.S I am not good at frontend.
Thank in advance

**Comment by andcarpi** [comment]
You should check the Datatables plugin documentation, since it's an external plugin and not a part of this package.

https://datatables.net/

**Comment by shiran3F** [comment]
@andcarpi THANK YOU SO MUCH!
for those might have same question, just refer to https://datatables.net/examples/server_side/simple.html and enable the brower devtool to see what paras were sent to the server.
