### ISSUE TITLE
aside bar scroll bar css

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2346]
### Issue type:
- [ ] Bug report       

### Environment:
* AdminLTE Version:  R.C. 5
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

### Description:
From the first day i'm getting this problem, aside scrollbar not getting style as its developed,

I know this is not your software bug but why it's now working in mine.

**Comment by REJack** [comment]
Did you fixed your bug?
