### ISSUE TITLE
.btn-group class not wokring with select 2

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2347]
@REJack  There is some issue when we are using `.btn-group` for button and select2 class its change the select2 borders.

Is there anything that we can use?

 Have a Look in below image
![image](https://user-images.githubusercontent.com/29248598/67328277-e1645980-f536-11e9-8dd2-6f2324235982.png)

**Comment by REJack** [comment]
If you use the default (built in) select2 theme there is no style changes for this, but it should work with the bootstrap4 select2 theme that’s additionally added in AdminLTE.

**Comment by REJack** [comment]
I've added style fixes for select2 but not for `.btn-group`, I added it for `.input-group`.
This change comes with the next release (rc.6).

The following code
```html
<div class="input-group">
  <div class="input-group-prepend">
    <button class="btn btn-outline-secondary" type="button" id="button-addon1">Button</button>
  </div>
  <select class="form-control select2">
    <option selected="selected">Alabama</option>
    <option>Alaska</option>
    <option>California</option>
    <option>Delaware</option>
    <option>Tennessee</option>
    <option>Texas</option>
    <option>Washington</option>
  </select>
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button" id="button-addon1">Button</button>
  </div>
</div>
```
will look like this

![select2 demo](https://graphiko.cloud/index.php/s/AZ3qYnFxCPSayLJ/preview)

**Comment by deepak458** [comment]
This is what it want.

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.
