### ISSUE TITLE
Two line item in select2 input havn't bottom padding

### ISSUE THREAD

**Issue by gotounix** [ColorlibHQ/AdminLTE#2349]
### Issue type:
- [*] Bug report

### Environment:
* AdminLTE Version:  AdminLTE 3.0.0-rc.5
* Operating System:  Windows 10
* Browser (Version):  Firefox 70

### Description:
![111](https://user-images.githubusercontent.com/18606632/67377804-d18d5980-f5b8-11e9-8c86-8dfccedcd559.png)

**Comment by REJack** [comment]
I see what you mean, I'll fix this soon.

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.
