### ISSUE TITLE
General Form / "File Input" don't show path

### ISSUE THREAD

**Issue by ardabugra** [ColorlibHQ/AdminLTE#2350]
Hello,

File path does not appear even though I selected the file.

```
<script>
            $('#inputGroupFile02').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
</script>
```

I tried to do it with the script, the image is corrupted if the file name is long.

**Comment by REJack** [comment]
For this you should use `bs-custom-file-input` like it's done in Bootstrap 4's docs, but if the file name is to long you will always not get a cutted text display.

I've also added `bs-custom-file-input` plugin in v3-dev branch with in forms/general.html demo.

**Comment by ardabugra** [comment]
I did it according to our document,

Can you help me shorten the file name

**Comment by REJack** [comment]
For a quick string substraction you can use `substring()`, like `$(this).next('.custom-file-label').html(fileName.substring(0, 50));` (50 is the max char lenght for the file name, this can be changed to your favor). 

Note: this will work only with your custom js and not with the `bs-custom-file-input` plugin.
