### ISSUE TITLE
Select2 (Default Theme)  and Select2 (Bootstrap4 Theme) not working into same page

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2351]
@REJack there is some bug with `Select2 (Bootstrap4 Theme)` it's not working with `Select2 (Default Theme)`. When we use both in the same page, then `Select2 (Bootstrap4 Theme) `not show any drop down values.

for more reference check your [page ](https://adminlte.io/themes/dev/AdminLTE/pages/forms/advanced.html)

check `Select2 (Bootstrap4 Theme)` it's not show any record.

**Comment by deepak458** [comment]
@REJack also there is some issue with Select2 (Bootstrap4 Theme) height, have a look

![image](https://user-images.githubusercontent.com/29248598/67425073-f9021780-f5f4-11e9-8b78-f5a67308d6ba.png)

**Comment by REJack** [comment]
> there is some bug with Select2 (Bootstrap4 Theme) it's not working with Select2 (Default Theme). When we use both in the same page, then Select2 (Bootstrap4 Theme) not show any drop down values.

I found the bug and fixed it in v3-dev branch, the bootstrap4 theme variant needs loaded after the default theme variant.

> also there is some issue with Select2 (Bootstrap4 Theme) height, have a look

For style bugs with the bootstrap4 theme you need to create a issue on the [plugin repo](https://github.com/ttskch/select2-bootstrap4-theme).

**Comment by deepak458** [comment]
> I found the bug and fixed it in v3-dev branch, the bootstrap4 theme variant needs loaded after the default theme variant.

@REJack  As of now in latest release, i also try to load the bootstrap 4 theme after the main theme but still getting same error.



> For style bugs with the bootstrap4 theme you need to create a issue on the [plugin repo](https://github.com/ttskch/select2-bootstrap4-theme).

Also Thanks for the reference.

**Comment by REJack** [comment]
>  As of now in latest release, i also try to load the bootstrap 4 theme after the main theme but still getting same error.

 I can't replicate this after fixing the init bug with 242ef8984ad0a231ce7a819ecad282b41ad4e9fc, for this may you should create a issue on [select2's repo](https://github.com/select2/select2).

>  And any solutions to remove focus outline from select 2 because there is only select2 have outlines

Where you have outlines/box-shadows? I see only a other border color on focus like general input's with the latest release.

**Comment by deepak458** [comment]
@REJack Ok, now i get this where i'm getting error first thing, yes you are right about this

> there is some bug with Select2 (Bootstrap4 Theme) it's not working with Select2 (Default Theme). When we use both in the same page, then Select2 (Bootstrap4 Theme) not show any drop down values. 

but still there is some issue with select2 focus, i have check the code the select 2 you have removed focus from select2 but i'm getting it because of select2  bootstrap 4 theme.

have a look in your current fix [242ef89](https://github.com/ColorlibHQ/AdminLTE/commit/242ef8984ad0a231ce7a819ecad282b41ad4e9fc) still select2  bootstrap 4 theme is showing the focus outline.

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.
