### ISSUE TITLE
Tooltips?

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#2352]
### Issue type:
- [X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
I see references to ToolTips in the code, but I do not see any examples, are there examples, where can I find them?

**Comment by andcarpi** [comment]
Tooltips are part of bootstrap, you can check the docs here:
https://getbootstrap.com/docs/4.1/components/tooltips/

**Comment by REJack** [comment]
> Tooltips are part of bootstrap, you can check the docs here:
https://getbootstrap.com/docs/4.1/components/tooltips/

Correct, the AdminLTE demos are mostly a demo for the custom styles/stuff that comes with AdminLTE and less bootstrap4 demo items to reduce the demo size.
