### ISSUE TITLE
Icon Colors with Success, Info, Warning, Danger

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#2353]
### Issue type:
- [X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Description:
How do I make an icon the color of success, info, warning or danger?

**Comment by andcarpi** [comment]
just add a color style in their element...
example (for success, i used green):
<i class="fas fa-check" style="color:green"></i>

**Comment by jeffreyroberts** [comment]
Well the thing is, is I am using php and mysql to generate the content dynamically, and I am storing in a notifications table success, info, warning, or danger, depending on the notification, for a growl like callout, and then on another page, I am listing the notifications, and I only have access to success, info, warning, or danger from the DB, and I would prefer not to have to switch that field and create another variable, as I might use these notifications else where as well, and that leads to a lot of extra code, when I could just label the icon success for instance...

I will create a custom css for now, but it would be nice to see this added to the template/theme

**Comment by deepak458** [comment]
> ### Issue type:
> * [x]  Feature request
> * [ ]  Bug report
> * [ ]  Documentation
> 
> ### Description:
> How do I make an icon the color of success, info, warning or danger?

@jeffreyroberts you can use `bg-primary, bg-info....` and some more for background color and also for icons and text color use `text-red, text-gree, text-info...` class for text color, icon color

**Comment by REJack** [comment]
P.S. You can also use theme color names with text-* like text-success instead of color names.
