### ISSUE TITLE
Legacy User Menu right ride padding

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2354]
@REJack in current release Legacy User Menu not aling with user profile image also user image and user name space is little bit small have a look in your release: 

![image](https://user-images.githubusercontent.com/29248598/67481927-71fa8100-f680-11e9-9828-5040f15cfb61.png)

And What I'm taking about
![image](https://user-images.githubusercontent.com/29248598/67482240-09f86a80-f681-11e9-8f1c-2fe587a855b9.png)

* Increase the user profile image size by 10 px
* Added some space between user image and user name (add strong attribute only for me don't consider that in this issue)

**Comment by REJack** [comment]
I see what you mean, I'll change this soon 😄

**Comment by REJack** [comment]
I've released rc.6 with this change/fix.
