### ISSUE TITLE
Remove outline from elements in mozilla

### ISSUE THREAD

**Issue by SmileYzn** [ColorlibHQ/AdminLTE#2356]
### Issue type:
- [x] Bug report       
- [ ] Documentation   
- [ ] Feature request 

### Environment:
* AdminLTE Version:  Latest RC5 version
* Operating System:  Windows 8.1 and Linux Mint
* Browser (Version): Mozilla Firefox (Latest)

### Description:

Hi folks, can someone remove border outline in Firefox browser?
I did not tested in other browsers like chrome, see the image:

https://i.imgur.com/YPraeoR.png

**Comment by REJack** [comment]
Where is the outline I can't find it on your image 🤦‍♂

**Comment by SmileYzn** [comment]
Sorry i'm uploaded wrong screenshot, outline is removed when alt is pressed to take screenshot lol

https://i.imgur.com/OmQBhlR.png

Also in sidebar toggle button, im used linux mint and firefox in this screenshot

**Comment by REJack** [comment]
I've removed the firefox outline in v3-dev branch 😄

**Comment by SmileYzn** [comment]
Thanks, nice work :+1:
