### ISSUE TITLE
Large CSS Distribution Size (3.0.0)

### ISSUE THREAD

**Issue by DeliriumCode** [ColorlibHQ/AdminLTE#2357]
\dist\css\admintlte.min.css
The new AdmintLTE 3.0.0 has a CSS size of 691KB
The old AdminLTE 2.4.18 has a CSS size of 105KB

This is a quite a large increase?

**Comment by REJack** [comment]
Yep I know what you mean.
I guess this comes from the sidebar mixins, I'll change this soon.

**Comment by REJack** [comment]
I've checked the whole code yesterday, the increased file size comes from v3's inbuilt color variations instead of skins (the v2 .css is also without the skins)

I reduced the files size by ~100kb with some optimizations in my latest commit (9252541)

**Comment by REJack** [comment]
I've released rc.6 with the reduced css file size :D
