### ISSUE TITLE
FEATURE REQUESTS: Bigger screen size breakpoints

### ISSUE THREAD

**Issue by clockover** [ColorlibHQ/AdminLTE#2358]
Hello,

Why not integrate bootstrap 4.x screen size breakdown XXL, XXXL, .. ?
It can be very usefull :)

Thanks a lot :)

**Comment by REJack** [comment]
For which breakpoint sizes, 2k & 4k?

**Comment by clockover** [comment]
I think 1440 and 1920 should be a good choice with actual pc monitor on the market. No ? :)

**Comment by REJack** [comment]
I will check it out and add it to v3.1.0 😄  to get v3.0.0 released soon.

**Comment by REJack** [comment]
After reviewing my PR again , I will not add new breakpoints, the biggest concern is that the dist sizes increase so much and we have already to big dist files. For this you should modify AdminLTE by yourself, you can use the PR as startingpoint to add new breakpoints.
