### ISSUE TITLE
[Feature Request] More Example Pages

### ISSUE THREAD

**Issue by jeffreyroberts** [ColorlibHQ/AdminLTE#2359]
### Issue type:
- [X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.17
* Operating System:  OSX
* Browser (Version):  Latest Chrome

### Description:
I could really use some more example pages, I am not a designer, I am a backend coder, and this theme/template has been a life saver, however, I could really use some more example pages, like the more example pages, the better this theme/template will be, IMO there should be a hundred example pages, you really have something amazing here, don't skimp on the examples...

Some Example Pages I could Use Are

- Search (With and Without Advanced Search Options)
- Search Results (One with text, One with pictures, One with mutlimedia)
- Image Gallery
- Video Gallery
- Google Maps Page
- FAQ Page
- Contact Us
- Landing Pages (SaaS, App, etc...)
- Blog Templates (Could use a bunch of different templates for different blog posts)
- eCommerce Browse Products
- eCommerce Product Page
- eCommerce View Cart
- eCommerce Checkout

These are just some examples of pages I could personally use, and I know if I could use them, then a lot of other developers out there could use them as well... The reason developers are using this theme/template is because it is open source, and because it is open source it can be used in projects and freely distributed with those projects... Most of us can't afford to pay for the rights to distribute templates, and we could really use a lot of examples that are included in pay themes/templates

Just take a look at any theme/template on wrapbootstrap, and check out the example pages included there, and we could definitely use those examples here as well...

Thank you so much

Also, is there somewhere where I can donate to the efforts here?

-

**Comment by REJack** [comment]
That's a nice idea, but for AdminLTE v2 I'll not add any new feature since v3 development is near to release. 

I'll add more examples to AdminLTE v3.1.0, to get v3.0.0 released soon.

**Comment by jeffreyroberts** [comment]
Do you have a date for 3.0 release?

Also, is there somewhere else I can contact you to chat? I have built out a CakePHP Dashboard and Web Application skeleton using 2.4.17, and I would like to talk to you about building out the same for 3.0, the current skeleton has over 70 pages in it, and I think if we were to collaborate a bit the CakeAdminLTE 3.0 release could be really special =]

**Comment by REJack** [comment]
My focus is on 1. Nov if anything works after the next rc. (I'll release today a new rc)

> Also, is there somewhere else I can contact you to chat?

👍 Send me an email.

**Comment by Lycantant** [comment]
Nice idea. Vote for Search Results, Landing Pages, and Blog Templates 👍

**Comment by REJack** [comment]
@jeffreyroberts May you can enhance your list above with this from your old issue 😄 

> 
    Product Page
    ** w/ forum thread style reviews with multi-media attachments
    Shop Home Page
    ** Featured Products
    ** Featured Reviews
    Shop Product Search Page
    ** Product Search List with reviews/quantity/etc
    Add Product Page

**Comment by deepak458** [comment]
@REJack i'm taking about something like that [Link](https://www.wrappixel.com/demos/admin-templates/pixeladmin/email-templates/password-reset.html)

**Comment by deepak458** [comment]
@REJack when we expect the next release for these pages

**Comment by SmileYzn** [comment]
It can be added a wizard too, useful for paymants and other things

**Comment by REJack** [comment]
I've added for now

* Additional Login/Register Version
* Search (With and Without Advanced Search Options)
* Search Results (One with text, One with pictures, One with mutlimedia)
* FAQ Page
* Contact Us

I see no relevance for Shop/eCommerce examples but feel free to create a PR for this.

@SmileYzn With v3.1 comes a step wizard (bs-stepper)
