### ISSUE TITLE
FileInput doesn't present name of the chosen file

### ISSUE THREAD

**Issue by shiran3F** [ColorlibHQ/AdminLTE#2362]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  AdminLTE v3.0.0-rc.4 and AdminLTE v3.0.0-rc.5
* Operating System:  Any
* Browser (Version):  Chrome 67.0.3396.99, Firefox 60.9.0esr, and Safari from iphone

### Description:
https://adminlte.io/themes/dev/AdminLTE/pages/forms/general.html
Two fileinput fields at this page have the same problem.
I have read [issue#2350](https://github.com/ColorlibHQ/AdminLTE/issues/2350). But it seems it helps nothing. And I didn't see bs-custom-file-input added in the demo? Did I miss anything?

**Comment by REJack** [comment]
The online demo is still on rc.5 release state it's not synced with the v3-dev branch.

**Comment by REJack** [comment]
I've released rc.6 with this change/fix. 
Also the online demo is updated 😄
