### ISSUE TITLE
Select2: Add form-control-sm support

### ISSUE THREAD

**Issue by valos** [ColorlibHQ/AdminLTE#2363]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE :  3.0.0-rc.5

### Description:
It seems that there is not support for form-control-sm fields in select2-bootstrap4-theme (for both single and multiple selects).
It would be pretty cool to add this feature.

Perhaps a look at this fork could be helpful:
https://github.com/angel-vladov/select2-bootstrap-theme

**Comment by REJack** [comment]
The select2-bootstrap4-theme is not developed by AdminLTE, please open a issue for this on the [select2-bootstrap4-theme's repo](https://github.com/ttskch/select2-bootstrap4-theme).

**Comment by RomeoJathu** [comment]
Check this link. 
[github](https://github.com/berkanakyurek/select2-bootstrap4-theme/issues/19 
)
