### ISSUE TITLE
Support Legacy Toolbar Style (v3)

### ISSUE THREAD

**Issue by DeliriumCode** [ColorlibHQ/AdminLTE#2364]
Add an option to use the same sidebar style as V2. i.e. add .nav-legacy to display the navbar using the v2 UI i.e. selected items viewed as a dash of color at the side rather than the bubble of color around the text.

After reviewing the release candidate, and v2. The sidebar design of v2 feels more modern and is preferred over the v3 implementation.

**Comment by REJack** [comment]
V3 has already a `.nav-flat` style for a v2-like style, you can test it in demo through the control-sidebar.

**Comment by DeliriumCode** [comment]
![v2 default](https://user-images.githubusercontent.com/48930895/67752980-e5f3ab00-fa2b-11e9-9c58-8d518aad0991.PNG)
![v3 flat](https://user-images.githubusercontent.com/48930895/67752981-e5f3ab00-fa2b-11e9-971d-b032ff244566.PNG)

**Comment by DeliriumCode** [comment]
The v2 version for me simply looks more modern.

**Comment by REJack** [comment]
I've added a `.nav-legacy` class for the v2-like style in v3-dev branch.

Here is a preview 😄 
![Screenshot_2019-10-30 AdminLTE 3 Dashboard 3](https://user-images.githubusercontent.com/1554582/67852755-4d355c00-fb0d-11e9-9fe9-b9fc54344fc1.png)

**Comment by REJack** [comment]
Changes released with v3.0.0 😄

**Comment by debarshi121** [comment]
.nav-legacy is not working on adminlte 3. I want a sidebar like adminlte 2.
