### ISSUE TITLE
disabled button should not trigger click event

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2365]
### Issue type:
- [ ] Feature Request       

### Environment:
* AdminLTE Version:  3.0.0.rc1
* Operating System:  Window 10
* Browser (Version):  FireFox(Latest)

### Description:

I think buttons with `.disabled` class should not trigger **click** events. And should add `cursor: not-allowed;` css style. Thanks.

**Comment by REJack** [comment]
I can't replicate this issue with Firefox 70 on macOS, but I found this on Bootstrap4's docs:

> The .disabled class uses pointer-events: none to try to disable the link functionality of `<a>`s, but that CSS property is not yet standardized. In addition, even in browsers that do support pointer-events: none, keyboard navigation remains unaffected, meaning that sighted keyboard users and users of assistive technologies will still be able to activate these links. So to be safe, add a tabindex="-1" attribute on these links (to prevent them from receiving keyboard focus) and use custom JavaScript to disable their functionality.

**Comment by cataclysmuprising** [comment]
Thanks for your comment bro. My FireFox version is 70 too and it triggers click events. Now I controlled with js code for my case. And how do you think to add `cursor: not-allowed;` style ?

**Comment by REJack** [comment]
I've added `cursor: not-allowed;` to `.btn.disabled` in my latest commit (9252541) 😄.

**Comment by REJack** [comment]
Changes released with v3.0.0 😄
