### ISSUE TITLE
Errors with Filterizr

### ISSUE THREAD

**Issue by massimba** [ColorlibHQ/AdminLTE#2366]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Module '"./FilterizrOptions/defaultOptions"' has no exported member 'RawOptions'.	vtech	D:\source\repos\vtech\plugins\filterizr\Filterizr.d.ts	5	
Error		Build:Module '"./FilterizrOptions/defaultOptions"' has no exported member 'RawOptionsCallbacks'.	vtech	D:\source\repos\vtech\plugins\filterizr\FilterContainer.d.ts	1	
Error		Build:Module '"./ActiveFilter"' has no exported member 'Filter'.	vtech	D:\source\repos\vtech\plugins\filterizr\FilterItems.d.ts	1	
Error		Build:Module '"./ActiveFilter"' has no exported member 'Filter'.	vtech	D:\source\repos\vtech\plugins\filterizr\Filterizr.d.ts	4

**Comment by REJack** [comment]
Use only Filterizr's .ts files if you want build it by yourself, you should use the .js files instead.
