### ISSUE TITLE
sidebar-mini treeview sub items collapse 

### ISSUE THREAD

**Issue by mmorganGitHub** [ColorlibHQ/AdminLTE#2368]
- [x] Feature request
* AdminLTE Version:  v3

In v2 the sidebar treeview sub items collapsed when you clicked the sidebar into the mini state. Then expanded during hover.

Also is it possible to keep the sidebar collapsed after page change

**Comment by REJack** [comment]
> In v2 the sidebar treeview sub items collapsed when you clicked the sidebar into the mini state. Then expanded during hover.

I personally like the new behavior, but I'll add a custom class for the old behavior 😄 

> Also is it possible to keep the sidebar collapsed after page change

It's possible with the `enableRemember` option for PushMenu, more details in the [docs](https://adminlte.io/docs/3.0/javascript/push-menu.html). But it's JS driven this can produce a visible state change after page loaded (based where you load the js files), I personally build this everytime in my app to avoid this.

**Comment by REJack** [comment]
I've added `.nav-collapse-hide-child` for the v2 behavior in v3-dev branch.

**Comment by mmorganGitHub** [comment]
Thank you

**Comment by REJack** [comment]
Changes released with v3.0.0 😄
