### ISSUE TITLE
info box icons aren't vertical alligned

### ISSUE THREAD

**Issue by GuxMartin** [ColorlibHQ/AdminLTE#2369]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0-rc.6 
* Operating System: Linux/Ubuntu 18.04 
* Browser (Version): Chrome (Latest)  

### Description:
info box icons aren't vertical alligned

![example](https://user-images.githubusercontent.com/9992433/67791954-f1e86880-fa3d-11e9-8710-c0d160f0e841.jpg)

**Comment by REJack** [comment]
Thanks for reporting this issue, I found the bug and fix it soon.

**Comment by REJack** [comment]
I fixed it in the v3-dev branch

**Comment by REJack** [comment]
Changes released with v3.0.0 😄
