### ISSUE TITLE
Select2 Padding Issue with text-sm  class

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2370]
Hi @REJack it's take a long time to understand what is wrong with my code and my select 2 padding, finally i short out this. There is issue if we use `.text-sm` class inside `.content-wrapper`. Select 2 padding not work properly.

Have a Look before `.text-sm` class
![image](https://user-images.githubusercontent.com/29248598/67921655-618d5d80-fbce-11e9-8965-0f5d8a55a1d3.png)

And after using `.text-sm` class
![image](https://user-images.githubusercontent.com/29248598/67921721-a2857200-fbce-11e9-9416-234be8eefd64.png)

Hope you get this what im taking about

**Comment by REJack** [comment]
I've added a fix for the builtin theme in v3-dev branch 😄 .

**Comment by deepak458** [comment]
@REJack  also check this:
![image](https://user-images.githubusercontent.com/29248598/67938918-754cba00-fbf6-11e9-9f54-b2f4cdbacb13.png)

**Comment by REJack** [comment]
Are you think the left padding is too less on the builtin theme?

The bugs in the bootstrap4 theme need a seperate issue on the theme repo 😄

**Comment by REJack** [comment]
I've updated the select2 style again in v3-dev branch to get a similar look beside form-control/custom-form selects or inputs

**Comment by REJack** [comment]
Changes released with v3.0.0 😄
