### ISSUE TITLE
All the starter pages are broken

### ISSUE THREAD

**Issue by stevehomer** [ColorlibHQ/AdminLTE#2371]
### Issue type:

- [ x] Bug report       

### Environment:
* AdminLTE Version:  2.4.4,  2.4.11, 2.4.18 etc
* Operating System:  Win 10
* Browser (Version):  Chrome latest

### Description:

The starter page is broken. The left hand menu is not working correctly ie when you click on a sub menu item the highlight does not work. Compare starter.html with AdminLTE-2.4.x/index.html

If you click on a sub menu link in the latter works correctly.

Rather peed as was trying to start a complete rebuild tonight.

If there is a quick fix and someone knows it pls email!

**Comment by REJack** [comment]
I can't reproduce this bug on the live demo, both pages work do the same.

May you can post your html markup of the sidebar, also a preview image would be awesome 😄

**Comment by stevehomer** [comment]
I know this must sound completely anal but if I am about to rebuild the whole thing I don't want to have to spend hours tracking down little things! I am not a great programmer and finding them can take hours. 

In starter for `2.3.11` on `mouseover` or `click` a highlight is added to the activated (?) top level menu.


![image](https://user-images.githubusercontent.com/7356099/68025108-e9916700-fca3-11e9-95fd-6dc9828ffc21.png)


With `2.4.18` the highlighted link remains on the currently active menu item. 

![image](https://user-images.githubusercontent.com/7356099/68025500-d29f4480-fca4-11e9-8c85-9a5ad07d95b1.png)


NB: In both images the "Link in level 2" was hovered over.


I know this is tiny but it just made me nervous. I have spent many hours sorting out tiny things when they go wrong (ie when I screw something up) I just want to start from somewhere rock solid.

Grateful for any pointers.

**Comment by stevehomer** [comment]
Was this fixed or did you still not understand??

**Comment by REJack** [comment]
No it's not fixed, but AdminLTE v2.4 isn't maintained anymore. It didn't recieved any updates since the v2.4.18 is released and the v3.0 is fully released.
