### ISSUE TITLE
Forgot Password, Recover Password Pages

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2373]
### Issue type:
- [ ] Feature request 

You can also add forgot password, and change password page into demo page.

i know that is easy but in your demo it's look more good and more relevent.

**Comment by REJack** [comment]
For v3?

**Comment by REJack** [comment]
"change password page" for like login page or default with sidebar?

**Comment by deepak458** [comment]
@REJack  Like Login Page

- Also One FAQ page Like [Check](https://www.wrappixel.com/demos/admin-templates/pixeladmin/main/faq.html)
- Search Page Also

**Comment by REJack** [comment]
I'll look over it and may I add this to v3.0, forgot password and recover password is not hard :P

> - Also One FAQ page Like Check
> - Search Page Also

@deepak458 these two examples are already requested in #2359 and will added in v3.1.0.

**Comment by deepak458** [comment]
@REJack waiting for the V3.0

**Comment by REJack** [comment]
Release online 😄 with forgot password and recover password demo.
