### ISSUE TITLE
AdminLTE v3.0.0 released

### ISSUE THREAD

**Issue by REJack** [ColorlibHQ/AdminLTE#2375]
Hey Folks,

I've recently published AdminLTE v3.0.0 🎉  with these last changes/fixes:
- fixed info box icon aligning
- added .nav-legacy
- added .nav-collapse-hide-child
- fixed sidebar-light-hover-bg & sidebar-light-active-color
- removed mozilla dotted border from focus links
- fixed select2 paddings/margins 
- corrected select2 paddings to change look similar to form-control/custom-form select
- added forget password & recover password demo 
- fixed card default border after adding nav tabs support

For the complete changelog [look here](https://github.com/ColorlibHQ/AdminLTE/compare/v3.0.0-rc.6...v3.0.0).

Overall I want to say thanks for great help with bug/error reports and enhancement ideas while the v3 development.

We have also new stuff on the list for AdminLTE v3.1.0, we planned to add RTL Support, more demo examples and much more.

regards REJack

**Comment by mzy666888** [comment]
when can download on cdnjs？

**Comment by REJack** [comment]
Normally cdnjs need 1-2 days to update it.

**Comment by REJack** [comment]
@mzy666888 You can also use [jsDelivr](https://www.jsdelivr.com/package/npm/admin-lte)

**Comment by BassemN** [comment]
Congratulations for version 3 release :)

**Comment by ChineseGhost** [comment]
How can I custom the main sidebar like I test in the demo? Please advice.

**Comment by gittmy** [comment]
Congratulations for version 3 release :)

**Comment by cataclysmuprising** [comment]
Thanks a lot for your hard works.. Cheer !

**Comment by leogitpro** [comment]
The default card component header the underline style still is: border-bottom: none for v3.0.0.

**Comment by REJack** [comment]
Thanks 🍻 😄 I will release soon v3.0.1 with a small fix and updated plugins.

@ChineseGhost That are only addtional classes or classes to replace, like to change the sidebar color you need to change `.sidebar-dark-primary` to `.sidebar-dark-purple` on `.main-sidebar` for purple active color in sidebar or add `.nav-flat` on `.nav-sidebar` for flat sidebar style for more options look at the docs [main-sidebar](https://adminlte.io/docs/3.0/components/main-sidebar.html) / [color variations](https://adminlte.io/docs/3.0/layout.html).

**Comment by ChineseGhost** [comment]
@REJack Thank you very much for your reply. Now I have got the design I want.  👍👍👍👍

**Comment by BassemN** [comment]
@REJack Some of the AdBlock extension like [AdGuard AdBlocker](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg) hide class `brand-link` as you can see [here](https://user-images.githubusercontent.com/3768012/68127051-bc4fed80-ff1d-11e9-851c-87b919e33249.png).

**Comment by REJack** [comment]
@BassemN I can't replicate this with AdGuard, I see the brand-link.

**Comment by BassemN** [comment]
@REJack I tested it again and the brand-link is hidden, for more details please check this [image](https://user-images.githubusercontent.com/3768012/68140609-c7624800-ff34-11e9-9e58-85cb7a642d06.png).

**Comment by Rainzart** [comment]
Congratulations for v3 and thanks for hard work! :D

**Comment by danielsobrinho** [comment]
Congratulations! Thanks for the work and I hope to contribute sometime. Thanks!

**Comment by REJack** [comment]
@BassemN I still can't reproduce this, see this [image](https://user-images.githubusercontent.com/1554582/68204962-70f31900-ffc9-11e9-9717-dcf802e73d5e.png). May you have custom settings in adguard or something else.

**Comment by BassemN** [comment]
@REJack The issue is on Chrome but on Firefox there is no issue.

**Comment by Lycantant** [comment]
Finally. Thank you for your hard work 👍

**Comment by REJack** [comment]
@BassemN Even on Chrome I can't reproduce this, see this [image](https://user-images.githubusercontent.com/1554582/68287731-7c0a7f80-0083-11ea-9bd6-75baae1de625.png).

**Comment by BassemN** [comment]
@REJack I'm so sorry if this issue is only at my end. Anyway, Thanks a lot for your efforts.

**Comment by Jeckerson** [comment]
@REJack Will there be upgrade guide like for previous versions?
Example: https://adminlte.io/docs/2.4/upgrade-guide

**Comment by REJack** [comment]
@Jeckerson Loom at this 😄 , https://adminlte.io/docs/3.0/upgrade-guide.html

**Comment by benlinx1018** [comment]
Congratulations for version 3 release :)

**Comment by Raoch** [comment]
Is there a reason the homepage still links to v2 docs? I can only find v3 docs via google/links above

**Comment by REJack** [comment]
> Is there a reason the homepage still links to v2 docs? I can only find v3 docs via google/links above

Yep I don't find time to update the site and I have no access to the old self-created CMS where the page is build. I will create soon the v3.1.0-rc0 to test it in some private projects and may some other test it too After the v3.1.0 release I will create a new Page ^^
