### ISSUE TITLE
remove jquery as a dependency

### ISSUE THREAD

**Issue by lastlink** [ColorlibHQ/AdminLTE#2376]
**Is your feature request related to a problem? Please describe.**
Remove jquery as a dependency

**Describe the solution you'd like**
Have vanilla javascript or some kind of adminlte js functions. Maybe use as web components

**Describe alternatives you've considered**
Right now I pull in the adminlte css and use plain vuejs and javascript to emulate actions cutting down my dependency size

**Comment by REJack** [comment]
This is would cause a huge plugin change, but I'll look into it may I add this change in v3.1.0. 

I would rebuild it in vanilla javascript and additional a jquery plugin version for quick updates without error. I am not familiar with web components.

**Comment by lastlink** [comment]
web components is a way to write your ui frameworks to be js framework agnostic (meaning it would work in vuejs, react, angular) This would probably be a much bigger change (shouldn't be super complicated) than separating out the jquery plugins into separate js files and having vanilla js to power most of admin lte.

**Comment by REJack** [comment]
I need to find a tutorial for web comopnents, then I can decide if I can do it easy 😄 a PR is also welcome.

**Comment by lastlink** [comment]
Yah webcomponents would be the biggest change. But removing the jquery dependencies or separating them would be more optimal.
Here is one reference for webcomponents: https://github.com/mateusortiz/webcomponents-the-right-way

**Comment by oliverlj** [comment]
Good luck for treeview slideDown :)

**Comment by reyberyturiaga** [comment]
The bootstrap team is already set on removing jQuery dependency when version 5 is released:

https://github.com/twbs/bootstrap/issues/28342

It might be wise to wait for them to finish their implementation and just start working from that. At least that would cut down the burden of maintenance on this project.

**Comment by REJack** [comment]
> Good luck for treeview slideDown :)

The slides will be the hardest part of the moving.

> The bootstrap team is already set on removing jQuery dependency when version 5 is released

I know 😄 the v5 changes look really nice.

> It might be wise to wait for them to finish their implementation and use that as starting point. At least that would cut down the burden of maintenance on this project.

That's true but Bootstrap 5 woulde cause a new major version of AdminLTE, also the release date is not announced yet.

May I'll move this issue to AdminLTE v4, but this is still a nice feature for v3.1 and it would help for implementations in angular, react & vue.

**Comment by oliverlj** [comment]
for the moment, i did the slide in css with max-height but it is not optimal
````scss
.nav-sidebar .menu-open > .nav-treeview {
  max-height: 300px;
  transition: max-height 0.3s ease-in-out;
}

.nav-sidebar .nav-treeview {
  display: block;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.3s ease-in-out;
}
````

**Comment by REJack** [comment]
After some small test I decided to move this Issue to v4.0, Bootstrap 5 brings nice utils for easy adaption from jquery like the EventHandler, SelectorEngine and other small helper functions also the collapse component in v5 will help us to remove jquerys slide functions.
