### ISSUE TITLE
Card- * styles do not work

### ISSUE THREAD

**Issue by charlienux** [ColorlibHQ/AdminLTE#2378]
It seems that the card-primary card-success card-warning card-danger styles were removed.

**Comment by charlienux** [comment]
Reviewing I found that there are other bg- * classes that help change colors.

For example.
`` <div class = "card-header bg-primary> Header </div>
``

**What should be corrected then are the examples that appear on the Widgets page.**

I guess the card-outline no longer works.

**Comment by REJack** [comment]
I've fixed the bug in the master repo, I'll release v3.0.1 soon with this fix.
