### ISSUE TITLE
[BUG] Broken card-primary|success|etc classes after release

### ISSUE THREAD

**Issue by romaven** [ColorlibHQ/AdminLTE#2379]
**Describe the bug**
If I use `<div class="card card-outline card-primary">` I have a problem
Was
![image](https://user-images.githubusercontent.com/13623163/68076551-24d88680-fdc7-11e9-850d-a33e19ba164f.png)
Now
![image](https://user-images.githubusercontent.com/13623163/68076554-33bf3900-fdc7-11e9-8119-60b5608137df.png)

**To Reproduce**
1. Use `<div class="card card-outline card-primary">`

**Environment (please complete the following information):**
 - AdminLTE v3.0.0
 - Ubuntu 18.04
 - Chrome (Latest)

**Comment by REJack** [comment]
Duplicate of #2378
