### ISSUE TITLE
How do I use AdminLTE 3.X in my Django project?

### ISSUE THREAD

**Issue by ghost** [ColorlibHQ/AdminLTE#2382]
I don't know what those files are needed when they are needed.

**Comment by rupin** [comment]
You can look at my django application to understand more https://github.com/rupin/WrittenAudioWebsite

**Comment by d-demirci** [comment]
You can check it out here. [https://github.com/d-demirci/django-adminlte3](https://github.com/d-demirci/django-adminlte3)
