### ISSUE TITLE
[BUG] Content margin on collapsed sidebar without sidebar-mini

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2383]
**Sidebar Container Not Closed**
When we remove attribute class **sidebar-mini** from **body** tag
background/container of Sidebar not closed,
both in firefox and chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/14267724/68185271-be748380-ffd3-11e9-973f-6eaa76e896fd.png)

when we click humberger icon, to hide sidebar:

![image](https://user-images.githubusercontent.com/14267724/68185148-6b9acc00-ffd3-11e9-941a-2261901217b7.png)

**Environment:**
 - AdminLTE Version:  v3.0.0
 - Operating System:  Windows 10
 - Browser (Version): Firefox(latest), Chrome (lates)

**Comment by REJack** [comment]
I've fixed this in master repo, it will released with v3.0.1 😄
