### ISSUE TITLE
[BUG]  In IE11, chartjs.html, the Donut Chart is expanding to vertical infinitely

### ISSUE THREAD

**Issue by monadgon** [ColorlibHQ/AdminLTE#2384]
In IE 11
The Donut Chart is expanding to vertical infinitely.

1. Go to 'index.html'
2. Click on 'Charts > ChartJS'
3. The doughnut chart is enlarged, and the box is growing up infinitely.
4. See Screenshot

**Expected behavior**
The chartJS page should be displayed like chrome(latest).

**Screenshots**
![image](https://user-images.githubusercontent.com/511164/68261595-f804c780-0083-11ea-8b3a-769578e92a3d.png)

**Environment :**
 - AdminLTE Version: v3.0.0 (released)
 - Operating System:  Windows 10 Pro
 - Browser (Version): IE 11, Chrome (Latest)

**Comment by REJack** [comment]
Sadly I can't fix this and this is more an IE11 bug than plugin bug, I've added a workaround for this bug in the master repo.

**Comment by monadgon** [comment]
Thanks
