### ISSUE TITLE
[BUG] card with products table overlaps on mobiles

### ISSUE THREAD

**Issue by tikky** [ColorlibHQ/AdminLTE#2385]
Version: Admin LTE 3.0.0 final

Dashboard3, table with products
https://adminlte.io/themes/dev/AdminLTE/index3.html

on Safari (Iphone8) table rows are longer then table. Please take a look at screenshot:
![iphone_dashboard3](https://user-images.githubusercontent.com/546755/68297216-ad407b00-0096-11ea-9088-1c2324fe32b3.jpeg)

**Comment by REJack** [comment]
Thanks for reporting this issue, I've fixed it in the master repo.

**Comment by tikky** [comment]
I've added "table-responsive" in my copy.
Have tested, works fine.

I am happy to close the issue.
thx for fast response ...and all the effort to make AdminLte3

**Comment by REJack** [comment]
I've added `table-responsive` also on the `card-body` in my fix 😄.
