### ISSUE TITLE
[BUG] Buttons border disappears in Firefox

### ISSUE THREAD

**Issue by GuxMartin** [ColorlibHQ/AdminLTE#2386]
**Describe the bug**
On active button, border disappears and affects others elements. Only in Firefox

**To Reproduce**
1. Go to https://adminlte.io/themes/dev/AdminLTE/pages/UI/buttons.html
2. Click on any button, recomendable buttons on second column
3. See bug affects all the table

**Expected behavior**
Border not disappears

**Screenshots**
![bug](https://user-images.githubusercontent.com/9992433/68310417-963d6100-0075-11ea-9b30-30d62b773bb7.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System:  Ubuntu 18.04
 - Browser (Version): Firefox 70.0.1

**Comment by GuxMartin** [comment]
Click on outline buttons is more evident

**Comment by REJack** [comment]
Thansk for reporting this issue, I've fixed in master repo 😄
