### ISSUE TITLE
[BUG] select2 'allowClear' not work

### ISSUE THREAD

**Issue by Superllb93** [ColorlibHQ/AdminLTE#2387]
**Describe the bug**
Config select2 like this:
```
$('.select2').select2({
    allowClear: true
})
```
it causes a clear button ("x" icon) to appear on the select box, like this:

![image](https://user-images.githubusercontent.com/49815294/68315201-5ec0ca00-00f2-11ea-9503-c7f1a6d45048.png)

so, clicking the clear button will clear the selected value. Unfortunately, it does not work, error as follows:

![image](https://user-images.githubusercontent.com/49815294/68315232-6a13f580-00f2-11ea-9471-4b5741725b46.png)

**Comment by REJack** [comment]
I tried it with the demo files, to get it work I need also a placeholder like this 
```js
{
  placeholder: 'Please select one',
  allowClear: true
}
```

**Comment by Superllb93** [comment]
> I tried it with the demo files, to get it work I need also a placeholder like this
> 
> ```js
> {
>   placeholder: 'Please select one',
>   allowClear: true
> }
> ```

**Comment by Superllb93** [comment]
thanks, it works

if there are multiple `select`, setting data-placeholder maybe be more suitable:


```
<select id="a" class="form-control select2" data-placeholder="Please select a"></select>

...

<select id="b" class="form-control select2" data-placeholder="Please select b"></select>
```
