### ISSUE TITLE
[BUG] CSS compile error

### ISSUE THREAD

**Issue by jcheros** [ColorlibHQ/AdminLTE#2388]
**Describe the bug**
Error when try to compile the css running `npm run css`

$ npm run css

> admin-lte@3.0.0 css E:\desarrollo\repos\social\templates\AdminLTE-3.0.0
> npm-run-all --sequential css-compile css-prefix css-minify

> admin-lte@3.0.0 css-compile E:\desarrollo\repos\social\templates\AdminLTE-3.0.0
> npm run css-compile-bash build/scss/AdminLTE.scss dist/css/adminlte.css

> admin-lte@3.0.0 css-compile-bash E:\desarrollo\repos\social\templates\AdminLTE-3.0.0
> node-sass --importer node_modules/node-sass-package-importer/dist/cli.js --output-style expanded --source-map true --source-map-contents true --precision 6 
$* "build/scss/AdminLTE.scss" "dist/css/adminlte.css"

An output directory must be specified when compiling a directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-lte@3.0.0 css-compile-bash: `node-sass --importer node_modules/node-sass-package-importer/dist/cli.js --output-style expanded --source-map true --source-map-contents true --precision 6 $* "build/scss/AdminLTE.scss" "dist/css/adminlte.css"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-lte@3.0.0 css-compile-bash script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jose.chero\AppData\Roaming\npm-cache\_logs\2019-11-06T16_00_51_702Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jose.chero\AppData\Roaming\npm-cache\_logs\2019-11-06T16_00_53_042Z-debug.log
ERROR: "css-compile" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-lte@3.0.0 css: `npm-run-all --sequential css-compile css-prefix css-minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-lte@3.0.0 css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jose.chero\AppData\Roaming\npm-cache\_logs\2019-11-06T16_00_53_393Z-debug.log
[2019-11-06T16_00_53_393Z-debug.log](https://github.com/ColorlibHQ/AdminLTE/files/3815510/2019-11-06T16_00_53_393Z-debug.log)
[2019-11-06T16_00_53_042Z-debug.log](https://github.com/ColorlibHQ/AdminLTE/files/3815516/2019-11-06T16_00_53_042Z-debug.log)

**To Reproduce**
Running `npm run css`

**Expected behavior**
Compiled CSS from SCSS

**Environment (please complete the following information):**
 - AdminLTE Version: [v3.0.0]
 - Operating System:  [Win10]
 - Browser (Version): [Chrome (Latest)]

**Additional context**
Node version 10.16.0 or 8.16.2

**Comment by REJack** [comment]
I've fixed this bug in master repo, it will released soon 😄

**Comment by jcheros** [comment]
Thanks, it works perfect.
