### ISSUE TITLE
[BUG] Bootstrap Slider without tooltip

### ISSUE THREAD

**Issue by guillaumecardon** [ColorlibHQ/AdminLTE#2389]
Bootstrap Slider used in AdminLTE v3 is based on Seiyria github : https://github.com/seiyria/bootstrap-slider

On the following example, we can see a black tooltip indicating the value of slider
https://seiyria.com/bootstrap-slider/#example-1

On AdminLTE v3.0.0, no tooltip.

**To Reproduce**
1. Go to 'UI Sliders'
2. Click on a slider
3. No tooltip displayed

**Expected behavior**
The default tooltip indicating the value of slider.

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System:  Windows 10 1903
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
I've added a fix to show the tooltip in master branch (works but not 100% correct), bootstrap-slider is still not 100% BS4 ready.
