### ISSUE TITLE
[BUG] Starter Page is not available via 3.x Docs

### ISSUE THREAD

**Issue by o0fatigue** [ColorlibHQ/AdminLTE#2391]
**Describe the bug**
Starter Page is not available via 3.x Docs

**Screenshots**
![image](https://user-images.githubusercontent.com/13743801/68359568-ab8eba00-015f-11ea-9dee-0a18382edea8.png)

![image](https://user-images.githubusercontent.com/13743801/68359588-bea18a00-015f-11ea-925f-fbb5018fe46a.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System: macOS Catalina
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
I've fixed it in the docs in the master repo and adminlte.io/docs/3.0 will updated with the next release.

**Comment by o0fatigue** [comment]
Thanks a lot! I am able to access the starter page from master.
