### ISSUE TITLE
[FEATURE] SCSS Var Name Refactoring ?!

### ISSUE THREAD

**Issue by zAfLu** [ColorlibHQ/AdminLTE#2395]
**Is your feature request related to a problem? Please describe.**
Its not that easy to restyle adminLTE from scss without changing tons of vars.
For example (Check this image https://i.smatify.com/jgSMALOMo2cdpmol.png) to made a "dark mode" you need to change white to black and black to white. Or you just rename every var in scss  (  Tons of lines ^^)

**Describe the solution you'd like**
I would like to rename all the vars to make it easier to easily change color themes. 
Someting like: 

**Currently** 
```css
// stylelint-disable
$white:    #ffffff !default;
$gray-900: #212529 !default;

// Settings for the `<body>` element.
$body-bg:                   $white !default;
$body-color:                $gray-900 !default;

```
**Should be**
```css
// stylelint-disable
$white:    #ffffff !default;
$gray-900: #212529 !default;

// New Custom Vars
$adminlte-custom-main-bg: $white !default;
$adminlte-custom-main-color: $gray-900!default;

// Settings for the `<body>` element.
$body-bg:                   $adminlte-custom-main-bg !default;
$body-color:                $adminlte-custom-main-color !default;

```

That would be much easier to restyle adminLTE without overriding every color var. You could easiely change ```$adminlte-custom-main-bg```to something you like and it would aplly everywhere you would expect it. 

To clarify: I dont want that someone else should do this work. Me and some friends would do the work and make a PR BUT we dont wanna waste time if you dont like this idea. So are you down with that or not? :)

**Comment by REJack** [comment]
That's a nice idea, feel free to create a PR 😄 but please use shorter variable names, 

A dark mode for the AdminLTE is also a great idea this would a great add for v3.1.

**Comment by Smatify** [comment]
Great that you are into this!

I just started working on an attempt to get a dark mode up (I'm one of the `some friends` @zAfLu mentioned :D) - does this color scheme seems _okayish_ for you? It's still in an early iteration

![](https://i.smatify.com/PJV4U62jfexkwkCn.png)

**Comment by REJack** [comment]
I would stay with the sidebar dark color and set the content-wrapper background color to darken('sidebar dark color', 5%) 😄 also the card background would get the bg-dark color.

This would look like this, navbar is set to navbar-dark, card has bg-dark and I've added via dev tools content wrapper background color `#292d32` and body color `#f8f9fa`
![Screenshot_2019-11-10 AdminLTE 3 Blank Page](https://user-images.githubusercontent.com/1554582/68542889-e6d3f780-03b0-11ea-8828-3aea5c7ee99c.png)

**Comment by danny007in** [comment]
closing because of 
we are using `prefered-color-scheme` in v4
