### ISSUE TITLE
[BUG] Angular attributes getting lowercased in Sidebar Menu

### ISSUE THREAD

**Issue by MPapst** [ColorlibHQ/AdminLTE#2396]
**Describe the bug**
I'm trying to integrate AdminLTE v3 into my angular project.
Nevertheless all of the routerLink Attributes are getting lowercased and then do not work (I'm not pretty sure it is because of this, but the only thing I found right now).

**To Reproduce**
1. clone the fresh repo
2. add attribute ```routerLink="hallo"``` to index.html line 192
![image](https://user-images.githubusercontent.com/16494676/68545137-805bd300-03ca-11ea-852b-22ea358ecd2c.png)
3. run ```npm run dev```
4. inspect sidebar
![image](https://user-images.githubusercontent.com/16494676/68545146-89e53b00-03ca-11ea-9f70-5f82176d9d26.png)

**Expected behavior**
Attributes should not changed.

**Environment (please complete the following information):**
 - AdminLTE Version: commit f80e848273aec1161b6245125fe24fa6a19fcbc7
 - Operating System:  Win 10
 - Browser (Version): Chrome

**Additional context**
This only happens in the sidebar. In the main content there is no lowercasing.

**Comment by REJack** [comment]
For me this only a display issue, routerLink will only used by Angular default routerLink will not interpret it and I guess they lowercase this in the inspector in view-source it is correct.

**Comment by REJack** [comment]
Also `npm run dev` uses browser-sync, idk if it supports angular 😄

**Comment by MPapst** [comment]
yes you are right - this is just an issue of the chrome inspector. Need to figure out what the reason is, the link is not working.

There was no need to be angular compatible, just because it happened even without angular :)

**Comment by REJack** [comment]
> yes you are right - this is just an issue of the chrome inspector. 

👍 

> Need to figure out what the reason is, the link is not working.

Try to wrap routerLink in `[]` like `[routerLink]` sometimes this helped me with my angular tests.  But idk why this makes a difference 🤣 

P.S. Falls du noch andere probleme hast oder sogar ideen für neuerungen immer her damit 😃

**Comment by MPapst** [comment]
Actually it was a missing import of ```RouterModule``` in the corresponding Module...

Ich melde mich, wenn mir noch etwas auffällt. 
Vielleicht kann ich ja sogar eine Anleitung zur Übernahme und zum aktuell halten für Angular schreiben. Ich  finde die Integration etwas mühselig, weil die Standalone Seite sehr unterschiedlich zu einer Angular Architektur ist.
Vielleicht könnte man da etwas modularisieren (Aber vielleicht stelle ich mir das auch zu einfach vor - Webfrontend ist nicht so mein Steckenpferd :))
