### ISSUE TITLE
Calendar card-body padding[FEATURE]

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2397]
In the calendar preview it's inside card and there is 0 padding, what if i want to show only calendar in full page. It's look nasty. can you just write some CSS for that also for padding along with calendar border and  calendar  themes.

**Comment by REJack** [comment]
In the calendar example is only a padding 0 on card-body with `.p-0`, all other styles comes directly from fullcalendar, AdminLTE has actually no extra classes for fullcalendar.

Also example pictures / code would be awesome 😄
