### ISSUE TITLE
conflict bootstrap jasny file input

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2398]
Here the example from jasny (https://www.jasny.net/bootstrap/3.2.0/javascript/#fileinput-examples)
![image](https://user-images.githubusercontent.com/14267724/68579804-9e4b3580-04a7-11ea-8b1e-9bbf56b367e7.png)

it when file was selected:
![image](https://user-images.githubusercontent.com/14267724/68579907-d5214b80-04a7-11ea-94c9-99c8b524d8b5.png)

**Its integrated with Admin LTE**

![image](https://user-images.githubusercontent.com/14267724/68579972-f3874700-04a7-11ea-9da4-8ffbac120cc6.png)

when select same image file:
![image](https://user-images.githubusercontent.com/14267724/68580001-069a1700-04a8-11ea-9b9a-f32e23cf399d.png)

How to fixed it?

**Environment (please complete the following information):**
 - AdminLTE Version:  v3.0.0
 - Operating System:  Windows 10
 - Browser (Version): Chrome (Latest), Firefox (latest)

**Comment by REJack** [comment]
I've looked over jasny-bootstrap, if you want to use jasny-bootstrap you need to use v4.0.0 and load the css and js file from it in your project. The images look like you have not loaded the css file.
