### ISSUE TITLE
[BUG] in "plugins/filterizr" in visual studio 2019

### ISSUE THREAD

**Issue by starnew123** [ColorlibHQ/AdminLTE#2399]
AdminLTE-3.0 giving 4 error in visual studio 2019 when i debugging.

1. "plugins/filterizr/ActiveFilter" has no exported member 'Filter'. Did you mean to use 'import Filter from "plugins/filterizr/ActiveFilter"' instead?	"plugins\filterizr\FilterItems.d.ts"

2. "plugins/filterizr/ActiveFilter" has no exported member 'Filter'. Did you mean to use 'import Filter from "plugins/filterizr/ActiveFilter"' instead?	"plugins\filterizr\Filterizr.d.ts"

3. "plugins/filterizr/FilterizrOptions/defaultOptions"' has no exported member 'RawOptions'. Did you mean to use 'import RawOptions from "plugins/filterizr/FilterizrOptions/defaultOptions" instead?	"plugins\filterizr\Filterizr.d.ts"

4. "plugins/filterizr/FilterizrOptions/defaultOptions"' has no exported member 'RawOptionsCallbacks'. Did you mean to use 'import RawOptionsCallbacks from "plugins/filterizr/FilterizrOptions/defaultOptions"' instead? "plugins\filterizr\FilterContainer.d.ts"

i m using 
windows 10
Adminlte-3.0(Latest)
Visual Studio 2019

**Comment by REJack** [comment]
According to this error you try to compile filterizr (.ts -> .js), AdminLTE doesn't compile plugins we use only pre-compiled plugin files.
