### ISSUE TITLE
dataTables search and pagination dropdown misaligned

### ISSUE THREAD

**Issue by yusofy** [ColorlibHQ/AdminLTE#2400]
**Describe the issue**
dataTables pagination and search are misaligned in adminLTE. This only happens when I use `dom: 'Blfrtip'` to be able to use export buttons.

**Expected behavior**
They should be aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/6264190/68821227-5b2dc580-0653-11ea-953a-dd8d4a612672.png)

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.0

**Additional context**
Code i'm using. 
```
$(document).ready(function (){   
     var table = $('#contacts').DataTable({
        'ajax': '<URL>', 
        dom: 'Blfrtip', 
        'processing': true,
        'serverSide': true,
        'scrollX': true,
        buttons: [
        'copy', 'csv'
        ],
        'order': [1, 'asc']
     });
```

**Comment by REJack** [comment]
It look like you doesn’t loaded the BS4 css/js files from DataTables, this should fix the style bugs.

**Comment by REJack** [comment]
If you loaded all files, then it's a bug from datatables itself. But try this dom 
```js
"<'col-sm-12 col-md-6'Bl>frtip"
``` 
or
```js
"<'row'<'col-sm-12 col-md-6'Bl><'col-sm-12 col-md-6'f>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>"
```

**Comment by yusofy** [comment]
Hey @REJack,

I have the following files put in:
```
<link rel="stylesheet" href="plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<link rel="stylesheet" href="plugins/datatables-buttons/css/buttons.bootstrap4.css">
<script src="plugins/datatables/jquery.dataTables.js"></script>
<script src="plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="plugins/datatables-buttons/js/buttons.bootstrap4.js"></script>
<script src="plugins/datatables-buttons/js/dataTables.buttons.js"></script>
<script src="plugins/datatables-buttons/js/buttons.html5.js"></script>
```
Using your suggestion, the misalignment has become better but it seems the buttons are now causing the misalignment.
```
"<'row'<'col-sm-12 col-md-6'Bl><'col-sm-12 col-md-6'f>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>"
```
Here is a screenshot. 
![image](https://user-images.githubusercontent.com/6264190/68868011-5cdfa380-06bc-11ea-8467-dd37af3931c7.png)

I saw on datatables that the issue was fixed a while back which is why I opened the issue here. I also read it could be an issue with cross files from different plugins but I couldn't tell which ones may be causing them.

**Comment by yusofy** [comment]
I played a little with the dom now that it made sense. I changed it to be like this:
```
"<'row'<'col-sm-12 col-md-4'l><'col-sm-12 col-md-4'B><'col-sm-12 col-md-4'f>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>"
```

Now the output is like this: 
![image](https://user-images.githubusercontent.com/6264190/68868912-f65b8500-06bd-11ea-9357-d58976c2eaba.png)

I just now need to figure out the button formatting! Thank you for your help!!!! Also - Love your template.
