### ISSUE TITLE
Close menu SideBar for default

### ISSUE THREAD

**Issue by TranceDevCode** [ColorlibHQ/AdminLTE#2402]
**how can close the menu sidebar for default.**
Hello how are you? [...]

hey ColorlibHQ thank for your template... i need make a little change in the theme, just leave close the menu side in default option, because for default when i install the adminlte is open, but i need leave close for default this option...

How can do it, have the Admin LTE 3

![image](https://user-images.githubusercontent.com/50996233/68987701-c5d53180-080a-11ea-9905-2dd3dcc5983a.png)

**Comment by REJack** [comment]
If I understand you correct, you want a collapsed sidebar on page load?

If yes, simply add `.sidebar-collapse` on `body`.

**Comment by TranceDevCode** [comment]
Yes, that's work for me, thank u!
