### ISSUE TITLE
Integrating with Angular App

### ISSUE THREAD

**Issue by axript** [ColorlibHQ/AdminLTE#2403]
Pleaae how do I integrate the theme with my angular app.

**Comment by REJack** [comment]
Sadly I can't help you with that, I don't use Angular.

May @MPapst can help you with this 😄.

**Comment by MPapst** [comment]
A basic integration is not that complicated.
* copy AdminLTE directory under assets
* Update your index.html to import all the css and script files that are needed for AdminLTE (use index.html from AdminLTE to figure out which are those), modify the paths to match the assets folder. As an alternative you can install the dependencies using npm and reference them directly (I did that partly)
* Modify your app component with the content of AdminLTE, to achieve that I created a Layout Module (do not forget to import RouterModuel in here :)) in Angular having 3 components: 
  * sidebar component (containing the menu)
  * header component
  * footer component

When finished you can start using the theme. 
For a better integration you can create your own angular components for each AdminLTE widget as needed.
