### ISSUE TITLE
CardWidget - not possible to change collapse icon

### ISSUE THREAD

**Issue by vmartis** [ColorlibHQ/AdminLTE#2404]
I would like to change icons of collapse button. When I defined button with another icon than 'fa-minus', changing of icons is not working when collapse button is pushed.

I tried put config into CardWidget constructor:

const element: any = $('#card')
const cardWidget = element.CardWidget({ collapseIcon: 'fa-chevron-right', expandIcon: 'fa-chevron-down' })

but it had no effect. I tried to debug widget, and it looks like the bug is in "_jQueryInterface(config)" function. "config" parameter is never passed into CardWidget constructor, and internal "_settings" object is initialized only in constructor.

**Comment by REJack** [comment]
It should be fixed with the latest commit e24c4d0. 😄
