### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContext' of null at HTMLDocument

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2405]
**Describe the bug**
I tried to integrate AdminLTE V3.0 into my Application.

**Expected behavior**
When I launced the Application, I expected the Dashboard V1 to display as its in AdminLTE v1 dashboard v1, but I got this error:

`jquery.min.js:2 Uncaught TypeError: Cannot read property 'getContext' of null
    at HTMLDocument.<anonymous> (dashboard.js:113)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)`

See the diagram:
**Screenshots**
![adminlte_jquery2](https://user-images.githubusercontent.com/34077129/69221273-24860c80-0b77-11ea-8637-d6bd82538211.PNG)

Then this made the dashboard not to display the graph appropriately:

![adminlte_template](https://user-images.githubusercontent.com/34077129/69220964-72e6db80-0b76-11ea-9f55-3fe6e38bcd9a.PNG)

**Environment :**
 - AdminLTE Version: [v3.0.0]
 - Operating System:  [Windows
 - Browser (Version): [Chrome]

**Additional context**
How do I resolve this please?

**Comment by REJack** [comment]
Do you get other errors/warings too or only the warning and the one error? 
Does this error comes also on the [online demo](https://adminlte.io/themes/v3/)?
Did you changed the content in Dashboard 1?

**Comment by noblemfd** [comment]
@REJack  - 1. No, I didn't get other errors/warnings
2. No, this error is not on the online demo.
3.I didn't change the content in Dashboard 1

**Comment by REJack** [comment]
I've tested a bit the dashboard.js and the the error comes when the canvas (`<canvas id="revenue-chart-canvas">`) is not available, but the dashboard js files are only for demo purpose and not required.

**Comment by noblemfd** [comment]
OK. Thanks

**Comment by REJack** [comment]
Is this issue still open?

**Comment by noblemfd** [comment]
Yes, its still open? How do I close it since its resolved?

**Comment by REJack** [comment]
I don't understand, is your problem solved?

**Comment by noblemfd** [comment]
Yes, the problem is solved. Thanks

**Comment by spockyto** [comment]
The problem also appears in the demo version.
appears after a few seconds

**Comment by samrath15** [comment]
I am getting the same issue but this is my error. I don't know where and how to fix this. I don't see any issues other than this in my console.
o![image](https://user-images.githubusercontent.com/25046632/107165219-39b7a880-6980-11eb-97d6-941883ef3709.png)

**Comment by saif31617** [comment]
> I am getting the same issue but this is my error. I don't know where and how to fix this. I don't see any issues other than this in my console. I even removed all the code of admin lte and am compiling it with empty HTML just to see what is causing the issue. I read about the canvas id comment but not sure if it applies to me or I am don't understand how to apply it.
> Thanks
> o![image](https://user-images.githubusercontent.com/25046632/107165219-39b7a880-6980-11eb-97d6-941883ef3709.png)

have you solved this error kindly guide me

**Comment by wilca** [comment]
Hola, 
para solucionar este problema, debes de editar el archivo dashboard.js, en tu caso la que este utilizando
![image](https://user-images.githubusercontent.com/78506146/178060015-d2737666-e245-4ace-92d0-b50ac27e3ea2.png)

puedes borrar todo el archivo o tambien no hacer referencia a ese archivo, o tambien dejar las estadísticas que necesites
![image](https://user-images.githubusercontent.com/78506146/178060301-b9322c90-f34c-4183-b292-c0e2fbbda527.png)

despues de guardar
![image](https://user-images.githubusercontent.com/78506146/178060517-0cff5651-899e-405c-b0ba-8a4305d8f7e3.png)
