### ISSUE TITLE
[BUG] index3.html control-sidebar 

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2406]
**Describe the bug**
In index3.html the control-sidebar does't display corrected.

**To Reproduce**
1. Open index3.html
2. Click the control sidebar in the right top
3. Scroll to the bottom, you'll see the bug in the right bottom

**Expected behavior**
Should same as in index.html/index2.html

**Screenshots**
![image](https://user-images.githubusercontent.com/6952917/69392986-dad22900-0d12-11ea-8a6c-9398d391b47e.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.1
 - Operating System: Win10
 - Browser (Version): Chrome (Latest)

**Additional context**
I found some warning in demo.js, Is this correct?
![image](https://user-images.githubusercontent.com/6952917/69394263-816bf900-0d16-11ea-8484-e6d02a85e4e3.png)

**Comment by REJack** [comment]
I've fixed this bug and also the duplicate variable in demo.js 😄

**Comment by GerryGe** [comment]
Thank you very much for your reply.
