### ISSUE TITLE
[BUG] Card-outline and card-colors not working

### ISSUE THREAD

**Issue by theonly27** [ColorlibHQ/AdminLTE#2407]
The Card Header color, Card outline is not working.

**Comment by REJack** [comment]
Which version of AdminLTE you use v3.0.0 or v3.0.1?

**Comment by olsizotaj** [comment]
For example: <div class="card card-success">, "card-success" doesn't have any effect.

**Comment by REJack** [comment]
@olsizotaj Also which version of AdminLTE you use?

**Comment by olsizotaj** [comment]
@REJack i am using version 3.0.

Please navigate to this url: https://adminlte.io/docs/3.0/components/cards.html
Then go to the section "Card Variants" and see that all **Cards** have the same style even the class is different.

**Comment by REJack** [comment]
@olsizotaj Please update to v3.0.1, it's fixed in this version already. I'll update the docs tomorrow to v3.0.1.
