### ISSUE TITLE
[FEATURE] Form validation

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2408]
**Is your feature request related to a problem? Please describe.**
When submit form, we need do client validation.

**Describe the solution you'd like**
Integrate with jquery.validate.js and give some examples.

**Comment by REJack** [comment]
jQuery Validation is already added in AdminLTE but without examples right now, I'll add demo for it.

**Comment by REJack** [comment]
I've added a demo in the master repo, it will released with v3.0.2.

**Comment by GerryGe** [comment]
> I've added a demo in the master repo, it will released with v3.0.2.

Thanks a lot for your hard works.
