### ISSUE TITLE
Customize sidebar and header colors

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2409]
**Is your feature request related to a problem? Please describe.**
The sidebar color is not allowing the logo to really appear very well because the color is maroon.

**Describe the solution you'd like**
I want to change the sidebar color to Grey color and the header color to Maroon color.

![adminlte_sidebar](https://user-images.githubusercontent.com/34077129/69476266-429e7780-0dd8-11ea-8fec-f76a7538d305.PNG)

How do I achieve this?

**Comment by REJack** [comment]
To accomplish this you need to change CSS classes in your HTML markup. 
For the navbar you need to replace, `navbar-white navbar-light` with `navbar-dark navbar-maroon` on `main-header`.
For the sidebar you need to replace, `sidebar-dark-primary` with something like `sidebar-light-maroon` on `main-sidebar`.

**Comment by noblemfd** [comment]
In the main sidebar

`  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>
  </aside>`

How do I change the navbar

`<a href="index3.html" class="brand-link">`

to light-grey

**Comment by REJack** [comment]
do you use navbar fixed?

**Comment by noblemfd** [comment]
Yes, I used fixed navbar. I have something like this: 

`<aside class="main-sidebar sidebar-dark-primary elevation-3">
    <a href="index3.html" class="brand-link navbar-gray">
    <span class="brand-text font-weight-light">HRIS</span>
    </a>
   <div class="sidebar">`

![navsidebar](https://user-images.githubusercontent.com/34077129/69527185-10258380-0f6c-11ea-8a4a-30423b17a2b3.PNG)


But the grey colour for the navbar is too deep, I want to make it light-gray as shown below because of the logo:

![light_gray](https://user-images.githubusercontent.com/34077129/69527311-51b62e80-0f6c-11ea-92c5-5f441ea6d39f.PNG)

**Comment by REJack** [comment]
Add `.navbar-light` to `.brand-link` like `<a href="index3.html" class="brand-link navbar-light">`.

**Comment by noblemfd** [comment]
When I added

`<a href="index3.html" class="brand-link navbar-light">`

it becomes white instead of light-grey.

![navbarlight](https://user-images.githubusercontent.com/34077129/69528069-d9e90380-0f6d-11ea-961a-00d945988ec7.PNG)

What do I still need to do?

**Comment by REJack** [comment]
try `bg-gray-light` or `bg-gray` instead of `navbar-light`.

**Comment by noblemfd** [comment]
Thanks. Issue resolved
