### ISSUE TITLE
Couln't find profile tab

### ISSUE THREAD

**Issue by ferrybintang** [ColorlibHQ/AdminLTE#2410]
Hey,
on adminlte v2 there is profile tab in header but on v3 i couldn't find it especially sign out button cause i often use it, thank you and congratulations for v3

**Comment by codemunkie15** [comment]
There is a legacy user menu sample page on the demo. It has the profile header you are referring to.

https://adminlte.io/themes/dev/AdminLTE/pages/examples/legacy-user-menu.html
