### ISSUE TITLE
[BUG] Sidebar navigation link hover colour does not reflect accent colour

### ISSUE THREAD

**Issue by codemunkie15** [ColorlibHQ/AdminLTE#2411]
**Describe the bug**
When you hover over a sidebar navigation item the colour changes to blue. I thought that this would change depending on the accent colour I was using but this is not the case.

**To Reproduce**
Change the accent colour.
Hover over a sidebar navigation item.
Text colour is always blue. It does not consider the accent colour.

**Expected behavior**
I would expect the text colour to use the accent colour.

**Screenshots**
Here I have set the accent colour to yellow. The active item has a yellow background but the hover colour is still blue.
![image](https://user-images.githubusercontent.com/13065317/69488695-ea618700-0e64-11ea-805a-20c1dccdeafa.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll fix this soon.

**Comment by REJack** [comment]
I've added a fix in master repo.

**Comment by codemunkie15** [comment]
Thanks!

**Comment by codemunkie15** [comment]
The same thing is apparent on active input boxes too. Should these also be affected by the accent colour? i.e. the border colour when you are inside a textbox.

Thanks

**Comment by codemunkie15** [comment]
@REJack Should I raise a separate bug for the above issue?

**Comment by REJack** [comment]
No, you need not create a new issue for this. I'll fix this soon before releasing v3.0.2.

**Comment by REJack** [comment]
I've added a fix for form element focus border in master repo.
