### ISSUE TITLE
[BUG] iOS & macOS fixed navbar visibility bug

### ISSUE THREAD

**Issue by scotticles** [ColorlibHQ/AdminLTE#2412]
**Describe the bug**
IOS 13.2.3 using the fixed-topnav, the brand-link goes hidden where on android it still shows up. 

**To Reproduce**
1. Using an IOS device Go to https://adminlte.io/themes/dev/AdminLTE/pages/layout/fixed-topnav.html
2. Click on the bars / push menu / hamburger icon top left.

**Expected behavior**
The brand-link is supposd to swipe over with the menu but it does not.

**Screenshots**
IOS:
![image_from_ios](https://user-images.githubusercontent.com/186373/69502620-6e9c2480-0ece-11ea-9245-d5151ce8fd9a.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/186373/69502561-0b11f700-0ece-11ea-9d93-2569e69dce7a.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System:  IOS 13.2.3
 - Browse: Safari

**Comment by GerryGe** [comment]
I found the first time brand-link goes hidden, but after click the third times it will show.

**Comment by REJack** [comment]
Thanks for reporting this issue, I found also on my iPhone it shows if you scroll down 😄 I really need to fix this.

**Comment by REJack** [comment]
I've added a fix in master repo.
