### ISSUE TITLE
[BUG] Select2 select is not being displayed correctly

### ISSUE THREAD

**Issue by Jatapiaro** [ColorlibHQ/AdminLTE#2413]
**Describe the bug**
For some reason the select2 componentes are not displayed correctly.

**To Reproduce**
Try to put any select2 component on the screen

**Expected behavior**
The select does not look like the one in the examples

**Screenshots**
https://imgur.com/YLrpCWW

**Environment (please complete the following information):**
 - AdminLTE Version: [^3.0.0]
 - Operating System:  [macOS Catalina]
 - Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
Did you loaded the select2 css files after AdminLTE's css files?

**Comment by Jatapiaro** [comment]
Yes, I saw the examples code but I did not find anything different. For some reason I needed to specify the theme.

```
$('.select2').select2({
        theme: 'bootstrap',
});
```
