### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nikonov91-dev** [ColorlibHQ/AdminLTE#2414]
**Describe the bug**
The min-height of container ```<div class="content-wrapper" style="min-height: 10396px;">``` isnot recomputed after the sidebar is closed (clicking to burger btn) 

**To Reproduce**
1. open a page is logner 2 times than screen height; The sidebar must be opened;
2. Close the sidebar clicking the burger btn
3. scroll right down to the footer
4. see the empty space because of unupdated min-height is really bigger than needed when the body-width is become bigger Sidebar closed;

**Expected behavior**
expected to recompute the min-height on sidebar closing-opening

**Environment (please complete the following information):**
 - AdminLTE v3.0.0-beta.2 (as written in AdminLTE.js
 - linux mint
 - Chrome 78

**Comment by REJack** [comment]
Please update AdminLTE v3 to the latest version (v3.0.1) and check if the bug is still there.
