### ISSUE TITLE
can you add some plug-ins?

### ISSUE THREAD

**Issue by mhiStrat** [ColorlibHQ/AdminLTE#2415]
Hello, can you add some plug-ins?

1. Scrollbar style

2. Move back and forth

3. Label manager

**Comment by mhiStrat** [comment]
http://zui.sexy/

**Comment by REJack** [comment]
Please provide some example pictures for this plugins.

**Comment by mhiStrat** [comment]
![Tab manager](https://user-images.githubusercontent.com/18133427/70705811-b533b080-1d0f-11ea-9009-5452873b185e.png)
![scroll  bar](https://user-images.githubusercontent.com/18133427/70705813-b7960a80-1d0f-11ea-8879-3514eed2c2ca.png)
![Transfer ](https://user-images.githubusercontent.com/18133427/70705818-b95fce00-1d0f-11ea-8176-d90a0ca3d454.png)

**Comment by mhiStrat** [comment]
The first image is the TAB manager plug-in ；
The second image is the scroll bar style ；
The third picture is transfer ；
Ask me if you don't understand

**Comment by REJack** [comment]
I've looked over your plugin ideas, 1. is already requested, 2. is already builtin with overlayScrollbars and 3. is already builtin with Bootstrap Dual List Box.
