### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nagpals** [ColorlibHQ/AdminLTE#2417]
**Issue** 
Date Picker
**Description**
I need to add the date picker. The git code does not work for the button date picker. 
Additionally, there is no way to keep it blank, it will populate it for you in any case. 

I need a non-mandatory field of Date. If i try implementing Bootstrao Date, i need to include bootstrap.css which makes all alignment in bad shape.

**Steps to reproduce the behavior:**
1. Try adding a Datepicker. The git code doesn't have a simple date picker but has date ranges. 
2. Button date picker doesnt work.

**Expected behavior**
I should be able to add Date picker into the page as a non-mandatory field.

**Environment (please complete the following information):**
 - AdminLTE Version: [v3.0.0]
 - Operating System:  [macOS Catalina for development and Linux server]
 - Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
You will not need to load bootstrap.css, Bootstrap 4's css is complete in AdminLTE's css.

**Comment by nagpals** [comment]
> You will not need to load bootstrap.css, Bootstrap 4's css is complete in AdminLTE's css.

But bootstrap Datepicker doesnt work without including bootstrap.min.css (any version)

**Comment by REJack** [comment]
You want to use a external plugin that not comes with AdminLTE right?

If you want a Datepicker, use Tempusdominus Bootstrap 4 which is included in AdminLTE.

Here is a example code for date only:
```html
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
                    <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker4').datetimepicker({
                    format: 'L'
                });
            });
        </script>
    </div>
</div>
```

**Comment by nagpals** [comment]
I tried this but click doesnt work. 

Please see the screenshot : 
https://prnt.sc/q2r1a2

**Comment by REJack** [comment]
Do you recieve a errro in the debug console?

**Comment by nagpals** [comment]
> Do you recieve a error in the debug console?

No, there is no error. The error you see is intentional, as I have but a slash not to include my previously included bootrap.min.css.

**Comment by nagpals** [comment]
<link rel="stylesheet" href="bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">

**Comment by REJack** [comment]
Try to use Tempusdominus Bootstrap 4 instead of bootstrap-datepicker

```html
  <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
```

**Comment by nagpals** [comment]
That worked @REJack. Really appreciate your help. I used the date you mentioned and it worked.

**Comment by nagpals** [comment]
> Try to use Tempusdominus Bootstrap 4 instead of bootstrap-datepicker
> 
> ```
>   <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
>   <script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
> ```

This doesnt work, appreciate your help and time.

**Comment by REJack** [comment]
Does work now? 😄

**Comment by nagpals** [comment]
> Does work now? 😄

Yes :)
