### ISSUE TITLE
[FEATURE] kanban board like trello and Jira

### ISSUE THREAD

**Issue by mgamal92** [ColorlibHQ/AdminLTE#2418]
I have a todo list app with tasks list but i need to show it as board view like (Todo, Doing, Done) as Trello and Jira . Is there any plan to do that ?

**Comment by REJack** [comment]
You mean like kanban board?

**Comment by mgamal92** [comment]
Exactly

**Comment by REJack** [comment]
At the moment there are no plan for this, but this would also a nice add for v3.1.0.

I'll add this to the v3.1.0 milestone 😄

**Comment by mgamal92** [comment]
Can I expect it within one week or one month ? :D

**Comment by REJack** [comment]
Idk at the moment I have no due date for v3.1.0, but I guess 2 months till release but I'll release rc's before (RTL support is quite heavy 😄 also the plain javascript plugins will hard too)

**Comment by mgamal92** [comment]
Keep Going . Great Work!

**Comment by REJack** [comment]
I keep this issue open to track the state 😄 I'll close this if it's added

**Comment by mgamal92** [comment]
OK Great man 👍

**Comment by xthakila** [comment]
is the kanban board similar to the one here https://uselooper.com/page-project-board.html
is the kanban demo and view already comitted to the master if not where can I download the RC with the Kanban code?

**Comment by REJack** [comment]
It's in master branch available.

**Comment by xthakila** [comment]
Nice I will check it out. Is it similar to the one I linked?

**Comment by REJack** [comment]
I would say it's to 60-70% similar 🤣 but it's more minimalistic 😄

**Comment by xthakila** [comment]
> I would say it's to 60-70% similar 🤣 but it's more minimalistic 😄

Haha yeah I just looked at it lol any chance you are going to clean it up?

**Comment by xthakila** [comment]
> > I would say it's to 60-70% similar 🤣 but it's more minimalistic 😄
> 
> Haha yeah I just looked at it lol any chance you are going to make it less minimalistic?

would be awesome if we could get this :)

**Comment by xthakila** [comment]
or even just the drag drop boxes.

**Comment by dotdeas** [comment]
Will there be drag-n-drop support between the boards?

**Comment by AdeSupriyadi** [comment]
Just try v 3.1.0-rc

Content overlap card area when scrolled

![image](https://user-images.githubusercontent.com/14267724/103838249-27b3c300-50bf-11eb-8283-129ca68a25b7.png)
