### ISSUE TITLE
[BUG] Form-control labels with alt css

### ISSUE THREAD

**Issue by fedee13** [ColorlibHQ/AdminLTE#2420]
If I use the alt css:

adminlte.core.min.css
adminlte.components.min.css
adminlte.extra-components.min.css
adminlte.pages.min.css

The label in form-control are not bold. But if I use adminlte.min.css everything is ok.

**Comment by REJack** [comment]
I'll check the alt css files 😄

**Comment by REJack** [comment]
I've fixed the alternative css files in the master repo.
