### ISSUE TITLE
[FEATURE] Please also add D3

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2423]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
D3 is awesome library for data visualization so please include D3 by default.

**Comment by REJack** [comment]
That's a nice idea, feel free to create a PR 😄 may with a simple demo.

**Comment by REJack** [comment]
This is also a great add for v3.1.0.

**Comment by saileshkush95** [comment]
I'm working on this.
