### ISSUE TITLE
[BUG] sidebar menu based scroll on single page application is blocking card title

### ISSUE THREAD

**Issue by ajinabraham** [ColorlibHQ/AdminLTE#2424]
**Describe the bug**
When nav bar has a fixed top `layout-navbar-fixed` , upon clicking on the sidebars, the title of card is blocked by top navbar for navigations in single page app.

**To Reproduce**
1. Code `<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">`
2. Click on a sidebar item that scrolls down to a card in a single page app that uses # based scrolling.
3. Actual behavior
![Screenshot 2019-11-30 at 10 01 01 PM](https://user-images.githubusercontent.com/4301109/69908716-f4cbd580-13bc-11ea-830e-d5edeeb5c1eb.png)

**Expected behavior**
![Screenshot 2019-11-30 at 10 01 12 PM](https://user-images.githubusercontent.com/4301109/69908720-fd241080-13bc-11ea-9f26-a9353f47ff5a.png)

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.1]
 - Operating System:  [e.g. macOS Catalina]
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**
Side bar menu option
```
  <li class="nav-item">
            <a href="#scan_options" class="nav-link">
              <i class="nav-icon fas fa-cog"></i>
              <p>
                Scan Options
              </p>
            </a>
          </li>
```
Section
```
<section id="scan_options" class="content">
..
</section>
```

**Comment by REJack** [comment]
I know this, you need to add a single anchor and not use the id of section or others. I‘ve described it in the docs. 

> Tip!
If you want to use anchors with a fixed navbar, you need to add .anchor to you hidden anchor, e.g. <a id="testAnchor" class="anchor"></a>.

https://adminlte.io/docs/3.0/layout.html

**Comment by ajinabraham** [comment]
Thanks, my bad.
