### ISSUE TITLE
Top-nav.html Page Mobile Size Notifications Issue

### ISSUE THREAD

**Issue by chan2093** [ColorlibHQ/AdminLTE#2425]
Hi, I am Chrome user, messages & notification element in Top Navigation Page has some issue...
![Capture](https://user-images.githubusercontent.com/47651746/69915649-78082c80-148c-11ea-8743-e89f976dca2a.PNG)

**Comment by chan2093** [comment]
![Capture2](https://user-images.githubusercontent.com/47651746/69915681-ce756b00-148c-11ea-9d77-2120602d5e55.PNG)
Normal view...

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll check and fix this soon.

**Comment by REJack** [comment]
I've fixed this issue in the master repo.
