### ISSUE TITLE
[BUG] The Github preview not usable on Firefox, Smaller and misaligned. 

### ISSUE THREAD

**Issue by techno-express** [ColorlibHQ/AdminLTE#2426]
**Describe the bug**
- Does not display correctly when using Firefox.

**To Reproduce**
- open index3.html or https://adminlte.io/themes/v3/ or https://adminlte.io/docs/3.0/

**Expected behavior**
- Should look the same as Chrome, or like in AdminLTE version 2.4

**Screenshots**
- Firefox index3.html and the same on https://adminlte.io/themes/v3/
![firefoxIndex](https://user-images.githubusercontent.com/29784725/69915511-ccc08e80-141d-11ea-90b8-ea1f5a5fe1bc.jpg)
- https://adminlte.io/docs/3.0/ using Firefox
![firefox](https://user-images.githubusercontent.com/29784725/69915521-0f826680-141e-11ea-8502-eba3266efc8c.jpg)

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.0]
3.0.1
 - Operating System:  [e.g. macOS Catalina]
Windows 7
 - Browser (Version): [e.g. Chrome (Latest)]
Firefox (Latest)

**Additional context**

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll check and fix this soon.

**Comment by REJack** [comment]
Sadly I can't replicate this issue. I get everytime the same result on various browsers. May the problems comes from old cache or addons/plugins.

**Comment by techno-express** [comment]
> 
> 
> Sadly I can't replicate this issue. I get everytime the same result on various browsers. May the problems comes from old cache or addons/plugins.

Not sure what you mean? You might not able to replicate if loading from your build environment. Cause I'm getting the issue while viewing your github preview page https://adminlte.io/themes/v3/:
![previewFireFox](https://user-images.githubusercontent.com/29784725/70149682-a5183300-1676-11ea-8e9d-a17d53c4ba32.jpg)

However if i pull up https://adminlte.io/themes/v3/index2.html: 
![previewFireFoxIndex2](https://user-images.githubusercontent.com/29784725/70149986-338cb480-1677-11ea-8e3d-6d66c01c2cb0.jpg)

**No problem**, but this page has `<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">` that fixes the issue, but going to any other link still gets the misalignment.

**Comment by REJack** [comment]
I tested only the online demo to test the active build, but I tested it with a fresh installed firefox without any addon.

The index2.html image looks also not correct, I dont know why the logo img is not correctly sized on all examples.

**Comment by techno-express** [comment]
I just pulled up preview page on an Linux system using Firefox with smaller resolution screen size, with no issue. Then on Windows 10 laptop, even smaller screen size, and no issue. 

This is strange, they all have ublock origin addon, it's on Chrome too. But I have another Windows 10 system showing the same behavior, it's resolution more square than wide screen. Not sure what's going on.

**Comment by REJack** [comment]
Really strange behavior, I use also uBlock Origin on my browsers 😄 It works great, but I use it with the default filter list (without any filter changes). 

Could you try it again on the browsers with issue and start them in [safemode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode)?

**Comment by techno-express** [comment]
That didn't fix the issue. 

However after some reading the troubleshooting section, the browsers that was failing was using the same profile prefs that i copied to keep same layout/settings. 

After deleting, no issues, but it screwed up my 20 tabs of auto restore sessions. **not good**.
