### ISSUE TITLE
[FEATURE] Please add logout menu

### ISSUE THREAD

**Issue by taumal** [ColorlibHQ/AdminLTE#2427]
**_AdminLTE 2_** had a logout menu at right side of main header but **_AdminLTE 3_** don't have it. Please add this. 

Thank you.

**Comment by deepak458** [comment]
@taumal it's already have on a page [Check here](https://adminlte.io/themes/dev/AdminLTE/pages/examples/legacy-user-menu.html)

**Comment by taumal** [comment]
Oops!! Sorry I didn't noticed.

Thank you so much.

**Comment by narsenault** [comment]
Hi, 

@deepak458, the link above is broken is there an updated link?

Thanks,

-Neil

**Comment by REJack** [comment]
That was a old dev online demo, here is the correct one. https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html

**Comment by narsenault** [comment]
@REJack Awesome thanks for the quick response and that's exactly what we were looking for.
