### ISSUE TITLE
[FEATURE] Bring back the help-block and has-success classes for validation

### ISSUE THREAD

**Issue by codemunkie15** [ColorlibHQ/AdminLTE#2428]
**Is your feature request related to a problem? Please describe.**
AdminLTE 2 had good support for jQuery Unobtrusive Validation with a class called has-success that you can put on a form-group and also a help-block class for adding validation messages at the bottom of input boxes. This made it easy to add and remove classes via javascript for client side validation.

**Describe the solution you'd like**
Bring back the has-success class instead of having to add is-valid to the input element and bring back the help-block class for validation messages.

**Comment by REJack** [comment]
This is a change from Bootstrap4 and I can't change this behavior.

But may this helps you https://www.npmjs.com/package/jquery-validation-unobtrusive-bootstrap.

**Comment by codemunkie15** [comment]
Didn't realise this was vanilla bootstrap behaviour! Thanks for the link.
