### ISSUE TITLE
[BUG] Accent colour affecting btn-block href elements

### ISSUE THREAD

**Issue by codemunkie15** [ColorlibHQ/AdminLTE#2429]
**Describe the bug**
Accent colours are affecting the text colour of href buttons using the btn-block class. This means if I am using a blue accent colour, the text colour becomes the same as the primary button colour making it invisible.

**To Reproduce**
Choose blue accent colour
Go to profile page
Hyperlink buttons using primary colour now have same text colour as background

**Expected behavior**
The accent colour shouldn't affect btn-block elements. The text colour should stay black/white.

**Screenshots**
![image](https://user-images.githubusercontent.com/13065317/69977468-c536dd80-1522-11ea-90b8-e3e29bec21d2.png)

**Environment (please complete the following information):**
 - AdminLTE Version: 3.1

**Comment by REJack** [comment]
Thanks for reporting this isseu, I'll check and fix this soon.

**Comment by REJack** [comment]
I've fixed this issue in master repo
