### ISSUE TITLE
[BUG] Description Horizontal isn't horizontal

### ISSUE THREAD

**Issue by RatStrydom** [ColorlibHQ/AdminLTE#2430]
**Describe the bug**
Description Horizontal isn't horizontal. Looks exactly like the vertical one.

**To Reproduce**
1. Go to 'https://adminlte.io/themes/dev/AdminLTE/pages/UI/general.html'
2. Scroll down to 'Description Horizontal'

**Expected behavior**
Label and description should be next to each other.

**Screenshots**
![AdminLTE](https://user-images.githubusercontent.com/10528274/69988944-4bffb080-154b-11ea-9ce1-eadaa2771165.PNG)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System:  Windows 10
 - Browser (Version): Chrome (Latest)

**Additional context**
None

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll check and fix this soon.

**Comment by REJack** [comment]
I've fixed the html markup to get the correct result in master repo.

**Comment by RatStrydom** [comment]
Working now. Thanks.
