### ISSUE TITLE
[BUG] Drag and drop feature doesn't work on mobile

### ISSUE THREAD

**Issue by ni-fara** [ColorlibHQ/AdminLTE#2431]
**Describe the bug**
There is a To Do List in Dashbord v1, it's items has a drag and drop feature on desktop using mouse pointer but on mobile you can't use this feature with touch screen.

**Expected behavior**
On mobile version may be touching the item for a few seconds let the user to move the item of the list.

**Environment (please complete the following information):**
 - AdminLTE Version: 3

**Comment by REJack** [comment]
Thanks for reporting this issue, but the drag and drop/sortable feature is a part of the jQuery UI and it's not managed by AdminLTE itself.
