### ISSUE TITLE
[BUG] blank in layout

### ISSUE THREAD

**Issue by Baozi2** [ColorlibHQ/AdminLTE#2432]
**Describe the bug**

**To Reproduce**
1.  npm run dev 
2.  when mouse scroll down or up 
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5621510/70115644-59c44b80-169b-11ea-9767-7cc4f614d637.png)

**Environment (please complete the following information):**
 - AdminLTE Version: [master ]
 - Operating System:  [macOS Catalina]
 - Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
Sadly I can't replicate this issue (also with Catalina & Chrome 78.0.3904.108). Which node/npm version you use?

**Comment by Baozi2** [comment]
thank you!
node version v10.15.3
npm version v6.9.0
I find it appear in some condition, when I find that, I will tell you! Now you can ignore it

**Comment by REJack** [comment]
>  I find it appear in some condition, when I find that, I will tell you! Now you can ignore it

Ok 👍
