### ISSUE TITLE
Give back the colors

### ISSUE THREAD

**Issue by icemagno** [ColorlibHQ/AdminLTE#2433]
Where is the beautiful and clear `skin-blue` color? (`#3c8dbc`).

And I need back the `skin-*` option. The `navbar-foo navbar-bar navbar-mymother navbar-blah` method is very boring...

The new blue is terrible and ugly. Too bright. 

Thanks.

**Comment by REJack** [comment]
The blue color was changed by the old author, idk know why it's changed. I've added a new color lightblue in the master repo.

Skin option was also removed by the old author, I personally like it and I have no plans to bring them back in AdminLTE v3 (it would cause breaks by every v3 user), with AdminLTE v4 (BS5) I can bring the skins back this would also reduce the filesize of adminlte.css.
