### ISSUE TITLE
[FEATURE] Clarification: how do you drop in a different bootstrap css package?

### ISSUE THREAD

**Issue by aaronhudon-ts** [ColorlibHQ/AdminLTE#2436]
**Describe the solution you'd like**
To be able to drop in a customized bootstrap.css file, e.g. one of the themes from bootswatch

**Comment by REJack** [comment]
There is no way to use a customized bootstrap.css files, AdminLTE use bootstrap's SCSS files and generates it own customized bootstrap.css as adminlte.css. 
If you want to change colors and other styles, then you will need to modify or replace `build/scss/_bootstrap-variables.scss`. (I prefer modifying)

**Comment by aaronhudon-ts** [comment]
@REJack too bad.  I would be nice to be able to drop-in a dark-theme.
