### ISSUE TITLE
[BUG]it is BUG in Dashboard 3

### ISSUE THREAD

**Issue by guyuewuren** [ColorlibHQ/AdminLTE#2440]
**Describe the bug**

**To Reproduce**
2. Click on 'fas fa-th-large'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.1
 - Operating System:  windows 10
 - Browser (Version): Chrome (Latest)
![QQ截图20191211161002](https://user-images.githubusercontent.com/15320333/70603326-42ec9e80-1c31-11ea-8f94-d89014a22621.jpg)
![QQ截图20191211160901](https://user-images.githubusercontent.com/15320333/70603327-42ec9e80-1c31-11ea-970d-3a916a6c0613.jpg)

**Additional context**

**Comment by REJack** [comment]
Please try this bug with the master repo again, I can't replicate this issue with v3.0.2-pre.

**Comment by guyuewuren** [comment]
> Please try this bug with the master repo again, I can't replicate this issue with v3.0.2-pre.

Yes, it has been fixed in v3.0.2-pre
