### ISSUE TITLE
Beginners Questions

### ISSUE THREAD

**Issue by mpi42** [ColorlibHQ/AdminLTE#2442]
Hello,

I'm sorry for the stupid questions but I'm a "beginner" in this area.

I would like to use the AdminLTE template for a small project and loaded it into Visual Studio Code with npm and executed it again in the directory "npm install".

I have prepared the starter.html so that it fits me and now I want to create a subpage. 
Do I proceed correctly if I only copy the starters.html page? And in this subpage.html and the starter.html the links adapt? 
So for each subpage an own HTML page where the links are correct and the class "active" are set for the side menu? 

for the final deployment on the webserver is there a npm command which only "exports" the things that are needed or do i have to clean the plugins/templates/css etc. manually afterwards?

thank you

**Comment by REJack** [comment]
If you only want to use the precompiled dist files you will not need to run npm install. You will only need npm install if you modify scss/js files from AdminLTE.

If you build a static website you will need to add manually the "active" state to the sidebar menu.

There is no export command, but you will only need to use/copy the dist & plugins folder.

**Comment by mhanchini** [comment]
if you not using npm you can download it as zip [https://github.com/ColorlibHQ/AdminLTE/archive/v3.0.1.zip](url) 
extract the dist,img and plugins folder.
add it depend on what frontend do you use.
you're ready to go

**Comment by edwardtilley** [comment]
If I just want to make revisions, run the included node.js apps, and then deploy the updates on a production server, what are the recommended steps here. I can make changes on a local test server, but its not clear what is the best way to run the new site with login authentication in production.
