### ISSUE TITLE
Main sidebar: user panel as dropdown menu, and .text-truncate on menu items

### ISSUE THREAD

**Issue by zubfatal** [ColorlibHQ/AdminLTE#2445]
This is probably a bit of a longshot, but i'll try anyways.

#### user panel as dropdown
Is there any way to make the `.user-panel` act as a normal, expandable menu with sub-menu items?

#### .text-truncate on menu items
in the `.user-panel` i can make use of `.text-truncate` like this:
```html
<div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="https://i.pravatar.cc/150" class="img-circle elevation-2" alt="User Image">
    </div>

    <div class="info">
        <a href="#" class="d-block text-truncate">
            This is a very very very very veery long name
        </a>
    </div>
</div>
```
Which renders as `This is a very very very ve...`
If i put the `.text-truncate` class on the `<p>` in the sidebar menu, it doesn't work.
According to the bootstrap 4 docs, `.text-truncate` requires either `display: block` or `display: inline-block`  which has been set on the `.nav-sidebar .nav-link p` rule.

Thanks.

**Comment by REJack** [comment]
> user panel as dropdown

Do you mean a expandable "user"-menu inside the sidebar? Or in the topnav?

> .text-truncate on menu items

Check this comment https://github.com/ColorlibHQ/AdminLTE/issues/2416#issuecomment-558622865

**Comment by zubfatal** [comment]
@REJack Thanks for your quick response.
> Do you mean a expandable "user"-menu inside the sidebar? Or in the topnav?

Yes, i meant in the sidebar, i tried creating it as a normal menu item with sub-menu which seems to work, but gives funky issues with spacing etc. when using the collapsed sidebar state.

> Check this comment #2416 (comment)

Nice! that actually pointed me a bit in the right direction, didn't realize I had to use a `max-width` since it worked without problems on the existing `.user-panel` without providing `max-width`

**Comment by REJack** [comment]
>  Yes, i meant in the sidebar, i tried creating it as a normal menu item with sub-menu which seems to work, but gives funky issues with spacing etc. when using the collapsed sidebar state.

Can you provide your user menu item with sub-menu test code? May I can add a simple fix for the behavior.

**Comment by zubfatal** [comment]
Sorry for the delayed response, I've since moved on to using a user menu in the top navigation instead.
I've created some mockup of what i remember i was using when attempting to create the menu in the main sidebar:
```html
<li class="nav-item has-treeview user-panel">
    <a href="#" class="nav-link">
        <img src="/path/to/user-image.png" class="img-circle user-avatar mr-2">
        <p>
            My username
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview" style="display: none;">
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Menu item #1</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Menu item #2</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Menu item #3</p>
            </a>
        </li>
    </ul>
</li>
```
I don't have a the bits and pieces, but at the same time i was trying to make use of `.text-truncate` as well since a user might have a "long" name.
