### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by devsetgo** [ColorlibHQ/AdminLTE#2446]
**Describe the bug**

The plugin fullcalendar-interactive is missing /main.min.css. From what I can tell, this is not needed from a look through fullcalendars plugin (https://fullcalendar.io/docs/getting-started) when I downloaded it directly.

So I believe this just needs to be removed from calendar.html.

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.1]

**Comment by REJack** [comment]
Thanks for reporting this issue, I've fixed it in master repo.

**Comment by devsetgo** [comment]
Great.
