### ISSUE TITLE
Skin support for v3.x?

### ISSUE THREAD

**Issue by pwalimbe** [ColorlibHQ/AdminLTE#2449]
the preview version of adminlte.io has skins and good font sizes. But v3.x does not seem to have. Is that correct?

**Comment by REJack** [comment]
Yep this is correct, the bigger font size comes from the massive change from px to rem. I would say it's increased about ~2px, but you can add `.text-sm` on `body` for an smaller more v2 like look (this will also gives you a smaller navbar, brand & footer).

P.S. there other classes also available to change the sidebar style like v2.

**Comment by pwalimbe** [comment]
Thanks useful information - I did add .text-sm and it worked. will then wait for v4 I guess for skins.

**Comment by REJack** [comment]
You have various additional classes in v3 to change the look, e.g. for sidebar pills background, navbar background, brand background & accent colors.

**Comment by MGatner** [comment]
Hi @REJack, stumbled in here trying to resolve usage issue. I'm using the starter page as a template but missing CSS. Are all the references to skin from a previous version and not applicable to version 3?
```
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="dist/css/skins/skin-blue.min.css">
...
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
...
-->
<body class="hold-transition skin-blue sidebar-mini">
```

If so it would probably be good to remove this from the top of the Layout page:

> Tip!
> The [starter page](https://adminlte.io/themes/AdminLTE/starter.html) is a good place to start building your app if you'd like to start from scratch.
