### ISSUE TITLE
[BUG] incorrect margin on sidebar nav 

### ISSUE THREAD

**Issue by RamezIssac** [ColorlibHQ/AdminLTE#2450]
**Describe the bug**
You would see the issue if you checked 

**To Reproduce**

1. go to v3 any page
2. Check on
Sidebar nav flat style
Sidebar nav legacy style
Sidebar nav compact
3. collapse the sidebar
4. You see the menu item is to the left a little 

**Expected behavior**
It should be centered

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.0]
 - Operating System: linux but i think it's on all
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**
I really liked the v2 menu where the sidebar is not all shown when hover, only the menu being hovered would be displayed.

Also i feel like you're not satisfied with V3 yet (as you dont make it the website -> preview), and i agree.. what on v2 style that is still missing on v3 and making v3 not as pretty ?

Last but definitely not least
**Thank you** for this amazing theme which is in cooperated in https://github.com/ra-systems/ra

**Comment by REJack** [comment]
I see what you mean, with `Sidebar nav compact` it doesn't align correctly. I've fixed this in master branch.

> Also i feel like you're not satisfied with V3 yet (as you dont make it the website -> preview)

I work at the moment on a new website for AdminLTE beside publishing a new version.

> and i agree.. what on v2 style that is still missing on v3 and making v3 not as pretty ?

In v3 is pretty much anything from v2 (request by v2 users while development), in my memory I only not adapted the non-fixed sidebar hover popout menu style that's asked in a issue recently.

>  I really liked the v2 menu where the sidebar is not all shown when hover, only the menu being hovered would be displayed.

You can disable the hover with adding `.sidebar-no-expand` on `.main-sidebar`.

**Comment by RamezIssac** [comment]
Thank you for your quick response 

I'll do my best to help out as a non-front-end inclined person.

One thing though: 
Adding `.sidebar-no-expand` disable the expand altogether, it doesn't provide that the menu hovered is shown to the side.

**Comment by REJack** [comment]
Nope, this is not added in v3, but it's requested recently #2435 (this would not work with fixed sidebar).
