### ISSUE TITLE
Datatables in AdminLTE3

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2452]
**Describe the bug**
I learnt there are datatables in AdminLTE3.  
1. Where in ADMINLTE3 do I find datatables as in the diagram below.
2. How do I apply and use it?

**Screenshots**
![adminlte3_datatables](https://user-images.githubusercontent.com/34077129/71091406-55248a80-21a5-11ea-8555-1a7da831cd19.PNG)

**Environment (please complete the following information):**
 - AdminLTE Version: [v3.0.0]
 - Operating System:  [Windows]
 - Browser (Version): [Chrome (Latest)]

Thank you

**Comment by RamezIssac** [comment]
You can find datatables in the Menu -> Tables -> Datatable

As for the screen shot, you can always to initialize the Datatable you want with the options you need as mentioned in the datatables manual. (and I believe you're searching for this page on  the manual https://datatables.net/extensions/buttons/)

**Comment by noblemfd** [comment]
@RamezIssac  - Problem solved. Thanks
