### ISSUE TITLE
[BUG] invalid-feedback ?

### ISSUE THREAD

**Issue by RamezIssac** [ColorlibHQ/AdminLTE#2453]
invalid-feedback is currently commented out with other no validation example or alternative.

Please bring it back (or an alternative) :)

**Comment by REJack** [comment]
Where you see invalid-feedback commented out? AdminLTE doesn't remove or disable the form feedbacks, it has only an additional warning feedback that was removed with bootstrap4.

**Comment by RamezIssac** [comment]
Thank you mate! Great work!!
