### ISSUE TITLE
Side multi-level menu doesn't work with Angular 8.

### ISSUE THREAD

**Issue by emilioyn** [ColorlibHQ/AdminLTE#2454]
Hello, multilevel sidebar menu does't work on Angular 8 (TypeScript), here is the HTML code:

```html
<li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-envelope"></i>
            <p>
              Mailbox
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" data-widget="tree">
            <li class="nav-item">
              <a href="../mailbox/mailbox.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Inbox</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../mailbox/compose.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Compose</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../mailbox/read-mail.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Read</p>
              </a>
            </li>
          </ul>
        </li>
```

When I click on menu to expand, it doesn't open as expected.

Thanks,

**Comment by emilioyn** [comment]
More info: AdminLTE 3 on Chrome.

**Comment by REJack** [comment]
The markup look correct, may you need to init the treeview on page load. 
Try to add `$('[data-widget="treeview"]').Treeview('init');`.

**Comment by emilioyn** [comment]
Hello @REJack, thank you for your answer, where do I add this snipet?

**Comment by REJack** [comment]
Idk how your app is build, if I'm not wrong you can add this in ngOnInit or something like this.
May this https://github.com/ColorlibHQ/AdminLTE/issues/2290#issuecomment-534809669 can help you.

**Comment by emilioyn** [comment]
Guys, found the solution:
1) Add "node_modules/jquery/dist/jquery.min.js" and "node_modules/admin-lte/dist/js/adminlte.min.js" to "scripts" section in angular.json;

2) Following a  sample valid markup:

`<li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-envelope"></i>
            <p>
              Mailbox
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" data-widget="tree">
            <li class="nav-item">
              <a href="../mailbox/mailbox.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Inbox</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../mailbox/compose.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Compose</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../mailbox/read-mail.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Read</p>
              </a>
            </li>
          </ul>
        </li>`

Is this approach correct? If so, I'll close this issue.
