### ISSUE TITLE
[BUG] Bootstrap Switch Button Size

### ISSUE THREAD

**Issue by tuncaybahadir** [ColorlibHQ/AdminLTE#2455]
Although we choose the key size in Bootstrap Switch plugin, small size keys are formed. There is also an undefined class problem. Screen shot below.

**Screenshots**
![resim](https://user-images.githubusercontent.com/1303432/71192858-1de3d580-229a-11ea-860a-8890ca19cfbb.png)

![resim](https://user-images.githubusercontent.com/1303432/71192159-cdb84380-2298-11ea-81f9-1fd01e8dec5c.png)
![resim](https://user-images.githubusercontent.com/1303432/71192251-f6403d80-2298-11ea-8414-0621ab88a43d.png)

OR

![resim](https://user-images.githubusercontent.com/1303432/71192323-1a9c1a00-2299-11ea-9810-94b9a5e16c1b.png)
![resim](https://user-images.githubusercontent.com/1303432/71192366-2b4c9000-2299-11ea-8991-342f923d7788.png)

And Undefined class name problem

![resim](https://user-images.githubusercontent.com/1303432/71192450-5cc55b80-2299-11ea-93dc-d8fdc00cfa34.png)

 - AdminLTE Version: [v3.0.2-pre]
 - Operating System:  [windows 10]
 - Browser (Version): [Firefox Dev. Edition (Latest), Chrome (Latest)]

**Comment by REJack** [comment]
Please report this issue on the plugins repo (https://github.com/Bttstrp/bootstrap-switch), it's not maintained by AdminLTE.
