### ISSUE TITLE
DatePicker?

### ISSUE THREAD

**Issue by DreadedBeard** [ColorlibHQ/AdminLTE#2456]
In the old versions of AdminLTE there is a pop up date picker. 
https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html

In the latest release there is no such thing ( only ones can be found with a date RANGE ).

Can be found on the advanced form elements page.

pages/forms/advanced.html ( Date Picker )

**Comment by REJack** [comment]
There is also a Datetimepicker which you can use for, it's called (tempusdominus-bootstrap-4](https://tempusdominus.github.io/bootstrap-4/Usage/) _it need moment.js as dependency_.

In the AdminLTE v3 docs is only the timepicker visible, but this markup can used for datepicker too or even for the combined datetimepicker.

**Comment by codemunkie15** [comment]
https://bootstrap-datepicker.readthedocs.io/en/latest/

This one also works with Bootstrap4 if you're not a fan of TempusDominus like me. I added the below small css tweaks to add some needed spacing on the calendar table:

`.datepicker td,
.datepicker th
{
  padding: 5px;
  line-height: 1;
  width: 30px;
  height: 30px;
}

.datepicker.dropdown-menu {
  padding: 4px;
}`

**Comment by ZurMaD** [comment]
Thanks guys. But will be cool to add simple date picker to templates.

**Comment by danny007in** [comment]
> 
> 
> Thanks guys. But will be cool to add simple date picker to templates.

You can add by contributing

**Comment by cataclysmuprising** [comment]
You can use `singleDatePicker: true` for daterangepicker as the [example](https://www.daterangepicker.com/#example3).
