### ISSUE TITLE
I want to buy license plz 

### ISSUE THREAD

**Issue by sawassosft** [ColorlibHQ/AdminLTE#2457]
Hi, 

iam using now Adminlte (free style NOT PREMIUM ) to programming website for my company

but it is impossible to put your copyright in the footer ! , so i want know how to buy license to use just in one site for just my company site please without write in the footer copyright !!

**Comment by juplayLP** [comment]
I am just citing https://adminlte.io/docs/3.0/license.html here:

> What You Must Do When Using AdminLTE
>>Include the license notice in all copies of the work.
>>Include the copyright notice in all copies of the work. This applies to everything except the notice in the footer of the HTML example pages.

You don't have to include their copyright in your footer, just somewhere on the page in general should be enough

Please correct me when I'm wrong here though.

**Comment by sawassosft** [comment]
> I am just citing https://adminlte.io/docs/3.0/license.html here:
> 
> > What You Must Do When Using AdminLTE
> > > Include the license notice in all copies of the work.
> > > Include the copyright notice in all copies of the work. This applies to everything except the notice in the footer of the HTML example pages.
> 
> You don't have to include their copyright in your footer, just somewhere on the page in general should be enough
> 
> Please correct me when I'm wrong here though.

thanks for replay , but i will be in Shameful mode  if one of employee see this copyright !! , i can't !! 

iam just want one thing , buy license  just for (not write any copyright) in any page ! , just for one site !

**Comment by burakdobur** [comment]
You can't buy open source licence. This is under MIT licence.
