### ISSUE TITLE
[BUG] Issue with 'Responsive Hover Table'

### ISSUE THREAD

**Issue by omexlu** [ColorlibHQ/AdminLTE#2458]
Hello,

Somehow there is a difference between 'Admin LTE 2' and 'Admin LTE 3' in the 'Responsive Hover Table' in the Mobile View.

In the 'Admin LTE 2' the table is more scrollable in width and is not pressed as much.

You can compare the problem in the online demo:
Admin LTE 2 (https://adminlte.io/themes/AdminLTE/pages/tables/simple.html):
![admin-lte-2](https://user-images.githubusercontent.com/3801660/71317846-2c8fdf80-2488-11ea-812a-436f1d533282.png)

Admin LTE 3 (https://adminlte.io/themes/dev/AdminLTE/pages/tables/simple.html):
![admin-lte-3](https://user-images.githubusercontent.com/3801660/71317847-2d287600-2488-11ea-9d4f-942aad0caf1e.png)

How can i adjust it so that it is as horizontally scrollable as in 'Admin LTE 2' and the table is not so compressed?

PS. I have not changed anything in the code but use it in the standard version of the demo. But I wish that in the 'Admin LTE 3' it is scrollable in the same width as in the 'Admin LTE 2' and is not so compressed.

Thanks in advance.

**Comment by danny007in** [comment]
Try this make seperate div for table-responsive 
Because in bootstrap 4 this is special feature for multiple table or single tbl
https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-tables.php
<body>
<div class="bs-example">
    <div class="table-responsive"> 
        <table class="table">
            <thead>
                <tr>
                    <th>Row</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Biography</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Clark</td>
                    <td>Kent</td>
                    <td>clarkkent@mail.com</td>
                    <td>Lorem ipsum dolor sit amet...</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>John</td>
                    <td>Carter</td>
                    <td>johncarter@mail.com</td>
                    <td>Vestibulum consectetur scelerisque...</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Peter</td>
                    <td>Parker</td>
                    <td>peterparker@mail.com</td>
                    <td>Integer pulvinar leo id risus...</td>
                </tr>
            </tbody>
        </table>
    </div>    
</div>
</body>

https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-tables.php

**Comment by danny007in** [comment]
>  <div class="table-responsive"> 
>         <table class="table">

**Comment by omexlu** [comment]
Hello,

This is already set by default in Admin LTE 3:
```
<div class="card-body table-responsive p-0">
                  <table class="table table-hover text-center">
                    <thead>
                      <tr>
                        <th>1.</th>
                        <th>2.</th>
                        <th>3.</th>
                        <th>4.</th>
                        <th>5.</th>
                        <th>6.</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1.</td>
                        <td>2.</td>
                        <td>3.</td>
                        <td>4.</td>
                        <td>5.</td>
                        <td>6.</td>
                      </tr>      
                      </tbody>
                  </table>
</div>
```
Or what do you mean exactly?

**Comment by omexlu** [comment]
@REJack do you have maybe a solution for this? Maybe it have something to do with css config?

Thank you.

**Comment by REJack** [comment]
There are two options for this:
1. add `.text-nowrap` to the table
2. add a min-width to the table

**Comment by omexlu** [comment]
Adding ' .text-nowrap ' to the table fix this issue for me, thank you a lot :)
