### ISSUE TITLE
Plugins Not Working

### ISSUE THREAD

**Issue by foreversaver** [ColorlibHQ/AdminLTE#2459]
Hi!

Can I know which plugins or/and css that cause my AdminLTE 3.0,1 index page look like this:-

![GitHub Trouble 1 1](https://user-images.githubusercontent.com/7608691/71339364-31d75200-258e-11ea-80a3-4db1eb71f845.png)

Instead of something like this (like how it supposed to look like):-

![GitHub Trouble 2 1](https://user-images.githubusercontent.com/7608691/71339658-1c165c80-258f-11ea-8e30-e3dace9cd6cb.png)

I don't know which plugins or/and css that could cause this issue. Would really appreciate it if you guys can help me with this.

Thank you.

**Comment by REJack** [comment]
Could you send me the bugged html file, you are not the first with this issue but I've not find what it caused :/ May you get some errors in your dev tools console.

**Comment by foreversaver** [comment]
Oh sorry. I should have mentioned that the html file got no bugs in it. It works just fine. I'm implementing this on Yii2 Framework the same way I did with the 2.4 version.

It just that this time around it gave me such error. 

If you have any other suggestion, do please tell me where should I look.

**Comment by danny007in** [comment]
> 
> 
> Oh sorry. I should have mentioned that the html file got no bugs in it. It works just fine. I'm implementing this on Yii2 Framework the same way I did with the 2.4 version.
> 
> It just that this time around it gave me such error.
> 
> If you have any other suggestion, do please tell me where should I look.

There might be can issues with include function in backend

**Comment by REJack** [comment]
> There might be can issues with include function in backend

I suspect that too.
