### ISSUE TITLE
How can I change sidebar bottom border Color ?

### ISSUE THREAD

**Issue by masumluf** [ColorlibHQ/AdminLTE#2461]
I would like to change border-bottom color in AdminLTE sidebar. Where should I change the style? I am new in AdminLTE

**Comment by REJack** [comment]
Which border you mean, the border between user panel and menu inside the sidebar?

**Comment by REJack** [comment]
Also for which version v3 or v2.4?

**Comment by masumluf** [comment]
Hello Jack, the version i am using is v2.4 I need to change border color for left sidebar tree menu's. Like When I will click on any tree menu ul border bottom should be white color.

**Comment by REJack** [comment]
You mean like this?
![grafik](https://user-images.githubusercontent.com/1554582/71574824-c0962280-2aea-11ea-8699-5b8697ddef42.png)

If yes, I've only used the skin-black in my screenshot 😄.

**Comment by masumluf** [comment]
[https://prnt.sc/qhfoua](url)
like this white border on the left side under dashboard v2

**Comment by REJack** [comment]
Did you added the border by yourself? I get no border like this :/.

**Comment by masumluf** [comment]
I need to add this border but where should I change ?

**Comment by REJack** [comment]
You'll need a custom css like this:
```css
.treeview.active .treeview-menu {
    border-bottom: 3px solid 
    white;
}
```

**Comment by masumluf** [comment]
Thank you REJack

**Comment by REJack** [comment]
No problem 😄
