### ISSUE TITLE
[BUG] Split buttons links does not work

### ISSUE THREAD

**Issue by fjsosa** [ColorlibHQ/AdminLTE#2462]
Go to the example page: UI Elements/ buttons
Section: Split buttons

Copy the code of one dropdown buttons in an example project
Set a link for any of the dropdown items ie: Separated Link=>href="some real link"
The link does not work.

Expected result:
Each item in the dropdown should have a link, and each link should work propery opening the url set.

**Comment by REJack** [comment]
This is a bug from bootstrap4, if the dropdown menu is inside the dropdown-toggle. 
You can the markup to this:
```html
<div class="btn-group">
  <button type="button" class="btn btn-default">Action</button>
  <button type="button" id="dropdownSubMenu1" class="btn btn-default dropdown-toggle dropdown-icon" data-toggle="dropdown">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div aria-labelledby="dropdownSubMenu1" class="dropdown-menu" role="menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="https://google.com">Separated link</a>
  </div>
</div>
```
