### ISSUE TITLE
[BUG] Dropdown menu in navbar is broken on mobile

### ISSUE THREAD

**Issue by sergiz** [ColorlibHQ/AdminLTE#2464]
**Describe the bug**
If you don't use .layout-top-nav and want to use a normal dropdown menu in the navbar, it doesn't work properly on small screen sizes. It is just blank white, although the links are still there. It works perfectly on bigger screens.

**To Reproduce**
1. Use this code in your main header (make sure your layout is **not** .layout-top-nav).
```
<nav class="navbar navbar-static-top">
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 2</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
```
2. Open the site on your big screen and drop the menu. It works as it should. Resize the screen to small size, open the menu and its blank.

**Expected behavior**
I would expect it to work on small screen the same way as it works on a big one.

**Screenshots**
Big: http://shrani.si/f/X/29/KeI3JI4/screen1.png
Small: http://shrani.si/f/1w/a/1F8kwPFy/mobile.png

**Environment (please complete the following information):**
 - AdminLTE Version: v2.4.18
 - Operating System:  Windows
 - Browser (Version): Firefox (Latest)]

**Comment by danny007in** [comment]
In your case the  problem may in AdminLTE Version: v2.4.18, Actually this version is deprecated so you can use adminlte 3, his is very simple to migrate
