### ISSUE TITLE
Pushmenu on Angular not showing mini sidebar

### ISSUE THREAD

**Issue by akhtarmo** [ColorlibHQ/AdminLTE#2465]
Good Day ReJack, 

Thanks for all your efforts and sharing this great piece of work with the community.

I had managed to successfully migrate v2.x on Angular and it works perfectly.

Yesterday I tried moving the v3.0.1 onto Angular. (Keeping in mind that I am a novice on Angular).

I faced 2 issues:

1. When I click on the hamburger menu, the sidebar collapses (it doesn't show the mini-sidebar
2. The chart elements do not show

It is probably something silly that I have missed and would appreciate if you could help.

I have posted my code at [https://github.com/akhtarmo/adminlte3-angular8](https://github.com/akhtarmo/adminlte3-angular8).

I would also like to know how I could change the color themes to match my own color palette.

Thanks for your time and help in advance.

Kind Regards,

**Comment by REJack** [comment]
> When I click on the hamburger menu, the sidebar collapses (it doesn't show the mini-sidebar

You need to add `.sidebar-mini` on the body tag.

> The chart elements do not show  

Did you recieve any error in your dev console?

> I would also like to know how I could change the color themes to match my own color palette.

For this you need to modify AdminLTE and recompile the dist files, simple edit the colors in `build/scss/_variables.scss` and after all changes you need only to run `npm run dev` (if you precompile them and copy them afterwards, but you can also add the AdminLTE compiling step in your Angular project to keep it in only one simple project)

**Comment by akhtarmo** [comment]
Thanks for the prompt response ReJack,

the side bar issue is resolved based on your suggestion.

i have attached the error that i am getting on the Inspect window
![charterror](https://user-images.githubusercontent.com/30242269/71619649-dab12d00-2bde-11ea-9220-5b14b49c72f4.PNG)

**Comment by REJack** [comment]
Sorry for the late response, yep try to remove the demo & dashboard js files they are only need or the example pages.
