### ISSUE TITLE
[BUG] accent-* with body not working with active class in dropdown

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2466]
There is some error when we are using `accent-* (example: accent-info)` is working fine, but when we are using it with pre-active dropdown, It's not change background color but change color and hover color.

it's always show primary background color when dropdown menu have active class. have a look in  below image.

![image](https://user-images.githubusercontent.com/29248598/71572086-81c09680-2b03-11ea-8281-52158b614210.png)

![image](https://user-images.githubusercontent.com/29248598/71572271-3f4b8980-2b04-11ea-9d6d-4c40c610d2bf.png)

for more confirmation i'm using Data-table with column visibly plugin in same Data-table.

**Comment by deepak458** [comment]
@REJack is there any solutions for this?

**Comment by deepak458** [comment]
@REJack any update for this?

**Comment by REJack** [comment]
No sorry 😞 I had much to do due XMas and New Year, I'll add a fix for this soon.

**Comment by REJack** [comment]
I looked over the accent and it has still some bugs with overriding the wrong links I'll fix it and add a override for the dropdown active.

**Comment by REJack** [comment]
I've added a fix for this in the master branch 😄

**Comment by deepak458** [comment]
@REJack Thanks

**Comment by deepak458** [comment]
@REJack still there are some dropdown who have active class with primary accent.

**Comment by deepak458** [comment]
@REJack when user click on drop-down link with `accent-*` it's show `primary color` on focus. it's has to be depend upon `accent-*`

**Comment by REJack** [comment]
Please provide a screenshot I can't replicate this, :focus generates a light grey background not primary.

**Comment by REJack** [comment]
Ok I found what you mean, you mean active (on click/hold) I'll fix this too 😄.

**Comment by REJack** [comment]
I've fixed this in master branch 😄
