### ISSUE TITLE
[BUG] Card header padding issue when using button inside card-header

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2467]
When we are using button inside card header, it's work fine but the card-header title not align center have a look in below image:

![image](https://user-images.githubusercontent.com/29248598/71572719-83d82480-2b06-11ea-8034-8112a013abd5.png)

**Comment by REJack** [comment]
Is this button inside the `.card-tools`-div?

**Comment by deepak458** [comment]
@REJack no It's not inside any card-tools, it's just a simple button with `float-right` CSS.

**Comment by REJack** [comment]
Try it inside of .card-tools, there it should be alignd correctly

**Comment by REJack** [comment]
> Try it inside of .card-tools, there it should be alignd correctly

@deepak458 Did it worked?

**Comment by deepak458** [comment]
@REJack Yes It's worked but it's not align, so i fix it with some bootstrap classes check below code, It's worked fine for me.

`<div class="ml-auto mr-2 pt-1 text-align-right">`
`<a class="btn btn-info btn-sm my-auto border-top-0 text-white" href="#"><i class="fas fa-eye fa-sm"></i> View List</a>`
`<a class="btn btn-info btn-sm my-auto border-top-0 text-white" href="#"><i class="fas fa-edit fa-sm"></i> Edit</a>`
`</div>`

Image:
![image](https://user-images.githubusercontent.com/29248598/72453819-bad85680-37e5-11ea-8fdf-e417457b4c8c.png)

**Comment by deepak458** [comment]
@REJack it's just working, i added it in my list, i will use `.card-tool`.

Thx
