### ISSUE TITLE
[BUG] Login Page: form Position not fixed

### ISSUE THREAD

**Issue by perspolise** [ColorlibHQ/AdminLTE#2468]
If in login page add any error Or text after `<body class="login-page">` (ie: server side error Exception) Login Form not fixed:

![Untitled](https://user-images.githubusercontent.com/19752074/71575456-470a2e80-2b02-11ea-9129-f41d1541006b.jpg)

**Comment by REJack** [comment]
The login-box is not fixed it's only placed in the center of the page via flexbox. You should place the error after `<div class="login-logo">` or before/after the `<p class="login-box-msg">`.

**Comment by perspolise** [comment]
Sure, But in dynamic content template system (ie php plates Or twig) php model/controller error, print after body. my mean is: I set `body` for body template and include all dynamic page into `body` so php error print after `body`.

**Comment by REJack** [comment]
I understand what you mean, I use twig to place my errors on specific spots but that depends also on the used framework/base code. 😄 

As a little workaround you can add a custom css for this.

```css
.login-page,
.register-page {
  flex-direction: column;
}
```

I'll add this little workaround to AdminLTE v3.

**Comment by perspolise** [comment]
@REJack Gr8. Worked now. thanks

**Comment by danny007in** [comment]
> 
> 
> I understand what you mean, I use twig to place my errors on specific spots but that depends also on the used framework/base code. 😄
> 
> As a little workaround you can add a custom css for this.
> 
> ```css
> .login-page,
> .register-page {
>   flex-direction: column;
> }
> ```
> 
> I'll add this little workaround to AdminLTE v3.

better you can add directly in repo

**Comment by REJack** [comment]
I've added this little workaround to the master repo.
