### ISSUE TITLE
[SUGGESTION] Simple typo error in AdminLTE example page.

### ISSUE THREAD

**Issue by hareendranmg** [ColorlibHQ/AdminLTE#2471]
**Description**
The link of Forgot Password and Recover Password elements in the https://adminlte.io/themes/v3/pages/examples/contacts.html page is wrong. 
**To Reproduce**
1: Go to https://adminlte.io/themes/v3/pages/examples/contacts.html EXAMPLES-->Extras-->Forgot Password.
2: Link of Forgot Password is https://adminlte.io/themes/v3/pages/examples/..examples/forgot-password.html. It has to https://adminlte.io/themes/v3/pages/examples/forgot-password.html. Same for the case of Recover Password.

**Comment by dharmendrashah** [comment]
correct it

**Comment by REJack** [comment]
This is already fixed, but the demo is not updated and will updated with the next release.
