### ISSUE TITLE
Search in sidebar

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2472]
Is your feature request related to a problem? Please describe.
When the sidebar is becoming huger, it's hard to find the right one. Could you possible to provide the search functions.

Describe the solution you'd like
Add the demo how to do search in sidebar.

The format like below screenshots or highlight the results or hidden or other formats.
![image](https://user-images.githubusercontent.com/6952917/71660324-a62ba580-2d85-11ea-87ad-9550a3cc2758.png)

![image](https://user-images.githubusercontent.com/6952917/71660305-94e29900-2d85-11ea-9bc3-c5580b563dd1.png)

Thanks.

**Comment by REJack** [comment]
Am I getting you right, you ask for javascript search function to find menu items?

**Comment by GerryGe** [comment]
Not only the js, I also need your recommend of how to show the result, maybe need some class.

**Comment by REJack** [comment]
Sure with css styles 😄 , I'll add this to the v3.1 todo

**Comment by GerryGe** [comment]
Thanks your hard work!👍
