### ISSUE TITLE
Card Outline in Tab panel issue

### ISSUE THREAD

**Issue by guillaumecardon** [ColorlibHQ/AdminLTE#2474]
When you put a card outline in a tab panel, the "outline" style is not applied.

![2020-01-03 15_28_24-AdminLTE 3 _ Navbar   Tabs](https://user-images.githubusercontent.com/47170797/71728735-2d3c5480-2e3e-11ea-82c0-ee049381726c.png)

 - AdminLTE Version: 3.0.1
 - Operating System:  Fucking slowly Windows 10 1903
 - Browser (Version):  Chrome (Latest)

**Comment by REJack** [comment]
Please try the master repo, if the bug appears there too 😄

**Comment by guillaumecardon** [comment]
It's better, but border-bottom is missing ;)
![2020-01-04 09_14_50-AdminLTE 3 _ Navbar   Tabs](https://user-images.githubusercontent.com/47170797/71762691-d16fdb00-2ed2-11ea-9bdd-94373b82ecb7.png)

**Comment by REJack** [comment]
Ok I'll add a fix for this too 😄

**Comment by REJack** [comment]
I've fixed this issue in the master branch 😄
