### ISSUE TITLE
[Fix] whick file define css 'has-treeview'?

### ISSUE THREAD

**Issue by mzy666888** [ColorlibHQ/AdminLTE#2475]
**Describe the bug**
when I use AdminLte on Visual Studio 2019, it tips `has-treeview`  unknown。
![image](https://user-images.githubusercontent.com/2587129/71761380-24fb1c80-2f05-11ea-9e17-f6fc91563d79.png)

**To Reproduce**
1. I use VSC search in file, but can't find the css `has-treeview`。 Only find in .html file ,but it was used.

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.1]
 - Operating System:  [e.g. Windows 10]
 - Browser (Version): [e.g. Chrome (Latest)]

**Comment by REJack** [comment]
This is still a old remnant from v2, it's not need anymore I'll remove the classes soon from the html files.

**Comment by masterkain** [comment]
same as `data-widget="treeview"` ?
