### ISSUE TITLE
[BUG] Sidebar not collapsing correctly when multiple levels involved

### ISSUE THREAD

**Issue by internaut19** [ColorlibHQ/AdminLTE#2476]
**Describe the bug**
When the sidebar menu has multiple levels defined and data-accordion is set to true, it only collapses the first option in the sub menu.

**To Reproduce**
1. Set data-accordion to true in 
```<ul class='nav nav-pills nav-sidebar flex-column' data-widget='treeview' role='menu' data-accordion='true'>```
2. Create a multi level menu structure. Ex:
```
<li class='nav-item has-treeview'>
	<a href='#' class='nav-link'>
		<i class='nav-icon fas fa-book'></i>
			<p>
				Level 0
				<i class='right fas fa-angle-left'></i>
			</p>
	</a>
<ul class='nav nav-treeview has-treeview'>
	<li class='nav-item'>
		<a href='#' class='nav-link'>
			<i class='right fas nav-icon fa-angle-left'></i>
			<p>Level 1</p>
		</a>
		<ul class='nav nav-treeview'>
			<li class='nav-item'>
				<a href='#' class='nav-link'>
					<i class='fas fa-plus nav-icon'></i>
					<p>Level 2</p>
				</a>
			</li>
		</ul>
	</li>
</ul>
<ul class='nav nav-treeview'>
	<li class='nav-item'>
		<a href='#' class='nav-link'>
			<i class='fas fa-minus nav-icon'></i>
			<p>Level 1</p>
		</a>
	</li>
</ul>
</li>
<li class='nav-item has-treeview'>
	<a href='#' class='nav-link'>
		<i class='nav-icon fas fa-book'></i>
			<p>
				Level 0
				<i class='right fas fa-angle-left'></i>
			</p>
	</a>
<ul class='nav nav-treeview'>
	<li class='nav-item'>
		<a href='#' class='nav-link'>
			<i class='fas fa-minus nav-icon'></i>
			<p>Level 1</p>
		</a>
	</li>
</ul>
</li>
```
3. Click on the first Level 0 option and then click on the second Level 0 option, it should collapse completely the first Level 0 option but it doesn't, it only collapses the first Level 1 option.

**Expected behavior**
When clicking on a first Level 0 option it should collapse completely any other Level 0 opened.

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.1
 - Operating System: Windows 10
 - Browser (Version): Chrome (Latest), Firefox (Latest)

**Comment by REJack** [comment]
I can't replicate this isseu with the master repo, I get the expected behavior.

**Comment by internaut19** [comment]
I've taken the code from the example page and adapt it so the problem can be reproduced. If you open the level 1 menu and the click on the Extras, the level 1 option will not close correctly.

   
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-plus-square"></i>
              <p>
                Extras
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="pages/examples/login.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Login</p>
                </a>
              </li>
            </ul>
          </li>   
          <li class="nav-header">MISCELLANEOUS</li>
          <li class="nav-item">
            <a href="https://adminlte.io/docs/3.0" class="nav-link">
              <i class="nav-icon fas fa-file"></i>
              <p>Documentation</p>
            </a>
          </li>
          <li class="nav-header">MULTI LEVEL EXAMPLE</li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Level 1
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Level 2
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Level 2</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Level 2 dub
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Level 2</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Level 1</p>
            </a>
          </li>

**Comment by REJack** [comment]
I found a additional unexpected `ul.nav-treeview`that carries also menu items.
```html
        </ul>
        <ul class="nav nav-treeview">
```

The Treeview script only open/close the first `.nav-treeview` inside the `li`.

**Comment by internaut19** [comment]
Will you consider adapting the Treeview script for multiple ul.nav-treeview under the same main menu item? I thinks it's a nice thing to have and I am sure it's common.

**Comment by REJack** [comment]
I've not decided to this while I enhanced Treeview, if I change this (`.find('> ' + Selector.TREEVIEW_MENU)` to `.find(Selector.TREEVIEW_MENU)`) all subitems would open also with opening the level 1 main item and I didn't found a solution for this 😞 that's why the script point for the first treeview child.
