### ISSUE TITLE
[FEATURE] - AdminLTE V3.x Sidebar Collaspe complete

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2478]
@REJack is there any class that complete hide the side bar but show top brand-link when side bar on fully Collaspe, and when user click on pushmenu full sidebar show-up.

i have try to remove sidebar-mini class it's work fine but white space is coming when sidebar collaspe.

1) Im looking for something like that
![image](https://user-images.githubusercontent.com/29248598/71969425-a4059300-322c-11ea-83a9-59b3eb3dc9c3.png)

2) When i remove sidebar-mini class
![image](https://user-images.githubusercontent.com/29248598/71969719-3e65d680-322d-11ea-8236-93fda8d182fb.png)

using `hold-transition layout-navbar-fixed sidebar-collapse layout-fixed` class in main body and `main-sidebar sidebar-light-info elevation-4 sidebar-no-expand` into aside

**Comment by deepak458** [comment]
@REJack is there any solution for this issue, i need to work on some project and this issue i'm facing.

**Comment by deepak458** [comment]
@REJack any update on this issue.

**Comment by REJack** [comment]
sorry I was sick since new year 😞 From your body classes `.sidebar-no-expand` should not used without sidebar-mini 😄 if I guess right.

I'll check this out, please checkout the master branch I've tested your body class and I got the correct result may I fixed it already.

**Comment by deepak458** [comment]
@REJack you can also add Example page of this in to demo website.

I just want to show only top bar as Top Navigation but when user click on sidebar button It's show up

**Comment by REJack** [comment]
I've added a seperate demo for this behavior and fixed the hidden sidebar with layout-top-nav.

**Comment by deepak458** [comment]
@REJack Thanks i just check it, and it's worked fine, so when we expect release date ?
