### ISSUE TITLE
Main Sidebar doesn't show headers when hovering.

### ISSUE THREAD

**Issue by Root3287** [ColorlibHQ/AdminLTE#2480]
## Issue
[X ] Feature request
[X ] Bug report
[ ] Documentation 

## Environment
- AdminLTE: v3.0.1
- OS: Linux
- Browser: Firefox

## Steps to reproduce
I was debugging my application when I found this. I am not sure if this is a unintended bug or a feature idea, but it's something to post about.

What I have currently set up
```html
<body class="hold-transition sidebar-mini sidebar-collapse">
    ...
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent nav-flat" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
            <li class="nav-header">Core</li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Settings
                        <i class="right fas fa-angle-left"></i>
                        <!-- can change to number  -->
                    </p>
                </a>
               ...
            </li>
        </ul>
    </nav>
</body>
```

Now If a user hover over to view the links on the main sidebar, the .nav-header would not show. But if the user some how toggle the main sidebar it would then show.

## What the expected output
When the user hover over the left sidebar, to have some way to view the .nav-header items.

**Comment by REJack** [comment]
I see what you mean, I'll fix this soon.

**Comment by REJack** [comment]
I've added a fix for this in master repo 😄
