### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by somaraj** [ColorlibHQ/AdminLTE#2481]
AdminLTE 3 **[nuget](https://www.nuget.org/packages/AdminLTE3.MVC/)** package for **ASP.Net MVC**

`Install-Package AdminLTE3.MVC -Version 1.0.0`

**Comment by REJack** [comment]
I'll add your nuget package to the implementations list inside the docs.

**Comment by somaraj** [comment]
Thanks.
