### ISSUE TITLE
[FEATURE] jQuery Smart Wizard

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2482]
@REJack i'm looking for `jQuery-Smart-Wizard` jquery plugin with inbuilt in css in form

**Comment by REJack** [comment]
I'll look over this for v3.1, but may I search a non-jquery plugin 😄

**Comment by deepak458** [comment]
@REJack there is one more class that exist into old V. 2... `.toolbar, .dataTables_info` add it for this also

**Comment by REJack** [comment]
I've added bs-stepper in #2916 coming with v3.1 :smile:
