### ISSUE TITLE
[BUG] Card Variants (Default & Outline) look all the same

### ISSUE THREAD

**Issue by Tilogorn** [ColorlibHQ/AdminLTE#2483]
**Describe the bug**
As I migrated from 2.4.15 to 3.0.1 and started to exchange boxes with cards, I noticed that the card variants concerning default and outline all look the same. Not just on my localhost but also on the official documentation.

**To Reproduce**
1. See https://adminlte.io/docs/3.0/components/cards.html

![Bildschirmfoto vom 2020-01-10 15-12-36](https://user-images.githubusercontent.com/7524854/72158948-a9451800-33bb-11ea-8583-967c2a22413d.png)

**Expected behavior**
I expected different styles on the cards as I am used to from [boxes](https://adminlte.io/docs/2.4/boxes)

![Bildschirmfoto vom 2020-01-10 15-13-12](https://user-images.githubusercontent.com/7524854/72158999-beba4200-33bb-11ea-8fe6-ba7582b3637e.png)

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.1
 - Operating System:  Linux Mint 19 Tara
 - Browser (Version): Chrome (78)

**Comment by Tilogorn** [comment]
May be related to https://github.com/ColorlibHQ/AdminLTE/issues/2474

**Comment by REJack** [comment]
This is already fixed in master repo and will come with v3.0.2.

**Comment by Tilogorn** [comment]
Do you have an estimated release date for v3.0.2?
