### ISSUE TITLE
[BUG] "starter page" stated in the docs does not exist

### ISSUE THREAD

**Issue by Tilogorn** [ColorlibHQ/AdminLTE#2484]
**Describe the bug**
In the docs on page `layout.html` there is a "starter page" referenced which does not exist.

**To Reproduce**
1. Go to https://adminlte.io/docs/3.0/layout.html

> The starter page is a good place to start building your app if you’d like to start from scratch.

No link, just a plain paragraph.

Lokks like copy/paste [from v2.4](https://adminlte.io/docs/2.4/layout), where this is an actual link with a starter page.

**Expected behavior**
Embedded link to a starter page based on v3.
If this is still `todo` then a hint at this place in the docs would be nice (right now it is just irritating).

**Screenshots**
V2.4:
![Bildschirmfoto vom 2020-01-10 15-24-10](https://user-images.githubusercontent.com/7524854/72159730-4bb1cb00-33bd-11ea-8fa9-ac4847fc0ec8.png)

V3.0.1:
![Bildschirmfoto vom 2020-01-10 15-24-21](https://user-images.githubusercontent.com/7524854/72159744-566c6000-33bd-11ea-9aee-652510dac806.png)

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.1
 - Operating System:  Linux Mint 19 Tara
 - Browser (Version): Chrome (78)

**Comment by REJack** [comment]
This is fixed with bfb74266b72e9007a02a4d344ce6204ca377934c, I'll update the docs with the next release.
