### ISSUE TITLE
Installation of v2.4.18 through Composer is not working

### ISSUE THREAD

**Issue by sudo-barun** [ColorlibHQ/AdminLTE#2486]
AdminLTE v2.4.18 cannot be installed through Composer as it depends upon a non-existent package `bower-asset/jquery`.

**To Reproduce**
1. Create a fresh PHP project and run `composer init`
2. `composer require almasaeed2010/adminlte=v2.4.18`
4. See error in the console output below:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for almasaeed2010/adminlte v2.4.18 -> satisfiable by almasaeed2010/adminlte[v2.4.18].
    - almasaeed2010/adminlte v2.4.18 requires bower-asset/jquery >=1.9.0 <4.0.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Expected behavior**
The package should be installable without any error.

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v2.4.18]

**Comment by REJack** [comment]
To download AdminLTE via composer you need to use/add [Asset-Packagist](https://asset-packagist.org/).

**Comment by sudo-barun** [comment]
Thanks @REJack, it works.

It would be better if you mention this information in https://adminlte.io/docs/2.4/installation.

**Comment by REJack** [comment]
Sadly I can't update the old v2.4 docs, I close this issue.
