### ISSUE TITLE
[BUG] .table-condensed is now .table-sm

### ISSUE THREAD

**Issue by Tilogorn** [ColorlibHQ/AdminLTE#2487]
**Describe the bug**
The `Condensed Full Width Table` example shown on https://adminlte.io/themes/v3/pages/tables/simple.html **is not condensed**.

The [Bootstrap 4 docs state](https://getbootstrap.com/docs/4.0/migration/): `Renamed .table-condensed to .table-sm for consistency.`

In fact `.table-condensed` has no more effect to tables.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/pages/tables/simple.html
3. Scroll down to 'Condensed Full Width Table'

**Expected behavior**
A condensed table, as with `.table-sm`

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System:  Linx Mint 19 Tara
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
Thanks for reporting this bug, I'll fix this soon 😄
