### ISSUE TITLE
[FEATURE] Extra Badge Options

### ISSUE THREAD

**Issue by andcarpi** [ColorlibHQ/AdminLTE#2488]
**Describe the solution you'd like**
Just need a bigger label/badges class, because when using label in tables, or showing data, i wanted the text to be more readable compared to the rest of the infos...

**Describe alternatives you've considered**
Considered using regular buttons or button-sm without the hover effect, who was the perfect size for my taste, lil bigger text than badges, but not so much surrounding margin/padding to extend parents div height/size. But coundt get rid of hover/click effect.

** Extras **
We could also have additional badges options, like border radius (no round edges or pill format), padding, and weight config classes.

**Additional context**
![image](https://user-images.githubusercontent.com/13441557/72353265-84ee8180-36c2-11ea-8afa-2a03ebcbc23b.png)

**Comment by REJack** [comment]
I've added a additional class for the badges (`.badge-btn`) in master repo.

Here is a preview, (`.badge-btn.badge-pill` has the same height like btn-sm)
![Screenshot_2020-01-15 AdminLTE 3 Dashboard 2](https://user-images.githubusercontent.com/1554582/72415288-68128680-3774-11ea-9fce-203cc95efc91.png)

**Comment by andcarpi** [comment]
Nice! Thanks!
