### ISSUE TITLE
[FEATURE] Request Dark Version

### ISSUE THREAD

**Issue by hrace009** [ColorlibHQ/AdminLTE#2489]
It will be good if we have AdminLTE Dark Version 💯

**Comment by REJack** [comment]
That's a nice request, this would a nice add for v3.1 😄

**Comment by hrace009** [comment]
> 
> 
> That's a nice request, this would a nice add for v3.1 😄

thank you,

**Comment by hrace009** [comment]
can't wait more longger :D

**Comment by kylebakerio** [comment]
I'd say try using a dark mode chrome extension or even the new built-in chrome dark mode and borrow from that CSS there to start with.

**Comment by whittinghamj** [comment]
This would be an awesome update - as I'm visually impaired, having dark themes is a must for me and brwoser mods just dont quite cut it and get it wrong more often than not.

**Comment by MGatner** [comment]
I would love to see full support for `prefers-color-scheme: dark`. Might be in addition to a static dark theme but there would be significant overlap.
