### ISSUE TITLE
[BUG] Scroll with ScrollAnywhere extension in Chrome Browser is very slow

### ISSUE THREAD

**Issue by artemdigi** [ColorlibHQ/AdminLTE#2490]
**Describe the bug**

I'm use this extension in Chrome 

https://chrome.google.com/webstore/detail/scrollanywhere/jehmdpemhgfgjblpkilmeoafmkhbckhi

And AdminLTE v3 is scrolling very slow

**To Reproduce**
1. Oper Chrome Browser
2. Install ScrollAnywhere extension https://chrome.google.com/webstore/detail/scrollanywhere/jehmdpemhgfgjblpkilmeoafmkhbckhi
3. Open settings of ScrollAnywhere 
4. Setups "Scroll button" = "Right button"
6. Click "Save changes"
7. Open https://adminlte.io/themes/dev/AdminLTE/index.html
8. Try to scroll by grab right mouse button

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.1
 - Operating System:  Windows 10, Linux Manjaro Grome (Latest)
 - Browsers: Chrome (Latest), Chromium (Latest), Opera (Latest)

**Comment by REJack** [comment]
I can't replicate this issue on my macOS Chrome with the extension installed, I'll try this on my home gaming machine with Win10. 
The old demo https://adminlte.io/themes/dev/AdminLTE/index.html is not updated, please try https://adminlte.io/themes/v3/index.html. Also does it only scrolls slow on the dashboard pages or on any demo page like the widgets demo.

**Comment by artemdigi** [comment]
Yes, https://adminlte.io/themes/v3/index.html have the same effect.

I have only Windows and Linux OS, and can't check in macOS.

Maybe record screen video?

**Comment by artemdigi** [comment]
>  Also does it only scrolls slow on the dashboard pages or on any demo page like the widgets demo.

Scroll with ScrollAnywhere is slow on ALL pages.

**Comment by REJack** [comment]
I found the bug, it will fixed with the next release (v3.0.4).
