### ISSUE TITLE
[FEATURE] Please Commit version 3.x on CDNJS

### ISSUE THREAD

**Issue by JNPSoftware** [ColorlibHQ/AdminLTE#2493]
https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/admin-lte

CDNJS only have version 2.x

**Comment by REJack** [comment]
I don't know how to update the files on cdnjs, I'll look how I can update them.

**Comment by JNPSoftware** [comment]
Thank You, version 3.0.2 is on CDNJS now.
https://cdnjs.com/libraries/admin-lte
