### ISSUE TITLE
How to completely hide side bar when press hamburger menu

### ISSUE THREAD

**Issue by NaySoewin-1** [ColorlibHQ/AdminLTE#2495]
Dear all, 
(1) Let me request one thing that i want to hide completely sidebar when i press Han burger menu, (like google cloud) 
i don't want collapsed menu https://prnt.sc/qq2qvu
(2) and How to set small body text as default https://prnt.sc/qq2ro9
 , Thanks

**Comment by REJack** [comment]
1. Simply remove `.sidebar-mini` from body tag, or try [this layout](https://adminlte.io/themes/v3/pages/layout/top-nav-sidebar.html) as startpoint.

2. add `.text-sm` to your body tag.

**Comment by NaySoewin-1** [comment]
Hi, Mr. REJack , Thanks for your reply and everything is work good , but one more thing  is i want to set default (non-sidebar) when user first login . Thanks again

**Comment by REJack** [comment]
This depends on your application base, I can't give you infos for this.
