### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ViaCoders** [ColorlibHQ/AdminLTE#2496]
Hello,
How can I change direction of scrollbar to Left. Please see the attached image.
Best Regards,
![scroll](https://user-images.githubusercontent.com/60089647/72707681-39325100-3b76-11ea-8374-8ae77cc5bc41.jpg)

**Comment by REJack** [comment]
With AdminLTE v3.0 you can not change the direction of the sidebar, but this will come with v3.1 (see #2236).
