### ISSUE TITLE
Iframe tab pages

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2497]
Is your feature request related to a problem? Please describe.
In China, we prefer to use tab pages, Could you possible to provide this function.

Describe the solution you'd like
Add the js/css and demo how to support iframe pages.

I found  demos as below:
https://www.layui.com/admin/std/dist/views/
https://weituotian.github.io/AdminLTE-With-Iframe/pages/index_iframe.html
![image](https://user-images.githubusercontent.com/6952917/72771985-9d6c1800-3c3d-11ea-9cb8-9021832c5e55.png)

![image](https://user-images.githubusercontent.com/6952917/72771816-11f28700-3c3d-11ea-8625-e9843f8e2a93.png)

Kind Regards!

**Comment by REJack** [comment]
I'll look over the demos, may I'll add this to v3.1.

**Comment by GerryGe** [comment]
I am looking forward to see this feature. Thanks.

**Comment by REJack** [comment]
@GerryGe I've added this feature in the `feat/iframe-plugin`-branch, feel free to test it 😄 let me know if you have some ideas to enhance or change.

You need to compile the js file and open the iframe.html to test it.

**Comment by zxo102** [comment]
> I'll look over the demos, may I'll add this to v3.1.

Here is another "add-tabs"  for your reference. It seems there is no need to change html files. It looks like this:   
![image](https://user-images.githubusercontent.com/9945043/94984164-cfc76680-057b-11eb-8933-c74e839c413a.png)

1. It needs "js" and "css" from :
  https://github.com/hbbcs/BootStrap-addTabs
2. Here is some more details:
  https://blog.csdn.net/dkjhl/article/details/89509073

3. you can download the source code at 
https://pan.baidu.com/s/1g_wFkrxNvWrO9cYBwTra9w 
with pw: 00ck
