### ISSUE TITLE
[BUG]nav-icons should be align with User Image

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2499]
**Describe the bug**
`nav-icons` from `nav-sidebar` should be align with `user-panel > image`.

**To Reproduce**
1. click on **data-widget="control-sidebar"**
2. choose **Sidebar nav legacy style** or **Sidebar nav compact**
3. see the `nav-sidebar > nav-icons` alignments with   `user-panel > image`.

**Expected behavior**
 `nav-sidebar > nav-icons` should be align equally  with   `user-panel > image`

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5186970/72866202-da511100-3d08-11ea-9df1-93f0a9990d15.PNG)

![Capture2](https://user-images.githubusercontent.com/5186970/72866287-1ab08f00-3d09-11ea-94e6-b136ae472275.PNG)

**Additional informations:**

I think this should be adjust at `.nav-link` padding style. Please check for using with `text-sm` body style class and `sidebar-collapse` styles also. Thanks.

**Environment :**
 - AdminLTE Version: [v3.0.2]
 - Operating System:  [Window 10]
 - Browser (Version): [Firefox (Latest)]

**Comment by REJack** [comment]
Thanks for the report 😄 I'll change this

**Comment by REJack** [comment]
I've aligned the nav-icon's with all posibile custom classes in the master branch.

**Comment by cataclysmuprising** [comment]
Thanks bro ... !
