### ISSUE TITLE
[BUG] Wrong title for examples/project_add.html 

### ISSUE THREAD

**Issue by bansalshashank** [ColorlibHQ/AdminLTE#2500]
Ideally, the title for the project_add page should be **AdminLTE 3 | Project Add** but its **AdminLTE 3 | Project Edit**

**To Reproduce**
1. Go to 'https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/examples/project_add.html'
2. Search for **<title>** tag
3. The title is AdminLTE 3 | Project Edit instead of AdminLTE 3 | Project Add 

**Expected behavior**
The title should be AdminLTE 3 | Project Add

**Environment (please complete the following information):**
 - AdminLTE Version: [3.0.2]
 - Operating System:  [Ubuntu 18 bionic]
 - Browser (79.0.3945.130 (Official Build) (64-bit)): [Chrome (Latest)]

**Comment by REJack** [comment]
Thanks for the report and the PR, I've merged it 😄

**Comment by bansalshashank** [comment]
Thank you for merging the request and your welcome,
I have observed another typo in examples/invoice_print.html where the title in Invoice instead of Invoice Print should I raise a PR for the same as well ?
