### ISSUE TITLE
[BUG] Typo in title of examples/invoice-print.html

### ISSUE THREAD

**Issue by bansalshashank** [ColorlibHQ/AdminLTE#2502]
**Describe the bug**
There is a typo in the title of examples/invoice-print.html where the title should be AdminLTE 3 | Invoice Print it is AdminLTE 3 | Invoice, keeping in consistency with rest of the examples

**To Reproduce**
1. Go to **https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/examples/invoice-print.html**
2. Search for **<title>** tag
3. The title should be AdminLTE 3 | Invoice Page instead of AdminLTE3 | Invoice

**Expected behavior**
The title should be AdminLTE 3 | Invoice Page instead of AdminLTE3 | Invoice

**Environment (please complete the following information):**
 - AdminLTE Version: [3.0.3-pre]
 - Operating System:  [Ubuntu 18 bionic]
 - Browser (Version): [Chrome (79.0.3945.130 (Official Build) (64-bit))]

**Comment by bansalshashank** [comment]
#2503

**Comment by REJack** [comment]
PR merged 😄
