### ISSUE TITLE
[FEATURE] Vertical Align checkbox

### ISSUE THREAD

**Issue by andcarpi** [ColorlibHQ/AdminLTE#2504]
**Is your feature request related to a problem? Please describe.**
Yes, i want to align the checkbox in a form

**Describe the solution you'd like**
When making forms and defining sizes for the controls, like using col-md-3, 4, 6, etc... and having a icheck/checkbox in the same row, and since the checkboxes labels are after then and aligned horinzontally, i can't have a good vertical alignment of the checkbox.

**Describe alternatives you've considered**
Creating an extra label before the checkbox to use the label space and align it with the other fields didnt worked, because empty labels do not use the space. Current alternative was to add top margin/padding to the checkbox div.

**Additional context**
example
`<div class="row">
                  <div class="col-3"><label for="input-test2">Label</label>
                    <input type="text" class="form-control" placeholder=".col-3">
                  </div>
                  <div class="col-4">
                    <label for="input-test">Label</label>
<input type="text" id="input-test" class="form-control" placeholder=".col-4">
                  </div>
                  <div class="col-5">
                    <div class="icheck-primary">
<input type="checkbox" id="checkboxPrimary1" checked="">
                        <label for="checkboxPrimary1">Click Me</label>
                      </div>
                  </div>
                </div>`

![image](https://user-images.githubusercontent.com/13441557/72900364-82b1a600-3d06-11ea-9a34-a8202a14a8f2.png)

**Comment by REJack** [comment]
For this you need to place a fake label (`<label>&nbsp;</label>`) before the checkbox, like this example: `<div class="row"> <div class="col-3"><label for="input-test2">Label</label> <input type="text" class="form-control" placeholder=".col-3"> </div> <div class="col-4"> <label for="input-test">Label</label> <input type="text" id="input-test" class="form-control" placeholder=".col-4"> </div> <div class="col-5"> <label>&nbsp;</label> <div class="icheck-primary"> <input type="checkbox" id="checkboxPrimary1" checked=""> <label for="checkboxPrimary1">Click Me</label> </div> </div> </div>`
