### ISSUE TITLE
Bootstarp 4 selectpicker

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#2505]
Add selectpicker to adminlte

**Comment by cataclysmuprising** [comment]
This is a good idea. I do prefer **[selectpicker](https://developer.snapappointments.com/bootstrap-select/)** than select2. You can use it by adding below css.

```
.bootstrap-select .dropdown-toggle.btn-light {
	background-color: #fff;
	border-color: #ced4da;
	border-radius: 0;
}
```

![Capture](https://user-images.githubusercontent.com/5186970/72954598-4bef9480-3dc7-11ea-947a-3aa8ca812e96.PNG)

**Comment by REJack** [comment]
That's is a nice idea, I'll look over this while v3.1 development may I add this to AdminLTE.

**Comment by davidbuckleyni** [comment]
I am having real issues with mvc and your theme it will not work with bootstrap select picker at all. Even a basic control will not be styled or be allowed to drop down.

<select class="selectpicker" id="searchType" name="searchtype" onchange="this.form.submit()">
                                                            <option value="All">All</option>
                                                            <option value="Businesses">Businesses</option>
                                                            <option value="Events">Events</option>
                                                            <option value="News">News</option>
                                                            <option value="Lifestyle">Lifestyle</option>

                                                        </select>

**Comment by REJack** [comment]
We need also the JS init script, otherwise this is only a default HTML select.

**Comment by REJack** [comment]
I will not add it to AdminLTE, caused by that bootstrap-select depends on jQuery.

You can change the dropdown active color with changing the accent colors.
