### ISSUE TITLE
[FEATURE] Full-screen button

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2511]
@REJack can you just add fullscreen button also.
have a look below image and old same colsed issue https://github.com/ColorlibHQ/AdminLTE/issues/332.

![image](https://user-images.githubusercontent.com/29248598/73060025-f8f80900-3ebc-11ea-8fee-da1ec7e5aa3e.png)

**Comment by REJack** [comment]
A fullscreen button inside the navbar? What would this toggle to fullscreen?

I've added a fullscreen button to the cards, thats visible in the [Widgets Page](https://adminlte.io/themes/v3/pages/widgets.html).

**Comment by deepak458** [comment]
@REJack i already know that, but what is users want to switch into full-screen view.

**Comment by REJack** [comment]
To fullscreen the whole page?

**Comment by deepak458** [comment]
Yes.

**Comment by JNPSoftware** [comment]
I have used this code on OLD 2.x

`              <li class="fullscreen"><a><i class="fas fa-expand-arrows-alt" data-toggle="tooltip" title="Fullscreen" data-placement="bottom"></i></a></li>
`

`//fullscreen function
			$(".fullscreen").click(function(){
				x = $(this).find("a>i").attr("class") ;
				if(x == "fas fa-expand-arrows-alt")
				{
					showFullscreen(document.documentElement);
					$(this).find("a").html('<i class="fas fa-compress-arrows-alt" data-toggle="tooltip" title="Exit Fullscreen" data-placement="bottom"></i>');
				}else{
					exitFullscreen();
					$(this).find("a").html('<i class="fas fa-expand-arrows-alt" data-toggle="tooltip" title="Fullscreen" data-placement="bottom"></i>');
				}
			});
			//Fullscreen Function
			function showFullscreen(element) {
				if(element.showFullscreen) {
					element.showFullscreen();
				} else if(element.mozRequestFullScreen) {
					element.mozRequestFullScreen();
				} else if(element.webkitRequestFullscreen) {
					element.webkitRequestFullscreen();
				} else if(element.msRequestFullscreen) {
					element.msRequestFullscreen();
				}
			}
			//Exit Fullscreen Function
			function exitFullscreen() {
				if(document.exitFullscreen) {
					document.exitFullscreen();
				} else if(document.mozCancelFullScreen) {
					document.mozCancelFullScreen();
				} else if(document.webkitExitFullscreen) {
					document.webkitExitFullscreen();
				}
			}
`

**Comment by deepak458** [comment]
@REJack any update for this..

**Comment by REJack** [comment]
I'll add this in v3.1.

**Comment by suntong** [comment]
Is it available somewhere in demo to switch into full-screen view? I clicked a few, but nothing happened.

**Comment by REJack** [comment]
It's available in the master branch.

**Comment by suntong** [comment]
Got it. thx. 

One thing I noticed is that, browser offers "Press ESC to end full screen mode", and if I do press ESC to end full screen mode, then the JS side isn't aware of such change, and the "shrink-back" icon remains as "shrink-back" (despite the windows has already shrunk back), instead of being changed back to "full-screen" again. 

So maybe leaving the "full-screen" icon as the previous, I.e., without toggling is a better option:

![i](https://user-images.githubusercontent.com/29248598/73060025-f8f80900-3ebc-11ea-8fee-da1ec7e5aa3e.png) 

It save the JS side from detecting the view mode change.
