### ISSUE TITLE
How to make sidebar toggler and control sidebar toggler independent from nav-item

### ISSUE THREAD

**Issue by iyilm4z** [ColorlibHQ/AdminLTE#2512]
I try to implement the theme([repo)](https://github.com/iyilm4z/admin-lte-dotnet) with [.Net Core Tag Helpers](https://docs.microsoft.com/tr-tr/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-3.1). but i've faced with a simple and annoying issue. I cant set control sidebar toggler which staying in nav-item as float left(as the last element always). I need this because i want to make users available to have full control rest of the navbar.

I don't want to use ml-auto, if i use below happens.

![pic1](https://user-images.githubusercontent.com/9105939/73071857-e681cd80-3ec4-11ea-8e84-8490b6a5440d.png)
![pic2](https://user-images.githubusercontent.com/9105939/73071913-0618f600-3ec5-11ea-97e7-efb7f8ad9a59.JPG)

![pic3](https://user-images.githubusercontent.com/9105939/73071879-f39ebc80-3ec4-11ea-8285-9508a68386ec.JPG)

**Comment by REJack** [comment]
Try to change the last `ml-auto` to `mr-auto`.

**Comment by iyilm4z** [comment]
it did'n work:(

![Untitled](https://user-images.githubusercontent.com/9105939/73072810-fc908d80-3ec6-11ea-89f0-f29b4ab0489e.png)

**Comment by iyilm4z** [comment]
Btw it was easy with v2. I was doing what i want with styles and markups below.

```
.sidebar-right-toggle {
  float: right;
}

.sidebar-right-toggle a {
  padding: 15px;
  display: block;
  line-height: 20px;
  cursor: pointer;
}
```
  
```
<header class="main-header">
  <a class="logo">
    ...
  </a>
  <nav class="navbar navbar-static-top">   
  <a class="sidebar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
	
	<!- Custom content goes here-->
	
	<div class="sidebar-right-toggle">
		<a href="#"><i class="fa fa-gears"></i></a>
	</div>
  </nav>
</header>
```

**Comment by REJack** [comment]
Try to remove the last `ml-auto` (the ml-auto make the big gap between the text menu left and icon menu right, like this 
![grafik](https://user-images.githubusercontent.com/1554582/73109077-73974780-3f02-11ea-9edd-1ff8e6137917.png)

**Comment by iyilm4z** [comment]
It doesn't work as you can see. User may want header empty. If so, control navbar toggler stays near to main sidebar toggler which is not expected behavior by me. Main sidebar toggler must be the first and control navbar toggler must be the last. Even there is no custom markup between those.

<img width="932" alt="Capture" src="https://user-images.githubusercontent.com/9105939/73121903-bc491200-3f8f-11ea-9d0b-3b5e96168661.PNG">

**Comment by REJack** [comment]
From the last image you need to add `ml-auto` to the last navbar-nav.

ml-auto is used to generate the space between the navbar navs.

**Comment by iyilm4z** [comment]
Adding an empty ul before control navbar toggler fixed the issue.

```html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
  </ul>

   <!-- Left navbar content here -->

  <ul class="navbar-nav ml-auto">
    <li class="nav-item">&nbsp;</li>
  </ul>

  <!-- Right navbar content here -->

  <ul class="navbar-nav">
    <li class="nav-item">
      <a
        class="nav-link"
        data-widget="control-sidebar"
        data-slide="true"
        href="#"
        ><i class="fas fa-th-large"></i
      ></a>
    </li>
  </ul>
</nav>

```

**Comment by REJack** [comment]
Thats a good way too 👍
