### ISSUE TITLE
[BUG] Select 2 validation border-color

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2513]
there is some issue with form validation, when we validate it with select 2. It's not change border color on error.

**Comment by deepak458** [comment]
@REJack i just find a way but need some inbuilt class for this error and success
`
		errorPlacement: function (error, element) {
			error.addClass('invalid-feedback');
			element.closest('.form-group').append(error);
			if ($(element).hasClass('select2')){
				$(element).closest(".form-group").find('.select2-selection').css('border-color','#dc3545').addClass('text-danger');
			}
		},`

as of now `is-valid` class only work with `form-control`

**Comment by REJack** [comment]
I've looked over it `is-valid` is not maintained by AdminLTE it's a bootstrap 4 core part, also select2 isn't build for validationthe message is not well positioned and there are no color changes by itself. So you will need your solution.
