### ISSUE TITLE
[FEATURE] card-tool for nav nav-tabs in card-header

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2514]
@REJack you can also add `.card-tool` for `nav nav-tabs` in `card-header`

**Comment by REJack** [comment]
I've added additional style to display card-tools correctly, you can use this structure to add card tools on right like the default card style 😄 
```html
<li class="ml-auto">
<div class="card-tools">
  ...
</div>
</li>
```

**Comment by deepak458** [comment]
It's worked but `.card-tools` have some peddling css so that not align check below image

![image](https://user-images.githubusercontent.com/29248598/73257301-82734800-41e9-11ea-8e1a-08632359b4c7.png)

also when we use `text-sm` class have a look

![image](https://user-images.githubusercontent.com/29248598/73257339-9b7bf900-41e9-11ea-80fb-9f9448c8f8b1.png)

CODE:
```
<li class="ml-auto">
<div class="card-tools">
    <button type="button" class="btn btn-info">Button</button>
</div>
</li>
```

**Comment by REJack** [comment]
I would prefrerr btn-xs instead of text-sm


Try this code:
```html
<li class="ml-auto">
<div class="card-tools mt-2 mr-2">
    <button type="button" class="btn btn-info btn-xs">Button</button>
</div>
</li>
```

With the coming v3.0.3 you will not need `mt-2 mr-2`.
