### ISSUE TITLE
[FILE-STRUCTURE] some of the filenames in the examples are inconsistant with current structure

### ISSUE THREAD

**Issue by bansalshashank** [ColorlibHQ/AdminLTE#2515]
**Describe the bug**
As per the current file structure, filename words are  seperated with **-** but in some files it was done using **_**

**To Reproduce**
1. Go to 'pages/examples'
2. Observe the filename for e_commerce.html, project_add.html, project_edit.html, project_detail.html

**Expected behavior**
The filename should be in the as: 
e-commerce.html, project-add.html, project-edit.html, project-detail.html
 
 - AdminLTE Version: [3.0.3-pre]

**Comment by bansalshashank** [comment]
#2516

**Comment by REJack** [comment]
@bansalshashank you need not to create a issue if you the a PR to fix it, a PR is enough 😄
