### ISSUE TITLE
How to use AdminLTE v3 with dotnet(MVC Core, Razor Pages and Tag Helpers)?

### ISSUE THREAD

**Issue by iyilm4z** [ColorlibHQ/AdminLTE#2518]
Hi community,

[This repo](https://github.com/iyilm4z/admin-lte-dotnet) made by me shows how to implement layout and starter page of AdminLTE v3 for dotnet technologies **MVC Core**, **Razor Pages** and **Tag Helpers**. I did layout implementation _as modular as possible_ to control it better. I hope you guys can learn something from my approach.

Kind regards.

**Comment by REJack** [comment]
Thats a nice demo repo, I'll add this to the implementations list in the docs.

**Comment by iyilm4z** [comment]
@REJack thanks! i'll do it better day by day. Give it a star:)

**Comment by REJack** [comment]
I've added your repo link in the docs, it will published on the online docs with the next release.

**Comment by iyilm4z** [comment]
@REJack thanks!
