### ISSUE TITLE
[FEATURE] Top Navigation + Sidebar - Toggle menu

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2519]
@REJack i'm using sidebar as fixed without changing it by page-wise. In my project i have added active class using jquery and Windows based. so i don't need to copy `sidebar `on every page i just include it.

- My question
Is there any solution if we use `layout-top-nav` class in body my toggle slide to left, but what if my header is fixed for every-page and i can't change it.

Is there any solution so i can use `layout-top-nav` and `sidebar-mini` and toggle can't slide with it.

Or what if i want to use `layout-top-nav` with `sidebar-mini`.

**Comment by REJack** [comment]
`layout-top-nav` & `sidebar-mini` works together but looks not really good 😄 You can use the `pages/layout/top-nav-sidebar.html` and add sidebar-mini to body class.

**Comment by deepak458** [comment]
@REJack i want to say my `sidebar-nav & header` is fixed for all page and i can't change classes for any specific page but i can change class of body and other parts, so if i need `layout-top-nav` for some specific page page i can use them but when i use `layout-top-nav` class it's worked but my `sidebar-toggle btn` slide to left because now there is no sidebar present.

when user click on `sidebar-toggle btn`  then `layout-top-nav` work but still `sidebar-toggle btn` is behind the sidebar because now `layout-top-nav` has been clicked and `sidebar opened`

so is there any solution for so we can fix `toggle btn` or we can also use header logo with `sidebar-mini` so my toggle not slide every time when we use `layout-top-nav`

**Comment by REJack** [comment]
Idk but you could try to use the layout-top-nav structure without `layout-top-nav` class added, the layout-top-nav class changes the default margin from the content with sidebar.
For now I do not know any solution.
