### ISSUE TITLE
[FEATURE] Exapandable tables

### ISSUE THREAD

**Issue by bansalshashank** [ColorlibHQ/AdminLTE#2520]
**Is your feature request related to a problem? Please describe.**
Recently in a use case, I wanted to have an expandable table to that the edit form can be rendered in the table itself instead of redirecting the user to another page  

**Describe the solution you'd like**
I would like to add some classes to the table to make it expandable like cards

**Comment by REJack** [comment]
Please send some screenshots as demo/example.

**Comment by bansalshashank** [comment]
https://stackblitz.com/angular/ygdrrokyvkv?file=app%2Ftable-expandable-rows-example.html

**Comment by REJack** [comment]
Oh ok nice, I'll add this to v3.1.

**Comment by bansalshashank** [comment]
I'll raise the PR for the same in a while

**Comment by REJack** [comment]
Ok nice, please create a Table.js or TableHelper.js like the Dropdown.js for this.

**Comment by bansalshashank** [comment]
#2528

**Comment by REJack** [comment]
PR merged 😄
