### ISSUE TITLE
[BUG]brand-link - transition

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2523]
Brand Link transition is little slow from aside menu. while we are using it with layout-top-nav.

Check Below Images

![image](https://user-images.githubusercontent.com/29248598/73350201-99ca3800-42b2-11ea-8adb-cf097d5c3b5f.png)

![image](https://user-images.githubusercontent.com/29248598/73350218-a353a000-42b2-11ea-8caa-0e6881bbd1fb.png)

![image](https://user-images.githubusercontent.com/29248598/73350235-ab134480-42b2-11ea-8f4f-4062668166db.png)

**Comment by REJack** [comment]
I'll look over the sidebar transitions with layout-top-nav, but I don't know if I can fix this :/.

**Comment by REJack** [comment]
Which body classes you used, layout-fixed or something?

**Comment by REJack** [comment]
I've added a fix for this, according to your picutres I would guess you use navbar fixed and bg-navy on brand-link.
