### ISSUE TITLE
[BUG] layout-fixed with layout-top-nav

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2525]
@REJack when we use `layout-top-nav` class with `layout-fixed`, It's freeze sidebar

**Comment by REJack** [comment]
For sure, layout-top-nav doesn't work with layout-fixed. layout-top-nav also set the content width to 100% which isn’t perfect for layout-fixed.

**Comment by deepak458** [comment]
@REJack Thanks for quick reply, I know but because `layout-top-nav` doesn't work with `layout-fixed` then sidebar have to 100% height from top to bottom it's looks not good when it's end in middle have a look in below image.

![image](https://user-images.githubusercontent.com/29248598/73525192-b3938880-4434-11ea-9ac4-bcda294ecd9d.png)

**Comment by REJack** [comment]
I'll add a fix for this 😄

**Comment by deepak458** [comment]
Thanks
