### ISSUE TITLE
How can I custom the main sidebar like I test in the demo? Please advice.

### ISSUE THREAD

**Issue by jensysantana** [ColorlibHQ/AdminLTE#2530]
How can I custom the main sidebar like I test in the demo? Please advice.

**Comment by REJack** [comment]
AdminLTE v3 has servals custom classes to change style of the main sidebar, check out the [docs](https://adminlte.io/docs/3.0/components/main-sidebar.html) for this.

**Comment by jensysantana** [comment]
ok thank you so much.
