### ISSUE TITLE
V3 mobile calendar not reponsive

### ISSUE THREAD

**Issue by Lucipher** [ColorlibHQ/AdminLTE#2531]
V3 mobile calendar not reponsive

![image](https://user-images.githubusercontent.com/1323545/73602347-84eced80-45ad-11ea-857e-f4c09e8d1fe5.png)

**Comment by REJack** [comment]
That's a common bug from fullcalendar, I'll add a small workaround for this 😄

**Comment by MarnusTainthong** [comment]
i found problem same this
![image](https://user-images.githubusercontent.com/36034933/73861082-1d65c500-486f-11ea-8310-0811da204832.png)

not responsive for medium and small screen.

**Comment by REJack** [comment]
@MarnusTainthong your problem is related to DataTables not to AdminLTE itself, may you need to change something.

**Comment by MarnusTainthong** [comment]
> @MarnusTainthong your problem is related to DataTables not to AdminLTE itself, may you need to change something.

thank you.

**Comment by REJack** [comment]
I've added a workaroud for this in the master branch.
