### ISSUE TITLE
[BUG] Card Refresh triggers jQuery's load twice on the first click

### ISSUE THREAD

**Issue by rwutzke** [ColorlibHQ/AdminLTE#2532]
Using the Data API for the Card Refresh Plugin, the first click on a refresh button triggers two loads. Apparantly, this is due to the default of `loadOnInit` being set to `true` (i.e. it can be "fixed" by setting that default value to `false` in the javascript sources). But I can hardly imagine that this is a desired functionality?
I am using the current version 3.0.2

**Comment by REJack** [comment]
I've fixed this behavior in the master repo, now the script loads correctly on page load and also not loads anymore twice on click.
