### ISSUE TITLE
CardRefresh plugin issue

### ISSUE THREAD

**Issue by netstreet** [ColorlibHQ/AdminLTE#2533]
i have issue change content: or all others parameters..
below my code what i use but still CardRefresh use the default settings what it is set to in CardRefresh.js

i try to found examples but not shown in the AdminLTE document.

my code something wrong or i'm undestand something wrong :D this really is possible ;)

`('[data-card-widget="card-refresh"]').CardRefresh({
      content: '.card-data',
      loadInContent: true,
      loadOnInit: true,
      responseType: 'json',
      overlayTemplate: '<div class="overlay"><div class="fa fa-refresh fa-spin"></div></div>',
    })`

**Comment by ZeroPit** [comment]
I'm currently at the same problem and load the corresponding data via data

      <button type="button" id="card-refresh_widget"
            data-card-widget="card-refresh" data-source="...">
            <i class="fas fa-sync-alt"></i>
      </button>

      <script>$("#card-refresh_widget").CardRefresh("load"); </script>

Only "load" loads everything twice, which I fix with another else


      CardRefresh._jQueryInterface = function _jQueryInterface(config) {
        var data = $(this).data(DATA_KEY);
        var options = $(this).data();
        if (!data) {
            data = new CardRefresh($(this), options);
            $(this).data(DATA_KEY, typeof config === 'string' ? data : config);
        }
        else {
            if (typeof config === 'string' && config.match(/load/)) {
                data[config]();
            } else if (typeof config === 'object') {
                data._init($(this));
            }
        }
      };
     
maybe it will be fixed in the next version and the _init use the config and not the $(this) reference

**Comment by REJack** [comment]
I've fixed this behavior in the master branch, now the script loads correctly on page load.
