### ISSUE TITLE
select2 focus border color

### ISSUE THREAD

**Issue by giovanierthal** [ColorlibHQ/AdminLTE#2534]
select2 fields, where multiple = false, do not change the border color when focused.

**Comment by REJack** [comment]
Please provide more informations like a picture, example code or link. 
Also which version of AdminLTE is related to this bug?

**Comment by giovanierthal** [comment]
I don't think it's a bug, it's just a "concept" that I follow.

For example, on windows:

[https://i.imgur.com/umbg5wj.png](url)

The text box and the drop-down list have blue borders.

Select2 editors have only "text input" with a blue border.

Single selection:: [https://i.imgur.com/CVzb3ym.png](url)
Multiple selection: [https://i.imgur.com/ipNv9SZ.png](url)

If someone understands that this behavior is ideal, great, otherwise I will respect it.

**Comment by REJack** [comment]
That's the correct behavior because the focus is on the input on both times, the focus isn't on the dropdown itself on single selection. But I'll change the border color too to get the correct behavior if the serach box is disabled.

**Comment by REJack** [comment]
I've fixed this in master branch.

**Comment by charlienux** [comment]
When the focus is on a multiple selector and the list of options is closed, the border changes color correctly to indicate that it has the focus.

However if the focus is on a single selector and the list of options is closed, the border does not change color to indicate that it has focus.

**Comment by REJack** [comment]
@charlienux Did you tested the master repo or v3.0.2? Also can you send me some example images?

**Comment by charlienux** [comment]
@REJack I did the test with the master repository. The same problem arises.

It can be seen on the 'Advanced Demo' page. When clicking on the first minimal select, the list of options appears, if Shift-Tab is pressed, the list is closed and the focus remains on the element, however the blue border does not appear indicating that the element has the focus . Pressing Tab advances to the next select, a multiple select where the blue border does appear indicating that it has focus. Again, if Shift-Tab is pressed, the focus returns to the minimal select, however the blue border does not appear.

**Comment by REJack** [comment]
Ok this are two issues, 
1. the single select2 focus isn't available for main container (div can't focused), but it comes with an extra css class that select2 adds to the element on focus one of the focusable child elements.
2. if you "shift-tab" you pick the hidden select element that will used as base of the select2 generation, only the select2 authors are able to change this behavior.


I've added a fix for this to the master branch. You can test it 😄

**Comment by charlienux** [comment]
@REJack Thanks for your help.

Reviewing it seems that this behavior occurs when select2 has default as its theme.

It does not happen when select2 sets 'bootstrap4' as the theme.

**Comment by REJack** [comment]
Ok 😄 but I also doesn't modify the "bootstrap4" select2 theme. I've tested again my latest fix for the default theme and now it behaves the same way as the bootstrap 4 theme except it adds more borders 😃.
