### ISSUE TITLE
Is this possible in v3.x ? 

### ISSUE THREAD

**Issue by GaryQ** [ColorlibHQ/AdminLTE#2535]
I have a project using 2.4 and would love to migrate to v3 but I'm unable to find a way to reproduce the same look for the info boxes as this:

![Snip1](https://user-images.githubusercontent.com/3269694/73656987-f634ab00-4656-11ea-86ac-0232d12b445e.jpg)

Is there a workaround possible?
TIA

**Comment by REJack** [comment]
Try this css overrides:
```css
.info-box {
	padding: 0;
}

.info-box .info-box-icon {
	background: rgba(0, 0, 0, 0.25);
}

.info-box .progress {
	margin-left: -10px;
	margin-right: -10px;
}
```

**Comment by GaryQ** [comment]
Awesome! Thanks so much for the quick response. Looking forward to trying it out.
