### ISSUE TITLE
How to Customize the Narbar header color

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2536]
I want to customize the navbar header and give it a color of my choice that is not in the available one. 

This is the current navbar:

![adminlte_header](https://user-images.githubusercontent.com/34077129/73662556-539f1b00-469c-11ea-9958-c4300ffc2fa8.PNG)

How do I achieve this?

Thank you

**Comment by MarnusTainthong** [comment]
if color not in choice i think must to edit CSS file.

**Comment by noblemfd** [comment]
> if color not in choice i think must to edit CSS file.

Which CSS file  and how?

**Comment by REJack** [comment]
If you only want to change the navbar color you can override the color with a simple javascript (like `$('.main-header').css('background', 'rgb(255,143,13)');` but you will need may text color changes too).

You can also create a more enhanced javascript script for this, if you want to change the sidebar active or maybe more too.
