### ISSUE TITLE
control-sidebar push the content

### ISSUE THREAD

**Issue by marfab** [ColorlibHQ/AdminLTE#2537]
Hi guys,

I'm trying to use the control-sidebar (on the right) with the "controlsidebarSlide" option on "false". I wish control-sidebar would open and push the content (to make space for itself).
I'm trying this code:
`<a data-widget="control-sidebar" data-controlsidebarSlide="false" href=""><i class="fas fa-cog fa-spin"></i></a>"`
..but the control-sidebar slides over the content.

Can you help me?

Fabio

PS. this the body:
`<body class="hold-transition sidebar-mini sidebar-collapse layout-fixed">...</body>`

#version3.0

**Comment by REJack** [comment]
Try to add `.control-sidebar-push` to body.

**Comment by marfab** [comment]
It works!

Thanks a lot!!! :)
