### ISSUE TITLE
Button color style false?

### ISSUE THREAD

**Issue by MarnusTainthong** [ColorlibHQ/AdminLTE#2538]
![image](https://user-images.githubusercontent.com/36034933/73859842-484f1980-486d-11ea-92e9-b2e43880c9ae.png)
this AdminLTE v3.x

![image](https://user-images.githubusercontent.com/36034933/73860002-7d5b6c00-486d-11ea-8143-ea144463f774.png)
this AdminLTE v2.x

i not sure you you intended to change text color in button

**Comment by REJack** [comment]
The base style and colors of the button was changed with moving to bootstrap 4 also the primary color. This was a decision of the original author of AdminLTE and I will keep it.
