### ISSUE TITLE
How to change theme colors to custom values

### ISSUE THREAD

**Issue by omarko** [ColorlibHQ/AdminLTE#2539]
With AdminLTE 3.0.2, I am trying to implement a system that allows the user to choose their own menu and sidebar colors from a color picker. The result would probably be in a hex rgb

Is this possible? 

Thanks

**Comment by REJack** [comment]
You can achieve this with a javascript.

**Comment by omarko** [comment]
Of course, I was kind of hoping for the custom switch to enable this, as seen here: 

https://adminlte.io/docs/3.0/layout.html

Thanks for the help
