### ISSUE TITLE
[bug]while v3 miss bower_components which in v2

### ISSUE THREAD

**Issue by lingnancfy** [ColorlibHQ/AdminLTE#2540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.0]
 - Operating System:  [e.g. macOS Catalina]
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
The bower_components was removed since the whole plugins come from npm and not bower, also bower was removed from AdminlTE v3 since its not maintained anymore.
