### ISSUE TITLE
[QUESTION] framework recommendation

### ISSUE THREAD

**Issue by edwardtilley** [ColorlibHQ/AdminLTE#2542]
Python & Django - I've looked into using Python and Django to run this front-end template but am concerned that Django only permits a single requests thread. This limitation restricts Dash Plotly users and so I assume that it will also restrict users of this template?

Native Node.js - There is native node.js login authentication, database (MySQL, etc) support, and I assume email and other apps showcased on the dashboard's nav menus. Is my assumption true? Are all of the apps shown on the template node.js apps? or plugins?

PHP - What is the benefit of using Laravel over Python Django?

**Comment by REJack** [comment]
First of all the Template itself doesn't recommend any framework, it's just a plain HTML and you can use it in any framework that uses HTML to display content.

> Python & Django - I've looked into using Python and Django to run this front-end template but am concerned that Django only permits a single requests thread. This limitation restricts Dash Plotly users and so I assume that it will also restrict users of this template?

That's true, it's a Django limitation so you would get restricted also with AdminLTE.

> Native Node.js - There is native node.js login authentication, database (MySQL, etc) support, and I assume email and other apps showcased on the dashboard's nav menus. Is my assumption true? Are all of the apps shown on the template node.js apps? or plugins?

The external plugins they AdminLTE comes with aren't nods.js apps, they are all only JS/CSS plugins and they are only delivered via npm. (mostly if the plugin have a nodejs app base, they might use only it to compile the js or css).

> PHP - What is the benefit of using Laravel over Python Django?

That's hard to say, I personally like PHP and use Laravel (I use it also for new projects with the [Laravel-AdminLTE](https://github.com/jeroennoten/Laravel-AdminLTE) package). I would say there is no real benefit, both can pretty much the same in my opinion . Both supports high scalability, both have large community, both uses ORM for DBs and so on the main difference is only the language.

Laravel comes also with a simple login authentication and Laravel also provides a fast micro-framework of it called Lumen which is used to develop micro-services and API development with the intent of providing speed and high response time.

You can also checkout this comparsion of [Laravel & Django](https://hackr.io/blog/django-vs-laravel)

I hope this helps you 😄 If I worte something wrong please correct me.

**Comment by edwardtilley** [comment]
Thanks - that is a help. I am trying to avoid PHP I think. It's great; I just want to work with a little more "trending" language if I can. I've done a lot of PHP and I know Wordpress and many significant developments are built in PHP - and its very fast as well.

I didn't mention a Flask - Python implementation. This would not have Django's "single requests thread" restriction. Is there a quasi "supported" Flask fork that implements the template with its login, chat, email, calendar, and other apps, etc?

**Comment by REJack** [comment]
I don't know if there is any AdminLTE Flask implementation, I didn't get any information about new implementations that otherwise I would add it to the implementations list in the docs 😄, but I would guess there is only a v2 version.

**Comment by rudipratm** [comment]
I'm developing a website using admin lte, and I'm currently using CodeIgniter framework. It's easy and feels compatible with it.

**Comment by REJack** [comment]
@rudipratm Which CI version? 3 or 4-rc? 😄 Also which Auth Lib you use for it?

**Comment by rkorzeniewski** [comment]
@edwardtilley - I've develop [IBAdmin](https://github.com/inteos/IBAdmin) application with Django and AdminLTE. It is working great!

**Comment by rudipratm** [comment]
@REJack I'm using CodeIgniter 3 for now, and I didn't use Auth Lib, just normal a self-made authentication 😄. For me, AdminLTE working fine!

**Comment by REJack** [comment]
@rudipratm Give CI4 a try it's much faster and works great 😄 if you search also a good and enhanced Auth Lib you can checkout [CodeIgniter-Aauth](https://github.com/emreakay/CodeIgniter-Aauth) (v3-dev branch is for CI4, ~95% tested with Migrations, Social Logins, TOTP and many more features).

**Comment by rudipratm** [comment]
@REJack thank you for your information! I'll give a try!

**Comment by safen** [comment]
how to set the default **Tab** to load in **Tabbed IFrame Plugin**?
