### ISSUE TITLE
How to edit text style of info-box

### ISSUE THREAD

**Issue by MarnusTainthong** [ColorlibHQ/AdminLTE#2543]
![image](https://user-images.githubusercontent.com/36034933/74138476-41852580-4c24-11ea-9c5e-44faeddc0d06.png)

How can i edit info-box to place text in a middle like this.
![image](https://user-images.githubusercontent.com/36034933/74138769-c3754e80-4c24-11ea-9ca3-cb7c372e532f.png)

When i remove which class 

> info-box-text

 or 

> info-box-number

Text are appear to top again.
I try to use CSS to style it but can't.

**Comment by REJack** [comment]
Place a span without any class between the `info-box-text` & `info-box-number` spans.

Like this
```html
<div class="info-box">
  <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

  <div class="info-box-content">
    <span class="info-box-text">Messages</span>
	<span>Test</span>
    <span class="info-box-number">1,410</span>
  </div>
  <!-- /.info-box-content -->
</div>
```

This will look like this:
![grafik](https://user-images.githubusercontent.com/1554582/74224044-4f848600-4cb8-11ea-9f3b-b1b4e208be1d.png)

**Comment by MarnusTainthong** [comment]
if it possible to have only text in the middle.

**Comment by REJack** [comment]
Try this with margin top 😄 

```html
<div class="info-box">
  <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>
  <div class="info-box-content">
    <span class="info-box-text mt-3">Messages</span>
  </div>
</div>
```
Or this with flex:
```html
<div class="info-box">
  <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>
  <div class="info-box-content d-flex">
    <span class="info-box-text align-self-center">Messages</span>
  </div>
</div>
```

This will look like this: 
![Screenshot_2020-02-15 AdminLTE 3 Widgets](https://user-images.githubusercontent.com/1554582/74588514-91396780-4ffd-11ea-9dbc-dc6f7859c166.png)

**Comment by KeridaoPotencia** [comment]
and the colors?
