### ISSUE TITLE
[BUG] nav-sidebar + nav-compact in compact mode

### ISSUE THREAD

**Issue by thewebartisan7** [ColorlibHQ/AdminLTE#2545]
**Describe the bug**
When adding class . nav-compact to .nav-sidebar, and then resize sidebar to compact mode, the icons seem not centered, but more on right side. I see the margin-left is higher compared to normal. Is this intentionally? 

Screenshot:

<img width="168" alt="Screenshot 2020-02-10 at 12 30 30" src="https://user-images.githubusercontent.com/57477934/74146692-f8bc7500-4c01-11ea-85f7-ae21d07a2b8f.png">

**Comment by REJack** [comment]
Which version of AdminLTE you use v3.0.0/v3.0.1? In v3.0.2 it should fixed.

**Comment by thewebartisan7** [comment]
Version 3.0.3-pre

**Comment by REJack** [comment]
Ok, I'll check this tomorrow.

**Comment by REJack** [comment]
I've fixed this in master branch.
