### ISSUE TITLE
Different Layout Options

### ISSUE THREAD

**Issue by cos2000** [ColorlibHQ/AdminLTE#2547]
Thank you very much for AdminLTE v3, i like it very much!!! But i have a little request:

The main css file (adminlte.min) with 642kb is really big. The reason is, thats the complete bootstrap.css is in there, whats ok, but it contains all colored layouts (dark, light and so on) in one file.

In AdminLTE V2 has each colored theme a own css file, so i can load only the css code that i really need. When i use the adminlte.min.css than 50% of the code isnt needed. For exampe, when i use sidebar-dark-primary, than i dont need or use the code for the light variant.

When its possible to split it in layout files its much easier for me to edit the colors and create colors for my needs! The current version is very confusing for edit!

I would like it when you can add a version without bootstrap css in it. So i can easier update bootstrap for my self! But more important for me are different layout style css files, so its more clear to work with!

Thanks again for bring AdminLTE V3 on its way and any work from you on this nice admin-theme!

Best regards
CoS

**Comment by REJack** [comment]
> In AdminLTE V2 has each colored theme a own css file, so i can load only the css code that i really need. When i use the adminlte.min.css than 50% of the code isnt needed. For exampe, when i use sidebar-dark-primary, than i dont need or use the code for the light variant.

It was skins to override the color scheme but they are not complete themes, this is also planned to come back with v4 (I've added a note in the [v4 project](https://github.com/ColorlibHQ/AdminLTE/projects/13).

> When its possible to split it in layout files its much easier for me to edit the colors and create colors for my needs! The current version is very confusing for edit!

Why it's confusing to edit the current version? I personally like it more than v2. You need only to know how to manipulate/override the scss variables.

> I would like it when you can add a version without bootstrap css in it. 

That will probably never happend, the whole project use mixins and other stuff from bootstrap. Also it's claimed to be a bootstrap based theme.

**Comment by cos2000** [comment]
> Why it's confusing to edit the current version? I personally like it more than v2. You need only to know how to manipulate/override the scss variables.

Ohh i've not used the scss - I just downloaded latest version as zip file. Dont used sass/scss files! i'll try it ;-)
