### ISSUE TITLE
[BUG] Elements not clickable with chromedriver

### ISSUE THREAD

**Issue by niklasmoeller** [ColorlibHQ/AdminLTE#2548]
**Describe the bug**
I am using WebDriver with Chrome via Chromedriver to test my site using AdminLTE. Since I switched to AdminLTE v3 I get the problem, that elements outside of the viewport are said to be not clickable. This is also the case, when I send Chromedriver against the demo page of AdminLTE v3 (e.g. https://adminlte.io/themes/v3/pages/widgets.html)

When I deactivate headless mode, I can see that it scrolls to the element, but does not seem to be able to click it.

When I remove the AdminLTE css from my page, it can click the element.

**To Reproduce**
Steps to reproduce the behavior (using chromedriver):
1. Using chromedriver
2. Go to 'https://adminlte.io/themes/v3/pages/widgets.html'
3. Click on something outside of the viewport (e.g. the link 'Documentation' in the sidebar)

**Expected behavior**
I expect chromedriver to be able to click the element, but something seem to be obscuring the element or making it not-clickable in the center of the element. I get this message

`element click intercepted: Element is not clickable at point (125, 790)\n  (Session info: chrome=80.0.3987.100)\n  (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Mac OS X 10.15.1 x86_64)`

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System:  macOS Catalina
 - Browser (Version): Chrome 80 via Chromedriver 80 (Latest)

**Additional context**
I know this is not a problem of AdminLTE alone but probably in connection with some strange chromedriver behaviour, but I was hoping to get some help here. Also as I said maybe there is some transparent element obscuring the button or some CSS that could be optimized to fix the problem (even though it's "just in a test").

**Comment by REJack** [comment]
I've never used chromedriver or something like this, could you give me some advices how I can test it on my system (macOS too).

**Comment by niklasmoeller** [comment]
If you install chrome, chromedriver and python, you should be ready to go. You probably need to install the selenium package for python using `pip`.

I wrote and tested the following script for you which produces the message and opens the browser window so you can actually see what's happening in chrome.

**test-click.py**
```python
import time
from selenium import webdriver

driver = webdriver.Chrome()  # Optional argument, if not specified will search path.
driver.set_window_size(1280, 800);
driver.get('https://adminlte.io/themes/v3/index3.html');
time.sleep(5) # Let the user actually see something!
link_to_click = driver.find_element_by_xpath('.//a[./@href][(((./@id = "Documentation" or contains(normalize-space(string(.)), "Documentation")) or contains(./@title, "Documentation")) or .//img[contains(./@alt, "Documentation")])]')
link_to_click.click();
time.sleep(5) # Let the user actually see something!
driver.quit()
```

which produces the following error

```
Traceback (most recent call last):
  File "chromedriver-test.py", line 7, in <module>
    link_to_click = driver.find_element_by_name('Documentation');
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="Documentation"]"}
  (Session info: chrome=80.0.3987.116)

niklasmoeller@Niklass-MacBook-Pro sportograf_relaunch % python3 chromedriver-test.py
Traceback (most recent call last):
  File "chromedriver-test.py", line 9, in <module>
    link_to_click.click();
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/niklasmoeller/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (125, 920)
  (Session info: chrome=80.0.3987.116)
```

**Comment by REJack** [comment]
I've found a workaround for this using move_to_element_with_offset()

Try this python script
```python
import time
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains

driver = webdriver.Chrome()  # Optional argument, if not specified will search path.
driver.set_window_size(1280, 800);
driver.get('https://adminlte.io/themes/v3/index3.html');
time.sleep(5) # Let the user actually see something!
link_to_click = driver.find_element_by_xpath('.//a[./@href][(((./@id = "Documentation" or contains(normalize-space(string(.)), "Documentation")) or contains(./@title, "Documentation")) or .//img[contains(./@alt, "Documentation")])]')
ActionChains(driver).move_to_element_with_offset(link_to_click, 0, -100).click().perform()
time.sleep(5) # Let the user actually see something!
driver.quit()
```
