### ISSUE TITLE
Hi author , PushMenu

### ISSUE THREAD

**Issue by naysw** [ColorlibHQ/AdminLTE#2551]
Hi, 
Could you please guide me how to change ==> pushmenu to overlay menu ? Thanks

**Comment by REJack** [comment]
Please provide more information like a screenshot.

**Comment by NaySoewin-1** [comment]
Hi, Thanks for your reply , Please kindly check attach screenshoot. Thanks 
https://prnt.sc/r2p81y

**Comment by REJack** [comment]
You can only achieve this with layout-top-nav and sidebar together. Like this https://adminlte.io/themes/v3/pages/layout/top-nav-sidebar.html, but in some ways it hides the pushmenu button if the sidebar is open.
