### ISSUE TITLE
[FEATURE] aria related, use button for push menu

### ISSUE THREAD

**Issue by oliverlj** [ColorlibHQ/AdminLTE#2554]
Just for the semantic, i would be better to have a button for the push menu in the template ?
```html
<button class="btn btn-link nav-link" data-widget="pushmenu" type="button"><!---->
  <i class="fas fa-bars"></i>
</button> seems to give same result of
```
```html
<a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
```

**Comment by REJack** [comment]
What's the benefits of changing it from`a` to `button`?

**Comment by oliverlj** [comment]
ember template linter warn me about this rule : 

https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-invalid-interactive.md

a role="button" would be satisfied.

**Comment by REJack** [comment]
Ok 👍 I'll change this.

**Comment by REJack** [comment]
I've updated the demo & docs example in master branch. (docs will update with the next release)
