### ISSUE TITLE
[FEATURE] Add support for select2 form-control-sm

### ISSUE THREAD

**Issue by theonly27** [ColorlibHQ/AdminLTE#2555]
**Is your feature request related to a problem? Please describe.**
Yes, if I have a lot of page, and will always add css every page if want to show the small select2

**Comment by MarnusTainthong** [comment]
Small like this ?
[https://github.com/select2/select2/issues/5769](url)

**Comment by REJack** [comment]
I've added form-control-sm support based on the newly added text-sm support in the master branch.
