### ISSUE TITLE
[BUG] Sidebar Treeview Not Work when I use Promise on vue-router

### ISSUE THREAD

**Issue by viandwi24** [ColorlibHQ/AdminLTE#2556]
**[Vue] [vue-router]**
When I use Promise on vue-router, I find the sidebar treeview doesn't work.
I've tried re-init with the following code but it still doesn't work:

`window.$('ul[data-widget="treeview"]').Treeview();`

**but when trying other re-init like layout it works :**

`window.$('body').Layout();`

**Comment by REJack** [comment]
try `window.$('ul[data-widget="treeview"]').Treeview('init');`

**Comment by viandwi24** [comment]
ok thanks, that worked for me.
