### ISSUE TITLE
[FEATURE] submenu of left side navigation should be different background color or styles

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2559]
**Is your feature request related to a problem? Please describe.**
It is not problem but it would be better if obvious.

**Describe the solution you'd like**
I would like to suggest submenues have something like different background color or some paddings from left.

**Describe alternatives you've considered**
....

**Additional context**
Please check below screenshoot. I think this is a little dificult to determine which is submenu or main menu.

![Capture](https://user-images.githubusercontent.com/5186970/74904313-f6b09e00-53d9-11ea-8a11-90d06b6c6a46.PNG)

**Comment by REJack** [comment]
> I would like to suggest submenues have something like different background color or some paddings from left.

Only with the `.nav-legacy` or `.nav-flat` on `.nav-sidebar` changes the background color. 
And `.nav-child-indent` does add a padding to the left but it push's the submenu, it's not inside the submenu elements.
