### ISSUE TITLE
[FEATURE] Live Search for Sidebar menu item

### ISSUE THREAD

**Issue by nyomanc** [ColorlibHQ/AdminLTE#2560]
Hi, currently i have multilevel menus and some menu tree have many other menus.
I think if its better to have something like searchbar in the menu like

I already tried to make like this but I dont know how to make the JS
![image](https://user-images.githubusercontent.com/38039429/74916420-67ff4980-53f8-11ea-994d-e281c58bb76d.png)
If you have some guide how to make this seach feature work , Please Tell Me
Thank You

**Comment by REJack** [comment]
There is no script for this available, but this will come with v3.1. (see #2472)
