### ISSUE TITLE
[BUG] AdminLTE fails to install with yarn and custom folder

### ISSUE THREAD

**Issue by FelipeEmerim** [ColorlibHQ/AdminLTE#2561]
**To Reproduce**
1. create a .yarnrc file with a custom --modules-folder
2. run yarn-add admin-lte

**Expected behavior**
The package should install

**Screenshots**

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'fs-extra'
Require stack:
- /home/felipe/projects/colplan/public/assets/admin-lte/build/npm/Publish.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/felipe/projects/colplan/public/assets/admin-lte/build/npm/Publish.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/felipe/projects/colplan/public/assets/admin-lte/build/npm/Publish.js'
  ]
}
```

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.2
 - Operating System:  Ubuntu 19.10

**Additional context**

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll check this within the next days.

**Comment by REJack** [comment]
I may found the problem, 
I first tried to add `yarn add admin-lte` with this .yarnrc content
```bash
--modules-folder 'vends'
```
everything works like it should after some tests, I created a blank folder and added this to .yarnrc by hand
```bash
--modules-folder vends
```
and without the single-quotes yarn add failed.

Please check this 😄

**Comment by FelipeEmerim** [comment]
Thanks for the quick response!

I did what you said and it worked perfectly. But, I believe the quotes should not be required. Every other package I have works without them. Plus, many examples of the modules-folder option do not use quotes.

On the other hand the only official docs we have is [this](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-modules-folder) and it is not clear about the behavior at all.

Also as a test I tried passing --modules-folder via cli and it behaves exactly the same as putting it in .yarnrc.

Thanks again for the support!!

**Comment by REJack** [comment]
> But, I believe the quotes should not be required

If I remember right, the quote set it to a string and without it's a constant that some scripts use as string, I didn't figured out how I can require it correctly for this behavior. And I personally set always paths as string with quotes, only if I'm lazy not 😃 

Also this look like yarn itself cause this problem and not load the node modules correctly.

> Thanks again for the support!!

No problem 😄 I close this issue.

**Comment by FelipeEmerim** [comment]
Sorry for coming back. But when I said it worked I was not quite right. When I put the quotes in my .yarnrc, yarn install the packages to the node_modules folder. That's why it worked.

With double quotes I have the same error

**Comment by REJack** [comment]
That's strange :/ I've found this issue https://github.com/yarnpkg/yarn/issues/5200 on yarn's repo that's may related to this.

**Comment by FelipeEmerim** [comment]
Thanks again. I will try that.

**Comment by juniwalk** [comment]
Hello, have you solved this issue? I am still getting errors.

```
root@s3:/router/dp_dev/sandbox # yarn -v
1.22.4
root@s3:/router/dp_dev/sandbox # npm -v
6.14.4
root@s3:/router/dp_dev/sandbox # node -v
v13.14.0
```

```
root@s3:/router/dp_dev/sandbox # yarn upgrade
yarn upgrade v1.22.4
[1/4] Resolving packages...
warning admin-lte > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning admin-lte > bootstrap-colorpicker > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning admin-lte > tempusdominus-bootstrap-4 > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning admin-lte > pdfmake > pdfkit > fontkit > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "admin-lte > bootstrap-switch@3.3.4" has incorrect peer dependency "bootstrap@^3.1.1".
warning "admin-lte > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "moment-timezone@^0.5.11".
warning "admin-lte > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "tempusdominus-core@5.0.3".
[4/4] Rebuilding all packages...
[2/2] ⠄ admin-lte
error /srv/htdocs/dp/dev/sandbox/www/vendor/admin-lte: Command failed.
Exit code: 1
Command: npm run plugins
Arguments: 
Directory: /srv/htdocs/dp/dev/sandbox/www/vendor/admin-lte
Output:
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1592377283211-0.7496240200515996/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> admin-lte@3.0.5 plugins /srv/htdocs/dp/dev/sandbox/www/vendor/admin-lte
> node build/npm/Publish.js -v

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- /srv/htdocs/dp/dev/sandbox/www/vendor/admin-lte/build/npm/Publish.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/srv/htdocs/dp/dev/sandbox/www/vendor/admin-lte/build/npm/Publish.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/srv/htdocs/dp/dev/sandbox/www/vendor/admin-lte/build/npm/Publish.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-lte@3.0.5 plugins: `node build/npm/Publish.js -v`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the admin-lte@3.0.5 plugins script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T07_01_23_836Z-debug.log
```

**Comment by REJack** [comment]
@juniwalk Try to remove your node_modules folder and reinstall with yarn again.

**Comment by juniwalk** [comment]
I have custom folder in www/vendor so my assets are in domain root, without the custom folder it works. I tried everything that was mentioned above to be tried and nothing worked. So I did remove the folder to no avail.

**Comment by FelipeEmerim** [comment]
I solved it by adding these two settings pointing to my custom directory. Note that the paths have to be absolute

# ./.yarnrc
--*.modules-folder /app/public/assets
env:
  NODE_PATH "/app/public/assets

**Comment by juniwalk** [comment]
@FelipeEmerim Well I don't like hard coding absolute path there but it really does work! Thank you.

**Comment by FelipeEmerim** [comment]
@juniwalk Me neither, but it is the only way I got it working. It seems to be a problem with yarn as mentioned above.
