### ISSUE TITLE
[FEATURE] - add top-margin option to Customize AdminLTE sidebar

### ISSUE THREAD

**Issue by drankje** [ColorlibHQ/AdminLTE#2562]
**Is your feature request related to a problem? Please describe.**
I think it's good to add an option to add pt-1 top-margin to the first sidebar link in a dropdown menu. 

**Describe the solution you'd like**
After my back-end generates sidebar nodes and jQuery tells me the document was ready I loop with this basic script:
https://gist.github.com/drankje/7241016a715d16e5983b4327ebc6adc0

It might be nice to add this to the current demo js for the right sidebar with customization toggle checkboxes. 

**Additional context**
Screenshot before and after: https://imgur.com/a/I1jSXtn

**Comment by REJack** [comment]
I don't enhance the demo.js with custom scripts like this, this is only a personal style preferences and I wouldn't add `pt-1` to the elements via JS.

The demo.js is only to show some extra classes/options for the panel that comes with AdminLTE itself (non-boostrap4 classes).
