### ISSUE TITLE
[FEATURE] Please add different examples for editors (textarea)

### ISSUE THREAD

**Issue by Uranjitsu** [ColorlibHQ/AdminLTE#2566]
Please add different examples for editors (textarea). Example: Markdown or other examples

**Comment by REJack** [comment]
I personally doesn't use often text edtiors, if you can send me some example editors it would a lot.

**Comment by Uranjitsu** [comment]
Examples:
https://codemirror.net/index.html
https://ckeditor.com/ckeditor-5/demo/
http://nicedit.com/demos.php
https://pandao.github.io/editor.md/
https://lab.lepture.com/editor/
https://simplemde.com/
https://froala.com/wysiwyg-editor/examples/textarea/
https://textbox.io/

**Comment by REJack** [comment]
I'll look over examples, but I have to lose the licenses if I can add them to AdminLTE without any problems.
