### ISSUE TITLE
[BUG] Widget icon dont work

### ISSUE THREAD

**Issue by Uranjitsu** [ColorlibHQ/AdminLTE#2567]
Widget Icon FA dont work for me:
`<span class="info-box-icon bg-warning"><i class="fas fa-picture-o" aria-hidden="true"></i></span>`

or
`<span class="info-box-icon bg-warning"><i class="far fa-picture-o" aria-hidden="true"></i></span>`

The icon is not displayed.

**Comment by REJack** [comment]
You try to use a not existing fontawesome 5 icon, the icon picture (fa-picture-o) was renamed to image `fa-image`. A ton of icons was renamed in fontawesome 5.

**Comment by Uranjitsu** [comment]
Oh sorry. Fixed :D
