### ISSUE TITLE
In Admin lte 3.0.2 mobile view of side bar menu has issue

### ISSUE THREAD

**Issue by mukeshkamboj1** [ColorlibHQ/AdminLTE#2568]
**Describe the bug**
When you open in mobile view, and click on 3 dots to open sidebar, then there is no option to close sidebar,.

**To Reproduce**
1. Go to ' three dots in mobile view...'
2. Click on 'three dots to open side bar menu....'
After that no easy step to close sidebar or hide

**Expected behavior**

**Screenshots**
![lteerror](https://user-images.githubusercontent.com/40025869/75329569-d2efcb00-58a5-11ea-8abf-caaf5f0ad1f3.jpg)

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.2]
 - Operating System:  [e.g. Windows 10]
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
You only need to click on the content then the sidebar closes.

**Comment by mukeshkamboj1** [comment]
In mobile view , there is no space left to click outside sidebar,i m using in reactjs, when i click on content componenet, nothing happen, i just use style of this template

**Comment by mukeshkamboj1** [comment]
You only need to click on the content then the sidebar closes, .. i think this is not better approach to hide also,,, i m using in reactjs, when i click on content componenet, nothing happen, i just use style of this template

**Comment by REJack** [comment]
You need to init the Layout script, you will also need to init Treeview for the sidebar submenu's. 

This is also need on Angular & Vue too.

**Comment by mukeshkamboj1** [comment]
need to init the PushMenu script, you will also need to init Layout for layout fixed and Treeview for the sidebar submenu's.,   how???

**Comment by REJack** [comment]
You need to run these JS lines after load/init your app:

```js
$('body').Layout();
$('[data-toggle="push-menu"]').PushMenu();
$('[data-widget="treeview"]').Treeview();
```

But I don't know where and how, I don't use react.

**Comment by mukeshkamboj1** [comment]
not understand how to add in reactjs
