### ISSUE TITLE
[BUG] Sidebar Hover Problem

### ISSUE THREAD

**Issue by tuncaybahadir** [ColorlibHQ/AdminLTE#2569]
In the Customize Adminlte menu, we select the "Sidebar nav compact" and "Sidebar nav child indent" settings, and in the hover states of the child elements in the sidebar, the menu shifts to the left.

1: Click "Customize AdminLTE" menu
2: Choose "Sidebar nav compact"
3: Select "Sidebar nav child indent"
4: Hover over any menu via Sidebar. You will see the error

This problem appeared with the last update, there was no such problem before. I request your correction.

In the second picture, you can see the icons shifted by ~ 5px to the left.

**Screenshots**
![resim](https://user-images.githubusercontent.com/1303432/75389089-0c9cf200-58f7-11ea-8cc1-a7946b13bf4f.png)

![resim](https://user-images.githubusercontent.com/1303432/75389391-7a491e00-58f7-11ea-969a-7acfa1fd2dc5.png)

![resim](https://user-images.githubusercontent.com/1303432/75389439-8af99400-58f7-11ea-95ea-8279ba969d4f.png)

 - AdminLTE Version: Last Update
 - Operating System:  Windows 10
 - Browser (Version): Chrome (Latest), Firefox Developer Edition(Latest)

**Comment by REJack** [comment]
Thanks for the report, I've fixed it in master branch.
