### ISSUE TITLE
[Question] I got a lot of spam mails

### ISSUE THREAD

**Issue by cataclysmuprising** [ColorlibHQ/AdminLTE#2576]
What are those and how can this be possible ? It is new for me ... and I can't find those issues on here.

![Capture](https://user-images.githubusercontent.com/5186970/75518754-09f1e800-5a30-11ea-9c56-db8eaff723fa.PNG)

**Comment by REJack** [comment]
They was spam related and GitHub removed them right away only one wasn’t removed that I closed.

**Comment by cataclysmuprising** [comment]
Thank you bro ... I was confused with them :D .... I thought I only got them ...
