### ISSUE TITLE
[DOCS] Migration from v2.4.x: Do not include bootstrap styles separately

### ISSUE THREAD

**Issue by Tilogorn** [ColorlibHQ/AdminLTE#2577]
I just noticed the hard way that whereas in `V2` you had to include **bootstrap and AdminLTE styles**, now in `V3` you must include **just AdminLTE styles** because they **contain** the bootstrap styles.

It would be nice to get this info at a central place, e.g. in the [upgrade guide](https://adminlte.io/docs/3.0/upgrade-guide.html).

Example `V2` https://adminlte.io/themes/AdminLTE/starter.html: 
```html
<html>
    <head>
        [...]
        <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
        [...]
        <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
```

Example `V3` https://adminlte.io/themes/v3/starter.html:
```html
<html>
    <head>
        [...]
        <link rel="stylesheet" href="dist/css/adminlte.min.css">
```
Took me way too long on a legacy codebase to figure out why every style got applied twice.

**Comment by REJack** [comment]
I see what you mean, I'll update the upgrade guide according to this issue.

**Comment by REJack** [comment]
I've updated the upgrade guide, the online docs will updated with the next release.
