### ISSUE TITLE
[FEATURE] Working Contact Form

### ISSUE THREAD

**Issue by c0fe** [ColorlibHQ/AdminLTE#2580]
**Purpose**

The purpose of this issue ticket is to propose a feature addition that I would implement but I want to see what the maintainers think of this before I spend time on something that has no chance.

**Feature**

The proposed feature is to add a second form example into the admin template, one that would utilize a PHP script on the back to perform validation (backend validation is more secure) and then printout the results.

I want to create two designs, one using regular bootstrap form fields and one using custom form fields, both would perform backend validation with the frontend handling printing of the error messages.

Currently the project has no PHP scripts at all so i wanted to see if this is something that the maintainers are open to having added.

**Comment by REJack** [comment]
AdminLTE itself doesn't comes with any backend related scripts (neither PHP, Python, ASPnet, NodeJS or other for frameworks/languages) also I doesn't want to create such scripts to keep AdminLTE complete independent from any backend/framework.
