### ISSUE TITLE
[FEATURE] Sign ut button.

### ISSUE THREAD

**Issue by iampopular** [ColorlibHQ/AdminLTE#2581]
For Release: https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.0.2
Wehre i can find Sign Out button which present in https://adminlte.io/themes/AdminLTE/index2.html top navigation.

**Comment by REJack** [comment]
Checkout [this](https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html).

**Comment by iampopular** [comment]
Thanks for point it out !!
