### ISSUE TITLE
[BUG] Mobile View For DataTables 

### ISSUE THREAD

**Issue by abdulhamidnugroho** [ColorlibHQ/AdminLTE#2583]
**Describe the bug**
Mobile View For DataTables (Not Responsive)
**To Reproduce**
1. Go to 'Tables'
2. Click on 'DataTables'
3. Make Display to mobile View

**Expected behavior**
Seems not responsive website especially for DataTables

**Screenshots**
![image](https://user-images.githubusercontent.com/40796875/75754726-c8c74400-5d5f-11ea-847f-5e3749ecd57a.png)

**Environment (please complete the following information):**
 - AdminLTE Version: [v3.0.2]
 - Operating System:  [Windows 10]
 - Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
I've updated the demo to use the DataTables Responsive Plugin.
