### ISSUE TITLE
[FEATURE]Change overlay color

### ISSUE THREAD

**Issue by pauldbentley** [ColorlibHQ/AdminLTE#2584]
**Is your feature request related to a problem? Please describe.**
The color of the overlay spinner is fixed as `#343a40` - this is a bit too dark for my template

**Describe the solution you'd like**
I'd like to use one of the other `text-*` classes to change the color.

**Describe alternatives you've considered**
I tried adding `text-*` to the `div.overlay` and the `i` inside but this doesn't work.

**Comment by REJack** [comment]
Try to add `text-*` on the `i`

**Comment by pauldbentley** [comment]
> Try to add `text-*` on the `i`

I tried that but it didn't work.  In `_miscellaneous.scss` there is a selector `.card .overlay>.fas` is overriding this.

**Comment by REJack** [comment]
I can't replicate this, which AdminLTE you use? 

If I add e.g. `text-danger` to `i.fas` it changes correctly the color of the icon and look like this:
![image](https://user-images.githubusercontent.com/1554582/75900074-a9521900-5e3c-11ea-870a-0b79dce0c54f.png)

I've used this code as demo: (based on a small-box but works also with cards, etc.)
```html
<div class="small-box bg-info">
  <!-- Loading (remove the following to stop the loading)-->
  <div class="overlay">
    <i class="fas fa-3x fa-sync-alt text-danger"></i>
  </div>
  <!-- end loading -->
  <div class="inner">
    <h3>150</h3>
    <p>New Orders</p>
  </div>
  <div class="icon">
    <i class="fas fa-shopping-cart"></i>
  </div>
  <a href="#" class="small-box-footer">
    More info <i class="fas fa-arrow-circle-right"></i>
  </a>
</div>
```

The .overlay > i.fas (and any other) doesn't use `!important` and allows to override it.

**Comment by pauldbentley** [comment]
It works for `text-danger` as per your example as this is defined with `!important` - but the text color variations are not defined with `!important`, for example I wanted to use `text-gray` or `text-orange` which don't work.  It's only a minor issue, I can use `text-secondary` for now.

**Comment by REJack** [comment]
I've added a fix for this in the master branch.
