### ISSUE TITLE
Quick fix for warning color for bg-warning and btn-warning [BUG]

### ISSUE THREAD

**Issue by Elvis254** [ColorlibHQ/AdminLTE#2588]
Both bg-warning and btn-warning use black color instead of white.
After changing the codes to these ones the styling will be much better and pleasant to the eyes.

```
.btn.btn-warning { color: #f8f9fa !important; background-color: #fd7e14; border-color: #fd7e14; box-shadow: none; }
.btn.btn-warning:hover { color: #f8f9fa; background-color: #dc6502; border-color: #dc6502; }
.info-box.bg-warning, .info-box.bg-gradient-warning { background-color: #fd7e14 !important; color: #ffffff !important; }
.info-box.bg-warning .progress-bar, .info-box.bg-gradient-warning .progress-bar { background-color: #ffffff !important; }
```

 - AdminLTE Version: 3.0.2
 - Operating System:  Windows 10
 - Browser (Version): Chrome

Thanks a lot for this awesome HTML5 framework.

**Comment by REJack** [comment]
I'll look over this tomorrow 😄

**Comment by Elvis254** [comment]
Okay it will be much appreciated. :)

**Comment by REJack** [comment]
The "warning"-color (yellow) with a white text color have not a good contrast to each other, that's why I stay with this. We use a Bootstrap 4 SCSS function to get a good contrast that's why it sets a black text color instead of white text color.
