### ISSUE TITLE
[BUG] Footer has a extra white space under it

### ISSUE THREAD

**Issue by gh-supersudo** [ColorlibHQ/AdminLTE#2589]
**Describe the bug**
Footer has extra white space.

**Expected behavior**
No extra white space.

**Screenshots**
![alt text](https://images2.imgbox.com/b8/0c/9XIAUHN3_o.png "footer adminlte")

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.2
 - Operating System: Manjaro Linux
 - Browser (Version): Firefoxv73.0.1

**Additional context**
I noticed that when I removed the auto calculated min-height attribute in the content-wrapper, the white space gets removed.

**Comment by REJack** [comment]
I can't replicate this, can you give me a code example. May this collides with any extra classes.

**Comment by gh-supersudo** [comment]
> I can't replicate this, can you give me a code example. May this collides with any extra classes.


```html
<div id="app" class="wrapper">
  <!-- Main content -->
   <div class="content-wrapper">
    <div class="container-fluid">
       <div class="row" style="height: 100%">
       <div class="col-md-6 col-sm-12 ml-auto bg-white pt-3">
        <h3><i class="fas fa-user-lock"></i>Login</h3>
        <hr>
        <form method="POST" action="#">
           <!-- Login Form -->
        </form>
       </div>
     </div>
    </div>
  </div>
  <!-- Footer -->
   <footer class="main-footer" style="background-color: fuchsia; color: #000;">
      <div class="d-flex align-items-center justify-content-center">
        Footer
      </div>
    </footer>
</div>

<style>
</style>
```

**Comment by REJack** [comment]
Do you have any body class too?

**Comment by gh-supersudo** [comment]
Oh sorry, I edited it.

**Comment by REJack** [comment]
No problem :D 

The navbar markup would be helpful too or even a complete HTML markup incl. navbar sidebar & footer. I still can't replicate it :/

**Comment by gh-supersudo** [comment]
Here is the top and side navigation.
```
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
   <!-- Top navigation-->
</nav>
<!-- Sidebar -->
<aside class="main-sidebar elevation-4">
     <div class="sidebar">
         <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
              <!-- Sidebar links-->
          </ul>
        </nav>
      </div>
</aside>
```

**Comment by REJack** [comment]
I can't still not replicate it :/  may it comes from any content inside the navbar or content itself with the demo content (used starter) it work like it should.

**Comment by gh-supersudo** [comment]
Huh.. Is there a way to prevent the package from adding calculated min-height? Because there are no problems when I remove that in console.

**Comment by gh-supersudo** [comment]
The problem only occurs when the content is less than the height of the screen.

**Comment by REJack** [comment]
> Huh.. Is there a way to prevent the package from adding calculated min-height? Because there are no problems when I remove that in console.

Nope at the moment not, but I'll add an option for this.

**Comment by gh-supersudo** [comment]
I think I solved it. I removed the wrapper class and it worked.

**Comment by REJack** [comment]
Ok, but on small devices is the overlay over the content with expanded sidebar not available without the wrapper class and then you can't close the sidebar on small devices.

**Comment by REJack** [comment]
I've added a option to the Layout.js called panelAutoHeight (`data-panel-auto-height`) to disable or add an offset to the calculation, coming with the next version (v3.0.3).
