### ISSUE TITLE
Open Sans Font 

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#2591]
Open Sans Font Looks Good

Plz make an offline file for fonts

**Comment by REJack** [comment]
I have already a note on the v3.1 project to replace the online google font with a NPM loaded font, but I will look over the code and may I add the Open Sans font as optional font to the project via a body class.

**Comment by XhmikosR** [comment]
@REJack https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro

Just make sure you select the proper options, i.e you probably just need modern browsers and only a few `font-weight`s.

But please do note that Google Fonts does more behind the scenes, so this method has its downsides.

**Comment by XhmikosR** [comment]
Oh, also make sure you manually add `font-display: swap` because the aforementioned helper does add it IIRC.

**Comment by XhmikosR** [comment]
Although TBH this seems outside the scope of the project IMHO. People should figure this out themselves if they need to. You should stick to Google Fonts for the reasons I mentioned above.

**Comment by REJack** [comment]
@XhmikosR Do you preferr add the font files directly in the repo instead of installing it via npm? 

I would add the `source-sans-pro` npm package instead of managing per hand.

**Comment by XhmikosR** [comment]
I wouldn't bother personally. It's bloat and something few people will need. After all, the code has fallback fonts.
