### ISSUE TITLE
[BUG] Accent colour affecting sidebar

### ISSUE THREAD

**Issue by codemunkie15** [ColorlibHQ/AdminLTE#2592]
**Describe the bug**
The accent colour is affecting the sidebar. Is this intentional? I would have expected the sidebar links to stay black.

**To Reproduce**
Add an accent colour on the demo page

**Expected behavior**
Sidebar links should not have accent colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/13065317/76304375-3113a980-62bb-11ea-846f-dc32b3443279.png)

**Comment by REJack** [comment]
This bug is already fixed and will released with v3.0.3.
