### ISSUE TITLE
[Question] Sticky footer in sidebar nav

### ISSUE THREAD

**Issue by codemunkie15** [ColorlibHQ/AdminLTE#2593]
Are you able to provide an example on how to have a sticky footer in the sidebar navigation please? I am using the below currently but because of `position: absolute` it is overlapping the nav items when they are expanded. Note that I am using fixed sidebar also. I also experimented with `flex-fill` but could not get it working.

```
  .sidebar-footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      padding: 1rem;
  }
```

```
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Nav items -->
    </div>
    <div class="sidebar-footer">
      <img src="https://via.placeholder.com/150" />
    </div>
    <!-- /.sidebar -->
```

![image](https://user-images.githubusercontent.com/13065317/76399308-4f8aab00-6376-11ea-8012-a33f62a1d034.png)

![image](https://user-images.githubusercontent.com/13065317/76399342-5dd8c700-6376-11ea-8eff-acc78d1de6c1.png)
Footer image should not overlap here - it should be displayed below the items.

Many thanks

**Comment by REJack** [comment]
Look at this https://github.com/ColorlibHQ/AdminLTE/issues/2441#issuecomment-564536740.

**Comment by codemunkie15** [comment]
That is not quite what I am after. The example you posted has a fixed footer where it is always visible. I want the footer to stick to the bottom but also be part of the scrollable content if that makes sense?

**Comment by REJack** [comment]
Simply add a empty(no classes) li in the nav or div in div.sidebar but it’s should not position absolute or outside of div.sidebar. div.sidebar is the element that get the scrollbars on layout-fixed.

**Comment by codemunkie15** [comment]
I have added a `div` inside the sidebar class after the `<nav>` but how do I push it to the bottom of the screen?

**Comment by codemunkie15** [comment]
I managed to solve this using flexbox. Add `d-flex` and `flex-column` to the sidebar, add `flex-fill` to the nav and then add the footer after the nav, inside the sidebar:

```
    <div class="sidebar d-flex flex-column">
       <nav class="mt-2 flex-fill">
         <!-- Navbar -->
       </nav>

       <!-- Footer -->
       <div class="p-3">
          <img src="https://via.placeholder.com/150" />
       </div>
    </div>
```

If you're using overlayScrollbar you also have to add `os-host-flexbox` to the sidebar and the below style to turn the container into a flexbox:

```
.os-content {
    display: flex;
    flex-direction: column;
}
```
