### ISSUE TITLE
[QUESTION] using color palette

### ISSUE THREAD

**Issue by Neurozone** [ColorlibHQ/AdminLTE#2594]
**Describe the bug**
I'm trying to use classes defined here: https://adminlte.io/themes/AdminLTE/pages/UI/general.html

Like bg-gray-active for color palette.
But It seems I can't use it and I don't know how to.

I included 
<link rel="stylesheet" href="{{ url }}/templates/influx-adminlte-3/dist/css/skins/_all-skins.min.css">
<link rel="stylesheet" href="{{ url }}/templates/influx-adminlte-3/dist/css/adminlte.min.css">

On my twig page but the class seems undefined
So my question is how can I use the color palette ?

**Comment by REJack** [comment]
Which version of AdminLTE you use?
The url that you sent is the old v2 demo not the v3 demo.

**Comment by Neurozone** [comment]
The version 3

**Comment by Neurozone** [comment]
Here is the good url
https://adminlte.io/themes/v3/pages/UI/general.html

**Comment by REJack** [comment]
In the new demo is no active background example, only default and disabled.
