### ISSUE TITLE
Fake spaces cause shifted sidebar in layout-navbar-fixed body

### ISSUE THREAD

**Issue by davidmtobias** [ColorlibHQ/AdminLTE#2598]
Hi,
I've been struggling several hours with an strange issue about "layout-navbar-fixed" body option. If I use the dist/css/admin.min (minified version), all work fine; but if I compile .scss files in my Rails project, the left sidebar doesn't get the margin top properly, so, it apears shifted up. 

I've notice that the problem is hidden behind a strange "fake" spaces in lines 36, 39, 94, 104, 305 315. In this lines, you can see ".sidebar {", but the space character beteween 'sidebar' and '{' is not an normal space character. Compiling the scss files with those "fake" spaces produces a broken out .css file, so, the "sidebar element" doesn't get his margin-top property.

Thank you very much for AdminLTE!
David

https://github.com/ColorlibHQ/AdminLTE/blob/0643791d8d645e0eee3c7b6d8f85df4bd831588b/build/scss/_layout.scss#L36

**Comment by REJack** [comment]
Thanks for reporting, I'll check and fix this soon.

**Comment by REJack** [comment]
I've replaced the fake spaces with real in all build files incl. build/scss/_layout.scss.
