### ISSUE TITLE
[BUG] footer add text-sm, the .content-wrapper style: min-height is wrong

### ISSUE THREAD

**Issue by cngarlan** [ColorlibHQ/AdminLTE#2599]
index2.html add text-sm at footer:
`<footer class="main-footer text-sm"> `
reload index2.html 
i find `<div class='content-wrapper' style='min-height=832.031px;'>`
it's ok when there are many page elements
but when there are few page elements, not exceed page height, the scroll bar is still displayed

AdminLTE Version: 3.0.2

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll look tomorrow over this.

**Comment by REJack** [comment]
I've added a fix for this, this comes not from a wrong calculation it comes from the margin-bottom with fixed footer. I've replaced it with padding-bottom and now it works correctly. This will published with the next release.
