### ISSUE TITLE
[BUG] No scrollbar on left menu on desktop/PC

### ISSUE THREAD

**Issue by sonyarianto** [ColorlibHQ/AdminLTE#2600]
**Describe the bug**
On index3.html on V3.0.3-pre still no scrollbar on left menu.

**To Reproduce**
1. Git clone latest
2. Go to index3.html on the browser
3. No scrollbar on left menu on desktop/PC

**Expected behavior**
Scrollbar exists similar on V2 or V1

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.3-pre
 - Operating System:  Ubuntu
 - Browser (Version): Chrome latest

**Comment by REJack** [comment]
The difference between Dashboard 3 and Dashboard 1/2 is that Dashboard 3 doesn't use the `layout-fixed` feature/class and this results to this behavior and displays the whole sidebar across the site. You see also that the whole page scrolls instead of the sidebar only.
