### ISSUE TITLE
Initial Build Fail

### ISSUE THREAD

**Issue by Mikey00409** [ColorlibHQ/AdminLTE#2601]
On a brand new project, on the initial startup it is unable to complie due to the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.2.10.0\build\Microsoft.Net.Compilers.props.	KSC X_0	C:\Users\MichaelVirnelson\Documents\TFS\X.0 Items\Bag of Tricks\KSC X_0\KSC X_0.csproj	283

**Comment by REJack** [comment]
AdminLTE doesn't provides nuget packages, for this you need to contact the nuget package creator.

**Comment by Mikey00409** [comment]
> AdminLTE doesn't provides nuget packages, for this you need to contact the nuget package creator.
The package of the .net.complier is installed through Nuget.  Its just not being recognized from the project for some reason.  I have seen stuff on forums stating its in the webconfigs that needs adjusting however i think its best to ask the source.
