### ISSUE TITLE
[BUG]3.x version not use sidebarExpandOnHover?

### ISSUE THREAD

**Issue by alienjun** [ColorlibHQ/AdminLTE#2603]
**Describe the bug**
3.xversion not use sidebarExpandOnHover?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.0]
 - Operating System:  [e.g. macOS Catalina]
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
With AdminLTE v3 the JS option for this is removed, you can add `.sidebar-no-expand ` to `aside.main-sidebar`.
