### ISSUE TITLE
[BUG] uploading of the plugin in wordpress failed

### ISSUE THREAD

**Issue by icsuk** [ColorlibHQ/AdminLTE#2604]
**uploading of the plugin in wordpress failed**

After downloading from [](https://adminlte.io/download/AdminLTE-master) and uploading the plugin in wordpress it failed to upload.

**To Reproduce**
1. Go to '[](https://adminlte.io/)'
2. Click on '[Download](https://adminlte.io/download/AdminLTE-master)'
3. Add it as new plugin to wordpress

**Expected behavior**
It will say uploading, installing, then it will say uploading failed.

**Video screencast**
[https://ufile.io/y2p07kah](URL)

**Environment (please complete the following information):**
 - AdminLTE Version: [v3.0.2]
 - Operating System:  [Chrome OS]
 - Browser (Version): [Chrome (Version 81.0.4044.72)]

**Comment by REJack** [comment]
This is not a Wordpres Plugin, it's only a HTML/CSS/JS Theme based on Bootstrap 4, but you can create a WP Theme on your own with this Theme.
