### ISSUE TITLE
bootstrap-switch v3.4.0 have a bug

### ISSUE THREAD

**Issue by snake19870227** [ColorlibHQ/AdminLTE#2605]
<img width="1191" alt="截屏2020-03-2222 45 12" src="https://user-images.githubusercontent.com/49919227/77252490-13691b80-6c8f-11ea-9195-a1e86122e5ad.png">
1 使用了一个未知的变量，2 一定进入不了 if 块，导致初始化的时候设置 state 属性不起作用

**Comment by snake19870227** [comment]
<img width="819" alt="截屏2020-03-2222 56 57" src="https://user-images.githubusercontent.com/49919227/77252691-858e3000-6c90-11ea-8e82-9e70802c2828.png">
上图为bootstrap-switch 3.3.4版本相同逻辑的代码，使用了options中的state。
https://github.com/Bttstrp/bootstrap-switch/releases bootstrap-switch并未正式发布3.4.0版本

**Comment by REJack** [comment]
Please write issues in english, otherwise I can't help.

**Comment by snake19870227** [comment]
<img width="1191" alt="截屏2020-03-2222 45 12" src="https://user-images.githubusercontent.com/49919227/77254067-b9218800-6c99-11ea-80ba-1cb3972d8144.png">
bootstrap-switch v3.4.0 have a bug.
1. An unknown variable is used
2. never enter the if block
Causes the initialized 'state' parameter to fail
<img width="819" alt="截屏2020-03-2222 56 57" src="https://user-images.githubusercontent.com/49919227/77254128-1c131f00-6c9a-11ea-8b15-8d0afa8151ec.png">
bootstrap-switch v3.3.4 Code with the same functionality

**Comment by snake19870227** [comment]
It is recommended to use bootstrap-switch v3.3.4

**Comment by snake19870227** [comment]
Sorry! I'm not good at English

**Comment by REJack** [comment]
I've downgraded the boostrap-switch to 3.3.4 only even the 3.3.5 has the same bug.
