### ISSUE TITLE
Sidebar menu treeview not working after redirection in Angular 8 [BUG]

### ISSUE THREAD

**Issue by RRGT19** [ColorlibHQ/AdminLTE#2607]
**Describe the bug**
Once you log in using the login page you will be redirected to the Dashboard. In this moment in the Dashboard the sidebar menu "treeview" option does not open. Also, a menu with a simple link (not treeview) does not work and sometimes the website is reload when you click on it.

**To Reproduce**
1. Go to login page
2. Continue to be redirected to the Dashboard
3. Try to click on a sidebar menu treeview

**Expected behavior**
A working sidebar menu treeview after a redirection from the log in page.

**Environment:**
 - AdminLTE Version: 3.0.2
 - Angular 8.3.21
 - Operating System:  macOS Catalina
 - Browser (Version): Chrome (Latest)

**Additional context**
The same problem has been reported for Angular 4 and AdminLTE v2 [here](https://github.com/ColorlibHQ/AdminLTE/issues/1570), but the solutions provided there does not work in Angular 8.

**angular.json**
```json
"styles": [
      "node_modules/admin-lte/plugins/fontawesome-free/css/all.min.css",
      "node_modules/admin-lte/dist/css/adminlte.min.css",
      "src/styles.scss"
],
"scripts": [
      "node_modules/admin-lte/plugins/jquery/jquery.min.js",
      "node_modules/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js",
      "node_modules/admin-lte/dist/js/adminlte.min.js"
]
```

**Comment by REJack** [comment]
You need to init the TreeView after login, with ` $('[data-widget="treeview"]').Treeview('init')`.

This issue https://github.com/ColorlibHQ/AdminLTE/issues/2550 can help you.

**Comment by RRGT19** [comment]
> You need to init the TreeView after login, with ` $('[data-widget="treeview"]').Treeview('init')`.
> 
> This issue #2550 can help you.

Hi, those solutions did not work for me.

I have tried:

**#1.**
```
import {Component, OnInit} from '@angular/core';
import * as $ from 'jquery';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {
  ngOnInit(): void {
    $('[data-widget="treeview"]').Treeview('init');
  }
}
```
This causes an error saying:

> ERROR TypeError: jquery__WEBPACK_IMPORTED_MODULE_2__(...).Treeview is not a function.

**#2.**
```
import {Component, OnInit} from '@angular/core';
import * as $ from 'jquery';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {
  ngOnInit(): void {
    $(document).ready (() => {
      const trees: any = $('[data-widget = "treeview"]');
      trees.Treeview();
    });
  }
}
```

This causes an error saying:

> jQuery.Deferred exception: trees.Treeview is not a function TypeError: trees.Treeview is not a function.

**#3.**
```
import {Component, OnInit} from '@angular/core';
import * as $ from 'jquery';
import * as AdminLte from 'admin-lte';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {
  ngOnInit(): void {
    $('[data-widget="treeview"]').each(function() {
      AdminLte.Treeview._jQueryInterface.call($(this), 'init');
    });
  }
}
```

With this the sidebar menu treeview is working and there is no errors in the console, but, the button `data-widget="pushmenu"` in the navbar to toggle the sidebar is not working. You click on it and nothing happens.

--
Any idea how to fix this issue to have all working properly?

**Comment by REJack** [comment]
```js
AdminLte.Layout._jQueryInterface.call($('body'));
AdminLte.PushMenu._jQueryInterface.call($('[data-widget="pushmenu"]'));
```

Try to add these lines in your ngOnInit() from Method 3, you need to init the PushMenu and Layout too to get the whole AdminLTE experience.

**Comment by RRGT19** [comment]
> ```js
> AdminLte.Layout._jQueryInterface.call($('body'));
> AdminLte.PushMenu._jQueryInterface.call($('[data-widget="pushmenu"]'));
> ```
> 
> Try to add these lines in your ngOnInit() from Method 3, you need to init the PushMenu and Layout too to get the whole AdminLTE experience.

For some reason it's still not working with those two lines added.

What I have:
```typescript
import {Component, OnInit} from '@angular/core';
import * as $ from 'jquery';
import * as AdminLte from 'admin-lte';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {

  constructor() {
  }

  ngOnInit(): void {
    $('[data-widget="treeview"]').each(function() {
      AdminLte.Treeview._jQueryInterface.call($(this), 'init');
      AdminLte.Layout._jQueryInterface.call($('body'));
      AdminLte.PushMenu._jQueryInterface.call($('[data-widget="pushmenu"]'));
    });
  }

}
```
But, I have it working now with a few new lines of code. I have used a EventEmitter from the HeaderComponent that emits when you click on the `pushmenu` button. I receives this notification on my parent which is the layout (I have divided everything in components) and here, in the layout, the method's logic is to add and remove the class `sidebar-open` and `sidebar-collapse` accordingly.

This logic and your recommendation make the template works as expected.

**Comment by gitcoderis** [comment]
Having the same issue.. None of the above answers solve this - 3rd level menu overlaps other menus (like in #2550, for example).
It works okay on initial page load, but after reloading page, menu behavior changes and it start to be buggy (overlapping other menus, expanding too quickly).
Tried various ways to init 'treeview' like suggested above, but nothing helps.
Is there a way how to solve this for angular?

**Comment by swtw122** [comment]
Hey guys, I had the same issue and fixed it with:

in the imports section add...
`declare var $: any;`

in ngOnInit section...
`$('[data-widget="treeview"]').Treeview('init');`

**Comment by kinsmanma** [comment]
I figured I should share this, as it took me ages to figure it out as well.

So I had the issue when I init my treeview, pushmenu stopped functioning (no treeview and pushmenu worked fine).

few bits of info: angular 9.1.12 and AdminLTE 3, All pieces (header, content, aside, footer) split into components.

so first to to get treeview working:

`import * as $ from 'jquery';
import * as AdminLte from 'admin-lte';`

at the top of the typescript (mine is in a aside component).

and in your class:
`  ngAfterViewInit(): void {
    $('[data-widget="treeview"]').each(function() {
      AdminLte.Treeview._jQueryInterface.call($(this), 'init');
    });
  }`

don't forget to implement afterviewinit.

next is giving your body an id:
`<body id="portalBody" class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">`

so you can use jquery on it.

and finally for your toggle link  in the html (mine is in a header component):
`<a role="button" class="nav-link" (click)="toggle()" href="javascript:void(0);" ><em class="fa fa-bars"></em></a>`

in the line where it has data-widget=push menu, replace it for the line above and in the type script add the code below:
`import * as $ from 'jquery';`

and in the class, add the function:

`  toggle(): void {
    const portalBody = $('#portalBody');
    if ( portalBody.hasClass( 'sidebar-collapse' )) {
      portalBody.removeClass('sidebar-collapse');
      portalBody.addClass('sidebar-open');
    } else {
      portalBody.addClass('sidebar-collapse');
    }
  }`

Hopefully this helps someone as much as everyone here helped me.

**Comment by wwongchaipanid** [comment]
import {Component, OnInit} from '@angular/core';

**//import * as $ from 'jquery';  
declare var $: any;**

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {
  ngOnInit(): void {
    $('[data-widget="treeview"]').Treeview('init');
  }
}

**Comment by tuhincse24** [comment]
In my case for angular 13, I have added the below codebase on my **main** component instead of the **sidebar** component. Now both pushmenu and sidebar menu working perfectly without refresh.
`
    $(function() {
      const trees: any = $('[data-widget = "treeview"]');
      trees.Treeview('init');
    });`

**Comment by prajapatipravin** [comment]
> Hey guys, I had the same issue and fixed it with:
> 
> in the imports section add... `declare var $: any;`
> 
> in ngOnInit section... `$('[data-widget="treeview"]').Treeview('init');`
> 
> inside the sidebar component

it works.

thank YOU!!!!!!

**Comment by Jaime1706** [comment]
Hola, para los que al hacer clic en el sidebar se les actualiza toda la pagina, les dejo la siguiente solución:
1- en el index.html cambiar el <script src="./assets/dist/js/adminlte.min.js"></script> por <script src="./assets/dist/js/adminlte.js"></script> 

2- eliminar la ultima línea del documento adminlte.js la cual es  =>   //# sourceMappingURL=adminlte.js.map

3- buscar en el archivo adminlte.js que está en assets/dist/js la fracción de código 
if (isOpen) {
        this.collapse($__default["default"](treeviewMenu), parentLi);
      } else {
        this.expand($__default["default"](treeviewMenu), parentLi);
      }

4- remplazarlo por el siguiente código
      var getUltimoClic = Number(localStorage.getItem('ultimoClic'));
      var horaclic = new Date();
      var clic = horaclic.getTime();
      if (clic - getUltimoClic > 1) {
        if (isOpen) {
          this.collapse($__default["default"](treeviewMenu), parentLi);
        } else {
          this.expand($__default["default"](treeviewMenu), parentLi);
        }
        var ultimoClic = new Date();
        localStorage.setItem('ultimoClic', ultimoClic.getTime().toString());
      }

5- en el componente del sidebar  el ngOnInit queda de la siguiente manera
ngOnInit(){
    $('[data-widget="treeview"]').Treeview('init');
    var ultimoClic = new Date();
    localStorage.setItem('ultimoClic', ultimoClic.getTime().toString());
  }

y eso seria todo, esta un poco enredado pero a mi me funciono y espero que a alguno de los que tienen este detalle pueda ayudarlos igual

**Comment by Kokleng-Dev** [comment]
Hello sir [REJack], I have issue with adminlte is not collapse menu after refreshing. I use vuejs 3 cli and I follow your step "need to init the TreeView after login, with $('[data-widget="treeview"]').Treeview('init'). " then it work both drop down menu list and collapse menu but if i refresh page it work only drop down menu but it won't collapse. please help me. thanks in advacnce.

**Comment by Alexiserist** [comment]
> Hello sir [REJack], I have issue with adminlte is not collapse menu after refreshing. I use vuejs 3 cli and I follow your step "need to init the TreeView after login, with $('[data-widget="treeview"]').Treeview('init'). " then it work both drop down menu list and collapse menu but if i refresh page it work only drop down menu but it won't collapse. please help me. thanks in advacnce.

Hey i have the same issue but i try to downgrade my admin-lte version from 3.2.0 to version admin-lte 3.0.5  so it's work fine for me.

**Comment by RGVision** [comment]
> ```
> import {Component, OnInit} from '@angular/core';
> 
> //import * as $ from 'jquery';       //DELETE THIS LINE
> declare var $: any;                  //INSERT THIS LINE
> 
> @Component({
>   selector: 'app-sidebar',
>   templateUrl: './sidebar.component.html',
>   styleUrls: ['./sidebar.component.scss']
> })
> export class SidebarComponent implements OnInit {
>   ngOnInit(): void {
>     $('[data-widget="treeview"]').Treeview('init');
>   }
> }
> ```

It Works Thankk You!!!!!
