### ISSUE TITLE
[BUG] Dashboard Fixed header and footer responsive not working. 

### ISSUE THREAD

**Issue by benedictchow00** [ColorlibHQ/AdminLTE#2610]
I'm using AdminLTE Version : v3.0.1
Browser: Google Chrome 
Operating System : Window 10 

what is want to do is fixed the header & footer position for my responsive page. I've try changing my html, body class to 
`<body data-gr-c-s-loaded="true" style="height: auto;" class="sidebar-mini layout-footer-fixed layout-navbar-fixed sidebar-open">` 
and below is the attachment and this is what i get 
![Capture](https://user-images.githubusercontent.com/30893861/77321212-ce0b2380-6d4c-11ea-942f-2f4c538c91ee.PNG)
do you guys know how to fix this problem ?

**Comment by REJack** [comment]
I need more informations, which AdminLTE Version, which Browser, which Operating System and maybe the steps to reproduce too.

Next time please use the Bug Report Issue Template and don't clear it out.

**Comment by benedictchow00** [comment]
> 
> 
> I need more informations, which AdminLTE Version, which Browser, which Operating System and maybe the steps to reproduce too.
> 
> Next time please use the Bug Report Issue Template and don't clear it out.

**Comment by REJack** [comment]
AdminLTE v3.1 isn't released, which version exact you use 3.0.0, 3.0.1 or 3.0.2?

**Comment by benedictchow00** [comment]
I mean AdminLTE v3.0.1*

**Comment by danny007in** [comment]
> 
> 
> I mean AdminLTE v3.0.1*

use 3.0.2 version of adminlte

**Comment by REJack** [comment]
Please update AdminLTE to v3.0.3 (latest version) and test it again.
