### ISSUE TITLE
Show AdminLTE version number on page

### ISSUE THREAD

**Issue by brianread108** [ColorlibHQ/AdminLTE#2611]
Is there anyway to display the AdminLTE version number automatically (i.e. extracted from the package)?

**Comment by REJack** [comment]
Here is a simple Javascript, you only need to place a empty span `.adminlte-version` (e.g. `<span class="adminlte-version"></span>`).

You can also change version display `AdminLTE v3.0.2` to `3.0.2` for this you need to change the `const versionType` to anything except `full`. 

**Important:** this doesn't work with file:// calls.

```js
$(document).ready(function() {
  const classSelector = 'adminlte-version';
  const versionType = 'full'; // 'full' OR true;
  for (var i = 0, max = document.styleSheets.length; i < max; i++) {
    if ((document.styleSheets[i].href).includes("adminlte")) {
      $.ajax({
        url: document.styleSheets[i].href,
        dataType: "text",
        success: function(cssText) {
          const searchReg = /AdminLTE v([0-9.]{0,})/;
          const result = cssText.match(searchReg);
  
          $(`.${classSelector}`).text(result[versionType == 'full' ? 0 : 1]);
        }
      });
    }
  }
});
```

**Comment by brianread108** [comment]
That is great-  many thanks.

**Comment by brianread108** [comment]
Re-opening this:
Since 3.2.0 I am getting this failure:

login:420 Uncaught TypeError: Cannot read properties of null (reading '0')
    at Object.success (login:420)
    at c (VM609 jquery.min.js:2)
    at Object.fireWith [as resolveWith] (VM609 jquery.min.js:2)
    at l (VM609 jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (VM609 jquery.min.js:2)

Line 420 is your line "$(`.${classSelector}`).text(result[versionType == 'full' ? 0 : 1]);"

I am still getting the correct result though!!

**Comment by brianread108** [comment]
Looks like the error message was there for 3.1.0 as well.

I don't appear to be able actually re-open this issue.

**Comment by brianread108** [comment]
ok, after quite a bit of head scratching the difference seems to be that there are more than one css file whose name includes "adminlte", however only one of them has the AdminLTE v<whatever> string. The one that doesn't results in a null return from the match command.
So, this seems to work:

		$(document).ready(function() {
			const classSelector = 'adminlte-version';
			const versionType = 'full'; // 'full' OR true;
			for (var i = 0, max = document.styleSheets.length; i < max; i++) {
				if ((document.styleSheets[i].href).includes("adminlte")) {
				  $.ajax({
					url: document.styleSheets[i].href,
					dataType: "text",
					success: function(cssText) {
					  const searchReg = /AdminLTE v([0-9.]{0,})/;
					  const result = cssText.match(searchReg);  
					  if (result != null){ $(`.${classSelector}`).text(result[versionType == 'full' ? 0 : 1]);}
					}
					});
				}
			}

**Comment by brianread108** [comment]
Latest is this, otherwise fails if you have inline CSS:

`		$(document).ready(function() {
			const classSelector = 'adminlte-version';
			const versionType = 'full'; // 'full' OR true;
			for (var i = 0, max = document.styleSheets.length; i < max; i++) {
				//alert(document.styleSheets[i]);
				if (document.styleSheets[i].href == null) continue;
				if ((document.styleSheets[i].href).includes("adminlte")) {
				  $.ajax({
					url: document.styleSheets[i].href,
					dataType: "text",
					success: function(cssText) {
					  const searchReg = /AdminLTE v([0-9.]{0,})/;
					  const result = cssText.match(searchReg);  
					  if (result != null){ $(`.${classSelector}`).text(result[versionType == 'full' ? 0 : 1]);}
					}
					});
				}
			}
 `
