### ISSUE TITLE
Easy question about Calendar

### ISSUE THREAD

**Issue by pascalf22** [ColorlibHQ/AdminLTE#2614]
Hello!

Thanks alot for Admin LTE.. i really love it ! wonderful job !!

I have the version 2.4, in the calendar, can i remove the month and day view ? I only need the week view!

I tried to remove month and day from the right button:

```
$('#calendar').fullCalendar({
      header    : {
        left  : 'prev,next today',
        center: 'title',
        right : 'agendaWeek'
      },
```

But it still show the default view ( month)
Is it possible ?

Thanks a lot !
Have a great day ! 
Pascal

**Comment by REJack** [comment]
For questions about AdminLTE Plugins, you should look over the desired plugin docs (e.g. for Fullcalender on fullcalendar.io) all used/added plugins are listed in [v3 Docs -> Dependencies](https://adminlte.io/docs/3.0/dependencies.html). 

You want to use the timeGridWeek view, here is the link to FullCalendar's timegrid docs https://fullcalendar.io/docs/timegrid-view.

**Comment by pascalf22** [comment]
Hello !! Ok perfect !! Thanks a lot!

Pascal
