### ISSUE TITLE
[BUG] Sidebar bottom nav item hidden in mobile safari 

### ISSUE THREAD

**Issue by sspurgeon** [ColorlibHQ/AdminLTE#2615]
Hi guys,

Just found this issue on my test iPhone: When a main page's content fits on screen (ie no scrolling required) there's nothing that will make the bottom toolbar of the mobile safari app disappear (this is usually achieved by scrolling down). 

This means that safari's bottom toolbar is always in place and never hides. Currently, this means that the last nav item on the sidebar will always be concealed by the toolbar.

The logic of AdminLTE 3 scrolling on the iPhone I tested with seems to be: 

- Scrolling the sidebar down moves through the nav items
- When you reach the bottom, if you keep scrolling, the sidebar stops scrolling and scrolling switches to the main page.
- Scrolling the main page pushes the mobile safari bottom toolbar down, revealing the last nav item in the sidebar

Fine when there's enough content on the main page to require scrolling but when there's not, the bottom toolbar remains, causing the problem.

A short screen capture of the issue is here: [https://thetechcompany.co.uk/IMG_1068.MOV](https://thetechcompany.co.uk/IMG_1068.MOV)

Device: iPhone 7
OS: 13.3.1
Browser: Mobile Safari
AdminLTE ver: 3.0.2

Cheers

Sam

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll test some fixes/workarounds later to get avoid of this behavior.

I've done some small tests on my iPhone and it's only appears if the sidebar is in fixed mode (`.layout-fixed` on body).
 
Please next time use the Issue Template for v3 Bug Reports 😄.

**Comment by sspurgeon** [comment]
Ok will do! Thanks for looking into it.

**Comment by REJack** [comment]
I've found the bug and fixed it in the master branch.

**Comment by sspurgeon** [comment]
Thanks so much! I'll update now

**Comment by REJack** [comment]
I'll release soon the next release (v3.0.3) with this and other fixes 😄.
