### ISSUE TITLE
slow load of side bar

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#2616]
My best Suggestion is make - two style sheet and script.js for one for ui and another for plugins.

then ui will load faster after that plugins will load

**Comment by REJack** [comment]
The AdminLTE css have only plugin overrides or extra classes but not whole plugin css codes and the AdminLTE's js files don’t contain any third-party plugin, all plugin css/js files are not bundled with AdminLTE you need to load all by your self like the demo show. Also based on the build system of your app you can bundle your needed plugin files and separately AdminLTE with it dependencies.
