### ISSUE TITLE
How to Convert the Following Script to Text

### ISSUE THREAD

**Issue by robwopster61** [ColorlibHQ/AdminLTE#2618]
I am a novice and need the help of any willing.  Please advise me of the most effective methods to convert the following script into plain English?

```
<smil>
<head>
<layout>
<root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="IMG_1926.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1930.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1928.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1927.png" region="Image"/>
</par>
</body>
</smil>
```

**Comment by REJack** [comment]
I don’t know anything about this code, this is not from AdminLTE. Please ask question like this on stackoverflow.com.

**Comment by googplay** [comment]
> I am a novice and need the help of any willing. Please advise me of the most effective methods to convert the following script into plain English?
> 
> ```
> <smil>
> <head>
> <layout>
> <root-layout/>
> <region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
> <region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
> </layout>
> </head>
> <body>
> <par dur="10s">
> <img src="IMG_1926.png" region="Image"/>
> </par>
> <par dur="10s">
> <img src="IMG_1930.png" region="Image"/>
> </par>
> <par dur="10s">
> <img src="IMG_1928.png" region="Image"/>
> </par>
> <par dur="10s">
> <img src="IMG_1927.png" region="Image"/>
> </par>
> </body>
> </smil>
> ```

**Comment by Austinet** [comment]
<smil>
<head>
<layout>
 <root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="D1A95D8C-.jpg" region="Image"/>
</par>
</body>
</smil>

**Comment by justEuphoriaalways** [comment]
<smil>
<head>
<layout>
 <root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="ms-SVDsKo.jpg" region="Image"/>
</par>
</body>
</smil>

What is this ??

**Comment by donyanbzz1** [comment]
<smil>
<head>
<layout>
 <root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="737319661.jpg" region="Image"/>
</par>
</body>
</smil>

**Comment by donyanbzz1** [comment]
<smil>
<head>
<layout>
 <root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="737319661.jpg" region="Image"/>
</par>
</body>
</smil>

**Comment by Hipatia4331** [comment]
Hello, I have one frind that has been sending me that text 14 times, this IS a common error of MMS mostly in Apple devices. This text IS in SMIL format which IS a tope of code used to structure social media.
If you are wondering It doesen't mean anything so if someone sends you this just tell them to reset their device or anything to eliminate the error.

In muy situation this happens with a friend that messages me through MMS with an Apple watch, any advice?

**Comment by Jazamsv** [comment]
> I am a novice and need the help of any willing. Please advise me of the most effective methods to convert the following script into plain English?
> 
> ```
> <smil>
> <head>
> <layout>
> <root-layout/>
> <region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
> <region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
> </layout>
> </head>
> <body>
> <par dur="10s">
> <img src="IMG_1926.png" region="Image"/>
> </par>
> <par dur="10s">
> <img src="IMG_1930.png" region="Image"/>
> </par>
> <par dur="10s">
> <img src="IMG_1928.png" region="Image"/>
> </par>
> <par dur="10s">
> <img src="IMG_1927.png" region="Image"/>
> </par>
> </body>
> </smil>
> ```

<smil>
<head>
<layout>
<root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="IMG_1926.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1930.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1928.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1927.png" region="Image"/>
</par>
</body>
</smil>

**Comment by Jazamsv** [comment]
<smil>
<head>
<layout>
<root-layout/>
<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>
<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>
</layout>
</head>
<body>
<par dur="10s">
<img src="IMG_1926.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1930.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1928.png" region="Image"/>
</par>
<par dur="10s">
<img src="IMG_1927.png" region="Image"/>
</par>
</body>
</smil>

Convert this to text format
