### ISSUE TITLE
How to use markdown editor insert code block and make it highlight? 

### ISSUE THREAD

**Issue by hectorwill** [ColorlibHQ/AdminLTE#2620]
How to use markdown editor insert code block and make it highlight? or use 3rd-party libs like highlight.js

**Comment by REJack** [comment]
Ask plugin related questions on the plugin repo itself, we only can help you with the AdminLTE's own JS plugins.

**Comment by hectorwill** [comment]
> Ask plugin related questions on the plugin repo itself, we only can help you with the AdminLTE's own JS plugins.

ok,thank you
