### ISSUE TITLE
[BUG] Collapse is not working when when i maximize

### ISSUE THREAD

**Issue by EliseuPorto** [ColorlibHQ/AdminLTE#2626]
**Describe the bug**
The menu on the left side is not appearing as before when maximizing the screen.

**To Reproduce**
Reduce the size of the browser until the left side menu disappears, then maximize it. The left side menu will not be as before

**Screenshots**
![Admin LTE](https://user-images.githubusercontent.com/62800448/77825979-673e8f00-70eb-11ea-8c2e-55b0090163c3.gif)

**Environment (please complete the following information):**
 - AdminLTE Version: AdminLTE v3.x
 - Operating System:  Windows 10
 - Browser:  Chrome (Latest), Microsoft Edge (Latest)

**Comment by REJack** [comment]
I've added a fix for this in master repo, I look over all bug reports and may I push today a new version again with these fixes.
