### ISSUE TITLE
[BUG] Accent not working on Datatable pagination

### ISSUE THREAD

**Issue by developerGM** [ColorlibHQ/AdminLTE#2628]
If I apply `accent-info` on body, the pagination layout in DataTable has background `info` and text-color `info`.
![image](https://user-images.githubusercontent.com/9252653/78149151-f0c8c680-7435-11ea-881d-066008dafe7b.png)

I am using "datatables-bs4/css/dataTables.bootstrap4.min.css" as CSS for datatable.
`"admin-lte": "^3.0.3"`

**Comment by REJack** [comment]
I've added a fix for this in master repo, I look over all bug reports and may I push today a new version again with these fixes.

**Comment by developerGM** [comment]
WOW!

**Comment by developerGM** [comment]
@REJack 
how can I test your fix ?
if I run "npm install" to download your 3.0.3 version, not solve the problem.

**Comment by REJack** [comment]
This fix isn't in v3.0.3, it will come with v3.0.4.

**Comment by developerGM** [comment]
Oh ok, now It's clear. 
I saw a commit 2hours ago and I got confused.
I will wait your commit.
Really thanks for your work.
