### ISSUE TITLE
[BUG] SweetAlert2 integration, CSS problem

### ISSUE THREAD

**Issue by developerGM** [ColorlibHQ/AdminLTE#2629]
I am usgin sweetalert2
`npm install --save sweetalert2 @sweetalert2/ngx-sweetalert2`

and in my css
`@import "../node_modules/admin-lte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css";`

the problem is I found in <head> the JS (<script charset="utf-8" src="sweetalert2.js"></script>) and CSS of sweetalert2 that override mine.

This integration to use sweetalert2 is wrong?

**Comment by REJack** [comment]
Do you not get the right theme or what’s the exact problem? AdminLTE has only color overrides for Sweetalert2, in order to get the same colors import the Sweetalert2 scss before AdminLTE.
