### ISSUE TITLE
AdminLTE 2.4 and Vue.js

### ISSUE THREAD

**Issue by SilvaFilipe** [ColorlibHQ/AdminLTE#2633]
Is it possible to use all the components from the 2.4 version in a Vue.js project? If so, can you give me some guidance on how to do it or at least some documentation that can make this task easier? Thank you!

**Comment by REJack** [comment]
I don’t know, but you can look over the closed issue or search in GitHub itself there are some Angular adaptations may there is also one for VueJS.
