### ISSUE TITLE
Different PushMenu plugin button icon

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2634]
How to use different icon when the sidebar is expand or collapsed?

**Comment by REJack** [comment]
You can only trigger this with a custom css

**Comment by GerryGe** [comment]
> You can only trigger this with a custom css

@REJack  Thanks

I add the css in the index.html  as below:
、、、css
<style>
    a[data-widget="pushmenu"]>i:before {
      content: "\f036"; }

    .sidebar-collapse a[data-widget="pushmenu"]>i:before {
      content: "\f038"; }
  </style>
And it works like:
![pushmenu](https://user-images.githubusercontent.com/6952917/78683777-4a436080-7922-11ea-81e4-d84215138452.gif)

Could you tell me whether this is correct? 
Or can you give me a demo?

Kind regards.

**Comment by GerryGe** [comment]
![pushmenu](https://user-images.githubusercontent.com/6952917/78684959-b4a8d080-7923-11ea-803e-509be01120d6.gif)

**Comment by REJack** [comment]
Yep that's correct 😄

**Comment by GerryGe** [comment]
😄

**Comment by REJack** [comment]
There is at the moment no way to hide this sub-menu icon's on collapsed sidebar, could you create a extra issue for this and I will add this to v3.1.

**Comment by GerryGe** [comment]
#2644
