### ISSUE TITLE
Integrating AdminLTE with MVC 5 Application

### ISSUE THREAD

**Issue by andrmc01** [ColorlibHQ/AdminLTE#2635]
I have a very basic MVC 5 Application which I am attempting to add AdminLTE to. I downloaded the AdminLTE Nuget package and added the code from the startup.html page to my MVC application's _Layout.cshtml page. I updated all the CSS and JS links to point to the right directory for my application.

Here is the code in the _Layout.cshtml file.

[Layout cshtml.txt](https://github.com/ColorlibHQ/AdminLTE/files/4434934/Layout.cshtml.txt)

This is what the page ends up looking like: 
![starter page 2](https://user-images.githubusercontent.com/5922442/78510392-c55e1880-7762-11ea-8147-491105d9131b.png)

It appears that not all the CSS and/or JS files are being properly loaded. What am I missing?

**Comment by iyilm4z** [comment]
@andrmc01 Hi! [Here](https://github.com/iyilm4z/admin-lte-dotnet) is my repo shows how to use admin-lte with various dotnet technologies. Please give a star if it helps. Thanks.

**Comment by andrmc01** [comment]
@iyilm4z Hello there. I've used your repo but I'm still having issues getting everything to style properly. Upon investigation I found that it appears that this project is using SASS. This is the first time I've ever used SASS so forgive me if this is a stupid question: Do I need to convert the provided SASS files into actual CSS files in order for the styling to appear?

Thanks!

**Comment by andrmc01** [comment]
So I did a bit of digging and it looks like my project is referencing the SASS files. Well all but one. In the image below there are 2 Chrome Dev tool windows open. The one on the right is from the starter.html file from the repo. The one on the left is my project. For some reason my project is missing references to _layout.scss. How do I go about incorporating this css file into my project?

![Dev Tools](https://user-images.githubusercontent.com/5922442/79285548-e671e800-7e8b-11ea-8376-c4dc236aa307.png)

**Comment by andrmc01** [comment]
I figured it out. Apparently it was a CSS issue. I the CSS version I had in my project must have been old or something. I copied the AdminLTS.css file from the project with the Starter.html file into mine, overriding my current one, and it started working!
