### ISSUE TITLE
[BUG] (maybe?) Trying the npm install method... Next step unclear?

### ISSUE THREAD

**Issue by kylebakerio** [ColorlibHQ/AdminLTE#2636]
**Describe the bug**
I attempt the npm install method. I get all the packages, but no scaffold of any kind. Basically none of the folders I'd get if I did git clone of the repository. No idea what I'm supposed to do, just going to delete and git clone instead.

Maybe I'm just rusty, but... what am I missing?

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.4
 - Operating System: Debian 10
 - Browser (Version): N/A
 - Node/NPM: 10.19.0 / 6.14.4

**Comment by REJack** [comment]
Which folders you mean? If you run npm install admin-lte all files are located in node_modules/admin-lte otherwise you should get a error from npm.

**Comment by kylebakerio** [comment]
Ah, this was unclear. I'm used to node_modules being in the root folder of the project, instead of the project being inside a folder inside of node_modules.

Perhaps it's my own ignorance, but I couldn't guess that, and just didn't understand why I had all the dependencies but the project itself wasn't here.

**Comment by kingIZZZY** [comment]
I was also confused - it doesn't seem like the standard/natural way how to install something via npm, you don't usually need to dig into node_modules folders to run build/compile/run commands and edit/customize your code project that way...

Perhaps the cloning git and _then_ running `npm install` & further npm compile/build commands is the more "correct" way to use this project?
