### ISSUE TITLE
[BUG] NPM Install error

### ISSUE THREAD

**Issue by mrzainulabideen** [ColorlibHQ/AdminLTE#2638]
**Describe the bug**
When i install with npm install admin-lte@3.0 --save

**To Reproduce**
1. Go to 'terminal'
2. Install using NPM with 'npm install admin-lte@3.0 --save'
3. See error

**Expected behavior**
admin-lte@3.0 should get installed

**Terminal Output**
user@computer:~/Documents/projects/project$ npm install admin-lte@^3.0.4 --save

> admin-lte@3.0.4 install /home/user/Documents/projects/project/node_modules/admin-lte
> npm run plugins

> admin-lte@3.0.4 plugins /home/user/Documents/projects/project/node_modules/admin-lte
> node build/npm/Publish.js -v

/home/user/Documents/projects/project/node_modules/admin-lte/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/Documents/projects/project/node_modules/admin-lte/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-lte@3.0.4 plugins: `node build/npm/Publish.js -v`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the admin-lte@3.0.4 plugins script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-04-07T17_11_29_025Z-debug.log
npm WARN notsup Unsupported engine for fs-extra@9.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@9.0.0
npm WARN notsup Unsupported engine for universalify@1.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: universalify@1.0.0
npm WARN notsup Unsupported engine for p-map@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: p-map@4.0.0
npm WARN notsup Unsupported engine for semver@7.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.2.1
npm WARN notsup Unsupported engine for pacote@11.1.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pacote@11.1.4
npm WARN notsup Unsupported engine for npm-packlist@2.1.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npm-packlist@2.1.1
npm WARN notsup Unsupported engine for cacache@15.0.0: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cacache@15.0.0
npm WARN notsup Unsupported engine for npm-package-arg@8.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npm-package-arg@8.0.1
npm WARN notsup Unsupported engine for mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: mkdirp@1.0.4
npm WARN notsup Unsupported engine for npm-registry-fetch@8.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npm-registry-fetch@8.0.0
npm WARN notsup Unsupported engine for semver@7.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.2.1
npm WARN notsup Unsupported engine for tar@6.0.1: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: tar@6.0.1
npm WARN notsup Unsupported engine for @npmcli/installed-package-contents@1.0.5: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @npmcli/installed-package-contents@1.0.5
npm WARN notsup Unsupported engine for mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: mkdirp@1.0.4
npm WARN notsup Unsupported engine for semver@7.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.2.1
npm WARN notsup Unsupported engine for npm-install-checks@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npm-install-checks@4.0.0
npm WARN notsup Unsupported engine for semver@7.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.2.1
npm WARN notsup Unsupported engine for semver@7.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.2.1
npm WARN notsup Unsupported engine for make-fetch-happen@8.0.4: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: make-fetch-happen@8.0.4
npm WARN notsup Unsupported engine for cacache@15.0.0: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cacache@15.0.0
npm WARN notsup Unsupported engine for mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: mkdirp@1.0.4
npm WARN notsup Unsupported engine for tar@6.0.1: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: tar@6.0.1
npm WARN react-icheck@0.3.8 requires a peer of react@^15 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap-switch@3.3.4 requires a peer of bootstrap@^3.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN tempusdominus-bootstrap-4@5.1.2 requires a peer of tempusdominus-core@5.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-lte@3.0.4 install: `npm run plugins`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the admin-lte@3.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-04-07T17_11_39_080Z-debug.log

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0
 - Operating System:  Ubuntu 18.04
 - Browser (Version): Chrome (Latest) but didn't got there.

**Comment by REJack** [comment]
Node 8 isn't supported anymore.

**Comment by mrzainulabideen** [comment]
Node upgraded to 13 and it worked!
