### ISSUE TITLE
[BUG] Accent not working on anchors with btn class

### ISSUE THREAD

**Issue by dfabarbosa** [ColorlibHQ/AdminLTE#2639]
If I apply an accent on the body it will apply that accent on anchors with 'btn' class.

![image](https://user-images.githubusercontent.com/1285323/78775214-c0c97800-798d-11ea-9d4a-92384b6ce996.png)

Maybe you can add the 'btn' class to this exception like this:

`.accent-info a:not(.dropdown-item):not(.btn-app):not(.nav-link):not(.brand-link):not(.page-link):not(.btn)`

Or you can add a new class called 'no-accent' for example, to avoid this kind of behaviour in the future, like this:

`.accent-info a:not(.dropdown-item):not(.btn-app):not(.nav-link):not(.brand-link):not(.page-link):not(.no-accent)` 
and then we can use it this way:
`<a href="#" class="btn btn-sm btn-info no-accent">text</a>`

 - AdminLTE Version: v3.0.3

**Comment by REJack** [comment]
I'll look over this and add a fix for it.

**Comment by danny007in** [comment]
> 
> 
> I'll look over this and add a fix for it.

make custom btn class or else every btn-* will get same

**Comment by REJack** [comment]
I've added a fix for this in the master branch 😄
