### ISSUE TITLE
[BUG] Bootstrap 3.x.x dependency

### ISSUE THREAD

**Issue by gongAll** [ColorlibHQ/AdminLTE#2640]
**Describe the bug**
When I install AdminLTE 3.0.4 through npm, I get a warning I believe should not exist. Given that the AdminLTE 3.x.x should be bootstrap 4.x.x only.
```
warning "admin-lte > bootstrap-switch@3.3.4" has incorrect peer dependency "bootstrap@^3.1.1".
```
Apart from this one, I also get the following:
```
warning "admin-lte > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "moment-timezone@^0.5.11".
warning "admin-lte > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "tempusdominus-core@5.0.3".
```

Wouldn''t it make sense to already integrate those with the main package, given that it is the common solution you've used before?

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.4
 - Operating System:  ManjaroLinux 19.0.2

**Comment by REJack** [comment]
These errors can literally be ignored, we would only need this if want to recompile bootstrap-switch or tempusdominus-bootstrap, but we use only the dist files from this packages. Also I didn't found a good alternative to bootstrap-switch.

**Comment by gongAll** [comment]
I don't think you understand: bootstrap-switch 3.4.0 is for bootstrap 4.x.x while bootstrap-switch 3.3.4 is still for bootstrap 3.x.x, from what I understood

**Comment by DerGonzi** [comment]
lol

**Comment by REJack** [comment]
bootstrap-switch 3.4.0 is not a offical release and it doesn't work properly, look at this https://github.com/ColorlibHQ/AdminLTE/issues/2605.

**Comment by gongAll** [comment]
sorry I missed that previous issue. Closing.
