### ISSUE TITLE
Can't Extract Zip File or Composer Download Releases

### ISSUE THREAD

**Issue by hafijul233** [ColorlibHQ/AdminLTE#2641]
I tried to download different versions of project release of adminlte3.0.4 as zip and tar.gz compression files but there re extraction issue on jquery-ui.css file on version 3.0.4 and raphheld error on  2.4.18 . Also when using composer i got error **Invalid Zip file** 

>composer require "almasaeed2010/adminlte=~3.0"
Package operations: 1 install, 0 updates, 0 removals
  - Installing almasaeed2010/adminlte (v3.0.4): Downloading (100%)
    Invalid zip file, retrying...

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.4]
 - Operating System:  Windows 10
 - Browser (Version): Firefox 75.0 64 bit
 - Tools(IDE) phpStorm 2019.3

**Additional context**

**Comment by REJack** [comment]
I can't replicate this, try to run `composer clear-cache` and install/require it again.

**Comment by hafijul233** [comment]
I tried to clean composer cache .after that still having this problem.. This are the error message screenshot
[https://ibb.co/6P94fhV](url)
[https://ibb.co/dQfr5yk](url)

**Comment by hafijul233** [comment]
thank you. it is my region ISP problem.
