### ISSUE TITLE
[BUG] Label of custom checkbox styled wrong

### ISSUE THREAD

**Issue by dlnsk** [ColorlibHQ/AdminLTE#2642]
Checkbox with 'custom-control-label' should not styled bold.
https://getbootstrap.com/docs/4.4/components/forms/#checkboxes-and-radios-1

**Comment by REJack** [comment]
That's not a Bug, that's the style of AdminLTE we don't need to follow exaclty the Bootstrap 4 style that's why we are a theme/template based on BS4.
