### ISSUE TITLE
Hide the sub-menu icon when sidebar collapse

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2644]
When sidebar collapse, how to hide the sub-menu icon?

![image](https://user-images.githubusercontent.com/6952917/78955191-10847c80-7b11-11ea-9d5f-7b15603ec746.png)

**Comment by REJack** [comment]
This feature is already builtin, just add `.nav-collapse-hide-child` to `.nav-sidebar`. 🤦‍♂️ I've added a option to the demo.js to test it on our demos.
