### ISSUE TITLE
[BUG]Active Class for Submenu is not effective when using JQuery to Change

### ISSUE THREAD

**Issue by Jithin-C-V** [ColorlibHQ/AdminLTE#2645]
**Describe the bug**
My idea is to have a single page and with NavBar,SideBars & empty body.

Then the body content will be updated through AJAX Calls based on the selected side bar/nav bar option.

I just taken the blank page tried to do some jQuery steps for auto changing the active class in Side Bar menu. It is working for main menu but not effective for SubMenus.

**To Reproduce**
1. Add two different custom class names. 1. For Main Menu & 2.For SubMenus.
```
        <li class="nav-item has-treeview idc_left_navbar"> #----> Custom Class "idc_left_navbar" added for main menu item.
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard_New
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item idc_left_navbar_sub"> #--> Custom class "idc_left_navbar_sub" added for SubMenu Item.
                <a href="#" class="nav-link">
                  <p>Active Page</p>
                </a>
              </li>
              <li class="nav-item idc_left_navbar_sub"> #--> Same Custom class "idc_left_navbar_sub" added for another SubMenu Item.
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Inactive Page</p>
                </a>
              </li>
            </ul>
          </li>
```
2. Now add below Scripts.
```
$('.idc_left_navbar').on('click',function(){ #--> Main Menu Clicks
  var tmp = $(this);
  //console.log(tmp);
  $('.idc_left_navbar_sub a.active').removeClass('active'); #--> Removing active class from all submenu.
  $('.idc_left_navbar a.active').removeClass('active'); #--> Removing active class from all main menu.
  $(this).children('a').addClass('active'); #--> Adding active class to element a for highlighting Main Menu.
  //var tmp = $(this).children('a').addClass('active');
  //console.log(tmp);
});

$('.idc_left_navbar_sub').on('click',function(){ #--> SubMenu Clicks
  //var tmp = $(this);
  //console.log(tmp);
  $('.idc_left_navbar_sub a.active').removeClass('active'); #--> Removing active class from all submenu.
  $(this).children('a').addClass('active'); #--> Adding active class to element a for highlighting SubMenu.
  //var tmp = $(this).children('a').addClass('active');
  //console.log(tmp);
});
```

3. No errors in console. but when checking output of $(this), i can see active class not getting added for SubMenu element "a".

**Expected behavior**
Since my URL or Page is not getting changed, i need to dynamically set active class on MainMenu & SubMenu based user clicks. The body will be changed with AJAX Data.

**Screenshots**
![Screen Shot 2020-04-10 at 6 31 52 PM](https://user-images.githubusercontent.com/10374816/78993106-94af2200-7b5a-11ea-933a-e1d37fb0988d.png)

I have actually clicked on the Active Page sub menu. But active class not getting added.

**Environment (please complete the following information):**
 - AdminLTE Version: AdminLTE-3.0.2
 - Operating System:  macOS High Sierra
 - Browser (Version): Chrome & Safari

**Additional context**

**Comment by REJack** [comment]
Check this custom script https://github.com/ColorlibHQ/AdminLTE/issues/1482#issuecomment-559347681, this one set the active menu on page change but you can modify it to work with ajax.

**Comment by Jithin-C-V** [comment]
> #1482 (comment)

Hi RE Jack,

I saw this before posing, but i confused on below line.

> var url = window.location;

**Comment by Jithin-C-V** [comment]
> Check this custom script [#1482 (comment)](https://github.com/ColorlibHQ/AdminLTE/issues/1482#issuecomment-559347681), this one set the active menu on page change but you can modify it to work with ajax.

Hi RE Jack,

I am not able to see the mentioned classes in AdminLTE3 Sample Page. Are those cusotm classes ?

**Comment by REJack** [comment]
Try this

```js
    $('.nav-sidebar a').on('click', function(e) {
        e.preventDefault();
        var url = this.href;
        if (!url.includes('#')) {
          $('.nav-item.active, .nav-link.active').removeClass('active');
  
          // for sidebar menu entirely but not cover treeview
          $('.nav-sidebar a.nav-link').filter(function() {
            return this.href.includes(url) && !this.href.includes('#');
          }).addClass('active');
  
          // for treeview
          $('.nav-sidebar .nav-treeview a').filter(function() {
            return this.href.includes(url) && !this.href.includes('#');
          }).parents(".menu-open").find("> .nav-link").addClass('active');
        }
    });
```

**Comment by Jithin-C-V** [comment]
> Try this
> 
> ```js
> $('.nav-sidebar a').on('click', function(e) {
>   e.preventDefault();
>   var url = this.href;
>   if (!url.includes('#')) {
>     $('.nav-item.active, .nav-link.active').removeClass('active');
> 
>     // for sidebar menu entirely but not cover treeview
>     $('.nav-sidebar a.nav-link').filter(function() {
>       return this.href.includes(url) && !this.href.includes('#');
>     }).addClass('active');
> 
>     // for treeview
>     $('.nav-sidebar .nav-treeview a').filter(function() {
>       return this.href.includes(url) && !this.href.includes('#');
>     }).parents(".menu-open").find("> .nav-link").addClass('active');
>   }
> });
> ```

Hi Jack,

It selecting all Menu & SubMenu when clicking on any menu.

![Screen Shot 2020-04-10 at 8 09 23 PM](https://user-images.githubusercontent.com/10374816/78998962-4d7b5e00-7b67-11ea-9bbc-47db1a181659.png)

**Comment by REJack** [comment]
If you follow the sidebar menu structure like it's in starter.html it should work, but this works not for links with query it only checks for the raw link like (test.html, test2.html ...) not (test.html?page=norm, test.html?page=doub ...)

**Comment by Jithin-C-V** [comment]
> If you follow the sidebar menu structure like it's in starter.html it should work, but this works not for links with query it only checks for the raw link like (test.html, test2.html ...) not (test.html?page=norm, test.html?page=doub ...) it works also not with links like this (index#test, index#config ...) this would cause a more enhanced script.

I am following SideBar menu structure only. Infact i used Starter.html. But changed name to Console.php

In my case, there is no URL Changes. What ever clicks we are doing, the URL will be http://<IP>:8080/Console.php

**Comment by REJack** [comment]
You use in every href `javascript:void(0)` that's why all links will acivated, you can place there the real links.

**Comment by Jithin-C-V** [comment]
> You use in every href `javascript:void(0)` that's why all links will acivated, you can place there the real links.

Yeah. Here is the problem. These navigations actually not opening any new page. 

I will add a custom class & data, which load body from AJAX based clicked menu.

What is best to achieve both ?

**Comment by REJack** [comment]
Sure that's the point with ajax based pages, that's why I've added `e.preventDefault();` (this will bock the default click event like switch page).

You can place your AJAX script in my custom script and get the correct page via `url/this.href` this should work easily, but my script need a real href not a fake or a href that all links have.

**Comment by Jithin-C-V** [comment]
> Sure that's the point with ajax based pages, that's why I've added `e.preventDefault();` (this will bock the default click event like switch page).
> 
> You can place your AJAX script in my custom script and get the correct page via `url/this.href` this should work easily, but my script need a real href not a fake or a href that all links have.

I have put unique name for href.
```
[root@jithin-dev includes]# grep "href" SIDEBAR_MENU.include 
	    <a href="Console.php" class="nav-link active">
            <a href="Console2.php" class="nav-link">
                <a href="Console3.php" class="nav-link">
                <a href="Console4.php" class="nav-link">
            <a href="Console5.php" class="nav-link">
[root@jithin-dev includes]# 
```

But still the active class have issues in adding and removing.

![Screen Shot 2020-04-10 at 8 49 51 PM](https://user-images.githubusercontent.com/10374816/79001842-de086d00-7b6c-11ea-9cf4-7acd29e611c3.png)
![Screen Shot 2020-04-10 at 8 49 29 PM](https://user-images.githubusercontent.com/10374816/79001846-dfd23080-7b6c-11ea-9042-0236fafa43c5.png)
![Screen Shot 2020-04-10 at 8 49 20 PM](https://user-images.githubusercontent.com/10374816/79001847-e06ac700-7b6c-11ea-9187-d5f5cd830238.png)

**Comment by REJack** [comment]
You give the "Dashboard_New" also a real href but this should only have a href="#" otherwise you would load there any time a content but it's only a submenu header to open the elements below.

**Comment by Jithin-C-V** [comment]
> You give the "Dashboard_New" also a real href but this should only have a href="#" otherwise you would load there any time a content but it's only a submenu header to open the elements below.

I changed the Dashboard_New's href to "#". Still same behaviour.

**Comment by REJack** [comment]
Check this [fiddle](https://jsfiddle.net/kh2zyL6g/), there you see my adaption of the sidebar with the custom js script.

**Comment by Jithin-C-V** [comment]
> Check this [fiddle](https://jsfiddle.net/kh2zyL6g/), there you see my adaption of the sidebar with the custom js script.

Fiddle is working like a charm.

Let me take fresh starter.html and try same.

**Comment by Jithin-C-V** [comment]
Done everything from scratch. Now worked like a charm...

Thanks a lot for your time and great support RE Jack.

**Comment by REJack** [comment]
No problem 😄
