### ISSUE TITLE
[BUG] With layout-navbar-fixed class appear white space in sidebar

### ISSUE THREAD

**Issue by wondertalik** [ColorlibHQ/AdminLTE#2647]
**Describe the bug**
There are a few problems.
1.  If you don´t want to use footer block, then at the bottom of the sidebar appear white free space. (Screenshot 1)
2. The footer is above the sidebar. (Screenshot 2)

**To Reproduce**
1. Add class "layout-navbar-fixed" to body
2. Remove or leave footer block

**Screenshots**
Screenshot 1
![Captura de Pantalla 2020-04-11 a la(s) 2 28 24 p  m](https://user-images.githubusercontent.com/1611064/79043695-0346bb00-7c01-11ea-92c2-e12e0cdd59fc.png)

Screenshot 2
![Captura de Pantalla 2020-04-11 a la(s) 2 37 36 p  m](https://user-images.githubusercontent.com/1611064/79043836-13ab6580-7c02-11ea-88d2-a288fa080f1c.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.* - 3.0.4
 - Operating System:  macOS Catalina
 - Browser (Version): Chrome (Latest)

**Comment by danny007in** [comment]
`<body class="hold-transition sidebar-mini layout-navbar-fixed">`

> Replace with this code and try.

**Comment by wondertalik** [comment]
> `<body class="hold-transition sidebar-mini layout-navbar-fixed">`
> 
> > Replace with this code and try.

@danny007in. Nop, doesn't work.

**Comment by Jithin-C-V** [comment]
I faced the same issue. What i done is, i have added layout-fixed class.

`<body class="hold-transition sidebar-mini layout-navbar-fixed layout-fixed">`

**Comment by danny007in** [comment]
update adminlte to latest vesion 3.0.4

**Comment by REJack** [comment]
I found the problem and will fix it in the next days.

**Comment by wondertalik** [comment]
@Jithin-C-V thanks, it works.

@REJack , thanks for your job.

**Comment by REJack** [comment]
I've added a fix for this in the master branch 😄
