### ISSUE TITLE
[BUG] Side bar won't stay collapsed

### ISSUE THREAD

**Issue by Sarrus1** [ColorlibHQ/AdminLTE#2651]
**Describe the bug**
Whatever I do, if I refresh the page or change the page, the sidebar will be expanded.

**To Reproduce**
It happens straight out of the box. Same behavior on the demo website.
Collapse the sidebar, refresh the page, and the sidebar isn't collapsed.

**Expected behavior**
The sidebar should "remember" the position it had before the refresh or the page change.

**Environment (please complete the following information):**
 - AdminLTE Version:  v3.0.4
 - Operating System: macOS Catalina
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
Did you enabled the remeber function? It’s not enabled by default.

**Comment by Sarrus1** [comment]
I've set the enableRemeber to true in adminlte.js, like this:
`var Default = {
      autoCollapseSize: 992,
      enableRemember: true,
      noTransitionAfterReload: true
    };`

However it did not fix the issue

I've also added the pushmenu plugin to my sidebar button like to:

`<a class="nav-link" data-widget="pushmenu" data-enable remember="true" href="#" role="button"><i class="fas fa-bars"></i></a>`

With no success haswell

**Comment by REJack** [comment]
You set the inline option wrong

You set it like this: 
`<a class="nav-link" data-widget="pushmenu" data-enable remember="true" href="#" role="button"><i class="fas fa-bars"></i></a>`

But it should look like this:
`<a class="nav-link" data-widget="pushmenu" data-enable-remember="true" href="#" role="button"><i class="fas fa-bars"></i></a>`

**Comment by Sarrus1** [comment]
That solved the issue! Thanks a lot!

However, for some reason, this worked on one page, without any glitch, however, on another page, the sidebar collapses very quickly when i reload the page.

Both html pages use the same base.html (i'm using django)

**Comment by REJack** [comment]
yeah that comes from the plugin itself, it wait's until the DOM is complete loaded/renderd and then it triggers the sidebar to the correct state to get avoid of this you need to implement this in your app itself instead of using the JS function.

**Comment by Sarrus1** [comment]
Oh ok, I'll look into it then, thanks :D

**Comment by REJack** [comment]
No problem :D If you have some other questions related to AdminLTE, feel free to open a new issue.
