### ISSUE TITLE
Admin LTE version 2 - Calendar question

### ISSUE THREAD

**Issue by pascalf22** [ColorlibHQ/AdminLTE#2652]
Hello !

First of all.. thanks for AdminLTE... i really love it ! If i can contribute(give you money), let me know i will do it!
I have a SMALL question...

I'm trying to use the Calendar (Admin LTE version2)

I saw in javascript code the Drop function.

I want to save it in the database... but how i get the begening time... All my events are 1 hour long... but i need to get the start time and day in the DROP function...

How can i get it ?

Here the code of the DROP function :

```
drop      : function (date, allDay) { // this function is called when something is dropped
      

        // retrieve the dropped element's stored Event Object
        var originalEventObject = $(this).data('eventObject')

        // we need to copy it, so that multiple events don't have a reference to the same object
        var copiedEventObject = $.extend({}, originalEventObject)

        // assign it the date that was reported
        copiedEventObject.start           = date
        copiedEventObject.allDay          = allDay
        copiedEventObject.backgroundColor = $(this).css('background-color')
        copiedEventObject.borderColor     = $(this).css('border-color')
        //alert(copiedEventObject.start );
        // render the event on the calendar
        // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
        $('#calendar').fullCalendar('renderEvent', copiedEventObject, true)

        // is the "remove after drop" checkbox checked?
        if ($('#drop-remove').is(':checked')) {
          // if so, remove the element from the "Draggable Events" list
          $(this).remove()
        }

      }
```

Thanks a lot and have a great day !

Pascal

**Comment by pascalf22** [comment]
Hello !
I also need to get the external event ID (lunch,GoHome, dohomeWord) and the time..
To insert in database...
Can i achieve it in version 2 ?
Is it all in drop function ?
Please!

Thanks a lot!
Pascal

**Comment by REJack** [comment]
AdminLTE has no own Calendar Plugin, for this you should checkout the [fullCalendar docs](https://fullcalendar.io/docs/drop).

**Comment by pascalf22** [comment]
ok thanks !
