### ISSUE TITLE
[FEATURE] Will the new user panel be getting a pop up box with a profile button and logout button?

### ISSUE THREAD

**Issue by TimothyBramlett** [ColorlibHQ/AdminLTE#2655]
The old user panel had a pop up box like this:

![image](https://user-images.githubusercontent.com/7890441/79519272-05ea4b80-8019-11ea-8b9a-0a423c6f0040.png)

The new user panel does not have one:

![image](https://user-images.githubusercontent.com/7890441/79519324-23b7b080-8019-11ea-93ad-23293e7a1779.png)

Would it be possible to add one?

**Comment by GerryGe** [comment]
You can find it in Extras menu...
![image](https://user-images.githubusercontent.com/6952917/79555983-01826900-80d3-11ea-8f28-f94a7c02708e.png)

**Comment by TimothyBramlett** [comment]
@GerryGe I am actually not talking about the legacy profile. :)

I mean a new pop up for the new panel.  Do you understand what I mean?
