### ISSUE TITLE
[FEATURE] Fontawesome 5.13.0 svg icons not correctly displayed

### ISSUE THREAD

**Issue by DivadNojnarg** [ColorlibHQ/AdminLTE#2657]
**Describe the bug**
I was trying to use the Fontawesome 5.13.0 svg icons pack. I followed the instructions from [their](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-svg) page and included the the all.min.js file. While almost all icons render well, I noticed issues with timeline icons and small card icons. 

**Expected behavior**

Icons should properly render. Moreover, small card icons should be animated on hover, which is not the case.

**Screenshots**

<img width="1563" alt="Screenshot 2020-04-21 at 08 59 30" src="https://user-images.githubusercontent.com/18291543/79835187-94125900-83ae-11ea-8795-8283275490f0.png">

<img width="932" alt="Screenshot 2020-04-21 at 09 00 46" src="https://user-images.githubusercontent.com/18291543/79835286-bb692600-83ae-11ea-8029-7a74b21cf2d1.png">

Expected:
<img width="932" alt="Screenshot 2020-04-21 at 09 01 35" src="https://user-images.githubusercontent.com/18291543/79835354-dcca1200-83ae-11ea-9a49-c527359ee4fa.png">

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.4]
 - Operating System:  [e.g. macOS Mojave, Windows 10]
 - Browser (Version): [e.g. Chrome (Latest), Safari, ...]

**Comment by namkylan** [comment]
Thanks your guild

**Comment by REJack** [comment]
That's not a bug, AdminLTE v3 doesn't support FA SVG icons at the moment, but I'll add this to the v3.1 Milestone.
