### ISSUE TITLE
[HELP]Install AdminLTE 3 from npm to laravel project

### ISSUE THREAD

**Issue by hrace009** [ColorlibHQ/AdminLTE#2659]
I have installed adminlte on my laravel project with command ```npm install admin-lte```, and build using ```npm run prod```. and everything bundle on app.css and app.js
Everything run perfect and i can create the admin menu exactly like demo AdminLte3.

but i can't execute toastr.
i try make button to execute toastr like bellow:
```
<button type="button" class="btn btn-primary" onclick="toastr.success('Data has been save!')">Save changes</button>
```
when i press the button, it show nothing.

but when i try it on plain HTML, it work.

Anyone can give clue about this?

Thanks

**Comment by REJack** [comment]
You need to load toastr by your self, it's a third-party plugin.
