### ISSUE TITLE
[npm install fails]

### ISSUE THREAD

**Issue by leihuagh** [ColorlibHQ/AdminLTE#2660]
**Describe the bug**
Fresh install package cannot be built by "npm install"

**To Reproduce**
1. Create a folder called "templates" and cd in "templates"
2. Go to 'https://github.com/ColorlibHQ/AdminLTE'
3. Click on green button 'clone or download', click on icon for copy to clip.
4. Paste to command line
```shell
git clone https://github.com/ColorlibHQ/AdminLTE.git adminlte
```
5. cd in adminlte and type "remove .git"
```shell
cd adminlte
rm -rf .git
git init
```
6. Run "npm install"
```shell
npm install
```
7. Failure occurs. 

**Expected behavior**
After upgrading node.js to 14.0.0

**Screenshots**
---------------------------------------------------------------
λ npm install

> node-sass@4.13.1 install C:\xampp\htdocs\templates\adminlte\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via
--------------------------------------------------

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.4]
 - Operating System:  [Windows 10]
 - Browser (Chrome (Latest)]
- Node.js 14.0.0

**Additional context**

**Comment by hugomarshall** [comment]
I have the same problem with admin-lte@2.4.12.

**Comment by leihuagh** [comment]
> I have the same problem with admin-lte@2.4.12 in Visual Studio cdnjs

I finally solve the problem.  

Remove Node.js
Remove /users/<your name>/AppData/Roaming/npm
Remove /users/<your name>/AppData/Roaming/npm-cache

Re-install node.js
Re-install all packages in global include: npm-check-updates

git clone adminlte 3.0.4 to your localhost.
cd in adminlte folder
remove .git
git init
ncu -u (update all packages in package.json)
remove package-lock.json
npm install
npm run dev

You can build up the app without any problem
