### ISSUE TITLE
[FEATURE] How to completely close sidebar on desktop?

### ISSUE THREAD

**Issue by jmlxxvi** [ColorlibHQ/AdminLTE#2661]
**Is your feature request related to a problem? Please describe.**
When using desktop size screens the sidebar gets minified but I would like it to be completely closed as it is when the screen is small.

**Describe the solution you'd like**
I would like to behave the same as mobile size version, just closing the sidebar completely. 

**Describe alternatives you've considered**
No alternatives considered so far.

**Additional context**

**Comment by REJack** [comment]
Simply remove the `sidebar-mini` class from body.

**Comment by jmlxxvi** [comment]
That was it. Thank you for your promptly help.
