### ISSUE TITLE
[BUG] Collapsed sidebar on Mac/Ipad (Safari)

### ISSUE THREAD

**Issue by wondertalik** [ColorlibHQ/AdminLTE#2662]
Good day.

On ipad/safari 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1611064/80480197-816cc680-8950-11ea-9ae8-a422c1c3b145.gif)

On mac/safari
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/1611064/80480895-c1807900-8951-11ea-86f3-31c900330b1b.gif)

**Describe the bug**
On ipad/safari when the menu is collapsed and I click on some item in sidebar, the sidebar text disappears.
On mac/safari when I point to the sidebar, the text inside disappears

**To Reproduce**
1. Open demo on ipad, collapse sidebar
2. Click/Hover on sidebar menu

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.4
 - Operating System:  macOS Catalina
 - Browser (Version): Safari (Latest)

**Comment by REJack** [comment]
Which iPadOS Version you use? Can you test if the issue is on the Dashboard 3 page too?

**Comment by wondertalik** [comment]
> Which iPadOS Version you use? Can you test if the issue is on the Dashboard 3 page too?

1. IpadOS 13.4.1
2. This issue appears on all pages, including Dashboard 3.

**Comment by REJack** [comment]
I've added a fix with d20dd7c13a2a0a67bd2ec7acc8286f4bcac3c17c, may you can clone the master branch & test it on your iPad. 
I have only an old iPad Mini (max iOS9 🤣) but on my MacBook with 10.15.4 it works now.

**Comment by wondertalik** [comment]
ok, i will try in a few days. thanks.
