### ISSUE TITLE
[BUG] Failed npm install plugins

### ISSUE THREAD

**Issue by fedee13** [ColorlibHQ/AdminLTE#2663]
**Describe the bug**
Fails to install library with npm

**To Reproduce**
1. Try npm install admin-lte
2. See error

**Expected behavior**
Successful Install library in project

**Screenshots**
![alt text](https://i.imgur.com/bWdF8kd.png "install error")
[https://imgur.com/bWdF8kd](screenshot)

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.4
 - Operating System:  Windows 7
 - Browser (Version): Chrome [(Latest)](url)

**Additional context**

**Comment by REJack** [comment]
I would guess you use nodejs 8 or lower, AdminLTE dropped the nodejs 8 support since it's no maintained anymore.

**Comment by fedee13** [comment]
You can close it if you want, indeed the version on the computer was 8.11.3, sorry!
