### ISSUE TITLE
Jquery File Upload[FEATURE]

### ISSUE THREAD

**Issue by AnNajib** [ColorlibHQ/AdminLTE#2664]
Please add Jquery File Upload example or another similar upload plugin

**Comment by REJack** [comment]
Please add some examples.

**Comment by AnNajib** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/41133893/80794924-52ab5600-8bc5-11ea-8181-2d4abed1a10a.png)
the challenge is, it did not use Bootstrap 4 yet

**Comment by REJack** [comment]
I'm not happy to add new plugins based on jQuery, 
But I will look for some jQuery less plugins for this, like https://fineuploader.com.
