### ISSUE TITLE
[BUG] Dropdown Card Widget calculates wrong position

### ISSUE THREAD

**Issue by lodzen** [ColorlibHQ/AdminLTE#2665]
**Describe the bug**
When the dropdown Button is toggled in a card Widget the Menu always pops up at the bottom right Position as visible at the following link in the Calendar card:
https://adminlte.io/themes/v3/index.html

**To Reproduce**
1. Go to the Calendar Card
2. Click on the dropdown
3. The Menu is displayed out of the card border

**Expected behavior**
It should be possible to define the position of the dropdown menu.

**Screenshots**
![Screenshot_20200430-144543_Chrome](https://user-images.githubusercontent.com/21340840/80712333-2541a800-8af2-11ea-9ab4-f85054de14f5.jpg)

**Environment (please complete the following information):**
 - AdminLTE Version: latest
 - Operating System:  Windows
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
I've added in the master branch a offset to this dropdown menu, now it looks like this.

![Bildschirmfoto vom 2020-05-02 um 12 35 33](https://user-images.githubusercontent.com/1554582/80861932-d458bd80-8c71-11ea-94c9-98aecaaa9fc7.png)
