### ISSUE TITLE
[BUG] Issue in Menu collapse in mobile view after project was converted to angular

### ISSUE THREAD

**Issue by hardeeksharma** [ColorlibHQ/AdminLTE#2667]
**Describe the bug**
I converted the project to an angular project where i added all that static css some that were available as cdn directly in index.html and others in assets and added them to path in angular.json.
Same was done for all the JS
And then i copied the index.html code to angular's app.component.html. When i accessed the file via mobile i was able to open the side menu but it was not able to close when clicking anywhere

**Comment by REJack** [comment]
I don't use AngularJS, but you can checkout this Implementation [AdminLTE-3-Angular](https://github.com/erdkse/adminlte-3-angular).

**Comment by hardeeksharma** [comment]
Thankxx man. I didnt used angular JS I was converting is into Angular 8 project. I'll check you implementation
