### ISSUE TITLE
[BUG] npm install on linux

### ISSUE THREAD

**Issue by rntjr** [ColorlibHQ/AdminLTE#2669]
## **Describe the bug**
I created a new angular project, right after i tryed to install via npm.
It failed to install, thats the log file:
[2020-05-03T23_21_36_490Z-debug.log](https://github.com/ColorlibHQ/AdminLTE/files/4572249/2020-05-03T23_21_36_490Z-debug.log)

## **To Reproduce**

1. #npm install -g @angular/cli
2. #ng new angular
3. #cd angular
4. #npm install admin-lte@^3.0 --save

## **Environment:**
 - AdminLTE Version: [e.g. v3.0.0]
 - Operating System:  Linux renato-pc 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
 - Browser (Version): Chrome (Latest)

## **Additional context**
I used root user for execute the commands.

**Comment by REJack** [comment]
I can't replicate this issue on my dev webserver, I tested it with node 10.15.2, 10.20.1 & 12.16.1 and it worked without any error.

**Comment by rntjr** [comment]
I tested in my windows machine and worked. Maybe it's my Linux machine that's trouble. 
It presented that's a message: Error: EACCES: permission denied.
