### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by christopherison8** [ColorlibHQ/AdminLTE#2671]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v2.4.18]
 - Operating System:  [e.g. macOS Catalina]
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
Issue without any usable content
