### ISSUE TITLE
[BUG] Searchfield in sidebar under-/overfilling width

### ISSUE THREAD

**Issue by dotdeas** [ColorlibHQ/AdminLTE#2673]
**Describe the bug**
The searchfield in sidebar don't match the width correctly. Both Safari and Chrome (macOS) are showing different width on the same page with the same code.

**To Reproduce**
Added searchfield code from the documentation

**Expected behavior**
Searchfield is not filling the width or are overfilling it.

**Screenshots**
![image](https://user-images.githubusercontent.com/4384392/80972254-33f3cc00-8e1e-11ea-9d89-f1755eacaa8c.png)
Left sidebar is in Safari 13.1, the right sidebar is Chrome 81.0.4044.129. Both are on macOS but tried in Chrome on a Windows machine and it was the same issue.

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.4
 - Operating System:  macOS 10.15.4 (also tried on Windows 10 (1910)
 - Browser (Version): Safari and Chrome (latest)

**Comment by REJack** [comment]
I've added a fix in the master branch for this 😄

**Comment by dotdeas** [comment]
Tested the fix from the master branch and it fixed it issue, thanks :)

**Comment by REJack** [comment]
Sweet 👍 I'll publish a new release in the next days.

**Comment by dotdeas** [comment]
Just noticed that the margin to the nav-items also seems to be off. Tried placing the code on different locations in the sidebar section but same result.

![image](https://user-images.githubusercontent.com/4384392/81057226-4c222480-8ecc-11ea-8bec-0f894da3da13.png)

**Comment by REJack** [comment]
I've added the same margin-bottom like the nav-link's to the master branch, but you can override it with `.mb-*`.
