### ISSUE TITLE
Sass file : ~bootstrap/scss/functions not found

### ISSUE THREAD

**Issue by atdesign10** [ColorlibHQ/AdminLTE#2675]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.0]
 - Operating System:  [e.g. macOS Catalina]
 - Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
Please fill out the complete bug report, including "To Reproduce".

**Comment by danny007in** [comment]
[https://stackoverflow.com/a/48549228](url)

find here
