### ISSUE TITLE
[BUG]add .sidebar-no-expand to aside.main-sidebar. no v2 hover effect

### ISSUE THREAD

**Issue by alienjun** [ColorlibHQ/AdminLTE#2676]
**Describe the bug**
in v3.x add .sidebar-no-expand to aside.main-sidebar. not have v2.x hover effect
v2.x effect:
<img width="313" alt="WX20200507-170815@2x" src="https://user-images.githubusercontent.com/3049502/81276696-f42f1d80-9085-11ea-9d8c-dd0b1dd39fc5.png">

How to achieve this effect in v3.x ?

**Comment by REJack** [comment]
This feature/behavior isn't implemented in v3, but it is already requested in #2435 and will come with v3.1.
