### ISSUE TITLE
[BUG] Text overflow on smaller screen sizes

### ISSUE THREAD

**Issue by immanuelfodor** [ColorlibHQ/AdminLTE#2677]
**Describe the bug**
On smaller screen/window sizes, the text in the top boxes overflows (see attached screenshot)

**To Reproduce**
Lower the browser viewport size or use a smaller screen resolution.

**Expected behavior**
The text is wrapping to the next line (may cause other troubles) or the overflown part is 3-dotted (e.g., Comments in the last...) and only shown on mouse hover in a tooltip.

**Screenshots**
![image](https://user-images.githubusercontent.com/21174107/81390618-0eb3d600-911c-11ea-9ab7-ce8b8bc121c0.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System: Linux (Manjaro, latest)
 - Browser (Version): Firefox, Chrome (all latest, seems to be a browser independent problem though)

**Comment by REJack** [comment]
To wrap the text in to a new line add to the `info-box-text` the class `text-wrap`.
To truncate the text with `...` add to the `info-box-content` the class `text-truncate`. (Here you should add a tooltip to display the whole pharse)

**Comment by immanuelfodor** [comment]
Thanks, fixed it locally, will it be included in a future release?

**Comment by REJack** [comment]
Our demo pages are only examples, we not need to add this in the demo it's also a user choice how to manage to long textes. But I'll add a note to the docs for the info boxes.

**Comment by immanuelfodor** [comment]
Okay, feel free to close this if you want to :)

**Comment by REJack** [comment]
I've added a note to the docs, it will updated with the next release.
