### ISSUE TITLE
[BUG] install adminlte 3 laravel npm run watch error

### ISSUE THREAD

**Issue by carlospas** [ColorlibHQ/AdminLTE#2679]
I need to install adminlte3 in laravel 7

my error is when I add on app.scss:

**if I use:**

`@import "~admin-lte/dist/css/adminlte.css";`

> ERROR in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/admin-lte/dist/css/adminlte.css
> Module build failed: BrowserslistError: Unknown browser query `dead`
> at C:\Users\Admin\Desktop\app\edonline\eduapp\node_modules\browserslist\index.js:164:11
> at Array.reduce (<anonymous>)

if I use:

`@import "node_modules/admin-lte/dist/css/adminlte.css";`

> ERROR in ./resources/assets/sass/app.scss
> Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './node_modules/admin-lte/dist/css/adminlte.css' in

**if I use:**

`@import "C:\Users\Admin\Desktop\app\edonline\eduapp\node_modules\admin-lte\dist\css\adminlte.css";`

> run but, dosen't work the template, just the boostrap 4.4.1 work

> app.scss boostrap RUN well
`@import "~bootstrap/scss/bootstrap.scss";`

> package.json

```
"devDependencies": {
    "axios": "^0.16.2",
    "bootstrap": "^4.4.1",
    "cross-env": "^5.0.1",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "popper.js": "^1.16.1",
    "vue": "^2.1.10"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.13.0",
    "admin-lte": "^3.0.4",
    "vue-top-progress": "^0.7.0"
  }

```

> boostrap.js

```
try {
    window.$ = window.jQuery = require('jquery');

    require('bootstrap');
    require('admin-lte');
} catch (e) {}
```

**Comment by REJack** [comment]
Try to upgrade your laravel-mix, the first example is the correct way to get this work without absolute paths.
