### ISSUE TITLE
[BUG] Main sidebar is not collapsing on click outside of it

### ISSUE THREAD

**Issue by SashaJarvi** [ColorlibHQ/AdminLTE#2680]
**Describe the bug**
Main sidebar is not collapsing, when I click outside of it in mobile devices

**To Reproduce**
1. Add `import '../node_modules/admin-lte/dist/js/adminlte.min.js' ` to my entrypoint (I use webpack)
2. Add `data-widget="pushmenu"` to a button to activate the plugin. In my case

```
<li class="nav-item">
    <a class="nav-link" data-widget="pushmenu" href="#" role="button">
    <i class="fas fa-bars"></i></a>
</li>
```

3. Add sidebar:

```
<aside class="main-sidebar sidebar-dark-primary elevation-4">
        <a href="" class="brand-link text-center" target="_blank">
            <span class="brand-text font-weight-light">Company name</span>
        </a>

        <div class="sidebar">
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="tree" role="menu" data-accordion="false">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon far fa-file-alt"></i>
                            First Item
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon far fa-edit"></i>
                            Second Item
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-id-card"></i>
                            Third Item
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>

```
4. `npm run start`
5. Go to responsive design mode in browser.
6. Choose device with <992px screen width.
7. Click on button to show sidebar.
8. Click outside of sidebar

**Expected behavior**
Main sidebar is collapsing on click outside of it

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.0]
 - Operating System:  Win 10
 - Browser (Version): Chrome (Latest)

**Additional context**
This is my entrypoint file

```
import $ from 'jquery'
import popper from 'popper.js';
import bootstrap from 'bootstrap';
import '../node_modules/admin-lte/dist/js/adminlte.min.js'

import './scss/style.scss';
```

And this is my `webpack.config.js`

```
const path = require('path');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
    entry: './src/index.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env'],
                        babelrc: true
                    }
                }
            },
            {
                test: /\.(sass|scss)$/,
                use:  ['style-loader', MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader', 'sass-loader']
            },
            {
                test: /\.(svg|eot|woff|woff2|ttf)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                            outputPath: 'fonts/'
                        }
                    }
                ]
            }
        ]
    },
    plugins: [
        new CleanWebpackPlugin(),
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
        new MiniCssExtractPlugin({
            filename: 'bundle.css',
        }),
        new HtmlWebpackPlugin({
            template: './src/index.html',
            filename: 'index.html'
        }),
        new HtmlWebpackPlugin({
            template: './src/operator.html',
            filename: 'operator.html'
        }),
    ]
};
```

**Comment by REJack** [comment]
Did you placed the `<div class="wrapper">` around the sidebar, navbar, footer and content-wrapper?

**Comment by SashaJarvi** [comment]
Yes, I placed
![image](https://user-images.githubusercontent.com/33623986/81547351-68b6d480-9384-11ea-87c2-0e2cf1429896.png)

**Comment by REJack** [comment]
Do you recieve any console errors?

**Comment by SashaJarvi** [comment]
Only this:
`DevTools failed to load SourceMap: Could not load content for http://localhost:8080/sockjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by REJack** [comment]
It looks like you need to init the plugins (e.g. PushMenu, Treeview & Layout) like its needed for Angular, React & VueJS.

**Comment by SashaJarvi** [comment]
I tried to init plugin using jQuery, but the issue remains
![image](https://user-images.githubusercontent.com/33623986/82180162-a79adc00-98e8-11ea-932d-78304a970c4f.png)

**Comment by REJack** [comment]
Did you added the `sidebar-toggle-btn` class to your button? You not need a extra class for this, you can use `[data-widget="pushmenu"]` instead also you need to init the Layout Plugin too for the sidebar overlay.

**Comment by SashaJarvi** [comment]
I tried to do this, but the issue still remains 
![image](https://user-images.githubusercontent.com/33623986/82571817-2d8a8180-9b8c-11ea-804b-29d2c124fbe1.png)
![image](https://user-images.githubusercontent.com/33623986/82571838-367b5300-9b8c-11ea-8b6d-b1e84a846e5c.png)

**Comment by REJack** [comment]
If you want the sidebar overlay to close the sidebar on small screens, you need also to init the Layout plugin.

**Comment by SashaJarvi** [comment]
I understood. Should I do it like this?

`$('body').Layout('fixLayoutHeight')`

**Comment by REJack** [comment]
No 😄 it should be only `$('body').Layout()` or `$('body').Layout('init')` (both do the same).

**Comment by SashaJarvi** [comment]
Okay, I'll try it, thanks

**Comment by SashaJarvi** [comment]
Sorry, but it still does not work( I cannot understand the reason
![image](https://user-images.githubusercontent.com/33623986/82575652-6c6f0600-9b91-11ea-8def-7b857d89b155.png)
![image](https://user-images.githubusercontent.com/33623986/82575709-7d1f7c00-9b91-11ea-9718-a3feeffb68b2.png)

**Comment by SashaJarvi** [comment]
This is some kind of dark magic😄

**Comment by REJack** [comment]
Mmh do you receive any console error now?

**Comment by REJack** [comment]
Other questions do you build this in a public project or in a private project, if its public I would look over it later 😄 or do you can create me a demo repo for it?

**Comment by SashaJarvi** [comment]
No, I have not any errors in console.
Yes, I can create repo for you within 30 minutes or an hour.

**Comment by REJack** [comment]
Perfect, I will look over it later this evening 😃.

**Comment by SashaJarvi** [comment]
I made the demo repo for you. Thank you in advance)
https://github.com/SashaJarvi/admin-layout

**Comment by SashaJarvi** [comment]
Maybe something to do with Webpack?

**Comment by REJack** [comment]
You got a Issue on your repo 😄

**Comment by SashaJarvi** [comment]
Oh, it was my mistake 😄 
Thank you very much for you time!

**Comment by REJack** [comment]
No problem 😄 I close this issue. Feel free to open a new issue when you have another problems.

**Comment by msaltieri** [comment]
Sorry guys, just because I had the exact same problem, I drop the solution here since it is not reported in this thread.

In case someone did it, the `<div id="sidebar-overlay">` **must not** be created manually within the `<div class="wrapper">` element. As @REJack reported, this prevents the function to be applied on click.

**Comment by atefBB** [comment]
I've followed the `solution` steps but the button still not working ! 
I have the same issue as @SashaJarvi, @REJack any ideas? Thank you.

**Comment by jaycee04** [comment]
> Oh, it was my mistake 😄
> Thank you very much for you time!

wheres the solution? i got the same problem here too ..but base on comments the solution never posted. it was ended like magic. you posted the repo then tada !

**Comment by agussudarmanto** [comment]
> > Oh, it was my mistake 😄
> > Thank you very much for you time!
> 
> wheres the solution? i got the same problem here too ..but base on comments the solution never posted. it was ended like magic. you posted the repo then tada !

![image](https://user-images.githubusercontent.com/4178612/114552534-e703b100-9c8e-11eb-96d5-f600e7a5fdda.png)

As mention from @msaltieri here https://github.com/ColorlibHQ/AdminLTE/issues/2680#issuecomment-639049137
i just comment sidebar-overlay element, thanks
