### ISSUE TITLE
[BUG] Select2 dropdown doesn't appear when the card is maximized (using data-card-widget="maximize")

### ISSUE THREAD

**Issue by 77media-creations** [ColorlibHQ/AdminLTE#2682]
**Describe the bug**
Select2 dropdown list doesn't appear when the card is made full screen using card-tools (data-card-widget="maximize").

**To Reproduce**
1. Create a` div class="card"`.
2. Add card tools `div class="card-tools"` in card header.
3. Add maximize button `data-card-widget="maximize"` in card tools.
4. Add select2 form field on the `card-body`.
5. Maximize the card.
6. Click on select field and the dropdown doesn't appear here.

**Expected behavior**
A dropdown list of options should appear when clicking on select2 box.

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.4
 - Operating System:  macOS Catalina 10.15.3
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
I've added a fix for this in the master branch.
