### ISSUE TITLE
[BUG] Toastr positioClass="toast-bottom-full-width" not working

### ISSUE THREAD

**Issue by AdeSupriyadi** [ColorlibHQ/AdminLTE#2683]
**Toastr positioClass="toast-bottom-full-width" not working**
When we change option of toastr positionClass to toast-bottom-full-width, width not shown in full

**Screenshots**
It is From official toastr:
![image](https://user-images.githubusercontent.com/14267724/81797423-fa674300-9538-11ea-9620-e3a320fe3115.png)

it is in AdminLte toastr with positionClass="toastr-bottom-full-width"
![image](https://user-images.githubusercontent.com/14267724/81797618-3ac6c100-9539-11ea-940e-e3d27d5ef600.png)

**Environment :**
 - AdminLTE Version: v3.0.2
 - Operating System:  Ubuntu 20.04 Focal Fossa
 - Browser (Version): Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by REJack** [comment]
I've added a fix for this in the master branch, it will released with the next version.
