### ISSUE TITLE
[BUG] Node_modules in root directory.

### ISSUE THREAD

**Issue by gidaban** [ColorlibHQ/AdminLTE#2686]
**Describe the bug**
I just spotted when i uploading project on server, inside `admin-lte` directory is `node_modules` directory. That is really necessary? i am installing by npm 

**Environment (please complete the following information):**
 - AdminLTE Version: [e.g. v3.0.4]

**Comment by REJack** [comment]
Did you installed it with `npm install admin-lte`?

If yes, this node_modules folder comes not from AdminLTE itself. 
If no and you cloned AdminLTE and runned `npm install` then the node_modules folder is necessary.

**Comment by gidaban** [comment]
@REJack yes i installed with `npm install admin-lte`

**Comment by REJack** [comment]
I can't replicate this issue, I don't get a node_modules folder inside the admin-lte folder. This looks like a nodejs/npm bug, may the nodejs forum can help here.
