### ISSUE TITLE
Documentation on adding aditional style colors for elements e.g. btn card

### ISSUE THREAD

**Issue by semanticfire** [ColorlibHQ/AdminLTE#2687]
**Is your feature request related to a problem? Please describe.**
We would like to theme AdminLTE to match logo colors and add some aditional colors for cards and button e.g. btn-mytheme1

**Describe the solution you'd like**
Piece of documentation how to achieve this in the wiki

**Describe alternatives you've considered**
Copying existing styles and modify them in a seperate CSS. time consuming error prone

**Additional context**
Just changing the primary colors etc in the scss is not an ideal solution since warning/danger are still needed

**Comment by REJack** [comment]
That's a nice idea, I'll add a docs section for this in v3.1. For now I explain it here 😄 

1. You need to setup a build environment like AdminLTE's (node-sass & node-sass-package-importer)

2. Create a Main SCSS file like this:
```scss
/*!
 *   AdminLTE v3.0.4
 *   Author: Colorlib
 *   Website: AdminLTE.io <http://adminlte.io>
 *   License: Open source - MIT <http://opensource.org/licenses/MIT>
 */

// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/bootstrap-variables';
@import '~bootstrap/scss/bootstrap';

// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/variables';
@import '~admin-lte/mixins';

@import '~admin-lte/parts/core';
@import '~admin-lte/parts/components';
@import '~admin-lte/parts/extra-components';
@import '~admin-lte/parts/pages';
@import '~admin-lte/parts/plugins';
@import '~admin-lte/parts/miscellaneous';
```

3. Add a map-merge for the theme-colors like this:
```scss
/*!
 *   AdminLTE v3.0.4
 *   Author: Colorlib
 *   Website: AdminLTE.io <http://adminlte.io>
 *   License: Open source - MIT <http://opensource.org/licenses/MIT>
 */

// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/bootstrap-variables';
@import '~bootstrap/scss/bootstrap';

// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/variables';
@import '~admin-lte/mixins';

$company: #00FF00;
$theme-colors: map-merge((
    'company': $company,
), $theme-colors);

@import '~admin-lte/parts/core';
@import '~admin-lte/parts/components';
@import '~admin-lte/parts/extra-components';
@import '~admin-lte/parts/pages';
@import '~admin-lte/parts/plugins';
@import '~admin-lte/parts/miscellaneous';
```

4. Compile a CSS file from the SCSS file 😄 
5. Enjoy your custom theme color

**Comment by semanticfire** [comment]
Okay, great tip! I played around with it a bit and have some questions/remarks
* I see that I get a bunch of '*-company' styles which I can use ( great! )
* it will generate a full CSS, not a theme 'add-on' , correct ?
* I don't get btn-company styles?

Keep up the good work!

**Comment by REJack** [comment]
Yep it will create the complete AdminLTE css files, with v4 comes the skin support back.

It should create a btn-company style too, you could also use the mixins to create only the btn-company style like additional styles/skin for AdminLTE. I can give you later a code snippet to generate only these instead of compiling thr whole AdminLTE.

**Comment by semanticfire** [comment]
It currently does not create the btn-* styles

**Comment by REJack** [comment]
Ok I found my failure 😄 the file should look like this:

```scss
/*!
 *   AdminLTE v3.0.4
 *   Author: Colorlib
 *   Website: AdminLTE.io <http://adminlte.io>
 *   License: Open source - MIT <http://opensource.org/licenses/MIT>
 */

// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/build/scss/bootstrap-variables';

$company: #00FF00;
$theme-colors: map-merge((
    'company': $company,
), $theme-colors);

// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/build/scss/variables';
@import '~admin-lte/build/scss/mixins';

@import '~bootstrap/scss/bootstrap';

@import '~admin-lte/build/scss/parts/core';
@import '~admin-lte/build/scss/parts/components';
@import '~admin-lte/build/scss/parts/extra-components';
@import '~admin-lte/build/scss/parts/pages';
@import '~admin-lte/build/scss/parts/plugins';
@import '~admin-lte/build/scss/parts/miscellaneous';
```

or for a simple skin you can use this:
```scss
// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/build/scss/bootstrap-variables';
@import '~bootstrap/scss/mixins';

$company: #00FF00;

.btn-company {
    @include button-variant($company, $company);
}
```

**Comment by semanticfire** [comment]
Now it works as expected!
For me the issue is done, but I guess you'll leave it open as documentation check?

**Comment by REJack** [comment]
Yep, I will close it if the docs information is added.

**Comment by draizada** [comment]
> Ok I found my failure 😄 the file should look like this:
> 
> ```css-scss
> /*!
>  *   AdminLTE v3.0.4
>  *   Author: Colorlib
>  *   Website: AdminLTE.io <http://adminlte.io>
>  *   License: Open source - MIT <http://opensource.org/licenses/MIT>
>  */
> 
> // Bootstrap
> // ---------------------------------------------------
> @import '~bootstrap/scss/functions';
> @import '~admin-lte/build/scss/bootstrap-variables';
> 
> $company: #00FF00;
> $theme-colors: map-merge((
>     'company': $company,
> ), $theme-colors);
> 
> // Variables and Mixins
> // ---------------------------------------------------
> @import '~admin-lte/build/scss/variables';
> @import '~admin-lte/build/scss/mixins';
> 
> @import '~bootstrap/scss/bootstrap';
> 
> @import '~admin-lte/build/scss/parts/core';
> @import '~admin-lte/build/scss/parts/components';
> @import '~admin-lte/build/scss/parts/extra-components';
> @import '~admin-lte/build/scss/parts/pages';
> @import '~admin-lte/build/scss/parts/plugins';
> @import '~admin-lte/build/scss/parts/miscellaneous';
> ```
> 
> or for a simple skin you can use this:
> 
> ```css-scss
> // Bootstrap
> // ---------------------------------------------------
> @import '~bootstrap/scss/functions';
> @import '~admin-lte/build/scss/bootstrap-variables';
> @import '~bootstrap/scss/mixins';
> 
> $company: #00FF00;
> 
> .btn-company {
>     @include button-variant($company, $company);
> }
> ```

using this in version 3.2 and compiling - getting an error 

Message:
    node_modules/admin-lte/build/scss/_root.scss
Error: Undefined variable.
@each $color, $value in $colors-alt {
                             ^^^^^^^^^^^
  node_modules/admin-lte/build/scss/_root.scss 4:29             @content
  node_modules/admin-lte/build/scss/mixins/_dark-mode.scss 8:7  dark-mode()
  node_modules/admin-lte/build/scss/_root.scss 1:1              @import
  node_modules/admin-lte/build/scss/parts/_core.scss 5:9        @import

Please help here

**Comment by antonioalexl** [comment]
I have the same problem. Could anyone help?

**Comment by semanticfire** [comment]
I think it is because 3.2.0 added a set of other colors, meanwhile I've updated my stylesheets like this:

``` css
/*!
 *   AdminLTE v3.2.0
 *   Author: Colorlib
 *   Website: AdminLTE.io <http://adminlte.io>
 *   License: Open source - MIT <http://opensource.org/licenses/MIT>
 */

// Bootstrap
// ---------------------------------------------------
$primary:   #F08E16 !default;
$danger:    #a80d0d !default;
$warning:   #FDB90D !default;
$success:   #29A44B !default;
$secondary: #66a8c1 !default;
$dark:      #595959 !default;

$primary-alt:   #F08E16 !default;
$danger-alt:    #a80d0d !default;
$warning-alt:   #FDB90D !default;
$success-alt:   #29A44B !default;
$secondary-alt: #66a8c1 !default;
$info-alt: #66a8c1 !default;
$dark-alt:      #595959 !default;

@import '~bootstrap/scss/_functions';
@import '~admin-lte/build/scss/_bootstrap-variables';

$fgmain: #e78610;
$fgdark: #575756;
$theme-colors: map-merge((
    'fgmain': $fgmain,
    'fgdark': $fgdark,
), $theme-colors);

$colors-alt: map-merge((
    'fgmain': $fgmain,
    'fgdark': $fgdark,
), $theme-colors);

$theme-colors-alt: map-merge((
    'fgmain': $fgmain,
    'fgdark': $fgdark,
), $theme-colors);


/* CSS 
--color1: hsla(33%, 93%, 91%, 1);
--color2: hsla(249%, 81%, 49%, 1);
--color3: hsla(176%, 100%, 75%, 1);
--color4: hsla(195%, 80%, 49%, 1);
--color5: hsla(0%, 96%, 64%, 1);
--color6: hsla(355%, 65%, 24%, 1);
--color7: hsla(180%, 10%, 33%, 1);

/* HEX 
$color1: #e78610ff;
$color2: #27187eff;
$color3: #00bfb2ff;
$color4: #19647eff;
$color5: #a40606ff;
$color6: #3c1518ff;
$color7: #4c5454ff;

/* HSL 
$color1: hsla(33%, 93%, 91%, 1);
$color2: hsla(249%, 81%, 49%, 1);
$color3: hsla(176%, 100%, 75%, 1);
$color4: hsla(195%, 80%, 49%, 1);
$color5: hsla(0%, 96%, 64%, 1);
$color6: hsla(355%, 65%, 24%, 1);
$color7: hsla(180%, 10%, 33%, 1);

/* RGB 
$color1: rgba(231, 134, 16, 1);
$color2: rgba(39, 24, 126, 1);
$color3: rgba(0, 191, 178, 1);
$color4: rgba(25, 100, 126, 1);
$color5: rgba(164, 6, 6, 1);
$color6: rgba(60, 21, 24, 1);
$color7: rgba(76, 84, 84, 1);


// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/build/scss/_variables';
@import '~admin-lte/build/scss/_mixins';

@import '~bootstrap/scss/bootstrap';


@import '~admin-lte/build/scss/parts/core';
@import '~admin-lte/build/scss/parts/components';
@import '~admin-lte/build/scss/parts/extra-components';
@import '~admin-lte/build/scss/parts/pages';
@import '~admin-lte/build/scss/parts/plugins';
@import '~admin-lte/build/scss/parts/miscellaneous';
```
