### ISSUE TITLE
Add Fontawesome-iconpicker as plugin 

### ISSUE THREAD

**Issue by semanticfire** [ColorlibHQ/AdminLTE#2688]
**Is your feature request related to a problem? Please describe.**
In our use case people can select FA icons for menu items, a icon selector like fontawesome-iconpicker would be helpfull

**Describe the solution you'd like**
Add https://github.com/itsjavi/fontawesome-iconpicker as plugin

**Describe alternatives you've considered**
Manually adding it in the projects that need it

**Comment by REJack** [comment]
I'm not happy to add new plugins based on jQuery. 
But I will look for a jQuery less plugin for this, when I add new plugins with v3.1.

**Comment by REJack** [comment]
I've looked over fontawesome-iconpicker and it's not maintained anymore from this point it will not added to AdminLTE.
