### ISSUE TITLE
[BUG]when both use sidebar-collapse and layout-boxed the aside slide can not hide

### ISSUE THREAD

**Issue by bigxu** [ColorlibHQ/AdminLTE#2691]
**Describe the bug**
`<body class="hold-transition sidebar-collapse layout-boxed">`
the aside can not hide.
![Selection_091](https://user-images.githubusercontent.com/1390215/82197797-fd45a780-992d-11ea-9f72-826e81854513.png)
![Selection_092](https://user-images.githubusercontent.com/1390215/82197789-fb7be400-992d-11ea-946f-8132c5e346af.png)

**Comment by REJack** [comment]
I've added a fix for this in the master branch, it will published with the next release.

**Comment by bigxu** [comment]
> I've added a fix for this in the master branch, it will published with the next release.

Thank you very much ~~ ^_^. 
 You help me a lot

**Comment by bigxu** [comment]
fixed at: fbe0340eb0aa2088951397acba894daac0b43f44

**Comment by XhmikosR** [comment]
@REJack @bigxu FYI something broke boxed layout and collapsed sidebar on hover on v3.0.5:

<img src="https://user-images.githubusercontent.com/349621/82488871-5c9be700-9ae9-11ea-9b0f-2f4f6793f7f9.jpg" alt="2020-05-20_22-28-21" width="450">

v3.0.4 is fine.
