### ISSUE TITLE
Can we run default page as login instead of index.html and Is that possible to call an external REST api in it?

### ISSUE THREAD

**Issue by jayna456** [ColorlibHQ/AdminLTE#2692]
I am able to successfully installed and run admin-lte in my node js project. I found that pages are loading from node_modules/admin-lte. But I don't know how can I make the default page as login page not index,html.

I did not find that where is the default page is running!!!!

And more over i made login api and want to call that api while user doing login. How can I call that login api from login.html page??

Please help me out!!!

**Comment by REJack** [comment]
The Pages that comes with AdminLTE have no functions they are only as a Demo how to build the login, etc. It's also not recommend to use these pages directly from the node_modules folder, if you want to use these files copy them to your main resources then you can modify the login to use api calls.

The default page is set from your web server (e.g. nodejs express), you should not use AdminLTE's browsersync for this.

**Comment by jayna456** [comment]
yea.. I got this.. @REJack thank you for your response.. :)
