### ISSUE TITLE
[INFO] ASP.NET Boilerplate startup template uses AdminLTE v3

### ISSUE THREAD

**Issue by iyilm4z** [ColorlibHQ/AdminLTE#2693]
[ASP.NET Boilerplate](https://aspnetboilerplate.com) is a general purpose application framework especially designed for new modern web applications. It uses already familiar tools and implements best practices around them to provide you a SOLID development experience.

[Here](https://github.com/aspnetboilerplate/aspnetboilerplate) is framework repo and [here](https://github.com/aspnetboilerplate/module-zero-core-template) is startup repo of ASP.NET Boilerplate uses AdminLTE v3! I'm really so happy for taking role of making this job done.

Could we please add this info to [implementations](https://adminlte.io/docs/3.0/implementations.html) part of documents?

**Comment by REJack** [comment]
I'll add this soon into the docs.

**Comment by iyilm4z** [comment]
@REJack thank you.

**Comment by REJack** [comment]
It's added with cad5566d67876f0e1bd8eb1393931f7962e9fe5a
