### ISSUE TITLE
which file contains the code to edit btnToggle() on the sidnav component in AdminLTE

### ISSUE THREAD

**Issue by DariusDarvish** [ColorlibHQ/AdminLTE#2694]
I am trying to input this code into my Angular project which directory should I place it in? 

var url = window.location;

$('ul.sidebar-menu a').filter(function() {
	 return this.href == url;
}).parent().addClass('active');

$('ul.treeview-menu a').filter(function() {
	 return this.href == url;
}).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');

I copied the from https://github.com/ColorlibHQ/AdminLTE/issues/1806 courtesy 
of REJack

**Comment by REJack** [comment]
If I'm correct you should add this code in ngOnInit().
