### ISSUE TITLE
How to separate the two links 

### ISSUE THREAD

**Issue by yuriuss** [ColorlibHQ/AdminLTE#2695]
Hi!

I didn't find a solution that would separate the two links in the <li></li> tags, example:
```
<ul class="navbar-nav ml-auto">
   <li class="nav-item">
          <a class="btn btn-outline-primary btn-sm" href="/login">Sign In</a>
   </li>
   <li class="nav-item">
          <a class="btn btn-primary btn-sm" href="/signup">Sign Up</a>
   </li>
</ul>
```
![Screenshot_20200521_142722](https://user-images.githubusercontent.com/2412098/82555306-340b0000-9b70-11ea-81e5-4c676018bc99.png)

What is the best way to make sure that there is a normal space between the two link buttons?

**Comment by REJack** [comment]
Try to place both buttons in one li or add to the first button `mr-1` or `mr-2` class.
