### ISSUE TITLE
[BUG] Bootstrap Switch locked at 3.3.4

### ISSUE THREAD

**Issue by tacman** [ColorlibHQ/AdminLTE#2696]
bootstrap-switch "3.3.4"

https://github.com/ColorlibHQ/AdminLTE/blob/master/package.json#L81

This generates a warning:

    warning "admin-lte > bootstrap-switch@3.3.4" has incorrect peer dependency "bootstrap@^3.1.1".

Is there a reason it's locked at 3.3.4?  Can it be bumped to ^3.4, since this is bootstrap 4 only?

**Comment by REJack** [comment]
We used bootstrap-switch 3.4 but there are massive compile bugs/errors and that’s why we use bootstrap-switch 3.3.4. Also bootstrap-switch isn’t maintained at the moment, may there is a better alternative.
