### ISSUE TITLE
[BUG] Treeview plugin issue when having multiple menus in the same page

### ISSUE THREAD

**Issue by fl0v** [ColorlibHQ/AdminLTE#2698]
**Describe the bug**
Using the data-widget="treeview" more then once in the same page leads to setting multiple listeners for click event on $(document). As a result some issues will apear after expanding a multilevel menu.

**To Reproduce**
Have 2 dropdown menus in the same page, both having data-widget='treeview' and atleast one with more then 1 level.

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.5
 - Browser (Version): Chrome (Latest)

**Additional context**
In Treeview.js the Data API hook will call the init() function for each element selected by Selector.DATA_WIDGET.
https://github.com/ColorlibHQ/AdminLTE/blob/6b8b69261f1aacbb4be037c934f3c3652e6dff27/build/js/Treeview.js#L159-L168

And the plugin init() function will call _setupListeners which will capture the click event on all document.
https://github.com/ColorlibHQ/AdminLTE/blob/6b8b69261f1aacbb4be037c934f3c3652e6dff27/build/js/Treeview.js#L62-L64
https://github.com/ColorlibHQ/AdminLTE/blob/6b8b69261f1aacbb4be037c934f3c3652e6dff27/build/js/Treeview.js#L128-L132

**Possible solution**
I think there should be a check in _setupListeners() to make sure the event is captured only once.

**Comment by REJack** [comment]
I understand what you mean, but the Treeview Plugin isn’t designed to use multiple treeviews with the same data-widget. I can look over it while I create AdminLTE v3.1.
