### ISSUE TITLE
where is the Data tables js code?

### ISSUE THREAD

**Issue by arwivi1903** [ColorlibHQ/AdminLTE#2699]
![327C6E11-4F75-41F3-B8E5-2ADAE7AD4B34](https://user-images.githubusercontent.com/57416151/82953396-6030e180-9fb3-11ea-9b6c-324ef3f8bf36.png)

Show  10-25-50-1000 entries
And
Showing 1 to 10 of 57 entries

I want to make the "Show -  Showing - to - entries" text sections in Turkish.  where do i change?  Could you help?

**Comment by REJack** [comment]
For this please checkout the DataTable's Docs.

**Comment by arwivi1903** [comment]
ok thanks.
