### ISSUE TITLE
[BUG] .small-box should use a transform instead of transitioning the font-size

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2702]
**Describe the bug**

`.small-box` should use a `transform` instead of transitioning the `font-size`

https://github.com/ColorlibHQ/AdminLTE/blob/6b8b69261f1aacbb4be037c934f3c3652e6dff27/build/scss/_small-box.scss#L104

https://github.com/ColorlibHQ/AdminLTE/blob/6b8b69261f1aacbb4be037c934f3c3652e6dff27/build/scss/_small-box.scss#L125

https://github.com/ColorlibHQ/AdminLTE/blob/6b8b69261f1aacbb4be037c934f3c3652e6dff27/build/scss/_small-box.scss#L133

**Environment (please complete the following information):**

 - AdminLTE Version: 3.0.5

**Additional context**

Transitioning transforms is more performant that the font-size.

Initially I did it in https://github.com/pi-hole/AdminLTE/pull/1386 but since it's present in AdminLTE latest, I thought I'd make an issue so that it's fixed properly upstream.

**Comment by REJack** [comment]
Thats a nice idea, I'll update this soon. It's also nice to see that Pi-hole updates to AdminLTE v3 😄.

**Comment by XhmikosR** [comment]
> It's also nice to see that Pi-hole updates to AdminLTE v3 😄.

I decided to do it because Bootstrap 3.x is so limiting. 🙂 WIP branch https://github.com/pi-hole/AdminLTE/compare/devel...adminlte-3?w=1

BTW you should go through the codebase for other cases where you transition properties that shouldn't be transitioned because they are bad for performance.

**Comment by XhmikosR** [comment]
For example I see many cases where padding/margin/margin-left/width/top/left/right is transitioned. That's not very performant. It's OK in some cases to do it like `a` elements, but for big elements like the sidebar this can be problematic.

Also, generally try to avoid `transition: all ...` and be specific about which properties are transitioned.

I hope you don't mind making these suggestions 🙂

**Comment by REJack** [comment]
I've changed the transition to transform for the small-box in da47f231453c7589b41abc2a28b412a653c6d3e6.


> For example I see many cases where padding/margin/margin-left/width/top/left/right is transitioned. That's not very performant. It's OK in some cases to do it like a elements, but for big elements like the sidebar this can be problematic.

I'll look over this while the v4 changes, that's a bigger point or some one create a PR for it then I push it to v3.1 😄 

> Also, generally try to avoid transition: all ... and be specific about which properties are transitioned.

That's a good point, I'll look over it while the v3.1 changes.

**Comment by XhmikosR** [comment]
The thing is I'm not 100% familiar with your codebase, so I'd rather not make these changes myself. :)

It's not super urgent but it should be addressed because it really is bad for performance.

**Comment by XhmikosR** [comment]
I opened #2719 to track the remaining stuff, closing this since a patch has landed on master :)
