### ISSUE TITLE
[BUG] v3.0.5 boxed layout collapsed sidebar regression

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2703]
v3.0.5 boxed layout does not show hovered sidebar items properly. A regression from https://github.com/ColorlibHQ/AdminLTE/commit/fbe0340eb0aa2088951397acba894daac0b43f44 due to the `z-index` change

**To Reproduce**
1. Toggle boxed layout
2. Collapse sidebar
3. Hover over sidebar

**Screenshots**

<img src="https://user-images.githubusercontent.com/349621/83064767-00960d00-a06b-11ea-97fc-81129a185f30.jpg" alt="2020-05-27_22-37-40" width="450">

**Environment (please complete the following information):**
 - AdminLTE Version: 3.0.5
 - Operating System:  Windows
 - Browser (Version): Firefox latest

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll fix this soon.

**Comment by REJack** [comment]
It's fixed with c2e77427ba9c3d498e60cc2353a36c3f9d876259 😄

**Comment by XhmikosR** [comment]
@REJack https://github.com/ColorlibHQ/AdminLTE/commit/c2e77427ba9c3d498e60cc2353a36c3f9d876259#commitcomment-39562707

**Comment by XhmikosR** [comment]
So, @REJack the above needs to be fixed, right?

**Comment by REJack** [comment]
Still open? 😄

**Comment by pauldbentley** [comment]
Is there an ETA on the release for this?  Thanks

**Comment by XhmikosR** [comment]
Closing since it was fixed in https://github.com/ColorlibHQ/AdminLTE/commit/c2e77427ba9c3d498e60cc2353a36c3f9d876259

@pauldbentley you could downgrade to 3.0.4 until there's a new version out
