### ISSUE TITLE
[FEATURE] switch to string constants in JS

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2704]
I recently did this on Bootstrap itself for both our master and v4-dev branches.

* https://github.com/twbs/bootstrap/pull/30358
* https://github.com/twbs/bootstrap/pull/30490

@REJack As you can see the results are pretty big. 🙂

Would be nice if you made the change on AdminLTE itself.

PS. we have released a v4.5.0 upstream, but there are a couple of [regressions](https://github.com/twbs/bootstrap/issues?q=is%3Aopen+is%3Aissue+label%3Aregression) we have to fix. After v4.5.1 is out, you should definitely update to that.

**Comment by REJack** [comment]
That's a really nice idea, I had also the idea to replace the constants before. But I saw no benefit from it, but now I see it reduces the JS file size 😄. I'll change while the v3.1 development.

**Comment by XhmikosR** [comment]
I'll take a stab at it after the current PRs are sorted. Have you thought about adding bundlewatch to monitor the sizes?
