### ISSUE TITLE
[BUG] Update jQuery to v3.5.1

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2714]
I'm marking it as a bug due to the security fixes it includes.

That being said, every plugin should be tested, see if there are any plugin updates and make them. I started updating some dependencies, for example #2713 which has some fixes for jQuery 3.x. I'll probably don't have the time to update the rest, but it should be done nonetheless :)

**Comment by REJack** [comment]
I'll look over the plugins in the next days, I would say the most of them should work without any problem.
