### ISSUE TITLE
[BUG] sidebar item icon transition

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2729]
When clicking on a sidebar item with `fa-angle-left`, it rotates after the menu item is full expanded/collapsed.

This feels a little unnatural. See the sidebar items here to see how it should behave: https://twbs-bootstrap.netlify.app/docs/5.0/getting-started/introduction/

This is also present in v2.x but I assume that's no longer maintained, right?

**Comment by REJack** [comment]
I know but I was too lazy to change this 🤣 

Yep v2.x isn't maintained anymore.

**Comment by REJack** [comment]
I added fix for this in the fix-sidebar-item-icon-transition branch 😄 This should work without any markup changes.

**Comment by XhmikosR** [comment]
@REJack it seems the card widget has the same issue with the collapse minimize/maximize icon.

I didn't check any other places but there might be more.

**Comment by REJack** [comment]
This issue look like it's fixed, the card widget icons (collapse/minimize/maximize icon) have no delay like the sidebar icons had.
