### ISSUE TITLE
[FEATURE] run node-sass less times

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2734]
It's marginally faster, see https://github.com/twbs/bootstrap/blob/master/package.json#L24

The only issue is the different output dir you have, but I guess you could run node-sass twice instead of 6 times :)

**Comment by REJack** [comment]
The problem is that we can only compile it to one file and not to multiple in one run. That's why i created multiple scripts for it, but I've created a new script for this to reduce the npm script lines 😄 the RTL support would blow up the npm scripts.

**Comment by XhmikosR** [comment]
You can compile multiple files, that's what we are doing upstream :)

**Comment by REJack** [comment]
Whuut I've tested it but it generated only one css file at the end, may you can create a PR for this too 😄

**Comment by XhmikosR** [comment]
The multiple targets along with #2725 makes it hard for me, but I can try later.

**Comment by XhmikosR** [comment]
@REJack the proper way would be this: https://github.com/ColorlibHQ/AdminLTE/compare/master...XhmikosR:scss-refactoring

But this is a breaking change.

**Comment by REJack** [comment]
> @REJack the proper way would be this: master...XhmikosR:scss-refactoring

This is a kind of change for v3.1 or even for v4.

**Comment by XhmikosR** [comment]
What do you mean push to v3.1? I can make a PR if you want.

**Comment by REJack** [comment]
A PR would be great 😄
