### ISSUE TITLE
Implementation in nuxtjs

### ISSUE THREAD

**Issue by VinceSanityyy** [ColorlibHQ/AdminLTE#2782]
**Is your feature request related to a problem? Please describe.**
Implement in nuxt

**Describe the solution you'd like**
Do you have any instructions how can I implement this template in my nuxt js project?

**Describe alternatives you've considered**
Right now i am using bootstrap

**Comment by VinceSanityyy** [comment]
@REJack I found a nuxtjs with adminLTE 3. https://github.com/ppraserts/nuxtjs-adminlte-101. Is this the right one to do it?

**Comment by REJack** [comment]
I didn't used nuxtjs but it looks ok ^^ you need to try if the sidebar and treeview works, that are the important parts 😄

**Comment by VinceSanityyy** [comment]
yah but it has jquery on it. is it okay to use it with nuxt/vue? @REJack

**Comment by REJack** [comment]
You won't get around jQuery, AdminLTE itself use it as a dependency and VueJS has not problem with jQuery itself. You can get rid of it with AdminLTE v4 there we gonna drop the jQuery dependency 😄.

**Comment by VinceSanityyy** [comment]
okay thanks @REJack
