### ISSUE TITLE
Bootstrap bg-gradient-variant deprecated

### ISSUE THREAD

**Issue by bobvandevijver** [ColorlibHQ/AdminLTE#2786]
The bootstrap `bg-gradient-variant` mixin is deprecated since v4.5.0, so we should probably look for an alternative here.

```
WARNING: The `bg-gradient-variant` mixin has been deprecated as of v4.5.0. It will be removed entirely in v5.
         on line 8 of node_modules/bootstrap/scss/mixins/_deprecate.scss, in mixin `deprecate`
         from line 22 of node_modules/bootstrap/scss/mixins/_background-variant.scss, in mixin `bg-gradient-variant`
         from line 58 of node_modules/admin-lte/build/scss/mixins/_backgrounds.scss, in mixin `background-gradient-variant`
         from line 42 of node_modules/admin-lte/build/scss/_colors.scss
         from line 9 of node_modules/admin-lte/build/scss/parts/_miscellaneous.scss
         from line 23 of node_modules/admin-lte/build/scss/AdminLTE.scss
         from line 9 of stdin
```

**Comment by REJack** [comment]
This warning is known, but we wait for Bootstrap 3.5.1 then I will fix it while updating to Bootstrap v3.5.1.

**Comment by REJack** [comment]
I've looked over the code and there is no quick fix for this. We can only remove it, but this would cause breaks by users they use the gradient's. 

We can only remove this warning with Bootstrap 5 since they replaced the `bg-gradient-*` classes with one `bg-gradient` class.
> The bg-gradient-variant() mixin is removed since the .bg-gradient class can now be used to add gradients to elements instead of the .bg-gradient-* classes.

Also I don't know if there is any option to supress this warning :/

**Comment by bobvandevijver** [comment]
We could maybe copy the implementation of bootstrap to this repository, without the deprecation notice (but marking it as internal, is that easy with scss? 🤔). That way, AdminLTE wouldn't generate the warnings itself, but when a user uses it directly from bootstrap, they will still get the warning (as they should).

I do assume that the new bootstrap major also implies a new AdminLTE major, which gives you the possibility to mark the copy as only available in the current version in order to suppress the warnings.

**Comment by bobvandevijver** [comment]
@REJack I see the related MR has been reverted, does this needs to be reopened?

**Comment by brianrlewis** [comment]
Any update on this?

**Comment by santiagoapp** [comment]
> I've looked over the code and there is no quick fix for this. We can only remove it, but this would cause breaks by users they use the gradient's.
> 
> We can only remove this warning with Bootstrap 5 since they replaced the `bg-gradient-*` classes with one `bg-gradient` class.
> 
> > The bg-gradient-variant() mixin is removed since the .bg-gradient class can now be used to add gradients to elements instead of the .bg-gradient-* classes.
> 
> Also I don't know if there is any option to supress this warning :/

This worked for me, thanks!

**Comment by bobvandevijver** [comment]
Looks like #3040 fixed this, but there is no stable release available (yet)

**Comment by moqska** [comment]
> I've looked over the code and there is no quick fix for this. We can only remove it, but this would cause breaks by users they use the gradient's.
> 
> We can only remove this warning with Bootstrap 5 since they replaced the `bg-gradient-*` classes with one `bg-gradient` class.
> 
> > The bg-gradient-variant() mixin is removed since the .bg-gradient class can now be used to add gradients to elements instead of the .bg-gradient-* classes.
> 
> Also I don't know if there is any option to supress this warning :/

I've found the Bootstrap variable to suppress deprecated warnings and it's working, although it is clearly a bad and risky practice in the long-term.
`$enable-deprecation-messages: false;`
