### ISSUE TITLE
[BUG] Question AdminLTE 2

### ISSUE THREAD

**Issue by andriux1990** [ColorlibHQ/AdminLTE#2793]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [e.g. macOS Catalina]
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

this is not an issue .. i just want to know if adminLTE 2 has stopped having support

**Comment by REJack** [comment]
You can still get support here, but the maintenance of AdminLTE v2 is stopped months ago.
