### ISSUE TITLE
[BUG] Move demo{1,2,3}.js files after 3rd-party JS files

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2806]
Since it's custom code, it should come after 3rd-party JS files.

Also, remove demo.js from pages that don't need it, see #2805, #2802

**Comment by REJack** [comment]
the demo.js fills the control siderbar (right) with the customization options (css classes), everywhere we load it the control sidebar will filled up.

**Comment by XhmikosR** [comment]
Alright, still it should come after all 3rd-party scripts :)
