### ISSUE TITLE
[BUG] Remove flot-old

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2807]
Not sure what the history behind this is, but there are 2 instances of flot right now. So, someone who installs via npm will get flot, but all the others will get flot-old.

This should be cleared up, and also removed from .npmignore.

**Comment by REJack** [comment]
We use flot-old on the flot.html demo page, since they removed some of the flot chart types. But we can remove it.

**Comment by XhmikosR** [comment]
As long as the examples work properly, this should be cleaner.
