### ISSUE TITLE
[FEATURE] Scss: use the mixins whenever possible

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2819]
There's a stylelint rule that could be leveraged to blacklist certain properties, like transition, and instead the mixin will need to be used.

This will ensure consistency.

Also, might be a good chance to deduplicate any mixins. Some may be available upstream.

**Comment by REJack** [comment]
@XhmikosR I move this and other of your issues to v4 to release soon v3.1, we can takle these issues directly on rework the scss codebase.
