### ISSUE TITLE
[BUG] DataTable pagination button does not responsive on mobile layout 

### ISSUE THREAD

**Issue by quannetwork** [ColorlibHQ/AdminLTE#2821]
If you adjust the screen width below 370px, the pagination buttons do not collapse.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/pages/tables/data.html
2. Turn on Chrome Dev mode
3.  Adjust the screen width below 370px

**Screenshots**
![2020-06-07_19-23](https://user-images.githubusercontent.com/8580008/83968581-6e0c2e00-a8f4-11ea-9075-1481e454fe8b.png)

**Environment (please complete the following information):**
- AdminLTE Version: latest
- Operating System: Ubuntu 18.04
- Browser (Version): Chrome (Latest)

**Comment by quannetwork** [comment]
Update: this problem already discussed on [this post](https://datatables.net/forums/discussion/50818/responsive-paging-buttons-datatables-bootstrap-4)

**Comment by REJack** [comment]
You can also override the amount of numbers showing with 
```js
$.fn.DataTable.ext.pager.numbers_length = 5;
```

I would not add a fix for this, to give the users the control over the style.
