### ISSUE TITLE
[QUESTION] Can I change the Coppyright sign at the footer?

### ISSUE THREAD

**Issue by Magniplayz** [ColorlibHQ/AdminLTE#2826]
Can I change the Coppyright sign at the footer? or i have to buy the premium version if its possible?

**Comment by REJack** [comment]
Yes you can remove/change it, the copyright at the footer is not required for the legals. 

P.S. There is no Premium Version of AdminLTE.

**Comment by Magniplayz** [comment]
Thanks for the information sir
