### ISSUE TITLE
Default sidebar to collapsed on medium browser

### ISSUE THREAD

**Issue by pauldbentley** [ColorlibHQ/AdminLTE#2828]
**Is your feature request related to a problem? Please describe.**
On a medium browsers, on page load the sidebar is visible, then slides off screen.  This often looks strange when users click a link on the page.

For small it seems to work (although the elevation drop shadow does show for a second and then goes but I can live with that)

**Describe the solution you'd like**
Is there a way to make it so the sidebar starts as collasped so we don't see it slide off to the side for medium?

**Describe alternatives you've considered**
I've tried combinations of sidebar-closed sidebar-collapse, but can't get it to work how I want for medium.

**Comment by REJack** [comment]
For the Sidebar is no difference between Medium Sized Screens and Large Screens, both work the same way. Did you tried to add `.sidebar-collapse` to body and load the page with it? 

Also which width is for you Medium? If its <992px then it’s may come from the JS (from the Aufo-Collaspe or the State-Remeber feature).

**Comment by pauldbentley** [comment]
Here is an example of the behavior from the [demo dashboard 1](https://adminlte.io/themes/v3/index3.html) with my broswer at 800px wide and I click the "Home" link in the nav.

![adminlte-menu](https://user-images.githubusercontent.com/5243982/84487059-1ffd7e80-ac96-11ea-8f82-4a2914181dec.gif)

So the sidebar is hiding at <992px, but then slides out on every page load afterwards

**Comment by REJack** [comment]
That's default behavior if the sidebar isn't collapsed, since we close it via js after DOM is loaded.
You can disable the auto close feature if you want to.
