### ISSUE TITLE
[FEATURE] Improve plugins copy scripts

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2833]
Right now folders or individual files are copied.

Ideally, regex should be allowed to be used for example `foobar/*.{css,js}`. This would make .gitignore clearer and the whole operation faster.

**Comment by danny007in** [comment]
can we make 
 parallel copying the folders in the loop `Promise.all`

**Comment by danny007in** [comment]
closing this issue, because in AdminLTE v4 plugins are cdn
