### ISSUE TITLE
maximized-card does not scroll the content

### ISSUE THREAD

**Issue by 77media-creations** [ColorlibHQ/AdminLTE#2840]
**Describe the bug**
If a div card is applied the class 'maximized-card', it goes full screen as expected but if the content of the card is longer than the screen height, it does not scroll the content instead shows whatever is covered in the full screen.

**To Reproduce**
1. Create a <div class="card">
2. Fill up the card with some data/content (enough to let you scroll to view the whole lot)
3. View the page in browser (chrome)
4. Add the class "maximized-card" to the div from the devtools
5. Now the div will be in fullscreen mode but the content is not scrollable

**Expected behavior**
Content longer than the screen height should scroll.

**Environment (please complete the following information):**
- AdminLTE Version: [v3.0.5]
- Operating System:  [e.g. macOS Catalina 10.15.3]
- Browser (Version): [e.g. Chrome (Latest)]

**Comment by FurmigaHumana** [comment]
.card.maximized-card {
    overflow: scroll;
}

**Comment by 77media-creations** [comment]
@FurmigaHumana: thanks for the suggestion, but it makes the footer stick at around middle of the screen. Please have a look on the attached gif.
![screen](https://user-images.githubusercontent.com/51688338/84906302-14c2ac80-b0f5-11ea-8854-0c215e83f007.gif)

**Comment by REJack** [comment]
You should only give the card body overflow scroll like this
```css
.card.maximized-card .card-body {
    overflow: scroll;
}
```
