### ISSUE TITLE
Hello I am facing with small issue , Dropdown menu [BUG]

### ISSUE THREAD

**Issue by onbica** [ColorlibHQ/AdminLTE#2842]
Hello,
How can i use `dropdown-menu-sm` under the main navbar of `nav-item dropdown user-menu`, It doesn't work for me here, Thanks

![image](https://user-images.githubusercontent.com/62180549/84584561-f70ef200-ae2b-11ea-925b-4e9b62869d78.png)

![image](https://user-images.githubusercontent.com/62180549/84584442-887d6480-ae2a-11ea-954d-e632359380a7.png)

**Comment by REJack** [comment]
There is no issue with the dropdown user-menu.

1. there is no class called `dropdown-menu-sm`, only `dropdown-menu-sm-(left|right)`.
2. the user-menu is fixed to `280px` width, you can override this with the `w-100` class.

**Comment by onbica** [comment]
Hi,
Thanks for Reply , When i try to overide class with `w-100` , it does't give me correct style , Thanks agian 
![image](https://user-images.githubusercontent.com/62180549/84599960-df6f5200-ae9b-11ea-9cde-6cb5f90d5cc0.png)
