### ISSUE TITLE
[HELP] Installation via Laravel

### ISSUE THREAD

**Issue by jamols09** [ColorlibHQ/AdminLTE#2845]
I have installed AdminLTE via this command `npm install admin-lte@^3.0 --save`  on my project path, upon copying the code under the 'node_module' folder and pasting on the views folder on app.blade.php the theme does not show anything.

**Comment by REJack** [comment]
That's not a AdminLTE related problem, you need to check how to load correctly the assets via your blade file and make sure that you copied the dist files to the `public` folder, but you can also test [Laravel-AdminLTE](https://github.com/jeroennoten/Laravel-AdminLTE) it has great features and work with any AdminLTE v3 version.
