### ISSUE TITLE
[FEATURE] Contextual classes for Application buttons

### ISSUE THREAD

**Issue by MacGyer** [ColorlibHQ/AdminLTE#2846]
**Is your feature request related to a problem? Please describe.**
Application buttons `.btn-app` cannot be used in combination with contextual classes (e. g. `primary`, `danger` etc.)

**Describe the solution you'd like**
Add the possibility to apply contextual classes to `.btn-app` like `.btn-app-danger`. (see `btn-outline-danger`).

Thanks.

**Comment by REJack** [comment]
In order to use a custom color with the `.btn-app` you can simply add `bg-danger` or any other theme color variations like this example.

![grafik](https://user-images.githubusercontent.com/1554582/87875200-db20e200-c9cf-11ea-95ac-8f5e6812e8a2.png)
