### ISSUE TITLE
Dynamic recursion tree menu

### ISSUE THREAD

**Issue by ZhangQueque** [ColorlibHQ/AdminLTE#2847]
**Is your feature request related to a problem? Please describe.**
Whenever I dynamically generate a menu bar, there's no recursive method,

**Describe the solution you'd like**
So I wrote a recursive JS script where the API just returns the data in the form of (ID, name, PID)

**Describe alternatives you've considered**
So I wrote a recursive JS script where the API just returns the data in the form of (ID, name, PID)

**Additional context**
 
![image](https://user-images.githubusercontent.com/61497473/84966442-254e4380-b144-11ea-86d3-547c28f8107f.png)

[This is the JS script](https://www.zhangqueque.top:99/adminLTETreeBase.js)

**Comment by ZhangQueque** [comment]
<ul class="sidebar-menu" id="Menu"></ui>

**Comment by mesut777** [comment]
the script url that you provided doesn't work. can you please share it ?

**Comment by ZhangQueque** [comment]
https://github.com/ZhangQueque/CRM_MVC/blob/master/BT.MVC/wwwroot/js/adminLTETree.js @mesut777
