### ISSUE TITLE
Carregamento de Plugins

### ISSUE THREAD

**Issue by CosmeDaniel** [ColorlibHQ/AdminLTE#2848]
How do I know which Plugin is used for each component on the AdminLTE3 pages, to only load the necessary plugins?
Example: DataTables - for tables, FullCalendar 4 - for calendar. FastClick - For which component? jQuery Knob - For which component? And so for all other Plugins. I have this difficulty using AdminLTE3.

**Comment by tikky** [comment]
I think you should not ask for help here. This is an issue tracker.
But maybe you can find some information here: https://adminlte.io/docs/3.0/dependencies.html

**Comment by REJack** [comment]
There are several ways to check this, 1. look over the source code and check where the JS get initialized 2. check the code styles with the browser dev tools.

Also please ask questions like this on stackoverflow, there you get faster help for such questions.
