### ISSUE TITLE
BUG - sidebar menu needs two click on iOS

### ISSUE THREAD

**Issue by tikky** [ColorlibHQ/AdminLTE#2853]
On Safari Mobile, if you click on sidebar icon and then one of the menu option, instead of click and go to the link, you have strange behavior. Button seems to be clicked because background color is grey, but you need to make additional click (touch) to make the link opened. 

Steps to reproduce on iPhone. 
1. Open Safari and go to, for example: [https://adminlte.io/themes/v3/index.html](https://adminlte.io/themes/v3/index.html)
2. Click to open left sidebar
3. Click "Dashboard 2"
 - **now instead of going to "Dashboard2" we can see only backround change to grey and this seems to be a bug**
4. If you will click one more time on the same button ("Dashboard2") then you will go to the new page

So expected result after step 2 is step 4 (without step3).

_Additional tests:_
What is more interesting problem is visible if I am going from index.html to index2.html (or index3.html)
but if I am on index3 and clicking on index.html seems to be ok.

**Comment by tikky** [comment]
![3BD80BA9-8496-4592-8215-84E829DAB89E](https://user-images.githubusercontent.com/546755/85605598-99ac4980-b652-11ea-851f-5e745b3081fb.gif)

**Comment by tikky** [comment]
I've made additional tests:

- iOS Safari problem is visible
- Chrome on Android phone - it works fine
- Opera Touch on iOS also problem is visible

**Comment by REJack** [comment]
I've tested it and its looks like the OverlayScrollbars cause this weird bug, you can get rid of this with adding the fastclick polyfill.

```html
<script src="plugins/fastclick/fastclick.js"></script>
<script>
  if ('addEventListener' in document) {
    document.addEventListener('DOMContentLoaded', function() {
      FastClick.attach(document.body);
    }, false);
  }
</script>
```
