### ISSUE TITLE
Is there a way for the scrollbar to always show even if the mouse pointer has left the sidebar div?

### ISSUE THREAD

**Issue by gh-supersudo** [ColorlibHQ/AdminLTE#2854]
I want the scrollbar to show when the content is expanded, and always visible unless the content is folded back that fit to browser width.

I tried changing it with this code but the scrollbar always hide when the mouse pointer left the sidebar div.
Here is the code:
```js
document.addEventListener("DOMContentLoaded", function() {
    OverlayScrollbars(document.querySelectorAll('.sidebar'), {
      sizeAutoCapable: true,
      scrollbars: {
        visibility: "visible",
        autoHide: "never",
      },
    });
});
```

I also tried it in jquery

```js
$(function() {
    $(".sidebar").overlayScrollbars({
      sizeAutoCapable: true,
      scrollbars: {
        visibility: "visible",
        autoHide: "never",
      },
    });
});
```

**Comment by REJack** [comment]
Try to add ` data-scrollbar-auto-hide="n"` on your body tag.

**Comment by gh-supersudo** [comment]
> data-scrollbar-auto-hide="n"

Thanks! It worked!
