### ISSUE TITLE
upgrade to bootstrap 5

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#2855]
will be upgraded in AdminLTE v4
 after AdminLTE v3.1.0 release

**Comment by GTANAdam** [comment]
I'm also very interested in seeing this happen in a parallel branch, thanks!

**Comment by the-provost** [comment]
Yes please. Looking forward to a parallel bootstrap 5 branch with bootstrap svg icons

**Comment by danny007in** [comment]
> Yes please. Looking forward to a parallel bootstrap 5 branch with bootstrap svg icons

Exactly,
then we no need of huge plugin called fontawesome

**Comment by medeepaksaini** [comment]
@REJack when you are planning to start working on V4 and thinking for Alpha release.

**Comment by danny007in** [comment]
> 
> 
> @REJack when you are planning to start working on V4 and thinking for Alpha release.

After v3.1.0 release

**Comment by spizzo14** [comment]
When is bootstrap 5 coming any estimate on date?

**Comment by danny007in** [comment]
> 
> 
> When is bootstrap 5 coming any estimate on date?

it will come with v4
may be takes 4 months

**Comment by leonardodepaula** [comment]
Any update on v4 development?

**Comment by danny007in** [comment]
> 
> 
> Any update on v4 development?

After AdminLTE v3.1.0 release

**Comment by spizzo14** [comment]
Can I pay or donate to get this done faster? Who's the head developer or owner of the code?

**Comment by REJack** [comment]
I'm the head dev 😄, code owner is @ColorlibHQ / @puikinsh

**Comment by medeepaksaini** [comment]
@REJack it's a long time, how are you ?

It's getting delay to release `V 3.1.0`. I think you are including all suggestions back to back before release it.

We all know it's not easy task, but is that possible to release `V 3.1.0` with exiting new features. I think it's almost done and you already released RC of this version.

So, release it and let go to V5 Beta 2 is release in few weeks its release, so i hope we can start working on it.

**Comment by REJack** [comment]
At the moment we have some small bugs from the dark mode after I fixed them i can relase v3.1.0, may i release it on friday or saturday 😄.

**Comment by medeepaksaini** [comment]
Okay 👍

**Comment by medeepaksaini** [comment]
@REJack if these are miner bugs and not causing look issues. we can fix them on bug fix release. but lets try to release it by max Saturday. I will also try to help into it to manage timeline 👍
