### ISSUE TITLE
Image Not Properly aligned on sidebar header

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#2856]
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [e.g. Windows 10]
- Browser (Version): [e.g. Chrome (Latest)]

I am trying replace the Text on the AdminLTE Sidebar header with Logo/Image

I have this code:

`    

    <aside class="main-sidebar sidebar-dark-primary elevation-3">

    

    <a href="{{ route('home') }}" class="brand-link navbar-dark bg-gray-light">

    <span class="brand-text font-weight-light">

       <img src="{{ asset('theme/adminlte3/dist/img/peopleedge_logo.png') }}" class="brand-image"
    alt="PeopleEdge">

    </span>

    <span class="brand-text font-weight-light">PeopleEdge</span>`

which gives me this:

![adminlte_image_old](https://user-images.githubusercontent.com/34077129/85749746-041bc300-b701-11ea-9f5b-6d78e8aff40e.PNG)

But I don't know to the text "PeopleEdge"

So when I removed 

`<span class="brand-text font-weight-light">PeopleEdge</span>`

From the the code, what I got is not well-aligned:

![adminlte_image_new](https://user-images.githubusercontent.com/34077129/85750098-50670300-b701-11ea-9d4a-1f385bc60a11.PNG)

How do I align the Image properly and that it will not scatter the page. Then I also want the image to be bigger, well-dimensioned and be more visible.

Thanks

**Comment by REJack** [comment]
Add `.clearfix` to `.brand-link`.

**Comment by noblemfd** [comment]
@REJack - where is .brand-link

**Comment by REJack** [comment]
```html
<a href="{{ route('home') }}" class="brand-link clearfix navbar-dark bg-gray-light">
```
