### ISSUE TITLE
[BUG] Right sidebar is not always shown correctly

### ISSUE THREAD

**Issue by caschoff** [ColorlibHQ/AdminLTE#2862]
I have a problem with the right sidebar. It is not always shown correctly. In detail, it is shown correctly if the footer is completely visible or completely out of the window. If the footer is partially visible, the right sidebar has the wrong height.

I made a video for a better demonstration:

https://cloudstore.uni-ulm.de/s/AHoeNZfPNByZsTo

I checked the html source against validator.w3.org and found no errors.

I do not think the code is intersting, if it is, it is here: https://pastebin.com/92052q4G or I can paste it here completely.

AdminLTE is 3.0.2.

Regards,
Christian

**Comment by caschoff** [comment]
Here is another example. Sidebar seems to have problems if there is not enough content (but the siedebar has a lot of content).

<img width="375" alt="Bildschirmfoto 2020-07-07 um 09 06 03" src="https://user-images.githubusercontent.com/3326657/86734181-10255000-c032-11ea-91ff-ee4141d11bb2.png">
<img width="354" alt="Bildschirmfoto 2020-07-07 um 09 06 20" src="https://user-images.githubusercontent.com/3326657/86734189-10bde680-c032-11ea-8e53-c25658a09306.png">

**Comment by REJack** [comment]
Please try AdminLTE v3.0.5 (latest).

Do you use the `layout-fixed` class on your body?

**Comment by caschoff** [comment]
I'm using `layout-fixed`. I will try AdminLTE v3.0.5 and report back, thanks.

**Comment by caschoff** [comment]
Ok, now I have AdminLTE v3.0.5 but nothing has changed :-(

**Comment by REJack** [comment]
At the moment I can't fix & publish it fast, but here is a workaround css style for this.

```
.control-sidebar-slide-open .control-sidebar,
.control-sidebar-slide-open .control-sidebar::before {
    bottom: 57px !important;
    top: 57px !important;
    height: auto !important;
}

.control-sidebar .control-sidebar-content {
    height: 100% !important;
}
```

I hope this works, I'll let this issue open to tackle it while the v3.1 development.
