### ISSUE TITLE
[FEATURE] Some combinations of side, top and footer.

### ISSUE THREAD

**Issue by arcanisgk** [ColorlibHQ/AdminLTE#2863]
allow testing with javascript of the possible configurations of the menus/bar: top, side and footer.

Options:

Top Menu:
		1. Default (Hide on scroll down web page)
		2. Fixed (Always on display)
		3. Defauld and Fixed with Box Layout.

Side Menu:
		1. Collapse: show/hiden Menu.
		2. Shrink: Capable to minimize the menu (view Only Icons)
		3. Collapse, Shrink status enable/disable by Default (option by default)
		4. Default (Scroll with Scroll content).
		5. Fixed (Always on display)
		6. IF Top menu is Fixed, put Side Menu down it, instead of on left.
		7. Scroll content of Side Menu like slimScroll.

Footer and Menu Footer:
		1. Defauld: show on scroll down at end of content.
		2. Fixed: (Always on display)
		3. Allow to add Menu Element to footer menu.

**Comment by REJack** [comment]
You mean testing with javascript, like the color options in control sidebar in the demo?

**Comment by arcanisgk** [comment]
Yes, can create a branch to do...

**Comment by REJack** [comment]
> can create a branch to do...

What you mean?

**Comment by arcanisgk** [comment]
> > can create a branch to do...
> 
> What you mean?

if you can create a branch, to download and work on them the modifications ... I think you need to work on the css, the html and javascript to get the proposed layouts ...

**Comment by REJack** [comment]
I'll look over the demo.js may I will add this with v3.1, there is no css/html needed for this the demo.js generates the whole content.

**Comment by REJack** [comment]
I've reworked the demo.js in master branch, you can check it out there are more options to modify the look.

**Comment by arcanisgk** [comment]
I will be checking very soon
