### ISSUE TITLE
Install AdminLTE via NPM - This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by mvavrina** [ColorlibHQ/AdminLTE#2865]
Hello,
i have problem to download  AdminLTE via npm. it ends in error with This is probably not a problem with npm. There is likely additional logging output above.

Can you help me please?

Thank you, Michal

**Comment by REJack** [comment]
We cant help you without the logging.

**Comment by mvavrina** [comment]
Login in Gitlab? Iam logged

**Comment by REJack** [comment]
No we need the npm log that was generated on the AdminLTE install approach.

**Comment by mvavrina** [comment]
Here is it
https://jsfiddle.net/gxc3htn7/

**Comment by REJack** [comment]
You use node v8.15.0 but you need atleast node v10.

We have for this also a note in the readme above the npm/yarn commands.
> Important Note: To install it via npm/Yarn, you need at least Node.js 10 or higher.

**Comment by mvavrina** [comment]
Thank you a lot, it was helpful!
