### ISSUE TITLE
[BUG] XSS on calendar page

### ISSUE THREAD

**Issue by mkaraoz** [ColorlibHQ/AdminLTE#2867]
**Describe the bug**
On Calendar page, While creating an event, if you enter **"><script>alert(1)</script>** as the name, you get an alert window. I found it while I was checking out the live demo. Live demo runs version 2.4.13. If this is fixed on v3.x please ignore the report. 

1. Go to 'main page'
2. Click on 'Calender on the left hand pane'
3. Enter "><script>alert(1)</script> as the name of the event 
4. Click on add button
4. JS alert pops up

**Expected behavior**
Input is filtered or the output is html encoded so you cannot run js on the page

**Screenshots**
![image](https://user-images.githubusercontent.com/2737954/86643429-5c966e80-bfe5-11ea-8625-fcfd89c233f1.png)

**Environment (please complete the following information):**
- AdminLTE Version: 2.4.13
- Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
The complete calendar script is not ready to use (without any modifications), it's only for demo purposes.

Also AdminLTE v2 is not maintained anymore.
