### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kekushke** [ColorlibHQ/AdminLTE#2870]
I downloaded AdminLTE 3.x using npm. All is well. Then I downloaded a new feature package using `npm`. This worked well as well. The new package appears in `package.json` file and is downloaded into `node_modules`. I also added the `dist` directory of the new package to the  to the list in `build/npm/Publish.js` so that it is copied to `plugins` directory. All this is working fine. 

But, it is not clear if the new packages' javascript and css would be automatically included in final `dist/js/adminlte.min.js` and `dist/css/adminlte.min.css`?  I don't fully understand scripts in `package.json`.

Is it correct that  `npm run production` will include all the javascript and css from the newly updated `Publish.js` into minimized `dist/js/adminlte.min.js` and `./dist/css/adminlte.min.css`?

If there is a documentation as to how to add a package to the AdminLTE so that it is automatically included into `adminlte.min.js` on `npm run production`? For some reason this did not work for me. Many Thnx!

**Comment by REJack** [comment]
Only AdminLTE's own styles/scripts are included in `dist/js/adminlte(.min).(js/css)` there are no thrid party styles/scripts included.

The `npm run production` script isn't designed to include third party styles/scripts. You need to create a own concat script to accomplish this.
