### ISSUE TITLE
Toggle button not working in 2.4.x

### ISSUE THREAD

**Issue by judodan** [ColorlibHQ/AdminLTE#2882]
I just moved from 2.3.x to 2.4.x (hoping to move to 3.x in not too distant future) and I've noticed that the toggle buttons are not working.

If you go to the example here: https://adminlte.io/themes/AdminLTE/index.html

In the chat area, there are two buttons, one green and one red. It used to be (2.3.x) the active button would change when you clicked one, but it doesn't appear to be working now.

In the older version, the code was in app.js, but the filename changed so I can't even find when the change was made.

Has anybody else seen this and fixed it?

**Comment by REJack** [comment]
AdminLTE v2.4 isn't maintained anymore since v3 is released. Sadly this bug wasn't reported before the support/maintance ended. Idk if somebody fixed this, but I would say you can get a better help on stackoverflow.com with your question.
