### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aiyaful** [ColorlibHQ/AdminLTE#2886]
**Describe the bug**
500: Internal Server Error

**To Reproduce**
1. Go to https://github.com/ColorlibHQ/AdminLTE
2. Click on GitHub releases
3. Scroll down to AdminLTE 3.0.5 source code and download

**Expected behavior**
should download.

**Tried Any Solution**
Tried right click and save link as.

**What did it do**
failed - Server problem

**Comment by REJack** [comment]
This bug isn't related to AdminLTE itself, please check your webserver for this.
