### ISSUE TITLE
Sidebar search enhancement

### ISSUE THREAD

**Issue by GerryGe** [ColorlibHQ/AdminLTE#2888]
#2841
How to use keyboard down key(↓) to select filter results?
For example, I input "Pro", then I use  down key(↓) to move to "Project Add" menu, then I can press Enter to open the page.
![image](https://user-images.githubusercontent.com/6952917/87404486-cbc91f80-c5f0-11ea-9277-ba80586fd199.png)

Another, there are two close buttons, I highlight with the red box in the screenshot.
By the way, I use the master branch with last commit  3fffe80, but It looks different with your screenshot, yours don't have two close buttons.

**Steps to reproduce:**
1.  clone
2.  npm install
3.  npm run dev

**Comment by REJack** [comment]
1. I'll add this feature to move across the search entries with the arrow up/down keys.
2. The second "X" comes from Chrome/Edge, I'll add a style to hide them.
