### ISSUE TITLE
[BUG] Treeview not working on Android (Nuxt.js)

### ISSUE THREAD

**Issue by pwongsathorn** [ColorlibHQ/AdminLTE#2889]
I'm using AdminLTE for my product's admin page which implimented with Nuxt.js (Vue 2), most thing work fine except Treeview isn't working on Android mobile devices. It cannot open or collapse any menu. Anyway, desktop and iOS still work properly.

I'm not sure how to give you a step to reproduce, since you need to logged-in to the system.

**but here's the code:**
![image](https://user-images.githubusercontent.com/65006123/87444774-680b1a80-c621-11ea-9ba1-619586e3f6b1.png)

**Environment:**
- AdminLTE Version: v3.0.0
- Operating System: Android > 4.4
- Browser (Version): Every browser

**Comment by pwongsathorn** [comment]
Solved myself
I have to check for DOM is ready before run each()
![image](https://user-images.githubusercontent.com/65006123/87655214-25ad1f00-c782-11ea-82f0-243ae48e1ba9.png)

**Comment by danus12** [comment]
@pwongsathorn Your idea was and is still the solution trick, thank you
The adminlte 3.1.0-rc version has the same bug
