### ISSUE TITLE
Third level sidebar nav - wrong 2 level nav is expanded [BUG]

### ISSUE THREAD

**Issue by bro-source** [ColorlibHQ/AdminLTE#2900]
**Describe the bug**

I have made a 3-level sidebar navigation.

When I click on a 2-level navigation link other 2-level with 3-level (treeview) is also expanded.

Level - 1
  Level - 2 (1) <-- This one is expanded.
    Level - 3 (1)
  Level - 2 (2)  <-- When I click on this link.

It looks like it happens after pageload.

**Environment (please complete the following information):**
- AdminLTE Version: [v3.0.5] Latest from Github
- Operating System:  [Windows 10]
- Browser (Version): [Chrome (Latest), Edge (Latest)]

**Comment by REJack** [comment]
Please provide a example code to reproduce this bug.

**Comment by bro-source** [comment]
Hi, just found the issue.

Too many class="active"

Sorry! Just close.

Best regards and thanks for an awsome templage!

/henrik
