### ISSUE TITLE
[FEATURE] Multiple sidebars (control sidebars)

### ISSUE THREAD

**Issue by frosadev** [ColorlibHQ/AdminLTE#2901]
Is there a way to have multiple control sidebars on the same page?
It would be nice to be able to define the id of the element to toggle it.

Thanks in advance

**Comment by REJack** [comment]
There is no way to define the id of the control sidebar, it's designed to only use one control sidebar you would need to hide/show the content on show/hide the contro sidebar with the builtin events.

**Comment by frosadev** [comment]
Wouldn't it be awesome to have this feature for a future release?
Is there any plans to having it?
I saw many requests for it online.

**Comment by REJack** [comment]
> Wouldn't it be awesome to have this feature for a future release?

I see no really benefit from this feature, since you can manipulate the content before opening the control sidebar also they would overlap if both would open.

>  Is there any plans to having it?

Nope there is no plan to implement.

>  I saw many requests for it online.

Where you saw the requests?

**Comment by frosadev** [comment]
One use case could be to have a side panel for main settings and have a page (like master-detail).

I've seen people asking on how to achieve that on stackoverflow.

**Comment by zxo102** [comment]
I try to use multiple sidebars using divs with `display:block `and `display:none` to toggle it:
   
https://github.com/ColorlibHQ/AdminLTE/issues/3071#

But It is not collapsible.

**Comment by REJack** [comment]
I've added a new option `target` to open a specific control-sidebar to handle multiple. It will released with v3.1.0.
