### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by persistencelkg** [ColorlibHQ/AdminLTE#2902]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47962831/87852163-30a6b180-c932-11ea-9428-9643fe0d5696.png)

When I use AdminLTE v3.x , A bug occur in which I reference jquery.vmap.min.js These is error from chrome
`jquery.vmap.min.js:10 Error: <svg> attribute width: Expected length, "undefined".`

By the way, this bug happen in When I use **dashboard.js**

So How to deal with?

**Comment by REJack** [comment]
Please report this error/bug on [jqvmap](https://github.com/10bestdesign/jqvmap) repo, also the dashboard.js isn't build for production usage it's only for our demos.
