### ISSUE TITLE
[FEATURE] adminlte sass render example

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#2909]
[FEATURE] adminlte sass render example

how to do that make an tutorial

**Comment by REJack** [comment]
What exactly you mean?

**Comment by guillaumecardon** [comment]
I agree. It could be interesting to have a doc or tutorial explaing how to use adminlte with sass.
I think that the main goal is to customize easily colors ($primary, $secondary, etc.)

**Comment by REJack** [comment]
Sorry for the late response :/ I've added a docs page already, but if you need some info now you can take a look a this https://github.com/ColorlibHQ/AdminLTE/issues/2687#issuecomment-630128293
