### ISSUE TITLE
[BUG] Menu items cant be hidden

### ISSUE THREAD

**Issue by DesRodman** [ColorlibHQ/AdminLTE#2918]
**Describe the bug**
At AdminLTE v2 was opportunity to hide some menu with class => "hidden"
Same thing dont works at AdminLTE v3

**To Reproduce**
```
 <nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview"><li class="nav-item treeview">
				<a class="nav-link " href="/"><i class="nav-icon fab fa-chess"></i>  <p>Routing  <i class="right fas fa-chess"></i></p></a>
				<li class="nav-item"><a class="nav-link " href="/moderation"><i class="nav-icon fas fa-theater-masks"></i>  <p>Moderation  </p></a></li>
				<li class="hidden nav-item"><a class="nav-link " href="/spec-moderation"><i class="nav-icon fas fa-hand-holding-heart"></i>  <p>Personal moderation  </p></a></li>
			</ul>
</nav>
```
**Expected behavior**
at AdminLTE v2 i hide Manu category and selected menu
In my example menu "Personal moderation" should be not visible, but anyway i can see both menu items

**Screenshots**
https://prnt.sc/tnoh4s

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [e.g. Ubuntu 19.10]
- Browser (Version): [e.g. Firefox (Latest)]

**Comment by REJack** [comment]
Try to replace `.hidden` with `.d-none`.

**Comment by DesRodman** [comment]
`.d-none` is working
Thanks a lot
