### ISSUE TITLE
[BUG] Mulitple Level Dropdown Menu Overlapping

### ISSUE THREAD

**Issue by ligarp** [ColorlibHQ/AdminLTE#2919]
**Describe the bug**

**To Reproduce**
1. Go to 'pages/layout/top-nav.html'
2. Click on 'Dropdown menu'
3. Click on 'Dropdown submenu1'

**Expected behavior**
This is multilevel dropdown menu from version 3.0.2

![Screenshot_256](https://user-images.githubusercontent.com/43329321/88368444-48f65080-cdb8-11ea-825a-dbada507b448.png)

**Screenshots**
This is the behavior from version 3.05.
the problem will occure when i click the dropdown sub menu level 1, the child menu will overlap the parent.

![Screenshot_255](https://user-images.githubusercontent.com/43329321/88368223-ccfc0880-cdb7-11ea-978b-adf85ed1adf2.png)

**Environment:**
- AdminLTE Version: [v3.0.5]
- Operating System:  [Windows 10]
- Browser (Version): [Chrome (84.0.4147.89),Firefox(78.0.1 64-bit)]

**Comment by REJack** [comment]
I can't replicate this issue, please check your dev console for errors.

**Comment by ligarp** [comment]
i downloaded the source code (v3.0.5) from the release page.

There are no errors or warning in the console tab

![Screenshot from 2020-07-24 23-06-12](https://user-images.githubusercontent.com/43329321/88411661-867fcb80-ce02-11ea-9f63-d7366f4ac16a.png)

And this is the screenshot from the network tab, everything is ok.

![Screenshot from 2020-07-24 23-07-38](https://user-images.githubusercontent.com/43329321/88412007-1aea2e00-ce03-11ea-9fa5-9c8478a154b1.png)
