### ISSUE TITLE
[FEATURE] Control Sidebar Plugin - option to close instead of toggle

### ISSUE THREAD

**Issue by tikky** [ColorlibHQ/AdminLTE#2940]
I am looking an option for JS code which can close right sidebar, called "Control Sidebar Plugin"
I know I now is possible to toggle (open/close) sidebar:

Code to toggle is:
`<a href="#" data-widget="control-sidebar" id="my-toggle-button">Toggle Control Sidebar</a>`
jQuery:

`$("#my-toggle-button").ControlSidebar('toggle');`

... but I need to close it only (instead of toggle).
Is is possible now?
- If yes, please add this information to manual: [https://adminlte.io/docs/3.0/javascript/control-sidebar.html](https://adminlte.io/docs/3.0/javascript/control-sidebar.html)
- If now, please mark it as my feature request

As I bypass solution maybe is there an option to check if sidebar is open, then I can use toggle only for open sidebar.

**Comment by REJack** [comment]
You can use `collapse` or `expand` instead of `toggle`.

I'll update the docs to point these methods too.

**Comment by tikky** [comment]
Thank you for the information.
Will be great to add it to documentation.
