### ISSUE TITLE
[BUG] npm install issue

### ISSUE THREAD

**Issue by jiten143** [ColorlibHQ/AdminLTE#2941]
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

**Comment by pacoorozco** [comment]
I'm going to work on this if you don't mind..

**Comment by REJack** [comment]
I don't know if bootstrap support popper v2 that's why we stay on v1, you can ignore this warning.
