### ISSUE TITLE
Card Tool Buttons are Not Working

### ISSUE THREAD

**Issue by jkmuka** [ColorlibHQ/AdminLTE#2942]
Card Tool buttons do not do anything when clicked, only when importing the CardWidget.js but I do not see that step anywhere in the docs.

Adding the below from demo to an html page with adminlte.js and  adminlte.css loaded

```
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Card Tools</h3>

        <div class="card-tools">
            <!-- This will cause the card to maximize when clicked -->
            <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
            <!-- This will cause the card to collapse when clicked -->
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            <!-- This will cause the card to be removed when clicked -->
            <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
        </div>
        <!-- /.card-tools -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        The body of the card
    </div>
    <!-- /.card-body -->
</div>
```

**Expected behavior**
The remove button should remove the card, the expand button should expand the card and the minimize button should minimize the card

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.0
- Operating System:  Windows 10
- Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
You need load the adminlte(.min).js to get the whole layout and all extra plugins working.
