### ISSUE TITLE
[BUG] Dependencies outdated

### ISSUE THREAD

**Issue by dvdknaap** [ColorlibHQ/AdminLTE#2943]
**Describe the bug**
When i run yarn dev i get the following warnings
![image](https://user-images.githubusercontent.com/6288313/89132401-1664fa00-d514-11ea-8c4d-dad32610ef8c.png)

**To Reproduce**
Compile the theme with webpack encore

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.5
- Operating System: Ubuntu

**Comment by REJack** [comment]
Regarding to the popper.js warings: I don't know if bootstrap support popper v2 that's why we stay on v1, you can ignore this warning.

There is no pdfmake update to fix this warning but they are working on a new update.
