### ISSUE TITLE
[FEATURE] adminlte.io Update "LIVE PREVIEW"-link on mainpage. 

### ISSUE THREAD

**Issue by sourcenux** [ColorlibHQ/AdminLTE#2957]
**Is your feature request related to a problem? Please describe.**
Yes. When I first started working with adminLTE, I did not notice, that your "Live-Preview" on adminlte.io uses the old AdminLTE 2.4.x template instead of the newer version 3.0.5. The download-link on the main page points to this github repository where you will rather download the most recent version (3.0.5) instead of the old 2.4.x-version somewhere in the long list of releases. 

**Describe the solution you'd like**
First Idea: Update the Link for "live preview" on the main page to point to  https://adminlte.io/themes/dev/AdminLTE/index.html

**Describe alternatives you've considered**
Second Idea: Add another button called "Live Preview (3.0.5)" while preserving the old button. In this case you could also rename the old button to "Live Preview (2.4.x - Unsupported)" or something like that. 

**Additional context**

![grafik](https://user-images.githubusercontent.com/29550035/89737726-90950180-da73-11ea-9a8f-a6417f8f461e.png)

**Comment by REJack** [comment]
The AdminLTE page is already in work, but AdminLTE v3.1 has a higher priority 😄.
