### ISSUE TITLE
[BUG] Sidebar links are all set to active when added a "#" at the end of the link.

### ISSUE THREAD

**Issue by gh-supersudo** [ColorlibHQ/AdminLTE#2967]
**Describe the bug**
Sidebar links are all set to active when added a "#" at the end of the link.

**To Reproduce**
1. Add "#" at the end of a link
2. Refresh the page

**Expected behavior**
A selected link should be the only link that should be active.

**Environment (please complete the following information):**
- AdminLTE Version: 3.0.2
- Operating System:  Manjaro Linux v19.0.2
- Browser (Version): Firefox v75

**Comment by prsolucoes** [comment]
AdminLTE Version: 3.0.5

**Comment by REJack** [comment]
This bug can't replicated, also AdminLTE has no auto active setter may this comes from an custom script.
