### ISSUE TITLE
Change collapse icon of cardWidget

### ISSUE THREAD

**Issue by HumbertoSilveira** [ColorlibHQ/AdminLTE#2968]
I would like to change the collapse/expand icon of the cardWidget but didn't find on docs, so I tested this solution found in the issue @https://github.com/ColorlibHQ/AdminLTE/issues/2404:

$('.card-widget').CardWidget({
        collapseTrigger: '.btn-collapse',
        collapseIcon: 'fa-caret-up',
        expandIcon: 'fa-caret-down'
});

But that also not work. Is it a bug or I'm doing something wrong?

**Comment by REJack** [comment]
You need to init the CardWidget button instead of the whole Card, but you can also set the icon via data-attributes.
