### ISSUE TITLE
[FEATURE] Add SearchPane plugin for DataTables

### ISSUE THREAD

**Issue by dwasyl** [ColorlibHQ/AdminLTE#2977]
Hi there,

I'm trying to use the DataTables module that ships with AdminLTE, however I need to make use of the SearchPane plugin that Datatables recently published . Any chance of including this with the rest of the plugin modules for Datatables that are already included?

It's a relatively new plugin but is officially supported now.

Thanks

**Comment by REJack** [comment]
I've added the plugin in master branch 😄
