### ISSUE TITLE
[FEATURE] Change color of the submenu items.

### ISSUE THREAD

**Issue by JNPSoftware** [ColorlibHQ/AdminLTE#2979]
Hello guys, how can I change the color of this submenu (nav-item has-treeview) to not show it in blue when I hover over it? tks.
I use AdminLte 3.0.5. My nav class is "navbar-light navbar-lightblue"

![image](https://user-images.githubusercontent.com/33754986/90805957-ba132000-e2f2-11ea-90ec-f2895737dcf8.png)

**Comment by mineminemine** [comment]
> navbar-light navbar-lightblue
The above will not have any effect on the sidebar, what you need to look into is the sidebar styling.

However as of today, I don't think the template allows you to change the text color for nav items through class names so you will have to either change the styling per page or directly editing the imported adminlte.css / adminlte.min.css file. Specifically this line:

> .nav-pills .nav-link:not(.active):hover {
		color: aquamarine;
	}

Either put them in a <style> tag or edit them in the adminlte.css / adminlte.min.css file.

**Comment by JNPSoftware** [comment]
Thank you, this work for me.
