### ISSUE TITLE
[FEATURE] - Add skin switching capability to AdminLTE3 (which was available in AdminLTE2)

### ISSUE THREAD

**Issue by distributev** [ColorlibHQ/AdminLTE#2981]
**Is your feature request related to a problem? Please describe.**

In AdminLTE2 it was possible to switch the skin with one click and this was convenient to get a new skin from a single click.

![image](https://user-images.githubusercontent.com/19224635/90872061-57765e80-e39c-11ea-995c-e1567f309dcb.png)

**Describe the solution you'd like**

AdminLTE3 should bring back the skin switcher capability.

**Comment by SmileYzn** [comment]
I have created something in my new adminlte installation.
But you can check demo site, it have a demo feature

Admin shoud first fix accent colors in skin chooser of adminlte :P

**Comment by REJack** [comment]
Skins like they was available in AdminLTE v2 are not exist in v3 but it's already planned for v4.
