### ISSUE TITLE
Is it possibile to use the template in Angular?

### ISSUE THREAD

**Issue by marcobocca1973** [ColorlibHQ/AdminLTE#2985]
Hi,

I'd like to buy the template.

But I neet to know if it is possible to use it in Angular and how I can do it.

Thank you in advance

marco

**Comment by ozilion** [comment]
It's just a html template you can easyly us it in any framework or with library like Angular, react etc.

**Comment by REJack** [comment]
Yes, here is a example repo ([erdkse/adminlte-3-angular](https://github.com/erdkse/adminlte-3-angular)).
