### ISSUE TITLE
how to open a dropdown menu at the top right on the screen

### ISSUE THREAD

**Issue by mammnon** [ColorlibHQ/AdminLTE#2987]
Hi everybody,

I love adminLTE but I'm stuck within this simple feature:
I would like to open the dropdown messages-menu dynamically (ie; when a new message arrive).
I tried many way but none sucessfully.

Any idea ?

Thanks in advance

**Comment by REJack** [comment]
You simply need to add the `show` class to `.dropdown` & `.dropdown-menu`.
