### ISSUE TITLE
Licencia Copyright 

### ISSUE THREAD

**Issue by JorgeRB20** [ColorlibHQ/AdminLTE#2988]
La licencia Mit, especifica que es necesario que el aviso de Copyright este en todas sus paginas, es posible que el nombre de AdminLite cambie por el nombre de una empresa. 

La licencia Mit indica que se puede sublicenciar el producto a que se refiere.

**Comment by REscobar** [comment]
La licencia MIT es una de las permisivas, permite crear derivados, duplicar, reutilizar, etc., del software, con la única restricción que la noticia debe incluirse en todas las copias o porciones substanciales del software (este repositorio).

El software derivado no está obligado a utilizar los mismos términos de licenciamiento.

Con respecto a la noticia, lo que significa es que debe incluirse en el código fuente que se obtenga de este repositorio.

Translation: briefly explaining MIT license
