### ISSUE TITLE
Make project from ur template

### ISSUE THREAD

**Issue by muhammaddaffa06** [ColorlibHQ/AdminLTE#2989]
Can i use ur template for create my e-commerce project?

Thank you for your answer

**Comment by SmileYzn** [comment]
**Yes!**

**Comment by muhammaddaffa06** [comment]
are u admin or what bro ?

**Comment by SmileYzn** [comment]
Only a user that also uses in a comercial project

**Comment by muhammaddaffa06** [comment]
How about license ?

**Comment by REscobar** [comment]
It is licensed under the terms of the MIT license.

**Comment by muhammaddaffa06** [comment]
where i can put it ? do u have telegram?

**Comment by REscobar** [comment]
I don't have telegram, but keep posting your questions here and you will keep getting answers.

Now back to your question, where do you put what?

**Comment by muhammaddaffa06** [comment]
put the license bro

**Comment by REscobar** [comment]
These are the terms under wich this repository is licensed

https://github.com/ColorlibHQ/AdminLTE/blob/master/LICENSE

**Comment by muhammaddaffa06** [comment]
i copy all, and then put in my project?

**Comment by REscobar** [comment]
You don't need to apply the license to the files you create for your project, the following quote from the license basically means that if you copy a file from this repository, even if you modify it, you should not remove the license notice at the top.

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

_From https://github.com/ColorlibHQ/AdminLTE/blob/master/LICENSE#L12_

An example of this is the following file, it includes the base functionality of the theme and has a notice at the top, you are free to use, copy, modify, distribute, etc, as long as you keep the notice at the top.

https://adminlte.io/themes/v3/dist/js/adminlte.js


In simpler words, you are free (allowed) to use this software for any purpose you see fit, even for commercial projects.
