### ISSUE TITLE
[BUG] Datatables Buttons Collection: Dropdown menu will not open

### ISSUE THREAD

**Issue by AnthonyJZuniga** [ColorlibHQ/AdminLTE#2995]
**Describe the bug**
When attempting to use a collection in the button section of a datatable the dropdown menu for the collection will not open. I don't know if this is just an issue with Datatables or if there is some interaction going on with Adminlte's code.

**To Reproduce**
1. create a collection button in datatable script.
2. Click on the created button.

**Expected behavior**
The child buttons should display in a dropdown menu underneath the collection button.

**Screenshots**
It's tough to screenshot something that's not happening lol

**Environment (please complete the following information):**
- AdminLTE Version: 3.0.5
- Operating System:  Windows 10
- Browser (Version): Chrome Latest
- Laravel Version: 7.13.0
- Bootstrap Version: 4.5.2

**Comment by REJack** [comment]
You need to import the `buttons.bootstrap4.min.css` to get the dropdown shown.
