### ISSUE TITLE
need some information

### ISSUE THREAD

**Issue by medeepaksaini** [ColorlibHQ/AdminLTE#3011]
Hey everyone, i'm new here, i just want to know how he copying packages from `node_module` to `pluings folder`

also in build folder there is one `npm` folder that have `packages.js` file what it use and how i can do that

can someone please help to learn this thing.

**Comment by medeepaksaini** [comment]
@REJack can you please help me, how i can do that.

**Comment by REJack** [comment]
You need simply run `npm run plugins` to copy all the used plugins to the `plugins` folder.

**Comment by medeepaksaini** [comment]
> You need simply run `npm run plugins` to copy all the used plugins to the `plugins` folder.

Any plugins that i have to install and run at time to  compile file, because i check in `build` there is a file `pluings.js`

may be you are running this at time of initiation.

i want to know how i can also copy plugins from 'node_modules' to my 'plugins/vendor folder'

**Comment by medeepaksaini** [comment]
@REJack Can you please explain little bit more, that will help me so much in future

**Comment by REJack** [comment]
Either your use `npm run plugins` or `node build/npm/Publish.js` to copy the plugin files from node_modules, but if you want to copy custom ones your need to add the plugins in `build/npm/Plugins.js` and then run one of the commands.

**Comment by medeepaksaini** [comment]
@REJack if i added to `build/npm/Plugins.js` then i directly need to run this script file or need some kind of plugin (link - Gulp) to process this script.

**Comment by REJack** [comment]
You don't need no gulp or grunt for this, you can simply use our publish script to copy the files.

**Comment by medeepaksaini** [comment]
Okay

**Comment by medeepaksaini** [comment]
@REJack Thanks! this help me a lot also, how i can copy `sass/scss` files from `node_module` folder to my `sass plugins` folder

**Comment by medeepaksaini** [comment]
@REJack any help about this problem, because as of now i have copy sass file from `node_module` to `sass/plugins` folder

and while trying to import bootstrap as you `@import '~bootstrap/scss/functions';` its showing error

`Error: File to import not found or unreadable: ~bootstrap/scss/functions.`

**Comment by REJack** [comment]
You need a extra plugin to load node modules with the tilde `~`, we use the node-sass to build the css files from scss there we added a package called `node-sass-package-importer`. Idk if there are derivatives for other builders

**Comment by medeepaksaini** [comment]
@REJack thanks for input, how you have copy sass files in `build/sass/plugins` folder.

You are copying manually or using some kind of plugins ?

**Comment by REJack** [comment]
We don't copy/compile the sass/scss files from plugins, that's why we copy only the css & js files.

**Comment by medeepaksaini** [comment]
@REJack manually? EVERYTIME ?

**Comment by REJack** [comment]
No our plugins/publish script copies js and css  😄

**Comment by medeepaksaini** [comment]
okay

**Comment by medeepaksaini** [comment]
@REJack can you suggest me something on it

**Comment by REJack** [comment]
> @REJack can you suggest me something on it

What you mean?

**Comment by medeepaksaini** [comment]
how i can do that, copy plugins on sass folder automatically

**Comment by medeepaksaini** [comment]
also any course

**Comment by REJack** [comment]
You can modify our plugins/publish script and bind the script like us in the npm install hook, for this you can check our package.json. But this is only a quick and dirt solution.

**Comment by medeepaksaini** [comment]
@REJack Thanks for your help 😄

**Comment by medeepaksaini** [comment]
@REJack which` npm` command you will run in last to process all your `packages (css,scss,js)`

**Comment by medeepaksaini** [comment]
@REJack which config do i use in `eslint` because it's getting failed back to back
