### ISSUE TITLE
[BUG] mixin font-size not found

### ISSUE THREAD

**Issue by parsasabbar** [ColorlibHQ/AdminLTE#3012]
**Describe the bug**
I compiled the adminlte sass files and got this error:

![Capture](https://user-images.githubusercontent.com/62116286/92714139-0e00aa00-f371-11ea-8674-e970003ca6b7.PNG)
As it is seen, the mixin named font size not found!
I think this is a bug.

**To Reproduce**
go to "build/scss" and compile scss files via your favorite sass compiler tool 
(my favorite is live sass compiler extension in vs code)

**Environment:**
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [e.g. macOS Catalina]
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**
although we can add this mixin to _miscellaneous.scss file ourselves:

![Capture](https://user-images.githubusercontent.com/62116286/92715315-92076180-f372-11ea-9091-5d07ffe0e84b.PNG)

**Comment by REJack** [comment]
This sounds like you can't import the bootstrap package with the tilde-selector `~`, I can build the css files without any problem. The `font-size` mixin is a part of the rfs `responsive font size` package that's integrated in Bootstrap 4.

**Comment by parsasabbar** [comment]
> 
> 
> This sounds like you can't import the bootstrap package with the tilde-selector `~`, I can build the css files without any problem. The `font-size` mixin is a part of the rfs `responsive font size` package that's integrated in Bootstrap 4.

Thanks, you are right

**Comment by mfrancavigliaeximie** [comment]
so ohw did you solve the problem?
