### ISSUE TITLE
npm compiling file error

### ISSUE THREAD

**Issue by medeepaksaini** [ColorlibHQ/AdminLTE#3014]
@REJack when i'm trying to compile files from `scss` to `css` gettings error in `_bootstrap-variables.scss`

### Errro
```
public_html/src/scss/_bootstrap-variables.scss
263:1  ×  "value-keyword-case" has not been disabled   CssSyntaxError
```

*263:1 code :*
```
$embed-responsive-aspect-ratios: join(
  (
    (21 9),
    (16 9),
    (4 3),
    (1 1),
  ),
  $embed-responsive-aspect-ratios
);
```

can you suggest me how i can fix that

**Comment by REJack** [comment]
We don't use the `$embed-responsive-aspect-ratios` so I can't replicate this error, this doesn't appear to be a AdminLTE bug it look like a SCSS related error.
