### ISSUE TITLE
UI customize issue

### ISSUE THREAD

**Issue by ash03-coder** [ColorlibHQ/AdminLTE#3018]
if I customize AdminLTE such as navbar, sidebar color.... after refresh it becomes like the old one. How can I fix this?

**Comment by mineminemine** [comment]
Where are you editing it? How are you editing it?

Have you tried doing a hard refresh by Ctrl + F5?

**Comment by SmileYzn** [comment]
He means in customizer sidebar, these settings are used only for demonsration. Also the values are not saved in any place to maintain colors.

**Comment by REJack** [comment]
You need to set the classes by hand, the control sidebar is only for demo purpose and doesn't save anything.

**Comment by SmileYzn** [comment]
We also just crete a function in javascript to toggle these classes?
I have dome something else in my system using localStorage
