### ISSUE TITLE
Tailwind support/version

### ISSUE THREAD

**Issue by dcblogdev** [ColorlibHQ/AdminLTE#3028]
I've recently started using Tailwind and was wondering if there are plans to support tailwind in the future?

I'd love a TW version even if it was only the shell of the layout.

**Comment by SmileYzn** [comment]
I guess that tailwind is imcompatible with bootstrap :(

**Comment by dcblogdev** [comment]
yeah, it's a competing front end framework, more utility-based then class-based.

**Comment by SmileYzn** [comment]
I guess a lot of web projects supports bootstrap, more than tailwind. But is good to see usage of new frameworks.
Maybe a future project of admin dashboard can be based in tailwind :P

**Comment by REJack** [comment]
Sadly to say but at the moment we have no plans to create a new tailwind version, that would need a complete rework to get working with tailwind. Also this template is built on Bootstrap and that says pretty much everything.
