### ISSUE TITLE
[FEATURE] Icon Buttons please

### ISSUE THREAD

**Issue by suntong** [ColorlibHQ/AdminLTE#3030]
**Is your feature request related to a problem? Please describe.**

Buttons with icon looks really cool.

**Describe the solution you'd like**

Provide a standard way to add icon to Buttons. Like the ones in
https://sleek.tafcoder.com/button-default.html

![image](https://user-images.githubusercontent.com/422244/93691699-36964b80-fab7-11ea-9b34-7c22a627d283.png)

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by REJack** [comment]
That's a nice idea, I will add examples for this.
