### ISSUE TITLE
[FEATURE] Colored Checkbox and Radio buttons please

### ISSUE THREAD

**Issue by suntong** [ColorlibHQ/AdminLTE#3031]
**Is your feature request related to a problem? Please describe.**

Checkbox and Radio with colors looks really cool.

I found example of colored Checkbox, but didn't find example of colored Radio buttons.

**Describe the solution you'd like**

Provide a standard way to provide Colored Checkbox and Radio buttons, and include them in the demo. Like the ones in
https://sleek.tafcoder.com/checkbox-radio.html

![image](https://user-images.githubusercontent.com/422244/93691757-e23f9b80-fab7-11ea-8b72-10bcae91f871.png)

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by suntong** [comment]
Thank @REJack 

Could you add demo as well please? 

I checked the change "add .custom-control-input-outline for custom checkbox/radio outline onyl style" and all others in https://github.com/ColorlibHQ/AdminLTE/pull/3046, but nothing seems to be able to render colored Checkbox and Radio as posted in OP. 

Maybe the feature is already there, but without demo, I don't know how to apply. 

Thanks

**Comment by REJack** [comment]
Sure there is a example in the demo, take a look here ![img](https://i.imgur.com/e9CfPVN.png).

**Comment by suntong** [comment]
Ah, no wonder, somehow mine show up like this:

![image](https://user-images.githubusercontent.com/422244/94736479-470db800-033a-11eb-9c30-9530e8bb567b.png)

I just downloaded the lastest zip file and expand and visit it locally.

**Comment by REJack** [comment]
You need to clone master and build the css files.

**Comment by suntong** [comment]
I think downloading from https://github.com/ColorlibHQ/AdminLTE/archive/master.zip would be the same as clone the master. 

What would be missing is the `build the css files` step.  
How can I do that?
