### ISSUE TITLE
How we can make release and publish it into website [HELP]

### ISSUE THREAD

**Issue by medeepaksaini** [ColorlibHQ/AdminLTE#3050]
@REJack can you suggest me how i can release using VScode and publish it into my website.

**Comment by REJack** [comment]
What you mean with "make release"?

Either you publish it by your own (external (S)FTP app) or using the SFTP plugin. I personally use VSCode with SFTP Plugin but not for all my projects. But you need to compile the css/js files by your own.

**Comment by medeepaksaini** [comment]
@REJack so we i can use `SFTP` plugin to update changes into my live website ?

Or there is some other good way to update changes into website ?

also can i ignore `node_module` and some other folder while uploading pages into website ?

**Comment by medeepaksaini** [comment]
@REJack can you tell me by some kind of code? how i can push changes to my live website using vscode

**Comment by REJack** [comment]
> @REJack so we i can use SFTP plugin to update changes into my live website ?

Yep, but its only a good choice for static websites IMHO. 

> Or there is some other good way to update changes into website ?

Oh there are many ways to update changes easily, you need to find your favorite way. 

> also can i ignore node_module and some other folder while uploading pages into website ?

Yep there is a ignore setting there you can setup folder/files to ignore for each project.

> can you tell me by some kind of code? how i can push changes to my live website using vscode

There is no specific way to push changes to your live website, there are other ways to do it based on which framework you used in your page.

Try to ask this question on stackoverflow there you get better help 😄

**Comment by medeepaksaini** [comment]
@REJack Thanks 👍
