### ISSUE TITLE
How Re-Initialise Control Sidebar after AJAX Insert to SideBar Body

### ISSUE THREAD

**Issue by Jithin-C-V** [ColorlibHQ/AdminLTE#3051]
Hi,

I am updating my control sidebar with AJAX response every 5 secs. But after AJAX result insert the control sidebar plugin is not effective (No Scrolling is happening). 

So please help me on how to call Re-Initialise Control Sidebar after AJAX.

Thanks in Advance.

Current SideBar Code
```<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3 control-sidebar-content" id="idc-sidebar-contents">
      <h6>Your Non-Active Task</h6>
      <?php echo $MyTasksHtml; ?>
      <h6>System Active Task</h6>
      <?php echo $SystemTasks; ?>
    </div>
  </aside>
```
AJAX Code
```function startSidebarMonitor() {
  time = setInterval(function() {
    $.ajax({
      type: "POST",
      async: "false",
      data: {RequestType: "SidebarStats"},
      url: "./src/components/handles/Sidebar_Stats.php",
      success: function(result){
        var jsonResult = JSON.parse(result);
        if(jsonResult.Status == "True"){
          $("#idc-sidebar-contents").empty().append(jsonResult.SideBarBodyHtml);
        }
      }
    });
  }, 5000);
}
```

Regards,
Jithin C V

**Comment by mineminemine** [comment]
Instead of re-initializing the sidebar every time, why not update the specific divs only?
For example:
`

    <div class="p-3 control-sidebar-content" id="idc-sidebar-contents">
      <h6>Your Non-Active Task</h6>
      <div id="myTasksDiv"></div>
      <h6>System Active Task</h6>
      <div id="systemTasksDiv"></div>
    </div>
  </aside>
`

And then specifically target the divs using your AJAX calls with `$('#myTasksDiv').text("the stat here");` similar to how you're currently doing the AJAX code you've shown. You will also have to initialize the stat every time the page is loaded so keep that in mind.

**Comment by Jithin-C-V** [comment]
Cool.... 👍 

That will work. I haven't think in that way.

Regards,
Jithin C V
