### ISSUE TITLE
Bug Layout Orientation window.print()

### ISSUE THREAD

**Issue by educms** [ColorlibHQ/AdminLTE#3052]
AdminLTE 2
![adminlte2](https://user-images.githubusercontent.com/62460746/94365109-76cd7d80-00f8-11eb-92ae-7a519d7d08fe.png)
AdminLTE3
![adminlte3](https://user-images.githubusercontent.com/62460746/94365110-7a610480-00f8-11eb-95c4-d5c68ca43d5d.png)

**Comment by REJack** [comment]
Please use our Bug Report and fill out the needed informations!
