### ISSUE TITLE
[FEATURE] Sortable on simple tables

### ISSUE THREAD

**Issue by SmileYzn** [ColorlibHQ/AdminLTE#3065]
Hi, thanks for good work with AdminLTE.
Is possible to add to simple tables the table content sort like in datatables?
I mean, to sort columns in ascending or descending order.

Thanks

**Comment by REJack** [comment]
Do you mean only the styling/example or a JS Plugin?

**Comment by SmileYzn** [comment]
A js plugin, since i do not think is a good idea implement datatable only to have this feature?

I thin in something like in expandable bootstrap tables, with data-widget or similar

**Comment by REJack** [comment]
We have also jsGrid included. But you can use any plugin you want, you only need it install them.

**Comment by SmileYzn** [comment]
Yes that is the point, i do not looked at jsgrid, but basically i do not want to load a lot of html code of tables in these plugins

**Comment by danny007in** [comment]
> 
> 
> Yes that is the point, i do not looked at jsgrid, but basically i do not want to load a lot of html code of tables in these plugins

Any how this procedure will also have the same issue

**Comment by danny007in** [comment]
better to create separate js plugin, so anyone can like https://github.com/mymth/vanillajs-datepicker

**Comment by eerison** [comment]
I'm not sure if this issue was implemented or it was just closed 👀
