### ISSUE TITLE
[FEATURE] Card with image overlay maybe?

### ISSUE THREAD

**Issue by suntong** [ColorlibHQ/AdminLTE#3067]
**Is your feature request related to a problem?**

Card with image overlay would be cool.

**Describe the solution you'd like**

like this:

https://sleek.tafcoder.com/card.html

![image](https://user-images.githubusercontent.com/422244/94737451-d5cf0480-033b-11eb-971a-189462c59078.png)

**Comment by REJack** [comment]
This works already, that comes bootstrap itself. I'll add a example for this.

**Comment by suntong** [comment]
Thanks, for people who don't know bootstrap, like me, we depend all on the demo for what features available, :) :) Thanks for the demo.
