### ISSUE TITLE
AdminLTE ignores anchors and jumps to the page top after the page is loaded [BUG]

### ISSUE THREAD

**Issue by mariannk** [ColorlibHQ/AdminLTE#3070]
**Describe the bug**
AdminLTE ignores anchors and jumps to the page top after the page is loaded

**To Reproduce**
1. Go to https://adminlte.io/themes/AdminLTE/pages/UI/general.html#accordion
2. It jumps to the page top

**Expected behavior**
I expect it should jump here: ![anchor](http://dl3.joxi.net/drive/2020/10/01/0015/3873/1011489/89/30445f5e59.jpg)

**Environment (please complete the following information):**
- AdminLTE Version: The latest one on the demo site
- Operating System:  Windows
- Browser (Version): Chrome (Latest) and others

**Comment by SmileYzn** [comment]
DId you try with from main repository?
I guess that demo is not updated

**Comment by REJack** [comment]
This not a real bug, the div with the id accordion is inside the card body that's why the anchor points exactly after the header.

**Comment by mariannk** [comment]
@SmileYzn thank you for your answer. Yes, seems like it was fixed in the latest version. I downloaded and tested it, and it didn't jump to the page top anymore.
