### ISSUE TITLE
[BUG] Datatable info text does not wrap when viewed on mobile devices or desktop browser's responsive design mode

### ISSUE THREAD

**Issue by TonyThuitai** [ColorlibHQ/AdminLTE#3072]
The Datatable info text i.e _showing x to x of x entries (filtered from x total entries)_ that is at the bottom of the Datatable does not wrap on mobile devices or a desktop browser's Responsive Design mode especially when filtering the Datatable output. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the links provided in the bug description in two tabs of any browser on PC.
2. Press F12 or fn+F12 depending on keyboard configuration to access the browser's developer options on both tabs.
3. Switch to Responsive device Mode icon and select any of the preset smartphone models on both tabs.
4. On both tabs search for any text in the Datatables that have a search box and scroll down to the bottom of the Datatable where the info text is.
5. Compare the info text on both Datatables.

**Expected behaviour**
The info text that is below a Datatable that shows the number of entries and changes when the data is filtered wraps of the text is too long to fit a line on mobile devices as illustrated in the second screenshot.

**Screenshots**
The screenshots below illustrate the issue. The first screenshot is from [AdminLTE Datatable Demo](https://adminlte.io/themes/v3/pages/tables/data.html):

![wrap text issue](https://user-images.githubusercontent.com/64726924/94989505-03a38b80-057e-11eb-8864-67fdb1bf58b9.png)

The second screenshot is from [Datatable.net Boostrap 4 example](https://datatables.net/examples/styling/bootstrap4.html) that shows the correct wrapping of the info text:

![datatable correct info wrap](https://user-images.githubusercontent.com/64726924/94988910-56c70f80-0579-11eb-85f8-412aa9943b23.png)

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.5
- Operating System:  Linux Mint 20 (Ubuntu 20.04 Base)
- Browser (Version): Firefox(Latest), Google Chrome Stable (latest)

**Comment by REJack** [comment]
Thats already fixed in master repo and will released with v3.1.
