### ISSUE TITLE
[BUG] SidebarSearch Form and target attribute of <a>

### ISSUE THREAD

**Issue by zxo102** [ColorlibHQ/AdminLTE#3073]
In my customized AdminLTE, the sidebar menu behaviors correctly and "dashboard.html" is sent to the target :"iframe001" when the `<a>` is clicked,  as shown below: 
```
              <li class="nav-item">
                <a href="cgi.py?requestIds=[]&responseId=adminLTE/pages/dashboard.html" target="iframe001" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v1</p>
                </a>
              </li>
```
But via the searching result from SidebarSearch Form, "dashboard.html" is not sent to the target: iframe001.  It seems the target attribute is not passed to JS backend.

**Environment (please complete the following information):**
- AdminLTE Version: [v3.0.5]
- Operating System:  [Window 10]
- Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
We have no JS plugin that uses a target attribute.

**Comment by REJack** [comment]
I close this issue due inactivity.
