### ISSUE TITLE
[FEATURE] Scrollable navbar dropdown menu and centered when small screen

### ISSUE THREAD

**Issue by donny26utama** [ColorlibHQ/AdminLTE#3080]
Can we got navbar dropdown menu like v2 does?
in v2 dropdown position on after navbar height, active color, scrollable and nearly centered on small screen

v2 does
![image](https://user-images.githubusercontent.com/13846150/95091393-9a27a680-0750-11eb-8c81-5a0090c05bc5.png)
![image](https://user-images.githubusercontent.com/13846150/95091873-2fc33600-0751-11eb-86cb-d68ac9918cf7.png)

we compare with v3
![image](https://user-images.githubusercontent.com/13846150/95092983-76656000-0752-11eb-80c9-1c5f54189abc.png)
![image](https://user-images.githubusercontent.com/13846150/95093133-a44aa480-0752-11eb-8c3e-5ecea378b9e2.png)

**Comment by REJack** [comment]
I've added a new class `.dropdown-offset-legacy` in master repo, this class you can add to `.main-header` to get the correct top offset.

**Comment by donny26utama** [comment]
@REJack great job, thanks. 👍
