### ISSUE TITLE
[FEATURE] navbar search on small screen

### ISSUE THREAD

**Issue by donny26utama** [ColorlibHQ/AdminLTE#3081]
navbar search need improve on small device. can you change it?
rather than like this
![image](https://user-images.githubusercontent.com/13846150/95093807-5f733d80-0753-11eb-999f-45ec4333fab4.png)

become only icon like this
![image](https://user-images.githubusercontent.com/13846150/95094300-f3dda000-0753-11eb-8b57-e71943a848ff.png)

when click the search icon, form will show up
![image](https://user-images.githubusercontent.com/13846150/95094540-356e4b00-0754-11eb-8462-d8de539a757c.png)
and add button remove to back become icon again

**Comment by REJack** [comment]
That's a nice Idea, I will look into this after v3.1 is released to get it released fast 😄.

**Comment by donny26utama** [comment]
@REJack thanks a lot.

**Comment by danny007in** [comment]
> 
> 
> That's a nice Idea, I will look into this after v3.1 is released to get it released fast 😄.

Ill try this feature to implement

**Comment by REJack** [comment]
I've added a new plugin called NavbarSearch with that you can show/hide a search bar over the whole navbar. You can test it on the master branch.
