### ISSUE TITLE
[FEATURE] Top alert boxes

### ISSUE THREAD

**Issue by SmileYzn** [ColorlibHQ/AdminLTE#3083]
Hi, did we can implement header alert notifications?
Like in this page: https://adminlte.io/themes/AdminLTE/index.html

Look at orange (Warning notification)

This can be used for a lot of notifications that needed to display in some pages

Thanks

**Comment by REJack** [comment]
The orange Notify wasn't a implemented alert/notify, it was created by the original author to adverts some payed themes (Affiliate).

In AdminLTE v3, you can simply add an alert at first position in the `.content-wrapper` like this:
```html
<div class="content-wrapper">
    <div class="alert alert-danger rounded-0">This is only a test alert</div>
    ...
</div>
```

![img](https://i.imgur.com/vLVYINE.png)

**Comment by SmileYzn** [comment]
Thanks for repply bro, i think that uses some javascript too, but i will try it here.

Thanks again
