### ISSUE TITLE
[BUG] AdminLTE v3 beforeShowDay of datetimepicker not working

### ISSUE THREAD

**Issue by soloam** [ColorlibHQ/AdminLTE#3085]
**Describe the bug**
Hello I tried the example page https://adminlte.io/themes/v3/ and all works, but when I try to modify the datetimepicker to add beforeShowDay, the function is never called.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/
2. Duplicate page
3. Change $('#calendar').datetimepicker to add beforeShowDay

```
  $('#calendar').datetimepicker({
    beforeShowDay: teste,
    format: 'L',
    inline: true
  });

  function teste(date){
    console.log("RUN");

    return;
  }
```

**Expected behavior**
The beforeShowDay shuld be called, not doing nothing

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.0
- Operating System:  Linux Devia 10
- Browser (Version): Chrome (Latest)

Thank You

**Comment by SmileYzn** [comment]
Try to declare function teste before call datetimepicker

**Comment by soloam** [comment]
I tied both, declare the function, and add the function inline, both show the calendar, but never calls beforeShowDay.

Thank You

**Comment by SmileYzn** [comment]
what is the version that you used?

**Comment by soloam** [comment]
Admin LTE v3... I tested with the example that is on the website

A terça, 13/10/2020, 13:38, Cleverson <notifications@github.com> escreveu:

**Comment by SmileYzn** [comment]
i think that you used a method that do not exists in such plugin?
Since i can't find here: https://tempusdominus.github.io/bootstrap-4/Options/
or
here: http://www.daterangepicker.com/#options

**Comment by soloam** [comment]
I was looking at this
https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#beforeshowday
its
not the same?

Thank You

Cleverson <notifications@github.com> escreveu no dia terça, 13/10/2020 à(s)
13:59:

**Comment by SmileYzn** [comment]
Looking at included js files into theme and js file, you can found:

/**
* @version: 3.0.5
* @author: Dan Grossman http://www.dangrossman.info/
* @copyright: Copyright (c) 2012-2019 Dan Grossman. All rights reserved.
* @license: Licensed under the MIT license. See http://www.opensource.org/licenses/mit-license.php
* @website: http://www.daterangepicker.com/
*/

**Comment by REJack** [comment]
Since AdminLTE v3 we don't use the old "datetimepicker", we replaced it with Tempus Dominus Bootstrap4 as a AIO Date/Time Picker.
