### ISSUE TITLE
[BUG] Simple table not being responsive

### ISSUE THREAD

**Issue by mediantiba** [ColorlibHQ/AdminLTE#3092]
**Describe the bug**
AdminLte 3 Simple Tables are not being responsive, even though I'm using the correct classes for the table.

**To Reproduce**
1. Setup a new project and install AdminLte v3.0.5
2. Add a card with a card header and a card body
3. Add a table inside the card body
4. Add the classes `table-responsive p-0` to the card body
5. Add the classes `table table-hover text-nowrap` to the table element
6. Inspect the result in a small screen, table should be responsive but it's not.

**Expected behavior**
The table should be responsive with the ability to scroll horizontally.

**Screenshots**
![image](https://user-images.githubusercontent.com/11060031/96005608-464e4900-0e45-11eb-8713-043e5d455cca.png)
![image](https://user-images.githubusercontent.com/11060031/96004331-f0c56c80-0e43-11eb-8248-022d7c857909.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.0.5
- Operating System:  Win 10 Pro x64
- Browser (Version): Chrome (Latest), Edge (Latest)

**Comment by SmileYzn** [comment]
Can you show full code? I think that card is placed at incorrect div or something else

**Comment by mediantiba** [comment]
I found out what's causing the issue. First of all, I'm using AdminLte in an Angular project together with a library called ng-bootstrap to get access to Bootstrap functionality in Angular. I removed the Angular part as I wanted to avoid confusion.

As you can see from the screenshot, I am using a `nav nav-pills` to render a vertical menu. It turned out that the table is breaking and overflowing outside the parent container when the menu is vertical. Setting the menu orientation to horizontal fixed the issue.

I assume this can also be reproduced without Angular, since AdminLte already comes with Bootstrap.

**Comment by mediantiba** [comment]
Thanks for the suggestion! But as you can see from the comments, the problem was due to using a vertical navset. Switching to a horizontal navset seems to have solved the issue.
