### ISSUE TITLE
On click of a nav-link item close nav-treeview

### ISSUE THREAD

**Issue by DariusDarvish** [ColorlibHQ/AdminLTE#3094]
**Is your feature request related to a problem? Please describe.**
I am trying to create a method that closes the nav-treeview view whenever I click on a nav-link. When I click the the hide sid nav button I wish to compress all the nav-treeviews.

**Describe the solution you'd like**
I am using Angular, I can use jquery to close the nav-treeview.

**Additional context**
![Screenshot (8)](https://user-images.githubusercontent.com/50785846/96043874-99240280-0e3d-11eb-9629-6b9fdc515d6f.png)
![Screenshot (9)](https://user-images.githubusercontent.com/50785846/96043972-b1941d00-0e3d-11eb-8922-d37f39ecf4c5.png)

**Comment by REJack** [comment]
You mean you want to hide the sidebar sub menu items when collapsed?

**Comment by DariusDarvish** [comment]
Hi, Jack, I was able to get the functionality I need. I was wondering, where in Jquery can I find the method that controls the poping out of the side nav when I hover over it.

**Comment by DariusDarvish** [comment]
So I was able to get the functionality I want. However the symbols for the "nav nav-treeview" do not go back into their starting position.

**Comment by REJack** [comment]
> So I was able to get the functionality I want. However the symbols for the "nav nav-treeview" do not go back into their starting position.

That sounds like your have a bug in your html markup.

**Comment by DariusDarvish** [comment]
The little carrot dropdowns don't turn back into the starting position. Is there a Jquery code I can use to turn it back into it's starting position and if so can you please show me?

**Comment by REJack** [comment]
Please post your html markup of your sidebar, this sounds like you missed a class or misplaced the icon.

**Comment by DariusDarvish** [comment]
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery-1.12.4.min.js">\x3C/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

  <aside class="main-sidebar elevation-4" style="overflow-y: auto!important; overflow-x: hidden!important;"
    (mouseover)="in()" (mouseleave)="out()">


    
    <a routerLink='/login' class="brand-link">

      <span class="brand-text">
        <p><a style="color:#b30404;">AMAZON </a> <a style="color:#ff7b00;"> METRIX</a></p>

        <div class="company-switch">
          <i class="nav-icon far fa-address-card" name="nav-icon-top" style="margin-left: -10px;"></i>
          <select name='companies' [(ngModel)]='companies[0]' (ngModelChange)="onSubmit($event)">

            <option *ngFor="let company of companies" [ngValue]="company">{{company}}</option>
          </select>
        </div>
      </span>
    </a>

    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">

        <li class="nav-item" *ngFor="let x of side_nav_data">
          <a class="nav-link" *ngIf='x.corresponding_parent==null && x.parent==null'>
            <i class={{x.icon}}></i>
            <p style="margin-left:15px" (click)='navigate_to_page(x.corresponding_url, x.pass_param, x.name)'>
              {{x.name}}
            </p>
          </a>
        </li>

        <li class=" nav-item has-treeview" *ngFor="let x of side_nav_data">
          <a class="nav-link" *ngIf='x.parent=="True"'>
            <i class={{x.icon}}></i>
            <p style="margin-left:15px">
              {{x.name}}
              <i class="fas fa-angle-left right" style=margin-top:5px;></i>

            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item" *ngFor="let y of side_nav_data">
              <a routerLinkActive="active" class="nav-link" *ngIf='y.corresponding_parent==x.name' style='color:#b3b3b3'
                (click)='navigate_to_page(y.corresponding_url, y.pass_param, y.name)'>
                <i class={{y.icon}}></i>
                <p>
                  {{y.name}}</p>
              </a>
            </li>


          </ul>
        </li>


      </ul>

    </nav>






  </aside>
</body>

**Comment by REJack** [comment]
Which AdminLTE version you use?

**Comment by DariusDarvish** [comment]
Version 3

**Comment by REJack** [comment]
Then you should not load bootstrap 3 files.

**Comment by REJack** [comment]
I close this issue due inactivity.

**Comment by DariusDarvish** [comment]
So is there any way to fix my issue?
