### ISSUE TITLE
[BUG] Form will not work properly horizontally 

### ISSUE THREAD

**Issue by davidbuckleyni** [ColorlibHQ/AdminLTE#3095]
When I use a form inside a card it will not conform to the form-horizontal properlty

If you look at the field inputs inputColor inputnColor they should be side by side but also should be there labels. But when inside a card it doesnt appear to work showing the screen shot.

You will see the controls are side by side as should but their labels are showing at the top I have a feeling the card class is causing that.
![image](https://user-images.githubusercontent.com/5619229/96264002-a404a180-0fbb-11eb-92f8-8f0ac18db8d4.png)

It should look kinda like how it does here 

http://jsfiddle.net/aguiguy/tK2Q2/

for the colour fields with the labels at the start of the controls not the top of them
    <div class="row">
      <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Product Info</h5>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <div class="btn-group">
                        <button type="button" class="btn btn-tool dropdown-toggle" data-toggle="dropdown">
                            <i class="fas fa-wrench"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <a href="#" class="dropdown-item">Action</a>
                            <a href="#" class="dropdown-item">Another action</a>
                            <a href="#" class="dropdown-item">Something else here</a>
                            <a class="dropdown-divider"></a>
                            <a href="#" class="dropdown-item">Separated link</a>
                        </div>
                    </div>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            
            <div class="card-body">
 
                <form asp-action="Submit"   class="form-horizontal">

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>

                        </div>
                    </div>

                    <div class="control-group">
                        <div class="controls">
                            <label class="checkbox inline " style="padding-left: 10px;" for="inputColor">Favorite Color <input type="text" id="inputColor" class="form-control  span2" /></label>
                            <label class="checkbox inline " style="padding-left: 10px;" for="inputNColor">Next Color <input type="text" id="inputNColor" class="form-control span2" /></label>
                            
                        </div>
                    </div>

                    

                    <div class="form-group row">

                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
                </div>
                
            </div>
                
            </div>
            
            <div class="card-footer">
               
                
            </div>
            
        </div>

**Comment by REJack** [comment]
Your Demo is from Bootstrap 2.2, you can use the old demos in Bootstrap 4. Checkout [this](https://getbootstrap.com/docs/4.5/components/forms/#horizontal-form).
