### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#3097]
Is there any plan to support bootstrap 5

**Comment by SmileYzn** [comment]
In 4.0 i guess

**Comment by puikinsh** [comment]
There is going to be B5 version. But only after the final version of B5 is out. We are not going to support all the alphas an betas because they are not safe for production but are meant for testing only.

**Comment by amon** [comment]
@puikinsh @SmileYzn Hi, is there any estimated release date (or month at least) for the version v3.1.0? I know it's not relevant but I didn't want to create a seperate topic.
