### ISSUE TITLE
[QUESTION] AdminLTE v 3.x and Vue.js: starting from scratch

### ISSUE THREAD

**Issue by piemme** [ColorlibHQ/AdminLTE#3101]
Hi,
I would like to use in my Vue.js project an AdminLTE layout (v 3.x).
How can I start from scratch? I've seen #2633 and #2782 
What's the correct and the cleanest way to proceed?

Thank you in advance!

**Comment by danny007in** [comment]
Vuetify — A Material Design Framework for Vue.js
[https://vuetifyjs.com/en/](url)

If ur using vue v2

**Comment by REJack** [comment]
You can also use Bootstrap-VueJS.
https://bootstrap-vue.org/
