### ISSUE TITLE
Where to disable the scrolling bar on right side of adminLTE window?

### ISSUE THREAD

**Issue by zxo102** [ColorlibHQ/AdminLTE#3105]
Hi, 

As shown below:

[https://adminlte.io/themes/AdminLTE/pages/tables/simple.html](https://adminlte.io/themes/AdminLTE/pages/tables/simple.html)

When window expansion > 80%,   right-side scrolling bar  is there:
![image](https://user-images.githubusercontent.com/9945043/96964592-54832000-153d-11eb-9643-167f868e9e38.png)

When window expansion < 75%,  right-side scrolling bar is gone:
![image](https://user-images.githubusercontent.com/9945043/96964668-754b7580-153d-11eb-84e0-d2d0a9faf1e0.png)

The scrolling bar is also there in my demo  using adminLTE 3: 

![image](https://user-images.githubusercontent.com/9945043/96965638-11c24780-153f-11eb-8a36-926159bddf0e.png)

I read this doc at [https://adminlte.io/docs/3.0/javascript/layout.html](https://adminlte.io/docs/3.0/javascript/layout.html) and still can not get rid of the right-side scrolling bar.

any suggestions? Thanks for your help.

**Comment by REJack** [comment]
I can't replicate this issue, might you have some HTML Markup failures/bugs. Overall if you want to override this you can add the BS4 class `overflow-hidden` to body (I don't recommend this).

**Comment by REJack** [comment]
I close this issue due inactivity.
