### ISSUE TITLE
[QUESTION] AdminLTE v 3.x 当单击比较靠下的导航链接项时，导航会自动跳到top

### ISSUE THREAD

**Issue by douxindong** [ColorlibHQ/AdminLTE#3117]
### 问题：
```
当点击左侧导航栏的比较靠近屏幕底部的选项，或者点击已经超出屏幕底部的选项后，导航栏会自动弹落回top，想点击下一个选项时，还得滑动很长时间才能找到，体验很差。
```
### 建议：
```
增加开关，让左侧导航栏不随着点击选项而改变offset
```
### 见GIF：

![QQ20201103-095106](https://user-images.githubusercontent.com/18432069/97938515-8eb1b480-1dbc-11eb-9fcb-a0080a06dc93.gif)

**谢谢**。

**Comment by ThreeLambs** [comment]
激活的菜单自动垂直居中，菜单正常。内容不应该滚动，哈哈。
这项目好像没人维护的样子，提交个bug一周都没人看

**Comment by zxo102** [comment]
My left navigation bar on index.html works fine. However, I use an iframe to hold different content pages (left navigation bars on those pages are removed).

**Comment by douxindong** [comment]
看提交记录还是挺频繁的。

**Comment by REJack** [comment]
That the correct behavior from the browser, you switch the site and all sites starts on top.

**Comment by douxindong** [comment]
问题没有解决，你的回答太牵强，有没有真正去看我的问题？这种点击了一个选项之后左边的菜单栏也突然下坠的交互方式太low了，左侧的垂直位置不应受点击影响。明白吗？
