### ISSUE TITLE
TodoList plugin API does not call onCheck and onUncheck

### ISSUE THREAD

**Issue by xtremevision** [ColorlibHQ/AdminLTE#3122]
**Describe the bug**
TodoList plugin API does not call onCheck and onUncheck, even though I calling the plugin via the API method.

**To Reproduce**
1. Define a todolist
2. Initialize via the API method
3. Click on any checkbox, no event is triggered
 
**Expected behavior**
On checkbox checked or unchecked my anonymous functions should trigger.

**Screenshots**
See screenshot of code.

**Environment (please complete the following information):**
- AdminLTE Version: 3.0.5
- Operating System:  Windows 10 client, CentOS 8 server
- Browser (Version): Chrome, latest

![2020-11-05 11 43 41](https://user-images.githubusercontent.com/6533394/98269853-3fa28580-1f5c-11eb-8b05-f65d30db1307.png)

**Comment by REJack** [comment]
Please test the v3.1.0-pre (master branch), there should the bug already fixed.
