### ISSUE TITLE
When clicking the menu, the menu will "blink"

### ISSUE THREAD

**Issue by abedputra** [ColorlibHQ/AdminLTE#3126]
Thanks for the great template. 
I want to report when I implement your template, I saw something wrong.

**Describe the bug**
I saw the menu when clicking the menu, the menu will "blink", Please check the gif

**To Reproduce**
when clicking the navbar

**Screenshots**
![blink-navbar](https://user-images.githubusercontent.com/11581453/98831770-f16b1600-2476-11eb-8cc6-a92532747983.gif)

**Environment**
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [macOS Catalina]
- Browser (Version): [Chrome (Latest), also Safari]

Thank you

**Comment by Shidersz** [comment]
I believe this should be left opened, discussion about how to solve this can be found on next link:
https://github.com/jeroennoten/Laravel-AdminLTE/issues/763
