### ISSUE TITLE
Don't close main sidebar on small screen

### ISSUE THREAD

**Issue by cpt-max** [ColorlibHQ/AdminLTE#3127]
Currently the main sidebar collapses when the screen width drops below a certain threshold, which is exactly what I want. What I don't want is that it closes completely when the screen gets even narrower. Is there an easy way to make the sidebar stay collapsed on small screens, and never close it completely?

**Comment by REJack** [comment]
The mini sidebar is only visible for viewport size md and above, not for xs or sm. So you can not get the sidebar visible on small screens.

**Comment by cpt-max** [comment]
Thanks for the info. If I wanted to make that change myself, does that sound doable, or really hard?

**Comment by REJack** [comment]
I've added a extra class for this in master branch, you can simply add `.sidebar-mini-xs` and it will not hide on sm/xs size.

**Comment by cpt-max** [comment]
That's awesome! Thanks so much!
