### ISSUE TITLE
Image in Textarea Error if placed inside popup modal box

### ISSUE THREAD

**Issue by pobtech-official** [ColorlibHQ/AdminLTE#3128]
I placed a textarea (SummerNote) inside a large popup modal box and other form inputs, so the modal was scrollable. But, whenever I tried to add an image in the textarea, the image will be added into the textarea, but the modal isn't scrollable anymore.

Video: [https://drive.google.com/file/d/1PpBFVX0wsPHt_Spf0vjsTHW-ttcNLrX6/view?usp=sharing](https://drive.google.com/file/d/1PpBFVX0wsPHt_Spf0vjsTHW-ttcNLrX6/view?usp=sharing)

Does anybody have the same problem as mine or can anybody help me? Thank you very much.

**Comment by danny007in** [comment]
Paste the code for clear understanding

**Comment by REJack** [comment]
This bug comes from that Summernote uses also the bootstrap modals, you need to add the class `modal-open` after a summernote modal is closed.

Here is a simple script for this:
```js
$(document).on('hidden.bs.modal', '.note-modal', function() {
    if (!$('body').hasClass('modal-open')) $('body').addClass('modal-open');
})
```
