### ISSUE TITLE
Issue: Unable to make card-body contents to a full width with respect to a card width

### ISSUE THREAD

**Issue by abuujurayj** [ColorlibHQ/AdminLTE#3131]
**Describe the bug**
The information within the card-body can not be 100% wide if contents are short in length

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/35935316/99216903-de927180-27e7-11eb-96e8-0ed92db49266.png)

**Comment by danny007in** [comment]
Paste the code for clear understanding

**Comment by REJack** [comment]
I close this issue due inactivity.
