### ISSUE TITLE
Link colors in Nav Tabs [FEATURE]

### ISSUE THREAD

**Issue by miguel-alarcon** [ColorlibHQ/AdminLTE#3132]
In Nav Tabs, i cannot change the accent color to the links, or i don't know how to change this colors. I change the card color-schema, primary, secondary, danger, etc... but the links color of the link inside of the tab.

**Comment by REJack** [comment]
That you control with `.accent-*` on body e.g.`<body class="sidebar-mini layout-fixed accent-purple">`.

**Comment by miguel-alarcon** [comment]
i have already an accent- style in the body tag, all of other links in the page change color, but links color in tabs doesnt change

**Comment by REJack** [comment]
I see what you mean, I've fixed this in master branch and will released with v3.1.0.
