### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by evetsubasa** [ColorlibHQ/AdminLTE#3133]
**Describe the bug**

**To Reproduce**
1. Go to Dashboard / Charts - ChartJS
2. Click on Area Chart & Line Chart 
3. See error: cannot show the information of details

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [e.g. macOS Catalina]
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by danny007in** [comment]
use latest version [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest)
