### ISSUE TITLE
[BUG] Multi Level Menu Error

### ISSUE THREAD

**Issue by tuncaybahadir** [ColorlibHQ/AdminLTE#3134]
**Describe the bug**
Although there is no problem in AdminLTE 3.0.4 version in multilevel menus, all of the menus become open in v3.1.0-pre version. It is being turned on by div Js, which is Display None.

**To Reproduce**
Create a multilevel menu then add the active class next to the has-treeview class on another page, next to menu-open and nav-link class.

**Expected behavior**
The menu of the page that is actively selected in the Multilevel menu must be opened and the others must be closed.

**Screenshots**
![error1](https://user-images.githubusercontent.com/1303432/99524563-a76bbe00-29a9-11eb-995c-52262dea0713.png)
![error1-1](https://user-images.githubusercontent.com/1303432/99525147-793aae00-29aa-11eb-8938-f436ef722f55.png)
![error2](https://user-images.githubusercontent.com/1303432/99524575-ac307200-29a9-11eb-976a-0e4f2f8f8bfe.png)
![error3](https://user-images.githubusercontent.com/1303432/99524583-b05c8f80-29a9-11eb-9183-ef961f54e69f.png)

**Environment**
- AdminLTE Version: v3.1.0-pre
- Operating System:  Windows 10
- Browser (Version): Chrome (Latest), Firefox Developer Editon (Latest)

**Additional context**
To the menu that should be closed, display: none! Important; Even if we say display: block; as inline css is changing. There were no problems with the old versions.

**Comment by danny007in** [comment]
Just you use latest release for production [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) ,
In pre release version might contain bugs,

**Comment by tuncaybahadir** [comment]
thanks for your reply.

I downloaded the file https://github.com/ColorlibHQ/AdminLTE/archive/master.zip.

The problem was fixed when I did the update as you said.
