### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hail812** [ColorlibHQ/AdminLTE#3137]
![image](https://user-images.githubusercontent.com/3158261/99867533-61a33580-2bf5-11eb-8173-93040fb8600d.png)

**Comment by danny007in** [comment]
download latest release [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest)

**Comment by djidji01** [comment]
@danny007in the issue is the same on the latest release whenever max height is `.sidebar` and `($('.sidebar').height() - $('.control-sidebar-content').height()) < $('.main-footer').height()`. Also I think this may the same if max height is `window` with same condition.

**Comment by REJack** [comment]
You can test in the next days the v3.1-rc there is the bug fixed.
