### ISSUE TITLE
Unable to download, threat found by windows defender

### ISSUE THREAD

**Issue by manuvincent** [ColorlibHQ/AdminLTE#3138]
Windows defender detected a backdoor threat while downloading.

Threat detected: Backdoor: Win32/Dirtelti!ml

**Comment by REscobar** [comment]
This was reported a few days ago, but no threats were found when downloading the master branch through the download zip button on the main page.

Can you specify how are trying to download it?
Wich revision?

**Comment by tuncaybahadir** [comment]
The problem occurs when you download the package in the link below on the homepage.

https://github.com/ColorlibHQ/AdminLTE/archive/master.zip

Instead, use the link below for the final compilation.

https://github.com/ColorlibHQ/AdminLTE/releases/latest

I had the same problem. I had no problem when I downloaded it from latest.

**Comment by REscobar** [comment]
That's some weird behavior, I just downloaded from https://github.com/ColorlibHQ/AdminLTE/archive/master.zip which is the 0c3f82b revision and no threats are found by Windows Defender, uploaded to VirusTotal.com and no threats are found neither

https://www.virustotal.com/gui/file/9cb0092e8efcd3fd14264577fb49dca45b937c1e02e5f6c1796fae2c47f0a47c/detection

![image](https://user-images.githubusercontent.com/348416/99920273-02721d80-2ce8-11eb-969a-7672cca803a0.png)

**Comment by tuncaybahadir** [comment]
Could the problem be due to a difference with windows defender updates? I think it might be related to the database not being up to date.

Absolutely ridiculous to warn

**Comment by REscobar** [comment]
Checking for updates reports that I'm on the latest version and no warning is raised, times are UTC-6

![image](https://user-images.githubusercontent.com/348416/99924260-212fde80-2cff-11eb-8073-7abe05013dd8.png)

**Comment by manuvincent** [comment]
Updated defender,
Still showing the warning, when downloading from  [https://github.com/ColorlibHQ/AdminLTE/archive/master.zip](url)


![github-adminlte](https://user-images.githubusercontent.com/39438076/99926372-7b648a00-2d67-11eb-8ebf-d94cd2ff30ec.JPG)
![github-adminlte2](https://user-images.githubusercontent.com/39438076/99926374-7d2e4d80-2d67-11eb-924d-286cd05fe88e.JPG)

**Comment by REscobar** [comment]
I just updated defender again to the same version as in you screenshot and still no threats, would you try uploading to virustotal.com and sharing the url?

**Comment by manuvincent** [comment]
> I just updated defender again to the same version as in you screenshot and still no threats, would you try uploading to virustotal.com and sharing the url?

virustotal.com says the url is clean.
[https://www.virustotal.com/gui/url/940d5238fc71af8202022e023fa2f0d97e734e46ace5524e76ad0f306496f5f8/detection](url)

I was able to download from latest release without any warning.

**Comment by REJack** [comment]
I also can't replicate this issue, my test are all without any virus.

**Comment by REJack** [comment]
I've checked the files again and can't find a virus, for me this looks like you have something in your browser may its a browser extension.
