### ISSUE TITLE
[FEATURE] Sidebar close when collapsed

### ISSUE THREAD

**Issue by amerkoleci** [ColorlibHQ/AdminLTE#3143]
This is more question than bug or feature request, I would like to have the "menu-open" removed and the children collapsed when sidebar menu is closed, somethink like bellow:

![image](https://user-images.githubusercontent.com/1788857/100085672-9c52db00-2e4c-11eb-94b1-7a39c5b1052e.png)

Any thoughts?
Thanks in advance

**Comment by REJack** [comment]
You not need to remove menu-open for this, you can simply add `.nav-collapse-hide-child` to `.nav-sidebar`.

**Comment by amerkoleci** [comment]
Thanks, probably the demo page is not updated (https://adminlte.io/themes/v3/)

Thanks again

**Comment by REJack** [comment]
Yep it will be update with the next release.
