### ISSUE TITLE
Show Modal on Fullscreen Box/Card

### ISSUE THREAD

**Issue by AnNajib** [ColorlibHQ/AdminLTE#3148]
would it be nice if we can show modal when we click bitton on fullscreen card.

**Comment by REJack** [comment]
This is already working.
![grafik](https://user-images.githubusercontent.com/1554582/100318192-f0310180-2fbd-11eb-9f3d-468e492aade7.png)
_Image from latest version (v3.1.0-rc)._

**Comment by AnNajib** [comment]
Love it! Bless You..
