### ISSUE TITLE
[FEATURE] Request to update Summernote plugin to latest version

### ISSUE THREAD

**Issue by NVV-WebManager** [ColorlibHQ/AdminLTE#3149]
**Is your feature request related to a problem? Please describe.**
The latest version of summernote includes a PR that resolves an outstanding issue in the editor where javascript is fired when switching between code and display views.  See [Issue 1462](https://github.com/summernote/summernote/issues/1462) and [PR 3782](https://github.com/summernote/summernote/pull/3782) for more information

**Describe the solution you'd like**
I would like the plugin provided in this package to be updated to the latest release of summernote >= 0.8.18

**Describe alternatives you've considered**
Installing a second version of summernote until it is updated here.  This would only be temporary.

**Additional context**
None.

**Comment by REJack** [comment]
Summernote v0.8.18 is already up-to-date in AdminLTE v3.1.0-rc and will fully released soon.
