### ISSUE TITLE
Footer not really at bottom position of page

### ISSUE THREAD

**Issue by donny26utama** [ColorlibHQ/AdminLTE#3150]
![image](https://user-images.githubusercontent.com/13846150/100305908-b3bcd000-2fd4-11eb-82c1-ed07b33f9887.png)
from this screenshot footer doesnt at bottom position of page.
I found when accessing https://adminlte.io/themes/v3/pages/search/enhanced.html and some place

**Comment by danny007in** [comment]
It has solved [https://github.com/ColorlibHQ/AdminLTE/commit/17aea0e4ef1491a0ae6c3aaa14e81803244b59f2](https://github.com/ColorlibHQ/AdminLTE/commit/17aea0e4ef1491a0ae6c3aaa14e81803244b59f2) here

**Comment by danny007in** [comment]
Ill try this

**Comment by djidji01** [comment]
Nor `.sidebar` touching the the header correctly.

![image](https://user-images.githubusercontent.com/19886674/100318465-c7f9d080-2fc6-11eb-8038-0f496350e873.png)

**Comment by REJack** [comment]
> from this screenshot footer doesnt at bottom position of page.

Thats a calculation bug, I will check this.

> Nor .sidebar touching the the header correctly.

1. Image
This is only a display failure and caused by that we use padding without height, thats stuff I will rework in AdminLTE v4.

2. Image 
Thats the same calculation bug, I will check this.

**Comment by danny007in** [comment]
I found the bug

**Comment by REJack** [comment]
@danny007in please create a PR for this 😄

**Comment by danny007in** [comment]
> 
> 
> @danny007in please create a PR for this 😄

But one issue is, scrollbar will again gets struck

**Comment by REJack** [comment]
the min-height get calculated wrong in Layout.js, when the content is less than sidebar.

**Comment by djidji01** [comment]
> 
> 
> the min-height get calculated wrong in Layout.js, when the content is less than sidebar.

in addition to` overflow-y: auto;` changing this:

```
    if (offset !== false) {
      if (max === heights.controlSidebar) {
        if ($body.hasClass(CLASS_NAME_LAYOUT_TOP_NAV)) {
          $contentSelector.css(this._config.panelAutoHeightMode, (max + offset) + heights.header + heights.footer)
        } else {
          $contentSelector.css(this._config.panelAutoHeightMode, (max + offset))
        }
      } else if (max === heights.window) {
        $contentSelector.css(this._config.panelAutoHeightMode, (max + offset) - heights.header - heights.footer)
      } else {
        $contentSelector.css(this._config.panelAutoHeightMode, (max + offset) - heights.header)
      }

      if (this._isFooterFixed()) {
        $contentSelector.css(this._config.panelAutoHeightMode, parseFloat($contentSelector.css(this._config.panelAutoHeightMode)) + heights.footer)
      }
    }
```

To this 

```
    if (offset !== false) {
      if (max === heights.controlSidebar) {
        $contentSelector.css(this._config.panelAutoHeightMode, (max + offset))
      } else if (max === heights.window) {
        let diff = max - this._max({ sidebar: heights.sidebar, controlSidebar: heights.controlSidebar })

        if (diff > heights.footer) {
          diff = 0
        }

        $contentSelector.css(this._config.panelAutoHeightMode, (max + offset + diff) - heights.header - heights.footer)
      } else if (max === heights.sidebar) {
        const diff = heights.sidebar - heights.controlSidebar

        if (diff < heights.footer) {
          $contentSelector.css(this._config.panelAutoHeightMode, (max + offset) - diff)
        } else {
          $contentSelector.css(this._config.panelAutoHeightMode, (max + offset) - heights.footer)
        }
      } else {
        $contentSelector.css(this._config.panelAutoHeightMode, (max + offset) - heights.header)
      }

      if (this._isFooterFixed()) {
        $contentSelector.css(this._config.panelAutoHeightMode, parseFloat($contentSelector.css('min-height')) + heights.footer)
      }
    }
```

I don't see why the `$body.hasClass(CLASS_NAME_LAYOUT_TOP_NAV)` check!!

**Comment by danny007in** [comment]
> 
> 
> I found the bug
> 
> .sidebar {
> height: calc(100% - (#{$main-header-height-inner} + #{$main-header-bottom-border-width}));
> overflow-y: initial;
> padding-bottom: $sidebar-padding-y;
> padding-left: $sidebar-padding-x;
> padding-right: $sidebar-padding-x;
> padding-top: $sidebar-padding-y;
> }
> 
> to
> 
> .sidebar {
> height: calc(100% - (#{$main-header-height-inner} + #{$main-header-bottom-border-width}));
> overflow-y: auto;
> padding-bottom: $sidebar-padding-y;
> padding-left: $sidebar-padding-x;
> padding-right: $sidebar-padding-x;
> padding-top: $sidebar-padding-y;
> }

just needed to add below this code

body:not(.layout-fixed) {
  .sidebar {
    overflow-y: auto;
  }
}
