### ISSUE TITLE
[QUESTION] How is the website https://adminlte.io/themes/v3/ being used?

### ISSUE THREAD

**Issue by PerryCodes** [ColorlibHQ/AdminLTE#3155]
Is the site located here:
https://adminlte.io/themes/v3/

Being used for active development?  It seems to be changing regularly...  Currently many things working incorrectly related to the new tabbed iframe plugin.

I wouldn't expect this site to change until 3.1 is completed and released.  Is that not the case?

Regards,
Jason

**Comment by PerryCodes** [comment]
I must be blind or it's not possible... but can't seem to find where to remove the 'bug' label accidentally applied when creating this issue.  My apologies.

**Comment by REJack** [comment]
The page  https://adminlte.io/themes/v3/ is on the actual release (v3.1.0-rc) with all coming features.

What exactly work incorrectly with the tabbed iframe plugin?

**Comment by PerryCodes** [comment]
[cid:image001.png@01D6C3B0.A3458130]

When I click the iframe nav item in sidebar, this is shown at the bottom of the iframe.html page.

**Comment by PerryCodes** [comment]
![chrome issues](https://user-images.githubusercontent.com/2401573/100343645-42195d80-2fa5-11eb-9ad7-d6cc29c46fcf.png)

Notice that "No element found!" is always shown under Search regardless of what page you are on.

These issues seem to be happening on Chrome.  I have latest version installed.

**Comment by REJack** [comment]
Mmh :/ try to clear the site cache.

**Comment by PerryCodes** [comment]
Stale cache was in fact my problem.
