### ISSUE TITLE
[BUG] breadcrumb icon in v3.1.0-rc

### ISSUE THREAD

**Issue by sitchi** [ColorlibHQ/AdminLTE#3165]
![Screenshot from 2020-11-29 04-32-46](https://user-images.githubusercontent.com/11546683/100529111-65d6e080-31fd-11eb-8609-ca937ecd85d4.png)

**Comment by REJack** [comment]
Please post your html markup to help you better.

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

**Comment by danny007in** [comment]
> 
> 
> ![Screenshot from 2020-11-29 04-32-46](https://user-images.githubusercontent.com/11546683/100529111-65d6e080-31fd-11eb-8609-ca937ecd85d4.png)

Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

**Comment by REJack** [comment]
@sitchi Wrap your Icon & Text inside a span and the bug is gone.
