### ISSUE TITLE
[FEATURE] Upgrade to Gulp or webpack

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3167]
Because of huge task handling
![gulp](https://user-images.githubusercontent.com/50356015/100534783-9425e180-3238-11eb-9ee9-679470774113.gif)

**Comment by XhmikosR** [comment]
npm scripts are fine IMHO. No need to add another maintenance burden.

**Comment by danny007in** [comment]
Benefits are check [volt-bootstrap-5-dashboard](https://github.com/themesberg/volt-bootstrap-5-dashboard) thoroughly and run once @REJack @XhmikosR  .
It as more time saving features like gulp-file-include etc.
