### ISSUE TITLE
[FEATURE] Move to gulp

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3180]
Benefits are check [volt-bootstrap-5-dashboard](https://github.com/themesberg/volt-bootstrap-5-dashboard) thoroughly and run once @REJack @XhmikosR  .
It as more time saving features like gulp-file-include etc.

**Comment by XhmikosR** [comment]
Since you closed #3167 why would you make a new issue about the same thing?

**Comment by danny007in** [comment]
> 
> 
> Since you closed #3167 why would you make a new issue about the same thing?

Because I forgot to give conclusion
