### ISSUE TITLE
How to change the color code of primary, secondary, etc.. and also add new ones in Angular 11

### ISSUE THREAD

**Issue by RRGT19** [ColorlibHQ/AdminLTE#3188]
**Description**
I'm using Angular with this template and I would like to use the color of our brand for the buttons. That means, we need to change the color code of the primary, secondary, and so on. Also, we have a special color code for special buttons, we would like to add a new name for a new color to the colors options in the template.

**To Reproduce**
When we add the class `btn-primary`, `text-primary` or `bg-primary`, we would like to have this color instead: #EF9D20
The same thing for the rest of the colors, apply them a custom color code.

Also, add a new name for a color, for example `btn-special`, `text-special` and `bg-special`. With the color code: #431612

**What I have tried**
I have added this to the `styles.scss`:
```scss
$theme-colors: (
  "primary": #EF9D20,
  "secondary": #A41E2C,
  "danger": #ff4136,
  "success": #82BC00,
  "warning": #E48200,
);

@import '~bootstrap/scss/bootstrap-reboot';
@import '~bootstrap/scss/bootstrap';
```

But, this way breaks the design of a few elements, making them smaller, bigger or in a different position on the screen. Because of this weird behavior, we discarded this solution.

**Environment:**
- AdminLTE Version: 3.0.5
- Angular 11.0.2

**Additional context**
My goal is:

1. How to change the color code of te primary, secondary, etc...
2. How to add a new name for a color, for example `special`

**Comment by REJack** [comment]
You should overwrite the variables instead of changing the colors inside the $theme-colors array.

Try this scss file:
```scss
// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/build/scss/bootstrap-variables';

// Color Overwrite START
$primary: #EF9D20;
$secondary: #A41E2C;
$danger: #ff4136;
$success: #82BC00;
$warning: #E48200;
// Color Overwrite END

// Custom Theme Color START
$special-color: #00FF00;
$theme-colors: map-merge((
    'special': $special-color,
), $theme-colors);
// Custom Theme Color END

// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/build/scss/variables';
@import '~admin-lte/build/scss/mixins';

@import '~bootstrap/scss/bootstrap';

@import '~admin-lte/build/scss/parts/core';
@import '~admin-lte/build/scss/parts/components';
@import '~admin-lte/build/scss/parts/extra-components';
@import '~admin-lte/build/scss/parts/pages';
@import '~admin-lte/build/scss/parts/plugins';
@import '~admin-lte/build/scss/parts/miscellaneous';
```

**Comment by RRGT19** [comment]
@REJack 
Hi, thanks for your time and for helping me.

Copy & pasting your advice as it is didn't work. No errors while the app is compiling but the colors didn't change.

On the other hand, if I move all the imports at the end of the file, it works. Example:
```scss
// Color Overwrite START
$primary: #EF9D20;
$secondary: #A41E2C;
$danger: #ff4136;
$success: #82BC00;
$warning: #E48200;
// Color Overwrite END

// Custom Theme Color START
/*$special-color: #00FF00;
$theme-colors: map-merge((
  'special': $special-color,
), $theme-colors);*/
// Custom Theme Color END

// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/build/scss/bootstrap-variables';

// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/build/scss/variables';
@import '~admin-lte/build/scss/mixins';

@import '~bootstrap/scss/bootstrap';

@import '~admin-lte/build/scss/parts/core';
@import '~admin-lte/build/scss/parts/components';
@import '~admin-lte/build/scss/parts/extra-components';
@import '~admin-lte/build/scss/parts/pages';
@import '~admin-lte/build/scss/parts/plugins';
@import '~admin-lte/build/scss/parts/miscellaneous';
```

Notice that the part of "Custom Theme Color Start" is commented, that's why I have received the following error:
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
 ), $theme-colors);
     ^^^^^^^^^^^^^
```

This error is because the `@import '~bootstrap/scss/bootstrap';` is at the end of the file. If I move this single import to the top of the file, the error disappear, but, the colors overrides also stopped working.

I have tried different locations for the imports, some at the top, some at the bottom, etc.. and I cannot find how to make it work properly.

Do you have any idea?

**Comment by REJack** [comment]
Try to move this line to the top:

```scss
@import '~admin-lte/build/scss/bootstrap-variables';
```

**Comment by RRGT19** [comment]
@REJack 

With just that line at the top of the file, I receives the following error:
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: theme-color("primary") is not a color.
    ╷
156 │ $link-hover-color:          darken($link-color, 15%) !default;
    │                             ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/admin-lte/build/scss/_bootstrap-variables.scss 156:29  @import
```

Example:
```scss
// Bootstrap
// ---------------------------------------------------
@import '~admin-lte/build/scss/bootstrap-variables';

// Color Overwrite START
// ............
// Color Overwrite END

// Custom Theme Color START
// ............
// Custom Theme Color END

// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';

// Variables and Mixins
// ---------------------------------------------------
@import '~admin-lte/build/scss/variables';
@import '~admin-lte/build/scss/mixins';

@import '~bootstrap/scss/bootstrap';

@import '~admin-lte/build/scss/parts/core';
@import '~admin-lte/build/scss/parts/components';
@import '~admin-lte/build/scss/parts/extra-components';
@import '~admin-lte/build/scss/parts/pages';
@import '~admin-lte/build/scss/parts/plugins';
@import '~admin-lte/build/scss/parts/miscellaneous';
```

The error disappears if I add this line too at the top (but the custom colors not work anymore):
/```scss
/ Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/bootstrap';
@import '~admin-lte/build/scss/bootstrap-variables';

// The rest of the lines below....
```

I'm not sure what is going on.

**Comment by REJack** [comment]
You need not to mentent me in the issues 🤣 I already get notifications about any issue.

Try this: 
```scss
// Bootstrap
// ---------------------------------------------------
@import '~bootstrap/scss/functions';
@import '~admin-lte/build/scss/bootstrap-variables';

// Variables
// ---------------------------------------------------
@import '~admin-lte/build/scss/variables';

// Color Overwrite START
$primary: #EF9D20;
$secondary: #A41E2C;
$danger: #ff4136;
$success: #82BC00;
$warning: #E48200;
// Color Overwrite END

// Custom Theme Color START
$special-color: #00FF00;
$theme-colors: map-merge((
    'special': $special-color,
), $theme-colors);
// Custom Theme Color END

// Mixins
// ---------------------------------------------------
@import '~admin-lte/build/scss/mixins';

@import '~bootstrap/scss/bootstrap';

@import '~admin-lte/build/scss/parts/core';
@import '~admin-lte/build/scss/parts/components';
@import '~admin-lte/build/scss/parts/extra-components';
@import '~admin-lte/build/scss/parts/pages';
@import '~admin-lte/build/scss/parts/plugins';
@import '~admin-lte/build/scss/parts/miscellaneous';
```

**Comment by RRGT19** [comment]
I'm sorry for mentioning you, I thought that the only way you are notified was with a mention. :sweat_smile:

Your last recommendation didn't work, there is no errors and the app compiles properly, but the overrides of colors like primary, secondary, and so on..., disappeared. Now I see primary with the default blue of bootstrap. :pensive:

Seems that to create a new name for a color is more difficult than I thought it would be. If your last solution worked for you, maybe there is a compiling thing in Angular that make things different and while creating the new color is resetting all instead? I don't know... :pensive:

**Comment by glavrjk** [comment]
> I'm sorry for mentioning you, I thought that the only way you are notified was with a mention. 😅
> 
> Your last recommendation didn't work, there is no errors and the app compiles properly, but the overrides of colors like primary, secondary, and so on..., disappeared. Now I see primary with the default blue of bootstrap.
> 
> Seems that to create a new name for a color is more difficult than I thought it would be. If your last solution worked for you, maybe there is a compiling thing in Angular that make things different and while creating the new color is resetting all instead? I don't know.

Hello, this is my implementation changing the primary and secondary color. I use webpack encore

```
$primary: #2E008B;
$secondary: #FF8F1C;
$custom-file-text: (en: "Browse",  es: "Elegir");
@import '~admin-lte';
@import '~@fortawesome/fontawesome-free/css/all';
@import '~datatables.net-bs4';
@import '~datatables.net-responsive-bs4';
@import '~bootstrap-select/sass/variables';
@import '~bootstrap-select/sass/bootstrap-select';
@import '~jquery-steps/demo/css/jquery.steps';
@import '~bootstrap-slider';
@import '~overlayscrollbars/css/overlayscrollbars';
@import '~dropzone/dist/dropzone';
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700');

More Css.

```

Declare variables before all. Later admin-lte, later bootstrap. 😄  Of course your app styles file must be app.scss and your JS Compiler must accept compile SASS files for it's works. Sorry for my bad english 🤣
