### ISSUE TITLE
[BUG] Uncaught ReferenceError: u is not defined

### ISSUE THREAD

**Issue by rashbir** [ColorlibHQ/AdminLTE#3190]
**Describe the bug**
Whenever i Click the option from left menu it's showing the error in console.

admiralv1.js:197 Uncaught ReferenceError: u is not defined
    at HTMLAnchorElement.<anonymous> (admiralv1.js:197)
    at HTMLAnchorElement.dispatch (VM467 jquery.min.js:2)
    at HTMLAnchorElement.v.handle (VM467 jquery.min.js:2)
    at Object.trigger (VM467 jquery.min.js:2)
    at Object.simulate (VM467 jquery.min.js:2)
    at HTMLDocument.i (VM467 jquery.min.js:2)

![image](https://user-images.githubusercontent.com/75464267/101121104-53054700-3615-11eb-9b01-18e6554e3b9e.png)

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

**Comment by danny007in** [comment]
> 
> 
> **Describe the bug**
> Whenever i Click the option from left menu it's showing the error in console.
> 
> admiralv1.js:197 Uncaught ReferenceError: u is not defined
> at HTMLAnchorElement. (admiralv1.js:197)
> at HTMLAnchorElement.dispatch (VM467 jquery.min.js:2)
> at HTMLAnchorElement.v.handle (VM467 jquery.min.js:2)
> at Object.trigger (VM467 jquery.min.js:2)
> at Object.simulate (VM467 jquery.min.js:2)
> at HTMLDocument.i (VM467 jquery.min.js:2)
> 
> ![image](https://user-images.githubusercontent.com/75464267/101121104-53054700-3615-11eb-9b01-18e6554e3b9e.png)

admiralv1.js is not the adminlte

**Comment by rashbir** [comment]
> > **Describe the bug**
> > Whenever i Click the option from left menu it's showing the error in console.
> > admiralv1.js:197 Uncaught ReferenceError: u is not defined
> > at HTMLAnchorElement. (admiralv1.js:197)
> > at HTMLAnchorElement.dispatch (VM467 jquery.min.js:2)
> > at HTMLAnchorElement.v.handle (VM467 jquery.min.js:2)
> > at Object.trigger (VM467 jquery.min.js:2)
> > at Object.simulate (VM467 jquery.min.js:2)
> > at HTMLDocument.i (VM467 jquery.min.js:2)
> > ![image](https://user-images.githubusercontent.com/75464267/101121104-53054700-3615-11eb-9b01-18e6554e3b9e.png)
> 
> admiralv1.js is not the adminlte

It's Not A Issue, I had only renamed the file. How to fix this issue ?

**Comment by REJack** [comment]
Thats not only renamed, that's not our compiled code. Did you recompiled or merge them together with webpack or something else?

**Comment by rashbir** [comment]
> Thats not only renamed, that's not our compiled code. Did you recompiled or merged them together with webpack or something else?
> 
> I we have a variable called `u`.

Can you able to repair this error instead of putting new files. I can share my PC on remote access. Can you please help me on this. Thanks in advance.

**Comment by danny007in** [comment]
> 
> 
> > Thats not only renamed, that's not our compiled code. Did you recompiled or merged them together with webpack or something else?
> > I we have a variable called `u`.
> 
> Can you able to repair this error instead of putting new files. I can share my PC on remote access. Can you please help me on this. Thanks in advance.

Better you hire a Freelancer,
Because its not issue of AdminLTE 😄
