### ISSUE TITLE
[BUG] Transition conflict in sidebar search

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3191]
![qrve1Q47Nj](https://user-images.githubusercontent.com/50356015/101130849-3e7f7980-362a-11eb-9b92-2203e31a7fe7.gif)
![HAOGOpWhZs](https://user-images.githubusercontent.com/50356015/101130852-3fb0a680-362a-11eb-8a2d-a65813ebc5a4.gif)

**Comment by REJack** [comment]
I've fixed this in master branch 😄
