### ISSUE TITLE
[FEATURE] Integration with Adobe XD, Design System Package 

### ISSUE THREAD

**Issue by rasyidf** [ColorlibHQ/AdminLTE#3193]
Bootstrap 5 had already supported with DSP  [here](https://github.com/foxbox-digital/bootstrap-dsp), it's easier for us to follow the styling method. 

will there be a DSP for AdminLTE (Better snippet and better management,  I guess)

Integrating this feature might help us developing better AdminLTE.

**Comment by REJack** [comment]
Thats a nice feature but nothing what is important to implement/create, also I would never implement this into AdminLTE itself its more a external feature same as Sketch.
Feel free to create a DSP 😄.

**Comment by danny007in** [comment]
anyone can create another repo for this 😃 , we add in docs.
because this will become a way complicated

**Comment by olatzglez** [comment]
Hi everyone! Do you know if there is any AdminLTE kit for Adobe XD?
Thanks in advance.
