### ISSUE TITLE
[FEATURE] layout-navbar-fixed AND layout-footer-fixed enhancement aesthetic

### ISSUE THREAD

**Issue by arcanisgk** [ColorlibHQ/AdminLTE#3194]
`layout-navbar-fixed` must add scroll to web content NOT the entire web site:

Expected example:

![image](https://user-images.githubusercontent.com/1207306/101246586-4a2e7700-36e2-11eb-8261-48ff1d9392d0.png)

and also `layout-footer-fixed`  must respect the same rule:

![image](https://user-images.githubusercontent.com/1207306/101246668-c923af80-36e2-11eb-8827-9e9084472812.png)

**Comment by REJack** [comment]
The fixed navbar/footer are positioned with `position: fixed;` this placed the element over other elements, also we do it like bootstrap intended it in the whole framework. In few words: no it's totally correct.

![3lNAz2q](https://user-images.githubusercontent.com/1554582/101262857-d459f800-3741-11eb-9d34-6f13f298a4bc.png)
