### ISSUE TITLE
slow down a bit and wait for BS5

### ISSUE THREAD

**Issue by arcanisgk** [ColorlibHQ/AdminLTE#3195]
I am seeing the updates of this template quite animated; because for version 4 you don't leave BS 4XX aside and wait for the 5.0 release ... it's already in alpha / beta.

after version 3.1 I don't see the point of continuing to add more things that you may not be able to migrate to version 5 of BS.

If you want to have a better impact on the community of new developers, I recommend you launch a version of the template that supports BS5 as close to the launch of BS5.

or at least leave the template versions in parallel:

AdminLTE 3 = support BS up to last version of BS 4
AdminLTE 4 = support BS 5 ....

**Comment by REJack** [comment]
At the moment we are focusing on the v3.1.0 release after this I'll start with the v4.0 development but first I want the RTL support that comes probably with the next BS5 pre-release. 
Overall we will not work on two versions at the same time, if we start with v4 will only deliver fixes for v3.
