### ISSUE TITLE
[FEATURE] UPDATE 

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3205]
![firefox_AARgjhtaww](https://user-images.githubusercontent.com/50356015/101323081-1c863100-388e-11eb-9ffe-ebe27e85cca4.png)

**Comment by REJack** [comment]
I work at the moment on a complete new page 🤣 also idk how I can change this page but it will be replaced soon.
Maybe it will go online with v3.1.0 depending how long it will take but I'm thinking about to wait a week to release AdminLTE may some other users find some bugs.
