### ISSUE TITLE
how to save dashboard cards position

### ISSUE THREAD

**Issue by K1-Aria** [ColorlibHQ/AdminLTE#3206]
in AdminLTE DashboardV1 we can use drag and drop to move cards and change their position. how we can save this changes in database to keeping it?

**Comment by REJack** [comment]
Thats based on your backend and not a question for the Frontend, ask questions like this on Stackoverflow.com.

**Comment by K1-Aria** [comment]
when i change the positions, it should give me DOM changes some way. this is my question.
so its based on frontend

**Comment by REJack** [comment]
Check for this the jquery ui docs for dragable. Thats not a plugin build by AdminLTE.
