### ISSUE TITLE
[BUG] FROM - Vuln Cost - Security Scanner

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3207]
![firefox_uLYnmACHfx](https://user-images.githubusercontent.com/50356015/101456262-cda5cd80-3959-11eb-88b9-37be9ec603e4.png)
![XEYsWu6S4G](https://user-images.githubusercontent.com/50356015/101456267-cf6f9100-3959-11eb-8521-7742ad10923d.png)
![yTgo6cxds4](https://user-images.githubusercontent.com/50356015/101456275-d1d1eb00-3959-11eb-9966-0e32176cbd93.png)

**Comment by REJack** [comment]
Bootstrap Switch v3.4.0 & v3.3.5 do not work correctly that why we stuck on v3.3.4.

Summernote has no fix for this live, we are on the latest version.
