### ISSUE TITLE
[BUG] sidebar light theme, the scroll is invesible

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3208]
![c80H1UagXa](https://user-images.githubusercontent.com/50356015/101475575-968fe600-3972-11eb-9538-c784331a5f9b.gif)

![Code_ROvuMhHlwg](https://user-images.githubusercontent.com/50356015/101476016-1b7aff80-3973-11eb-9af5-1388dd974cb5.png)

**Comment by REJack** [comment]
Thats not a bug, the demo.js doesn't switch the scrollbarTheme. I've added a dirty fix for the demo.js now it works. 😄

**Comment by danny007in** [comment]
> 
> 
> Thats not a bug, the demo.js doesn't switch the scrollbarTheme. I've added a dirty fix for the demo.js now it works. 😄

@REJack  its fixed in demo.js not in 

![0TwbfKWiJw](https://user-images.githubusercontent.com/50356015/101602411-17f38100-3a24-11eb-8788-52e390d905e9.gif)

reopen #3208

**Comment by REJack** [comment]
If you change the class by hand you need to change the scrollbarTheme option too. Thats not a bug.
