### ISSUE TITLE
[BUG] Anchor <a> elements appear blue in 3.1 RC1

### ISSUE THREAD

**Issue by spotnick** [ColorlibHQ/AdminLTE#3209]
Hi!

I´m currently playing around with the 3.1 RC1 and found the new features pretty awesome! But I encountered something which I dont think was intended to be?

For example in the profiles page, alle anchor elements appear in blue: 

![grafik](https://user-images.githubusercontent.com/10115809/101519744-d612fe00-3983-11eb-97b7-80022735df61.png)

The reason for that is obviously this CSS rule:

![grafik](https://user-images.githubusercontent.com/10115809/101520106-4e79bf00-3984-11eb-8abf-1c4f754fe987.png)

I can of course change my elements to use a <span> instead of <a> but I also wanted to ask if the behaviour was inteded? :-)

Thanks a lot for your awesome work!!

All the best
Tom

**Comment by REJack** [comment]
Thats the correct behavior otherwise you wouldn't see that this is a link. 😄

But you can override this with `.text-muted` or other text color classes, or you can change the whole link colors with the accent classes.
