### ISSUE TITLE
[BUG] nodemon v2.0.6 not working parallel in nodejs v14.15.1 LTS

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3212]
Follow link [https://github.com/remy/nodemon/issues/1808](https://github.com/remy/nodemon/issues/1808)

**Comment by REJack** [comment]
I can't replicate this issue, it works like a charm on my machine tested with the latest NodeJS version.

**Comment by danny007in** [comment]
Try to save js files rapidly it will get struck. 
Windows 10 pro 64
nodejs v14.x LTS and also in v15 Lastest
Check https://github.com/remy/nodemon/issues/1827
So remove nodemon and any alternate to implement

**Comment by REJack** [comment]
Is this now fixed with nodemon v2.0.7?

**Comment by danny007in** [comment]
Actually i am using now node v12.

Later on i will tell by using node v14

**Comment by danny007in** [comment]
> 
> 
> Is this now fixed with nodemon v2.0.7?

not working

**Comment by danny007in** [comment]
After using this https://github.com/ianmcnally/npm-run-parallel working
