### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MildaGeorge** [ColorlibHQ/AdminLTE#3215]
AdminLte 3 Tree view plugin activate dynamically by jQuery not working

I have seen treeview plug in of admin lte with ul list implement dynamically by following code

$('ul').Treeview(options) 
but its not working
i have load all required js and css file, please suggest me how dynamically tree view plugin of adminlte activate through jQuery
is there any initialization required or any extra js file nedded

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

**Comment by MildaGeorge** [comment]
really thank you for your

**Comment by danny007in** [comment]
> 
> 
> really thank you for your

u can close the issue

**Comment by MildaGeorge** [comment]
sorry,
Still Tree View issue exist, its work finely with with data api, but while am try to dynamically convert list to treeview by jQuery 
plug in with following code from AdminLte documentation

$('ul').Treeview() not working, I really need to create side bar navigation dynamically, please suggest me what's the problem with my code , is any extra script file needed or any other init function required,
 option is what
please reply am struck with these issues

**Comment by MildaGeorge** [comment]
please help me to solve treeview implementationby dynamic  issue, if possible share jsfiddle

**Comment by danny007in** [comment]
> 
> 
> please help me to solve treeview implementationby dynamic issue, if possible share jsfiddle

Give some more details regarding issue like code, images, gifs to solve issue

**Comment by danny007in** [comment]
> 
> 
> please help me to solve treeview implementationby dynamic issue, if possible share jsfiddle

[https://adminlte.io/docs/3.0/javascript/treeview.html](url)

**Comment by MildaGeorge** [comment]
sir i have go through these document,
 i can implement Tree view plug in using data api like data-widget="treeview" with ul list,
but i want implement these plug in using jQuery by dynamically
and see solution from admin Lte documentation
$("ul").Treeview()
but with these code tree expansion and collapse event not working

**Comment by danny007in** [comment]
https://github.com/ColorlibHQ/AdminLTE/issues/2068 Follow it

**Comment by danny007in** [comment]
> 
> 
> sir i have go through these document,
> i can implement Tree view plug in using data api like data-widget="treeview" with ul list,
> but i want implement these plug in using jQuery by dynamically
> and see solution from admin Lte documentation
> $("ul").Treeview()
> but with these code tree expansion and collapse event not working

![sUtisZtu61](https://user-images.githubusercontent.com/50356015/101988604-a421d480-3cc0-11eb-9bd8-25c8fdb020ce.png)

**Comment by MildaGeorge** [comment]
yes sir, i read these documents, apply jquery treeview plug in but its not working,
i will share my code with you

var mainList=$('<ul id="mainList" class="nav nav-pills nav-sidebar flex-column"></ul>');
	var list=$('<li class="nav-item has-treeview"> <a href="#" class="nav-link active"><p>dashboard</p></a></li>');
	var subList=$('<ul class="nav nav-treeview"></ul>');
	var subli1=$('<li class="nav-item"><a href="#" class="nav-link active"><p>Basic Form</p></a></li>');
	subList.append(subli1);
	list.append(subList);
	mainList.append(list);
	$("#sideNav").append(mainList);

	$('ul.nav-sidebar').Treeview();
please suggest me solution , what's the problem with my code

**Comment by danny007in** [comment]
> 
> 
> yes sir, i read these documents, apply jquery treeview plug in but its not working,
> i will share my code with you
> 
> var mainList=$('
> 
> ');
> var list=$('
> 
> * [dashboard](#)
> 
> ');
> var subList=$('
> 
> ');
> var subli1=$('
> 
> * [Basic Form](#)
> 
> ');
> subList.append(subli1);
> list.append(subList);
> mainList.append(list);
> $("#sideNav").append(mainList);
> 
> ```
> $('ul.nav-sidebar').Treeview();
> ```
> 
> please suggest me solution , what's the problem with my code

Do you inserted this code ` <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">`

**Comment by MildaGeorge** [comment]
my ul list create dynamically
$(function () {
var mainList=$('<ul id="mainList" data-widget="treeview" class="nav nav-pills nav-sidebar flex-column"></ul>');
})
tree events works perfectly out side of $(function(){}) of jquery,
when am implement same code inside
 **_### $(document.)ready(function() {})_** 
Treeview expansion and collision not working

**Comment by danny007in** [comment]
Check out [https://stackoverflow.com/questions/19830689/why-is-the-jquery-script-not-working](https://stackoverflow.com/questions/19830689/why-is-the-jquery-script-not-working)

**Comment by MildaGeorge** [comment]
ya i checked, i have no error found in my page, i think i have no conflict with jquery since i load all script library same order as in your sample index.html page

**Comment by danny007in** [comment]
> 
> 
> my ul list create dynamically
> $(function () {
> var mainList=$('
> 
> ');
> })
> tree events works perfectly out side of $(function(){}) of jquery,
> when am implement same code inside
> **_### $(document.)ready(function() {})_**
> Treeview expansion and collision not working

try 

```js
$(function () {

    var mainList=$('

    ');

    $('ul.nav-sidebar').Treeview();    // on last only, u needed add this

})

```

**Comment by MildaGeorge** [comment]
why jaQuery activation of Treeview not working inside 
$(document.)ready(function() {})
function

**Comment by danny007in** [comment]
> 
> 
> why jaQuery activation of Treeview not working inside
> $(document.)ready(function() {})
> function

[https://stackoverflow.com/questions/5000415/call-a-function-after-previous-function-is-complete](https://stackoverflow.com/questions/5000415/call-a-function-after-previous-function-is-complete) try all method and delete urs replies which are unnecessary for this issue.
