### ISSUE TITLE
[BUG] Sidebar nav child indent after sidebar collapsed

### ISSUE THREAD

**Issue by paul45** [ColorlibHQ/AdminLTE#3228]
**Describe the bug**
after collapse the sidebar 
the nav child are not indent when the sidebar is focus or when the mouse is over sidebar

**Screenshots**
good nav child indent when slidebar isn't collapsed
![image](https://user-images.githubusercontent.com/3822819/102105837-28df3080-3e30-11eb-864e-7bc326c1ea70.png)

no nav child indent when slidebar is collapsed and focus is on the sidebar
![image](https://user-images.githubusercontent.com/3822819/102106591-0dc0f080-3e31-11eb-9719-8b36f06c617e.png)

**Environment :**
- AdminLTE Version: v3

**Comment by danny007in** [comment]
Followw the link https://github.com/ColorlibHQ/AdminLTE/pull/3187

**Comment by REJack** [comment]
That's the excepted behavior, the sidebar-mini has no child Indent while it's collapsed, otherwise there is to much movement and it looks ugly.

**Comment by FelipeEmerim** [comment]
This change did the trick for me:

```
.sidebar-collapse .main-sidebar:hover .nav-sidebar.nav-child-indent .nav-treeview {
    padding-left: 1rem;
}
```

The original was:

```
.sidebar-collapse .main-sidebar:hover .nav-sidebar.nav-child-indent .nav-treeview { 
    padding-left: 0; 
}
```
