### ISSUE TITLE
Proplem with class=row

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3229]
i used .load() jquery
if i use div class=row and the <script>
$('document').ready(function(){
    $('div.all').load('all.php');
});
</script> the col don't working good like the picture 

if i using without div class row it's working perfect any fixing please ??

![Screenshot_2020-12-14 Radius Manager - Administration Control Panel(1)](https://user-images.githubusercontent.com/31727156/102122763-06acd900-3e57-11eb-98cd-651b5ed4064c.png)

thats proplem

how can i fix it please

in version v2 no any proplem 
just in v3

**Comment by danny007in** [comment]
check out https://adminlte.io/docs/3.0/implementations.html

**Comment by muhanadali100** [comment]
Friends ... When i use <div class=row> and script the script doesn't work good it's showing like the picture if i remove div class row it's working perfect 

The row into adminlte v3 has a proplen

**Comment by REJack** [comment]
We need your html code to check it correctly.

**Comment by muhanadali100** [comment]
page1.php
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{ACPMAIN3}</title>
  
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
<script src="plugins/jquery/jquery.min.js"></script>
</head><body>
<p style="font-size:30px"><?php 
echo ' 
        
        <div class="col-lg-3 col-xs-6">
          
		
          <div class="small-box bg-blue">
            <div class="inner">
			
              <h2>' . $num_rows . '</h2>

              <p>Test Balance</p>
            </div>
            <div class="icon">
	       <i class="ion-man"></i>
            </div>
            <a href="users.php" class="small-box-footer">
              More info <i class="fa fa-arrow-circle-right"></i>
            </a>
          </div>
        </div>';
?>

page2.php
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{ACPMAIN3}</title>
  
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
<script src="plugins/jquery/jquery.min.js"></script>
<script>$('document').ready(function(){
    $('div.p1').load('page1.php');
});</script>
<?php
echo '         <div class=row>
<div class="p1"></div>
</div>
?>
that's result
![6](https://user-images.githubusercontent.com/31727156/102245503-b2653000-3f0e-11eb-9e5d-83104f79f6a8.png)

**Comment by danny007in** [comment]
@muhanadali100 Yours Code of https://pastebin.com/UmUNTrPD is this right or else check

```php
page1.php
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{ACPMAIN3}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Google Font: Source Sans
 
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
<script src="plugins/jquery/jquery.min.js"></script>
</head><body>
<p style="font-size:30px"><?php 
echo ' <!-- /.col -->
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
 
		<!-- small box -->
          <div class="small-box bg-blue">
            <div class="inner">
 
              <h2>TEST</h2>
 
              <p>Test Balance</p>
            </div>
            <div class="icon">
	       <i class="ion-man"></i>
            </div>
            <a href="users.php" class="small-box-footer">
              More info <i class="fa fa-arrow-circle-right"></i>
            </a>
          </div>
        </div>';
?>
</body>
</html>
------------------------------------------------------------------------------------------------------
page2.php
 
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{ACPMAIN3}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
<script src="plugins/jquery/jquery.min.js"></script>
<script>$('document').ready(function(){
    $('div.p1').load('page1.php');
});</script>
</head>
<body>
<?php
echo '<div class=row>
<div class="p1"></div>
</div>';
?>
</body>
</html>
```

Actually its problem of migration. 
Check file https://github.com/ColorlibHQ/AdminLTE/blob/master/index.html and replace it

**Comment by muhanadali100** [comment]
> Actually its problem of migration.

i do it but it's same proplem

**Comment by danny007in** [comment]
> 
> 
> > Actually its problem of migration.
> 
> i do it but it's same proplem
> 
> in v2 I never had a problem like this

Because v3 completely rewrites and more different than v2.
So better you change all code to v3.

**Comment by muhanadali100** [comment]
> 
> 
> > > Actually its problem of migration.
> > 
> > 
> > i do it but it's same proplem
> > in v2 I never had a problem like this
> 
> Because v3 completely rewrites and more different than v2.
> So better you change all code to v3.

i change but i have same proplem

**Comment by REJack** [comment]
You have problems with your markup in both files.

1. You can't place any a column in div thats in a row.
2. The whole body code from page2.php is in your div.p1 thats why its so small.
3. In your page2.php: since .load load the html you will not need the complete html markup like html tag or body tag even no javascript or css files are needed there.
4. Always use ids for such fuctions like .load, it's always more secure.

```php
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{ACPMAIN3}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
<script src="plugins/jquery/jquery.min.js"></script>
<script>$('document').ready(function(){
    $('#content').load('page2.php');
});</script>
</head>
<body>
<?php echo '<div class="row" id="content"></div>'; ?>
</body>
</html>
```


page2.php
```php
<?php 
echo '<div class="col-lg-3 col-xs-6">
  <p style="font-size:30px">
    <div class="small-box bg-blue">
      <div class="inner">
        <h2>TEST</h2>
          <p>Test Balance</p>
          </div>
        <div class="icon">
        <i class="ion-man"></i>
      </div>
      <a href="users.php" class="small-box-footer">
        More info <i class="fa fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
</div>';
?>
```
