### ISSUE TITLE
[BUG] iframe.html not working

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3233]
By https://github.com/ColorlibHQ/AdminLTE/commit/120844862fe5eff090f71cdf7c027ab8926e5587

![2FmGk6g2Me](https://user-images.githubusercontent.com/50356015/102252298-ef8beb00-3f2b-11eb-901d-090b7c33e86d.gif)

**Comment by REJack** [comment]
Fixed with #3235.
