### ISSUE TITLE
Proplem in 3.1.0

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3234]
![Screenshot_2020-12-17 Radius Manager - Administration Control Panel(3)](https://user-images.githubusercontent.com/31727156/102445625-fb1b0700-403c-11eb-9d7c-1e6c4bda21c0.png)

![Screenshot_2020-12-17 Radius Manager - Administration Control Panel(2)](https://user-images.githubusercontent.com/31727156/102445627-fd7d6100-403c-11eb-91ea-1e1c77ed02ac.png)

Everything is heading to the left
all form-row and table or box is heading to the left 
just the text inside the table heading to the center

**Comment by danny007in** [comment]
send html code for better understanding

**Comment by muhanadali100** [comment]
`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{ACPMAIN3}</title>
  
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  
  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
<script src="plugins/jquery/jquery.min.js"></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <header class="main-header">
    
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">

    <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="admin.php?cont=change_lang&lang=English" class="nav-link">English</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="admin.php?cont=change_lang&lang=Arabic" class="nav-link">Arabic</a>
      </li>
    </ul>

    
    <ul class="navbar-nav ml-auto">

      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </nav>
  </header>

  
<aside class="main-sidebar sidebar-dark-primary">
    
<section class="sidebar">
      
      <div class="user-panel">
        <div class="float-left image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="float-left info">
          <p>{ACTMANAGER}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online </a>
		  <a href="#"><i class="fa fa-circle text-faild"></i>{DATE}</a>

        </div>
      </div>  
      
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>      

  
  <aside class="main-sidebar sidebar-dark-primary elevation-4">

    
<div class="sidebar">
      
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="images/bg1.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">ADVANCED NET</a>
        </div>
      </div>
     
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

       
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          
          <li class="nav-item menu-open">
            <a href="admin.php" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                {MENU0000}
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="users.php" class="nav-link">
              <i class="nav-icon fas fa-user"></i>
              <p>
                {MENU01}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="users.php" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0100}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="users.php?val=0" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{AAAA16}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="users.php?val=1" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{AAAA6}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="users.php?val=4" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU9191}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="users.php" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0101}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="new.php" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0102}</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                {MENU02}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_services" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0200}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=new_service" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0201}</p>
                </a>
              </li>
            </ul>
          </li>

        <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-smile"></i>
              <p>
                {MENU03}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">2</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_managers" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0300}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=new_manager" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0301}</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-sitemap"></i>
              <p>
                {MENU04}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">2</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_nases" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0400}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=new_nas" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0401}</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-signal"></i>
              <p>
                {MENU05}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">2</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_ap" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0500}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=new_ap" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0501}</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-wifi"></i>
              <p>
                {MENU07}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">2</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_pools" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0700}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=new_pool" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0701}</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-square"></i>
              <p>
                {MENU09}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_cardseries" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0900}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=list_users&listacctype=4" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0901}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=list_refillcards" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0902}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=search_refillcards" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0903}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=cardgen" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0904}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=cardstats" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU0905}</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-eye"></i>
              <p>
                {MENU11}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">10</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=list_online_radius" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1100}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=traffic_report" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1102}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=search_traffic_data" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1103}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=search_traffic_summary" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1104}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=search_cts_data" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1105}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=search_postauth" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1106}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=quick_syslog" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1107}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=list_syslog" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1108}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=sysinfo" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1109}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=sysstats" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1110}</p>
                </a>
              </li>
            </ul>
          </li>

         <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tools"></i>
              <p>
                {MENU12}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="admin.php?cont=show_bulkmail" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1200}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=show_bulksms" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1201}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=start_radius_server" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1202}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=stop_radius_server" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1203}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="admin.php?cont=restart_radius_server" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{MENU1204}</p>
                </a>
              </li>
            </ul>
          </li>	
	              <li class="nav-item">  
            <a href="admin.php?cont=logout" class="nav-link">
              <i class="nav-icon fas fa-sign-out-alt"></i>
              <p>
                Logout
              </p>
            </a></li>

          <li class="nav-header">LABELS</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-danger"></i>
              <p class="text"><b>Balance {BALANCE} <b> {CURRENCY}</p>
            </a>
          </li>
          <li class="nav-header">Language</li>
          <li class="nav-item">
            <a href="admin.php?cont=change_lang&lang=English" class="nav-link">
              <i class="nav-icon far fa-circle text-success"></i>
              <p class="text"> <b> &nbsp;English</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="admin.php?cont=change_lang&lang=Arabic" class="nav-link">
              <i class="nav-icon far fa-circle text-success"></i>
              <p class="text"> <b> &nbsp;Arabic</p>
            </a>
          </li>
        </ul>
      </nav>
    </section>
    
  </aside>

  
  <div class="content-wrapper">
    
    <section class="content-header">
     {CONTENT}   
    </section>
  </div>
  
  <footer class="main-footer">
    <div class="float-right d-none d-sm-inline-block">
    <b>{ACPMAIN0}</b> {ACTMANAGER} | <b>{ACPMAIN1}</b> {DATE} | <b>{ACPMAIN2}</b> {VER} | <b>{ACPMAIN4}</b> {RADSTATUS} | <b>{ACPMAIN5}</b> {DHCPDSTATUS}
    </div>
    <strong>Copyright &copy; 2020 <a href="http://192.168.183.129">ADVANCED NET</a>.</strong> All rights
    reserved.
  </footer>

  
  <aside class="control-sidebar control-sidebar-dark">
    
  </aside>
  
</div>



<script src="plugins/jquery/jquery.min.js"></script>

<script src="plugins/jquery-ui/jquery-ui.min.js"></script>

<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>

<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="plugins/chart.js/Chart.min.js"></script>

<script src="plugins/sparklines/sparkline.js"></script>

<script src="plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>

<script src="plugins/jquery-knob/jquery.knob.min.js"></script>

<script src="plugins/moment/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>

<script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>

<script src="plugins/summernote/summernote-bs4.min.js"></script>

<script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

<script src="dist/js/adminlte.js"></script>

<script src="dist/js/demo.js"></script>

<script src="dist/js/pages/dashboard.js"></script>
</body>
</html>
`

if the {CONTENT} is form-row or table it's heading to the left

**Comment by kabutotx** [comment]
I do notice all your {CONTENT} is under content-header div and not content div

**Comment by muhanadali100** [comment]
> 
> 
> I do notice all your {CONTENT} is under content-header div and not content div

What differentiates?

**Comment by REJack** [comment]
Content Header only contains a header with optional breadcrumbs, this is also options you not need it.
Content contains the content thats why it called content 😄

**Comment by kabutotx** [comment]
I also see problem where you have your navbar wrapped in a <header> tag.
You also have 2 sidebars. 1 in a section and 1 in a div. Everything on the left side should be in 1 sidebar div.
Checkout starter.html or index.html.

**Comment by muhanadali100** [comment]
> 
> 
> Content Header only contains a header with optional breadcrumbs, this is also options you not need it.
> Content contains the content thats why it called content 😄

i change it do div class=content

thanx

**Comment by muhanadali100** [comment]
> 
> 
> I also see problem where you have your navbar wrapped in a header tag.
> You also have 2 sidebars. 1 in a section and 1 in a div. Everything on the left side should be in 1 sidebar div.
> Checkout starter.html or index.html.

i remove header tag 
and remove div section

thanx

**Comment by danny007in** [comment]
@muhanadali100 does this error still exist

**Comment by muhanadali100** [comment]
> 
> 
> @muhanadali100 does this error still exist

no it's working now good thanx
