### ISSUE TITLE
A cgi issue with adminLTE/iframe.html in AdminLTE 3.1.0

### ISSUE THREAD

**Issue by zxo102** [ColorlibHQ/AdminLTE#3244]
adminLTE/index.html works fine and RMR.html is processed in the backend and sent back to the iframe of "iframe001" after modifying adminLTE/index.html as follows:
  ```
 ...
  <li class="nav-item">
    <a href="cgi.py?requestIds=[]&responseId=system/drag-drop/RMR.html&SID=0x17689e315ed&pageId=adminLTE/iframe.html" target="iframe001" class="nav-link">
     <i class="far fa-circle nav-icon"></i>
     <p>RMR</p>
    </a>
  </li>
  ...
 <div class="content-wrapper">
    <iframe id="iframe001" name="iframe001" src=""></iframe>
 </div>
 ...
```

But just adding the same code into adminLTE/frame.html without `target="iframe001"` and `<iframe></iframe>` yields an error in DevTools of Chrome:

```
  <li class="nav-item">
    <a href="cgi.py?requestIds=[]&responseId=system/drag-drop/RMR.html&SID=0x17689e315ed&pageId=adminLTE/iframe.html" class="nav-link">
    <i class="far fa-circle nav-icon"></i>
    <p>RMR</p>
    </a>
  </li>
<!-- target="iframe001" is removed -->
```
I got an error in DevTools of chrome and href is as follows:
 
`Uncaught Error: Syntax error, unrecognized expression: panel-cgi.py?requestIds=[]&responseId=system-drag-drop-RMR&SID=0x17689e315ed&pageId=adminLTE-iframe.html-911 iframe`

It looks like "RMR.html" -> "RMR", "/" -> "-",...

- AdminLTE Version: [v3.1.0]
- Operating System:  [Windows10]
- Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
Fixed with f8ce13b9fa0196973ec7aa20cebd868bafdf1ee6.
