### ISSUE TITLE
[BUG] Dark theme, Datatable, Different accent color

### ISSUE THREAD

**Issue by FoxxenDev** [ColorlibHQ/AdminLTE#3248]
Hi! On the datatable pagination, with the dark mode activated and for exemple a cyan accent color selected, the word "Previous" and "Next" is like in light theme

1. Go to Datatable pages
2. Activate dark mode
3. Set a different accent color than the base one
4. Select the first or the last page with pagination

Expecting to be disabled but in dark not in light

![Screenshot_26](https://user-images.githubusercontent.com/32935159/103033394-a9a1d900-4562-11eb-8302-ab06644aa4e8.png)

![Screenshot_28](https://user-images.githubusercontent.com/32935159/103033400-aad30600-4562-11eb-99bc-0fc2ab2aedda.png)

- AdminLTE Version: V3.1.0-rc
- Browser (Version): Chrome (latest)

Thank in advance and sorry for the english. Have a great day !

**Comment by REJack** [comment]
Fixed in 47fa82fec3ee07b243eb6772ce4b76c1cfb8442d.
