### ISSUE TITLE
[BUG] Content height

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3249]
This coz of error and needed to remove or modify if  https://github.com/ColorlibHQ/AdminLTE/blob/656dbcd25231553ca716722c2c948b03c1af77f5/build/js/Treeview.js#L55

![1KMa2b22c5](https://user-images.githubusercontent.com/50356015/103103803-b0574b80-4649-11eb-8b29-e0e39841bcb9.gif)

**Comment by REJack** [comment]
I've fixed this issue with 955d89b.
