### ISSUE TITLE
[BUG] Tabbed IFrame Plugin not working in some of browsers

### ISSUE THREAD

**Issue by safen** [ColorlibHQ/AdminLTE#3266]
The  [Tabbed IFrame Plugin](https://adminlte.io/themes/v3/iframe.html) not working in some of the browsers like 
MI browser the Xiaomi mobile browsers tested on Xiaomi  MI 9
and  [Blisk browser ](https://blisk.io/)  tested on windows 10 
the issue is it won't navigate between pages  

https://user-images.githubusercontent.com/6255437/103287334-5234ba80-49f3-11eb-9897-658e209ea7c3.mp4

**Comment by danny007in** [comment]
Check out https://github.com/ColorlibHQ/AdminLTE/issues/3233

**Comment by REJack** [comment]
This bug comes from old browser engines that doesn't support `String.replaceAll()`.
I've added a fix for this with f378e2f359b6fcf031e70f57807786bcdd3b2146.
