### ISSUE TITLE
Happy New Year

### ISSUE THREAD

**Issue by REJack** [ColorlibHQ/AdminLTE#3271]
Hey folks 👋,

I wish you all a happy new year and good luck 🍀 for the new year.

P.S. I will release the next release (v3.1.0) in the first january week.

**Comment by ger88555** [comment]
Happy New Year, and thanks for this beautifully amazing tool you made <3

**Comment by AliShareei** [comment]
Hi @REJack, 
Happy New Year to you too,
Please consider this PR #3293 for the new version of AdminLTE.
