### ISSUE TITLE
[FEATURE] Discussion forum pages or forum UI elements

### ISSUE THREAD

**Issue by stodge** [ColorlibHQ/AdminLTE#3274]
**Is your feature request related to a problem? Please describe.**

I'm prototyping a website that uses forums, and not being a UI expert or CSS expert, I'd appreciate some UI elements that could be used to build a forum page or an example of a forum page.

**Describe the solution you'd like**

This is difficult to describe as I'm not sure how the pages should look, but right now, I have two pages:
 * view forum - shows forum title, child forums and any topics
 * view topic - shows topic title and content and any replies, plus pagination

**Describe alternatives you've considered**

I've tried building some forum pages using the elements currently available via AdminLTE 3 but the results are not good.

**Additional context**
N/A

**Comment by danny007in** [comment]
You can send Any Demo link from any websites 🕵🏼  regrading of urs "Describe"

**Comment by REJack** [comment]
That's a nice idea but it will not be added in v3, since we'll start with v4 development soon.

**Comment by stodge** [comment]
Ok, thanks for replying.
