### ISSUE TITLE
Css class .sidebar-wrapper

### ISSUE THREAD

**Issue by alexkuc** [ColorlibHQ/AdminLTE#3286]
While scrolling through docs, I have come across [Layout page](https://adminlte.io/docs/3.1//layout.html) which mentions `.sidebar-wrapper` used as a container for sidebar.

I believe this should removed from the docs as [this class is not used in the source code](https://github.com/ColorlibHQ/AdminLTE/search?q=.sidebar-wrapper)?

**Comment by danny007in** [comment]
Can u create PR for it

**Comment by danny007in** [comment]
For Docs development check https://jekyllrb.com/ and run `npm docs-serve`

**Comment by alexkuc** [comment]
PR created https://github.com/ColorlibHQ/AdminLTE/pull/3292
