### ISSUE TITLE
Including dependencies (plugins)

### ISSUE THREAD

**Issue by alexkuc** [ColorlibHQ/AdminLTE#3287]
On the [docs page](https://adminlte.io/docs/3.1/dependencies.html), there is a mention:

> Note! You need to load the js/css files of the plugin that you want to use. AdminLTE doesn’t load automatically all plugins, this would cause huge load times on every page load.

How to decide which page would require which plugin? Should example pages be used as guidance (`pages/`)?

I know this may sound silly but I wanted to double check to avoid (accidentally) omitting any important dependencies (plugins).

**Comment by danny007in** [comment]
Its https://jekyllrb.com/ is has some limitations

**Comment by danny007in** [comment]
> How to decide which page would require which plugin? Should example pages be used as guidance (pages/)?

It's dependent on there requirement, and in demo pages there will be have example so worry about that
