### ISSUE TITLE
[QUESTION] Where's plugins folder?

### ISSUE THREAD

**Issue by jogunism** [ColorlibHQ/AdminLTE#3288]
Hi!
I've just update to AdminLTE 3.1 and plugins folder has vanished.

I used to import the js/css what I needed like this.

import "admin-lte/plugins/jquery/jquery.min.js";
import "admin-lte/plugins/jquery-ui/jquery-ui.min.js";
import "admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js";
import "admin-lte/plugins/fontawesome-free/css/all.min.css";
import "admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css";

where are they?

**Comment by jogunism** [comment]
version: 3.1

**Comment by REJack** [comment]
The plugins folder is still there, you only don't load the plugins via npm there you copy the plugins files automatically while installing AdminLTE. This change is not only since v3.1.0 it's there since v3.0.0 😄.

**Comment by jogunism** [comment]
Thanks the reply!

I tried just import this. "admin-lte/dist/js/adminlte.min.js" but, 
other things didn't work. - font-awesome, jQuery etc.. 

I'm using Vue3 + typescript and adminLTE 3.1
before update the new version, it works well.

**Comment by danny007in** [comment]
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by jogunism** [comment]
@danny007in 
Hi.

I installed the library by yarn.

And, this is my project folder.
<img width="770" alt="screenshot" src="https://user-images.githubusercontent.com/8444942/103881384-a9651a00-50da-11eb-843a-0128a75584a0.png">
as you can see, the plugin folder has vanished.

Actually, there's nothing special in my code.
I've just imported the libraries like this.

```
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

import "admin-lte/plugins/jquery/jquery.min.js";
import "admin-lte/plugins/jquery-ui/jquery-ui.min.js";
import "admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js";
import "admin-lte/plugins/fontawesome-free/css/all.min.css";
import "admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css";

createApp(App)
  .use(store)
  .use(router)
  .mount("#app");
```

And... build error for can not find these files. ;/

**Comment by danny007in** [comment]
Take a look 👀 

![Annotation 2021-01-07 170730](https://user-images.githubusercontent.com/50356015/103888556-f06b0380-510a-11eb-8c9f-4a9d74ccba15.png)

**Comment by jogunism** [comment]
OMG.
What was the problem... :0

okay.
I'll try re-install all of it.
Many thanks!

**Comment by danny007in** [comment]
- delete yarn.lock and node_modules folder
- clear npm and yarn caches
- restart PC

**Comment by jogunism** [comment]
@danny007in @REJack 

haha... Shame on me..

It works.

Thank you so much!
Happy new year! ;D

**Comment by danny007in** [comment]
> - delete yarn.lock and node_modules folder
> - clear npm and yarn caches
> - restart PC

Does this solution worked

**Comment by jogunism** [comment]
@danny007in  
yes. 
Delete node_module, yarn.lock and cache and re-installed.
(I should have done it first.)

Thanks. ;D

**Comment by medeepaksaini** [comment]
@danny007in this issue is closed, you may also close this issue
