### ISSUE TITLE
[BUG] It cannot display the page "in iframe mode " when use python with flask .

### ISSUE THREAD

**Issue by qianlicao8000** [ColorlibHQ/AdminLTE#3295]
**Describe the bug**
 It cannot display the left side menu linkiing page "in iframe mode " when use python with flask .

**Comment by danny007in** [comment]
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by qianlicao8000** [comment]
In chrome “respect”source ,I find the code generated :the tab iframe's height is 0px.see the pic.
![caputure](https://user-images.githubusercontent.com/10287340/104123138-4bf3f600-5384-11eb-8c0c-e93c27104655.JPG)

**Comment by danny007in** [comment]
Which version Of adminLTE

**Comment by danny007in** [comment]
i mean rc to main

**Comment by qianlicao8000** [comment]
Uploading 202111020467rec.mp4…

**Comment by qianlicao8000** [comment]
AdminLTE-3.1.0-rc

**Comment by danny007in** [comment]
> 
> 
> AdminLTE-3.1.0-rc

Check in master branch 'npm run dev'

**Comment by qianlicao8000** [comment]
Not use npm,just download the git code,then use the code files in project .

**Comment by danny007in** [comment]
It as fixed in master branch,
And will be released soon in stable version

**Comment by qianlicao8000** [comment]
OK,thanks .Hope the stable version.

**Comment by danny007in** [comment]
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3266
