### ISSUE TITLE
Add Expand (fullscreen) / Compress box-widget

### ISSUE THREAD

**Issue by rainje** [ColorlibHQ/AdminLTE#332]
Hi,

I added this widget to my website and it works great, I think this could be a nice small addition to the project ;)

![widgets](https://cloud.githubusercontent.com/assets/1025666/7089277/f48a29ba-df9a-11e4-945e-c979c05e2966.png)

I'm not doing a pull request since my way of doing it may not be the best.

```
boxWidgetOptions: {
      boxWidgetIcons: {
        //The icon that triggers the collapse event
        collapse: 'fa fa-minus',
        //The icon that trigger the opening event
        open: 'fa fa-plus',
        //The icon that triggers the removing event
        remove: 'fa fa-times',
        //The icon that triggers the maximize event
        maximize: 'fa fa-expand'
      },
      boxWidgetSelectors: {
        //Remove button selector
        remove: '[data-widget="remove"]',
        //Collapse button selector
        collapse: '[data-widget="collapse"]',
        //Expand button selector
        maximize: '[data-widget="maximize"]'
      }
    },
```

```
//Listen for maximize event triggers
        $(o.boxWidgetOptions.boxWidgetSelectors.maximize).click(function (e) {
          e.preventDefault();
          _this.maximize($(this));
        });
```

```
maximize: function (element) {
        function maximizer(n) {
          if (n) {
            var t = $(window).height(),
                i = n.find(".box-header").height();
                n.find(".box-body").height(t - i)
          }
        }
        var t = element.parents(".box").first(),
            i = element.find("i").first(),
            r = "fa-compress",
            u = "fa-expand";
        t.hasClass("maximized") ? (i && i.addClass(u).removeClass(r), t.removeClass("maximized"), t.find(".box-body").css("height", "auto")) : (i && i.addClass(r).removeClass(u), t.addClass("maximized"), maximizer(t))
      }
```

```
.maximized {
    z-index: 9999;
    width: 100%;
    height: 100%;
    position: fixed;
    top: 0;
    left: 0;
}
```

**Comment by adaniello** [comment]
:+1:

**Comment by almasaeed2010** [comment]
Looks interesting. I will look into it and add it to the todo list if I find it appropriate. Thanks for the contribution!

**Comment by almasaeed2010** [comment]
Do you think it is possible to add transitions to the plugin to make it animate through states?

**Comment by rainje** [comment]
It should be, not sure if it's worth it though.

**Comment by YasserHassan** [comment]
@almasaeed2010 it would be nice also to include an option to expand the page to a full-screen mode.

**Comment by bpchia** [comment]
why I added but not working? no error message when I debugs F12 in chrome, when I press, the page refresh. anything I miss? not really good in javascript & css, tqvm

**Comment by rainje** [comment]
@bpchia this is almost a year old, it might not work with current adminlte version.

**Comment by sajanojha** [comment]
@rainje 
this seems like a very nice function. It works  really great. But it does not work when we have sortable divs. Any thought on that?

@almasaeed2010 My personal view is that this is a great addition to the dashboard. Have you thought to plug this one in? 

Let me know your views.
thanks

**Comment by mpavkovic** [comment]
So, what happened with this suggestion? Was it implemented? Because if it is there is no mention about it in the docs.

**Comment by rainje** [comment]
Afaik it was just closed.

**Comment by bulabula001** [comment]
thanks for shared

**Comment by inaf** [comment]
Thanks for shared, work great

**Comment by REJack** [comment]
I've added this feature in v3-dev, you can test it [here](https://adminlte.io/themes/dev/AdminLTE/pages/widgets.html)

It's still WIP, the maximize/minimize animation is not perfect, but it works 😄

**Comment by bpchia** [comment]
> I've added this feature in v3-dev, you can test it [here](https://adminlte.io/themes/dev/AdminLTE/pages/widgets.html)
> 
> It's still WIP, the maximize/minimize animation is not perfect, but it works 😄

It work great! when I can have this release version?

**Comment by REJack** [comment]
I‘ll create soon the v3.0.0-beta.1 release and publish it on npmjs and packagist.
