### ISSUE TITLE
add toastr using angular

### ISSUE THREAD

**Issue by Wuzzeke** [ColorlibHQ/AdminLTE#3345]
Hi,

I want to use a toastr. First I tried the ngx-toastr but then the toastr is displayed outside my template (bottom under my footer).
Then I looked at the toastr info of adminLte but I want to know how to use it in Angular. In fact I have a form and when pressing the submit button it should show a toastr when the form is invalid. Can somebody help me with tips on this?

Thanks in advance.
An

**Comment by REJack** [comment]
Please ask in the toastr/ngx-toastr repo for questions about toastr or ngx-toastr.
