### ISSUE TITLE
[FEATURE] sidebar search result  createTab after click

### ISSUE THREAD

**Issue by ttqiadmin** [ColorlibHQ/AdminLTE#3346]
use  iframe.html , when user click  "list-group-item" in the "sidebar-search-results",  sometimes want to  create a new Tab  .please consider the FEATURE.

**Comment by danny007in** [comment]
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by ttqiadmin** [comment]
Thanks for replying so quickly。

![image](https://user-images.githubusercontent.com/15372627/105665139-4f08ed80-5f11-11eb-8fd4-fa75e878d590.png)

Possibly associated code is  At line 1132 of  adminlte.js  
`return "<a href=\"" + link + "\" class=\"list-group-item\">\n  `
， it will Open in current window,    but i want to open a new tab .

**Comment by danny007in** [comment]
We can add this issue v3.2.x

**Comment by REJack** [comment]
Done, added 😄 it totally forgot this.
