### ISSUE TITLE
[BUG] iFrame content heigh on zoom in and shifting to next/prev tabs

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3382]
https://user-images.githubusercontent.com/50356015/107137014-4e6b5080-692e-11eb-84a0-a05fef025eca.mp4

**Comment by REJack** [comment]
Fixed with 1b66775d4bcddefb0c97b60b537c5e65290d8532

**Comment by REJack** [comment]
@danny007in can you send me an email to discuss the first steps for AdminLTE v4 development?

**Comment by danny007in** [comment]
> 
> 
> @danny007in can you send me an email to discuss the first steps for AdminLTE v4 development?

Check email

**Comment by danny007in** [comment]
sended to this info@rejack.de @REJack
