### ISSUE TITLE
[BUG] On IFrame Mode the Menu Search doesn't open the page inside tab -> iframe

### ISSUE THREAD

**Issue by decodethis** [ColorlibHQ/AdminLTE#3383]
**Describe the bug**
When using the menu item search In IFrame Mode, on item selection the page isn't open as  a iframe

**Comment by REJack** [comment]
Sounds like #3346

**Comment by decodethis** [comment]
Yes your right.. Will close it

**Comment by REJack** [comment]
It's already fixed, try the master and build the JS plugins.
