### ISSUE TITLE
[FEATURE] On Iframe Mode, check for tab already open

### ISSUE THREAD

**Issue by decodethis** [ColorlibHQ/AdminLTE#3384]
Control if a tab related to a menu item is already open and don't allow to open duplicates

**Comment by REJack** [comment]
Added with 472c1622cfa3762202edc1d3d5192914377ccc8d

**Comment by huskier** [comment]
If the opened tab is through URL(say, django's URL, like "/accounts/userinfo/"), there will be a new tab appear whenever we click the sidebar item(like the following item). Still do not know how to avoid the new tabs.
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/accounts/userinfo/" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Basic Info</p>
                </a>
              </li>
