### ISSUE TITLE
[BUG] Datatables tags isn't correct with original one's

### ISSUE THREAD

**Issue by XDavidT** [ColorlibHQ/AdminLTE#3397]
**Describe the bug**
The styling for Datatables in 'pages/tables/data.html' is showing 'ul' 'li' tags, when the datatables using only 'a' tags and 'span' tags.

**To Reproduce**
It's can be showed in the the file.
Activate datatables with the table in 'pages/tables/data.html'

**Expected behavior**
See the paging as it's show in html file

**Screenshots**
2 First - the AdminLTE file
2 Last - Me using angular+ Datatables with original CSS (since the css isn't working with this)
https://imgur.com/a/Y8JoyuY

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0-rc
- Operating System:  Windows
- Browser (Version): Firefox [last]

**Additional context**
Try to change the type of paging by datatables but didn't found any option...
The screen shot show differnce.

**Comment by REJack** [comment]
Idk but I would say this comes from the difference between `paging_simple_numbers` & `paging_full_numbers`. You should check your angular datatables configuration.

**Comment by XDavidT** [comment]
> Idk but I would say this comes from the difference between `paging_simple_numbers` & `paging_full_numbers`. You should check your angular datatables configuration.

It's just configuration to tell how many pages you want to see in there, but not the of the HTML tags..

**Comment by REJack** [comment]
First of all, did you use the datatables bootstrap overrides in your angular project? If not it could cause the css file bug/error.
Second if you have style override problems we can help you otherwise with JS problems you should ask at the used plugin repo.

**Comment by XDavidT** [comment]
> 
> 
> First of all, did you use the datatables bootstrap overrides in your angular project? If not it could cause the css file bug/error.
> Second if you have style override problems we can help you otherwise with JS problems you should ask at the used plugin repo.

Ok jsut forget from my datatables, even the HTML tags in datatables.net not the same.
It's look like you didn't activate any Datatables in your page, or it's not mention to Datatables.net ?

**Comment by danny007in** [comment]
@XDavidT if issue solved u can close 😄

**Comment by XDavidT** [comment]
> @XDavidT if issue solved u can close 😄

Sure, but it didn't, the HTML tags in AdminLTE is not familiar with the regular HTML tags of Datatables.net

**Comment by REJack** [comment]
That's normal that the HTML Tags are not the same as on Datatable.net, that's caused by the Bootstrap overrides from Datatables also the configuration changes some HTML Markups.

That's why I said ask at the datatables repo, we didn't modified Datatable.
