### ISSUE TITLE
[FEATURE] - Sidebar Menu Search - case and accent insensitive

### ISSUE THREAD

**Issue by decodethis** [ColorlibHQ/AdminLTE#3398]
**Is your feature request related to a problem? Please describe.**
Menu search should have the possibility to configure case and accent in order to be insensitive in both cases

**Comment by danny007in** [comment]
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by decodethis** [comment]
Hi. It's just to be accent insensitive, because it's already case insensitive

When i search the menu on the "mainsidebar-searcher", for instance:

 - In Portuguese:
      -  Countries is 'Países' - i want to be able to search with 'paises'
      -  Sessions is 'Sessões' -  'sessoes'

   or can i place at the menu item html the value without accents and set the searcher for that property ?

**Comment by danny007in** [comment]
Actually you needed to type exact word.
It an limitation 😃
