### ISSUE TITLE
[FEATURE] Tab close button and tab right click (close all, all except this)

### ISSUE THREAD

**Issue by decodethis** [ColorlibHQ/AdminLTE#3399]

**Comment by danny007in** [comment]
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by decodethis** [comment]
Hewe is an example of both situations.
Close button in each tab and a mouse right click on the tab with several options (Close other tabs...)


![image](https://user-images.githubusercontent.com/78700702/107621116-ad420a00-6c4d-11eb-9b23-559e29ee0e42.png)

**Comment by danny007in** [comment]
Nice 👍🏼 
Probably this will be implement in v3.1.1

**Comment by REJack** [comment]
I've enhanced the close button with e9ee4e5e17c45618d5b4336bd3b8d9f607743cf7.
![Bildschirmfoto 2021-02-17 um 09 18 57](https://user-images.githubusercontent.com/1554582/108175590-3f8c5700-7101-11eb-9622-c023b782ebba.png)

A context menu (right click) is a nice idea, I will add this to the feature list for v4.

**Comment by decodethis** [comment]
There is a major functionality that i would like not to be forgotten.
 - Close button on the tab itself, (ex: an X on the top right corner of the tab)
 - Ex: right now if i have 5 tabs open and i want to close one in the middle i have to select it first and then press the left close button.

**Comment by REJack** [comment]
@decodethis I've added a close button to the nav tabs, you can try it 😄

**Comment by decodethis** [comment]
Hi @ReJack.

Can you point me where is the tab close button (x) ?
Updated master branch and can’t find it?

**Comment by REJack** [comment]
Did you compiled the dist files?

**Comment by decodethis** [comment]
Yes. Also the "Close All Other" is doing the opposite.
It's closing only the active one.

**Comment by decodethis** [comment]
![image](https://user-images.githubusercontent.com/78700702/109501906-2c2da400-7a90-11eb-906d-fec4b3056795.png)

**Comment by danny007in** [comment]
@REJack can u create an new branch `conpled-3.1` and we can compile  in that branch
