### ISSUE TITLE
 [Feature] Keep only one tab page shown no matter how actions we triggered from the sidebar command.

### ISSUE THREAD

**Issue by huskier** [ColorlibHQ/AdminLTE#3401]
Hi,

I think the side-bar-click and the tab function in the IFrame-mode are somewhat duplicate, and I wonder whether it is possible to only display the current side-bar-click triggered page, not the tabbed pages?

Thanks.

Youbao

**Comment by danny007in** [comment]
simply click once 😄

**Comment by huskier** [comment]
Thanks for your quick response, danny007in. I meant that if I clicked the following three side-bar-command, then three tabbed pages are opened. However, I only want to just display one of the tree pages, not the tabbed three pages.
* Dashboard v1
* Dashboard v2
* Dashboard v3

It is not a bug, but I just do not know how to remove the type:bug label.

Thanks.
Youbao

**Comment by huskier** [comment]
Hi Daniel, 

Could we only keep only one tab page shown no matter how actions we triggered from the left-side-bar command?

Thanks.
Youbao

**Comment by danny007in** [comment]
> 
> 
> Hi Daniel,
> 
> Could we only keep only one tab page shown no matter how actions we triggered from the left-side-bar command?
> 
> Thanks.
> Youbao

That mean, no use of iframe

**Comment by danny007in** [comment]
Ok we can add new feature like `max-tab` to iFrame

**Comment by huskier** [comment]
Thanks for your consideration, Daniel.
If the max-tab is set to 1, every time we triggered a command from the left-sidebar, only one tab is displayed? 
Specifically, 
Trigger "Danshboard V1", the IFrame load page of "Dashboard V1" only;
Trigger "Danshboard V2", the IFrame load page of "Dashboard V2" only.
We're looking forward to this behavior.

Best regards,
Youbao

**Comment by danny007in** [comment]
can u change issue title 👍🏼

**Comment by REJack** [comment]
For this you don't need the IFrame Mode, the IFrame mode is for tabbed IFrames not only single IFrame. You should simply create a small javascript to get your feature.

**Comment by danny007in** [comment]
> 
> 
> For this you don't need the IFrame Mode, the IFrame mode is for tabbed IFrames not only single IFrame. You should simply create a small javascript to get your feature.

Add in docs

**Comment by huskier** [comment]
@danny007in Hi Daniel, have you added this in the docs? We can not find the related contents in the docs.

**Comment by danny007in** [comment]
> 
> 
> @danny007in Hi Daniel, have you added this in the docs? We can not find the related contents in the docs.

@huskier check https://stackoverflow.com/questions/11556571/prevent-click-event-from-firing-multiple-times-issue-with-fading
and
in js 
add condition if (<Those html>) exist then click event should not work
