### ISSUE TITLE
[Question] How to set the treeview expand by default?

### ISSUE THREAD

**Issue by huskier** [ColorlibHQ/AdminLTE#3405]
Hi,

We want to expand part of the treeviews when loading the page. We've tried the following approaches:
1. Put 'active' in `<li> <ul> <a>`'s classes, no useful;
2. Put the following code in the ready function, in vain.
```
   <script>
        $(document).ready( function() {
            $('ul').Treeview(expandSidebar="true");
        });
  </script>
```
3. Put data attribute "data-expand-sidebar="true"" in the` <ul>` element, no useful.
`<ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false" data-expand-sidebar="true">`

All the above three approaches are in vain.

We think there should be a simple way to control this behavior. Any help are appreciate.

Thanks.
Youbao

**Comment by Elghamed** [comment]
use class "menu-open" along side with "nav-item"

`<li class="nav-item menu-open">
       <a href="#" class="nav-link">
            <i class="nav-icon fas fa-users"></i>
            <p>
                   Users
                   <i class="right fas fa-angle-left"></i>
           </p>
     </a>
     <ul class="nav nav-treeview">
              <li class="nav-item">
                   <a href="#viewUsers" class="nav-link">
                           <i class="far fa-list-alt nav-icon"></i>
                           <p>View Users</p>
                   </a>
             </li>
     </ul>
</li>
                        `

**Comment by huskier** [comment]
Thank you, Elghamed. This solved my problem!
