### ISSUE TITLE
[ACTIONS] add bundlewatch

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3407]

**Comment by REJack** [comment]
Thats already built-in with the CI workflow on node 12.

**Comment by danny007in** [comment]
i have been tested in local machine it shows error

**Comment by REJack** [comment]
What kind of error?

**Comment by danny007in** [comment]
> 
> 
> What kind of error?

after build 
https://ja2r7.app.goo.gl/TbKN3hWF8qCHkXyaA

**Comment by danny007in** [comment]
node v14 and windows 10

**Comment by REJack** [comment]
Thats not a error, that is the point of bundlewatch. It looks like your adminlte.core.min.css is exactly on the maximum size, bundlewatch doesn't like that. 🤣

**Comment by danny007in** [comment]
Exactly
bundlewatch work's in this type case differently

**Comment by REJack** [comment]
But it would not make a difference if you add it as seperate action.
