### ISSUE TITLE
[BUG] Weird card horizontal sizes on contact page when horizontal resolution is high

### ISSUE THREAD

**Issue by codot-fr** [ColorlibHQ/AdminLTE#3424]
**Describe the bug**
Hello. When the horizontal resolution exceed a particular threshold, the card size seem to be different from a card to another.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/pages/examples/contacts.html
2. Enlarge the window until the cards start to space out

**Expected behavior**
I guess the cards should extend to fit the entire screen with an equal width

**Screenshots**
![cards-ok](https://user-images.githubusercontent.com/39614999/107924054-a596a400-6f72-11eb-8b08-4d187222f5d1.PNG)
![cards-nok](https://user-images.githubusercontent.com/39614999/107924061-a7606780-6f72-11eb-821c-5e046ebd259c.PNG)

**Environment (please complete the following information):**
- AdminLTE Version: 3.0.5 and online 3 version
- Operating System:  Windows 10
- Browser (Version): Chrome (Latest)

**Additional context**
- Resolution : 3440*1440

**Comment by REJack** [comment]
Did you Zoomed In/Out, for me it looks like your zoom level is 75%.

**Comment by danny007in** [comment]
I think so its zoom out issue

**Comment by codot-fr** [comment]
Nop, 100%.

![Clipboard01](https://user-images.githubusercontent.com/39614999/107957703-4308cc80-6fa1-11eb-9080-0fafa1ca37b6.jpg)


Also, Chrome 88.0.4324.150

**Comment by REJack** [comment]
Fixed with 26136409f1889fb6dd752984c21ade7757f58774.
