### ISSUE TITLE
[BUG] npm ERR! notarget - No matching version found for datatables.net-keytable@2.6.1

### ISSUE THREAD

**Issue by RRGT19** [ColorlibHQ/AdminLTE#3428]
**Describe the bug**
```
 % npm install admin-lte@3.0.5 --save
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for datatables.net-keytable@2.6.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'datatables.net-keytable-bs4'
npm ERR! notarget 
```

**To Reproduce**
Try to install using: `npm install admin-lte@3.0.5 --save` or using `npm install admin-lte@^3.1 --save`.

**Expected behavior**
That the installation finishes successfully.

**Screenshots**
None.

**Environment:**
- AdminLTE Version: v3.0.5
- Operating System:  macOS Catalina
- Browser (Version): Chrome (Latest)
- NPM: v6.14.11
- Node: v12.18.4

**Additional context**
I have tried:
1. rm -rf node_modules
2. Delete `package-lock.json` file
2. npm cache clean --force
3. npm install
4. npm install admin-lte@3.0.5 --save

Didn't work.

How can we workaround or fix this?

**Comment by danny007in** [comment]
clear npm cache

**Comment by RRGT19** [comment]
> clear npm cache

Tried it and didn't work. Still cannot install AdminLTE, same error.

**Comment by danny007in** [comment]
https://nodejs.org/en/ install LTS version

**Comment by RRGT19** [comment]
datatables.net-keytable@2.6.1 is listed as tag [here](https://github.com/DataTables/Dist-DataTables-KeyTable/tags), but this specific version is not listed in NPM [here](https://www.npmjs.com/package/datatables.net-keytable).

Maybe this is the issue?

**Comment by RRGT19** [comment]
> https://nodejs.org/en/ install LTS version

I have tried it and didn't work.

I have updated from v12.18.4 to v14.15.5 with no results.

![Screen Shot 2021-02-18 at 3 06 41 PM](https://user-images.githubusercontent.com/33521443/108408193-1d76ff80-71fb-11eb-9bf7-94533ede0102.png)

**Comment by danny007in** [comment]
its issue of DataTable
Report there 😃

**Comment by RRGT19** [comment]
You are right, there is an issue [here](https://datatables.net/forums/discussion/67089/no-matching-version-found-for-datatables-net-keytable-2-6-1).

I don't know why AdminLTE is trying to download the v2.6.1. I don't know what else to try.

**Comment by armin-ch-m** [comment]
I have the same issue here too!

**Comment by DataTables** [comment]
I'm not sure why our npm publish failed for that repo - apologies. It passed for all the other related ones. Possibly something transient in the network. Its [done now though](https://www.npmjs.com/package/datatables.net-keytable/v/2.6.1).

**Comment by RRGT19** [comment]
> I'm not sure why our npm publish failed for that repo - apologies. It passed for all the other related ones. Possibly something transient in the network. Its [done now though](https://www.npmjs.com/package/datatables.net-keytable/v/2.6.1).

Now is working/installing correctly. Thanks for your quick feedback.

**Comment by danny007in** [comment]
Fixed at https://github.com/DataTables/Plugins/issues/515
