### ISSUE TITLE
why the iframe don't working with php ?? 

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3433]
the iframe doesn't work with php , just with html why ??

**Comment by REJack** [comment]
what kind of error you get?

**Comment by muhanadali100** [comment]
![Screenshot_2021-02-19 User Active](https://user-images.githubusercontent.com/31727156/108521952-525b8300-72dd-11eb-82ed-187bbae2e088.png)

showing blank page

if i used html page it's working good
but if used php showing blank page

**Comment by REJack** [comment]
check console (F12)

**Comment by danny007in** [comment]
fixed in https://github.com/ColorlibHQ/AdminLTE/issues/3402

**Comment by muhanadali100** [comment]
i used the latest update and it's not working

**Comment by danny007in** [comment]
wait for nexr release or compile https://github.com/ColorlibHQ/AdminLTE#contributing
