### ISSUE TITLE
[BUG] parameter issue at switchTab method in iFrame.js

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3434]
one argument
https://github.com/ColorlibHQ/AdminLTE/blob/3d488f173f95f8583c1c36253fa8dea38156ea85/build/js/IFrame.js#L157

but here two arguments
https://github.com/ColorlibHQ/AdminLTE/blob/3d488f173f95f8583c1c36253fa8dea38156ea85/build/js/IFrame.js#L111
https://github.com/ColorlibHQ/AdminLTE/blob/3d488f173f95f8583c1c36253fa8dea38156ea85/build/js/IFrame.js#L116

**Comment by REJack** [comment]
Remove the second argument, it’s not used the function anymore.

**Comment by REJack** [comment]
I’m not at home, otherwise I would remove it quick 😂😂

**Comment by danny007in** [comment]
ok i will remove and test it
