### ISSUE TITLE
[BUG]  Sidebar toggle not working after fixing sidebar treeview

### ISSUE THREAD

**Issue by PabloDSL2** [ColorlibHQ/AdminLTE#3451]
**Describe the bug**
I have a project usign adminLTE components and everything worked fine, the only problem that I had was that the treeview of the sidebar was not working in the first load of a page. (for example, after login changing the view to another component).

I solved that issue using a fix (https://github.com/ColorlibHQ/AdminLTE/issues/1570#issuecomment-409022326) and now the threeview works fine but another problem poped out.

The toggle button that hides/shows the sidebar does not work anymore, is there something that I have to do?

**Expected behavior**
Sidebar toggle button work even with the treeview fix

**Environment**
- AdminLTE Version: v3.0.4
- Operating System:  Windows 10 Home
- Browser (Version): Chromium Edge (lastest)

**Additional context**
Project made with Angular 9.1.1 using lazy loading.

**Comment by REJack** [comment]
Beside initializing the TreeView you need to initialize PushMenu & Layout too

**Comment by PabloDSL2** [comment]
> Beside initializing the TreeView you need to initialize PushMenu & Layout too

Do you have a example of how to do that? Im Using angular 9 

I tried doing this 
`ngAfterViewInit() {
    $('[data-widget="treeview"]').each(function() {
        AdminLte.Treeview._jQueryInterface.call($(this), 'init');
    });
    AdminLte.Layout._jQueryInterface.call($(this), 'init');
    AdminLte.PushMenu._jQueryInterface.call($(this), 'init');
  }`

and this

`ngAfterViewInit() {
    $('[data-widget="treeview"]').each(function() {
      AdminLte.Treeview._jQueryInterface.call($(this), 'init');
      AdminLte.Layout._jQueryInterface.call($(this), 'init');
      AdminLte.PushMenu._jQueryInterface.call($(this), 'init');
    });
  }`

but neither of them worked

**Comment by PabloDSL2** [comment]
I somehow found how to do it. just put this code in the component.ts of the topbar

`declare var $: any`

`changeStatusMenu(){`
`    $('[data-widget="pushmenu"]').PushMenu('toggle')`
` }`

and in the html 

`<a class="nav-link" (click)="changeStatusMenu()" data-widget="pushmenu" role="button"><i class="fas fa-bars"></i></a>`

Is not the best fix but it worked, now when you first load the proyect sidebar treeview and toggle button will work as they should
