### ISSUE TITLE
[Question] Change IFrame tab title dynamically 

### ISSUE THREAD

**Issue by navtek** [ColorlibHQ/AdminLTE#3457]
Hi guys, I've been playing around with the new Tabbed IFrame widget and it's awesome. One thing I would like to ask, is it possible to update the title of the current tab from the page loaded inside the iFrame?.

i.e. I open a page to register a user, then I type the new username as 'john' so in this case the tab title would be something like User - john. 

This is something I see multiple tabs of the same page would benefit of.

Keep up the good work! :)

**Comment by danny007in** [comment]
ofcourse u can do u with urs custom js
and
wait for next release
