### ISSUE TITLE
[BUG] in "docs" > "Components" > "Direct Chat" > "card-tools" > "button" Please correct "collapse" and remove

### ISSUE THREAD

**Issue by MojtabaFaal** [ColorlibHQ/AdminLTE#3468]
hello

in "docs" > "Components" > "Direct Chat" > "card-tools" > "button" 

Please correct "collapse" and "remove" :
Replace "**data-widget**" with "**data-card-widget**"

Mistake = [Link](https://adminlte.io/docs/3.1//components/direct-chat.html)
Correct = [Link](https://adminlte.io/themes/v3/index2.html)

False :
`<button type="button" class="btn btn-tool" data-widget="collapse">`
True :
`<button type="button" class="btn btn-tool" data-card-widget="collapse">`

False :
`<button type="button" class="btn btn-tool" data-widget="remove">`
True :
`<button type="button" class="btn btn-tool" data-card-widget="remove">`

thanks

**Comment by danny007in** [comment]
can u create PR 😃

**Comment by MojtabaFaal** [comment]
**PR** ?
what do you mean ?

**Comment by danny007in** [comment]
> 
> 
> **PR** ?
> what do you mean ?

Pull request

**Comment by MojtabaFaal** [comment]
I do not know
Can you do it yourself?

**Comment by REJack** [comment]
Fixed 😄  also the CSS pointer was still incorrect 🤦🏼

**Comment by MojtabaFaal** [comment]
Thanks
