### ISSUE TITLE
[BUG] Menu level 3 shaking when selected

### ISSUE THREAD

**Issue by LucivalSoares** [ColorlibHQ/AdminLTE#3469]
When we open the submenu of level 3, and the option "Sidebar nav child hide when collapsing" is active, and we are going to open a level 3 menu, the menus are shaking, why? is there a correction for that?

.nav-collapse-hide-child bug

**Comment by danny007in** [comment]
send video

**Comment by LucivalSoares** [comment]
added nav-collapse-hide-child: https://file.re/2021/03/02/adminlte-3--dashboard---treme/

no added nav-collpase-hide-child: https://file.re/2021/03/02/adminlte-3---nao-treme/

**Comment by danny007in** [comment]
send directly in github

**Comment by LucivalSoares** [comment]
added nav-collapse-hide-child:

https://user-images.githubusercontent.com/75479578/109697031-7f752480-7b6c-11eb-8c1f-41ff74be738e.mp4

**Comment by LucivalSoares** [comment]
no 

https://user-images.githubusercontent.com/75479578/109697121-99166c00-7b6c-11eb-81fb-24524ff2a9ab.mp4

added nav-collapse-hide-child:

**Comment by danny007in** [comment]
add issue title.

**Comment by LucivalSoares** [comment]
thanks for the guidance i'm new to github

**Comment by REJack** [comment]
That’s a browser bug related to the fade animation, I found since 1 year no fix :/.
