### ISSUE TITLE
[BUG] [IFrame model]  throw exception when Delete IFrame tab by delete icon

### ISSUE THREAD

**Issue by ThreeLambs** [ColorlibHQ/AdminLTE#3470]
![Snipaste_2021-03-03_15-51-48](https://user-images.githubusercontent.com/23123048/109771956-646fe680-7c38-11eb-8452-c4aa61712a5a.png)
![Snipaste_2021-03-03_16-10-48](https://user-images.githubusercontent.com/23123048/109774206-10b2cc80-7c3b-11eb-9ed3-f61112a33f5a.png)

there are two ``<a>``, this should be :
```
removeActiveTab(){
 this.switchTab($navItemParent.children().eq(prevNavItemIndex).find('a.nav-link'))
}
```

And I think the  delete icon should show when mouseMoveIn ,and should be center vertically on the right  witch is beautiful then now.

**Comment by REJack** [comment]
Fixed and Added 🤣 you can try it
