### ISSUE TITLE
[BUG]Sidebar Search Plugin ：can't search chinese

### ISSUE THREAD

**Issue by ThreeLambs** [ColorlibHQ/AdminLTE#3473]
Chinese language search is not supported ?!

**Comment by REJack** [comment]
Idk how to give chinese language support for this, may you can help with it.

**Comment by danny007in** [comment]
Can search only needed to type exact words

**Comment by danny007in** [comment]
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by danny007in** [comment]
@ThreeLambs 
its working u needed to write more than 3 characters/letter/words 
😃
