### ISSUE TITLE
[BUG]How to click a link without open in Iframe tab

### ISSUE THREAD

**Issue by ThreeLambs** [ColorlibHQ/AdminLTE#3474]
i have some link in in nav-header , i want to add a class notIframe which not call the method 'openTabSidebar'.
 some open in  Iframe ,some not .
example , the switch language dropdown link which not open in iframe.

**Comment by REJack** [comment]
You want to exclude header items? If yes, simply add `data-use-navbar-items="true"` beside the `data-widget="iframe"` like the `data-loading-screen="750"`.

**Comment by ThreeLambs** [comment]
There are two links in the header navbar . One is open with iframe and the other not.

**Comment by REJack** [comment]
That’s actually not possible, but I will add this feature to AdminLTE v4.

**Comment by danny007in** [comment]
closing issue because https://github.com/ColorlibHQ/AdminLTE/issues/4580
