### ISSUE TITLE
[BUG]IFrame-mode sidebar function cannot work on Android's Firefox, iPad's Edge browsers. 

### ISSUE THREAD

**Issue by huskier** [ColorlibHQ/AdminLTE#3475]
**Describe the bug**
The main desktop browsers(Chrome(88), Firefox(86.0), Edge(88)) can work properly for IFrame-mode sidebar function. However, the IFrame-mode sidebar function cannot work on Android's Firefox, iPad's Edge browsers. The page can be loaded, but there is no tab pages are loaded when we click the items in the sidebar.

**To Reproduce**
1. Just access the IFrame-mode sidebar page through an Android's Firefox or an iPad's Edge browser. (Maybe there are other browsers that the IFrame-mode sidebar function cannot work, but we have not tested them)

**Environment (please complete the following information):**
- AdminLTE Version: [The latest master, dbf73e0 commit version]
- Operating System:  [The django server is on a Red Hat Enterprise Linux 7.x.]
- Browser (Version): [We access the IFrame-mode sidebar page from an Android (7.0, Firefox 58.0 for android.) or an iPad(Edge 46.1 for iPad version)]

**Comment by danny007in** [comment]
update browser

**Comment by huskier** [comment]
After recompiling the AdminLTE-3.1.0-rc, the IFrame-mode sidebar function can work on mobile browsers. However, the layout for the tabs part is not the same as in the desktop browsers. The following screenshot is captured from a Firefox browser on an Android phone. We've tried several other browsers(Android: chrome, edge; iPad: safari, firefox, edge, chrome), they all give the unexpected layout style like the screenshot below. Maybe some adjustments are needed for the mobile browsers.
![AdminLTEonMobileBrowsers](https://user-images.githubusercontent.com/5828575/110243025-9a440080-7f93-11eb-87d9-aa8ac7f4a091.png)

**Comment by danny007in** [comment]
recompiling master branch https://github.com/ColorlibHQ/AdminLTE

**Comment by huskier** [comment]
My fault, actually, I use the latest master branch for the test. The above mentioned AdminLTE-3.1.0-rc is actually the latest master branch.

**Comment by huskier** [comment]
Thank you for the attention. @danny007in @REJack 
Are the  tab-titles(Tab-1, Tab-2) display in vertical style intended?
After the "Fix: visible issue in touch device on iframe #3491", the tab-titles still displayed in verticle style, not the same as in the desktop browsers which display in horizontal style, that means all the tab-titles displayed in the same line, including "<<" and ">>" symbols.

**Comment by danny007in** [comment]
another clear image plz or video

**Comment by danny007in** [comment]
Fixed in https://github.com/ColorlibHQ/AdminLTE/pull/3496

**Comment by huskier** [comment]
Now, the style is the same for both mobile browsers and desktop browsers.

The magic line:
<div class="nav navbar navbar-expand navbar-white navbar-light border-bottom p-0">

Thank you, Daniel and Jack. @danny007in  @REJack

**Comment by REJack** [comment]
I'll add a style override for this later.
