### ISSUE TITLE
[Question] Still issues for the two solved issues.

### ISSUE THREAD

**Issue by huskier** [ColorlibHQ/AdminLTE#3476]
We think that the following two issues are still issues there.

1. [FEATURE] On Iframe Mode, check for tab already open #3384
    If the opened tab is through URL(say, django's URL, like "/accounts/userinfo/"), there will be a new tab appear whenever we click the sidebar item(like the following item). Still do not know how to avoid the new tabs.
```
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/accounts/userinfo/" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Basic Info</p>
                </a>
              </li>
```
2. Close button on the tab itself, (ex: an X on the top right corner of the tab) in iFrame #3426
    This issue is taged with "state: done", however, for the latest dbf73e0 commit version, we cannot see the "Close button on the tab itself". Do I download the wrong commit version?

Thanks.

**Comment by REJack** [comment]
Both of the point are already fixed, please reclone/redownload the master branch and recompile your files.

**Comment by huskier** [comment]
@REJack , Hi Jack, according to your reply, we have to compile the production, and it is not enough to just clone the master into local. Right?

We need the following operations, they are must!
**Compile dist files**
To compile the dist files you need Node.js/npm, clone/download the repo then:
npm install (install npm deps)
Optional: npm run dev (developer mode, autocompile with browsersync support for live demo)
npm run production (compile css/js files)

**Comment by huskier** [comment]
After recompiling AdminLTE according to the instruction in the Readme.MD file and according to Jack's guide, the issues are solved. Now, AdminLTE works like a charm.

Thanks Jack! @REJack

**Comment by REJack** [comment]
I will a custom class later for this ^^ I personally like permanently visible close buttons too 😂

**Comment by huskier** [comment]
Anyway, Thank you, Jack!

**Comment by REJack** [comment]
I've added a extra class called `permanent-btn-iframe-close`, add this to body and your close buttons will never disappear🤣.

**Comment by huskier** [comment]
@REJack Thank you very much for this function. It would be better if the tabs could follow the Chrome's tab-styles in the next few versions!

**Comment by REJack** [comment]
Feel free to create CSS styles for it and I will update it. 🤣

**Comment by huskier** [comment]
Thanks, I would try.
