### ISSUE TITLE
How can i use a small btn-app

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3477]
How can i use a small btn-app ?

this btn to big !!!

![Screenshot_2021-03-05 ADVANCED NET](https://user-images.githubusercontent.com/31727156/110170803-caf92e00-7e0b-11eb-88da-408b47ae9581.png)

**Comment by muhanadali100** [comment]
![Screenshot_2021-03-05 Easion - Bootstrap Dashboard Template](https://user-images.githubusercontent.com/31727156/110172360-13b1e680-7e0e-11eb-846f-bd63b449e16a.png)

like these small buttons

**Comment by danny007in** [comment]
ask to that dependency upstream

**Comment by REJack** [comment]
btn-app doesn’t come from upstream, also it make literally no sense to create a small btn-app the text size would be too small to read.

**Comment by REJack** [comment]
create a btn-sm with a tooltip 😂 would be the best solution.

**Comment by muhanadali100** [comment]
> 
> 
> create a btn-sm with a tooltip 😂 would be the best solution.

😂😂😂 friend i don't have any proplem 

but when i use my site with phone this make the page very tall because it's can't be row 
i use with a table

![Screenshot_2021-03-07 ADVANCED NET(1)](https://user-images.githubusercontent.com/31727156/110231532-4e5c7180-7f29-11eb-8c88-ed045e3e9ee8.png)

**Comment by danny007in** [comment]
@muhanadali100 use
https://www.w3schools.com/css/css_rwd_mediaqueries.asp 
https://stackoverflow.com/questions/6370690/media-queries-how-to-target-desktop-tablet-and-mobile

**Comment by SmileYzn** [comment]
Generally in tables we have horizontal layout, why did you need to butons in vertical layout?

`<a href="#" class="btn btn-xs btn-primary"><i class="fa fa-edit fa-fw"></i> Edit</a>`

Or just an button

`<button type="button" class="btn btn-xs btn-primary"><i class="fa fa-edit fa-fw"></i> Edit</button>`

**Comment by muhanadali100** [comment]
![Screenshot_2021-03-25 Material Dashboard PRO by Creative Tim](https://user-images.githubusercontent.com/31727156/112403797-238f5d00-8d20-11eb-9187-179cf3cad070.png)

these button in action is very beautiful and it's don't take a space in page 

i need the button like these @danny007in @REJack

**Comment by danny007in** [comment]
Simply use
```html
<a href="#" class="btn btn-primary"><i class="fa fa-user"></i></a>
```

**Comment by REJack** [comment]
You can create all of them easily with AdminLTE

**Comment by danny007in** [comment]
does the issue solved @muhanadali100

**Comment by muhanadali100** [comment]
yes , but i need to know how can i get the information when i set the mouse on the small button like

box upper the small btn have the name of the button it's showing when set the mouse on the btn

**Comment by REJack** [comment]
@muhanadali100 Try to add a tooltip to the button.
