### ISSUE TITLE
[BUG] Nav Tabs inside Card Header (DARK MODE)

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3498]
![Screenshot 2021-03-13 204445](https://user-images.githubusercontent.com/50356015/111034728-fcda4800-843c-11eb-8744-e9047c143488.png)

and many like this in same page
it was there, from earlier in dark mode

**Comment by REJack** [comment]
fixed with 22e087afcfbe1f4aca0a14061749b330e7dcd8f5
