### ISSUE TITLE
Getting below error while installing AdminLTE

### ISSUE THREAD

**Issue by Blason** [ColorlibHQ/AdminLTE#3513]
Hi Team,

Trying to install AdminLTE on Ubuntu 18.04 however facing this error. I am pretty novice to nodejs and wanted to install AdminLTE for my ubuntu server.

```sh
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/share/adminlte/AdminLTE-3.0.5/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-76-generic
gyp ERR! command "/usr/bin/node" "/usr/share/adminlte/AdminLTE-3.0.5/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/share/adminlte/AdminLTE-3.0.5/node_modules/node-sass
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/postcss-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-16T05_55_23_339Z-debug.log
root@waf:/usr/share/adminlte/AdminLTE-3.0.5# ls -l /usr/share/ad
adduser/  adminlte/
root@waf:/usr/share/adminlte/AdminLTE-3.0.5# ls -l /usr/share/adminlte/
total 22652
drwxrwxr-x 9 root root     4096 Mar 16 11:24 AdminLTE-3.0.5
-rw-r--r-- 1 root root 23188946 Mar 16 11:18 v3.0.5.tar.gz
root@waf:/usr/share/adminlte/AdminLTE-3.0.5# npm cache clean -f
```
npm WARN using --force I sure hope you know what you are doing.

**Comment by danny007in** [comment]
check https://github.com/ColorlibHQ/AdminLTE/issues/3371

**Comment by danny007in** [comment]
https://github.com/ColorlibHQ/AdminLTE/issues/3288 refer this.

**Comment by danny007in** [comment]
run in `sudo`

**Comment by REJack** [comment]
There is nothing where we can help, that’s a OS related bug/issue.

**Comment by navtek** [comment]
Don't use --force, you can use --legacy-peer-deps instead.

**Comment by danny007in** [comment]
what is npm version

**Comment by danny007in** [comment]
use `node v14` 
after installing do not upgrade `npm `

**Comment by Blason** [comment]
So looking at the comments it looks like its not possible to install AdminLTE with 18.04?

**Comment by navtek** [comment]
It should be possible, it just needs troubleshooting, what happens if you just use ```npm install``` without any flags?

**Comment by Blason** [comment]
Well now I tried with Ubuntu 20.04

33527 verbose Linux 5.4.0-66-generic
33528 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
33529 verbose node v10.19.0
33530 verbose npm  v6.14.4
33531 error code ELIFECYCLE
33532 error errno 1
33533 error node-sass@5.0.0 postinstall: `node scripts/build.js`
33533 error Exit status 1
33534 error Failed at the node-sass@5.0.0 postinstall script.
33534 error This is probably not a problem with npm. There is likely additional logging output above.
33535 verbose exit [ 1, true ]

************************
gyp verb remove removing development files for version: 10.19.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.19.0' ]
gyp verb remove using node-gyp dir: /opt/AdminLTE/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.19.0
gyp verb remove removing development files for version: 10.19.0
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, mkdir
gyp ERR! System Linux 5.4.0-66-generic
gyp ERR! command "/usr/bin/node" "/opt/AdminLTE/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/AdminLTE/node_modules/node-sass
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap-switch@3.3.4 requires a peer of bootstrap@^3.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN tempusdominus-bootstrap-4@5.39.0 requires a peer of tempusdominus-core@5.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@5.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-18T08_08_24_533Z-debug.log

**Comment by REJack** [comment]
Did you removed your node_modules folder and runned `npm i` again?
