### ISSUE TITLE
[QUESTION] Why Navigation Cut Off

### ISSUE THREAD

**Issue by redstonedesigner** [ColorlibHQ/AdminLTE#3517]
**Describe the bug**

Navigation is slightly curtailed in all sections.

**To Reproduce**
1. Download latest development version
2. Access any template (e.g. index, index2, forms)
3. Notice navbar is cut off on the right hand side, preventing the arrows and the ending of "Pierce"

**Expected behavior**

Arrows and words would not be cut off.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/29328096/111512792-0965e580-8748-11eb-92d7-e40fd56209d3.png)

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.0.0] **master** (I believe 3.1.x develop)
- Operating System:  [e.g. macOS Catalina] **Windows 10 Professional**
- Browser (Version): [e.g. Chrome (Latest)] **Chrome - Latest**

**Additional Context**

Display Resolution: **2560 x 1440**

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

**Comment by redstonedesigner** [comment]
The issue also seems to occur on the latest stable release.  See attached screenshot.

![image](https://user-images.githubusercontent.com/29328096/111517216-bc384280-874c-11eb-9d3e-110b078b75d7.png)

**Comment by danny007in** [comment]
paste code

**Comment by redstonedesigner** [comment]
There has been no modification, this is the base download.

**Comment by REJack** [comment]
What kind of browser you use? 
Please with Versionnumbers :D

**Comment by redstonedesigner** [comment]
![image](https://user-images.githubusercontent.com/29328096/111541255-26121580-8768-11eb-9f48-bb90537f7649.png)

**Comment by REJack** [comment]
true :D I will check it later or tomorrow 😄

**Comment by redstonedesigner** [comment]
Thanks.  Let me know what you find, if possible.

**Comment by danny007in** [comment]
> 
> 
> There has been no modification, this is the base download.
> 
> This issue occurs with all of the following:
> 
>     * The latest stable release
> 
>     * The 3.1.0-rc release
> 
>     * The latest commit (master)
> 
>     * The public demo

Exactly, for that's y i am asking code

**Comment by REJack** [comment]
A full screen screenshot would help extremely.

**Comment by redstonedesigner** [comment]
Public Demo:
![image](https://user-images.githubusercontent.com/29328096/111651517-34ab0c00-87fe-11eb-8f5a-6fe93a5d26e5.png)

Latest commit:
![image](https://user-images.githubusercontent.com/29328096/111652184-c9ae0500-87fe-11eb-9df7-bdb751fcf90b.png)

Release candidate:
![image](https://user-images.githubusercontent.com/29328096/111652280-dfbbc580-87fe-11eb-94fa-530cc2b25f03.png)

Stable:
![image](https://user-images.githubusercontent.com/29328096/111652406-f6621c80-87fe-11eb-8e24-4f3df2806171.png)

**Comment by danny007in** [comment]
It's an issue in some custom CSS.
@redstonedesigner better ask urs seniors

**Comment by kabutotx** [comment]
Change your Chrome font size in settings back to Medium.  You can use Windows Font sizing if you need it bigger.

**Comment by danny007in** [comment]
Add Code.

**Comment by redstonedesigner** [comment]
> Change your Chrome font size in settings back to Medium. You can use Windows Font sizing if you need it bigger. Or Change zoom in Chrome

This was the issue.  I have a visual impairment which means that I have to have the font size increased.  Reducing it back to standard resolved the issue.



> It's an issue in some custom CSS.
> @redstonedesigner better ask urs seniors

All of these screenshots were obtained from fresh downloads, I could even record a video of me downloading them and experiencing the same results.  There has been zero code modification or bootstrapping of additional code.

**Comment by medeepaksaini** [comment]
@danny007in this issue was resolved, close this issue

**Comment by danny007in** [comment]
> @danny007in this issue was resolved, close this issue

Same issue may appear to many users
So I labelled it as questions
