### ISSUE TITLE
[DOCS] Add dark mode with toggle

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3519]
- Also that need to save state in localStorage 
- Discuss here before Creating PR

**Comment by REJack** [comment]
use localStorage insead of cookies

**Comment by REJack** [comment]
otherwise we need a cookie info 😂

**Comment by danny007in** [comment]
https://codepen.io/2kool2/pen/abzgPzJ?editors=1000 can we do like this

**Comment by danny007in** [comment]
https://codepen.io/demilad/pen/bZRjpb or like this

**Comment by danny007in** [comment]
https://codepen.io/ananyaneogi/pen/zXZyMP or this

**Comment by danny007in** [comment]
add this in sass https://codepen.io/saulsolorzano/pen/XWNxPGQ

**Comment by MojtabaFaal** [comment]
Hello
I read today

`:root {
    color-scheme: light dark;
}`

Here :
[https://blogs.windows.com/msedgedev/2021/06/16/dark-mode-html-form-controls/](https://blogs.windows.com/msedgedev/2021/06/16/dark-mode-html-form-controls/)

Reference : 
[https://www.w3.org/TR/css-color-adjust-1/#color-scheme-prop](https://www.w3.org/TR/css-color-adjust-1/#color-scheme-prop)

**Comment by danny007in** [comment]
> 
> 
> Hello
> I read today
> 
> `:root { color-scheme: light dark; }`
> 
> Here :
> [blogs.windows.com/msedgedev/2021/06/16/dark-mode-html-form-controls](https://blogs.windows.com/msedgedev/2021/06/16/dark-mode-html-form-controls/)
> 
> Reference :
> [w3.org/TR/css-color-adjust-1/#color-scheme-prop](https://www.w3.org/TR/css-color-adjust-1/#color-scheme-prop)

I will add in adminlte v4

**Comment by MojtabaFaal** [comment]
> > Hello
> > I read today
> > `:root { color-scheme: light dark; }`
> > Here :
> > [blogs.windows.com/msedgedev/2021/06/16/dark-mode-html-form-controls](https://blogs.windows.com/msedgedev/2021/06/16/dark-mode-html-form-controls/)
> > Reference :
> > [w3.org/TR/css-color-adjust-1/#color-scheme-prop](https://www.w3.org/TR/css-color-adjust-1/#color-scheme-prop)
> 
> I will add in adminlte v4

Thanks
