### ISSUE TITLE
Datatable responsive showing the information in left not in center

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3520]
![Screenshot_2021-03-18 ADVANCED NET](https://user-images.githubusercontent.com/31727156/111614302-7d5bc880-87f0-11eb-9721-b225fbac5974.png)

how can i using the center with datatables responsive

**Comment by danny007in** [comment]
Ask to dataTable

**Comment by REJack** [comment]
You can easily change the responsive look, I prefer the modal version code/demo is in the [DataTables docs](https://datatables.net/extensions/responsive/examples/display-types/bootstrap4-modal.html).

**Comment by muhanadali100** [comment]
> 
> 
> You can easily change the responsive look, I prefer the modal version code/demo is in the [DataTables docs](https://datatables.net/extensions/responsive/examples/display-types/bootstrap4-modal.html).

thanx
