### ISSUE TITLE
[DOCS] CardRefresh Documentation & Examples

### ISSUE THREAD

**Issue by ZacHiler** [ColorlibHQ/AdminLTE#3521]
I'm not sure exactly how to word this, so I'll do my best. I've been on a journey trying to understand the Card Refresh plugin and how it's supposed to work. Currently, I have a table setup like this in the first div:

`<div class="card" id="card-refresh_widget" data-card-widget="card-refresh" data-source="../tables/somefile.php">`

Then, just for testing, I call the refresh like this:

`<script> window.onload = function() { setInterval(function(){ $("#card-refresh_widget").CardRefresh("load"); }, 2000); } </script>`

It works, but I'm still not sure I'm doing it right. The documentation doesn't explain it this way and I'm using the latest build of 3.1.0-rc. Other posts were helpful, but I'd still like to know if this is the correct way. Also, I tried to use a 'require' in the PHP file but no matter what path I gave, it said the file didn't exist. Any ideas?

**Comment by REJack** [comment]
There is not a real correct way to reload the cards with CardRefresh, your way is one of the ways.

> Also, I tried to use a 'require' in the PHP file but no matter what path I gave, it said the file didn't exist. Any ideas?

That's not related to AdminLTE, since we are only deploying HTML, CSS & JS.

**Comment by ZacHiler** [comment]
Ok, I may elaborate on methods in another thread to help others. I've really enjoyed AdminLTE.

**Comment by REJack** [comment]
> Ok, I may elaborate on methods in another thread to help others. I've really enjoyed AdminLTE.

Please open for this a Discussion 😄
