### ISSUE TITLE
any idea to add date and clock to my php page

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3529]
any idea to add date and clock to my php page ??

**Comment by danny007in** [comment]
check https://adminlte.io/themes/v3/pages/forms/advanced.html

**Comment by danny007in** [comment]
also https://getdatepicker.com/5-4/

**Comment by muhanadali100** [comment]
> 
> 
> check https://adminlte.io/themes/v3/pages/forms/advanced.html

no i don't know the date and time in form , i need to show the time in the start page like
25-3-2021 12:00:00 PM

**Comment by danny007in** [comment]
https://www.jqueryscript.net/tags.php?/Digital%20Clock/ see

**Comment by muhanadali100** [comment]
> 
> 
> https://www.jqueryscript.net/tags.php?/Digital%20Clock/ see

thanx it's working
