### ISSUE TITLE
[Improve] The distributed css file of AdminLTE3.1 is too large.

### ISSUE THREAD

**Issue by imcsd** [ColorlibHQ/AdminLTE#3530]
The distributed css with the size more than 1.3MB. I has try to remove some scss then build it, but the size still more than 1MB, is't slow down the page load significant.

I hope you can reduce the size of dist verion, or we can select the component which I need.

**Comment by danny007in** [comment]
@imcsd we will add `adminlte.slim.css` without `dark-mode` feature, then it will reduce as `v3.0.5`

**Comment by danny007in** [comment]
Done: https://github.com/ColorlibHQ/AdminLTE/pull/3533
