### ISSUE TITLE
[BUG] i tag in sidebar menu changed to SVG by fontawesome meaning navigation item with sub item don't have the arrow rotating once opened.

### ISSUE THREAD

**Issue by liljack** [ColorlibHQ/AdminLTE#3532]
**Describe the bug**
AdminLTE sidebar css has the following:
https://github.com/ColorlibHQ/AdminLTE/blob/v3/build/scss/_main-sidebar.scss#L109
with the purpose to rotate the arrow appearing on the right hand side of a menu item when there is sub navigations and the menu is open. 
For me this arrow never rotated. The reason is because Font awesome translate i tags to SVG automatically. Although you can desactivate this by setting `autoReplaceSvg: false` in font awesome configuration, people may not know about it and therefore not set this. Also I think adminLTE should support this, and the current css doesn't. This is possibly a feature request, but none the less would be nice and quick to add / fix.

**To Reproduce**
Unsure, this was after a fresh installation using yarn and a ruby on rails application.

**Expected behavior**
I would expect the arrow to rotate and pointing down (have the class `fa-angle-down` instead of `fa-angle-left`) when I click on the navigation item to display it's sub navigation.

**Screenshots**
Menu closed
![Screenshot 2021-03-24 at 18 39 43](https://user-images.githubusercontent.com/1465762/112358369-9244ca00-8cd0-11eb-8eb5-1195007d7982.png)
Menu opened
![Screenshot 2021-03-24 at 18 39 54](https://user-images.githubusercontent.com/1465762/112358378-94a72400-8cd0-11eb-8dc1-037a8d1f3d44.png)
i tag in the code
![Screenshot 2021-03-24 at 18 51 06](https://user-images.githubusercontent.com/1465762/112359858-016eee00-8cd2-11eb-92fc-b74d9fe46b5f.png)

translated automatically once rendered
![Screenshot 2021-03-24 at 18 32 31](https://user-images.githubusercontent.com/1465762/112358390-983aab00-8cd0-11eb-86c2-643317da1ad7.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.1
- Operating System:  macOS Big Sur
- Browser (Version): Chrome Version 89.0.4389.82 (Official Build) (x86_64)

**Additional context**
I think we can either add the following to _main-sidebar.scss (have tried that locally by adding the following in a custom css file and that fixed the problem):

```css
.menu-open,
  .menu-is-opening {
    > .nav-link {
      svg.right {
        @include rotate(-90deg);
      }
    }
  }
```
Alternatively we could not restrict the `i` tag in the current css, although I am unsure if there will be any side effect from doing that.

I happy do raise a PR for it.

**Comment by danny007in** [comment]
@liljack u can create PR 😃

**Comment by MojtabaFaal** [comment]
This problem occurs after inserting **/js/all.min.js**

**Comment by danny007in** [comment]
> 
> 
> This problem occurs after inserting **/js/all.min.js**

- use any one `all.min.js` or `all.min.css`
- both are same
