### ISSUE TITLE
[BUG] Sidebar overflow when layout-fixed isn't being used

### ISSUE THREAD

**Issue by ArthurHetem** [ColorlibHQ/AdminLTE#3537]
**Describe the bug**
When not using the .layout-fixed and the sidebar has various items, the overflow is set to auto, and this bring a bug on the end of the sidebar, screenshot on the end

**To Reproduce**
1. have various nav-item's on the nav
2. Expand any dropdown

**Expected behavior**
The expected behavior is that the overflow dont change, so the missing color "line" dont appear

**Screenshots**
![image](https://user-images.githubusercontent.com/7545272/112535180-bb299580-8d8a-11eb-863b-75a3ab15827d.png)
whitout expanding any dropdown everything is okay.
![image](https://user-images.githubusercontent.com/7545272/112538430-9df6c600-8d8e-11eb-94dc-4b52462954a8.png)
When expand a dropdown a gray line appear on the bottom

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  Not relevant
- Browser (Version): Not relevant

**Comment by danny007in** [comment]
use the latest browser like edge, chrome, mozilla

**Comment by ArthurHetem** [comment]
I'm using latest edge

**Comment by danny007in** [comment]
add full screen-shot
if possible video and code

**Comment by ArthurHetem** [comment]
![image](https://user-images.githubusercontent.com/7545272/112548200-9a693c00-8d9a-11eb-89ab-ebf34380a18e.png)
![image](https://user-images.githubusercontent.com/7545272/112548166-8e7d7a00-8d9a-11eb-8b44-b72a18e24505.png)

https://drive.google.com/file/d/12S9CdehGc3h0uI2caPFT6NCgH3NrWbFA/view?usp=sharing

I searched a little more, the issue is on the overflow that is applied by the line 556 of _layout.scss.
![image](https://user-images.githubusercontent.com/7545272/112548753-7a864800-8d9b-11eb-940d-55484b266998.png)

**Comment by danny007in** [comment]
that's not a gray line 
it is horizontal scrollbar

**Comment by danny007in** [comment]
use https://kingsora.github.io/OverlayScrollbars/#!overview
it's in plugins folder

**Comment by danny007in** [comment]
we will fix this in v3.1.1

**Comment by danny007in** [comment]
@ArthurHetem thanks for reporting, fixed in [`6db2e0d` (#3542)](https://github.com/ColorlibHQ/AdminLTE/pull/3542/commits/6db2e0d4e57212c584070eb86b47a81282ac9c80)

**Comment by ArthurHetem** [comment]
Thanks
