### ISSUE TITLE
[BUG] Font sizes of form-control-sm and custom-select-sm are inconsistent.

### ISSUE THREAD

**Issue by zybersup** [ColorlibHQ/AdminLTE#3539]
After updating the latest v.3.1.0 to my project which formerly used v.3.0.5, I notice that the font size of ".custom-select-sm" is much smaller than it previously was and also inconsistent with the other ".form-control-sm" surrounding. I inspect them and found that .custom-select-sm uses font-size 75% while .form-control-sm uses font-size 0.875rem.

Should it be consistent? Or Should I correct my use in a way? Please advise.

**Comment by danny007in** [comment]
> Should I correct my use in a way?
Try, 
if the issue remains
 reply here 😃

**Comment by danny007in** [comment]
@zybersup does this issue solved

**Comment by zybersup** [comment]
I have checked the related SCSS files and find that they are really set differently. And it affected both versions. (Firstly, I misunderstood it.)

To solve my problem, I just change 75% to 0.875rem in the compiled CSS file. However to fix it really, you need to change the font-size of the custom-input in your SCSS file. Additionally, I found that it is the inconsistency from Bootstrap itself, not yours. (See https://github.com/twbs/bootstrap/issues/26476)

**Comment by zybersup** [comment]
I have just found that this bug at Bootstrap is fixed since Nov 2018 affecting Bootstrap v4.2 and above. Does it mean the SCSS files here in AdminLTE 3.1 has not been fully updated to v4.6 as it says?

**Comment by REJack** [comment]
the SCSS files are updated but we use custom sizes for this thats the problem :D but I it fixed with 69c8d42.
