### ISSUE TITLE
create adminlte-bundle-dark  file for Dark Mode/ iframe/ Other if somthinf

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#3553]
Hi, Try to make adminlte.css & adminlte.js file size as small as can.

We can use bundle file for big changes/ RTL Support/ iframe/ other big components.

every file in each separate bundle file and you can also create adminlte-all.css file with all components also.

same thing apply upon js files

**Comment by danny007in** [comment]
https://github.com/ColorlibHQ/AdminLTE/pull/3533 see
