### ISSUE TITLE
[FEATURE] Change primary color upon accent color class

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#3554]
Hi if someone use accent color css into body tag, primary color should change upon that.

like (.btn, activate and dropdown everywhere)

**Comment by danny007in** [comment]
Give some more details regarding to issue like code, images, video to solve issue

**Comment by deepak458** [comment]
@danny007in in `V 3.1.0` if we added `accent-* (Color)` it's change only few area link dropdown active class and some other.

what i'm saying when someone using color like yellow/indigo, in navbar & sidebar, and when we use `.btn-primary` in button it's look off in that theme.

so if someone use `accent-* (Color)` this will also change primary color as per `accent-* (Color)` for everywhere mostly in `button`

**Comment by danny007in** [comment]
we are adding themes after release o overcome this 👍🏼
