### ISSUE TITLE
[BUG] URLs with characters '?' and '=' not encoded properly in sidebar search results.

### ISSUE THREAD

**Issue by zammitjohn** [ColorlibHQ/AdminLTE#3556]
**Describe the bug**
URLs with characters '?' and '=' not text encoded properly in sidebar search results. 
? -> %3F
= -> %3D
 
**To Reproduce**
1. Add element to sidebar element with 'href' containing a '?' or '='
2. Search for the element from the sidebar
3. Click on the result

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Browser (Version): Chrome (Latest)

**Comment by danny007in** [comment]
add url here ill check

**Comment by danny007in** [comment]
Fixed in https://github.com/ColorlibHQ/AdminLTE/pull/3557

**Comment by zammitjohn** [comment]
Thanks @danny007in!

**Comment by muhanadali100** [comment]
not working with me and i use the last update

**Comment by danny007in** [comment]
> 
> 
> not working with me and i use the last update

did u compiled

**Comment by muhanadali100** [comment]
> 
> 
> > not working with me and i use the last update
> 
> did u compiled

yep i complied and not working
