### ISSUE TITLE
[BUG] Missplaced "X" icon for Select2

### ISSUE THREAD

**Issue by emsilva** [ColorlibHQ/AdminLTE#3569]
**Describe the bug**
The X icon is misplaced for pills on Select2, it's sitting on top of the word for the selection.

**To Reproduce**
I'm using Rails 6. I attempted loading the CSS for select2 prior to adminlte and after. In both cases, the display is the same.
I'm calling select 2 with `$("#milestone_dependency_ids").select2()` without any options.

**Expected behavior**
Expected the pills to show [X String] instead of having the X on top of the word.

**Screenshots**
![Screen Shot 2021-04-05 at 00 31 56](https://user-images.githubusercontent.com/637781/113534411-13d90980-95a7-11eb-8605-4dd6bdccae98.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.0
- Operating System:  MacOS Big Sur 
- Browser (Version): Brave Latest

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

or 

use the latest browser like edge, chrome, Mozilla

or

check HTML code  properly compared with new version

**Comment by emsilva** [comment]
- Already using the latest version of AdminLTE 3.
- Already tested on latest Chrome, Latest Firefox and Latest Safari with the same issue.
- Regarding the HTML, I copied and paste the same example for Select2 used by AdminLTE 3. Its displaying the same problem (see screenshot)

![Screen Shot 2021-04-05 at 10 13 05](https://user-images.githubusercontent.com/637781/113577385-91c50100-95f7-11eb-8e96-2ce5db321a1a.png)

**Comment by danny007in** [comment]
paste code

**Comment by danny007in** [comment]
check https://stackoverflow.com/questions/5374645/jquery-plugin-not-working

**Comment by danny007in** [comment]
once ask  Select2

**Comment by danny007in** [comment]
check https://github.com/select2/select2/issues/5977
