### ISSUE TITLE
[BUG] Sidebar custom area on a fixed sidebar is mostly hidden on Android devices

### ISSUE THREAD

**Issue by DoobleD** [ColorlibHQ/AdminLTE#3570]
**Describe the bug**
On Android devices, the fixed sidebar + custom area has the custom area mostly hidden. This happens on the demo for instance.

**To Reproduce**
1. Go to [https://adminlte.io/themes/v3/pages/layout/fixed-sidebar-custom.html](https://adminlte.io/themes/v3/pages/layout/fixed-sidebar-custom.html) from Chrome or Firefox for Android.
2. Click on the push/burger menu on the top left to open the sidebar.
3. See the sidebar custom area mostly hidden.

I couldn't reproduce the issue by resizing the browser on desktop though, this really only happens with an Android device.

**Expected behavior**
The sidebar custom area should be fully visible, as it's the case on desktop.

**Screenshots**
<img src="https://user-images.githubusercontent.com/918201/113713614-d760f700-96e7-11eb-8280-e687da75631c.png" width="300">

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  Android 8.1.0, Nexus 5X.
- Browser (Version): Chrome 89.0.4359.105 and Firefox 87.0.0-rc. 1.

The issue also arises when testing from multiple Android devices on [BrowserStack](https://browserstack.com).

**Comment by REJack** [comment]
this should be fixed with 9d099b1, please test it (sadly I have no android phone).

**Comment by DoobleD** [comment]
@REJack thanks for the fix attempt @REJack! 9d099b1 doesn't seem to work for me, tested on same Android 8.1.0 device with Chrome 91.0 and Firefox 90.1.1.

Not sure if that's of any help, but you could try it with [browserstack.com](https://browserstack.com) for instance.

**Comment by DoobleD** [comment]
Has the issue been fixed, hence the closing?
