### ISSUE TITLE
Select control arrows disappear in dark mode

### ISSUE THREAD

**Issue by deboer-tim** [ColorlibHQ/AdminLTE#3571]
**Describe the bug**
When dark mode is enabled you can't see the up/down arrows on a custom select widget. As per screenshots this can be seen in the sample app on the Forms > General Elements page.

**To Reproduce**
1. Go to /pages/forms/general.html
2. See arrows in Different Styles > Custom Select section.
3. Turn on dark mode.
4. Arrows are no longer visible.

**Expected behavior**
Arrows switch color when in dark mode, e.g. to the same light gray as the border.

**Screenshots**
<img width="583" alt="Screen Shot 2021-04-06 at 1 53 34 PM" src="https://user-images.githubusercontent.com/19958075/113756978-10956900-96e0-11eb-9c80-4f4e930afb7b.png">
<img width="583" alt="Screen Shot 2021-04-06 at 1 53 42 PM" src="https://user-images.githubusercontent.com/19958075/113756979-112dff80-96e0-11eb-9d33-c52f6cf06792.png">

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System: macOS Big Sur 11.2.3
- Browser (Version): Safari or Chrome (Latest)

**Comment by REJack** [comment]
fixed in 747e0dd.
