### ISSUE TITLE
adminlte：How to transfer data about the world map

### ISSUE THREAD

**Issue by hitwhsr** [ColorlibHQ/AdminLTE#3573]

**Comment by danny007in** [comment]
Give some more details regarding to issue like code, images, video to solve issue

**Comment by hitwhsr** [comment]
When clicking on a country in the map, it will show how many new visitors there are. I want to know how this data is transmitted.
How can I query the data through my own database and transmit it to this map?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ColorlibHQ/AdminLTE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ColorlibHQ/AdminLTE] adminlte：How to transfer data about the world map (#3573)





 
Give some more details regarding to issue like code, images, video to solve issue

**Comment by danny007in** [comment]
u need to ask to the map plugin
 not adminlte 😄
