### ISSUE TITLE
[BUG] sidebar-collapse, aside doesnt hide after clic, even on mouseout

### ISSUE THREAD

**Issue by abaciocco** [ColorlibHQ/AdminLTE#3575]
**Describe the bug**
If move mouse over/out aside this expand/collapse. But if i clic a menu option aside stay expanded and dont collpase, even if i move mouse out the aside area. to get aside collpased i must clic somewhere out of aside area.
i try using js to force collpase on clic, but nothing happen
$('a[data-widget="pushmenu"]').PushMenu('collapse');

**Expected behavior**
if menu option is clicked, aside must collapse, or if not collapse automatic, when move pointer out it must collapse.

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: [v3.1.0]
- Operating System:  [Ubuntu 20]
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
The behavior is expected, caused by that you are still in focused on the menu option that's why it stay open and you need to click outside of the area.
