### ISSUE TITLE
[BUG]: Layout boxed problems when disabling sidebar-mini

### ISSUE THREAD

**Issue by Shidersz** [ColorlibHQ/AdminLTE#3576]
**Describe the bug**
The control sidebar won't work on **layout boxed** if you disable `sidebar-mini`. Also, if screen width is lower than `980px` the left sidebar won't open.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/pages/layout/boxed.html
2. Open right control sidebar and uncheck **Sidebar Mini** option
3. Try to open control sidebar again and see error.
4. Now, reduce screen width to reach a value under `980px` and try to open left sidebar.

**Expected behavior**
Both sidebars should work when disabling **sidebar mini** on layout boxed. Note they work when **not** using layout boxed and **sidebar mini** is disabled.

**Video**
You can check next video showing both issues:

https://user-images.githubusercontent.com/63609705/114098101-49c40980-9897-11eb-926a-eeb6955b57c0.mp4

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System: -
- Browser (Version): -

**Comment by REJack** [comment]
I've added a small workaround for it with 5ed42b1, it's visible but it doesn't slides 🤣
