### ISSUE TITLE
[BUG] dropdown-item Hover or Active is overlapping dropdown-menu border.

### ISSUE THREAD

**Issue by 78wesley** [ColorlibHQ/AdminLTE#3581]
**Describe the bug**
The border of the dropdown-menu is round but if I change the state of a dropdown-item to hover or active the first and last dropdown-item wil overlap the dropdown-menu border.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/index2.html.
2. go to the navbar and click on the messages or notification tab.
3. If you hover on the first or the last dropdown-item. You see that in the corners the selection is overlapping the dropdown-menu border.

**Expected behavior**
If I hover on the first or the last dropdown-item I want to to change the selection to be inside the dropdown-item.

**Screenshots**
Currently Hover state & Active state:
![image](https://user-images.githubusercontent.com/9322930/114269519-dc83b600-9a07-11eb-8d7d-3a985ead7b6c.png)

Future Hover state & Active state:
Hover state & Active state
![image](https://user-images.githubusercontent.com/9322930/114269522-e3122d80-9a07-11eb-98a1-efe13f012296.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System:  Windows 10 OS Version 2009 (Build 19042.870)
- Browser (Version): Google Chrome 89.0.4389.114 (Official Build) (64-bit) (cohort: Stable)

**Additional context**

I've a CSS fix for it.

```
.dropdown-menu > .dropdown-item:first-child:hover, .dropdown-menu > .dropdown-item:first-child:active {
  border-radius: 0.25em 0.25em 0 0;
}

.dropdown-menu > .dropdown-item:last-child:hover, .dropdown-menu > .dropdown-item:last-child:active {
  border-radius: 0 0 0.25em 0.25em;
}
```

**Comment by danny007in** [comment]
Rejack is dropdown behaviour is like that only or its bug

**Comment by danny007in** [comment]
add `overflow-hidden` class in `dropdown-menu` tagged element

```html
<div class="dropdown-menu `along with multiple classes`">
```

to 

```html
<div class="dropdown-menu overflow-hidden `along with multiple classes`">
```

it issue of bootstrap, u needed to ask them
check https://stackoverflow.com/questions/30677803/background-clip-with-round-border-radius
