### ISSUE TITLE
[BUG] Mastodon icon can't appear

### ISSUE THREAD

**Issue by engkrek** [ColorlibHQ/AdminLTE#3592]
**mastodon icon can't appear when I call it with unicode**
I want to use mastodon icon with unicode ( `&#xf4f6;` ) because I can't use fontawesomes icon in option in select. So, i use the unicode. Whatsapp, Twitter, envelope and Telegram icons works well, while Mastodon not. I tried it with span, without span (just unicode) and combine span and unicode, but still not solved

**To Reproduce**
1. Go to 'register.html'
2. paste this code :
```<div class="input-group mb-3">
          <div style="width: 68px;">
            <select class="form-control unit" id="pilihan" name="medsos" style="font-family: 'FontAwesome'; font-size: 16pt;" onchange="chg_kontak()">
              <option selected disabled class="fas">&#xf0c0;</option>
              <option value="telegram" class="fab">&#xf2c6;</option>
              <option value="whatsapp" class="fab">&#xf232;</option>
              <option value="email" class="fal">&#xf0e0;</option>
              <option value="mastodon" class="fab">&#xf4f6;<span class="fab fa-mastodon"></span></option>
              <option value="twitter" class="fab">&#xf099;</option>
            </select>
          </div>
          <input type="text" class="form-control" id="oth_contact" name="oth_contact" placeholder="kontak lain" required disabled onfocus>
          <div class="input-group-append nanggung" id="dikit">
            <div class="input-group-text">
            </div>
          </div>
        </div>```
3. Save and run
4. Choose mastodon option on select box. And see, the Mastodon icon appear or not

**Expected behavior**
Mastodon icon can appear after I choose it.

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System:  Manjaro KDE Plasma
- Browser (Version): Chromium (89.0.4389.114)

**Additional context**
Sorry for my bad English, you can ask me here or on my telegram (@aing_meong) if you don't understand my question

**Comment by danny007in** [comment]
check one https://fontawesome.com/icons/mastodon
u needed to ask https://fontawesome.com/
and
paste image here 👍🏼

**Comment by engkrek** [comment]
Just need to add fontawesome 5 online link or source. But, when we need to use the website locally, we can't do that. I hope Adminlte will support fontawesome on select-options no matter if we forced to use unicode instead of class ("fa-any-icon"). FYI, we can use fontawesome-icon in options like `<option value="mastodon" class="fab">&#xf4f6;</option>` if you added fontawesome 5 online source

**Comment by danny007in** [comment]
if solved
u can close 😄
