### ISSUE TITLE
[BUG] Using Treeview plugin twice on the same page breaks functionality

### ISSUE THREAD

**Issue by develart-projects** [ColorlibHQ/AdminLTE#3599]
**Describe the bug**
If you create two navigations on the same page, then apply on both treeview plugin like
`<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">`
..you will be able to open the menu, but then it stops reacting completelly.

**To Reproduce**
1. Create two nav bars with very same ul tag and params, see above
2. add some sub-level (level 2)
3. open sublevel
4. you are not able to close it (toggle)
5. bonus: level3+ is scrambled

https://user-images.githubusercontent.com/50356015/117542754-76567700-b037-11eb-9603-a89fda746ff1.mp4

(
One treeview is in the menu, second in the catogory list. Once I remove treeview from the menu, category list works fine. Then I put it back, once more time is broken. Thank you.)

**Expected behavior**
Normal tree view behavior. You can simply remove data-widget="treeview" param and second treeview starts to work imediatelly.

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.1.0]
- Operating System:  [e.g. Fedora Linux]
- Browser (Version): [e.g. Chrome (Latest), Firefox (latest)]

**Comment by danny007in** [comment]
make video
use sharex https://getsharex.com/

**Comment by develart-projects** [comment]
Here is the video: https://drive.google.com/file/d/1Zyx7utRYVj6AAEKDPsaxxhHz0qkT29hx/view

One treeview is in the menu, second in the catogory list. Once I remove treeview from the menu, category list works fine. Then I put it back, once more time is broken. Thank you.

**Comment by danny007in** [comment]
@develart-projects paste code
ill check

**Comment by develart-projects** [comment]
I don't have any public example unfortunately. But as described above - you just need two simple lists using treeview plugin to reproduce.

**Comment by REJack** [comment]
Sorry for the late response, you simply need to add to both a ID like the "mainTreeview" for sidebar and anything else for the second nav then it works like you want it 😄

**Comment by REJack** [comment]
But it's totally funny, that nobody say anything about that the nav-items are empty if the main-sidebar is collapsed 🤣

**Comment by develart-projects** [comment]
That works, thanks! Anyway, still seems to be kind of bug. Or (at least) maybe you should consider to document it.

**Comment by REJack** [comment]
I'll add a note in the docs 😄

**Comment by nahmias22** [comment]
Hi there, I have come across the same issue but even though I assign the same Id to both lists but once opened they still won't respond to the close action. Have I misunderstood something?

**Comment by develart-projects** [comment]
> Hi there, I have come across the same issue but even though I assign the same Id to both lists but once opened they still won't respond to the close action. Have I misunderstood something?

You have to pick different IDs, that's the point.

**Comment by nahmias22** [comment]
I had tried that as well but it still did not work. Do I need to initialise it separately in a script, and if so how do I do that?

**Comment by REJack** [comment]
No the `data-widget="treeview"`-attriebute triggers the init process, simply add a unique id to the treeview widgets. If it's still working, then you not use the 3.2.0-rc.
