### ISSUE TITLE
[BUG] Some components of the control sidebar are not working

### ISSUE THREAD

**Issue by MayeeshaHumaira** [ColorlibHQ/AdminLTE#3613]
**Describe the bug**
Some components of the control sidebar like Navbar Variants, Accent Color Variants, Dark Sidebar Variants, Light Sidebar Variants, Brand Logo Variants are not working. What should be done to make them work?

**To Reproduce**
1. Open index.html in a browser
2. Click on the control sidebar button at the top right of the page
3. Scroll down to 'Navbar Variants'
4. Select a color
5. Nothing happens on selecting a color

**Expected behavior**
Sidenavbar's color will change on selecting a color.

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

or 

use the latest browser like edge, chrome, Mozilla

or

check HTML code  properly compared with new version

**Comment by MayeeshaHumaira** [comment]
What is the task of the component marked with an arrow in this [image](https://prnt.sc/11ot66c)? On choosing a different color for Dark Sidebar Variants what change am I suppose to see?

**Comment by REJack** [comment]
Which color should not work?

I would say it works correctly.
![img](https://graphiko.cloud/index.php/s/PKPdBnDKnL3tDTy/preview)

**Comment by REJack** [comment]
__But you should not use our demo.js in your production envoirment, it's only created for testing purposes!__

**Comment by danny007in** [comment]
> 
> 
> **But you should not use our demo.js in your production envoirment, it's only created for testing purposes!**

on very toggle of controll sidebar a popup should tell this

**Comment by danny007in** [comment]
also add in docs

**Comment by REJack** [comment]
> on very toggle of controll sidebar a popup should tell this

No that's annoying while testing 🤣 idk why all think a demo.js is for production purpose too.

**Comment by danny007in** [comment]
> idk

it should trigger only once

**Comment by REJack** [comment]
I've added a alert, if the demo.js isn't loaded with browserSync active :D so we have no annoying alert on developing, also I added a storage to display every 15mins on page load the alert.
