### ISSUE TITLE
[BUG]CardRefresh comes a error with only using framework files

### ISSUE THREAD

**Issue by FlyArtist** [ColorlibHQ/AdminLTE#3614]
**Describe the bug**
I was just using the two files, what is the console error meaning, or my using way is wrong?

**Screenshots**
![image](https://user-images.githubusercontent.com/16695900/115352024-735f2800-a1e9-11eb-879f-7927e9313868.png)
![image](https://user-images.githubusercontent.com/16695900/115352081-85d96180-a1e9-11eb-96ec-023bc575ba2c.png)

**Environment**
- AdminLTE Version: v3
- Operating System:  Windows10
- Browser (Version):  Chrome 90.0.4430.72

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

or 

use the latest browser like edge, chrome, Mozilla

or

check HTML code  properly compared with new version

**Comment by REJack** [comment]
You forgot to load jQuery.

**Comment by gRoussac** [comment]
@REJack Error excepted the documentation does not say you need to load jquery for version 3.2, just two cdn files and this TypeError seems to be still in version 3.2 with those files. Regards
