### ISSUE TITLE
Sidebar Can't Overlay

### ISSUE THREAD

**Issue by chan2093** [ColorlibHQ/AdminLTE#3617]
My I know how to code or configure the sidebar menu can overlay my content? Now I have an issue when then sidebar menu expanded will force the body ratio changed. I want to fix the page content without affect by sidebar menu.

**Comment by REJack** [comment]
How it should overlay on your content? Please give me some more details.

**Comment by danny007in** [comment]
Rejack added complete details in docs regarding `#sidebar-overlay` 
because I also don't what is use of it

**Comment by REJack** [comment]
oh the `#sidebar-overlay` is for Small Screen (XS/SM) that the Sidebar is over the Content instead of moving it, but only for small screens.

**Comment by chan2093** [comment]
May I know #sidebar-overlay can coded for work in Medium and Large (MD/LG)?

**Comment by REJack** [comment]
For AdminLTE v4 sure, for AdminLTE v3 not.
