### ISSUE TITLE
[BUG] Select2 does not autofocus the search box when the select button or element is clicked

### ISSUE THREAD

**Issue by engkrek** [ColorlibHQ/AdminLTE#3618]
**Describe the bug**
Select2 does not autofocus the search box when the select button or element is clicked. I found it in version 3.1.0. I've also checked that in version 3.0.5 there isn't this problem. I've also tried re-downloading version 3.1.0, adding the "autofocus" attribute in line 4084 of select2.full.js

**To Reproduce**
1. Just open advanced form page from Adminlte 3.1.0
2. Click on Select2 element (choose the minimal, not the multiple input) and then try to type everything (don't click the search box, because we need that automatically focused)
3. Compare it to advanced form page from Adminlte 3.0.5

**Expected behavior**
Search box on select2 element can be focused automaticaly focused

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System: Manjaro KDE Plasma (I updated it yesterday)
- Browser (Version): Chromium (90.0.4430.72)

**Additional context**

**Comment by danny007in** [comment]
once plz ask to sweetalert

**Comment by danny007in** [comment]
Check https://github.com/select2/select2/issues/5993

**Comment by engkrek** [comment]
just need to add 
```$(".class-of-select-tag").on('select2:open', () => {
    document.querySelector('.select2-search__field').focus();
});``` . But, if u have 2 or more select tag which use select2 class, when you move to other select, and then click the select before it without click empty space out of the select, this is not work

**Comment by engkrek** [comment]
> Check [select2/select2#5993](https://github.com/select2/select2/issues/5993)

I'll wait for an answer or better way from this link only. Thanks @danny007in
