### ISSUE TITLE
DataTable buttons not working with class name

### ISSUE THREAD

**Issue by brunoromeo001** [ColorlibHQ/AdminLTE#3619]
Hello guys, 

I'm try using DataTable buttons with class name but the buttons not show, when i used #example1 it's working. When i change the name of id not working too, somebody can help me with this. 

$(".myTable").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]}).buttons().container().appendTo('.myTable_wrapper .col-md-6:eq(0)');

**Comment by danny007in** [comment]
ask to DataTable 😃
