### ISSUE TITLE
Not able to change the width of the sidemenu bar in non-expanded mode

### ISSUE THREAD

**Issue by jayforu** [ColorlibHQ/AdminLTE#3622]
I was trying to make the width of the side bar less that whtat it is now in it's non-expanded mode. I tried changing value in variables.less but file is not cpompiling. By the way, the file is _variables.less and not variables.less. Even without any modfications, file is not compilable. 

If someone can help me to in order to make it work, I would relly appreciate that. Also, how can I change the logo in the sidebar? I have tried following documentaion, but it dodnt work

**Comment by danny007in** [comment]
Give some more details regarding to issue like code, images, video to solve issue

**Comment by REJack** [comment]
We don't give support for AdminLTE v2.X anymore, you should upgrade it to v3.1.

**Comment by danny007in** [comment]
@jayforu 
read https://github.com/ColorlibHQ/AdminLTE/blob/master/CODE_OF_CONDUCT.md
https://adminlte.io/docs/3.1//upgrade-guide.html upgrade guide
