### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saif31617** [ColorlibHQ/AdminLTE#3633]
**Describe the bug**
zone-evergreen.js:182 Uncaught TypeError: Cannot read property 'getContext' of undefined

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.0.5]
- Operating System:  [e.g. OS]
- Browser (Version): [e.g. Chrome]

**Additional context**
![Screenshot (53)](https://user-images.githubusercontent.com/48271551/116083893-99d40600-a6b6-11eb-9447-ce0629fcc2db.png)

**Comment by danny007in** [comment]
it is deprecated https://github.com/angular/zone.js/
u needed to ask to i
or 
ask to urs senior
or
https://stackoverflow.com/questions/5374645/jquery-plugin-not-working 😃

**Comment by danny007in** [comment]
solution is https://stackoverflow.com/questions/10291693/cannot-read-property-getcontext-of-null-using-canvas
