### ISSUE TITLE
How to Increase the Height of Navbar Header

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#3634]
I am using AdminLTE-V3.1.

How do I increase the height of the Narvar Header to twice or almost twice of of the original height

![adminlte3_header](https://user-images.githubusercontent.com/34077129/116151146-26dd8600-a6dc-11eb-8bb8-7bd4c4dc6f78.PNG)

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.1.0]
- Operating System:  [Windows]
- Browser (Version): [e.g. Chrome (Latest)]

Thanks

**Comment by danny007in** [comment]
add custom css height with `!important` https://css-tricks.com/when-using-important-is-the-right-choice/ in header/navbar tag
