### ISSUE TITLE
[BUG] Fullscreen button won't change if you exit with ESC key

### ISSUE THREAD

**Issue by Shidersz** [ColorlibHQ/AdminLTE#3638]
**Describe the bug**
When entering the full screen mode using the navbar button, the icon is not changed if you exit pressing the **ESC** key on the keyboard.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/index3.html
2. Click on the full screen button.
3. Exit full screen mode pressing **ESC** key

**Expected behavior**
The icon should be changed when exit full screen mode using the **ESC** key.

**Video**
On the next video, you can see a first enter/exit full screen mode using the button (all works as expected). Then a second enter on full screen mode is triggered with the button, and an exit is done using the **ESC** key (icon do not change).

https://user-images.githubusercontent.com/63609705/116472656-92466580-a84c-11eb-890f-0748c824ee33.mp4

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  -
- Browser (Version): -

**Comment by danny007in** [comment]
Merged https://github.com/ColorlibHQ/AdminLTE/pull/3639 
u can close issue
