### ISSUE TITLE
[BUG] Closing parent in Treeview closes descendants, but "arrow" icon is not changed properly

### ISSUE THREAD

**Issue by develart-projects** [ColorlibHQ/AdminLTE#3643]
**Describe the bug**
INTRO: Bug is easy to reproduce - it's available in the Demo dashboard: https://adminlte.io/themes/v3/
When opening Level 2 and Level 3 in the left menu (Multi level example) and then closing level 2 (Level 1 click), level 3 is also closed, but icon is still pointing down, like it is open. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://adminlte.io/themes/v3/
2. Click on "MULTI LEVEL EXAMPLE" in the left menu, 2nd item (Level 1)
3. Click on 2nd item (Level 2) - level 3 is expanded
4. Click on Level 1 (from step 2) - everything is collapsed
5. Click one more time on the same item - Level 3 items are collapsed, but arrow is pointing down

**Expected behavior**
Either arrow is reversed to indicate "collapsed" state, or Level 3 is not collapsed. I expect consistent behaviour.

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System:  Fedora Linux 34
- Browser (Version): Vhrome latest, FF latest

**Comment by danny007in** [comment]
create video

**Comment by develart-projects** [comment]
> create video for this issue

Seems to be already fixed here: https://github.com/mostafahesham-dev/AdminLTE/commit/6ad835659665fbee5bbd99ddc0d348c598613575
