### ISSUE TITLE
[FEATURE] Cropper or any crop plugin for image upload

### ISSUE THREAD

**Issue by lochnessmengintai** [ColorlibHQ/AdminLTE#3663]
**Is your feature request related to a problem? Please describe.**
When we upload our photo to our account (in our testing web), we need to crop it first to match with our web requirement. But choosing a plugin for this is quite a headache, and installing it is even more of a headache.

**Describe the solution you'd like**
Please add a plugin to crop image such as: Croppie, Jcrop, or Cropper

**Describe alternatives you've considered**

**Additional context**
For now, I'm also confused about choosing a plugin that is simple and easy to apply to my website. Also easy to understand for beginners like me

**Comment by danny007in** [comment]
we will add in adminlte v4

**Comment by danny007in** [comment]
> 
> 
> @danny007in is someone working on this feature, i would like to contribute and try to implement this.
> 
> I have contributed before in this repo and I want to do it again however, I don't know which plugin to go with and what would be the way to do it.

Always welcome, and use cdn

**Comment by danny007in** [comment]
> 
> 
> @danny007in cdn for cropping the images?

yes

**Comment by bansalshashank** [comment]
@danny007in 

> > @danny007in cdn for cropping the images?
> 
> yes

can you send me documentation or something regarding the same.

**Comment by danny007in** [comment]
https://www.jsdelivr.com/package/npm/cropperjs?nav=config
use cdn
