### ISSUE TITLE
[FEATURE] I want to help complete the "Bootstrap 5 RTL"

### ISSUE THREAD

**Issue by MojtabaFaal** [ColorlibHQ/AdminLTE#3665]
Hello
**Bootstrap 5** has just been released
I am one of your users
My native language is **Persian**
I am very interested in working on your project
If you agree, I will help you in the section on **Bootstrap 5 RTL** .
To make the project go faster
Thank

**Comment by danny007in** [comment]
Cool,
Create an PR for https://github.com/ColorlibHQ/AdminLTE/tree/v4-dev

Quick guide
install nodejs
and

run in command line
'npm install'
`npm run dev`

**Comment by danny007in** [comment]
and i have already created some class for `.sidebar-rtl` add in body tag

**Comment by MojtabaFaal** [comment]
Hello
Can you come to Skype?

**Comment by danny007in** [comment]
> 
> 
> Hello
> Can you come to Skype?

Actually, i am just collaborator

u can discuss some, many user will know whats going on

**Comment by danny007in** [comment]
@MojtabaFaal 
can we discuss here https://github.com/ColorlibHQ/AdminLTE/discussions/3294
