### ISSUE TITLE
[BUG] (Laravel 8 + Vue) cssnano: Error in parsing SVG: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by syamsoul** [ColorlibHQ/AdminLTE#3670]
**Describe the bug**
I use Laravel 8 + Vue ... and I use Admin LTE 3  as the template for my project... When I run `npm run watch` or `npm run dev`, there is no problem at all... But when I run `npm run production`, it give me two errors.

`cssnano: Error in parsing SVG: Non-whitespace before first tag.`

**To Reproduce**
1. Install Laravel 8
2. Install Admin LTE 3 via npm
3. Include the admin lte 3 js and css
4. run `npm run production`
5. it will shows the errors

**Expected behavior**
There's should be no errors at all

**Screenshots**
![image](https://user-images.githubusercontent.com/15118790/117528427-d08a1480-b004-11eb-9957-c5a02516f6df.png)

**Environment:**
- AdminLTE Version: v3.1.0
- Operating System: Windows 10

**Comment by danny007in** [comment]
once
ask cssnano

**Comment by REJack** [comment]
Or simply use [Laravel-AdminLTE](https://github.com/jeroennoten/Laravel-AdminLTE/) (non Jetstream versione) or [jetstrap](https://github.com/nascent-africa/jetstrap) (Jetstream version)

**Comment by willydbd** [comment]
Hi, how were you able to solve this issue? Facing the same challenge, application ready for production
