### ISSUE TITLE
How to increase the width of the Top-Navbar-Layout

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#3688]
How do I increase the width of the top-navbar layout?

**Screenshots**

![top_navbar](https://user-images.githubusercontent.com/34077129/117893408-41098d80-b2b2-11eb-8c57-c5b8622236bc.PNG)

I want to increase it on both ends (leaf and right)

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.1.0]
- Operating System:  [e.g. Windows]
- Browser (Version): [e.g. Chrome (Latest)]

Thanks

**Comment by REJack** [comment]
Simply change `.container` to `.container-fluid` in `.content` & `.content-header`.

**Comment by noblemfd** [comment]
@REJack - Please do I find the folder?
