### ISSUE TITLE
[BUG] iframe mode not work with hash link

### ISSUE THREAD

**Issue by undsky** [ColorlibHQ/AdminLTE#3689]
When I use the following link,will generate id="panel--admin-#-pages-home-home" for .tab-pane. it not  work with jquery

`<a href="/admin/#/pages/home/home" class="nav-link">Home</a>`

**Comment by danny007in** [comment]
check https://github.com/ColorlibHQ/AdminLTE/issues/3556

**Comment by REJack** [comment]
should be fixed with 26c84e3, if you want to try it then you need to compile the dist files.
