### ISSUE TITLE
How to increase the width of register-v2.html

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#3691]
I want to perform the following:

1. How do I increase the width of the registration form registration.html
2. How do I use country flag text input in AdminLTE.? I want to use it for phone numbers.

Thanks

**Environment (please complete the following information):**
- AdminLTE Version: [v3.1.0]
- Operating System:  [Windows]
- Browser (Version): [Chrome (Latest)]

**Comment by REJack** [comment]
Simply add `.w-(25|50|75|100)` (e.g `.w-50` for 50% width) beside `.register-box` or `.login-box`.

**Comment by noblemfd** [comment]
> register-box

@REJack - I did each of these:

```
<div class="register-box.w-25">
<div class="register-box.w-50">
<div class="register-box.w-75">
<div class="register-box.w-100">
```

The size is as shown below. It remains the same for all. The width becomes smaller and it aligns to the top.

![register_width](https://user-images.githubusercontent.com/34077129/119041686-d392e680-b9ae-11eb-85bd-dc12aba7b27e.PNG)

What else do I do?

Thanks

**Comment by noblemfd** [comment]
It works @REJack . Thanks
