### ISSUE TITLE
How change font-family

### ISSUE THREAD

**Issue by avlobn** [ColorlibHQ/AdminLTE#3693]
Hello, I am not very good at html and I just need a user-friendly layout for my site,
tell me how to change the font-family of the body
specifically - I need to leave the standard one, and not the one that is built-in

i want the
![image](https://user-images.githubusercontent.com/29842685/118278519-c1a6d480-b4d2-11eb-943c-d339f950dd12.png)

**Comment by danny007in** [comment]
add custom css in header tag 

check https://developers.google.com/fonts/docs/css2

```html
  <head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Crimson+Pro">
    <style>
      body {
        font-family: 'Crimson Pro', serif;

      }
    </style>
  </head>

**Comment by danny007in** [comment]
>  I need to leave the standard one, and not the one that is built-in

Just remove link tag of   <link rel="stylesheet"
          href="https://fonts.

**Comment by avlobn** [comment]
> > I need to leave the standard one, and not the one that is built-in
> 
> Just remove link tag of <link rel="stylesheet"
> href="https://fonts.

Unfortunately, both of these methods did not work, the font-family is still changing without my knowledge and I do not know where to edit it

**Comment by avlobn** [comment]
how can I influence a file dist/node_modules/bootstrap/scss/_reboot.scss
that is not in the folder with the site, but which is displayed in the browser as influences on the body style

**Comment by avlobn** [comment]
I explain:
now when i open the site i see it
![image](https://user-images.githubusercontent.com/29842685/118284702-5f050700-b4d9-11eb-8b52-7526e216e9bc.png)
I want the font-family not to change, which file should I edit for this?

**Comment by danny007in** [comment]
delete .map files in assets folder of adminlte
like
`adminlte.css.map` `adminlte.min.css.map`

**Comment by avlobn** [comment]
> удалить `.map`файлы в папке с ресурсами администратора,
> например
> `adminlte.css.map` `adminlte.min.css.map`

whit not work

**Comment by danny007in** [comment]
> 
> 
> > delete .map files in assets folder of adminlte
> > like
> > `adminlte.css.map` `adminlte.min.css.map`
> 
> whit not work
> 
> Can you write a complete and verified path how to fix this? your previous 3 ways are not working

if delete those u will find real path

**Comment by REJack** [comment]
I tested it and @danny007in trick works, and is also the only way to get a custom font.

Did you placed the custom css after AdminLTE's css file? if not then AdminLTE overwrites the change, but you need to AdminLTE default behavior that's why you need to place it after.
