### ISSUE TITLE
Sidebar with AdminLTE V4 (RTL)

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3695]
the sidebar in AdminLTE V4 is error in RTL

![Web capture_15-5-2021_202322_](https://user-images.githubusercontent.com/31727156/118372700-9a780200-b5bb-11eb-9431-bf4383b735b2.jpeg)

**Comment by danny007in** [comment]
Read https://getbootstrap.com/docs/5.0/getting-started/rtl/

add `dir="rtl"` attribute in `<html>` tag

**Comment by danny007in** [comment]
`npm run css-compile`
and
`<link rel="stylesheet" href="dist/css/rtl/adminlte.rtl.css">`

**Comment by muhanadali100** [comment]
> 
> 
> `npm run css-all`
> and add `<link rel="stylesheet" href="dist/css/rtl/adminlte.rtl.css">`

it's ok but all the button in sidebar don't work

**Comment by danny007in** [comment]
> 
> 
> > `npm run css-all`
> > and add `<link rel="stylesheet" href="dist/css/rtl/adminlte.rtl.css">`
> 
> it's ok but all the button in sidebar don't work

Ill check on that.

and 

is this layout is fine.

**Comment by muhanadali100** [comment]
> 
> 
> > > `npm run css-all`
> > > and add `<link rel="stylesheet" href="dist/css/rtl/adminlte.rtl.css">`
> > 
> > 
> > it's ok but all the button in sidebar don't work
> 
> Ill check on that.
> 
> and
> 
> is this layout is fine.

edit the widget to appear correctly in RTL 
fix the sidebar to work correctly in RTL 
make a button to change between RTL and LTR automatic

**Comment by muhanadali100** [comment]
![Web capture_16-5-2021_13550_](https://user-images.githubusercontent.com/31727156/118393406-a14c5680-b647-11eb-9f3c-4d6cae451c04.jpeg)

all these proplem

**Comment by danny007in** [comment]
`npm run css-all`

**Comment by danny007in** [comment]
edit html to 
```html
<!DOCTYPE html>
<!-- <html lang="en"> -->
<!-- For RTL verison -->
<html lang="en" dir="rtl">


```
```html
  <!-- For RTL verison -->
  <link rel="stylesheet" href="dist/css/rtl/adminlte.rtl.css">
  <!-- <link rel="stylesheet" href="dist/css/adminlte.css"> -->

**Comment by muhanadali100** [comment]
![Desktop Screenshot 2021 05 16 - 16 26 37 79](https://user-images.githubusercontent.com/31727156/118398979-a28b7c80-b663-11eb-9749-3a199935e54e.png)
![Desktop Screenshot 2021 05 16 - 16 27 19 72](https://user-images.githubusercontent.com/31727156/118398980-a3bca980-b663-11eb-8437-1b067ae548a5.png)

![Desktop Screenshot 2021 05 16 - 16 27 39 80](https://user-images.githubusercontent.com/31727156/118398987-a7503080-b663-11eb-9561-2fc817acaa59.png)

i make everything but all there rtl error

**Comment by muhanadali100** [comment]
![Desktop Screenshot 2021 05 16 - 16 30 47 50](https://user-images.githubusercontent.com/31727156/118399091-1e85c480-b664-11eb-855a-6f7d2aca2740.png)

11 moderate severity vulnerabilities

**Comment by danny007in** [comment]
use NodeJS LTS version v14
clear cache
and delete node module dir

and mainly extract the folder https://www.youtube.com/watch?v=R2LJZDdno6U

**Comment by danny007in** [comment]
and use any one
`adminlte.css`
or
`adminlte.rtl.css`

**Comment by muhanadali100** [comment]
> 
> 
> and use any one
> `adminlte.css`
> or
> `adminlte.rtl.css`

remove adminlte.css from index.html 
and it's working perfect thanx
