### ISSUE TITLE
[FEATURE] lazy loading of tabs with IFrame plugin

### ISSUE THREAD

**Issue by uwemaurer** [ColorlibHQ/AdminLTE#3713]
Is it possible to load a tab with the IFrame plugin only after a user activated it?

I want to add several tabs programmatically and only load the content when the user activates the tab.

Also a full example using the jQuery API for the IFrame plugin would be nice. I was not able to get it to work (only works with the `data-widget='iframe'` method)

In my case I also don't want to that the sidebar links get opened as tab, I only want my programatically added tabs.
I was able to fix that with 

```
$(document).on('click', '.main-sidebar .nav-item > a.nav-link', e => {
    e.preventDefault()
    window.location.href = $(e.target).closest('a').attr('href')
})
```
so that the links work as normal links again. but it would be nicer to just add a flag to not open the sidebar links as tabs

**Comment by danny007in** [comment]
closing for https://github.com/ColorlibHQ/AdminLTE/issues/4580
