### ISSUE TITLE
[BUG] Control Sidebar do not work when using data-controlsidebar-slide="false"

### ISSUE THREAD

**Issue by Shidersz** [ColorlibHQ/AdminLTE#3716]
**Describe the bug**
The control sidebar do not show when using `data-controlsidebar-slide="false"` as documented [here](https://adminlte.io/docs/3.1//javascript/control-sidebar.html)

**To Reproduce**
1. On a local environment, edit `index.html` demo example.
2. Then replace the control sidebar toggle button definition by next one.
    ```html
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="false" href="#" role="button">
         <i class="fas fa-th-large"></i>
       </a>
    </li>
    ```

**Expected behavior**
The control sidebar should overlay the content-wrapper without the slide animation.

**Video**
You can see the issue on the next video.

https://user-images.githubusercontent.com/63609705/119242222-85a6eb80-bb32-11eb-95b2-43f976543da1.mp4

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  Linux Mint 20.1
- Browser (Version): Firefox (Latest)

**Additional context**

On the video you could note the class `.control-sidebar-open` is added to the body tag, but the `display: block` style added by that class to the `.control-sidebar` is filtered out, as shown on next image:

![Screenshot from 2021-05-22 19-09-55](https://user-images.githubusercontent.com/63609705/119242255-cc94e100-bb32-11eb-9ff3-f36250c33361.png)

**Comment by REJack** [comment]
fixed with d2e2987a5fdb36151e0f2c90dd1f9b476e33309b
