### ISSUE TITLE
[BUG] Daterangepicker with dark mode

### ISSUE THREAD

**Issue by FoxxenD** [ColorlibHQ/AdminLTE#3718]
**Bug**
Day, months, week "words" are white in dark mode (see the screenshot) with the date range input from date range picker

**To Reproduce**
(On the documention https://adminlte.io/themes/v3/pages/forms/advanced.html)
1 - Turn the dark mode on
2 - Go to the "Date picker"
3 - See the bug with "Date range", "Date and time range" and "Date range button"

**Screenshots**
![output_0e9zQX](https://user-images.githubusercontent.com/32935159/119266699-17befa80-bbec-11eb-8132-511891fd67ad.gif)

**Environment:**
- AdminLTE Version: V3.1.0-rc (bug present in V3.1.0 also)
- Operating System:  Windows
- Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
added with 3b46ba874f623f63b01171c8632f5886f2630b78 :D feel free to test
