### ISSUE TITLE
Smooth Transition on SideBar-collapse/open

### ISSUE THREAD

**Issue by FrancisPrakash** [ColorlibHQ/AdminLTE#3728]
In v3, How can we get the smooth transition on sidebar-collapse/open as in v2 ?

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

or 

use the latest browser like edge, chrome, Mozilla

or

check HTML code  properly compared with new version

**Comment by ZhangChengLin** [comment]
https://github.com/ColorlibHQ/AdminLTE/issues/3700

**Comment by FrancisPrakash** [comment]
This works good! Thanks.
