### ISSUE TITLE
[FEATURE]Adaptive layout without bootstrap

### ISSUE THREAD

**Issue by ZhangChengLin** [ColorlibHQ/AdminLTE#3730]
![image](https://user-images.githubusercontent.com/30773389/120008519-9ad9b980-c00d-11eb-9bcb-4f2e7ee19708.png)

After adjusting the width, the page did not follow the response layout changes.

Recurrence Note: Open the page first, then open the console, and adjust the width to reduce the width to below the corresponding value.

**Comment by ZhangChengLin** [comment]
@danny007in

**Comment by danny007in** [comment]
whats the value

**Comment by ZhangChengLin** [comment]
> whats the value

Above the middle of the picture, there is an approximate range value, 960+

Need to manually observe changes

**Comment by danny007in** [comment]
@ZhangChengLin  fixed in https://github.com/danny007in/AdminLTE/commit/73b18a3bfb218b366740ce39d9d1ef13a6a4805d
