### ISSUE TITLE
Proplem with V4

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3743]
i copy the files to my system 

php 5.3.10
ubuntu 12.04.5
apache 2.2.22

these what i get when open the index.html

![Desktop Screenshot 2021 06 02 - 01 33 11 67](https://user-images.githubusercontent.com/31727156/120398341-b234e180-c342-11eb-98b4-8606102dabde.png)

![Desktop Screenshot 2021 06 02 - 01 33 59 76](https://user-images.githubusercontent.com/31727156/120400307-4b192c00-c346-11eb-9af5-8b25c53ddba7.png)

**Comment by muhanadali100** [comment]
there are 2 proplem the sidebar and the navbar 

the navbar  

because the </nav> is use for twe time 
1- before       
2- at the end of navbar

`      
<nav class="main-header navbar navbar-expand navbar-light">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link sidebar-full-icon" data-pushmenu="full" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>
    
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
      </li>
</nav>

      
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge bg-danger navbar-badge">3</span>
        </a>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge bg-warning navbar-badge">15</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </div>
</nav>
`

the sidebar i didn't know what the proplem , i change everything but same proplem

**Comment by danny007in** [comment]
it is not ready for production,
Ill check the code
