### ISSUE TITLE
[BUG] Bootstrap 4 Upgrade - Broken DashBoard and SideMenu

### ISSUE THREAD

**Issue by HariPrasad-1493** [ColorlibHQ/AdminLTE#3744]
**Describe the bug**
Hi, 
I'm following the guide for adminLTe(current version 2.3) to upgrade to version 3.0. I use a ngx-admin-lte(https://github.com/TwanoO67/ngx-admin-lte) to bootstrap adminLTe to my Angular project 

**To Reproduce**

1. I've done the initial minor change from v2.3 to v2.4 => "HTML Changes
Change dist/js/app.min.js to dist/js/adminlte.min.js".
Rest all steps seems to be updated automatically

2. Then I had upgraded Bootstrap to version 4  and then manually did the class changes for BS3 TO 4 using VS code 

3.Finally did the AdminLTE update to version 3.1.0 

4. But after update the AdminLTE appears to be broken with the whole dashboard and box layout 

Pls let me know if any configuration is required from admin-lte  apart from the one mentioned in the guide of using boostrap.js
"CSS / JS Files
Since AdminLTE v3.0 Bootstrap 4 is complete included in AdminLTE’s CSS file. You will not need to load the Bootstrap CSS file bootstrap(.min).css, but you will need the Bootstrap JS file bootstrap(.min).js."

**Expected behavior**
Dashboard layout and application pages are to be displayed as 2.3version 

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.1.0]
- Operating System:  [e.g. Windows]
- Browser (Version): [e.g. Chrome (Latest)]
- Bootstrap - ^4.1.0
- -ngx-admin-lte - 3.0.0-beta
![AdminErr](https://user-images.githubusercontent.com/73699033/120458423-e517bd80-c3b4-11eb-9365-f342813f99a2.png)
 

**Additional context**

**Comment by HariPrasad-1493** [comment]
package.json for reference 
```
{
  "name": "bootstraping-ngx-admin-lte",
  "version": "0.5.1",
  "license": "WTFPL",
  "scripts": {
    "ng": "ng",
    "build": "ng build",
    "prod": "ng build --prod",
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.2.14",
    "@angular/common": "^11.2.14",
    "@angular/compiler": "^11.2.14",
    "@angular/core": "^11.2.14",
    "@angular/forms": "^11.2.14",
    "@angular/platform-browser": "^11.2.14",
    "@angular/platform-browser-dynamic": "^11.2.14",
    "@angular/router": "^11.2.14",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@ngx-loading-bar/http-client": "2.0.0",
    "@ngx-translate/core": "^12.0.0",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/colresizable": "^1.6.0",
    "admin-lte": "^3.0.0",
    "bootstrap": "^4.1.0",
    "bootstrap-datepicker": "^1.8.0",
    "chart.js": "^2.9.3",
    "colresizable": "^1.6.0",
    "core-js": "^2.6.4",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "ionicons": "^3.0.0",
    "jquery": "^3.6.0",
    "jquery-ui-dist": "^1.12.1",
    "lodash": "^4.17.21",
    "moment": "^2.24.0",
    "nestable": "^0.2.0",
    "ng-block-ui": "2.1.8",
    "ng2-charts": "^2.4.2",
    "ng2-dnd": "^5.0.2",
    "ng2-search-filter": "^0.5.1",
    "ngx-admin-lte": "^3.0.0-beta.1",
    "ngx-cookie-service": "^2.1.0",
    "ngx-order-pipe": "^2.0.2",
    "ngx-pagination": "^3.2.1",
    "ngx-toastr": "^11.1.0",
    "perfect-scrollbar": "^1.4.0",
    "rxjs": "^6.6.7",
    "rxjs-compat": "^6.6.7",
    "rxjs-tslint": "^0.1.8",
    "tslib": "^2.0.0",
    "utila": "^0.5.0-dev.1",
    "yarn": "^1.13.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.13",
    "@angular/cli": "^11.2.13",
    "@angular/compiler-cli": "^11.2.14",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~2.0.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.7",
    "webpack": "^4.4.1"
  }
}

```

**Comment by kabutotx** [comment]
Most likely an html or class problem. Lots of changes from AdminLTE 2 to 3.
1) View any console messages with dev-tools in browser.
2) Compare to starter.html since it is small.
3) Double check closing tags. That is what I usually messed up.

**Comment by REJack** [comment]
@HariPrasad-1493 did you followed the v3 Upgrade Guide completly? It looks like you missed some steps.
