### ISSUE TITLE
[BUG] Select2 bootstrap 4 theme not displaying, select2 standard theme incorrect height

### ISSUE THREAD

**Issue by leliofa** [ColorlibHQ/AdminLTE#3745]
**Describe the bug**
Trying to apply the select2 bootstrap4 theme I get an inconsistent layout (missing frame and contents)
Trying to fallback to the standard css for select2 I get an incorrect height that cannot be forced.
All the libraries are correctly loaded with the correct sequence (first standard css, second the bs4 theme)

**To Reproduce**
See screenshots

**Expected behavior**
Repllication of the documentation example.

**Screenshots**
<img width="927" alt="Screenshot 2021-06-03 at 15 11 55" src="https://user-images.githubusercontent.com/14059901/120650608-3dff5880-c47e-11eb-9e78-c2f5b9d523c7.png">With Bootstrap4 theme
<img width="864" alt="Screenshot 2021-06-03 at 15 12 57" src="https://user-images.githubusercontent.com/14059901/120650709-5bccbd80-c47e-11eb-86ba-6b9c35497fd9.png">
Without Bootstrap4 theme

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.0
- Operating System:  macOs BIGSur
- Browser (Version): Firefox Latest or Chrome Latest

**Additional context**

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

or 

use the latest browser like edge, chrome, Mozilla

or

check HTML code  properly compared with new version

**Comment by REJack** [comment]
@leliofa Did you tested it with AdminLTE v3.1?
