### ISSUE TITLE
[FEATURE] migrate from node-sass to dart sass

### ISSUE THREAD

**Issue by rogeliotg** [ColorlibHQ/AdminLTE#3771]
I have an install problem with node-sass on windows 10  (no administrative rigths).

Also node-sass is deprecated and is recommended to change to dart sass.

Any plans on migrate this?

**Comment by rogeliotg** [comment]
FYI, I make my way to migrate to sass:
desinstall node-sass and install sass:

`  "devDependencies": {
    ....
    "sass": "^1.34.1",`

change compile task:

`    "css-compile-bash": "sass --source-map ",
`
and change some paths into adminlte.scss:

`@import "../../node_modules/bootstrap/scss/functions";
@import "bootstrap-variables";
@import "../../node_modules/bootstrap/scss/bootstrap";`

**Comment by ZhangChengLin** [comment]
https://github.com/ColorlibHQ/AdminLTE/blob/97d6a97d16081fa8d09f627f5ae7f4bd0aafb5a9/gulpfile.js#L22

**Comment by danny007in** [comment]
Done in version 4 adminlte https://github.com/ColorlibHQ/AdminLTE/tree/v4-dev
