### ISSUE TITLE
[QUESTION] When is v3.2 expected to release?

### ISSUE THREAD

**Issue by 831220** [ColorlibHQ/AdminLTE#3772]
Very interested in the "slim" version of css,  to improve load speed of the page.
Is there a projected date or so?
Very grateful to this project 
:1st_place_medal:

**Comment by SmileYzn** [comment]
Try to not ask for releases, use this time to contribute or report bugs.

Is a bit rude, you can see the project status in Projects tab.
So you will see what is to do, in progress and what is done for next releases.

**Comment by 831220** [comment]
> Try to not ask for releases, use this time to contribute or report bugs.
> 
> Is a bit rude, you can see the project status in Projects tab.
> So you will see what is to do, in progress and what is done for next releases.

Oh, I see...sorry.   I'm very new here around. Thanks for the tip.
