### ISSUE TITLE
What is the role of lintScss?

### ISSUE THREAD

**Issue by ZhangChengLin** [ColorlibHQ/AdminLTE#3774]
https://github.com/ColorlibHQ/AdminLTE/blob/a65e7716e29b82f71cde933d668076704b7fc586/gulpfile.js#L104-L112

Is this paragraph unfinished? What does it do?

**Comment by danny007in** [comment]
lints the scss files

**Comment by ZhangChengLin** [comment]
> lints the scss files

Why did not use automatic repair? It just prints.
Is there any problem?
@danny007in

**Comment by danny007in** [comment]
> 
> 
> > lints the scss files
> 
> Why did not use automatic repair? It just prints.
> Is there any problem?
> @danny007in

it for non vscode users

ill add in futere
