### ISSUE TITLE
Preloader Very Slow with Datatables

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3775]
Preloader Very Slow with Datatables

![Desktop Screenshot 2021 06 12 - 12 27 24 25](https://user-images.githubusercontent.com/31727156/121790176-52adc000-cbe5-11eb-9a77-c510c9ed5971.png)

**Comment by danny007in** [comment]
its the behavior of preloader

**Comment by muhanadali100** [comment]
> 
> 
> its the behavior of preloader

it's just with datatables

**Comment by danny007in** [comment]
try https://stackoverflow.com/questions/55468588/datatable-initialization-events-fired-before-table-loaded
