### ISSUE TITLE
[Question] How to manage adminlte 3.1 required js files

### ISSUE THREAD

**Issue by mhanchini** [ColorlibHQ/AdminLTE#3778]
Hi
according to this example [AdminLTE-3-Angular by erdkse](https://github.com/erdkse/adminlte-3-react)
I looking for adminlte js files <jquery, adminlte.js,demo.js and so on> that usually added in index.html, how to load it without called in index.html or import it in index.js or app.js?
there is no script tags on index.html or import in index.js or app.js

**Comment by danny007in** [comment]
u needed to ask to angular
