### ISSUE TITLE
Do I need to include Bootstrap.js separately?

### ISSUE THREAD

**Issue by ishan501** [ColorlibHQ/AdminLTE#3789]
I'm trying to integrate AdminLTE V 3.1.0 into my Laravel project V 8.4.

The problem is, the 'nav-link dropdown-toggle' doesn't work as expected, it doesn't show 'dropdown-item'.

But, when I include 'bootstrap.min.js' then it works.

My question is, do I need to include 'bootstrap.js' separately? I thought 'adminlte.min.js' should be enough.

**Comment by danny007in** [comment]
needed to bootstrap.js seperately

**Comment by danny007in** [comment]
plz check demo pages

**Comment by ishan501** [comment]
Ok, thanks!
