### ISSUE TITLE
Suggestion for version number

### ISSUE THREAD

**Issue by bobonov** [ColorlibHQ/AdminLTE#3804]
This is a suggestion about version number.
Since the major version number is tightly connected to bootstrap major version number, maybe you should skip 4 and go directly to 5, so it gets in line with the bootstrap version used by the theme.

I know it not a big issue, but I think on communication and marketing point o view could help.
This is a bit like when php skipped version 6.

**Comment by danny007in** [comment]
php 6 version skipped 
because of some conflict in there team.

but we have clarity
