### ISSUE TITLE
[BUG] Badge Link

### ISSUE THREAD

**Issue by GitFoxDev** [ColorlibHQ/AdminLTE#3805]
**Describe the bug**
Set accent color to body tag (example "accent-success").
Add "badge badge-" classes to "a" tag, badge becomes link color. Link color resets the color of the text inside the badge (if "accent-success", all text inside badge be green). 

**To Reproduce**
1. Set class 'accent-success' to <body>
2. Create: `<a href="#" class="badge badge-info">Test</a>`
4. See error (text "Test" be green, not white/black

**Screenshots**
Its Ok - http://dl4.joxi.net/drive/2021/06/25/0019/1694/1259166/66/4c9383804d.png
Bug (add accent to body) - http://dl3.joxi.net/drive/2021/06/25/0019/1694/1259166/66/300dc17852.png

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Browser (Version): Firefox (Latest)

**Additional context**

**Comment by danny007in** [comment]
replace `badge-info` to `bg-info`

**Comment by danny007in** [comment]
add `text-white`

**Comment by SmileYzn** [comment]
Or just use Span badge inside <a> tag

**Comment by REJack** [comment]
fixed with c40e598
