### ISSUE TITLE
[BUG] - Hyperlinks not working

### ISSUE THREAD

**Issue by DardanHaliti** [ColorlibHQ/AdminLTE#3806]
**Describe the bug**
Hi,
I cloned the AdminLTE 3.1 Version
I followed the steps from the source: [https://github.com/ColorlibHQ/AdminLTE/tree/v3]
When I run the project using 'npm run dev' the project opened on port 3000.
when I tried to use/see the dashboards 1/2/3 the charts and everything else they won't open it seems like the hyperlinks are broken. When I changed the class nav-link to nav-link1(even if it lost its style) the hyperlinks seemed to work. Could you have a look at it?
**To Reproduce**
1. clone the project: git clone https://github.com/ColorlibHQ/AdminLTE.git
2. cd AdminTLE
3. npm install
4. npm run dev
5. 5. projects open on browser port 3000
6. Hyperlinks seem not to work [myabe a bug]

**Expected behavior**
To access the dashboard and all the other HTML pages via mouse click and not to open them in a new tab every time to see the project/dashboard.

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version:3.1
- Operating System:  windows 10
- Browser (Chrome (Latest)): 

**Additional context**

**Comment by Shidersz** [comment]
I think this is related to a problem I have already reported and is related to the **IFrame** plugin. See #3649
