### ISSUE TITLE
[BUG] Content height bugs when page loads

### ISSUE THREAD

**Issue by arthurmgb** [ColorlibHQ/AdminLTE#3822]
I installed AdminLTE on Laravel and I always come across this bug. What happens is that when I load the page for some reason the content height is calculated wrongly and this white "div" in the footer appears for a few seconds, I tried many solutions on the internet and none of them solved my problem 100%. I also tried modifying the .wrapper, .content-wrapper classes, but without success. I also tested it downloading from this repository and the same thing happens. How do I solve this problem?

![124405437-07368f80-dd15-11eb-8677-364442713ada](https://user-images.githubusercontent.com/62814691/124491713-f4aa6d80-dd89-11eb-8d3a-2e249bc097d7.png)

**Comment by Shidersz** [comment]
I want to share some extra data related to this problem:

- There should not be a footer defined on the page.
- To reproduce the problem you can edit the [starter.html](https://github.com/ColorlibHQ/AdminLTE/blob/master/starter.html) page to remove the **footer** definition on a development environment.

**Comment by arthurmgb** [comment]
I deleted the footer and made some changes. I'm not sure if it's right, but this code is working for me:

`            .wrapper{
                width: 100%;
                min-width: 100%;
                height: auto !important;
                position: absolute;
            }
            .content-wrapper{
                position: fixed;
                width: auto;
                top: 50px !important;
                bottom: 0px !important;
                right: 0px !important;
                left: 0px !important;
            } `

**Comment by REJack** [comment]
fixed with 4a2a28f

**Comment by Shidersz** [comment]
@REJack I'm not sure if problem is fixed now. The height was calculated fine previously, but there was a few hundred milliseconds where you see a white rectangle at the bottom of the page (as shown on the image). I have download latest commit to my test environment and the effect is still present, even more, now I can see a vertical scroll bar on the starter page when you do not need one for it. Check next video (look at the bottom)...

https://user-images.githubusercontent.com/63609705/125381611-9a517400-e36a-11eb-90e6-cbcccefd62f9.mp4

I think problem is related with delay on calling method `fixLayoutHeight()`. I will try to investigate more when get some time...
