### ISSUE TITLE
[QUESTION] Is it possible to change the DataTables pagination colour without using accent-*?

### ISSUE THREAD

**Issue by chetcuti** [ColorlibHQ/AdminLTE#3824]
Version: AdminLTE v3.1.0

I'm trying to change the color of the DataTables pagination, and the recommended way seems to be to use accent-\*, but when I add accent-\* to my body tag it changes my link colour too, which is very undesirable when my accent colour is red. I've tried using accent-\* in various areas but I haven't had any luck getting my DT pagination and URL colours to be different.

This is the pagination element I'm trying to change the colour of: https://i.imgur.com/bMtoBdp.png

Other than manually finding and changing the colouring in the CSS, is there any other way to accomplish this?

Oddly enough, while trying to search for solutions I came across my issue submission from 2016 about the exact same thing in the previous version of AdminLTE, #951. Ideally I would like to avoid manually messing with the CSS like I did back then.

**Comment by Mohamedn123** [comment]
I always do it manually,
You can find the css class in Google Chrome Developers Tools and then you can change it inline and set the color to whatever you like. But for an automated way I am not aware of any method that does that

**Comment by REJack** [comment]
That's already added in master (aka coming v3.2)
