### ISSUE TITLE
[FEATURE] add reload ability if allowDuplicates = false to IFrame Plugin

### ISSUE THREAD

**Issue by huskier** [ColorlibHQ/AdminLTE#3825]
To express the issue clearly, assume:
1. left-side-bar control item "pageA" can open a new tab named "TabA" with loaded page "/root/pageA.html";
2. There is a link <a  href="/root/pageB.html">pageB</a> in TabA's pageA.html page.

The issue is:
Once we've clicked the link "pageB", pageB.html will be loaded into the tab ("TabA"). Then when we click the left-side-bar control item "pageA", pageA.html cannot be loaded into the tab ("TabA"), instead, pageB.html is still displayed. We expect that the pageA.html will be loaded into the tab ("TabA") after we click the left-side-bar control item "pageA".

Thanks for your help.

**Comment by teja-94** [comment]
I have faced the same issue. If anyone finds out the issue. Please let me know.

**Comment by huskier** [comment]
I guess that once a specific tab is opened, when we trigger the left-side-bar control item again, the tab is just switched, and the html page is actually not reloaded. To solve the current issue, I think we have to force the html page reloading.

**Comment by REJack** [comment]
is there any error in the console?

**Comment by huskier** [comment]
No, There is no any error in the console. 
If the specific tab is firstly closed, then reopen with the left-side-bar control item, the behaviour is expected.

To solve the issue, I think the html page inside the tab should be reloaded whenever we trigger the the left-side-bar control item, instead of just switching to the tab.

**Comment by REJack** [comment]
I will add a option to reload the tab if single tab mode is active (allowDuplicates = false), I would not preferr to reload the windows but as a option it would be helpful for users 😄

**Comment by erkansen** [comment]
Is there any update on this issue? I have to update page content when user clicks to menu items.

**Comment by REJack** [comment]
at the moment no, but I will add it in the next days.

**Comment by REJack** [comment]
added with 4a2c52d9627ca707b350e1839f595f812710ecee
