### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by misterg200** [ColorlibHQ/AdminLTE#3826]
I am just getting started with adminLTE. I cloned from the git repo and got the index.html page working properly. After that a recompile (using npm install & npm run compile). As result the CSS files are regenerated and the index.html is still working but:
the navigation menu links are not working. This concern the link with the nav-item class.
![grafik](https://user-images.githubusercontent.com/87045955/124716507-74f4de00-df04-11eb-861f-e3cfad6f3dcb.png)

Version: AdminLTE 3.1.0
OS: windows 10

Any idea how I can get this fixed?
Thanks in advance

**Comment by ZhangChengLin** [comment]
Do you want to control different display states under different screens?
If so, have you tried adding a layer of dom to control the display state.

**Comment by misterg200** [comment]
No, I am fighting with my first compilation try. I simply run "git clone https://github.com/ColorlibHQ/AdminLTE.git" to download the package and run "npm install" and then "npm run compile" to test the process of scss to css generation. This process worked find, but the generated file seems to have an issue. 
I only edit the file (index.html) after I saw that the links are not working. In that fil, I added the code that you see in line 50-52 in the screenshot above to test the achors.

**Comment by ZhangChengLin** [comment]
If you are contacting this project for the first time, maybe you should look at more source code to understand something at this time. I don’t know what you are struggling with. The 3.1 series I know will perform some plug-in file operations after npm installs dependencies. You should pay attention.
If it is correct, 3.1 development should run the 23rd line dev of the package.json file for debugging and viewing.

**Comment by netphonetech** [comment]
I have the same issue here, when you use the adminLTE.min.js file that you downloaded it works well, but when you compile your adminLTE.min.js the links are not clickable, with the error attacehed: 
![image](https://user-images.githubusercontent.com/53331997/124795647-eb233000-df58-11eb-929f-da2a2f2efec3.png)

**Comment by Shidersz** [comment]
I believe your problems are related to the next issue I have opened some time ago: #3649 

I'm using next workaround as a quick fix to get links working, but the final fix on the `IFrame` plugin should be other:

```diff
diff --git a/build/js/IFrame.js b/build/js/IFrame.js
index 0fbb2472..8e615099 100644
--- a/build/js/IFrame.js
+++ b/build/js/IFrame.js
@@ -255,7 +255,8 @@ class IFrame {
       }, 1)
     })
     $(document).on('click', `${SELECTOR_SIDEBAR_MENU_ITEM}, ${SELECTOR_SIDEBAR_SEARCH_ITEM}`, e => {
-      e.preventDefault()
+      /* e.preventDefault() */
+
       this.openTabSidebar(e.target)
     })

```

**Comment by misterg200** [comment]
Thanks for your suggestion. Your workaround also works for me.  Here is what I did:
![grafik](https://user-images.githubusercontent.com/87045955/124806270-cb8e0680-df5c-11eb-821e-76f6902bd16d.png)

**Comment by misterg200** [comment]
the proposed workaround works. A real fix will be fine.

**Comment by Shidersz** [comment]
Yea, but note that change will affect the `IFrame` plugin and may not work as expected if you need it.
