### ISSUE TITLE
[FEATURE] IFrame Tab without close button

### ISSUE THREAD

**Issue by decodethis** [ColorlibHQ/AdminLTE#3827]
Is it possible to add an option for the Iframe Tab, so that could never be removed.

Remove the (X) button from the tab and the "Close All" and "Close All Other" wouldn't affect this "static" tabs.

When i load the app there are several default Tabs that are automatically Created and should always b present in the iframe navbar.

**Comment by danny007in** [comment]
closing for https://github.com/ColorlibHQ/AdminLTE/issues/4580
