### ISSUE TITLE
[BUG] The custom area in the "Fixed Sidebar + Custom Area" layout disappears when using small text

### ISSUE THREAD

**Issue by chetcuti** [ColorlibHQ/AdminLTE#3828]
**Describe the bug**
When you have small text enabled on the body HTML tag, the custom area in the "Fixed Sidebar + Custom Area" layout doesn't display. I originally found this issue while trying to apply the text-sm class to the body tag, but when I went to the live AdminLTE demo to investigate, I was able to reproduce the issue using the control sidebar.

**To Reproduce**
1. Open the live demo of the Fixed Sidebar + Custom Area page: 
     https://adminlte.io/themes/v3/pages/layout/fixed-sidebar-custom.html
2. Open the control sidebar on the right-hand side
3. Scroll down to the "Small Text Options" section
4. Enable the "body" option
5. The custom area has now disappeared

**Expected behavior**
The custom area should continue to be displayed even if small text is being used.

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  Linux
- Browser (Version): Vivaldi

**Comment by REJack** [comment]
fixed with ad2cdc7
