### ISSUE TITLE
new thought

### ISSUE THREAD

**Issue by pucoder** [ColorlibHQ/AdminLTE#3829]
**The current version is based on Bootstrap**

**could you consider the more scientific Tailwind CSS front-end framework?**

**The website address is https://tailwindcss.com/**

**Comment by REJack** [comment]
Actually not, since we use in the whole template bootstrap mixins and variables.

May @danny007in has an Idea to split our main code out to use it in various frameworks.

**Comment by danny007in** [comment]
adminlte v4 will be released in 2 month.

tailwind i may try in adminlte v5, and also may be in bootstrap v6 they make use of tailwind + bootstrap to support.

**Comment by danny007in** [comment]
@pucoder i have idea for how to adminlte v4 + tailwind i will add in docs

**Comment by joowdx** [comment]
> i have idea for how to adminlte v4 + tailwind i will add in docs

Does that mean you'll be building a separate tailwind version or just run tailwind along bootstrap?
Looking forward to it !
