### ISSUE TITLE
V4 Sidebar Error

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3861]
https://user-images.githubusercontent.com/31727156/127412731-dbb170b9-adf0-4537-b024-4cbf7567161a.mp4

when i click to any nav-item it's don't work (Widgets,Layout options,Forms,Tables)

i download the last update date is 18-7-2021

before previous update it's working ok without any proplem

**Comment by REJack** [comment]
V4 isn't ready to test now, the JS Scripts are still not migrated so it's normal that it wont work.
