### ISSUE TITLE
[QUESTION] how can i do add tab from subpage?

### ISSUE THREAD

**Issue by shngndgd** [ColorlibHQ/AdminLTE#3862]
Hi everyone,
i used tabbed iframe plugin in adminlte3 version and I want to add a new tab by clicking a button on the subpage.

I have been added to the adminlte.js file
**var SELECTOR_CUSTOM_BUTTON= 'a.custom-button';**
after to 
**var SELECTOR_SIDEBAR_MENU_ITEM = '.main-sidebar .nav-item > a.nav-link';**

and 

```
$__default['default'](document).on('click', SELECTOR_CUSTOM_BUTTON, function (e) {
   e.preventDefault();
_this2.openTabSidebar(e.target);
 });
```

i used subpage button is **< a class="custom-button" href="/Product/Detail/1">Detail Button< / a >** but dont work.

please could you tell me what is my fault?

**Comment by erkansen** [comment]
Hi,

You can call the below code to create new tab page.

top.$('.content-wrapper').IFrame('createTab', 'Page Title', 'Name of the html or php file.html, 'PageID', true);
