### ISSUE TITLE
[BUG] IFrame fullscreen button issue when using layout navbar fixed

### ISSUE THREAD

**Issue by Shidersz** [ColorlibHQ/AdminLTE#3864]
**Describe the bug**
The full screen button of the **IFrame plugin** is not working as expected when enabling `layout-navbar-fixed` on the body tag.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/iframe.html
2. Open the right control sidebar and enable the fixed checkbox for the **Header Options**
3. Close the right control sidebar.
4. Use the IFrame full screen toggle button.
5. Note full screen mode do not cover `100%` height of the screen.

**Video**
Next video shows how to reproduce the issue:

https://user-images.githubusercontent.com/63609705/127776027-5c98590a-ada0-41ca-9fad-36b64e863230.mp4

**Environment (please complete the following information):**
- AdminLTE Version: `dev-master`
- Operating System:  -
- Browser (Version): Firefox 90.0.2

**Comment by REJack** [comment]
Oh dang I killed it 🤣 I will check it later this day

**Comment by Shidersz** [comment]
😄 No problem, there are other bugs. I will report it later and I will try to help when get some time...

**Comment by REJack** [comment]
Ok 😄 you can join on our new discord, if you want to 😃

**Comment by REJack** [comment]
fixed with 13bcd7b662b5602f284903a087547e9f1146bc61
