### ISSUE TITLE
[BUG] Sidebar collapsing animation causes ugly word wrapping during transition

### ISSUE THREAD

**Issue by bastinald** [ColorlibHQ/AdminLTE#3865]
Check this out:

https://imgur.com/a/tgGs1A2

During the sidebar collapsing animation, there is an ugly word wrap effect (notice how the text goes below the icons for a brief moment).

I've managed to solve it by using text-nowrap, but should this fix not be included in the core?

**Comment by REJack** [comment]
That's an old known issue, after trying some fixes I need to say that we tackle this issue while developing v4 since we need to rework the whole sidebar expand/collapsing stuff.

**Comment by bastinald** [comment]
It works fine in 3.0 but not 3.1: https://adminlte.io/themes/dev/AdminLTE/index.html
