### ISSUE TITLE
[BUG] IFrame default tab height issue

### ISSUE THREAD

**Issue by Shidersz** [ColorlibHQ/AdminLTE#3872]
**Describe the bug**
The [IFrame documentation](https://adminlte.io/docs/3.1//javascript/iframe.html) says we have to explicitly define the `height` of a default tab as shown next:

```html
<div class="tab-pane fade active show" id="panel-index" role="tabpanel" aria-labelledby="tab-index">
  <iframe src="./index.html" style="height: 671px;"></iframe>
</div>
```

That is not correct, because height always depend on the client screen size. Height of the default tab should be automatically calculated as with the **empty tab** or the **loading screen**.

**To Reproduce**
1. Install a development environment following the [crontributing guidelines](https://github.com/ColorlibHQ/AdminLTE/blob/a9094a818923204ca4f9d8ed3b2bfb60e615b8df/.github/CONTRIBUTING.md)
2. Edit the `iframe.html` file and use next `content-wrapper` markup to add a default tab
    ```html
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper iframe-mode" data-widget="iframe" data-loading-screen="750">
      <div class="nav navbar navbar-expand navbar-white navbar-light border-bottom p-0">
        <div class="nav-item dropdown">
          <a class="nav-link bg-danger dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Close</a>
          <div class="dropdown-menu mt-0">
            <a class="dropdown-item" href="#" data-widget="iframe-close" data-type="all">Close All</a>
            <a class="dropdown-item" href="#" data-widget="iframe-close" data-type="all-other">Close All Other</a>
          </div>
        </div>
        <a class="nav-link bg-light" href="#" data-widget="iframe-scrollleft"><i class="fas fa-angle-double-left"></i></a>
        <ul class="navbar-nav overflow-hidden" role="tablist">
          <li class="nav-item active" role="presentation">
            <a class="nav-link active" data-toggle="row" id="tab-index" href="#panel-index" role="tab" aria-controls="panel-index" aria-selected="true">
              Dashboard v1
            </a>
          </li>
        </ul>
        <a class="nav-link bg-light" href="#" data-widget="iframe-scrollright"><i class="fas fa-angle-double-right"></i></a>
        <a class="nav-link bg-light" href="#" data-widget="iframe-fullscreen"><i class="fas fa-expand"></i></a>
      </div>
      <div class="tab-content">
        <div class="tab-pane fade active show" id="panel-index" role="tabpanel" aria-labelledby="tab-index">
          <iframe src="./index.html" style="height: 671px;"></iframe>
        </div>
        <div class="tab-empty">
          <h2 class="display-4">No tab selected!</h2>
        </div>
        <div class="tab-loading">
          <div>
            <h2 class="display-4">Tab is loading <i class="fa fa-sync fa-spin"></i></h2>
          </div>
        </div>
      </div>
    </div>
    ```
3. Use `npm run dev` to compile and start a demo at `http://localhost:3000/`.
4. Click on the `Tabbed IFrame Plugin` link of the demo site.
5. See height problem of the default tab (note this depends on the client screen size)

**Expected behavior**
Height of the default tab should be automatically calculated from JQuery/Javascript, as it is already done with the **empty tab** or the **loading screen**.

**Screenshots**
At next you can see an example of the height issue (when using hardcoded value on the html markup). As you can see, the default tab content do not use the 100% available height.

![Screenshot 2021-08-02 at 18-25-49 AdminLTE 3 Tabbed IFrames](https://user-images.githubusercontent.com/63609705/127925923-b4748191-8ee4-472d-a5ec-f955ac752ad3.png)

**Environment (please complete the following information):**
- AdminLTE Version: dev-master
- Operating System: -
- Browser (Version): -

**Comment by FlyArtist** [comment]
How to solve this problem now, how should I use the height of iframe tags. help~
