### ISSUE TITLE
Multiple control sidebars api

### ISSUE THREAD

**Issue by frosadev** [ColorlibHQ/AdminLTE#3890]
Hi,
Is there a way to use the data api to handle multiple control sidebars?
I saw that the javascript api has the target option to do it. Created on the issue:
#2901 

Thanks in advance.

**Comment by REJack** [comment]
any javascript api option is also available with the data api.

**Comment by frosadev** [comment]
So, in that case, on the button to toggle it the syntax is something like this?
data-controlsidebar-target="targetId"
Yes?

Is it possible to add that to the online docs?

**Comment by frosadev** [comment]
I tried many things and I can't have this working.
Is it possible to share the syntax for this to work? 
@REJack

**Comment by REJack** [comment]
You need to download the sourcecode and compile the dist files then it works :D its still in development and will released with v3.2.0.
