### ISSUE TITLE
[BUG] Dropdown.js Data API not working as expected

### ISSUE THREAD

**Issue by 1994rstefan** [ColorlibHQ/AdminLTE#3905]
**Describe the bug**
When viewing the AdminLTE 3 demo on the Dashboard v2 page the "Monthly Recap Report" has a dropdown inside it's card tools. (The wrench icon)
When I copy the exact same HTML code, the Dropdown is not working. Shouldn't that get handled by the data API of the Dropdown.js file? (.../admin-lte/build/js/Dropdown.js)
It seems the data API only handles `.navbar [data-toggle="dropdown"]` and `.dropdown-menu [data-toggle="dropdown"]`. Is this intended behaviour? Do I need my own JS to handle clicks on the button as a trigger for the dropdown or how is this intended to work? I wasn't able to find any documentation about it either.

**To Reproduce**
1. Install admin-lte (via npm/yarn in my case) and include the JS/CSS files required
2. Copy the HTML of the "Monthly Recap Report" card from Dashboard v2 from the demo page
3. The dropdown of the wrench button is not working anymore

**Expected behavior**
Obviously the dropdown should open when I click the wrench button

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  Arch Linux
- Browser (Version): Chrome (92.0.4515.159)

**Additional context**
I am using AdminLTE inside a Symfony project using webpack encore to bundle JS/CSS. As far is I was able to check the JS is included correctly inside my page.

**Comment by 1994rstefan** [comment]
@REJack Thank you, it is working now.

But i still think, that the docs should get updated about this topic, especially because the newest docs seem to only relate to v2.4, which isn't even the current version of AdminLTE.
It is also confusing because the Bootstrap styles get included automatically, but the JavaScript not.

**Comment by REJack** [comment]
The "newest" docs that you mean is on page, but you can find the correct in the demo pages on the left side or in the readme.md (https://github.com/ColorlibHQ/AdminLTE#documentation).

**Comment by 1994rstefan** [comment]
@REJack Ok, but when I got to https://adminlte.io/ and click on "Docs" in the navigation there, I am getting to the v2.4 docs. Also the version selection (upper left corner inside the docs) does not allow to switch to the >3 docs. This is somewhat confusing.
