### ISSUE TITLE
[BUG] Activate push menu using data api worked but jQuery doesn't work

### ISSUE THREAD

**Issue by tannguyencse19** [ColorlibHQ/AdminLTE#3910]
**Describe the bug**
I want to create 2 different sidebar (1 in dashboard and 1 in modal). 

I tried copy sidebar component (from dashboard) and write 2 button with the same `data-widget="pushmenu"`, but it push 2 sidebar together at the same time. 

So I read the docs and copy the jQuery code example `$('.btn-modal-sidebar').PushMenu('toggle');`, but it doesn't activate the push menu.

I also try `$(document).on('shown.lte.pushmenu', () => console.log('worked'))`, `$('.btn-modal-sidebar').on("click", () => console.log('worked'))` and other `data-[options]` like `data-auto-collapse-size="768"`. It all worked.

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  Win 10
- Browser (Version): Chrome (Latest)

**Comment by REJack** [comment]
actually we wont tackle this issue, but I will look over it with the v4 development.
