### ISSUE TITLE
Collapse Menue shifts for headers

### ISSUE THREAD

**Issue by schroedt** [ColorlibHQ/AdminLTE#3913]
Hi there,

I noticed shifting collapsed menues, when using `headers` in the menue (as stated in exampels). This is very irritating, as your mouse need to move downwards when openening the menue via mouse-over:

![grafik](https://user-images.githubusercontent.com/6430367/131253895-f2cd8eb9-a2ef-43ed-b04b-75b86e2b235d.png)
![grafik](https://user-images.githubusercontent.com/6430367/131253908-707549c2-9f86-4c31-84c0-fb3e9d92247f.png)

**Comment by REJack** [comment]
That was a requests features, to stay near with the v2.4 experience. But I added `.hide-nav-header-on-hover` that you can add to the body or nav-sidebar to hide them on focus/hover. added with 791a846.
