### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hardhikgupta** [ColorlibHQ/AdminLTE#3925]
**Description the bug**
NavBar is not fixed. I makes user to slide to the top every time they want to switch to other screen.

**To See**
1. Go to 'dashboard'
2. Slide down
3. See navbar is not fixed

**Expected behavior**
A navBar should be fix at top it saves the time of usre and it makes app look good.

**Environment (please complete the following information):**
- AdminLTE Version:  v3.0.0
- Operating System:  Android 10
- Browser (Version): Chrome

**Comment by hardhikgupta** [comment]
I started working on this issue #3925

**Comment by REJack** [comment]
We have already a fixed navbar and a fixed sidebar! simpy add `.layout-navbar-fixed` or `.layout-footer-fixed` to body, you should take a look at our docs!
