### ISSUE TITLE
[BUG] Events being fired before animation completed

### ISSUE THREAD

**Issue by frosadev** [ColorlibHQ/AdminLTE#3936]
Hi,
I was looking to the events of expanding and collapsing the card and I noticed that the event is fired when the animation is still in progress..
Any suggestions on bypassing that and have the events being fired when the animation is actually completed?

@REJack 
As a reminder..

**Comment by frosadev** [comment]
The events for control sidebar have the same issue

**Comment by REJack** [comment]
added with 9e1de03c2d7ed85ba6ce744b970b5b73f8f90d9f, please test it later if I release the RC version :)
