### ISSUE TITLE
[HELP] How to prevent menu closing from firing on sidebar links

### ISSUE THREAD

**Issue by tacman** [ColorlibHQ/AdminLTE#3942]
**Is your feature request related to a problem? Please describe.**

When I click on a sidebar item that is a link, the sidebar animation of closing the menu is fired, and the new page doesn't load until after the animation, recreating an unnecessary delay.

**Describe the solution you'd like**

This is likely a configuration / HTML problem in my code, hoping someone can tell me what I'm doing wrong.

**Additional context**

For example, https://anki-subtitles.herokuapp.com/ -- click on credits, and it opens a submenu.  Clicking on either items closes the menu before opening the new page.

```html
<li class="nav-item menu-open nav-item">
   <!-- collapsible ancestor-->
   <a class=" nav-link  active">
      <span class="nav-icon fas fa-circle"></span>
      <p>
         <!-- spanElement -->
         <span>Credits </span>
         <span class="end fas fa-angle-left"></span>
      </p>
   </a>
   <ul class="nav-treeview menu_level_1">
      <!-- has leaf_class -->                        
      <li class="f nav-link leaf">                            
         <a href="/credits/bundles">
         Bundles 
         </a>
      </li>
      <!-- has leaf_class -->                        
      <li class="active last nav-link leaf">                                        
         <a href="/credits/javascript" class=" active">
         Javascript 
         </a>
      </li>
   </ul>
</li>
```

The javascript I'm using is a copy of what's generated from the gulp build command, and is included in my webpack config.  It seems to work, except for this issue.  

https://github.com/survos/BaseBundle/blob/master/src/Resources/assets/js/adminlte.js

Alas, my javascript skills are limited.  I think the issue is that the close menu event is being fired on the entire tree, when really I just want it to fire on the -treeview items (the branches, not the leaves).  

```js
domReady(() => {
        const button = document.querySelectorAll(SELECTOR_DATA_TOGGLE$1);
        for (const btn of button) {
            btn.addEventListener('click', event => {
                // event.preventDefault()
                const treeviewMenu = event.target;
                const data = new Treeview(treeviewMenu, Default$1);
                data.toggle();
            });
        }
    });
```

Any suggestions?

**Comment by REJack** [comment]
From the fact that you modified AdminLTE so heavy to run Bootstrap 5, I can't tell you whats wrong.

**Comment by tacman** [comment]
Hmm.  I'm using v4-dev, which is bootstrap 5.  The only modifications I've
made is to create a /dist directory and publish it on yarnpkg (a temporary
measure, until you do that, but I use this in many projects so I needed to
be able to install it with yarn).

Other than that, the only thing I'm doing is not using the .js file, but
instead using bootstrap.js and then the small .js file of the classes
you've used for the menus and trees.

**Comment by REJack** [comment]
v4-dev is not even a bit ready to use, so for that we actually give no support, you need to wait min for a beta version

**Comment by REJack** [comment]
after I published v3.2, I will start with the TS migration for v4.

**Comment by tacman** [comment]
I think my problem is something simple, a wrong class somewhere in the tree.

The demo code with v4-dev works for menus:
https://adminlte4.gatner.be/index3.html (click on Dashboard 2, the page
opens without closing the menu).

Alas, this demo link is out of date, but when I run gulp build on my local
repo, the menus exhibit this problem of closing.  I just can't see what I'm
doing wrong in generating the HTML.

**Comment by REJack** [comment]
I will check it later and write the diffs

**Comment by REJack** [comment]
your sidebar html markup isn't correct, you set `.nav-link` to the `li`-tag but that need on the `a`-tag and you need to set `.nav-item` to the `li`-tag

**Comment by tacman** [comment]
THANKS!!!   I'm embarrassed about how many hours I looked for that, and couldn't see what was wrong.

Works as expected now.
