### ISSUE TITLE
[BUG] alter bug in mozilla firefox browser in adminlte v3.2.0-RC

### ISSUE THREAD

**Issue by danny007in** [ColorlibHQ/AdminLTE#3944]
Showing every time in every page in  mozilla, but not in chrome

```
You load AdminLTE's "demo.js", 
this file is only created for testing purposes!
```

**Comment by REJack** [comment]
This looks like a browserSync bug, I only use firefox for the main developing and I only get this bug 1 of 10 tries (after restarting browserSync).

**Comment by danny007in** [comment]
not use browserSync, checked in release zip of adminlte v3.2.0-rc

**Comment by tuncaybahadir** [comment]
The relevant warning is on the 13th line of the demo.js file. It is added as setTimeout and is being queried with localStorage.getItem('AdminLTE:Demo:MessageShowed') . You won't have any problems when you remove the code.

**Comment by REJack** [comment]
I still can't replicate this :/

**Comment by REJack** [comment]
I close this issue due inactivity.
