### ISSUE TITLE
[FEATURE] Navbar Badges should be easier to read

### ISSUE THREAD

**Issue by PerryCodes** [ColorlibHQ/AdminLTE#3945]
The navbar badges are very difficult to read.  If I ever found myself using AdminLTE for a production product, I'd have to completely replace this component.  I'm not saying they're impossible to read... but if you compare them to other admin/dashboard templates, you'll find these could really use some improvement or replaced entirely with icons that are larger and easier to read, especially the numbers!

**Comment by PerryCodes** [comment]
Here's AdminLTE:
![image](https://user-images.githubusercontent.com/2401573/142030311-05ed3c01-beb4-43f1-b932-b06f026637bb.png)

This is typical of other admin templates, this one being SmartAdmin:
![image](https://user-images.githubusercontent.com/2401573/142030150-7d361b25-d468-4516-a9ed-c235c7e98d63.png)

I'm not a designer, so I'm not sure if it's the size, contrast, or what... but to my eyes, it's very difficult to easily read the AdminLTE badges.

**Comment by PerryCodes** [comment]
Just came across this one and it's a great example of clear and readable badges.  This one is CoreUI/Bootstrap:
![image](https://user-images.githubusercontent.com/2401573/143719479-b84802db-9bce-4d6b-910b-67e653bab3f3.png)

I suggest you click all three screenshots I've posted for a 1:1, original image... You'll see just how much of a difference there is between the readability of badges in AdminLTE and CoreUI.

**Comment by danny007in** [comment]
Fixed in https://github.com/ColorlibHQ/AdminLTE/commit/1bf2f88cdc000f910364980816fd23a2da4bfcae
