### ISSUE TITLE
I can't delete calendar events

### ISSUE THREAD

**Issue by mecnun2020** [ColorlibHQ/AdminLTE#3952]
I want to edit or delete calendar events. I am not using FullCalendar. How can I delete calendar events on the AdminLTE 3 site?
![delete](https://user-images.githubusercontent.com/91432884/134821252-19de01f3-aaf1-4c80-9175-7404b53ca778.png)

**Comment by REJack** [comment]
Check the FullCalendar API, if you use the calendar example, otherwise check the API/docs of your plugin

**Comment by mecnun2020** [comment]
@REJack I don't know how to use FullCalendar. When I looked at the original page of the AdminLTE 3 theme, I could not find the process of deleting calendar events.

**Comment by mecnun2020** [comment]
@REJack How can I perform the deletion? Can you explain it to me descriptively?

**Comment by kabutotx** [comment]
Go to the website for full calendar. Docs are there.
[https://fullcalendar.io/docs](url)
