### ISSUE TITLE
Css class "table" have issue while printing

### ISSUE THREAD

**Issue by guillaumecardon** [ColorlibHQ/AdminLTE#3965]
When you want to print a page containing table, background colors aren't applied.

1. Create a table like "`<table class="table"><tr><td class="bg-primary">Test</td></tr></table>`"
2. Open print window (Ctrl + P) and check "Background graphics"
3. Backgrounds are not displayed
4. Remove class "table" like this  "`<table><tr><td class="bg-primary">Test</td></tr></table>`"
5. Open print window (Ctrl + P) and check "Background graphics"
6. Backgrounds are ok

- AdminLTE Version: 3.1.0
- Browser (Version): Chrome (Latest) / Firefox (Latest)

**Comment by REJack** [comment]
fixed with 52d9473
