### ISSUE TITLE
[BUG] min-height for .content-wrapper not adequately calculated

### ISSUE THREAD

**Issue by tuncaybahadir** [ColorlibHQ/AdminLTE#3970]
**Describe the bug**
 The opened .control-sidebar-content overlap the footer.

**To Reproduce**
1. Create a short left menu and homepage.
2. You will see that the height of the content-wrapper class is calculated incorrectly.
3. In v3.1.0 and earlier, the calculation is correct in the same design, but in v3.2.0-rc, the measurement is calculated incorrectly in the same design.

**Expected behavior**
I request the size of the content-wrapper class to be calculated correctly

**Screenshots**

**v3.1.0 - No issues**
![resim](https://user-images.githubusercontent.com/1303432/136676415-aae557ab-a276-4cd7-9332-d5e699b68272.png)

**v3.2.0-rc - problematic**
![resim](https://user-images.githubusercontent.com/1303432/136676462-122bc3c4-fef7-4572-8021-ae85a3e6ade9.png)

**Environment (please complete the following information):**
- AdminLTE Version: [v3.2.0-rc]
- Operating System:  [windows 10]
- Browser (Version): [Firefox Developer Edition 94.0b3]

**Comment by tuncaybahadir** [comment]
Guys, any progress on this?

**Comment by REJack** [comment]
I need your body classes to check this correctly, sorry for the late response.

**Comment by tuncaybahadir** [comment]
Hi Jack,
`<body class="sidebar-mini accent-danger pace-minimal pace-done" style="height: auto;">`

**Comment by REJack** [comment]
Do you have a navbar & navbrand active?

**Comment by tuncaybahadir** [comment]
I'm sorry for my late answer,
it does the calculation wrong whether I make any selection in the menu or not.

Working correctly:
![resim](https://user-images.githubusercontent.com/1303432/144128787-5ac19e8a-8259-411d-b1e5-2343018993e8.png)

Malfunctioning :
![resim](https://user-images.githubusercontent.com/1303432/144128873-fd1465d8-b268-4b39-9b6a-39ca77455b6d.png)

**Comment by tuncaybahadir** [comment]
Hi Jack,

I guess there is no progress on this?

**Comment by REJack** [comment]
I've tested it again with various variations and it works for me, may you can try it on latest master.

**Comment by sitchi** [comment]
hello, i m are such a problem too. problem if the content does not completely reach the footer. version v3.2.0-rc and master
![Screenshot from 2022-01-10 04-07-23](https://user-images.githubusercontent.com/11546683/148706922-0d339919-39b3-40c8-982a-15a9db833a0f.png)

**Comment by REJack** [comment]
> hello, i m are such a problem too. problem if the content does not completely reach the footer. version v3.2.0-rc and master
> 
> 
> 
> ```
> 
> <body class="sidebar-mini dark-mode">
> 
> 
> 
> <nav class="main-header navbar navbar-expand bg-dark navbar-dark">
> 
> ```
> 
> 
> 
> ![Screenshot from 2022-01-10 04-07-23](https://user-images.githubusercontent.com/11546683/148706922-0d339919-39b3-40c8-982a-15a9db833a0f.png)
> 
> 

Did you only used the dist files from master or did you rebuild them?

**Comment by sitchi** [comment]
i used dist files from master

**Comment by REJack** [comment]
You should rebuild them, they are old and get only rebuild before releases.

**Comment by tuncaybahadir** [comment]
I don't think there is any improvement related to the problem. There is no problem in the old version, but as I wrote above, unfortunately, when the page height is low in the new version, the content-wrapper min-height value is calculated incorrectly. If the page is long enough, the problem goes away.

**Comment by tuncaybahadir** [comment]
I found exactly what was causing the problem I was having.

When I add text-sm in my navbar's class definition, <div class="content-wrapper"> height is calculated incorrectly. I think there will be a solution to this issue.

Incorrect Calculation:

<nav class="main-header navbar navbar-expand navbar-dark text-sm">

![resim](https://user-images.githubusercontent.com/1303432/149678389-d3d94407-6722-4119-be6e-13d938c8beaa.png)


Correct Calculation:

<nav class="main-header navbar navbar-expand navbar-dark">

![resim](https://user-images.githubusercontent.com/1303432/149678441-5814ea06-d059-4d74-8629-9278af39de5f.png)

**Comment by REJack** [comment]
@tuncaybahadir @sitchi I still can't replicate this, try it my latest dist files from master (f88d61c).
[dist.zip](https://github.com/ColorlibHQ/AdminLTE/files/7919291/dist.zip)

**Comment by tuncaybahadir** [comment]
@REJack I'll try and let you know.

**Comment by REJack** [comment]
I think its fixed if you not wrote again 🤣
