### ISSUE TITLE
Request: Can you make the expandable table expand on button click instead of the row click

### ISSUE THREAD

**Issue by psychrabi** [ColorlibHQ/AdminLTE#3973]
**Request:**
Can you make the expandable table expand on button click instead of the row click

**Screenshots**
![image](https://user-images.githubusercontent.com/17595403/136692746-7fd4d854-9fff-4348-883c-ac244ba83a60.png)

**Environment (please complete the following information):**
- AdminLTE Version: v3.2.0-rc ]
- Operating System:  Windows 11
- Browser (Version): Edge(Latest)

**Additional context**
The expandable table function is really awesome. I tried to change the expansion from the row click to button click but it would break the function as a whole. So, i was wondering if you can add option to change the event from row click to button click.

**Comment by REJack** [comment]
Try 41e2971, I've enhanced ExpandableTable with button click beside table row click

**Comment by psychrabi** [comment]
Nice.. working as intended.
Thank you
