### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defaults' of undefined at Object: <anonymous> (plugins.bundle.js)

### ISSUE THREAD

**Issue by mrnimavat** [ColorlibHQ/AdminLTE#3987]
![image](https://user-images.githubusercontent.com/91533223/136934058-f1d8cb1c-7fa6-47af-a32d-0e6faec80277.png)

This is MY issue 
When site is Live in server then Console display this type of error

**Comment by REJack** [comment]
due your bundling I cant say what exactly breaks, also it doesn looks like any known AdminLTE error.

**Comment by REJack** [comment]
I close this issue due inactivity.
