### ISSUE TITLE
[BUG] Sidebar - Scrollbar not working when change screen size

### ISSUE THREAD

**Issue by MatiSanchez** [ColorlibHQ/AdminLTE#3988]
Testing the menu when the size of the screen changes, when it gets smaller, I found that the scroll in the menu never appears:

![image](https://user-images.githubusercontent.com/7718389/136973146-f714fe93-8f75-4120-8d1e-30c6443b468e.png)

For example in v3 it works:

![image](https://user-images.githubusercontent.com/7718389/136973264-e141cf59-ba23-450d-be9a-332d6f76e20e.png)

I tried adding `overflow-y: scroll;` and other styles, but it doesn't work.

**Environment:**

AdminLTE Version: Last in v4-dev
Operating System: Windows 10
Browser (Version): Chrome 94.0.4606.81

Thanks!

**Comment by REJack** [comment]
AdminLTE v4 is still in progress, we didn't added overlayScrollbars to v4 that's why it doesn't show up.

**Comment by danny007in** [comment]
is this issue still exist ?

**Comment by MatiSanchez** [comment]
> is this issue still exist ?

With 4.0.0-alpha1, the problem continues

**Comment by danny007in** [comment]
fixed in https://github.com/ColorlibHQ/AdminLTE/commit/05d3c49284b4b11987064aee5566ac466ed86a7d
