### ISSUE TITLE
[BUG] SCSS Build Documentation Missing Import

### ISSUE THREAD

**Issue by edusoccer1121** [ColorlibHQ/AdminLTE#4000]
**Describe the bug**
Documentation additional styles missing variables-alt import. Hence scss build fails in the _root.scss import called by _core.scss import.

**To Reproduce**
1. Follow documentation additional styles guide for extending AdminLTE.
2. Copy paste scss example file

**Expected behavior**
SCSS build successfully without errors.

**Screenshots**
<img width="739" alt="Screen Shot 2021-10-21 at 12 37 50 PM" src="https://user-images.githubusercontent.com/25164205/138320462-1456a064-5499-4399-a096-eb0570a5e1b4.png">

**Environment (please complete the following information):**
- AdminLTE Version: 3.1
- Operating System:  macOS BigSur 11.6
- Browser (Version): Chrome Version 94.0.4606.81 (Official Build) (x86_64)

**Additional context**
Adding the import right after the normal variables file import corrects the issue.

**Comment by REJack** [comment]
fixed with d4f159a
