### ISSUE TITLE
[BUG] Can't toggle fullscreen in Tabbed IFrame Plugin

### ISSUE THREAD

**Issue by MedHossam** [ColorlibHQ/AdminLTE#4002]
Bug on toggleFullscreen in _Tabbed IFrame Plugin_ when opening a tab dynamically.

**To Reproduce**
1. Just call the method using this : `$().IFrame('openTabSidebar', $('<a href="./index.html">Dashboard</a>'))`
2. You won't be able to toggle full screen again

**Expected behavior**
Toggle full screen button to work properly.

**Environment**
- AdminLTE Version: v3.1.0
- Browsers: Chrome (any supported version), Firefox (any supported version)

**Comment by REJack** [comment]
The point is that the jQueryInterface isn't working correct and you break your iframe if your try too add/open a tab via javascript.
