### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darulmuqimin** [ColorlibHQ/AdminLTE#4032]
**Describe the bug**
can't acses script/css(style)

this is normaly
![image](https://user-images.githubusercontent.com/87954422/139867266-648d16c7-9a01-4fab-b521-52a2596df233.png)

but this not normal
![image](https://user-images.githubusercontent.com/87954422/139867424-6e9dbb56-2d30-468b-8f6c-7a30f3c8b451.png)

iam using at the same of template

**Comment by REJack** [comment]
you set not the correct path the js/css files. I would guess your links are realtive and not absolute.

**Comment by REJack** [comment]
I close this issue due inactivity.
