### ISSUE TITLE
[BUG] Add link in treeview menu

### ISSUE THREAD

**Issue by alexandre-1992** [ColorlibHQ/AdminLTE#4041]
Hi! 
I would like to add a link to menu of adminLTE3 with laravel 8. But when I click on the main menu it unrolls and shows me the menu below admin. But I have filled in the href:{{route:('home')}} in the menu link;

Could I add a link that opens a page while scrolling down the menu?

Thanks

I would like to add a link to menu of adminLTE3 with laravel 8. But when I click on the main menu it unrolls and shows me the menu below admin. But I have filled in the href:{{route:('home')}} in the menu link;

Could I add a link that opens a page while scrolling down the menu?

Thanks

My code
  <nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
      
      
      
      <li class="nav-item menu-open">
        <a href="{{Route('home')}}" class="nav-link active bg-white">
          <i class="nav-icon fas fa-tachometer-alt "></i>
          <p>
             <i class="right fas fa-angle-left"></i>
             <b>Menu</b>
             
          </p>
        </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link active bg-white">
                  <i class="fas fa-user-shield nav-icon"></i>
                  <p>
                      <i class="right fas fa-angle-left"></i>
                      <b>Admin</b>
                      
                  </p>
                </a>
              </li>
           </ul>
        </li>
    </ul>
</nav>

![image](https://user-images.githubusercontent.com/58185779/140937778-3e0cd0b2-6118-4e48-a8dc-cca1d8605b22.png)

When i click on menu, they just scroll down and open admin sub-menu

**Comment by REJack** [comment]
Do I understand correct you want to use the href from "Menu" instead of opening the submenu? If yes, this will not work since we ignore the url to open the submenu.

**Comment by alexandre-1992** [comment]
I would like to open the submenu but when I click on the "Menu" I would like to open a home page, and then when I click on admin I open the administration page. Is it possible?

**Comment by REJack** [comment]
there is actually not option to use the href actually, but we can add this feature to v4

**Comment by alexandre-1992** [comment]
Ok thanks! I'm waiting for v4 soon. Thanks
