### ISSUE TITLE
[SCSS] Demo page tiny pixel offset in jqvmap

### ISSUE THREAD

**Issue by AlDjo** [ColorlibHQ/AdminLTE#4042]
**Describe the bug**

**To Reproduce**
1. Go to 'https://adminlte.io/themes/v3/'
2. Loot at Visitors vector map
3. Look more closely at the zoom in and zoom out buttons
4. See how slightly of center the + and - signs are
5. Notice the strange CSS rule in _jqvmap.scss: .jqvmap-zoomin, .jqvmap-zoomout {  border: 1px solid #ddd; }

**Expected behavior**
The + and - sign buttons are precisely centered.

**Screenshots**
![jqvmap_off_center](https://user-images.githubusercontent.com/49390589/140956030-0b27791e-3cfd-4382-8507-d60a369c7efd.jpg)
![jqvmap_centered](https://user-images.githubusercontent.com/49390589/140956053-bcda7f36-9b9a-41ba-8092-deaa6a2df6a0.jpg)

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System:  Windows 10 Enterprise
- Browser (Version): Chrome (95.0.4638.69)

**Additional context**
Just a thing OCD people notice.

**Comment by REJack** [comment]
fixed with 9cc4ce3
