### ISSUE TITLE
[BUG] Kaban board not working

### ISSUE THREAD

**Issue by nilekshdhimer91** [ColorlibHQ/AdminLTE#4052]
I have Admin LTE **version 3.1.0**

1. I visited the Kaban board page and try to drag and drop but it's not working. 
2. Kaban board also needs horizontal scroll CSS when we add more boards.

**Comment by REJack** [comment]
> 1. I visited the Kaban board page and try to drag and drop but it's not working.

That's correct it's not workes due not implemented 🤣 we will add this with v4 since we not added a new drag n drop api/plugin

> 2. Kaban board also needs horizontal scroll CSS when we add more boards.

I see scrollbars 
https://i.imgur.com/HBhSwtc.png

**Comment by REJack** [comment]
I close this issue due inactivity.
