### ISSUE TITLE
[BUG] Dropdown menu toggle not working with ASPX pages

### ISSUE THREAD

**Issue by equezada-jej** [ColorlibHQ/AdminLTE#4054]
**Describe the bug**

When using top-nav layout in AdminLTE, dropdown menus are not opening. Looking at the source code, the `ul` with `dropdown-menu` class isn't adding the `show` class when clicking.
It works on html pages, but it's not doing so in ASPX pages.

**To Reproduce**
1. Import html from /pages/layout/top-nav.html into .aspx page
2. Click on 'Dropdown'
3. The dropdown menu doesn't appear.

**Expected behavior**
The dropdown menu should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/93919226/142213214-92f71369-1c98-4a5f-9eb0-e0421ff4993c.png)
![image](https://i.stack.imgur.com/vCqTU.png)
In demo:
![image](https://i.stack.imgur.com/AGUxA.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System: Windows 10
- Browser (Version): Chrome (95.0.4638.69)

**Additional context**
I go into more detail here https://stackoverflow.com/questions/70004934/issue-using-dropdown-menus-of-adminlte-in-aspx-page

**Comment by REJack** [comment]
Did I seen it right that you unload/commment-out the jquery & bootstrap js files?

If yes, they are needed for bootstrap's dropdown functionality.

**Comment by equezada-jej** [comment]
> Did I seen it right that you unload/commment-out the jquery & bootstrap js files?
> 
> If yes, they are needed for bootstrap's dropdown functionality.

ScriptManager is including the jquery and bootstrap files

**Comment by REJack** [comment]
Which bootstrap version is included? v5?

**Comment by equezada-jej** [comment]
> Which bootstrap version is included? v5?

Ah, it's v3.4.1. I imagine I would need to upgrade and see how it goes, right?

**Comment by equezada-jej** [comment]
The issue was indeed the version of bootstrap being used. Upgraded to v4.6.0 and the menu is working correctly.
