### ISSUE TITLE
[BUG] No license file for sparklines plugin

### ISSUE THREAD

**Issue by hyandell** [ColorlibHQ/AdminLTE#4068]
**Describe the bug**
 Looking at the sparklines plugin, I'm not seeing any licensing information.

I think it's this project, available under MIT license, https://github.com/mariusGundersen/sparkline

**To Reproduce**
See: https://github.com/ColorlibHQ/AdminLTE/tree/master/plugins/sparklines

**Expected behavior**
That the license embedded in https://github.com/mariusGundersen/sparkline/blob/master/readme.md would be present in the directory, or that there would be a short source header on the js files.

**Environment (please complete the following information):**
- AdminLTE Version: Latest GitHub on this date
- Operating System:  n/a
- Browser (Version): n/a

**Comment by REJack** [comment]
Same as with jquery-knob.
> We not modify the added Plugins so we wont add the license to the plugins if the author doesn't add it.
