### ISSUE TITLE
[BUG] when using layout-fixed and layout-navbar-fixed, content grows

### ISSUE THREAD

**Issue by kreic51** [ColorlibHQ/AdminLTE#4090]
**Describe the bug**
when using layout-fixed and layout-navbar-fixed, content grows in header size and the scroll bar appears

**To Reproduce**
1. Go to Dashboard v3 page or Extras - Pace page or one with little content.
2. Open Control Sidebar(demo.js)
3. Click in Sidebar Options - Fixed
4. Click in Header Options - Fixed
5. Close Control Sidebar

**Expected behavior**
that the content don't grow, the scrollbar don't appear and the footer don't move down

**Screenshots**
with layout-fixed
![image](https://user-images.githubusercontent.com/40365277/143341842-08bbb1c6-ab96-4b14-a70f-bc671752cf3c.png)

with layout-fixed and layout-navbar-fixed
![image](https://user-images.githubusercontent.com/40365277/143342930-d4265802-75a8-4c7f-ab36-897719ab9ce8.png)

**Environment (please complete the following information):**
- AdminLTE Version: v3.2.0-rc
- Operating System:  win 10
- Browser (Version): Chrome Versión 96.0.4664.45

**Additional context**
with few options in the sidebar you can see it without using layout-fixed.
in version 3.1.0 this does not happen.

**Comment by REJack** [comment]
Does it happens with the master (c0196f1) too?

**Comment by REJack** [comment]
here are my latest [dist files](https://github.com/ColorlibHQ/AdminLTE/files/7599534/dist.zip), so not need to compile them 😄

**Comment by kreic51** [comment]
yes, it happens too

**Comment by kreic51** [comment]
in layout.js when declaring the heights constants, there is the line

header: $(SELECTOR_HEADER).length > 0 && !$('body').hasClass('layout-navbar-fixed') ? $(SELECTOR_HEADER).outerHeight() : 0,

if it is changed by

header: $(SELECTOR_HEADER).length > 0 ? $(SELECTOR_HEADER).outerHeight() : 0,

the problem is corrected, but I don't know if something else breaks

**Comment by REJack** [comment]
fixed with c110138
