### ISSUE TITLE
[BUG] The config option in js api is not recognized

### ISSUE THREAD

**Issue by tlyau62** [ColorlibHQ/AdminLTE#4104]
**Describe the bug**
The option in js api is not recognized. 

For example, the option object in [treeview](https://adminlte.io/docs/3.0/javascript/treeview.html) has no effect no matter what the value is.

Looks like the issue is come from the config [here](https://github.com/ColorlibHQ/AdminLTE/blob/master/build/js/Treeview.js#L135) did not passed into the constructor.

**To Reproduce**
1. $('#my-treeview').Treeview({ trigger: '.nav-link' });

**Comment by REJack** [comment]
That's a know Issue and we don't know actually to fix it, also we will drop jQuery support in v4 so it's not really urgent for us. but you can set the config via data-attributes.

**Comment by tlyau62** [comment]
> That's a know Issue and we don't know actually to fix it, also we will drop jQuery support in v4 so it's not really urgent for us. but you can set the config via data-attributes.

The jQuery plugin is very useful for other js framework, like vuejs, to extend this library.i hope it can be kept 🙏

**Comment by REJack** [comment]
I'm still search a easy maintainable way to provide a UMD JS Plugin that works with jQuery too but, I didn't found a nice solution. May I need to generate a jQuery Plugin based on the Generic JS Plugin, at the moment jQuery plugins is "music of the future" like the germans say 😄

**Comment by tlyau62** [comment]
I will close the issue for now. Keep up the great work.👍

**Comment by tlyau62** [comment]
I see, i will close the issue for now. Keep doing the grea
