### ISSUE TITLE
[QUESTION] - Side menu Chevrons pointing left

### ISSUE THREAD

**Issue by ChrisLang** [ColorlibHQ/AdminLTE#4110]
Good day, 

Could I kindly find out why your chevrons in the side menu point left, this seems to be incorrect to me. 
I could very well be incorrect myself, so felt like reaching out.

This component for the side menu is basically a Accordion component. 
If you look at how its normally done, they always point down or right when closed and up when open. 
[https://dribbble.com/search/accordion%20ui%20component](url)

The way I think about it is an arrow pointing left is used when navigating back in time and arrow point right is navigating forward in time. 

I've been a designer / developer for almost 15 years and this one is a bit of an eye sore for me, not a biggy as I just think most people will over look it and isn't really breaking any UX.

other useful links I found
[https://ux.stackexchange.com/questions/5735/which-way-should-arrows-point-in-a-collapsible-accordion-left-down-down-up](url)
[https://www.smashingmagazine.com/2017/06/designing-perfect-accordion-checklist/#:~:text=First%2C%20if%20accordion%20items%20are,plus%20icon%20might%20work%20well.](url)

Cheers 😊

**Comment by REJack** [comment]
I understand your point and I had also my problems with it, but in v3 I wont change it to the "normal" behavior. I will change it in v4, may @danny007in will change it in our v4-dev branch.

**Comment by ChrisLang** [comment]
@REJack thanks for the feed back, very much appreciated 👌. No rush we'll update outside at some point

**Comment by craph** [comment]
Hi @REJack , @danny007in , 

I think this issue (Question) can now be closed because you already merged this : https://github.com/ColorlibHQ/AdminLTE/pull/4360 :)

Thank you very much.
