### ISSUE TITLE
Question about unexpected behaviour when import AdminLTE twice

### ISSUE THREAD

**Issue by chsx258** [ColorlibHQ/AdminLTE#4116]
Hello there.
I know that AdminLTE-min.js should not be imported twice in one page, but once I mistakenly do that and find AdminLTE can not control the element anymore.
 I am curious about how does it happened. And there is no same qustions in stackoverflow or other website.
I will be more than  glad if you can explain it for me.
Thanks!

**Comment by REJack** [comment]
may this comes from that AdminLTE itself initializes if certian element are found then a reinit after that could be break stuff also it's not recommend to import JS Scripts twice :D

**Comment by REJack** [comment]
I close this issue due inactivity.
