### ISSUE TITLE
[BUG] Form Warning Animation Weird Behaviour

### ISSUE THREAD

**Issue by tomasserravento** [ColorlibHQ/AdminLTE#4118]
**Describe the bug**
Form warning has a really weird animation behaviour when it tries to tell a value is required or the input format is incorrect.

**To Reproduce**
1. Go to https://adminlte.io/themes/v3/pages/forms/general.html?
2. Insert a value in email address or any form object. Make sure this value is with an incorrect format example asd
3. Press Submit
4. See the weird flicker animation (you can also see my video)

**Expected behavior**
A clear animation without flickering.

**Screenshots**
https://user-images.githubusercontent.com/81922863/145168741-4f38fba3-8901-43f8-a3b3-94114deb52f7.mp4

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System:  Windows 10
- Browser (Version): Chrome 96.0.4664.93

Let me know if you need any more information or if Im doing something wrong.

Thanks for such an amazing template!

**Comment by ArthurHetem** [comment]
This is a browser native validation warning, not AdminLTE

**Comment by REJack** [comment]
Yep that looks like a hardware acceleration bug, may en/disable hardware acceleration would help. but AdminLTE itself can't modify this warnings except Text but that's a HTML feature itself not AdminLTE's feature :D

**Comment by REJack** [comment]
may you have some autofiller extensions installed that could cause this weird transition.

**Comment by REJack** [comment]
I close this issue due inactivity.
