### ISSUE TITLE
In fullscreen mode, it does not stay on full screen when switching to another page.

### ISSUE THREAD

**Issue by Haktansoft** [ColorlibHQ/AdminLTE#4120]
In fullscreen mode, it does not stay on full screen when switching to another page.
Can localStorage be added?

**Comment by REJack** [comment]
please provide a video to show us the bug

**Comment by Haktansoft** [comment]
> please provide a video to show us the bug

https://user-images.githubusercontent.com/89358177/145395691-889b5c4c-3992-45b6-8dae-ac910acabc2b.mp4

**Comment by SmileYzn** [comment]
Hi REJack, there is the video (in webm, since cinnamon can save only this format lol):

https://user-images.githubusercontent.com/5851851/145999673-382c8476-b02f-4d4d-942f-bcbef5cf0ed5.mp4

Thanks for work :pray:

**Comment by SmileYzn** [comment]
I think that cannot be "Fixed", since:

[Stackoverflow awnser](https://stackoverflow.com/a/28218645)

"The API specifies that fullscreen will only operate on the current, or descending browser contexts."

**Comment by REJack** [comment]
True that feature need to be added from the browsers.

**Comment by mohsetiawanmodeong** [comment]
i have a same problem using adminlte 3. please what is the solution?

**Comment by MisterDuval** [comment]
> i have a same problem using adminlte 3. please what is the solution?

no solution, the "issue" is on the browser side

**Comment by mohsetiawanmodeong** [comment]
hmmm i c, we must create SPA on own website maybe
