### ISSUE TITLE
[Suggestion] Is it possible to add a slim version?

### ISSUE THREAD

**Issue by 016** [ColorlibHQ/AdminLTE#4121]
Hey, thx for the work, it's great! I am thinking a new project recently, but I found that: the file size has become large, like the AdminLTE.min.css(2.4.x=>107KB, 3.2=>1.4MB), honest it's not good for large visits. So my question is, is it possible to add a slim version?

one more thing: maybe build an app allow user, select and generate need code?

again, AdminLTE is good, thx for your work.

**Comment by REJack** [comment]
you could use purgeCSS for production, but at the moment there is no slim version planed for v3. But since we revive the skin system in v4 the css files will go back to normal sizes.

**Comment by REJack** [comment]
I close this issue due inactivity.
