### ISSUE TITLE
.dl-horizontal class not working

### ISSUE THREAD

**Issue by gaztum** [ColorlibHQ/AdminLTE#4122]
### Describe the bug
.dl-horizontal class not working

### Steps To Reproduce
1. Go to https://adminlte.io/themes/dev/AdminLTE/pages/UI/general.html
2. Scroll down to 'Description Horizontal'
3. See error

### Screenshots
![image](https://user-images.githubusercontent.com/61505273/144245201-e2fee818-1b9f-453c-bf52-ccf6df81e2c6.png)

| Item    | Version
| ------- | -------
| Laravel | 8

**Comment by REJack** [comment]
The DescriptionList classes e.g. `dl-horizontal`-class are from Bootstrap 3 and with Bootstrap 4 they was replaced with simple rows/cols.

**Comment by REJack** [comment]
The demo you looked at isn't the v3.1 demo, the correct one is here https://adminlte.io/themes/v3/pages/UI/general.html.
