### ISSUE TITLE
[BUG] - display: flex (d-flex) overriding display: none (d-none)

### ISSUE THREAD

**Issue by ChrisLang** [ColorlibHQ/AdminLTE#4141]
Good day,

So if you have .d-none and .d-flex on the same element, .d-flex is taking preference over .d-none. .d-none in my mind should come last Or is there a reason for not doing this that I'm not understanding.

Thanks
Chris

`.d-none {
  display: none !important;
}

.d-inline {
  display: inline !important;
}

.d-inline-block {
  display: inline-block !important;
}

.d-block {
  display: block !important;
}

.d-table {
  display: table !important;
}

.d-table-row {
  display: table-row !important;
}

.d-table-cell {
  display: table-cell !important;
}

.d-flex {
  display: -webkit-flex !important;
  display: -ms-flexbox !important;
  display: flex !important;
}

.d-inline-flex {
  display: -webkit-inline-flex !important;
  display: -ms-inline-flexbox !important;
  display: inline-flex !important;
}`

I have logged this with BS [https://github.com/twbs/bootstrap/issues/35547](url)

**Comment by REJack** [comment]
Since you PR is merged in BS v5, we wont fix it in v3.2.
