### ISSUE TITLE
Navbar Labels becomes blur when I changed the color

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#4159]
**Describe the bug**
In AdminLTE-3.1, I tried to change the Header Navbar color from white to danger as shown below:

`<nav class="main-header navbar navbar-expand navbar-danger navbar-light">`

But the resulting Navbar header looks blur. The labels are no more clear. See it below:
![adminlte_header](https://user-images.githubusercontent.com/34077129/147911553-f7e28537-8faa-46c2-8351-fba575808686.PNG)

How do I resolve this and make the labels clear and legible?

Thanks

**Comment by REJack** [comment]
replace `navbar-light` with `navbar-dark`.

**Comment by noblemfd** [comment]
@REJack  - Its still the same thing. Remains same color

**Comment by REJack** [comment]
I've tested it with v3.2 (master) and it works, if I replace `navbar-light` with `navbar-dark`. 

Then it looks like this:
![img](https://i.imgur.com/pireZPB.png)

**Comment by noblemfd** [comment]
@REJack  - I installed it using npm install admin-lte@^3.1 --save
How do I upgrade to 3.2

**Comment by REJack** [comment]
Actually you can't upgrade to v3.2 beside the v3.2-rc build, I wait for a PR after this I publish the new release.

**Comment by noblemfd** [comment]
Thanks so much @REJack
