### ISSUE TITLE
[BUG] Plugins folder does not exist, if used Yarn 3.x

### ISSUE THREAD

**Issue by Ajtak** [ColorlibHQ/AdminLTE#4168]
Hi!
I've just update my project to yarn 3.1.1. Unfortunately, **plugins** folder does not exist. I'm tried remove .yarn folder and install again, but not working still.

I used to import the js/css what I needed like this.

import "admin-lte/plugins/jquery/jquery.min.js";
import "admin-lte/plugins/fontawesome-free/css/all.min.css";
import "admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css";

Is possible use plugins folder with yarn 3.x?

Yarn's documentation recommends [not to use postinstall scripts](https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall).

Thanks

**Comment by REJack** [comment]
Sadly with v3.2 we wont change the scripts or init phase, but it will changed in v4.

Also I have no clue how to fix it 😞

**Comment by REJack** [comment]
I close this issue due inactivity.
