### ISSUE TITLE
Bug v3.2.0 - Two strange behavior in side menu

### ISSUE THREAD

**Issue by consigli** [ColorlibHQ/AdminLTE#4186]
Bug 1 - if you select "Nav Child Hide on Collapse" for nav sidebar, on mouse over it opens but not show child.
![hide](https://user-images.githubusercontent.com/1521856/149672398-acc46361-fd3f-4707-aa38-c9529a91e4f7.JPG)

Bug 2 - when you select "Disable Hover/Focus Auto-Expand" on mouser over you can se brand name and menu label appear under the menu
![reopen](https://user-images.githubusercontent.com/1521856/149672532-4257b504-7b33-474d-9344-00c56c1803fc.JPG)

_Originally posted by @consigli in https://github.com/ColorlibHQ/AdminLTE/discussions/3943#discussioncomment-1979060_

**Comment by consigli** [comment]
@REJack the bug is related to v3.2.0 version. thanks

**Comment by REJack** [comment]
Fixed with f88d61cbc60bfc526d3dff2cbaca293411370ad8 😄
