### ISSUE TITLE
[FEATURE] User Account Dropdown

### ISSUE THREAD

**Issue by kenprogrammer** [ColorlibHQ/AdminLTE#4225]
Why was user account dropdown at the right top corner removed?

**Comment by chungnd10** [comment]
It's odd, don't understand why leave it out when it's used so often.

**Comment by codenannu** [comment]
@kenprogrammer  You can find
https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html

**Comment by codenannu** [comment]
> It's odd, don't understand why leave it out when it's used so often.

You can find
https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html

**Comment by codenannu** [comment]
> It's odd, don't understand why leave it out when it's used so often.

You can find
https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html

**Comment by kenprogrammer** [comment]
> @kenprogrammer You can find https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html



> @kenprogrammer You can find https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html

Thanks

**Comment by myziel** [comment]
i can't connect data base?? is there any solution

**Comment by craph** [comment]
@kenprogrammer did you solve your issue ? If yes, I think this issue can be closed ?

**Comment by kenprogrammer** [comment]
Yes
