### ISSUE TITLE
[BUG] Problem with nested list in summernote

### ISSUE THREAD

**Issue by jdanign** [ColorlibHQ/AdminLTE#4232]
I've tried here also: https://summernote.org/
As soon as you start nesting, this fails.
I've moved the three selected lines and the two lines right above them have also been moved.
Only the selected ones should have a square and the two upper lines should keep the circle.

Here you have de information: [https://github.com/summernote/summernote/issues/4222](https://github.com/summernote/summernote/issues/4222)

**Comment by REJack** [comment]
I close this issue due you created the same issue on the summernote repo.
