### ISSUE TITLE
Refreshsing Bootstrap table on adding input in any field

### ISSUE THREAD

**Issue by SoftCodeOn** [ColorlibHQ/AdminLTE#4240]
We want to avoid refreshing on adding input in the field, and on the input, pagination begins from start. We need to fix it, please.

**Comment by REJack** [comment]
Please use the Issue Template "Bug report for AdminLTE v3.x", and add steps to reproduce!

**Comment by SoftCodeOn** [comment]
Thank you, Jack for your contribution. Actually, We are using AdminLTE v3. It's connected to our database. The problem is we've created a table with input elements when we add something (HELLO) in input fields, for adding (HELLO) in the database the table will completely refresh for this purpose.  Is there any way to stop refreshing the table and adding input to our database? 

Another one is pagination. 
You may check pagination when we click like click on tab 3 it should be an active state but when I refresh or table refresh it's comes to 0. 
[https://adminlte.io/themes/dev/AdminLTE/pages/tables/data.html
](https://adminlte.io/themes/dev/AdminLTE/pages/tables/data.html
)

Kindly help us to activate pagination tab.

**Comment by REJack** [comment]
Do you use Datatables?

**Comment by SoftCodeOn** [comment]
Yes we are using Datatables

**Comment by SoftCodeOn** [comment]
No, I don't want inline edit. If is there a way by using Javascript or external CSS kindly tell us. Thank you

**Comment by REJack** [comment]
can you give me some screenshots or a video to understand your problem?

**Comment by SoftCodeOn** [comment]
Yes of course.

**Comment by SoftCodeOn** [comment]
Kindly see this video, https://drive.google.com/file/d/1oweueV5itFC2zATcVpGUv-IsLkYnMCwH/

When I have removed something from the input field like, after removing you have to see the table was refreshed, when I added text again in input field it's again refreshed. I don't need to refresh I want to save my input text without refreshing the table. Also, You may watch when I removed text from pagination tab 3 after removing it comes to tab 1.

**Comment by REJack** [comment]
Oh that's a question for the DataTables forum, sadly I didn't tried something like this :/ But it's a kind of InlineEditing so may DataTables Editor is a option for you.

**Comment by SoftCodeOn** [comment]
Can we active the pagination tab by using CSS or JS?
