### ISSUE TITLE
Pagination should active on page refresh

### ISSUE THREAD

**Issue by SoftCodeOn** [ColorlibHQ/AdminLTE#4241]
I am using the Admin LTE theme I have a problem with its datatable. I want to pagination tab active even on page refresh, can you please help me with this.
image may clear to know my problem.

https://i.ibb.co/gyVLLRw/prob.png

**Comment by REJack** [comment]
1. Thats a bug for AdminLTE v3 not v4.
2. Like wrote it on your other Issue (#4240), we not developed DataTables we use it only that's why I wrote that's a question for the DataTables forum.

**Comment by SoftCodeOn** [comment]
Okay
