### ISSUE TITLE
sidebar-collapse being overriden on load

### ISSUE THREAD

**Issue by cytech** [ColorlibHQ/AdminLTE#4259]
` <body class="layout-fixed sidebar-collapse">`
after page load sidebar starts out collapsed but then toggles open
something in pushmenu isopening() ?? overriding after load

compiled latest v4-dev

**Comment by danny007in** [comment]
Give some more details regarding to issue like code, images, video to solve issue

**Comment by cytech** [comment]
v4-dev (latest)
npm install
gulp compile
edit dist/index.html  and add sidebar-collapse to body
```
 <body class="layout-fixed sidebar-collapse">
    <div class="wrapper">
      <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-light">
```


https://user-images.githubusercontent.com/7809634/155884615-21e628b1-0073-44df-b4da-9554960ea357.mp4

**Comment by lenamtl** [comment]
There is a similar issue when we refresh the page we see the menu scrollbar flashing
refresh the page and check the menu scrollbar
https://adminlte4.gatner.be/index.html

**Comment by cytech** [comment]
follow up
caused by Pushmenu->
addSidebaBreakPoint() calling expand()
expand is removing bodyClass  CLASS_NAME_SIDEBAR_COLLAPSE
--
PR #4131 seems to correct this while also allowing for the state to be remembered

**Comment by danny007in** [comment]
is this issue still exist ?
