### ISSUE TITLE
[BUG] Chart JS don't show on my web browser

### ISSUE THREAD

**Issue by alexandre-1992** [ColorlibHQ/AdminLTE#4274]
Hi,

I copie the source code of Char JS and past it in my Laravel8 Project.
but When I got in my web browsers I see my chart JS like that

![image](https://user-images.githubusercontent.com/58185779/154076192-000d67e2-cbe2-46d4-b1c2-a5a10fdd1271.png)

But I want it's be like that 

<img width="444" alt="image" src="https://user-images.githubusercontent.com/58185779/154097013-001aa8ec-1be2-44e7-99e6-924ebb2d3afe.png">

My code in my app.js is:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/58185779/154097459-f76a73ae-3636-43cb-b558-30cb212e5ce2.png">

My code in my web pack.mix.js
<img width="457" alt="image" src="https://user-images.githubusercontent.com/58185779/154098031-ddd06649-1f45-4e55-bbd2-9197087aff14.png">

And my package.json
<img width="395" alt="image" src="https://user-images.githubusercontent.com/58185779/154098364-b8139710-937f-4030-b231-a1bc6929a66b.png">

I don't know where is wrong can you help please?

Regards

**Environment (please complete the following information):**
- AdminLTE Version: v3.1.0
- Operating System:  windows 10 & ubuntu 20.04
- Browser (Version): Microsoft Edge & Chrome (Latest)

**Comment by REJack** [comment]
Sadly we can't give support for ChartJS, ask your question at the ChartJS repo.
