### ISSUE TITLE
Looking for imageonline.co

### ISSUE THREAD

**Issue by harrygrower** [ColorlibHQ/AdminLTE#4303]
I have looked at the online application “text to image” generator. (https://addtext.imageonline.co/)   The email address - admin@imageonline.co - fails.    You are listed as a contributor., so I wondered if you could help in getting in touch with imageonline.co . Otherwise, are you able to help with my original query which is as follows:

Do you have a version that allows the text to be bulk added to multiple images. I would like to create a text file which I could then use to place text on each image. So for example, if I had a number of images I was reviewing, I could create the text file and then use this as the data to be placed on each image as appropriate.

Many thanks 

Barry Gower
GAIN - Gift Aid Consultants
51 Love Lane
Pinner
HA5 3EY

Tel  07910391653
[bg@gain.me.uk](https://github.com/ColorlibHQ/AdminLTE/issues/bg@gain.me.uk)
www.gain.me.uk  
@GAINGIFTAID

**Comment by REJack** [comment]
We are not contributors of imageonline.co, it uses only AdminLTE.
May you can download and modify the script to your needs, its only client side.
