### ISSUE TITLE
[BUG] Slidebar on the left side does not work

### ISSUE THREAD

**Issue by eerison** [ColorlibHQ/AdminLTE#4304]
**Slidebar on the left side does not work**

**Screenshots**
<img width="1225" alt="Screenshot 2022-03-03 at 16 16 59" src="https://user-images.githubusercontent.com/6358755/156595025-a4bfb2ed-741c-4229-8543-8ce67e63a768.png">

**Environment (please complete the following information):**
- AdminLTE Version: v3.2
- Browser (Version): Chrome (Latest)

For some reason this dropdown menu does not work, I tried to copy the whole wrapper div, that I got from [adminlte demo](https://adminlte.io/themes/v3/), and copy all `css` and `js` from headers, but it doesn't work at all, I don't know what I'm missing

**Comment by REJack** [comment]
You shouldn't use the css/js files from our page, that's not a CDN use them from https://www.jsdelivr.com/package/npm/admin-lte. After you use the CDN files, checkout the console for errors.

**Comment by eerison** [comment]
> You shouldn't use the css/js files from our page, that's not a CDN use them from https://www.jsdelivr.com/package/npm/admin-lte. After you use the CDN files, checkout the console for errors.

Hey @REJack , Yeah I know that  I shouldn't use this css/js from admin demo, I was just trying to identify what exactly is the problem for this dropdown doesn't work!

I tested with cdn (https://cdn.jsdelivr.net/npm/admin-lte@3.2.0/dist/js/adminlte.min.js) but it doesn't work too!

what is necessary to this drop down work?

**Comment by REJack** [comment]
checkout the blank.html there are all minium required files loaded, at least you need jquery js, bootstrap js and adminlte css/js and for the fixed sidebar(scollable sidebar) you need scrollbarOverlays.

**Comment by eerison** [comment]
> checkout the blank.html there are all minium required files loaded, at least you need jquery js, bootstrap js and adminlte css/js and for the fixed sidebar(scollable sidebar) you need scrollbarOverlays.

I'll test that :)

**Comment by eerison** [comment]
Ok, I can finish this issue!

it's more a question then a bug, if something doesn't work I can use this issue: #2542


Thanks for your support :)
