### ISSUE TITLE
[bug] Sidebar Content overlaps and for vertical scrollbar

### ISSUE THREAD

**Issue by VeillaultAdrien** [ColorlibHQ/AdminLTE#4344]
Hello ! I have the exact same issue. My jquery is up to date (3.6.0). I use Bootstrap 4.6, poppers 1.16.1. 
I have the issue with my code and the demo code. 
Does sliderbar use some others dependencies that my be outdated ?

Or how can I edit myself the animation ?

### Discussed in https://github.com/ColorlibHQ/AdminLTE/discussions/3514

<div type='discussions-op-text'>

<sup>Originally posted by **noblemfd** March 16, 2021</sup>
I am using admin-LTE v3. I tried to use multi-level menu sidebar

I have something like this:

    `<ul class="nav nav-treeview">
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="far fa-dot-circle nav-icon"></i>
                  <p>
                  {{ trans('global.leave') }}: Line Manager
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Annual Leave Analysis</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Leave Types</p>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="far fa-dot-circle nav-icon"></i>
                  <p>
                  {{ trans('global.leave') }}: HOD
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Hist. Statistics: Applied</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Departmental Statistics</p>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>`

Originally, it appears like this:

![multilevel1](https://user-images.githubusercontent.com/34077129/111285270-40050880-8641-11eb-8dcf-60acba122eb3.PNG)

As I click on any of the menus, it displays. But when I tried to click on the same menu or other menu below it, everything got distorted and overlaps. It even for short/small horizontal scroll-bar

![multilevel_error](https://user-images.githubusercontent.com/34077129/111285785-cd485d00-8641-11eb-8c1b-18755e2d34b8.PNG)

How do I resolve this?

Thanks</div>

**Comment by VeillaultAdrien** [comment]
The slideup animation doesn't work like it supposes to do. It didn't hide the element, just reduce the height

**Comment by REJack** [comment]
That's a common bug from jQuery, make sure you use the latest jQuery version.

**Comment by VeillaultAdrien** [comment]
I found a solution. It was a overflow issue. Neither adminLte nor Jquery put the overflow:hidden property on the menu element.
