### ISSUE TITLE
[FEATURE] Icon Picker

### ISSUE THREAD

**Issue by cod3rshotout** [ColorlibHQ/AdminLTE#4372]
Would be great to integrate an icon picker component like this https://github.com/furcan/IconPicker what do you think about it?

**Comment by ddevsr** [comment]
Icon Picker using **Font Awesome**, in AdminLTE available to use.

**Comment by cod3rshotout** [comment]
> 

Where? I can't find any demo on the site

**Comment by ddevsr** [comment]
Just use from `plugins/fontawesome-free/css/all.min.css`.

**Comment by lenamtl** [comment]
Icon picker is just a form widget this can be a nice to have and easy to add to any existing template.

There are a few github scripts most are very old...
I saw this one (not english) that may worth a try.
https://github.com/FriendsOfREDAXO/fa_iconpicker

For now we need go get at least the basic theme itsefl as it is still not ready yet ...
