### ISSUE TITLE
Como abrir pagina em fullscreen?

### ISSUE THREAD

**Issue by Vagner2022** [ColorlibHQ/AdminLTE#4395]
Olá pessoal, como abrir a pagina em fullscreen automaticamente.

igual quando clicamos.
<a class="nav-link" data-widget="fullscreen" href="#" role="button">
  <i class="fas fa-expand-arrows-alt"></i>
</a>

**Comment by REJack** [comment]
1. Please write your issue in english
2. You need to create a custom script for this
