### ISSUE TITLE
V4 console error

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4408]
On dashboard 3 page
There is an error in the console
Failed to load resource: the server responded with a status of 404 (Not Found) : dashboard3.js
https://adminlte4.gatner.be/index3.html

**Comment by burdittw** [comment]
In the source of index3.html just remove or rem out the line <script src="./assets/js/dashboard3.js"></script> and the error will go away. The script code below it is what was in that js file that was used on the AdminLTE 3 demo.

This is just some clean-up that needs to take place.
