### ISSUE TITLE
Upgrade CKeditor in AdminLTE 2

### ISSUE THREAD

**Issue by arienclaij** [ColorlibHQ/AdminLTE#4445]
Hello,

I've yet Admin LTE 2, and i'm curious what are the steps to update Ckeditor to the newest version in it's version 4 branch.
Now i have version 4.8.0, but the latest version of AdminLTE2 is in the demo is 4.12.1

How can i update them? I tought that **composer update** was working. But the version of it is still 4.8.0.

Anyone an idea?

**Comment by arienclaij** [comment]
I've figured out that i still get version 2.4.3 by composer?
**composer require "almasaeed2010/adminlte=~2.4"**

Why i don't get 2.4.18?

**Comment by REJack** [comment]
AdminLTE v2 isn't maintained since 2+ years.
