### ISSUE TITLE
Composer gives not the newest version

### ISSUE THREAD

**Issue by arienclaij** [ColorlibHQ/AdminLTE#4447]
Hello, 

I've yet Admin LTE 2, some day i will upgrade, but now is it as it is. 

I've figured out that i still get version 2.4.3 by composer?
composer require "almasaeed2010/adminlte=~2.4" 

Why i don't get 2.4.18? 

I am aware that development support is gone, but this is about using it via composer.  Closing a topic just doesn't seem right to me. So hope for your kindness to give the answer without closing the topic. 

I am friendly, so I expect kindness in return.  😉

**Comment by REJack** [comment]
AdminLTE v2 isn't maintained since 2+ years.

**Comment by arienclaij** [comment]
I know, but my question is why i get not the newest version?

**Comment by REJack** [comment]
Idk I not created composer, may you can set the specific version in your composer.json to fetch the newest version. 
NPM is in my opinion the best way but I not know if there you would get the newest version, give it a try.

**Comment by arienclaij** [comment]
I will try. Thnx in advance! 👍

**Comment by Scemist** [comment]
You can run `composer update` to change the composer.json version.

If doesn't work, you are probably using a no more maintained package, run `composer require "almasaeed2010/adminlte=~3.2" and remove the older package.

**Comment by craph** [comment]
@arienclaij did you solve your issue ?
