### ISSUE TITLE
[BUG] Columns not taking full height of row.

### ISSUE THREAD

**Issue by k4deng** [ColorlibHQ/AdminLTE#4454]
**Describe the bug**
I'm seeing that there are weird spacings between columns in a row making some pages look weird.

**To Reproduce**
You can view this issue on [this page](https://adminlte.io/themes/v3/pages/UI/general.html) well.

**Expected behavior**
Columns should take the whole row height and look uniform and even.

**Screenshots**
![image](https://user-images.githubusercontent.com/70725766/167718894-df8ba2f3-f4c0-4eaf-a1c0-c43973a04831.png)
![image](https://user-images.githubusercontent.com/70725766/167719069-6d736309-cfae-4c75-8914-f26c8bff1970.png)

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.0
- Operating System:  Windows
- Browser (Version): Firefox (100.0)-(Latest)

**Comment by lenamtl** [comment]
Hi,

You can use flex and flex-fill for this.
http://jsfiddle.net/lenamtl/5j0nfbdo/

**Comment by craph** [comment]
Hello @k4deng,

I don't think this behavior is a "bug".
This display is due to the flexibility of the component.
The size is based on the content of the component.

As mention @lenamtl , you can use `flex` and `flex-fill` to have want you want.
If it's ok, I think you can close your issue 😃
