### ISSUE TITLE
[BUG] "Tab is Loading" in Iframe feature will flash twice when I click the leftside bar item

### ISSUE THREAD

**Issue by Dieber** [ColorlibHQ/AdminLTE#4455]
**Describe the bug**
"Tab is Loading" in Iframe feature will flash twice when I click the leftside bar item

**To Reproduce**

1. Go to  https://adminlte.io/themes/v3/iframe.html
2. Click on dashboard v1
3. Click on dashboard v2
4. See error: "Tab is Loading" will flash twice before "the dashboard v2" loading complete, which will effect the user experience.

**Expected behavior**
Tab is Loading show once and Don't flash.

**Environment (please complete the following information):**
- AdminLTE Version: v3.0.0
- Operating System:  macOS
- Browser (Version): Chrome (Latest)

**Comment by resslinger** [comment]
@Dieber Please try to update AdminLTE.

**Comment by REJack** [comment]
Fixed with 75deb497b39c1a8547fe0f21a2478b066b223396

It would be nice if you can test the changes, but you will need to generate the new dist files.

**Comment by hryan49** [comment]
Tested this change and it is not working. @REJack

**Comment by hryan49** [comment]
iframe src is also called twice which may be root cause

**Comment by hryan49** [comment]
Confirmed working.
