### ISSUE TITLE
[BUGS] Here are a few things that I have found so far...

### ISSUE THREAD

**Issue by burdittw** [ColorlibHQ/AdminLTE#4487]
I started porting over to the new 4.x as I need to go all Bootstrap 5 for a new project.  Doing so I have found some things that don't work like they did or new things that I have seen looking a little weird.

1)  The top nav menu and the footer used to stick or be fixed to the top and bottom respectively. They now scroll with the page and I do not see any way to change them. The body tag contains the "layout-fixed" so I would assume they should be fixed and not moving with the page.

<p><del>
2)  The sidenav seem to have their own scroll bars now. Odd thing I am seeing is that now I get scrollbars for top to bottom and left to right. I only have 6 items so not sure why I would have the scroll bars going both ways. The left to right one is the one that gets me as it allows me to scroll, but their is no text long enough to make it scroll that way.</del>
(This is not an issue, I found that I double tagged the sidebar class.)
</p>

3) The user profile dropdown is nice by the way and I like this change from v3. <del>The issue I have ran into is if the name is to long (try 37 characters like mine is displaying) some things go wonky. The sidenav must be shifting its height as it shifts upwards and the branding logo moves up and crops the top.</del> (This was caused by my problem in issue 2.) The name also goes outside of the box as the box seems to be fixed width and not able to present the whole name correctly as it runs off the page. The section of text that says "Member since" gets shoved downward but again the dropdown does not change size to adjust for the extra space needed.

This is my first 48 hours playing with it and some of the things I have found so far. I am glad I found the bootstrap 5 version as I was starting to look at other admin dashboards but did not like them as much as this one.

**Comment by danny007in** [comment]
Give some more details regarding to issue like code, images, video to solve issue

**Comment by burdittw** [comment]
![AdminLTE-v4-User-Profile-Long-Name-with-spaces](https://user-images.githubusercontent.com/10444699/172073321-7a713d08-c632-46eb-9141-703f4e7d0237.png)
![AdminLTE-v4-User-Profile-Long-Name-with-periods](https://user-images.githubusercontent.com/10444699/172073322-19b663d2-c95a-4ce0-8556-23024c0053bf.png)
![AdminLTE-v4-User-Profile-Long-Name-shifts-banding-logo](https://user-images.githubusercontent.com/10444699/172073325-058e5ec1-a0e2-4338-8017-63bcfb53c488.png)

1) The first image is with a long name using spaces in-between the names.
2) The second image is the same long name with periods instead of spaces in-between the names.
3) The third picture is the long name showing the branding section pushed up.

If the name is long and the text wraps down the 'Member since" text gets pushed down on the bottom border of the blue background section.

The second image with the long name and periods is because the U.S. government uses smart cards for authentication and the user names on the certificate display as lastname.middlename.suffix.firstname.10-digit-identifier. Now one could break it up and do other things with it but most systems assign that value to the user name according to the X509Certificate2 specifications. Thus a very long display name.

When the name is long and runs off the user profile right side in the overflow it seems to be pushing the grid-area off as well as it goes off the screen currently with you not having the two other buttons working yet. I have been testing with the extra buttons showing and the branding logo issue is not moving up if there is extra space. But in the current version from your site the extra space is not there and goes offscreen. Once this happens the sidebar is shifting up and the branding logo gets cropped at the top.

Hope this helps and makes sense.

**Comment by burdittw** [comment]
I forgot about the header and the footer. I have found using the bootstrap 5 "fixed-top" and "fixed-bottom" make them stick as intended to the top and bottom respectively. I am not sure if the "position-fixed" means the header and footer should be fixed to the view screen area with no movement on scrolling or if it means fixed as in they always show on the top and bottom even when scrolling. If this is the intended outcome then there is no bug and I need to add the tags to the header and footer.

**Comment by danny007in** [comment]
@burdittw  does this issue still exist

**Comment by danny007in** [comment]
fixed in https://github.com/ColorlibHQ/AdminLTE/commit/2cc31e1ce2e29e26fe7a0df021485b2dd8081795

if still exist please reply

**Comment by burdittw** [comment]
The issue still exists and I have verified that I have merged the code base linked above and I do.

![user-profile-dropdown-issue](https://user-images.githubusercontent.com/10444699/216880368-f60d9d45-d6f3-4dc6-be6b-1a9687bd0094.png)

**Comment by danny007in** [comment]
fixed in https://github.com/ColorlibHQ/AdminLTE/commit/a5a1463237a2dffef5cf833e26b5891aaec7df55

**Comment by burdittw** [comment]
It looks like it has been fixed now.

![user-profile-dropdown-issue](https://user-images.githubusercontent.com/10444699/217116340-c6600a99-ad17-44ab-97b6-9820127bacec.png)
