### ISSUE TITLE
[Question] How to upgrade dash_admin_components in python dash?

### ISSUE THREAD

**Issue by hjp0712** [ColorlibHQ/AdminLTE#4508]
Hi, I have a question.

I use python dash including dash_admin_components package.

https://github.com/dawidkopczyk/dash-admin-components

But this package's last updated is 3 years ago.

I know latest adminLte version is in 2021.

How can I use latest version of dash_admin_components?

or can I use AdminLTE3 for UI on dash? If Possible, How can I convert or config?

please help

**Comment by REJack** [comment]
Ask the repo owner, we have no connection to the package.
