### ISSUE TITLE
[BUG] color and size are not selectable

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4516]
Hi,

I'm not sure if this was supposed to be selectable or not but this is not selectable.

https://adminlte.io/themes/v3/pages/examples/e-commerce.html
Available Colors and size are not selectable
Selection is not working, we can click on it but it does not stay selected.

**Comment by REJack** [comment]
There was never a script for this, it's only a template without JS.

**Comment by lenamtl** [comment]
Ok no problem
