### ISSUE TITLE
[BUG] Random issue when clicking on button

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4527]
Hi,

Go to https://adminlte.io/themes/v3/index.html
Go to sales box, click on **Donut** button click on **Area** button 
randomly the click is not triggering or not clicking so we have to click a second time or a third time on the button
No JS error into the console.

https://user-images.githubusercontent.com/2241324/176235840-32f2165c-23dd-41ed-b1ae-0bef7c368626.mp4

Note: I have encounter this issue elsewhere (menu and toggle) but I don't recall where exactly, I will do more test and let you know.

**Comment by REJack** [comment]
That isn't a bug due AdminLTE, this happens only if you enter the drag event and after it's finished you can click again.

**Comment by lenamtl** [comment]
I have encounter this same issue on menu item and toggle.
I don't know about the drag item event I'm just testing the page the way it is coded without draging the item.
And sometimes it occured on page load.
So page load I click on donut and nothing happen.

**Comment by lenamtl** [comment]
@danny007in There is no reason to uninstall Chrome for this and this also happening on Opera.

**Comment by REJack** [comment]
It's not chrome itself :D I can replicate it with firefox too

**Comment by REJack** [comment]
I will check it in the next days, but I guess it's caused by bootstrap's own JS. I can only barly reproduce it, almost 1 of 50 clicks it happens.

**Comment by lenamtl** [comment]
Any news?

In my case this occurred often ie 5 cliks but the problem is if it happen on the first click the user will think the button it is not working, and we don't want this.

**Comment by REJack** [comment]
I've tested it on various machines/OSes. I think we would need a dedicated drag-button instead of using the card header for it, that could be the fix for it, simple and easy 😉

**Comment by lenamtl** [comment]
Ok I see, this make sense, thanks
