### ISSUE TITLE
[BUG] Footer issue when image not found

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4529]
Hi,

I saw an issue with the footer when image is not found.
The placeholder may not be displayed because of the limit reached which is normal but because of this this break the footer and footer is not displayed correctly as the image is just and href this should not affect the way the footer display.

Goto https://adminlte.io/themes/v3/pages/examples/profile.html

**Comment by REJack** [comment]
That glitch comes from the browser, the AdminLTE script doesn't run till end due waiting for the image. That can be fixed with defer-/async-loading the script.
