### ISSUE TITLE
[Question]Does Fastclick still required nowadays

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4564]
Does Fastclick still required nowadays for v3 or v4?

**Comment by lenamtl** [comment]
So this should be removed on v3 and v4

**Comment by REJack** [comment]
It's only added as plugin, but it's not used anymore. I can remove it for the next release.

**Comment by REJack** [comment]
removed with 8df00a62466ffb9865855ec3e3243c9492b555e0
