### ISSUE TITLE
iframe in adminLTE v4.x

### ISSUE THREAD

**Issue by zxo102** [ColorlibHQ/AdminLTE#4580]
I would like to use iframe in adminLTE v4.x.  Are there any examples like iframe.html and iframe-dark.html in adminLTE v3?

Thanks a lot.

**Comment by zxo102** [comment]
lenamtl:  In my "old" project, a request page and a response page are in two iframes.  :)

**Comment by danny007in** [comment]
for iframe feature, contributors can create separate plugins, because it difficult to maintain in single repo
