### ISSUE TITLE
[FEATURE] data-lte-toggle to data-bs-toggle

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4590]
Hi,

I think the **data-lte-toggle** should be renamed to **data-bs-toggle** to be more uniform  
https://getbootstrap.com/docs/5.0/components/collapse/#example

**Comment by danny007in** [comment]
bs means bootstrap
lte means adminlte

**Comment by REJack** [comment]
I would not rename it to `bs`, since bootstrap doesn't provides the scripts for it 😄
