### ISSUE TITLE
Minimal custom scss being ignored?

### ISSUE THREAD

**Issue by cryo75** [ColorlibHQ/AdminLTE#4625]
I created a custom scss file as an example to see if the variable overrides are working:

```
$body-bg: #F000FF;
$main-bg: #0000FF;
$dark-main-bg: #FF0000;
$sidebar-dark-bg: #00FF00;
$enable-dark-mode: false;

@import '../_adminlte/node_modules/bootstrap/scss/bootstrap';
@import '../_adminlte/build/scss/adminlte.raw';
```

The css file gets generated and it's being linked in the main html file, where I have for example:

```
<aside class="main-sidebar sidebar-dark-primary elevation-4">
</aside>
```

However, no colors are being changed. The overrides I'm doing are just not taking affect. What am I missing?

**Comment by REJack** [comment]
I close this issue due inactivity.
