### ISSUE TITLE
[BUG] move the sidebar from left to right

### ISSUE THREAD

**Issue by siraj83** [ColorlibHQ/AdminLTE#4669]
**Describe the bug**

When I trying to move the sidebar from left to right, 

I just add style on <aside class="main-sidebar sidebar-dark-primary elevation-4 " style=" right: 0px !important;left: auto;">

I faced an issue that
the responsive with small size (mobile) doesn't work, the sidebar doesn't disappear.

So I need the right way to do it.

**Screenshots**

![Image 2](https://user-images.githubusercontent.com/49902894/186926785-64b32e32-ac24-489e-9fb1-4f1a15c66808.jpg)
![Image 1](https://user-images.githubusercontent.com/49902894/186926797-b440b2b9-f493-4e42-95b3-7383b1f77a0f.jpg)

**Environment**
- AdminLTE Version: v3
- Operating System:  Win 10
- Browser (Version): Chrome

**Comment by dfsmania** [comment]
I think `RTL` will be only supported on the incoming **AdminLTE v4**, check [closed issues](https://github.com/ColorlibHQ/AdminLTE/issues?q=is%3Aissue+is%3Aclosed+RTL) for more infomation...

**Comment by REJack** [comment]
Yep, AdminLTE v3 has not RTL support, for this you would need to look if someone reworked it for RTL.
