### ISSUE TITLE
Admin LTE (Dropzone.js) Not Working 

### ISSUE THREAD

**Issue by eyupfidan** [ColorlibHQ/AdminLTE#4680]
file upload in this link is not working

https://adminlte.io/themes/v3/pages/forms/advanced.html

screenshot 

https://prnt.sc/g1CTvAQCE4K3

**Comment by REJack** [comment]
We not deliver any php scripts, you need to get a server-side implementation example from [Dropzone.js' Docs](https://docs.dropzone.dev/getting-started/setup/server-side-implementation)
