### ISSUE TITLE
No scroll bar on the right side of the page

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#4689]
As I click on the Menu to display a page content, I observed that there's no scroll-bar on the right side. And this makes some content to be hidden. 

I am unable to see the lower part of the page.

In addition, the left side bar too is not having scrolbar too

**Screenshots**
![tight-page](https://user-images.githubusercontent.com/34077129/189053782-c82bb392-3ee5-410c-8fde-a789ff11c4b0.png)

**Environment (please complete the following information):**
- AdminLTE Version: [v3.2.0]
- Operating System:  [Windows 11]
- Browser (Version): [Chrome (Latest)]

.

**Comment by REJack** [comment]
Please provide example code or an demonlink.

**Comment by REJack** [comment]
I close this issue due inactivity.
