### ISSUE TITLE
[Issue] build scss 

### ISSUE THREAD

**Issue by Rhemi008** [ColorlibHQ/AdminLTE#4690]
**Describe the bug**
I am new to scss but i tried to compile the existing code in the build. and i am always having this error.

![image](https://user-images.githubusercontent.com/90092695/189191826-f427f214-e8d8-4c4f-b112-952997a3c5f0.png)

i already did the following steps to setup

1.) installed node-v18.8.0-x64
2.) opened cmd in admin and run the following command on AdminLTE-3.2.0
     - when i run npm install, npm i bootstrap@4.6.0 or  npm install bootstrap-scss@4.6.2 i get the following 
        
![image](https://user-images.githubusercontent.com/90092695/189191211-13327b60-ed9c-4602-b4d6-61d1ab653446.png)

3.) Then tried to compile it using the visual studio code by using the SASS live compilation

**To Reproduce**

**Expected behavior**
If possible could you guide me if i missed on installing something or configuring a file? or wrong path? any help would be deeply appreciated i already tried searching in here but could not get what was the solution 

I wanted to compile it again because i am planning to add a new color.

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version:  v3.2
- Operating System:  Windows 10
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by Rhemi008** [comment]
was able to fix it. tnx

**Comment by jomo-samah95** [comment]
@Rhemi008 I got the same issue and now I'm stuck. How did you fix it? mind to share a detail solution. will be much appreciated. thanks
