### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Strelix** [ColorlibHQ/AdminLTE#4699]
Would this theme be only for an administrative panel, or would it be okay as a normal website theme aswell?

By the look of it, it's suggested to be used as an admin overview, and i'm not sure what to use as a **main customer front page**. Any suggestions whether to use this or use another theme?

**Comment by Strelix** [comment]
Also apologies if this is the wrong section, i couldnt find anywhere else

**Comment by REJack** [comment]
Some of the users use it also for websites instead of panels only. Mostly boxed without sidebar 🤣
