### ISSUE TITLE
data-card widget not working from CDN 

### ISSUE THREAD

**Issue by fschiro** [ColorlibHQ/AdminLTE#4709]
I'm using the CDN to install AdminLTE 3.2 in my app: 

```
<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
```

I noticed that card-minimization is not working for me:

```
<button type="button" class="btn btn-tool" data-card-widget="collapse">
  <i class="fas fa-minus"></i>
</button>
```

The Github homepage states: ```Important Note: You needed to add separately cdn links for plugins in your project.```, but I'm not seeing these data-card widgets in the plugins section. 

Should the data-card minimization work from the adminlte.min.js CDN or do I need a plugin? If so, which plugin? 

Note: I searched the raw code from the [CDN](https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js) for the word "collapse" and this came up: ```',C='[data-card-widget="collapse"]'``` so I believe I should not need any external plugins because it looks to be a part of ```adminlte.min.js```. But, yeah it is not working for me. 

Thanks!

**Comment by REJack** [comment]
Card widget comes from adminlte(.min).js, thats not a 3rd-Party plugin. Also did you loaded jquery and bootstrap before adminlte in your HTML?

**Comment by fschiro** [comment]
Ah, no, I added bootstrap/jquery immediately after admin LTE. Is that why it did not work? I ended up using bootstrap cards directly.

**Comment by REJack** [comment]
AdminLTE requires both so you should load them before and not after AdminLTE.

**Comment by REJack** [comment]
I close this issue due inactivity.
