### ISSUE TITLE
[FEATURE] Add Bootstrap Toggle button

### ISSUE THREAD

**Issue by palcarazm** [ColorlibHQ/AdminLTE#4720]
**Is your feature request related to a problem? Please describe.**
AdminLTE v3.x had Bootstrap Switch component but was removed due to multiple bugs. There is a bootstrap plugin with the same main functionality with support for bootstrap 4 and bootstrap 5 (https://palcarazm.github.io/bootstrap5-toggle/)

**Describe the solution you'd like**
Include Bootstrap Toggle as a form component.

**Describe alternatives you've considered**

**Additional context**
Bootstrap toggle support main functionality of Bootstrap Switch, but also include:

- Tristate Toggle
- Navigation and switch with keyboard
- Support readonly attribute
- Custom form submit values for on and off state

Docs: https://palcarazm.github.io/bootstrap5-toggle/

**Comment by danny007in** [comment]
please use cdn https://www.jsdelivr.com/package/npm/bootstrap5-toggle?nav=config
