### ISSUE TITLE
Adminlte menu not working after redirection VUE3

### ISSUE THREAD

**Issue by ezekel** [ColorlibHQ/AdminLTE#4735]
Hi , 

Can I ask some help please, I'm using adminlte-3.2.0 and vue3, after I logging in to my app it will redirect me to my homepage, when I clck the menu it will not open but when I refresh the page it works fine I can open now the menu. this is how I imported it to my index.html

ex:
```
    <link href="../../plugins/fontawesome-free/css/all.min.css" rel="stylesheet">
    <!-- daterange picker -->
    <link href="../../plugins/daterangepicker/daterangepicker.css" rel="stylesheet">
    <!-- iCheck for checkboxes and radio inputs -->
    <link href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet">
 // some css import here ...
    <link href="../../dist/css/adminlte.min.css" rel="stylesheet">

```
and js above the closing tag of the body

```
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

// some js import here
<!-- AdminLTE App -->

<script src="../../dist/js/adminlte.min.js"></script>
```

I tried to put onMOunted(), but it did not work It will raise error to the console.

```
Uncaught TypeError: No method named "init"

```
```
onMounted(()=>{
$('[data-widget="treeview"]').Treeview('init').
)l
```

Thank you in advance

**Comment by amanf244** [comment]
Same problem

**Comment by REJack** [comment]
Simply run Treeview() without any argument.

**Comment by ezekel** [comment]
Hi @REJack 

Adding this on home.vue, it works after login the menu will work

```
onMounted(()=>{
  $('[data-widget="treeview"]').Treeview();

});
```

![image](https://user-images.githubusercontent.com/6830057/198823903-bfcf0dab-8cc4-41c8-b49d-89827bc32c1c.png)

But now the problem is when I refresh the page, I get this error in console

![image](https://user-images.githubusercontent.com/6830057/198823842-4d96f202-9d4f-433d-8379-3f87eecf9b72.png)


Thank you in advance

**Comment by REJack** [comment]
Check if you init it with the arg anywhere, maybe its still cached or something else.

**Comment by ezekel** [comment]
Hi @REJack , 

I cannot find any more declaring the code `  $('[data-widget="treeview"]').Treeview();`,

**Comment by ImCreator2** [comment]
[#4339 ](https://github.com/ColorlibHQ/AdminLTE/issues/4339#issuecomment-1315497840)

I think there should be function on Treeview.js to stop the evenListeners. Something like.

```
_stopListeners() {
    const elementId = this._element.attr('id') !== undefined ? `#${this._element.attr('id')}` : ''
    $(document).on('click', `${elementId}${this._config.trigger}`, event => {
      event.stopImmediatePropagation();
    })
  }
```
Like 'init' call, there should be call to stop it when Vue component is unMounted.

```
_stop() {
this._stopListeners()
}
```

So that we can call it on Vue unMounted hook something similar to init call.

```
onUnmounted(() => {
$('[data-widget="treeview"]').Treeview('stop');
})
```

**Comment by ezekel** [comment]
> [#4339 ](https://github.com/ColorlibHQ/AdminLTE/issues/4339#issuecomment-1315497840)
> 
> I think there should be function on Treeview.js to stop the evenListeners. Something like.
> 
> ```
> _stopListeners() {
>     const elementId = this._element.attr('id') !== undefined ? `#${this._element.attr('id')}` : ''
>     $(document).on('click', `${elementId}${this._config.trigger}`, event => {
>       event.stopImmediatePropagation();
>     })
>   }
> ```
> 
> Like 'init' call, there should be call to stop it when Vue component is unMounted.
> 
> ```
> _stop() {
> this._stopListeners()
> }
> ```
> 
> So that we can call it on Vue unMounted hook something similar to init call.
> 
> ```
> onUnmounted(() => {
> $('[data-widget="treeview"]').Treeview('stop');
> })
> ```

This doesn't work my file Treeview.js don't have that listener what version adminlte you have ?

**Comment by ezekel** [comment]
Finally, I got it worked!

In my Login.vue

```
onMounted(()=>{
  $('[data-widget = "treeview"]').Treeview();
});
```

And to my Authenticated.vue

```
onUnmounted(() => {
  $(document).on('click','[data-widget="treeview"] .nav-link', function (e) {
    e.stopImmediatePropagation();
  });
})
```
