### ISSUE TITLE
[BUG] How can i buy adminlte license?

### ISSUE THREAD

**Issue by mohamadzoghbi** [ColorlibHQ/AdminLTE#4756]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.0.0]
- Operating System:  [e.g. macOS Catalina]
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by REJack** [comment]
Next time create only a Discussion, instead of Issue and Discussion.

https://github.com/ColorlibHQ/AdminLTE/discussions/4327#discussioncomment-2310177
