### ISSUE TITLE
After the sidebar is folded, an X axis draggable scroll bar will appear

### ISSUE THREAD

**Issue by 18682788952** [ColorlibHQ/AdminLTE#4767]
![image](https://user-images.githubusercontent.com/31786261/198832054-808c84d8-2360-4d36-b47a-a39323029053.png)
This experience is very bad

**Comment by REJack** [comment]
It looks like you use layout-fixed without overlayscrollbars

**Comment by 18682788952** [comment]
Yes, how can I solve it? Thank you very much

**Comment by FireDeveloper** [comment]
Include at the head `<link rel="stylesheet" href="lib/OverlayScrollbars.min.css"><!-- overlayScrollbars -->`
And at the end of the body `<script src="lib/jquery.overlayScrollbars.min.js"></script><!-- overlayScrollbars -->`

**Comment by REJack** [comment]
I close this issue due inactivity.
