### ISSUE TITLE
[BUG] Update fontawesome-free plugin to v6.2.0 

### ISSUE THREAD

**Issue by MiguelRadaza** [ColorlibHQ/AdminLTE#4777]
**Describe the bug**
The font awesome plugin is outdated, might be good to update the plugin to v6.2.0. Thank you!

**Comment by DRSDavidSoft** [comment]
I manually upgraded without any problems.

**Comment by REJack** [comment]
We will not update FontAwesome on AdminLTE 3.2, due thats the second Major Update since our version and also this can break stuff for other users. upgrade it manually if you want the new like @DRSDavidSoft wrote.
