### ISSUE TITLE
How to change Header Color and Sidebar Color

### ISSUE THREAD

**Issue by noblemfd** [ColorlibHQ/AdminLTE#4817]
In the AdminLte-v3.2.0, for the header I have

**Header:**

    <nav class="main-header navbar navbar-expand navbar-white navbar-light">

**Sidebar:**

    <aside class="main-sidebar sidebar-dark-primary elevation-4">

**Expected behavior**
However, I want to change the Header color from white to  **#E92123**  (I don't want navbar-danger)

and also the sidebar color from dark into  **#7B7979**

This is what I currently have
**Screenshots**

![adminlte_color](https://user-images.githubusercontent.com/34077129/205378654-5a62bae0-d917-4557-8d7e-09456bba6e1e.png)

**Environment (please complete the following information):**
- AdminLTE Version: [v3.2.0]

Thanks

**Comment by burdittw** [comment]
The top navbar is Bootstrap 3, so the best way would to be following the examples on the Bootstrap website:
[Bootstrap 3 Navbar Color Schemes](https://getbootstrap.com/docs/4.0/components/navbar/#color-schemes)

Best approach would be to make a class called like `.bg-custom` or `.bg-red` and set the background color to your hex value. In the end it would look like this after you make the class:
`<nav class="main-header navbar navbar-expand navbar-dark bg-custom">`
The `navbar-dark` makes the text light or dark, which is opposite of what you pick. `dark=light text` and `light=dark text`

As far as the sidebar goes, you would need to go through the css and find the code that has the `background-color` set. It looks like it is in multiple spots. In this case you would need to either change all the spots to your value or you could create new classes and change the `sidebar-dark-primary` to say `sidebar-dark-custom` or whatever you want. Depending on the color you use you may need to also change the text color.

Hope that helps get you started!

**Comment by REJack** [comment]
Simply check out the docs, like the [Layout](https://adminlte.io/docs/3.2/layout.html) page.
