### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by forxer** [ColorlibHQ/AdminLTE#4837]
I haven't seen any activity here from members for over 6 months.

Lots of tickets. Lots of pull requests.

No patch release. No beta.

Is there still someone who can give us information on the future of this project? Or should we consider it abandoned?

**Comment by doc-** [comment]
I know the feeling.
I also think this project is not maintained anymore.

I will probably go ahead with CoreUI within the next months if Colorlib no longer updates AdminLTE.

**Comment by burdittw** [comment]
They are on here occasionally, but the next version was put on hold until Bootstrap 5.3 is released. It will bring native dark mode with it, which will make a lot of the coding to upgrade the current AdminLTE 3 to 4 easier. I am hoping that now that the holiday season is over, that we see an uptick in this project. Need to remember that this is an open-source project and is free. Things move slower as people have real lives and jobs as well. I know I want a newer version of this project yesterday, but I can't get it. Being it is an open-source project, I started modifying the code to meet my needs so I could start building an application now using it and hopefully be able to update it later to an official release.

**Comment by forxer** [comment]
Thanks @danny007in for responding.
