### ISSUE TITLE
Connecting Login Page to User SQL Server

### ISSUE THREAD

**Issue by cwardTK** [ColorlibHQ/AdminLTE#4859]
I'm hoping someone will be able to chime in on my question, I can't seem to find documentation on how to connect the login page to a sql server so added users can log into the website. I'm using visual studio, asp.net, C#

**Comment by burdittw** [comment]
Are you doing an MVC, Razor Page, old ASP forms, ASP.NET Core?

Are you using the built-in identity framework for username and password or are you building your own?

Assuming you are using .NET Core and the built in identity framework, then you should already have the SQL tables and the default web pages working. If so, you need to add the scaffolding items for identity and select the Account\Login page as a minimum. This will put the page in a section called Areas -> Identity -> Pages -> Account with a Login.cshtm file. Then take the code from AdminLTE and work it into the page.

Here is a page that shows what I am talking about:
[Customize Login Page on ASP.NET Core Web Application](https://bluerhinolabs.medium.com/customize-login-page-on-asp-net-core-web-application-73cc9574da32)

**Comment by cwardTK** [comment]
Oh this is great! Thank you for the link :)
