### ISSUE TITLE
Remove annoying margin in `.nav-link`

### ISSUE THREAD

**Issue by DRSDavidSoft** [ColorlibHQ/AdminLTE#4869]
**Is your feature request related to a problem? Please describe.**
This behavior reminds me of the IE era where css support for `:hover` was limited on elements and devs would often apply a hack where the parent element of `a` tag would be styled rather than the `a` element itself.

This is fine and works until the user moves the cursor right outside of the `a` boundaries (while still within the parent boundaries) and this would result in a very annoying (and IMO unprofessional) behavior where the the link _appears_ to be hovered on, but clicking on it wouldn't do anything -- rightly so, because the pointer isn't _actually_ on the link element, but rather on some empty space in the parent.

Very confusing for the user.

And if you complained to the devs applying such dubious and (IMO cancerous) practices, they would just laugh and tell you to move the cursor further to the center of the link, then click on it. Woah! Genius idea!

Unfortunately, AdminLTE v4.0 utilizes the same practice by giving the parent `li` element in the sidebar the `:hover` attribute, instead of the more sane approach to give the child `a` element the `:hover` attribute.  Personally I don't see the reason, although it works -- right until the client moves the cursor to the bottom of the `a` item whilist still in the `li` item (this is because the `a` item has a `margin-bottom` of `.2rem` set).

**Describe the solution you'd like**
Please either _apply the `:hover` attribute directly to the `a` item_ (best practice), or make use of one of the _workarounds_ below:

1. Remove `margin-bottom` from the `a` link _and_ give it a `padding-bottom`; this is because unlink margin (which accounts for the space _outside_ the link, padding will account for space _inside_ the link and thus will make the link clickable)
2. Remove `margin-bottom` from the `a` link _and_ give it to the parent `li` element as there is no use for the `a` element to have this space; the same theory as above applies here as well (the space is now between the `li` items not `a` items themselves)

or you can make use of the [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) attribute to make sure the hover event isn't registered on the `li` item until the pointer is moved into the `a` item directly:

```css
.nav-sidebar .nav-item>.nav-link {
	pointer-events: all;
	margin: 0 !important
}

.nav-sidebar .nav-item {
	pointer-events: none;
	margin-bottom: .2rem
}
```

Here I made use of both the pointer events workaround and the second change described above.
**Describe alternatives you've considered**

**Additional context**
I'm really sorry to be bothering with you for a small thing like this, but it's super confusing for the end user and also mind-bogglingly annoying for me.

Here's a screen capture of the issue:

https://user-images.githubusercontent.com/4673812/212721675-6fa64bc4-30a7-4cbc-a925-0755007d2e28.mp4

❤️ Thanks for maintaining AdminLTE! 😄

**Comment by DRSDavidSoft** [comment]
P.S. the customer says the click is "sometimes" not working and to to "please fix this".  So I wrote the custom css above, but I figured it'd be better to be merged in the upstream repo as well.

**Comment by danny007in** [comment]
please check this https://adminlte.io/themes/v3/index.html

**Comment by DRSDavidSoft** [comment]
@danny007in Thanks for the response, in the latest version this issue is not present! ❤️ 

It seems the ideal fix was used as the hover effect is not actually on the `.nav-link` element instead of its container! 😄 🎉

### Screenshot:
![fixed_navlink](https://user-images.githubusercontent.com/4673812/215345977-4c9761dc-9358-47ae-a52b-64c35485ad06.png)
