### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rijwanansari** [ColorlibHQ/AdminLTE#4878]
**Bug Description**
Bug in index page load with alert message.

**To Reproduce**
1. Load index page

**Expected behavior**
No Alert message or error.

**Screenshots**
![image](https://user-images.githubusercontent.com/25387035/214765636-9ed4dab3-8f90-40f5-a0db-0942b08698d9.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.x. (latest version)
- Operating System: Windows OS
- Browser (Version): Chrome Latest, Edge

Kind Regards
Rijwan Ansari

**Comment by PrathyushaModala** [comment]
Hi @rijwanansari 
Can I work on this issue??

**Comment by REJack** [comment]
This is not an error or bug, this is intentional since it is a demo file.
