### ISSUE TITLE
Request for RTL layout support in AdminLTE v4.x

### ISSUE THREAD

**Issue by ronniengoda** [ColorlibHQ/AdminLTE#4896]
I am a user of the AdminLTE v3.2.0 and I would like to request for the addition of RTL (Right-to-Left) layout support.

Many languages, such as Arabic, Hebrew and Persian, are written from right to left and therefore it would be great if the framework could accommodate this layout as well. This would make it more accessible to a wider audience and provide more options for customization.

I understand that the current focus of the project may be on other features, however, I believe that this is a crucial feature for many users who are looking for an admin template that supports RTL languages.

Thank you for considering my request. I look forward to seeing this feature added in future releases.

**Labels:**

- enhancement
- feature request
- rtl

**Comment by muhanadali100** [comment]
AdminLTE V4 support RTL 

Because AdminLTE V4 use bootstrap v5 where support rtl automatically without any changes in css,js

AdminLTE V4 Release was delayed because Bootstrap V5.3 stable was not released yet and it's alpha

**Comment by ronniengoda** [comment]
Thanks for the update. I appreciate the work the team has done in making AdminLTE more accessible to a wider audience by incorporating the RTL support in Bootstrap v5.

I understand that the release of AdminLTE V4 has been delayed because the stable release of Bootstrap v5.3 is still pending. Thank you for the information. I look forward to the release of both AdminLTE V4 and Bootstrap v5.3.

Keep up the good work!
