### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by fvbatistoni** [ColorlibHQ/AdminLTE#5516]
Hello guys. I'm from Brazil and I need to make an upgrade to my admin site. I've always used AdminLTE, but now I want use a PRO (completely adapted to Bootstrap 5.x). Could you give me a discount??? It is very expensive to me $69.... Is there a discount coupon?????
I 've loved this one https://dashboardpack.com/theme-details/admindek-html/

**Comment by puikinsh** [comment]
Hello @fvbatistoni 

Unfortunately, there are currently no active discounts for Admindek.
