### ISSUE TITLE
[BUG] Dashboard hidden after loaded fully in asp.net .net 7 framework

### ISSUE THREAD

**Issue by VinoVinothKanth** [ColorlibHQ/AdminLTE#5582]
**Describe the bug**
 Dashboard hidden after loaded fully in asp.net .net 7 framework

**To Reproduce**
include the files in visual studio asp.net mvc project and run this template

**Expected behavior**
dont not hide the template

**Screenshots**
![image](https://github.com/ColorlibHQ/AdminLTE/assets/43906566/ca00e0cd-749d-4854-bb51-7da4bd03d832)

**Environment (please complete the following information):**
- AdminLTE Version: [e.g. v3.2.0]
- Operating System:  [e.g. Windows 10]
- Browser (Version): [e.g. Chrome (Latest)]

**Additional context**

**Comment by danny007in** [comment]
Download Latest Stable release of AdminLte [https://github.com/ColorlibHQ/AdminLTE/releases/latest](https://github.com/ColorlibHQ/AdminLTE/releases/latest) for bug free and new features

or 

use the latest browser like edge, chrome, Mozilla

or

check HTML code  properly compared with new version

**Comment by VinoVinothKanth** [comment]
ok. i will check.

**Comment by danny007in** [comment]
is this issue still exist ?

**Comment by VinoVinothKanth** [comment]
Now resolved. Thanks
