### ISSUE TITLE
Big css size

### ISSUE THREAD

**Issue by frenzymind** [ColorlibHQ/AdminLTE#5651]
Hello. We used admin-lte v2.4.18, and `adminlte.min.css` file was 306 kb. We change to version 3.2.0 and this file is **1.4 Mb** , why is that so huge? Am i miss some thing ?
Thanks!

**Comment by danny007in** [comment]
https://github.com/ColorlibHQ/AdminLTE/issues/3692 Please Check for AdminLTE v4 Release
