### ISSUE TITLE
[FEATURE] Could you help make AdminLTE work with CDN script imports?

### ISSUE THREAD

**Issue by krirk0137** [ColorlibHQ/AdminLTE#5755]
[FEATURE] Could you help make AdminLTE work with CDN script imports?
**Is your feature request related to a problem? Please describe.**
I'm using .cshtml with plain CSS, HTML, and JS, without using Node.js. I'd like to use AdminLTE as well. Thank you!"

**Describe the solution you'd like**
Example Like this Boostrap  CDN Import Script  File    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

**Describe alternatives you've considered**
i am not use Node.js T^T 

**Additional context**
thank you for help me

**Comment by danny007in** [comment]
@krirk0137 you can download from npm repo directly, please research on that its very simple 😃 .
