### ISSUE TITLE
v4.0.0.-beta3 release bootstrap version mismatch 

### ISSUE THREAD

**Issue by Raza9798** [ColorlibHQ/AdminLTE#5804]
v4.0.0.-beta3 release says it upgraded the bootstrap to version 5.3.3. but the version does not updated on `package.json`
![image](https://github.com/user-attachments/assets/17723a61-6fab-443c-850d-92ee47936701)

Following is the changes of the release
https://github.com/ColorlibHQ/AdminLTE/blob/7f31eacc792da7c4c23439287c443d1ed6ba0f16/package.json
![image](https://github.com/user-attachments/assets/f59b256d-fa53-4cb7-a4b7-6483c2014d74)

**Comment by danny007in** [comment]
@Raza9798 please check it, https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json
